rejoner	rejonarà	V;IND;SG;3;FUT
pronunzier	pronunzia	V;IND;SG;3;PRS;LGSPEC1
renunzier	renunziareis	V;IND;PL;2;FUT
ejaminer	ejamineia	V;NFIN;SG;2;LGSPEC2
furmer	furmasse	V;IPFV;SBJV;SG;1;PST
pronunzier	pronunziea	V;IND;SG;3;PRS;LGSPEC3
aplicher	aplichovais	V;IPFV;IND;PL;2;PST
revucher	revuche	V;SBJV;PL;3;PRS
cunferir	cunferieis	V;SBJV;PL;2;PRS
remander	remandeie	V;IND;SG;1;PRS;LGSPEC2
coordiner	coordineis	V;IND;PL;2;PRS
perder	perdaron	V;IND;PL;1;FUT
arbitrer	arbitrarà	V;IND;SG;3;FUT
acrediter	acredite	V;SBJV;SG;1;PRS;LGSPEC1
someter	sometes	V;SBJV;SG;2;PRS;LGSPEC1
ester	sareis	V;IND;PL;2;FUT
assenier	assenieies	V;SBJV;SG;2;PRS;LGSPEC2
populer	populova	V;IPFV;IND;SG;3;PST
usserver	usservede	V;NFIN;PL;2
scriver	scrive	V;SBJV;SG;3;PRS
destumer	destuma	V;NFIN;SG;2;LGSPEC1
condujer	condujon	V;IND;PL;1;PRS
perde	perdareis	V;IND;PL;2;FUT
acrediter	acredite	V;IND;SG;1;PRS;LGSPEC1
aplicher	apliches	V;IND;SG;2;PRS;LGSPEC1
erjer	erjaras	V;IND;SG;2;FUT
secuestrer	secuestreie	V;IND;SG;1;PRS;LGSPEC2
someter	sometovais	V;IPFV;IND;PL;2;PST
ejaminer	ejaminon	V;IND;PL;1;PRS
pruibir	pruib	V;IND;SG;3;PRS;LGSPEC1
ncurajer	ncurajaron	V;IND;PL;1;FUT
fisser	fisseies	V;SBJV;SG;2;PRS;LGSPEC2
remplazer	remplazon	V;IND;PL;1;PRS
scurter	scurter	V;NFIN;LGSPEC1
proibir	proibesc	V;IND;PL;3;PRS;LGSPEC2
prejenter	prejentassa	V;IPFV;SBJV;SG;3;PST
slunger	slunga	V;IND;SG;3;PRS;LGSPEC1
viuler	viuleis	V;IND;PL;2;PRS
mantenir	mantenivais	V;IPFV;IND;PL;2;PST
revucher	revuchasses	V;IPFV;SBJV;SG;2;PST
publicher	publichasse	V;IPFV;SBJV;SG;1;PST
costituir	costitu	V;NFIN;SG;2;LGSPEC1
adater	adater	V;NFIN;LGSPEC1
remander	remandaras	V;IND;SG;2;FUT
marider	marideie	V;IND;SG;1;PRS;LGSPEC2
istruir	istruesce	V;SBJV;SG;3;PRS;LGSPEC2
istituir	istituireis	V;IND;PL;2;FUT
revucher	revuchovan	V;IPFV;IND;PL;1;PST
atuer	atuaron	V;IND;PL;1;FUT
slunger	slungon	V;SBJV;PL;1;PRS
atribuir	atribues	V;SBJV;SG;2;PRS;LGSPEC1
fisser	fissea	V;IND;SG;3;PRS;LGSPEC3
dormir	dormive	V;IPFV;IND;SG;1;PST
limiter	limiton	V;SBJV;PL;1;PRS
revucher	revuchova	V;IPFV;IND;PL;3;PST
pruibir	pruibesce	V;IND;SG;1;PRS;LGSPEC2
aproer	aproeie	V;IND;SG;1;PRS;LGSPEC2
ancunter	ancuntareis	V;IND;PL;2;FUT
comprer	compré	V;NFIN;LGSPEC2
dovei	dessarà	V;IND;SG;3;FUT
damander	damandeie	V;IND;SG;1;PRS;LGSPEC2
porter	portova	V;IPFV;IND;PL;3;PST
trater	tratasse	V;IPFV;SBJV;SG;1;PST
seurander	seurandasses	V;IPFV;SBJV;SG;2;PST
someter	sometarà	V;IND;PL;3;FUT
adoter	adotea	V;IND;SG;3;PRS;LGSPEC3
tradujer	traduj	V;NFIN;SG;2
ndicher	ndichede	V;NFIN;PL;2
emaner	emanes	V;SBJV;SG;2;PRS;LGSPEC1
ester	fossa	V;IPFV;SBJV;PL;3;PST
educher	educhon	V;SBJV;PL;1;PRS
mander	mandovan	V;IPFV;IND;PL;1;PST
manifester	manifesteia	V;IND;PL;3;PRS;LGSPEC2
revucher	revuchon	V;SBJV;PL;1;PRS
cherder	cherdova	V;IPFV;IND;SG;3;PST
determiner	determinaron	V;IND;PL;1;FUT
resulter	resulteie	V;SBJV;SG;1;PRS;LGSPEC2
liter	litede	V;NFIN;PL;2
cogner	cognareis	V;IND;PL;2;FUT
spieter	spieton	V;IND;PL;1;PRS
istruir	istruisses	V;IPFV;SBJV;SG;2;PST
perdujer	perdujessais	V;IPFV;SBJV;PL;2;PST
acurder	acurdeie	V;SBJV;SG;3;PRS;LGSPEC2
furmer	furmeia	V;IND;PL;3;PRS;LGSPEC2
depenjer	depenjeis	V;IND;PL;2;PRS
mantenir	mantenissa	V;IPFV;SBJV;PL;3;PST
tramuder	tramudareis	V;IND;PL;2;FUT
defrenzier	defrenzieis	V;SBJV;PL;2;PRS
someter	sometassa	V;IPFV;SBJV;PL;3;PST
respuender	respuendea	V;IND;SG;3;PRS;LGSPEC3
depenjer	depenjovais	V;IPFV;IND;PL;2;PST
autoriser	autorisassa	V;IPFV;SBJV;SG;3;PST
secuestrer	secuestraré	V;IND;SG;1;FUT
apurver	apurves	V;SBJV;SG;2;PRS;LGSPEC1
aproer	aproeis	V;SBJV;PL;2;PRS
spieter	spiete	V;SBJV;SG;1;PRS;LGSPEC1
educher	educhove	V;IPFV;IND;SG;1;PST
sporjer	sporjesse	V;IPFV;SBJV;SG;1;PST
redujer	reduj	V;IND;SG;3;PRS
reguler	reguleia	V;IND;SG;3;PRS;LGSPEC2
dejeujer	dejëujeia	V;NFIN;SG;2;LGSPEC2
perder	perdaré	V;IND;SG;1;FUT
messei	messessais	V;IPFV;SBJV;PL;2;PST
delegher	delegheie	V;SBJV;SG;1;PRS;LGSPEC2
sotscriver	sotscrive	V;IND;SG;1;PRS
atribuir	atribue	V;SBJV;PL;3;PRS;LGSPEC1
produjer	produjareis	V;IND;PL;2;FUT
ejaminer	ejaminassa	V;IPFV;SBJV;SG;3;PST
arjonjer	arjonjessais	V;IPFV;SBJV;PL;2;PST
capir	capesce	V;IND;SG;1;PRS;LGSPEC2
damander	damandaras	V;IND;SG;2;FUT
arbitrer	arbitrassa	V;IPFV;SBJV;PL;3;PST
lascer	lascassais	V;IPFV;SBJV;PL;2;PST
ratificher	ratifiche	V;SBJV;SG;1;PRS;LGSPEC1
cundaner	cundane	V;SBJV;SG;1;PRS;LGSPEC1
pronunzier	pronunziasses	V;IPFV;SBJV;SG;2;PST
ndicher	ndicha	V;IND;PL;3;PRS;LGSPEC1
reguler	reguleies	V;IND;SG;2;PRS;LGSPEC2
condujer	condujarà	V;IND;PL;3;FUT
reverir	reveriras	V;IND;SG;2;FUT
resulter	resultove	V;IPFV;IND;SG;1;PST
udir	udisse	V;IPFV;SBJV;SG;1;PST
storjer	storjon	V;IND;PL;1;PRS
ratificher	ratifichovan	V;IPFV;IND;PL;1;PST
trater	trate	V;IND;SG;1;PRS;LGSPEC1
acuser	acusa	V;IND;PL;3;PRS;LGSPEC1
adater	adateis	V;IND;PL;2;PRS
arester	aresteie	V;SBJV;SG;3;PRS;LGSPEC2
podei	pos	V;IND;SG;2;PRS
alesirer	alesirasses	V;IPFV;SBJV;SG;2;PST
stipuler	stipularon	V;IND;PL;1;FUT
volei	vues	V;IND;SG;2;PRS
istruir	istrue	V;SBJV;SG;1;PRS;LGSPEC1
adater	adatea	V;IND;SG;3;PRS;LGSPEC3
franjer	franjova	V;IPFV;IND;PL;3;PST
limiter	limites	V;SBJV;SG;2;PRS;LGSPEC1
slunger	slungeia	V;NFIN;SG;2;LGSPEC2
rejoner	rejone	V;IND;SG;1;PRS;LGSPEC1
franjer	franjaron	V;IND;PL;1;FUT
nascer	nasce	V;SBJV;SG;3;PRS
assenier	assenion	V;IND;PL;1;PRS
usserver	usservassan	V;IPFV;SBJV;PL;1;PST
afermer	afermeis	V;SBJV;PL;2;PRS
scuter	scoute	V;SBJV;SG;1;PRS;LGSPEC1
dejeujer	dejëujaras	V;IND;SG;2;FUT
atribuir	atribuive	V;IPFV;IND;SG;1;PST
costituir	costituesce	V;IND;SG;1;PRS;LGSPEC2
romper	rompesses	V;IPFV;SBJV;SG;2;PST
assenier	asseniova	V;IPFV;IND;SG;3;PST
nfurmer	nfurmassa	V;IPFV;SBJV;PL;3;PST
mener	meineia	V;IND;PL;3;PRS;LGSPEC2
mpartir	mpartes	V;IND;SG;2;PRS;LGSPEC1
detlarer	detlararà	V;IND;SG;3;FUT
nascer	nascova	V;IPFV;IND;SG;3;PST
trasferir	trasferes	V;IND;SG;2;PRS;LGSPEC1
istituir	istitues	V;IND;SG;2;PRS;LGSPEC1
prejenter	prejentovais	V;IPFV;IND;PL;2;PST
marider	marideia	V;IND;PL;3;PRS;LGSPEC2
fisser	fissasses	V;IPFV;SBJV;SG;2;PST
pruibir	pruibiva	V;IPFV;IND;PL;3;PST
furmer	furma	V;IND;SG;3;PRS;LGSPEC1
comprer	comprassais	V;IPFV;SBJV;PL;2;PST
registrer	registrova	V;IPFV;IND;SG;3;PST
goder	godovan	V;IPFV;IND;PL;1;PST
trasferir	trasferiva	V;IPFV;IND;SG;3;PST
depenjer	depenjon	V;SBJV;PL;1;PRS
fisser	fissaron	V;IND;PL;1;FUT
spartir	spartiva	V;IPFV;IND;SG;3;PST
destiner	destine	V;SBJV;PL;3;PRS
capir	capesce	V;SBJV;PL;3;PRS;LGSPEC2
cumander	cumanda	V;IND;PL;3;PRS;LGSPEC1
rezever	rezev	V;IND;SG;3;PRS
passer	passa	V;IND;PL;3;PRS;LGSPEC1
coordener	coordenassais	V;IPFV;SBJV;PL;2;PST
passer	passa	V;NFIN;SG;2;LGSPEC1
arjonjer	arjonjon	V;IND;PL;1;PRS
viuler	viuleies	V;SBJV;SG;2;PRS;LGSPEC2
ressolver	ressolva	V;IND;SG;3;PRS;LGSPEC1
finanzier	finanzieis	V;SBJV;PL;2;PRS
proibir	proibesces	V;IND;SG;2;PRS;LGSPEC2
costituir	costituissa	V;IPFV;SBJV;SG;3;PST
delegher	deleghea	V;IND;SG;3;PRS;LGSPEC3
arester	areste	V;IND;SG;1;PRS;LGSPEC1
spieter	spietasses	V;IPFV;SBJV;SG;2;PST
viuler	viula	V;NFIN;SG;2;LGSPEC1
avei	ae	V;SBJV;PL;3;PRS;LGSPEC1
prufesser	prufessasse	V;IPFV;SBJV;SG;1;PST
savei	saveis	V;IND;PL;2;PRS
determiner	determineia	V;NFIN;SG;2;LGSPEC2
registrer	registraras	V;IND;SG;2;FUT
resulter	resultasse	V;IPFV;SBJV;SG;1;PST
detlarer	detlarova	V;IPFV;IND;SG;3;PST
adoter	adotes	V;IND;SG;2;PRS;LGSPEC1
resserver	resserve	V;SBJV;PL;3;PRS
manifester	manifester	V;NFIN;LGSPEC1
aproer	aproé	V;NFIN;LGSPEC2
volei	voleis	V;SBJV;PL;2;PRS
pruibir	pruibesc	V;NFIN;SG;2;LGSPEC2
adater	adateis	V;SBJV;PL;2;PRS
defrenzier	defrenziovan	V;IPFV;IND;PL;1;PST
reurganiser	reurganise	V;SBJV;SG;3;PRS;LGSPEC1
resserver	resserveis	V;IND;PL;2;PRS
spidler	spidlovan	V;IPFV;IND;PL;1;PST
acurder	acurdeia	V;IND;PL;3;PRS;LGSPEC2
scriver	scrive	V;SBJV;PL;3;PRS
perdujer	perdujaras	V;IND;SG;2;FUT
coordener	coordenasse	V;IPFV;SBJV;SG;1;PST
nevei	nevessa	V;IPFV;SBJV;SG;3;PST
prejenter	prejentea	V;IND;SG;3;PRS;LGSPEC3
comunicher	comuniche	V;IND;SG;1;PRS;LGSPEC1
produjer	produjede	V;NFIN;PL;2
delegher	deleghassais	V;IPFV;SBJV;PL;2;PST
mirer	mirasses	V;IPFV;SBJV;SG;2;PST
rejoner	rejonasses	V;IPFV;SBJV;SG;2;PST
arbitrer	arbitrassan	V;IPFV;SBJV;PL;1;PST
gaujer	gaujeies	V;SBJV;SG;2;PRS;LGSPEC2
unir	unesc	V;NFIN;SG;2;LGSPEC2
delegher	delegharon	V;IND;PL;1;FUT
entenjer	entenjeis	V;SBJV;PL;2;PRS
afermer	afermarà	V;IND;SG;3;FUT
entenjer	entenjessan	V;IPFV;SBJV;PL;1;PST
reurganiser	reurganiseie	V;SBJV;SG;1;PRS;LGSPEC2
schiver	schiveis	V;SBJV;PL;2;PRS
purter	purtasses	V;IPFV;SBJV;SG;2;PST
remplazer	remplazassa	V;IPFV;SBJV;PL;3;PST
purter	purton	V;IND;PL;1;PRS
scuter	scoute	V;SBJV;SG;3;PRS;LGSPEC1
rejoner	rejones	V;SBJV;SG;2;PRS;LGSPEC1
udir	udissan	V;IPFV;SBJV;PL;1;PST
cunzeder	cunzedeis	V;SBJV;PL;2;PRS
redujer	redujarà	V;IND;PL;3;FUT
destumer	destumoves	V;IPFV;IND;SG;2;PST
depenjer	depenjesse	V;IPFV;SBJV;SG;1;PST
delegher	deleghon	V;SBJV;PL;1;PRS
desgorjer	desgorjove	V;IPFV;IND;SG;1;PST
delibrer	delibrareis	V;IND;PL;2;FUT
furmer	furmon	V;IND;PL;1;PRS
garantir	garantieis	V;IND;PL;2;PRS
someter	sometes	V;IND;SG;2;PRS;LGSPEC1
viuler	viules	V;IND;SG;2;PRS;LGSPEC1
coordener	coordenova	V;IPFV;IND;PL;3;PST
entenjer	entenjarà	V;IND;PL;3;FUT
capir	capion	V;SBJV;PL;1;PRS
rejoner	rejoneis	V;IND;PL;2;PRS
pruibir	pruibe	V;IND;SG;1;PRS;LGSPEC1
prufesser	prufessoves	V;IPFV;IND;SG;2;PST
aplicher	aplichova	V;IPFV;IND;PL;3;PST
coordener	coordenova	V;IPFV;IND;SG;3;PST
depenjer	depenjoves	V;IPFV;IND;SG;2;PST
unir	un	V;IND;SG;3;PRS;LGSPEC1
azerter	azerteie	V;SBJV;SG;1;PRS;LGSPEC2
secuestrer	secuestra	V;NFIN;SG;2;LGSPEC1
atuer	atueia	V;NFIN;SG;2;LGSPEC2
onjer	onjareis	V;IND;PL;2;FUT
reverir	reveresce	V;SBJV;SG;3;PRS;LGSPEC2
determiner	determinede	V;NFIN;PL;2
rester	resteia	V;NFIN;SG;2;LGSPEC2
destiner	destinassais	V;IPFV;SBJV;PL;2;PST
alesirer	alesireies	V;SBJV;SG;2;PRS;LGSPEC2
ressolver	ressolva	V;NFIN;SG;2;LGSPEC1
tramuder	tramudeie	V;SBJV;SG;1;PRS;LGSPEC2
nascer	nasces	V;SBJV;SG;2;PRS
coordiner	coordinovan	V;IPFV;IND;PL;1;PST
corompe	corompoves	V;IPFV;IND;SG;2;PST
stipuler	stipuleis	V;IND;PL;2;PRS
rezever	rezevede	V;NFIN;PL;2
giudicher	giudichovais	V;IPFV;IND;PL;2;PST
ndicher	ndichon	V;SBJV;PL;1;PRS
udir	ud	V;NFIN;SG;2;LGSPEC1
pruibir	pruibive	V;IPFV;IND;SG;1;PST
resulter	resultasses	V;IPFV;SBJV;SG;2;PST
trasferir	trasferissais	V;IPFV;SBJV;PL;2;PST
populer	populede	V;NFIN;PL;2
reprejenter	reprejentova	V;IPFV;IND;PL;3;PST
delibrer	delibreia	V;IND;SG;3;PRS;LGSPEC2
rater	ratassan	V;IPFV;SBJV;PL;1;PST
mpartir	mpartesce	V;IND;SG;1;PRS;LGSPEC2
acrediter	acreditasses	V;IPFV;SBJV;SG;2;PST
mpartir	mpartirà	V;IND;PL;3;FUT
acurder	acurdea	V;IND;SG;3;PRS;LGSPEC3
acrediter	acrediteis	V;IND;PL;2;PRS
jonjer	jonjareis	V;IND;PL;2;FUT
tramuder	tramudeia	V;IND;PL;3;PRS;LGSPEC2
segurer	segurassais	V;IPFV;SBJV;PL;2;PST
adater	adatovais	V;IPFV;IND;PL;2;PST
adater	adateie	V;IND;SG;1;PRS;LGSPEC2
storjer	storjes	V;IND;SG;2;PRS
liter	lita	V;IND;SG;3;PRS;LGSPEC1
deslier	desliasses	V;IPFV;SBJV;SG;2;PST
pronunzier	pronunzioves	V;IPFV;IND;SG;2;PST
aplicher	aplichasses	V;IPFV;SBJV;SG;2;PST
remplazer	remplazova	V;IPFV;IND;SG;3;PST
seurander	seurandaras	V;IND;SG;2;FUT
dejeujer	dejëujassan	V;IPFV;SBJV;PL;1;PST
destumer	destumassa	V;IPFV;SBJV;PL;3;PST
afermer	afermes	V;IND;SG;2;PRS;LGSPEC1
aproer	aproeia	V;IND;PL;3;PRS;LGSPEC2
resserver	resserves	V;SBJV;SG;2;PRS;LGSPEC1
trasferir	trasferiron	V;IND;PL;1;FUT
autoriser	autorisarà	V;IND;PL;3;FUT
cogner	cognon	V;SBJV;PL;1;PRS
manifester	manifesta	V;IND;SG;3;PRS;LGSPEC1
ratificher	ratificharà	V;IND;PL;3;FUT
purter	purtes	V;IND;SG;2;PRS;LGSPEC1
franjer	franjarà	V;IND;SG;3;FUT
delibrer	delibres	V;SBJV;SG;2;PRS;LGSPEC1
erjer	erjessa	V;IPFV;SBJV;PL;3;PST
respuender	respuendassa	V;IPFV;SBJV;PL;3;PST
comunicher	comunicheia	V;NFIN;SG;2;LGSPEC2
mutiver	mutivassan	V;IPFV;SBJV;PL;1;PST
parteziper	partezipovais	V;IPFV;IND;PL;2;PST
eserziter	eserzite	V;SBJV;PL;3;PRS
acurder	acurda	V;NFIN;SG;2;LGSPEC1
ressolver	ressolvaré	V;IND;SG;1;FUT
erjer	erje	V;SBJV;SG;1;PRS
respuender	respuendon	V;SBJV;PL;1;PRS
schiver	schivoves	V;IPFV;IND;SG;2;PST
detlarer	detlarer	V;NFIN;LGSPEC1
ndicher	ndicheis	V;SBJV;PL;2;PRS
njinier	njiniassais	V;IPFV;SBJV;PL;2;PST
reverir	reverireis	V;IND;PL;2;FUT
scuter	scouteie	V;SBJV;SG;1;PRS;LGSPEC2
cundaner	cundanon	V;SBJV;PL;1;PRS
finanzier	finanziede	V;NFIN;PL;2
dé	dèr	V;NFIN;LGSPEC2
perdujer	perdujova	V;IPFV;IND;PL;3;PST
arester	arestarà	V;IND;PL;3;FUT
scurter	scurtareis	V;IND;PL;2;FUT
aussei	aussesses	V;IPFV;SBJV;SG;2;PST
resserver	resservova	V;IPFV;IND;PL;3;PST
porter	porteie	V;SBJV;SG;3;PRS;LGSPEC2
arjonjer	arjonjessa	V;IPFV;SBJV;SG;3;PST
defrenzier	defrenziaras	V;IND;SG;2;FUT
muder	mudeia	V;IND;PL;3;PRS;LGSPEC2
mander	mandassan	V;IPFV;SBJV;PL;1;PST
dovei	dessareis	V;IND;PL;2;FUT
someter	someteie	V;SBJV;SG;3;PRS;LGSPEC2
anuler	anulasse	V;IPFV;SBJV;SG;1;PST
storjer	storjes	V;SBJV;SG;2;PRS
capir	cape	V;IND;SG;1;PRS;LGSPEC1
mander	mandon	V;SBJV;PL;1;PRS
rester	restasse	V;IPFV;SBJV;SG;1;PST
renunzier	renunzieie	V;IND;SG;1;PRS;LGSPEC2
comprer	compreie	V;SBJV;SG;1;PRS;LGSPEC2
anuler	anulassa	V;IPFV;SBJV;PL;3;PST
messei	messe	V;SBJV;PL;3;PRS
sustenir	sustenesce	V;IND;SG;1;PRS;LGSPEC2
unir	unisses	V;IPFV;SBJV;SG;2;PST
liter	liteis	V;SBJV;PL;2;PRS
danejer	danejaré	V;IND;SG;1;FUT
mander	mandarà	V;IND;PL;3;FUT
jì	jiras	V;IND;SG;2;FUT
purter	purtaron	V;IND;PL;1;FUT
gaujer	gaujasses	V;IPFV;SBJV;SG;2;PST
acrediter	acrediteie	V;IND;SG;1;PRS;LGSPEC2
renunzier	renunzie	V;SBJV;SG;3;PRS;LGSPEC1
autoriser	autorisassan	V;IPFV;SBJV;PL;1;PST
partir	pertes	V;IND;SG;2;PRS
viuler	viuleie	V;SBJV;SG;3;PRS;LGSPEC2
furmer	furmeie	V;SBJV;SG;3;PRS;LGSPEC2
cherder	cherdovais	V;IPFV;IND;PL;2;PST
curespuender	curespuendarà	V;IND;PL;3;FUT
adurver	adurveia	V;IND;PL;3;PRS;LGSPEC2
aplicher	aplichassais	V;IPFV;SBJV;PL;2;PST
remplazer	remplazeis	V;SBJV;PL;2;PRS
terjer	terjessan	V;IPFV;SBJV;PL;1;PST
storjer	storjovan	V;IPFV;IND;PL;1;PST
adoter	adoton	V;IND;PL;1;PRS
cianter	ciantovais	V;IPFV;IND;PL;2;PST
renunzier	renunzieia	V;IND;SG;3;PRS;LGSPEC2
fé	fajarà	V;IND;PL;3;FUT
destumer	destume	V;SBJV;PL;3;PRS
jonjer	jonje	V;NFIN;LGSPEC2
aproer	aproaron	V;IND;PL;1;FUT
desgorjer	desgorjaron	V;IND;PL;1;FUT
eserziter	eserziteie	V;SBJV;SG;3;PRS;LGSPEC2
revucher	revuché	V;NFIN;LGSPEC2
curespuender	curespuendareis	V;IND;PL;2;FUT
ester	fovais	V;IPFV;IND;PL;2;PST
dormir	dormissa	V;IPFV;SBJV;PL;3;PST
purter	purtes	V;SBJV;SG;2;PRS;LGSPEC1
istituir	istituivais	V;IPFV;IND;PL;2;PST
meter	metoves	V;IPFV;IND;SG;2;PST
mirer	mire	V;SBJV;SG;3;PRS;LGSPEC1
scuter	scutasses	V;IPFV;SBJV;SG;2;PST
vedei	vedovan	V;IPFV;IND;PL;1;PST
fé	fajessa	V;IPFV;SBJV;PL;3;PST
ndicher	ndichoves	V;IPFV;IND;SG;2;PST
educher	educheia	V;NFIN;SG;2;LGSPEC2
assenier	assenié	V;NFIN;LGSPEC2
reurganiser	reurganisovan	V;IPFV;IND;PL;1;PST
trasferir	trasferisses	V;IPFV;SBJV;SG;2;PST
damander	damandeia	V;IND;SG;3;PRS;LGSPEC2
sporjer	sporjesses	V;IPFV;SBJV;SG;2;PST
stipuler	stipuleie	V;SBJV;SG;1;PRS;LGSPEC2
remander	remande	V;IND;SG;1;PRS;LGSPEC1
acrediter	acrediteia	V;NFIN;SG;2;LGSPEC2
stabilir	stabilisse	V;IPFV;SBJV;SG;1;PST
coordener	coordeneie	V;SBJV;SG;3;PRS;LGSPEC2
resserver	resservede	V;NFIN;PL;2
publicher	publiches	V;IND;SG;2;PRS;LGSPEC1
ndrezer	ndreza	V;NFIN;SG;2;LGSPEC1
rater	ratede	V;NFIN;PL;2
alesirer	alesireies	V;IND;SG;2;PRS;LGSPEC2
afermer	afermes	V;SBJV;SG;2;PRS;LGSPEC1
scuter	scouteia	V;NFIN;SG;2;LGSPEC2
fisser	fissa	V;IND;PL;3;PRS;LGSPEC1
segurer	segurarà	V;IND;PL;3;FUT
trater	trataras	V;IND;SG;2;FUT
segurer	seguraron	V;IND;PL;1;FUT
adurver	adurveies	V;SBJV;SG;2;PRS;LGSPEC2
coster	coston	V;IND;PL;1;PRS
populer	populassa	V;IPFV;SBJV;SG;3;PST
meter	mete	V;SBJV;PL;3;PRS
reguler	regules	V;SBJV;SG;2;PRS;LGSPEC1
tradujer	tradujovais	V;IPFV;IND;PL;2;PST
passer	passeie	V;SBJV;SG;3;PRS;LGSPEC2
deslier	deslia	V;IND;SG;3;PRS;LGSPEC1
aproer	aproasses	V;IPFV;SBJV;SG;2;PST
produjer	produjes	V;SBJV;SG;2;PRS
assenier	assenieies	V;IND;SG;2;PRS;LGSPEC2
gaujer	gaujeie	V;SBJV;SG;1;PRS;LGSPEC2
reverir	reveresce	V;SBJV;SG;1;PRS;LGSPEC2
meter	metove	V;IPFV;IND;SG;1;PST
lascer	lasceie	V;SBJV;SG;3;PRS;LGSPEC2
acrediter	acreditaras	V;IND;SG;2;FUT
usserver	usserver	V;NFIN;LGSPEC1
limiter	limitarà	V;IND;PL;3;FUT
comprer	comprove	V;IPFV;IND;SG;1;PST
reprejenter	reprejenton	V;SBJV;PL;1;PRS
publicher	publichovan	V;IPFV;IND;PL;1;PST
jonjer	jonj	V;IND;PL;3;PRS
passer	passarà	V;IND;PL;3;FUT
assegurer	asseguron	V;IND;PL;1;PRS
cundaner	cundaneies	V;SBJV;SG;2;PRS;LGSPEC2
dovei	dessaré	V;IND;SG;1;FUT
adater	adateia	V;IND;SG;3;PRS;LGSPEC2
strenjer	strenjeis	V;IND;PL;2;PRS
ratificher	ratifichede	V;NFIN;PL;2
jonjer	jonjon	V;IND;PL;1;PRS
spieter	spietassa	V;IPFV;SBJV;PL;3;PST
costituir	costitue	V;SBJV;PL;3;PRS;LGSPEC1
adater	adaté	V;NFIN;LGSPEC2
cunferir	cunferion	V;IND;PL;1;PRS
spartir	spartissa	V;IPFV;SBJV;PL;3;PST
viver	vive	V;SBJV;PL;3;PRS
dormir	dormirà	V;IND;SG;3;FUT
marider	maridon	V;SBJV;PL;1;PRS
dormir	dorme	V;SBJV;PL;3;PRS;LGSPEC1
rater	ratassais	V;IPFV;SBJV;PL;2;PST
prufesser	prufessa	V;IND;PL;3;PRS;LGSPEC1
arester	aresteie	V;IND;SG;1;PRS;LGSPEC2
resulter	resulte	V;IND;SG;1;PRS;LGSPEC1
rater	rateies	V;SBJV;SG;2;PRS;LGSPEC2
atribuir	atribuivan	V;IPFV;IND;PL;1;PST
pronunzier	pronunzia	V;IND;PL;3;PRS;LGSPEC1
adoter	adotes	V;SBJV;SG;2;PRS;LGSPEC1
slunger	slunges	V;SBJV;SG;2;PRS;LGSPEC1
desvier	desviovan	V;IPFV;IND;PL;1;PST
delegher	deleghe	V;SBJV;PL;3;PRS
proibir	proibireis	V;IND;PL;2;FUT
defrenzier	defrenzie	V;NFIN;LGSPEC2
costituir	costituiva	V;IPFV;IND;PL;3;PST
nfurmer	nfurmova	V;IPFV;IND;SG;3;PST
cuntroler	cuntrola	V;IND;SG;3;PRS;LGSPEC1
istituir	istituesce	V;SBJV;SG;3;PRS;LGSPEC2
scurter	scurté	V;NFIN;LGSPEC2
mirer	mirovan	V;IPFV;IND;PL;1;PST
coordener	coordeneie	V;SBJV;SG;1;PRS;LGSPEC2
garantir	garantesces	V;SBJV;SG;2;PRS;LGSPEC2
ressolver	ressolveie	V;SBJV;SG;3;PRS;LGSPEC2
partir	partiva	V;IPFV;IND;SG;3;PST
emaner	emane	V;SBJV;SG;3;PRS;LGSPEC1
dejeujer	dejëuje	V;SBJV;PL;3;PRS
adurver	adurve	V;SBJV;SG;3;PRS;LGSPEC1
defrenzier	defrenziesse	V;IPFV;SBJV;SG;1;PST
depenjer	depenjova	V;IPFV;IND;SG;3;PST
acrediter	acrediton	V;IND;PL;1;PRS
assegurer	asseguré	V;NFIN;LGSPEC2
resserver	resservovan	V;IPFV;IND;PL;1;PST
fé	fajovais	V;IPFV;IND;PL;2;PST
detlarer	detlarovan	V;IPFV;IND;PL;1;PST
terjer	terjoves	V;IPFV;IND;SG;2;PST
rezever	rezeves	V;IND;SG;2;PRS
goder	gode	V;SBJV;PL;3;PRS
determiner	determines	V;SBJV;SG;2;PRS;LGSPEC1
perdujer	perdujon	V;IND;PL;1;PRS
damander	damandon	V;IND;PL;1;PRS
spartir	spartisse	V;IPFV;SBJV;SG;1;PST
marider	maridareis	V;IND;PL;2;FUT
delibrer	delibrovais	V;IPFV;IND;PL;2;PST
ndrezer	ndrezea	V;IND;SG;3;PRS;LGSPEC3
acuser	acuseis	V;IND;PL;2;PRS
perder	perdova	V;IPFV;IND;SG;3;PST
cumander	cumande	V;IND;SG;1;PRS;LGSPEC1
podei	posse	V;SBJV;SG;3;PRS
morir	morissa	V;IPFV;SBJV;SG;3;PST
secuestrer	secuestreis	V;SBJV;PL;2;PRS
goder	godea	V;IND;SG;3;PRS;LGSPEC3
unir	univais	V;IPFV;IND;PL;2;PST
pruibir	pruibes	V;SBJV;SG;2;PRS;LGSPEC1
dormir	dormesc	V;IND;PL;3;PRS;LGSPEC2
urganiser	urganisassa	V;IPFV;SBJV;SG;3;PST
adater	adate	V;SBJV;SG;3;PRS;LGSPEC1
jì	vae	V;SBJV;PL;3;PRS
partir	partivan	V;IPFV;IND;PL;1;PST
dejeujer	dejëujassais	V;IPFV;SBJV;PL;2;PST
muder	mude	V;SBJV;PL;3;PRS
njinier	njinie	V;SBJV;SG;3;PRS;LGSPEC1
njinier	njiniea	V;IND;SG;3;PRS;LGSPEC3
volei	volessan	V;IPFV;SBJV;PL;1;PST
liter	litovan	V;IPFV;IND;PL;1;PST
autoriser	autorisa	V;IND;PL;3;PRS;LGSPEC1
comprer	compreies	V;IND;SG;2;PRS;LGSPEC2
mpartir	mpartion	V;SBJV;PL;1;PRS
morir	morisses	V;IPFV;SBJV;SG;2;PST
curespuender	curespuendes	V;SBJV;SG;2;PRS;LGSPEC1
marider	marideis	V;IND;PL;2;PRS
partir	partives	V;IPFV;IND;SG;2;PST
perde	perdessa	V;IPFV;SBJV;PL;3;PST
apurver	apurveia	V;NFIN;SG;2;LGSPEC2
perder	perdon	V;IND;PL;1;PRS
slunger	slungarà	V;IND;PL;3;FUT
cruzier	cruziarà	V;IND;SG;3;FUT
spidler	spidlova	V;IPFV;IND;SG;3;PST
publicher	publicheis	V;IND;PL;2;PRS
usserver	usserve	V;IND;SG;1;PRS;LGSPEC1
determiner	determine	V;SBJV;SG;1;PRS;LGSPEC1
determiner	determineia	V;IND;PL;3;PRS;LGSPEC2
arjonjer	arjonj	V;NFIN;SG;2
cuntroler	cuntroloves	V;IPFV;IND;SG;2;PST
respuender	respuende	V;SBJV;SG;3;PRS;LGSPEC1
delibrer	delibreis	V;SBJV;PL;2;PRS
azerter	azertove	V;IPFV;IND;SG;1;PST
acurder	acurdasse	V;IPFV;SBJV;SG;1;PST
istituir	istituesces	V;SBJV;SG;2;PRS;LGSPEC2
adurver	adurva	V;IND;PL;3;PRS;LGSPEC1
adurver	adurves	V;IND;SG;2;PRS;LGSPEC1
manifester	manifesteie	V;IND;SG;1;PRS;LGSPEC2
urganiser	urganison	V;IND;PL;1;PRS
promulgher	promulgharà	V;IND;PL;3;FUT
remander	remandes	V;SBJV;SG;2;PRS;LGSPEC1
danejer	daneje	V;IND;SG;1;PRS;LGSPEC1
prufesser	prufesseia	V;IND;PL;3;PRS;LGSPEC2
messei	messei	V;NFIN
acurder	acurdove	V;IPFV;IND;SG;1;PST
redujer	reduje	V;SBJV;SG;1;PRS
strenjer	strenje	V;IND;SG;1;PRS
cunvalider	cunvalideia	V;IND;PL;3;PRS;LGSPEC2
scuter	scutova	V;IPFV;IND;SG;3;PST
dé	dae	V;SBJV;PL;3;PRS
parteziper	parteziparà	V;IND;SG;3;FUT
stabilir	stabilion	V;SBJV;PL;1;PRS
condujer	condujessais	V;IPFV;SBJV;PL;2;PST
udir	ude	V;SBJV;PL;3;PRS;LGSPEC1
acurder	acurdeis	V;IND;PL;2;PRS
dé	daron	V;IND;PL;1;FUT
comprer	comprea	V;IND;SG;3;PRS;LGSPEC3
rezever	rezevove	V;IPFV;IND;SG;1;PST
coordener	coordene	V;SBJV;SG;1;PRS;LGSPEC1
reurganiser	reurganiser	V;NFIN;LGSPEC1
sotscriver	sotscriv	V;IND;PL;3;PRS
seurander	seurandeis	V;SBJV;PL;2;PRS
storjer	storjessan	V;IPFV;SBJV;PL;1;PST
reguler	regularà	V;IND;PL;3;FUT
cuntroler	cuntroleie	V;SBJV;SG;3;PRS;LGSPEC2
coordiner	coordinasses	V;IPFV;SBJV;SG;2;PST
usserver	usserveies	V;IND;SG;2;PRS;LGSPEC2
ressolver	ressolvon	V;SBJV;PL;1;PRS
udir	udion	V;IND;PL;1;PRS
populer	populeia	V;NFIN;SG;2;LGSPEC2
sponjer	sponjon	V;IND;PL;1;PRS
coordiner	coordinova	V;IPFV;IND;PL;3;PST
perder	perdove	V;IPFV;IND;SG;1;PST
garantir	garant	V;IND;SG;3;PRS;LGSPEC1
franjer	franjaras	V;IND;SG;2;FUT
emaner	emaneia	V;IND;SG;3;PRS;LGSPEC2
prufesser	prufesse	V;IND;SG;1;PRS;LGSPEC1
atuer	atuareis	V;IND;PL;2;FUT
someter	sometove	V;IPFV;IND;SG;1;PST
costituir	costituesc	V;NFIN;SG;2;LGSPEC2
reurganiser	reurganison	V;IND;PL;1;PRS
assenier	asseniarà	V;IND;SG;3;FUT
remander	remandasses	V;IPFV;SBJV;SG;2;PST
remander	remandova	V;IPFV;IND;SG;3;PST
terjer	terjovais	V;IPFV;IND;PL;2;PST
arbitrer	arbitreis	V;IND;PL;2;PRS
dé	dà	V;IND;PL;3;PRS
giudicher	giudicheis	V;SBJV;PL;2;PRS
rater	raté	V;NFIN;LGSPEC2
comunicher	comunichassan	V;IPFV;SBJV;PL;1;PST
alesirer	alesira	V;NFIN;SG;2;LGSPEC1
reguler	reguleia	V;NFIN;SG;2;LGSPEC2
liter	litarà	V;IND;PL;3;FUT
cumporter	cumporteie	V;IND;SG;1;PRS;LGSPEC2
arbitrer	arbitré	V;NFIN;LGSPEC2
schiver	schivaras	V;IND;SG;2;FUT
resulter	resulteia	V;IND;SG;3;PRS;LGSPEC2
udir	udesces	V;SBJV;SG;2;PRS;LGSPEC2
morir	morissais	V;IPFV;SBJV;PL;2;PST
cogner	cognea	V;IND;SG;3;PRS;LGSPEC3
deslier	deslieie	V;SBJV;SG;3;PRS;LGSPEC2
comunicher	comunichoves	V;IPFV;IND;SG;2;PST
avei	aesse	V;IPFV;SBJV;SG;1;PST;LGSPEC2
assenier	assenier	V;NFIN;LGSPEC1
promulgher	promulgher	V;NFIN;LGSPEC1
corompe	coromparas	V;IND;SG;2;FUT
respuender	respuendeie	V;SBJV;SG;1;PRS;LGSPEC2
mpartir	mpartesc	V;IND;PL;3;PRS;LGSPEC2
spieter	spietea	V;IND;SG;3;PRS;LGSPEC3
cumander	cumandon	V;IND;PL;1;PRS
ndicher	ndicharon	V;IND;PL;1;FUT
promulgher	promulgheia	V;NFIN;SG;2;LGSPEC2
promulgher	promulghon	V;SBJV;PL;1;PRS
destumer	destumeia	V;NFIN;SG;2;LGSPEC2
desgorjer	desgorjes	V;SBJV;SG;2;PRS
remander	remanda	V;IND;SG;3;PRS;LGSPEC1
parteziper	partezipova	V;IPFV;IND;PL;3;PST
purter	purta	V;IND;SG;3;PRS;LGSPEC1
mener	menon	V;IND;PL;1;PRS
sustenir	sustenide	V;NFIN;PL;2
damander	damandes	V;SBJV;SG;2;PRS;LGSPEC1
mpartir	mpart	V;IND;PL;3;PRS;LGSPEC1
prejenter	prejenteia	V;IND;PL;3;PRS;LGSPEC2
acurder	acurdaré	V;IND;SG;1;FUT
cunzeder	cunzedes	V;SBJV;SG;2;PRS
reguler	regulede	V;NFIN;PL;2
arester	aresteis	V;IND;PL;2;PRS
garantir	garantiron	V;IND;PL;1;FUT
populer	populeies	V;SBJV;SG;2;PRS;LGSPEC2
delegher	delegharas	V;IND;SG;2;FUT
schiver	schiveies	V;IND;SG;2;PRS;LGSPEC2
urganiser	urganiseie	V;IND;SG;1;PRS;LGSPEC2
resulter	resultarà	V;IND;PL;3;FUT
aussei	aussaras	V;IND;SG;2;FUT
dormir	dormirà	V;IND;PL;3;FUT
deslier	desliarà	V;IND;PL;3;FUT
partir	partissan	V;IPFV;SBJV;PL;1;PST
sponjer	sponjer	V;NFIN;LGSPEC1
nevei	neveèr	V;NFIN;LGSPEC2
numiner	numinarà	V;IND;SG;3;FUT
adoter	adotovan	V;IPFV;IND;PL;1;PST
rater	rateia	V;IND;PL;3;PRS;LGSPEC2
cunzeder	cunzedaras	V;IND;SG;2;FUT
franjer	franjoves	V;IPFV;IND;SG;2;PST
adurver	adurvoves	V;IPFV;IND;SG;2;PST
schiver	schiveie	V;SBJV;SG;1;PRS;LGSPEC2
porter	portea	V;IND;SG;3;PRS;LGSPEC3
spidler	spidlon	V;SBJV;PL;1;PRS
vedei	vedova	V;IPFV;IND;PL;3;PST
cumporter	cumportovais	V;IPFV;IND;PL;2;PST
aussei	aussareis	V;IND;PL;2;FUT
liter	liter	V;NFIN;LGSPEC1
mpartir	mpartieis	V;SBJV;PL;2;PRS
revucher	revucheie	V;IND;SG;1;PRS;LGSPEC2
damander	damandeis	V;IND;PL;2;PRS
stipuler	stipuleia	V;IND;SG;3;PRS;LGSPEC2
redujer	redujarà	V;IND;SG;3;FUT
garantir	garante	V;IND;SG;1;PRS;LGSPEC1
promulgher	promulghede	V;NFIN;PL;2
desgorjer	desgorjessan	V;IPFV;SBJV;PL;1;PST
parteziper	partezipon	V;IND;PL;1;PRS
nascer	nascon	V;SBJV;PL;1;PRS
storjer	storjer	V;NFIN;LGSPEC1
reverir	reverieis	V;IND;PL;2;PRS
aussei	ausses	V;IND;SG;2;PRS
ester	fova	V;IPFV;IND;PL;3;PST
sponjer	sponjessa	V;IPFV;SBJV;PL;3;PST
adoter	adote	V;IND;SG;1;PRS;LGSPEC1
coordener	coordenaras	V;IND;SG;2;FUT
cogner	cognaras	V;IND;SG;2;FUT
limiter	limite	V;SBJV;SG;3;PRS;LGSPEC1
alesirer	alesirovan	V;IPFV;IND;PL;1;PST
registrer	registrasses	V;IPFV;SBJV;SG;2;PST
resserver	resserver	V;NFIN;LGSPEC1
arester	arestede	V;NFIN;PL;2
passer	passes	V;IND;SG;2;PRS;LGSPEC1
revucher	revuchove	V;IPFV;IND;SG;1;PST
deslier	deslieies	V;IND;SG;2;PRS;LGSPEC2
anuler	anulassa	V;IPFV;SBJV;SG;3;PST
delibrer	delibrassan	V;IPFV;SBJV;PL;1;PST
apurver	apurvede	V;NFIN;PL;2
ndicher	ndichassa	V;IPFV;SBJV;PL;3;PST
cruzier	cruzieis	V;IND;PL;2;PRS
mirer	mireies	V;IND;SG;2;PRS;LGSPEC2
urganiser	urganiser	V;NFIN;LGSPEC1
revucher	revucharà	V;IND;SG;3;FUT
jonjer	jonjeis	V;SBJV;PL;2;PRS
stabilir	stabilissan	V;IPFV;SBJV;PL;1;PST
limiter	limiteia	V;IND;SG;3;PRS;LGSPEC2
arjonjer	arjonjes	V;SBJV;SG;2;PRS
secuestrer	secuestrovan	V;IPFV;IND;PL;1;PST
delegher	deleghon	V;IND;PL;1;PRS
delegher	deleghé	V;NFIN;LGSPEC2
ncurajer	ncurajassa	V;IPFV;SBJV;SG;3;PST
scurter	scurtarà	V;IND;SG;3;FUT
aproer	aproova	V;IPFV;IND;SG;3;PST
defrenzier	defrenziessais	V;IPFV;SBJV;PL;2;PST
aproer	aproeis	V;IND;PL;2;PRS
damander	damandon	V;SBJV;PL;1;PRS
numiner	numinova	V;IPFV;IND;PL;3;PST
desgorjer	desgorjon	V;IND;PL;1;PRS
destumer	destumaras	V;IND;SG;2;FUT
istituir	istitues	V;SBJV;SG;2;PRS;LGSPEC1
jonjer	jonjoves	V;IPFV;IND;SG;2;PST
arbitrer	arbitreie	V;IND;SG;1;PRS;LGSPEC2
vedei	veid	V;IND;SG;3;PRS
avei	as	V;IND;SG;2;PRS
mutiver	mutivarà	V;IND;PL;3;FUT
acuser	acuseia	V;IND;SG;3;PRS;LGSPEC2
alesirer	alesire	V;SBJV;PL;3;PRS
perde	perdaré	V;IND;SG;1;FUT
cunferir	cunferisses	V;IPFV;SBJV;SG;2;PST
mutiver	mutiveie	V;SBJV;SG;1;PRS;LGSPEC2
arbitrer	arbitrovais	V;IPFV;IND;PL;2;PST
avei	ebe	V;SBJV;SG;3;PRS;LGSPEC2
dovei	dessan	V;IPFV;SBJV;PL;1;PST;LGSPEC1
condujer	condujaras	V;IND;SG;2;FUT
atribuir	atribuireis	V;IND;PL;2;FUT
afermer	afermaron	V;IND;PL;1;FUT
mander	mandeies	V;SBJV;SG;2;PRS;LGSPEC2
ancunter	ancuntes	V;IND;SG;2;PRS;LGSPEC1
savei	savessais	V;IPFV;SBJV;PL;2;PST
slunger	slungaras	V;IND;SG;2;FUT
sporjer	sporjer	V;NFIN;LGSPEC1
goder	godeies	V;SBJV;SG;2;PRS;LGSPEC2
savei	savessa	V;IPFV;SBJV;PL;3;PST
parteziper	partezipeie	V;SBJV;SG;3;PRS;LGSPEC2
cumander	cumandes	V;SBJV;SG;2;PRS;LGSPEC1
cuntroler	cuntrolassais	V;IPFV;SBJV;PL;2;PST
ndicher	ndiche	V;IND;SG;1;PRS;LGSPEC1
proibir	proibisses	V;IPFV;SBJV;SG;2;PST
cunvalider	cunvalidassa	V;IPFV;SBJV;PL;3;PST
acrediter	acreditova	V;IPFV;IND;PL;3;PST
resulter	resulteies	V;IND;SG;2;PRS;LGSPEC2
desgorjer	desgorjede	V;NFIN;PL;2
perdujer	perdujaré	V;IND;SG;1;FUT
pronunzier	pronunzie	V;SBJV;SG;3;PRS;LGSPEC1
apurver	apurve	V;SBJV;PL;3;PRS
cherder	cherde	V;SBJV;PL;3;PRS
udir	udes	V;IND;SG;2;PRS;LGSPEC1
mutiver	mutivea	V;IND;SG;3;PRS;LGSPEC3
aussei	ausse	V;SBJV;SG;3;PRS
partir	partiron	V;IND;PL;1;FUT
assegurer	assegureie	V;SBJV;SG;3;PRS;LGSPEC2
arbitrer	arbitrassais	V;IPFV;SBJV;PL;2;PST
detlarer	detlare	V;SBJV;PL;3;PRS
ndrezer	ndrezeie	V;SBJV;SG;1;PRS;LGSPEC2
finanzier	finanziassan	V;IPFV;SBJV;PL;1;PST
cunferir	cunfer	V;IND;SG;3;PRS;LGSPEC1
sotscriver	sotscriveis	V;SBJV;PL;2;PRS
destumer	destuma	V;IND;SG;3;PRS;LGSPEC1
istruir	istruiva	V;IPFV;IND;PL;3;PST
aussei	aussova	V;IPFV;IND;PL;3;PST
stabilir	stabilissa	V;IPFV;SBJV;SG;3;PST
scurter	scurteie	V;SBJV;SG;1;PRS;LGSPEC2
dormir	dormes	V;SBJV;SG;2;PRS;LGSPEC1
lascer	lasces	V;SBJV;SG;2;PRS;LGSPEC1
detlarer	detlarasse	V;IPFV;SBJV;SG;1;PST
coster	coste	V;IND;SG;1;PRS;LGSPEC1
nfurmer	nfurmon	V;SBJV;PL;1;PRS
reguler	regularé	V;IND;SG;1;FUT
deslier	desliasse	V;IPFV;SBJV;SG;1;PST
ncurajer	ncurajova	V;IPFV;IND;PL;3;PST
cunzeder	cunzedede	V;NFIN;PL;2
morir	muer	V;NFIN;SG;2
rejoner	rejonovais	V;IPFV;IND;PL;2;PST
cunvalider	cunvalidova	V;IPFV;IND;SG;3;PST
ratificher	ratificheia	V;IND;SG;3;PRS;LGSPEC2
mener	meineis	V;SBJV;SG;2;PRS;LGSPEC2
spartir	spartirà	V;IND;SG;3;FUT
schiver	schivaron	V;IND;PL;1;FUT
cumporter	cumportova	V;IPFV;IND;PL;3;PST
detlarer	detlare	V;SBJV;SG;3;PRS;LGSPEC1
atuer	atuarà	V;IND;SG;3;FUT
fisser	fissasse	V;IPFV;SBJV;SG;1;PST
garantir	garantesce	V;SBJV;PL;3;PRS;LGSPEC2
schiver	schive	V;SBJV;SG;1;PRS;LGSPEC1
cunvalider	cunvalidovais	V;IPFV;IND;PL;2;PST
comprer	compres	V;SBJV;SG;2;PRS;LGSPEC1
mantenir	mantenion	V;SBJV;PL;1;PRS
dovei	desses	V;IND;SG;2;PRS
nevei	nevei	V;NFIN;LGSPEC1
rezever	rezeveis	V;IND;PL;2;PRS
trater	tratea	V;IND;SG;3;PRS;LGSPEC3
onjer	onjessais	V;IPFV;SBJV;PL;2;PST
emaner	emanaras	V;IND;SG;2;FUT
dovei	dova	V;IPFV;IND;PL;3;PST;LGSPEC1
tradujer	tradujon	V;SBJV;PL;1;PRS
sustenir	sustenes	V;SBJV;SG;2;PRS;LGSPEC1
coster	costaras	V;IND;SG;2;FUT
manifester	manifesteie	V;SBJV;SG;1;PRS;LGSPEC2
strenjer	strenjer	V;NFIN;LGSPEC1
mirer	mirassais	V;IPFV;SBJV;PL;2;PST
rester	restaré	V;IND;SG;1;FUT
giudicher	giudicharà	V;IND;PL;3;FUT
stabilir	stabilesce	V;SBJV;SG;3;PRS;LGSPEC2
udir	udesc	V;IND;PL;3;PRS;LGSPEC2
pruibir	pruibissais	V;IPFV;SBJV;PL;2;PST
aplicher	aplichea	V;IND;SG;3;PRS;LGSPEC3
mener	meine	V;SBJV;SG;3;PRS;LGSPEC1
tradujer	tradujessais	V;IPFV;SBJV;PL;2;PST
liter	liteia	V;IND;PL;3;PRS;LGSPEC2
onjer	onjessa	V;IPFV;SBJV;SG;3;PST
rester	restovais	V;IPFV;IND;PL;2;PST
pruibir	pruibieis	V;SBJV;PL;2;PRS
atribuir	atribuirà	V;IND;SG;3;FUT
unir	unesc	V;IND;PL;3;PRS;LGSPEC2
manifester	manifestovais	V;IPFV;IND;PL;2;PST
meter	metesse	V;IPFV;SBJV;SG;1;PST
mander	mandasse	V;IPFV;SBJV;SG;1;PST
savei	savarà	V;IND;PL;3;FUT
alesirer	alesiraré	V;IND;SG;1;FUT
delibrer	delibra	V;IND;SG;3;PRS;LGSPEC1
nascer	nascovan	V;IPFV;IND;PL;1;PST
reprejenter	reprejentarà	V;IND;SG;3;FUT
viver	vivessan	V;IPFV;SBJV;PL;1;PST
autoriser	autorison	V;IND;PL;1;PRS
reguler	regulova	V;IPFV;IND;PL;3;PST
giudicher	giudichasse	V;IPFV;SBJV;SG;1;PST
meter	metessa	V;IPFV;SBJV;PL;3;PST
spidler	spidle	V;IND;SG;1;PRS;LGSPEC1
udir	udissa	V;IPFV;SBJV;PL;3;PST
arjonjer	arjonje	V;SBJV;SG;3;PRS
arjonjer	arjonjeis	V;SBJV;PL;2;PRS
populer	populassais	V;IPFV;SBJV;PL;2;PST
emaner	emanovan	V;IPFV;IND;PL;1;PST
rejoner	rejonova	V;IPFV;IND;PL;3;PST
deslier	deslieis	V;IND;PL;2;PRS
capir	capive	V;IPFV;IND;SG;1;PST
mener	menon	V;SBJV;PL;1;PRS
ester	fossais	V;IPFV;SBJV;PL;2;PST
spartir	spartesc	V;NFIN;SG;2;LGSPEC2
deslier	deslié	V;NFIN;LGSPEC2
coordener	coordeneie	V;IND;SG;1;PRS;LGSPEC2
istituir	istituissa	V;IPFV;SBJV;PL;3;PST
sotscriver	sotscrive	V;SBJV;PL;3;PRS
reverir	reverir	V;NFIN;LGSPEC1
lascer	lasceie	V;IND;SG;1;PRS;LGSPEC2
furmer	furma	V;NFIN;SG;2;LGSPEC1
aproer	aproeia	V;NFIN;SG;2;LGSPEC2
liter	litovais	V;IPFV;IND;PL;2;PST
cumander	cumandeies	V;SBJV;SG;2;PRS;LGSPEC2
aussei	aussarà	V;IND;PL;3;FUT
marider	maridassa	V;IPFV;SBJV;SG;3;PST
azerter	azertassa	V;IPFV;SBJV;PL;3;PST
cogner	cognovais	V;IPFV;IND;PL;2;PST
costituir	costitu	V;IND;PL;3;PRS;LGSPEC1
onjer	onjeis	V;SBJV;PL;2;PRS
pronunzier	pronunziassan	V;IPFV;SBJV;PL;1;PST
cruzier	cruzie	V;SBJV;SG;3;PRS;LGSPEC1
savei	sà	V;NFIN;SG;2
stabilir	stabilivais	V;IPFV;IND;PL;2;PST
emaner	emanasse	V;IPFV;SBJV;SG;1;PST
publicher	publicheie	V;SBJV;SG;1;PRS;LGSPEC2
emaner	emaneia	V;NFIN;SG;2;LGSPEC2
desvier	desvieis	V;SBJV;PL;2;PRS
determiner	determiner	V;NFIN;LGSPEC1
scuter	scoutes	V;SBJV;SG;2;PRS;LGSPEC1
resserver	resservon	V;SBJV;PL;1;PRS
liter	litassa	V;IPFV;SBJV;PL;3;PST
ncurajer	ncurajer	V;NFIN;LGSPEC1
storjer	storjovais	V;IPFV;IND;PL;2;PST
lascer	lascea	V;IND;SG;3;PRS;LGSPEC3
lascer	lascovais	V;IPFV;IND;PL;2;PST
romper	rompoves	V;IPFV;IND;SG;2;PST
sustenir	sustenisse	V;IPFV;SBJV;SG;1;PST
cogner	cognaré	V;IND;SG;1;FUT
mutiver	mutivovais	V;IPFV;IND;PL;2;PST
azerter	azerté	V;NFIN;LGSPEC2
prufesser	prufesseies	V;IND;SG;2;PRS;LGSPEC2
cumporter	cumporton	V;SBJV;PL;1;PRS
delibrer	delibraras	V;IND;SG;2;FUT
remplazer	remplazeia	V;NFIN;SG;2;LGSPEC2
resserver	resservaras	V;IND;SG;2;FUT
publicher	publichove	V;IPFV;IND;SG;1;PST
resulter	resultassa	V;IPFV;SBJV;PL;3;PST
passer	passeia	V;IND;SG;3;PRS;LGSPEC2
adater	adatassan	V;IPFV;SBJV;PL;1;PST
usserver	usserve	V;SBJV;SG;3;PRS;LGSPEC1
adater	adateia	V;NFIN;SG;2;LGSPEC2
spieter	spieteis	V;SBJV;PL;2;PRS
determiner	determinasses	V;IPFV;SBJV;SG;2;PST
rejoner	rejonaron	V;IND;PL;1;FUT
avei	aes	V;NFIN;SG;2;LGSPEC1
anuler	anularon	V;IND;PL;1;FUT
franjer	franjeis	V;SBJV;PL;2;PRS
cuntroler	cuntrolassa	V;IPFV;SBJV;SG;3;PST
trasferir	trasferieis	V;IND;PL;2;PRS
dejeujer	dejëujeis	V;SBJV;PL;2;PRS
stipuler	stipula	V;IND;SG;3;PRS;LGSPEC1
parteziper	parteziper	V;NFIN;LGSPEC1
apurver	apurveie	V;SBJV;SG;1;PRS;LGSPEC2
adater	adatassa	V;IPFV;SBJV;SG;3;PST
detlarer	detlareia	V;IND;SG;3;PRS;LGSPEC2
dormir	dormisse	V;IPFV;SBJV;SG;1;PST
giudicher	giudichasses	V;IPFV;SBJV;SG;2;PST
perdujer	perduje	V;NFIN;LGSPEC2
perde	perdeis	V;SBJV;PL;2;PRS
cherder	cherdeis	V;IND;PL;2;PRS
porter	portova	V;IPFV;IND;SG;3;PST
destiner	destineie	V;IND;SG;1;PRS;LGSPEC2
aplicher	aplicheie	V;IND;SG;1;PRS;LGSPEC2
jonjer	jonj	V;IND;SG;3;PRS
curespuender	curespuendeies	V;IND;SG;2;PRS;LGSPEC2
respuender	respuendasse	V;IPFV;SBJV;SG;1;PST
eserziter	eserziteia	V;IND;PL;3;PRS;LGSPEC2
ejaminer	ejamineis	V;IND;PL;2;PRS
sporjer	sporjaré	V;IND;SG;1;FUT
remplazer	remplazassais	V;IPFV;SBJV;PL;2;PST
promulgher	promulgheia	V;IND;SG;3;PRS;LGSPEC2
manifester	manifestea	V;IND;SG;3;PRS;LGSPEC3
cianter	cianteie	V;IND;SG;1;PRS;LGSPEC2
prejenter	prejentasses	V;IPFV;SBJV;SG;2;PST
assegurer	assegurassa	V;IPFV;SBJV;PL;3;PST
viver	vivove	V;IPFV;IND;SG;1;PST
arester	arestova	V;IPFV;IND;SG;3;PST
sustenir	susten	V;NFIN;SG;2;LGSPEC1
atribuir	atribuesce	V;SBJV;SG;1;PRS;LGSPEC2
secuestrer	secuestrea	V;IND;SG;3;PRS;LGSPEC3
atuer	atueis	V;SBJV;PL;2;PRS
secuestrer	secuestrassais	V;IPFV;SBJV;PL;2;PST
viuler	viulassais	V;IPFV;SBJV;PL;2;PST
afermer	afermovais	V;IPFV;IND;PL;2;PST
njinier	njinieia	V;NFIN;SG;2;LGSPEC2
muder	mudaré	V;IND;SG;1;FUT
istruir	istruesc	V;IND;PL;3;PRS;LGSPEC2
perdujer	perduje	V;SBJV;PL;3;PRS
spartir	spartissais	V;IPFV;SBJV;PL;2;PST
prejenter	prejentassan	V;IPFV;SBJV;PL;1;PST
arbitrer	arbitrovan	V;IPFV;IND;PL;1;PST
cumporter	cumportarà	V;IND;PL;3;FUT
adater	adatasses	V;IPFV;SBJV;SG;2;PST
morir	morissa	V;IPFV;SBJV;PL;3;PST
entenjer	entenjova	V;IPFV;IND;SG;3;PST
scuter	scutassa	V;IPFV;SBJV;SG;3;PST
cunvalider	cunvalider	V;NFIN;LGSPEC1
promulgher	promulghes	V;IND;SG;2;PRS;LGSPEC1
gaujer	gaujé	V;NFIN;LGSPEC2
aplicher	aplichon	V;SBJV;PL;1;PRS
vegnì	vegnissais	V;IPFV;SBJV;PL;2;PST
terjer	terjaré	V;IND;SG;1;FUT
dé	dae	V;SBJV;SG;1;PRS
cuntroler	cuntrolon	V;IND;PL;1;PRS
podei	podovan	V;IPFV;IND;PL;1;PST
limiter	limiter	V;NFIN;LGSPEC1
curespuender	curespuendeis	V;SBJV;PL;2;PRS
condujer	condujesse	V;IPFV;SBJV;SG;1;PST
trasferir	trasferesc	V;IND;SG;3;PRS;LGSPEC2
danejer	danejasses	V;IPFV;SBJV;SG;2;PST
ncurajer	ncurajarà	V;IND;PL;3;FUT
danejer	danejassan	V;IPFV;SBJV;PL;1;PST
secuestrer	secuestrassa	V;IPFV;SBJV;PL;3;PST
azerter	azerte	V;IND;SG;1;PRS;LGSPEC1
curespuender	curespuendove	V;IPFV;IND;SG;1;PST
mirer	mira	V;NFIN;SG;2;LGSPEC1
urganiser	urganises	V;IND;SG;2;PRS;LGSPEC1
segurer	segura	V;IND;PL;3;PRS;LGSPEC1
spartir	spartesce	V;SBJV;SG;3;PRS;LGSPEC2
tramuder	tramudes	V;IND;SG;2;PRS;LGSPEC1
cherder	cherdaré	V;IND;SG;1;FUT
nfurmer	nfurmeia	V;IND;PL;3;PRS;LGSPEC2
acrediter	acreditassa	V;IPFV;SBJV;PL;3;PST
autoriser	autorisé	V;NFIN;LGSPEC2
giudicher	giudicheie	V;SBJV;SG;1;PRS;LGSPEC2
lascer	lascer	V;NFIN;LGSPEC1
fisser	fisson	V;SBJV;PL;1;PRS
rater	ratova	V;IPFV;IND;PL;3;PST
atribuir	atribuissa	V;IPFV;SBJV;SG;3;PST
reprejenter	reprejente	V;SBJV;SG;1;PRS;LGSPEC1
someter	somete	V;SBJV;SG;3;PRS;LGSPEC1
curespuender	curespuendovan	V;IPFV;IND;PL;1;PST
segurer	segureie	V;IND;SG;1;PRS;LGSPEC2
sustenir	sustene	V;IND;SG;1;PRS;LGSPEC1
cogner	cogneia	V;NFIN;SG;2;LGSPEC2
giudicher	giudicheia	V;IND;SG;3;PRS;LGSPEC2
cunzeder	cunzed	V;IND;PL;3;PRS
schiver	schivova	V;IPFV;IND;PL;3;PST
coordener	coordenon	V;SBJV;PL;1;PRS
njinier	njiniaron	V;IND;PL;1;FUT
schiver	schives	V;SBJV;SG;2;PRS;LGSPEC1
determiner	determinova	V;IPFV;IND;SG;3;PST
mutiver	mutive	V;SBJV;SG;3;PRS;LGSPEC1
istruir	istruesce	V;SBJV;PL;3;PRS;LGSPEC2
emaner	emanassa	V;IPFV;SBJV;PL;3;PST
istituir	istituesce	V;SBJV;SG;1;PRS;LGSPEC2
danejer	danejon	V;SBJV;PL;1;PRS
furmer	furmovan	V;IPFV;IND;PL;1;PST
numiner	numinassa	V;IPFV;SBJV;SG;3;PST
condujer	condujaré	V;IND;SG;1;FUT
podei	podesse	V;IPFV;SBJV;SG;1;PST
rejoner	rejonareis	V;IND;PL;2;FUT
mander	mande	V;IND;SG;1;PRS;LGSPEC1
renunzier	renunziovan	V;IPFV;IND;PL;1;PST
dovei	dova	V;IPFV;IND;SG;3;PST;LGSPEC1
scurter	scurton	V;SBJV;PL;1;PRS
cruzier	cruzie	V;SBJV;PL;3;PRS
cuntroler	cuntrole	V;SBJV;SG;3;PRS;LGSPEC1
mpartir	mpartesc	V;IND;SG;3;PRS;LGSPEC2
alesirer	alesiré	V;NFIN;LGSPEC2
delibrer	delibrassa	V;IPFV;SBJV;SG;3;PST
segurer	segurova	V;IPFV;IND;SG;3;PST
franjer	franjova	V;IPFV;IND;SG;3;PST
cianter	cianton	V;SBJV;PL;1;PRS
cunferir	cunferes	V;SBJV;SG;2;PRS;LGSPEC1
assenier	assenieie	V;SBJV;SG;3;PRS;LGSPEC2
franjer	franje	V;SBJV;PL;3;PRS
sotscriver	sotscrivovais	V;IPFV;IND;PL;2;PST
cherder	cherdova	V;IPFV;IND;PL;3;PST
respuender	respuendasses	V;IPFV;SBJV;SG;2;PST
nascer	nascede	V;NFIN;PL;2
morir	morives	V;IPFV;IND;SG;2;PST
cumporter	cumporta	V;IND;PL;3;PRS;LGSPEC1
comprer	compreie	V;SBJV;SG;3;PRS;LGSPEC2
detlarer	detlarasses	V;IPFV;SBJV;SG;2;PST
volei	volon	V;IND;PL;1;PRS
dormir	dormives	V;IPFV;IND;SG;2;PST
corompe	corompe	V;SBJV;SG;3;PRS
mirer	mires	V;IND;SG;2;PRS;LGSPEC1
reguler	regulareis	V;IND;PL;2;FUT
resulter	resulta	V;IND;PL;3;PRS;LGSPEC1
limiter	limitoves	V;IPFV;IND;SG;2;PST
slunger	slungassa	V;IPFV;SBJV;PL;3;PST
garantir	garantireis	V;IND;PL;2;FUT
seurander	seurandova	V;IPFV;IND;SG;3;PST
rejoner	rejona	V;IND;SG;3;PRS;LGSPEC1
ejaminer	ejaminé	V;NFIN;LGSPEC2
scurter	scurte	V;SBJV;SG;1;PRS;LGSPEC1
goder	godassan	V;IPFV;SBJV;PL;1;PST
resserver	resserveies	V;IND;SG;2;PRS;LGSPEC2
comprer	compra	V;IND;SG;3;PRS;LGSPEC1
strenjer	strenjon	V;IND;PL;1;PRS
fisser	fisseie	V;SBJV;SG;3;PRS;LGSPEC2
tradujer	traduj	V;IND;SG;3;PRS
redujer	redujesses	V;IPFV;SBJV;SG;2;PST
curespuender	curespuendeies	V;SBJV;SG;2;PRS;LGSPEC2
corompe	corompe	V;NFIN;LGSPEC2
ndicher	ndichova	V;IPFV;IND;SG;3;PST
entenjer	entenj	V;IND;SG;3;PRS
seurander	seuranda	V;IND;PL;3;PRS;LGSPEC1
cherder	cherdon	V;IND;PL;1;PRS
parteziper	partezipe	V;SBJV;SG;3;PRS;LGSPEC1
seurander	seurandede	V;NFIN;PL;2
udir	udieis	V;SBJV;PL;2;PRS
autoriser	autorisassais	V;IPFV;SBJV;PL;2;PST
reguler	regulovais	V;IPFV;IND;PL;2;PST
dejeujer	dejëujarà	V;IND;SG;3;FUT
seurander	seurandeia	V;IND;PL;3;PRS;LGSPEC2
muder	mude	V;IND;SG;1;PRS;LGSPEC1
meter	mete	V;NFIN;LGSPEC2
resserver	resserveia	V;NFIN;SG;2;LGSPEC2
spidler	spidlede	V;NFIN;PL;2
gaujer	gaujeia	V;NFIN;SG;2;LGSPEC2
aplicher	apliché	V;NFIN;LGSPEC2
depenjer	depenjon	V;IND;PL;1;PRS
stabilir	stabilive	V;IPFV;IND;SG;1;PST
erjer	erjessais	V;IPFV;SBJV;PL;2;PST
arbitrer	arbitrasse	V;IPFV;SBJV;SG;1;PST
rezever	rezeve	V;SBJV;SG;3;PRS
promulgher	promulgheie	V;SBJV;SG;3;PRS;LGSPEC2
aproer	aproon	V;SBJV;PL;1;PRS
giudicher	giudicha	V;NFIN;SG;2;LGSPEC1
parteziper	partezipovan	V;IPFV;IND;PL;1;PST
ndrezer	ndrezeia	V;IND;SG;3;PRS;LGSPEC2
coordiner	coordineie	V;SBJV;SG;3;PRS;LGSPEC2
coordiner	coordinovais	V;IPFV;IND;PL;2;PST
mander	mandé	V;NFIN;LGSPEC2
avei	ebe	V;SBJV;SG;1;PRS;LGSPEC2
corompe	corompessa	V;IPFV;SBJV;SG;3;PST
pronunzier	pronunzieie	V;SBJV;SG;3;PRS;LGSPEC2
corompe	corompeis	V;SBJV;PL;2;PRS
aplicher	aplichassa	V;IPFV;SBJV;PL;3;PST
tramuder	tramude	V;IND;SG;1;PRS;LGSPEC1
perde	perdoves	V;IPFV;IND;SG;2;PST
someter	someter	V;NFIN;LGSPEC1
sotscriver	sotscrivaron	V;IND;PL;1;FUT
cruzier	cruziova	V;IPFV;IND;SG;3;PST
autoriser	autorisove	V;IPFV;IND;SG;1;PST
perder	perde	V;SBJV;SG;1;PRS
avei	ova	V;IPFV;IND;SG;3;PST;LGSPEC1
assegurer	asseguraras	V;IND;SG;2;FUT
destumer	destumassa	V;IPFV;SBJV;SG;3;PST
avei	esse	V;IPFV;SBJV;SG;1;PST;LGSPEC1
pronunzier	pronunzieie	V;SBJV;SG;1;PRS;LGSPEC2
dejeujer	dejëujasses	V;IPFV;SBJV;SG;2;PST
udir	udesces	V;IND;SG;2;PRS;LGSPEC2
coordiner	coordinaras	V;IND;SG;2;FUT
vegnì	vegneis	V;IND;PL;2;PRS
detlarer	detlarassais	V;IPFV;SBJV;PL;2;PST
sporjer	sporjova	V;IPFV;IND;PL;3;PST
reprejenter	reprejenté	V;NFIN;LGSPEC2
scurter	scurtasses	V;IPFV;SBJV;SG;2;PST
publicher	publicharon	V;IND;PL;1;FUT
slunger	slungovais	V;IPFV;IND;PL;2;PST
resulter	resultes	V;SBJV;SG;2;PRS;LGSPEC1
tramuder	tramudova	V;IPFV;IND;PL;3;PST
cunvalider	cunvalidaré	V;IND;SG;1;FUT
cruzier	cruzieia	V;IND;PL;3;PRS;LGSPEC2
emaner	emanassan	V;IPFV;SBJV;PL;1;PST
corompe	corompede	V;NFIN;PL;2
comprer	compreis	V;IND;PL;2;PRS
nascer	nasc	V;NFIN;SG;2
terjer	terjaron	V;IND;PL;1;FUT
emaner	emané	V;NFIN;LGSPEC2
plovei	piever	V;NFIN;LGSPEC2
arester	areste	V;SBJV;SG;3;PRS;LGSPEC1
ncurajer	ncurajarà	V;IND;SG;3;FUT
storjer	storjoves	V;IPFV;IND;SG;2;PST
segurer	segurea	V;IND;SG;3;PRS;LGSPEC3
desgorjer	desgorjova	V;IPFV;IND;PL;3;PST
viuler	viuleia	V;IND;PL;3;PRS;LGSPEC2
dé	desses	V;IPFV;SBJV;SG;2;PST
coster	costé	V;NFIN;LGSPEC2
cruzier	cruzieia	V;NFIN;SG;2;LGSPEC2
delegher	deleghede	V;NFIN;PL;2
revucher	revuchova	V;IPFV;IND;SG;3;PST
produjer	produjessais	V;IPFV;SBJV;PL;2;PST
prufesser	prufessova	V;IPFV;IND;PL;3;PST
rater	rateie	V;IND;SG;1;PRS;LGSPEC2
cunzeder	cunzedon	V;SBJV;PL;1;PRS
arbitrer	arbitres	V;IND;SG;2;PRS;LGSPEC1
cherder	cherdarà	V;IND;PL;3;FUT
sporjer	sporjarà	V;IND;SG;3;FUT
prufesser	prufessovan	V;IPFV;IND;PL;1;PST
reverir	reveresc	V;IND;PL;3;PRS;LGSPEC2
seurander	seurandareis	V;IND;PL;2;FUT
cumander	cumandove	V;IPFV;IND;SG;1;PST
sponjer	sponjaron	V;IND;PL;1;FUT
resserver	resservassa	V;IPFV;SBJV;PL;3;PST
mener	menaron	V;IND;PL;1;FUT
resulter	resultaré	V;IND;SG;1;FUT
capir	capiva	V;IPFV;IND;SG;3;PST
pruibir	pruibiron	V;IND;PL;1;FUT
spieter	spietassa	V;IPFV;SBJV;SG;3;PST
unir	une	V;SBJV;SG;1;PRS;LGSPEC1
aproer	aproasse	V;IPFV;SBJV;SG;1;PST
emaner	emana	V;NFIN;SG;2;LGSPEC1
desvier	desvieies	V;IND;SG;2;PRS;LGSPEC2
arbitrer	arbitreia	V;NFIN;SG;2;LGSPEC2
sponjer	sponjes	V;IND;SG;2;PRS
istituir	istituissais	V;IPFV;SBJV;PL;2;PST
stipuler	stipulasse	V;IPFV;SBJV;SG;1;PST
marider	maride	V;IND;SG;1;PRS;LGSPEC1
anuler	anulova	V;IPFV;IND;SG;3;PST
cruzier	cruzie	V;IND;SG;1;PRS;LGSPEC1
redujer	redujaré	V;IND;SG;1;FUT
apurver	apurvaré	V;IND;SG;1;FUT
ncurajer	ncurajovan	V;IPFV;IND;PL;1;PST
costituir	costituives	V;IPFV;IND;SG;2;PST
volei	volon	V;SBJV;PL;1;PRS
parteziper	partezipova	V;IPFV;IND;SG;3;PST
cogner	cogneis	V;IND;PL;2;PRS
urganiser	urganisaron	V;IND;PL;1;FUT
unir	univa	V;IPFV;IND;SG;3;PST
remander	remandove	V;IPFV;IND;SG;1;PST
dejeujer	dejëujova	V;IPFV;IND;SG;3;PST
delegher	delegha	V;IND;SG;3;PRS;LGSPEC1
sponjer	sponjova	V;IPFV;IND;PL;3;PST
gaujer	gaujova	V;IPFV;IND;PL;3;PST
rejoner	rejonova	V;IPFV;IND;SG;3;PST
destiner	destinaré	V;IND;SG;1;FUT
deslier	desliareis	V;IND;PL;2;FUT
manifester	manifeste	V;SBJV;SG;1;PRS;LGSPEC1
autoriser	autoriseia	V;IND;SG;3;PRS;LGSPEC2
dé	dova	V;IPFV;IND;PL;3;PST
curespuender	curespuendaras	V;IND;SG;2;FUT
scriver	scrivessais	V;IPFV;SBJV;PL;2;PST
afermer	afermassais	V;IPFV;SBJV;PL;2;PST
storjer	storje	V;SBJV;SG;1;PRS
ratificher	ratificharé	V;IND;SG;1;FUT
ndicher	ndichova	V;IPFV;IND;PL;3;PST
assegurer	assegureie	V;SBJV;SG;1;PRS;LGSPEC2
urganiser	urganisova	V;IPFV;IND;PL;3;PST
emaner	emane	V;IND;SG;1;PRS;LGSPEC1
manifester	manifestassa	V;IPFV;SBJV;PL;3;PST
seurander	seurandaré	V;IND;SG;1;FUT
pronunzier	pronunziova	V;IPFV;IND;PL;3;PST
promulgher	promulgharon	V;IND;PL;1;FUT
prejenter	prejentaron	V;IND;PL;1;FUT
vegnì	vegnes	V;SBJV;SG;2;PRS
sustenir	sustene	V;SBJV;SG;3;PRS;LGSPEC1
tramuder	tramudeia	V;NFIN;SG;2;LGSPEC2
cumporter	cumportassa	V;IPFV;SBJV;SG;3;PST
dejeujer	dejëujasse	V;IPFV;SBJV;SG;1;PST
ndicher	ndiche	V;SBJV;SG;1;PRS;LGSPEC1
furmer	furmareis	V;IND;PL;2;FUT
adoter	adotassa	V;IPFV;SBJV;SG;3;PST
spieter	spieteie	V;IND;SG;1;PRS;LGSPEC2
fisser	fissaré	V;IND;SG;1;FUT
dormir	dormieis	V;SBJV;PL;2;PRS
nfurmer	nfurmova	V;IPFV;IND;PL;3;PST
urganiser	urganisovais	V;IPFV;IND;PL;2;PST
jì	jide	V;NFIN;PL;2
tradujer	tradujaré	V;IND;SG;1;FUT
limiter	limitovais	V;IPFV;IND;PL;2;PST
aussei	ausse	V;SBJV;SG;1;PRS
sustenir	susteniron	V;IND;PL;1;FUT
avei	ae	V;SBJV;SG;1;PRS;LGSPEC1
danejer	danejarà	V;IND;SG;3;FUT
comunicher	comunicheie	V;SBJV;SG;1;PRS;LGSPEC2
comprer	comprarà	V;IND;PL;3;FUT
muder	mudea	V;IND;SG;3;PRS;LGSPEC3
desvier	desviasses	V;IPFV;SBJV;SG;2;PST
mirer	mira	V;IND;SG;3;PRS;LGSPEC1
eserziter	eserzitova	V;IPFV;IND;SG;3;PST
avei	ombe	V;SBJV;PL;1;PRS;LGSPEC2
istruir	istruì	V;NFIN;LGSPEC2
cundaner	cundanede	V;NFIN;PL;2
coordiner	coordina	V;IND;PL;3;PRS;LGSPEC1
vedei	vedareis	V;IND;PL;2;FUT
emaner	emaner	V;NFIN;LGSPEC1
mander	mandeie	V;SBJV;SG;1;PRS;LGSPEC2
reguler	regules	V;IND;SG;2;PRS;LGSPEC1
ndrezer	ndreze	V;SBJV;SG;1;PRS;LGSPEC1
mander	mandeies	V;IND;SG;2;PRS;LGSPEC2
tradujer	tradujon	V;IND;PL;1;PRS
rater	rater	V;NFIN;LGSPEC1
mirer	mira	V;IND;PL;3;PRS;LGSPEC1
jì	jissais	V;IPFV;SBJV;PL;2;PST
nfurmer	nfurmeis	V;SBJV;PL;2;PRS
spidler	spidleie	V;SBJV;SG;3;PRS;LGSPEC2
coordener	coordene	V;IND;SG;1;PRS;LGSPEC1
avei	aron	V;IND;PL;1;FUT
entenjer	entenjessa	V;IPFV;SBJV;SG;3;PST
produjer	produjeis	V;SBJV;PL;2;PRS
cuntroler	cuntroleia	V;IND;PL;3;PRS;LGSPEC2
emaner	emanarà	V;IND;PL;3;FUT
rejoner	rejonassan	V;IPFV;SBJV;PL;1;PST
terjer	terjovan	V;IPFV;IND;PL;1;PST
populer	populeies	V;IND;SG;2;PRS;LGSPEC2
assegurer	assegurova	V;IPFV;IND;PL;3;PST
mutiver	mutiveia	V;IND;PL;3;PRS;LGSPEC2
tramuder	tramudove	V;IPFV;IND;SG;1;PST
reverir	reveresces	V;SBJV;SG;2;PRS;LGSPEC2
alesirer	alesira	V;IND;PL;3;PRS;LGSPEC1
comunicher	comunichea	V;IND;SG;3;PRS;LGSPEC3
acuser	acuseia	V;IND;PL;3;PRS;LGSPEC2
corompe	corompes	V;SBJV;SG;2;PRS
jonjer	jonjarà	V;IND;PL;3;FUT
istituir	istituir	V;NFIN;LGSPEC1
apurver	apurvova	V;IPFV;IND;SG;3;PST
resulter	resulta	V;IND;SG;3;PRS;LGSPEC1
afermer	afermova	V;IPFV;IND;SG;3;PST
vegnì	vegnirà	V;IND;SG;3;FUT
vedei	vedarà	V;IND;PL;3;FUT
publicher	publicheie	V;SBJV;SG;3;PRS;LGSPEC2
nfurmer	nfurmes	V;SBJV;SG;2;PRS;LGSPEC1
cianter	ciantes	V;IND;SG;2;PRS;LGSPEC1
finanzier	finanziovan	V;IPFV;IND;PL;1;PST
vedei	veides	V;IND;SG;2;PRS
gaujer	gauja	V;IND;SG;3;PRS;LGSPEC1
mirer	mire	V;SBJV;SG;1;PRS;LGSPEC1
apurver	apurva	V;IND;PL;3;PRS;LGSPEC1
ejaminer	ejamine	V;SBJV;SG;1;PRS;LGSPEC1
remplazer	remplazes	V;SBJV;SG;2;PRS;LGSPEC1
danejer	danejovais	V;IPFV;IND;PL;2;PST
cuntroler	cuntroleies	V;SBJV;SG;2;PRS;LGSPEC2
purter	purteis	V;IND;PL;2;PRS
aussei	ausses	V;SBJV;SG;2;PRS
liter	litova	V;IPFV;IND;PL;3;PST
rezever	rezevareis	V;IND;PL;2;FUT
viuler	viule	V;SBJV;SG;1;PRS;LGSPEC1
marider	marideia	V;IND;SG;3;PRS;LGSPEC2
coster	costea	V;IND;SG;3;PRS;LGSPEC3
adater	adatova	V;IPFV;IND;PL;3;PST
atribuir	atribu	V;NFIN;SG;2;LGSPEC1
fisser	fissa	V;NFIN;SG;2;LGSPEC1
morir	moriras	V;IND;SG;2;FUT
mantenir	manteniva	V;IPFV;IND;SG;3;PST
anuler	anuleia	V;NFIN;SG;2;LGSPEC2
dormir	dormion	V;IND;PL;1;PRS
tramuder	tramudede	V;NFIN;PL;2
njinier	njiniede	V;NFIN;PL;2
determiner	determine	V;SBJV;SG;3;PRS;LGSPEC1
populer	popules	V;SBJV;SG;2;PRS;LGSPEC1
erjer	erje	V;SBJV;SG;3;PRS
resserver	resservarà	V;IND;PL;3;FUT
condujer	conduje	V;NFIN;LGSPEC2
adurver	adurvarà	V;IND;PL;3;FUT
acurder	acurdaras	V;IND;SG;2;FUT
romper	rompon	V;IND;PL;1;PRS
reverir	reverì	V;NFIN;LGSPEC2
azerter	azerta	V;IND;PL;3;PRS;LGSPEC1
messei	messarà	V;IND;SG;3;FUT
reverir	reveriva	V;IPFV;IND;SG;3;PST
destiner	destineis	V;SBJV;PL;2;PRS
seurander	seurande	V;SBJV;SG;1;PRS;LGSPEC1
delegher	deleghes	V;IND;SG;2;PRS;LGSPEC1
spartir	spartireis	V;IND;PL;2;FUT
determiner	determineie	V;SBJV;SG;3;PRS;LGSPEC2
adater	adata	V;IND;SG;3;PRS;LGSPEC1
deslier	desliova	V;IPFV;IND;SG;3;PST
sustenir	sustenesc	V;NFIN;SG;2;LGSPEC2
fisser	fisseia	V;IND;PL;3;PRS;LGSPEC2
trater	tratede	V;NFIN;PL;2
usserver	usservovais	V;IPFV;IND;PL;2;PST
arjonjer	arjonjon	V;SBJV;PL;1;PRS
spartir	spartesces	V;SBJV;SG;2;PRS;LGSPEC2
scurter	scurtea	V;IND;SG;3;PRS;LGSPEC3
viver	vivessa	V;IPFV;SBJV;SG;3;PST
rester	resta	V;NFIN;SG;2;LGSPEC1
atuer	atuea	V;IND;SG;3;PRS;LGSPEC3
dejeujer	dejëujassa	V;IPFV;SBJV;PL;3;PST
jì	jon	V;IND;PL;1;PRS
capir	capì	V;NFIN;LGSPEC2
proibir	proibive	V;IPFV;IND;SG;1;PST
cruzier	cruziaras	V;IND;SG;2;FUT
pronunzier	pronunziove	V;IPFV;IND;SG;1;PST
aussei	aussaré	V;IND;SG;1;FUT
ancunter	ancuntassais	V;IPFV;SBJV;PL;2;PST
registrer	registres	V;IND;SG;2;PRS;LGSPEC1
aproer	aproeies	V;SBJV;SG;2;PRS;LGSPEC2
ncurajer	ncurajon	V;IND;PL;1;PRS
reprejenter	reprejentes	V;IND;SG;2;PRS;LGSPEC1
ester	é	V;IND;SG;3;PRS
renunzier	renunziaras	V;IND;SG;2;FUT
cumporter	cumporté	V;NFIN;LGSPEC2
urganiser	urganisarà	V;IND;PL;3;FUT
educher	educhoves	V;IPFV;IND;SG;2;PST
ressolver	ressolveis	V;IND;PL;2;PRS
trasferir	trasferivan	V;IPFV;IND;PL;1;PST
azerter	azerter	V;NFIN;LGSPEC1
rezever	rezevessais	V;IPFV;SBJV;PL;2;PST
njinier	njinion	V;SBJV;PL;1;PRS
ratificher	ratifichassan	V;IPFV;SBJV;PL;1;PST
costituir	costituisse	V;IPFV;SBJV;SG;1;PST
unir	unes	V;IND;SG;2;PRS;LGSPEC1
ndrezer	ndreze	V;SBJV;SG;3;PRS;LGSPEC1
rezever	rezeve	V;SBJV;PL;3;PRS
viuler	viulovan	V;IPFV;IND;PL;1;PST
detlarer	detlaroves	V;IPFV;IND;SG;2;PST
perder	perdova	V;IPFV;IND;PL;3;PST
goder	goda	V;NFIN;SG;2;LGSPEC1
coordiner	coordinede	V;NFIN;PL;2
apurver	apurveia	V;IND;PL;3;PRS;LGSPEC2
arester	arestovais	V;IPFV;IND;PL;2;PST
dovei	dess	V;IND;SG;3;PRS
atribuir	atribuide	V;NFIN;PL;2
romper	rompessais	V;IPFV;SBJV;PL;2;PST
capir	capiras	V;IND;SG;2;FUT
podei	podarà	V;IND;PL;3;FUT
cunvalider	cunvalidova	V;IPFV;IND;PL;3;PST
marider	maridaré	V;IND;SG;1;FUT
aussei	ausse	V;SBJV;PL;3;PRS
marider	maridassan	V;IPFV;SBJV;PL;1;PST
manifester	manifestaras	V;IND;SG;2;FUT
costituir	costitues	V;IND;SG;2;PRS;LGSPEC1
capir	capiva	V;IPFV;IND;PL;3;PST
udir	ude	V;SBJV;SG;3;PRS;LGSPEC1
afermer	aferma	V;IND;PL;3;PRS;LGSPEC1
udir	udiva	V;IPFV;IND;PL;3;PST
mantenir	mantenesc	V;IND;PL;3;PRS;LGSPEC2
ncurajer	ncurajeie	V;SBJV;SG;1;PRS;LGSPEC2
rejoner	rejonea	V;IND;SG;3;PRS;LGSPEC3
resserver	resserveie	V;SBJV;SG;3;PRS;LGSPEC2
partir	partieis	V;SBJV;PL;2;PRS
dormir	dormesces	V;SBJV;SG;2;PRS;LGSPEC2
onjer	onjaré	V;IND;SG;1;FUT
udir	udissais	V;IPFV;SBJV;PL;2;PST
tramuder	tramude	V;SBJV;SG;3;PRS;LGSPEC1
vedei	veide	V;SBJV;SG;1;PRS
ndrezer	ndrezareis	V;IND;PL;2;FUT
atuer	atuon	V;SBJV;PL;1;PRS
urganiser	urganisea	V;IND;SG;3;PRS;LGSPEC3
cianter	ciantovan	V;IPFV;IND;PL;1;PST
numiner	numinasse	V;IPFV;SBJV;SG;1;PST
stabilir	stabilirà	V;IND;PL;3;FUT
terjer	terjede	V;NFIN;PL;2
terjer	terje	V;NFIN;LGSPEC2
depenjer	depenjessa	V;IPFV;SBJV;SG;3;PST
remander	remandassa	V;IPFV;SBJV;SG;3;PST
mpartir	mpartissa	V;IPFV;SBJV;SG;3;PST
mander	mande	V;SBJV;SG;3;PRS;LGSPEC1
costituir	costituieis	V;IND;PL;2;PRS
dormir	dormesce	V;SBJV;SG;1;PRS;LGSPEC2
remplazer	remplazeia	V;IND;PL;3;PRS;LGSPEC2
comunicher	comunicharà	V;IND;PL;3;FUT
renunzier	renunzion	V;IND;PL;1;PRS
capir	capireis	V;IND;PL;2;FUT
meter	metes	V;IND;SG;2;PRS
ester	fosse	V;IPFV;SBJV;SG;1;PST
spartir	sparte	V;SBJV;PL;3;PRS;LGSPEC1
produjer	produj	V;IND;SG;3;PRS
terjer	terje	V;SBJV;SG;1;PRS
aproer	aproea	V;IND;SG;3;PRS;LGSPEC3
storjer	storjeis	V;SBJV;PL;2;PRS
ancunter	ancunteis	V;IND;PL;2;PRS
gaujer	gaujeie	V;SBJV;SG;3;PRS;LGSPEC2
dovei	desse	V;SBJV;PL;3;PRS
dejeujer	dejëujé	V;NFIN;LGSPEC2
gaujer	gaujeie	V;IND;SG;1;PRS;LGSPEC2
udir	ud	V;IND;PL;3;PRS;LGSPEC1
adater	adate	V;SBJV;SG;1;PRS;LGSPEC1
mpartir	mpartiva	V;IPFV;IND;PL;3;PST
reprejenter	reprejenteis	V;IND;PL;2;PRS
promulgher	promulgheis	V;SBJV;PL;2;PRS
comprer	comproves	V;IPFV;IND;SG;2;PST
coordiner	coordineie	V;SBJV;SG;1;PRS;LGSPEC2
remander	remande	V;SBJV;PL;3;PRS
storjer	storj	V;IND;SG;3;PRS
depenjer	depenjaras	V;IND;SG;2;FUT
ejaminer	ejaminovais	V;IPFV;IND;PL;2;PST
arester	arestasses	V;IPFV;SBJV;SG;2;PST
storjer	storjaron	V;IND;PL;1;FUT
numiner	numinassan	V;IPFV;SBJV;PL;1;PST
rezever	rezevessa	V;IPFV;SBJV;SG;3;PST
coster	costassa	V;IPFV;SBJV;PL;3;PST
emaner	emaneie	V;SBJV;SG;1;PRS;LGSPEC2
muder	mudovan	V;IPFV;IND;PL;1;PST
mander	mandaras	V;IND;SG;2;FUT
stabilir	stabilesces	V;SBJV;SG;2;PRS;LGSPEC2
reurganiser	reurganisaré	V;IND;SG;1;FUT
numiner	numina	V;IND;SG;3;PRS;LGSPEC1
viuler	viularas	V;IND;SG;2;FUT
mener	menassa	V;IPFV;SBJV;PL;3;PST
desvier	desviasse	V;IPFV;SBJV;SG;1;PST
respuender	respuendede	V;NFIN;PL;2
registrer	registreia	V;IND;SG;3;PRS;LGSPEC2
perder	perdovan	V;IPFV;IND;PL;1;PST
muder	mudova	V;IPFV;IND;SG;3;PST
lascer	lascareis	V;IND;PL;2;FUT
perdujer	perdujoves	V;IPFV;IND;SG;2;PST
rezever	rezevaré	V;IND;SG;1;FUT
promulgher	promulghova	V;IPFV;IND;SG;3;PST
istituir	istituion	V;SBJV;PL;1;PRS
manifester	manifeste	V;SBJV;PL;3;PRS
usserver	usserveia	V;IND;PL;3;PRS;LGSPEC2
spidler	spidlassa	V;IPFV;SBJV;PL;3;PST
azerter	azerton	V;IND;PL;1;PRS
goder	goder	V;NFIN;LGSPEC1
arbitrer	arbitreis	V;SBJV;PL;2;PRS
scurter	scurta	V;NFIN;SG;2;LGSPEC1
marider	maridova	V;IPFV;IND;SG;3;PST
jonjer	jonjessan	V;IPFV;SBJV;PL;1;PST
corompe	coromp	V;IND;PL;3;PRS
coordener	coordeneis	V;SBJV;PL;2;PRS
savei	savaron	V;IND;PL;1;FUT
trater	trateie	V;SBJV;SG;3;PRS;LGSPEC2
mantenir	mantenesce	V;SBJV;SG;1;PRS;LGSPEC2
revucher	revuchoves	V;IPFV;IND;SG;2;PST
cunzeder	cunzede	V;SBJV;SG;3;PRS
damander	damandarà	V;IND;SG;3;FUT
dovei	desson	V;IND;PL;1;PRS
corompe	coromper	V;NFIN;LGSPEC1
unir	unesce	V;SBJV;SG;1;PRS;LGSPEC2
remander	remandon	V;SBJV;PL;1;PRS
trasferir	trasferiré	V;IND;SG;1;FUT
furmer	furmes	V;SBJV;SG;2;PRS;LGSPEC1
vegnì	vegnireis	V;IND;PL;2;FUT
storjer	storje	V;NFIN;LGSPEC2
ndrezer	ndrezarà	V;IND;SG;3;FUT
atribuir	atribuivais	V;IPFV;IND;PL;2;PST
cuntroler	cuntrolea	V;IND;SG;3;PRS;LGSPEC3
cunzeder	cunzede	V;NFIN;LGSPEC2
giudicher	giudichova	V;IPFV;IND;SG;3;PST
eserziter	eserzitasses	V;IPFV;SBJV;SG;2;PST
cumander	cumandeia	V;NFIN;SG;2;LGSPEC2
