dünya	dünyamızdan	N;ABL;SG;PSS3P
uşaqlıq	uşaqlıqlarımızda	N;LOC;PL;PSS3P
dünya	dünyalarımızda	N;LOC;PL;PSS3P
düşmən	düşmənləri	N;NOM;PL;PSS3P
qardaş	qardaşını	N;ACC;SG;PSS3P
lüğət	lüğətlərin	N;GEN;DEF;PL
kəfgir	kəfgirlərdən	N;ABL;PL
yemiş	yemişlərini	N;ACC;PL;PSS3P
məktəb	məktəbin	N;NOM;SG;PSS2S
rəhbər	rəhbərimiz	N;NOM;SG;PSS3P
namaz	namazlarını	N;ACC;PL;PSS3P
onurğa	onurğalarına	N;DAT;PL;PSS3P
amfiteatr	amfiteatrdan	N;ABL;SG
pilləkən	pilləkənlərdə	N;LOC;PL
qan	qanlar	N;NOM;PL
əqrəb	əqrəbində	N;LOC;SG;PSS2S
ilan	ilana	N;ACC;DEF;SG
ərik	əriklərində	N;LOC;PL;PSS3P
hörümçək	hörümçəyi	N;ACC;DEF;SG
hüceyrə	hüceyrələr	N;NOM;PL
qoxu	qoxularımızı	N;ACC;PL;PSS3P
beyin	beyninin	N;GEN;SG;PSS2S
tilişkə	tilişkədən	N;ABL;SG
dirsək	dirsəklərinizi	N;ACC;PL;PSS2P
namaz	namazı	N;ACC;DEF;SG
dolab	dolabdan	N;ABL;SG
sümük	sümüyümdə	N;LOC;SG;PSS1S
tələbə	tələbəmə	N;DAT;SG;PSS1S
alət	alətlərimin	N;GEN;PL;PSS1S
ulduz	ulduzların	N;GEN;DEF;PL
ağac	ağacı	N;ACC;DEF;SG
gəmi	gəmilərə	N;ACC;DEF;PL
bıçaq	bıçaqlarım	N;NOM;PL;PSS1S
armud	armudda	N;LOC;SG
tüstü	tüstülərdə	N;LOC;PL
zoğ	zoğu	N;ACC;DEF;SG
tərcümə	tərcümələrimdən	N;ABL;PL;PSS1S
sabun	sabunu	N;ACC;DEF;SG
alça	alçama	N;DAT;SG;PSS1S
sümük	sümüyünü	N;ACC;SG;PSS3P
xloroplast	xloroplastları	N;ACC;DEF;PL
nar	narlar	N;NOM;PL
dodaq	dodaqlara	N;ACC;DEF;PL
yağış	yağışı	N;ACC;DEF;SG
nəfəs	nəfəsdə	N;LOC;SG
ayaqqabı	ayaqqabılardan	N;ABL;PL
beyin	beynimizi	N;ACC;SG;PSS3P
kölgə	kölgəsinə	N;DAT;SG;PSS3S
dünya	dünyalarının	N;GEN;PL;PSS2S
dinozavr	dinozavrlarımızın	N;GEN;PL;PSS3P
əqrəb	əqrəblərimizin	N;GEN;PL;PSS3P
ereksiya	ereksiyalarımdan	N;ABL;PL;PSS1S
kömək	köməklərində	N;LOC;PL;PSS3S
vertolyot	vertolyotun	N;GEN;DEF;SG
kömək	köməyiniz	N;NOM;SG;PSS2P
açar	açarına	N;DAT;SG;PSS2S
buynuz	buynuzun	N;GEN;DEF;SG
hüceyrə	hüceyrələrimdən	N;ABL;PL;PSS1S
ad	adları	N;ACC;DEF;PL
nəticə	nəticələrə	N;ACC;DEF;PL
göbək	göbəyin	N;GEN;DEF;SG
dünya	dünyalarını	N;ACC;PL;PSS3S
mətbəx	mətbəxdə	N;LOC;SG
xəzinə	xəzinələrimə	N;DAT;PL;PSS1S
hüceyrə	hüceyrələrimdə	N;LOC;PL;PSS1S
məktəb	məktəbdə	N;LOC;SG
kömək	köməklərin	N;GEN;DEF;PL
hinduşka	hinduşkalara	N;ACC;DEF;PL
geodeziya	geodeziyalar	N;NOM;PL
rəngləmək	rənglədiniz	V;PL;2;PST
bardaq	bardaqdan	N;ABL;SG
baldız	baldızının	N;GEN;SG;PSS3P
kəfgir	kəfgirinə	N;DAT;SG;PSS2S
düşərgə	düşərgəni	N;ACC;DEF;SG
müzakirə	müzakirələrimdən	N;ABL;PL;PSS1S
hinduşka	hinduşkaya	N;ACC;DEF;SG
tələbə	tələbələrin	N;NOM;PL;PSS2S
müzakirə	müzakirələrdə	N;LOC;PL
qarğa	qarğalardan	N;ABL;PL
qoxu	qoxunda	N;LOC;SG;PSS2S
ereksiya	ereksiyası	N;NOM;SG;PSS3P
bozbaş	bozbaşa	N;ACC;DEF;SG
rəhbər	rəhbərində	N;LOC;SG;PSS3S
baldız	baldızları	N;NOM;PL;PSS3S
balıq	balıqlara	N;ACC;DEF;PL
biçin	biçindən	N;ABL;SG
ana	anaların	N;GEN;DEF;PL
od	od	N;NOM;SG
dinozavr	dinozavrlarda	N;LOC;PL
qoxu	qoxum	N;NOM;SG;PSS1S
badam	badamı	N;ACC;DEF;SG
kömək	köməkdən	N;ABL;SG
leşyeyən	leşyeyənlər	N;NOM;PL
mələk	mələklərinizi	N;ACC;PL;PSS2P
piano	pianolarda	N;LOC;PL
minbər	minbərlərdə	N;LOC;PL
qardaş	qardaşımıza	N;DAT;SG;PSS3P
şamisen	şamisendən	N;ABL;SG
beyin	beynimi	N;ACC;SG;PSS1S
xər	xərlər	N;NOM;PL
onurğa	onurğanda	N;LOC;SG;PSS2S
mənzərə	mənzərələrimizin	N;GEN;PL;PSS3P
penis	penislərimiz	N;NOM;PL;PSS3P
ay	aya	N;ACC;DEF;SG
namaz	namazlardan	N;ABL;PL
arxiv	arxivlərinin	N;GEN;PL;PSS2S
qardaş	qardaşınızdan	N;ABL;SG;PSS2P
qoxu	qoxularına	N;DAT;PL;PSS2S
onurğa	onurğalara	N;ACC;DEF;PL
xəstəlik	xəstəliklərdə	N;LOC;PL
inək	inəklərin	N;GEN;DEF;PL
okean	okean	N;NOM;SG
dinozavr	dinozavrlarımızda	N;LOC;PL;PSS3P
əqrəb	əqrəblərə	N;ACC;DEF;PL
qardaşlıq	qardaşlıqlarda	N;LOC;PL
vəziyyət	vəziyyətində	N;LOC;SG;PSS3S
ağlamaq	ağladım	V;SG;1;PST
kəfgir	kəfgirlər	N;NOM;PL
xoruz	xoruzun	N;GEN;DEF;SG
od	odda	N;LOC;SG
namaz	namazlarına	N;DAT;PL;PSS3S
kəfgir	kəfgirimdən	N;ABL;SG;PSS1S
rəssam	rəssamı	N;ACC;DEF;SG
gülüş	gülüşlərimiz	N;NOM;PL;PSS3P
mələk	mələklərinizdə	N;LOC;PL;PSS2P
qoxu	qoxuların	N;GEN;DEF;PL
bacı	bacın	N;NOM;SG;PSS2S
dəmir	dəmirlər	N;NOM;PL
kəfgir	kəfgirlərindən	N;ABL;PL;PSS3S
müzakirə	müzakirələrinizdən	N;ABL;PL;PSS2P
dəmir	dəmir	N;NOM;SG
ereksiya	ereksiyanızdan	N;ABL;SG;PSS2P
ad	adlar	N;NOM;PL
hörümçək	hörümçəyimin	N;GEN;SG;PSS1S
buz	buzun	N;GEN;DEF;SG
əqrəb	əqrəbim	N;NOM;SG;PSS1S
rəhbər	rəhbərə	N;ACC;DEF;SG
ağacdələn	ağacdələnə	N;ACC;DEF;SG
tərcümə	tərcümələrdə	N;LOC;PL
qaçmaq	qaçacaqsan	V;SG;2;FUT
xoruz	xoruzlardan	N;ABL;PL
rəhbər	rəhbərlərimdə	N;LOC;PL;PSS1S
şirkət	şirkətlərin	N;GEN;DEF;PL
ada	adalara	N;ACC;DEF;PL
rəhbər	rəhbərlərdə	N;LOC;PL
işıq	işıq	N;NOM;SG
çiyələk	çiyələklərin	N;GEN;DEF;PL
şəhər	şəhərdə	N;LOC;SG
jasmin	jasminlərin	N;GEN;DEF;PL
yəhudi	yəhudidə	N;LOC;SG
dırnaq	dırnaqlarını	N;ACC;PL;PSS3P
hüceyrə	hüceyrələrinin	N;GEN;PL;PSS3P
kəfgir	kəfgirlərinizin	N;GEN;PL;PSS2P
ereksiya	ereksiyaların	N;GEN;DEF;PL
rəhbər	rəhbərlərində	N;LOC;PL;PSS3P
balalayka	balalaykada	N;LOC;SG
dırnaq	dırnaqlarına	N;DAT;PL;PSS2S
gülüş	gülüşümüz	N;NOM;SG;PSS3P
gülüş	gülüşləri	N;ACC;DEF;PL
kamerton	kamertonların	N;GEN;DEF;PL
bozbaş	bozbaşlara	N;ACC;DEF;PL
şaftalı	şaftalılarımızın	N;GEN;PL;PSS3P
kraliça	kraliçalarımın	N;GEN;PL;PSS1S
qəlsəmə	qəlsəmələr	N;NOM;PL
dalğa	dalğası	N;NOM;SG;PSS3S
qardaş	qardaşın	N;NOM;SG;PSS2S
dırnaq	dırnağında	N;LOC;SG;PSS3S
qaçqın	qaçqını	N;ACC;DEF;SG
özünüidarəetmə	özünüidarəetmələrdə	N;LOC;PL
hörümçək	hörümçəyin	N;NOM;SG;PSS2S
qarğa	qarğaları	N;ACC;DEF;PL
qaloş	qaloşa	N;ACC;DEF;SG
qulaq	qulaqlarında	N;LOC;PL;PSS2S
mələk	mələkdən	N;ABL;SG
soğan	soğandan	N;ABL;SG
günəş	günəşə	N;ACC;DEF;SG
ağlamaq	ağladıq	V;PL;1;PST
açar	açarlarında	N;LOC;PL;PSS3P
rəng	rənglərə	N;ACC;DEF;PL
ərik	ərikləri	N;ACC;DEF;PL
ana	ananızdan	N;ABL;SG;PSS2P
içmək	içdik	V;PL;1;PST
fəaliyyət	fəaliyyətlərimiz	N;NOM;PL;PSS3P
onurğa	onurğanız	N;NOM;SG;PSS2P
ereksiya	ereksiyası	N;NOM;SG;PSS3S
dəvəquşu	dəvəquşlarının	N;GEN;DEF;PL
sümük	sümüklərinə	N;DAT;PL;PSS3P
qurbağa	qurbağalarda	N;LOC;PL
əqrəb	əqrəbinin	N;GEN;SG;PSS3S
şaftalı	şaftalınız	N;NOM;SG;PSS2P
ördək	ördəkdə	N;LOC;SG
kraliça	kraliçan	N;NOM;SG;PSS2S
açar	açarlarımızda	N;LOC;PL;PSS3P
dırnaq	dırnağınızı	N;ACC;SG;PSS2P
gülüş	gülüşümüzə	N;DAT;SG;PSS3P
fahişə	fahişələr	N;NOM;PL
rəndə	rəndələrə	N;ACC;DEF;PL
ağacdələn	ağacdələnlərdə	N;LOC;PL
bəbək	bəbəyin	N;GEN;DEF;SG
qaçmaq	qaçdıq	V;PL;1;PST
alça	alçalarında	N;LOC;PL;PSS2S
soğan	soğanlarda	N;LOC;PL
qalibiyyət	qalibiyyətlərin	N;GEN;DEF;PL
dinozavr	dinozavrınız	N;NOM;SG;PSS2P
qatar	qatarda	N;LOC;SG
çiçək	çiçək	N;NOM;SG
ət	ətlərdə	N;LOC;PL
fırtına	fırtınalar	N;NOM;PL
yemiş	yemişimin	N;GEN;SG;PSS1S
od	oda	N;ACC;DEF;SG
süngü	süngünü	N;ACC;SG;PSS2S
təsadüf	təsadüflərdə	N;LOC;PL
hüceyrə	hüceyrələrin	N;NOM;PL;PSS2S
beyin	beynimin	N;GEN;SG;PSS1S
arxiv	arxivinə	N;DAT;SG;PSS3P
köynək	köynəyimi	N;ACC;SG;PSS1S
arxiv	arxivinizə	N;DAT;SG;PSS2P
düşman	düşmanını	N;ACC;SG;PSS3P
quyruq	quyruqlardan	N;ABL;PL
bacı	bacımıza	N;DAT;SG;PSS3P
uşaqlıq	uşaqlığımın	N;GEN;SG;PSS1S
sümük	sümüyünə	N;DAT;SG;PSS3S
ad	adların	N;GEN;DEF;PL
kişi	kişilərdə	N;LOC;PL
dünya	dünyanızdan	N;ABL;SG;PSS2P
çiyələk	çiyələyin	N;GEN;DEF;SG
brilyant	brilyantlardan	N;ABL;PL
buynuz	buynuzlarını	N;ACC;PL;PSS3S
qulaq	qulaqlarımızın	N;GEN;PL;PSS3P
baldız	baldızlarımızdan	N;ABL;PL;PSS3P
mənzərə	mənzərələrinizi	N;ACC;PL;PSS2P
dəyirman	dəyirmanların	N;GEN;DEF;PL
ərik	əriklərimizdən	N;ABL;PL;PSS3P
müzakirə	müzakirələrinə	N;DAT;PL;PSS3S
xloroplast	xloroplastdan	N;ABL;SG
bibər	bibərlərin	N;GEN;DEF;PL
açar	açarlarımdan	N;ABL;PL;PSS1S
uşaqlıq	uşaqlıqlarında	N;LOC;PL;PSS2S
mələk	mələklərimizdə	N;LOC;PL;PSS3P
qulaq	qulağında	N;LOC;SG;PSS3P
mənzərə	mənzərəsində	N;LOC;SG;PSS3P
ayaq	ayaqları	N;ACC;DEF;PL
əqrəb	əqrəbinizin	N;GEN;SG;PSS2P
oturmaq	otururlar	V;PROG;PL;3;PRS
şənbə	şənbədən	N;ABL;SG
bülbül	bülbülə	N;ACC;DEF;SG
həqiqət	həqiqətə	N;ACC;DEF;SG
mələk	mələkləri	N;NOM;PL;PSS3P
dirsək	dirsəklərinizdə	N;LOC;PL;PSS2P
vəziyyət	vəziyyətlərində	N;LOC;PL;PSS3S
ərik	əriyimizdən	N;ABL;SG;PSS3P
namaz	namazımız	N;NOM;SG;PSS3P
dalğa	dalğalarımda	N;LOC;PL;PSS1S
qəlb	qəlblərimizdən	N;ABL;PL;PSS3P
kəlbətin	kəlbətinləri	N;ACC;DEF;PL
köynək	köynəyindən	N;ABL;SG;PSS2S
kraliça	kraliçaların	N;GEN;DEF;PL
rəhbər	rəhbərlərinizin	N;GEN;PL;PSS2P
rəhbər	rəhbərinizin	N;GEN;SG;PSS2P
darçın	darçınlardan	N;ABL;PL
tərcümə	tərcümələrimiz	N;NOM;PL;PSS3P
vaza	vazalarından	N;ABL;PL;PSS3S
gülüş	gülüşlərdən	N;ABL;PL
onurğa	onurğalarında	N;LOC;PL;PSS3S
penis	penislərin	N;NOM;PL;PSS2S
kraliça	kraliçamda	N;LOC;SG;PSS1S
süngü	süngünüz	N;NOM;SG;PSS2P
dünya	dünyandan	N;ABL;SG;PSS2S
mənzərə	mənzərələrdə	N;LOC;PL
dinozavr	dinozavrları	N;NOM;PL;PSS3P
alət	alətinizə	N;DAT;SG;PSS2P
tərcümə	tərcümələrin	N;GEN;DEF;PL
penis	penisimdə	N;LOC;SG;PSS1S
motosiklet	motosiklet	N;NOM;SG
tilişkə	tilişkənin	N;GEN;DEF;SG
müqayisə	müqayisələr	N;NOM;PL
söz	sözlərdən	N;ABL;PL
kölgə	kölgəmizdən	N;ABL;SG;PSS3P
bazar	bazarlarda	N;LOC;PL
köpük	köpükdən	N;ABL;SG
xəritə	xəritəni	N;ACC;SG;PSS2S
temperatur	temperaturları	N;ACC;DEF;PL
xəzinə	xəzinəmizin	N;GEN;SG;PSS3P
tarix	tarixlərdə	N;LOC;PL
mənzərə	mənzərələrinizdən	N;ABL;PL;PSS2P
balalayka	balalaykanın	N;GEN;DEF;SG
dövri cədvəl	dövri cədvəl	N;NOM;SG
donuz	donuzların	N;GEN;DEF;PL
düşman	düşmanınızda	N;LOC;SG;PSS2P
sümük	sümüklərə	N;ACC;DEF;PL
ox	oxlar	N;NOM;PL
mənzərə	mənzərəmiz	N;NOM;SG;PSS3P
kraliça	kraliçalarının	N;GEN;PL;PSS3P
süngü	süngüləri	N;NOM;PL;PSS3P
vaza	vazalarına	N;DAT;PL;PSS3P
bacı	bacılarıma	N;DAT;PL;PSS1S
onurğa	onurğalarımda	N;LOC;PL;PSS1S
bıçaq	bıçağından	N;ABL;SG;PSS3P
penis	penislərimizdə	N;LOC;PL;PSS3P
elektron poçt	elektron poçt	N;NOM;SG
vertolyot	vertolyotlara	N;ACC;DEF;PL
göyərçin	göyərçində	N;LOC;SG
ərik	əriyi	N;ACC;DEF;SG
hüceyrə	hüceyrəndən	N;ABL;SG;PSS2S
beyin	beyinləriniz	N;NOM;PL;PSS2P
zəfər	zəfərlərin	N;GEN;DEF;PL
məktəb	məktəblərdən	N;ABL;PL
geyşa	geyşanın	N;GEN;DEF;SG
lüğət	lüğətin	N;GEN;DEF;SG
qatar	qatardan	N;ABL;SG
dünya	dünyamıza	N;DAT;SG;PSS3P
dalğıc	dalğıcda	N;LOC;SG
okean	okeanlarda	N;LOC;PL
axış	axışlara	N;ACC;DEF;PL
buynuz	buynuzuna	N;DAT;SG;PSS2S
ereksiya	ereksiyalarınızdan	N;ABL;PL;PSS2P
sözlük	sözlüklərdə	N;LOC;PL
onurğa	onurğamıza	N;DAT;SG;PSS3P
tülkü	tülküdən	N;ABL;SG
onurğa	onurğalarımdan	N;ABL;PL;PSS1S
kəlbətin	kəlbətinlərə	N;ACC;DEF;PL
qarışqa	qarışqanın	N;GEN;DEF;SG
pişik	pişiklərə	N;ACC;DEF;PL
piano	pianolardan	N;ABL;PL
dalğa	dalğalardan	N;ABL;PL
tələbə	tələbələrdə	N;LOC;PL
ox	oxda	N;LOC;SG
düşmən	düşmənləri	N;ACC;DEF;PL
qəzet	qəzetdə	N;LOC;SG
quş	quşu	N;ACC;DEF;SG
kaktus	kaktuslardan	N;ABL;PL
alça	alçadan	N;ABL;SG
mələk	mələklərinizə	N;DAT;PL;PSS2P
bacı	bacılarında	N;LOC;PL;PSS3P
pomidor	pomidorları	N;ACC;DEF;PL
fəlsəfə	fəlsəfələrim	N;NOM;PL;PSS1S
ana	anamın	N;GEN;SG;PSS1S
ensiklopediya	ensiklopediyadan	N;ABL;SG
yemiş	yemişlərinə	N;DAT;PL;PSS3S
armud	armuda	N;ACC;DEF;SG
donuz	donuzlardan	N;ABL;PL
yemiş	yemişini	N;ACC;SG;PSS3S
geodeziya	geodeziyaları	N;ACC;DEF;PL
quş	quşlar	N;NOM;PL
şaftalı	şaftalısı	N;NOM;SG;PSS3S
bıçaq	bıçağımızın	N;GEN;SG;PSS3P
böyrək	böyrəkləri	N;ACC;DEF;PL
çömçəquyruq	çömçəquyruqları	N;ACC;DEF;PL
onurğa	onurğamızın	N;GEN;SG;PSS3P
ada	adada	N;LOC;SG
düşmən	düşmənim	N;NOM;SG;PSS1S
din	dinlərdən	N;ABL;PL
düşmən	düşməninə	N;DAT;SG;PSS2S
dinozavr	dinozavrında	N;LOC;SG;PSS2S
avtomobil	avtomobilə	N;ACC;DEF;SG
qardaşlıq	qardaşlıqlardan	N;ABL;PL
axış	axışı	N;ACC;DEF;SG
kəpənək	kəpənəklərdən	N;ABL;PL
ereksiya	ereksiyada	N;LOC;SG
kölgə	kölgəsinə	N;DAT;SG;PSS3P
mismar	mismarların	N;GEN;DEF;PL
alov	alovları	N;ACC;DEF;PL
göl	göllərə	N;ACC;DEF;PL
ulduz	ulduza	N;ACC;DEF;SG
açar	açarında	N;LOC;SG;PSS2S
qoxu	qoxularımızdan	N;ABL;PL;PSS3P
bazar	bazarları	N;ACC;DEF;PL
texnologiya	texnologiya	N;NOM;SG
axşam	axşamları	N;ACC;DEF;PL
matç	matç	N;NOM;SG
tülkü	tülkülərə	N;ACC;DEF;PL
bahar	baharda	N;LOC;SG
kölgə	kölgələrini	N;ACC;PL;PSS3P
kilsə	kilsədən	N;ABL;SG
rəng	rənglərin	N;GEN;DEF;PL
kraliça	kraliçalarınızda	N;LOC;PL;PSS2P
düşman	düşmanı	N;NOM;SG;PSS3S
gecə	gecələr	N;NOM;PL
muzey	muzeylərdən	N;ABL;PL
arxiv	arxivindən	N;ABL;SG;PSS3P
bacı	bacıya	N;ACC;DEF;SG
fəlsəfə	fəlsəfələrimizin	N;GEN;PL;PSS3P
qaçmaq	qaçdım	V;SG;1;PST
beyin	beyində	N;LOC;SG
mələk	mələyimə	N;DAT;SG;PSS1S
şahmat	şahmata	N;ACC;DEF;SG
dırnaq	dırnaqlardan	N;ABL;PL
tələbə	tələbəsinə	N;DAT;SG;PSS3S
bıçaq	bıçaqlarına	N;DAT;PL;PSS3P
ərik	əriklərinə	N;DAT;PL;PSS2S
zəlzələ	zəlzələdə	N;LOC;SG
ərik	əriyinə	N;DAT;SG;PSS2S
göz	gözündə	N;LOC;SG;PSS2S
dünya	dünyalarına	N;DAT;PL;PSS3P
qulaq	qulağımdan	N;ABL;SG;PSS1S
avtomobil	avtomobillərdən	N;ABL;PL
eşşək	eşşəkdən	N;ABL;SG
qardaş	qardaşlarımdan	N;ABL;PL;PSS1S
fəaliyyət	fəaliyyətlərə	N;ACC;DEF;PL
tələbə	tələbələri	N;NOM;PL;PSS3S
səviyyə	səviyyələr	N;NOM;PL
kölgə	kölgələrinizin	N;GEN;PL;PSS2P
namaz	namazlarımızı	N;ACC;PL;PSS3P
inək	inəkləri	N;ACC;DEF;PL
namaz	namazlarını	N;ACC;PL;PSS2S
onurğa	onurğaya	N;ACC;DEF;SG
köpük	köpüyə	N;ACC;DEF;SG
ördək	ördəkdən	N;ABL;SG
dirsək	dirsəyindən	N;ABL;SG;PSS3S
penis	penislərinin	N;GEN;PL;PSS2S
özünüidarəetmə	özünüidarəetmədə	N;LOC;SG
skripka	skripkaya	N;ACC;DEF;SG
təzyiq	təzyiqə	N;ACC;DEF;SG
dünya	dünyanın	N;GEN;DEF;SG
bacı	bacılarımızdan	N;ABL;PL;PSS3P
dirsək	dirsəklərimizin	N;GEN;PL;PSS3P
göz	gözləri	N;NOM;PL;PSS3P
dünya	dünyalarınıza	N;DAT;PL;PSS2P
əjdaha	əjdahanı	N;ACC;DEF;SG
dəvəquşu	dəvəquşunu	N;ACC;DEF;SG
vəziyyət	vəziyyətinə	N;DAT;SG;PSS3S
yemiş	yemişinizdən	N;ABL;SG;PSS2P
düşman	düşmanı	N;NOM;SG;PSS3P
onurğa	onurğalarımız	N;NOM;PL;PSS3P
məktəb	məktəbini	N;ACC;SG;PSS3P
gülmək	güləcək	V;SG;3;FUT
penis	penislərimə	N;DAT;PL;PSS1S
körfəz	körfəzlərdə	N;LOC;PL
açar	açarında	N;LOC;SG;PSS3S
fəaliyyət	fəaliyyətləri	N;NOM;PL;PSS3S
xəritə	xəritələrimizdən	N;ABL;PL;PSS3P
dayanacaq	dayanacaq	N;NOM;SG
məktəb	məktəblərinə	N;DAT;PL;PSS3P
incəsənət	incəsənətdə	N;LOC;SG
ərik	əriyimizə	N;DAT;SG;PSS3P
böyrək	böyrək	N;NOM;SG
qəlb	qəlblərinin	N;GEN;PL;PSS3P
əjdaha	əjdahaların	N;GEN;DEF;PL
dirsək	dirsəyimə	N;DAT;SG;PSS1S
namaz	namazlarda	N;LOC;PL
pişik	pişikləri	N;ACC;DEF;PL
günbəz	günbəzə	N;ACC;DEF;SG
şaftalı	şaftalılarından	N;ABL;PL;PSS3S
mənzərə	mənzərələrin	N;GEN;DEF;PL
şahmat	şahmatlar	N;NOM;PL
rəngləmək	rəngləyəcəyəm	V;SG;1;FUT
dirsək	dirsəyindən	N;ABL;SG;PSS3P
qoxu	qoxunuzdan	N;ABL;SG;PSS2P
tərcümə	tərcümələrinizdə	N;LOC;PL;PSS2P
mənzərə	mənzərənizin	N;GEN;SG;PSS2P
kraliça	kraliçamdan	N;ABL;SG;PSS1S
qarpız	qarpızın	N;GEN;DEF;SG
matç	matça	N;ACC;DEF;SG
qardaşlıq	qardaşlığa	N;ACC;DEF;SG
tələbə	tələbəmizdə	N;LOC;SG;PSS3P
gülüş	gülüşümüzdən	N;ABL;SG;PSS3P
dilənçi	dilənçini	N;ACC;DEF;SG
yardım	yardımların	N;GEN;DEF;PL
fəlsəfə	fəlsəfəniz	N;NOM;SG;PSS2P
tələbə	tələbə	N;NOM;SG
süngü	süngüsündən	N;ABL;SG;PSS3S
geyşa	geyşalarda	N;LOC;PL
sevgi	sevgilər	N;NOM;PL
bacı	bacımda	N;LOC;SG;PSS1S
damcı	damcılara	N;ACC;DEF;PL
bıçaq	bıçağıma	N;DAT;SG;PSS1S
ereksiya	ereksiyalarını	N;ACC;PL;PSS3S
alət	alətlərinin	N;GEN;PL;PSS2S
alça	alçamıza	N;DAT;SG;PSS3P
vəftiz	vəftizləri	N;ACC;DEF;PL
dinozavr	dinozavrına	N;DAT;SG;PSS2S
dırnaq	dırnaqdan	N;ABL;SG
şaftalı	şaftalıma	N;DAT;SG;PSS1S
düşmən	düşməninə	N;DAT;SG;PSS3S
günəbaxan	günəbaxandan	N;ABL;SG
süngü	süngü	N;NOM;SG
namaz	namazında	N;LOC;SG;PSS3P
bibər	bibərin	N;GEN;DEF;SG
tülpan	tülpanın	N;GEN;DEF;SG
xəzinə	xəzinələrindən	N;ABL;PL;PSS3S
sivilizasiya	sivilizasiyada	N;LOC;SG
göl	göldən	N;ABL;SG
şənbə	şənbədə	N;LOC;SG
göydələn	göydələnlər	N;NOM;PL
yemiş	yemişimdən	N;ABL;SG;PSS1S
tələbə	tələbələrinin	N;GEN;PL;PSS3P
dünya	dünyalarında	N;LOC;PL;PSS3P
dünya	dünyamın	N;GEN;SG;PSS1S
istifadəçi	istifadəçinin	N;GEN;DEF;SG
göz	gözümüzə	N;DAT;SG;PSS3P
məktəb	məktəblərim	N;NOM;PL;PSS1S
pay	payların	N;GEN;DEF;PL
sünnət	sünnətlərdə	N;LOC;PL
dolab	dolablara	N;ACC;DEF;PL
mismar	mismara	N;ACC;DEF;SG
yemiş	yemişimdə	N;LOC;SG;PSS1S
bürc	bürcdən	N;ABL;SG
balalayka	balalaykaları	N;ACC;DEF;PL
dünya	dünyalarınız	N;NOM;PL;PSS2P
beyin	beyninizi	N;ACC;SG;PSS2P
ərik	əriklərə	N;ACC;DEF;PL
bağban	bağbanlarda	N;LOC;PL
dağ	dağlar	N;NOM;PL
rəngləmək	rənglədik	V;PL;1;PST
hüceyrə	hüceyrəniz	N;NOM;SG;PSS2P
köpək	köpəklərə	N;ACC;DEF;PL
ad	ad	N;NOM;SG
namaz	namazını	N;ACC;SG;PSS3P
sözlük	sözlükləri	N;ACC;DEF;PL
göbək	göbəkdən	N;ABL;SG
respublika	respublikaların	N;GEN;DEF;PL
dirsək	dirsəyin	N;NOM;SG;PSS2S
fəlsəfə	fəlsəfənin	N;GEN;SG;PSS2S
mənzərə	mənzərəm	N;NOM;SG;PSS1S
xarici dil	xarici dillərə	N;ACC;DEF;PL
dinozavr	dinozavrını	N;ACC;SG;PSS3P
əqrəb	əqrəbinizdən	N;ABL;SG;PSS2P
qaçqın	qaçqına	N;ACC;DEF;SG
geyşa	geyşaya	N;ACC;DEF;SG
ağacdələn	ağacdələni	N;ACC;DEF;SG
osminoq	osminoq	N;NOM;SG
tülkü	tülkünün	N;GEN;DEF;SG
zəlzələ	zəlzələlərdə	N;LOC;PL
oraq	oraqda	N;LOC;SG
yemiş	yemişlərimiz	N;NOM;PL;PSS3P
alça	alçalarımızın	N;GEN;PL;PSS3P
fəaliyyət	fəaliyyətindən	N;ABL;SG;PSS3S
fəlsəfə	fəlsəfələrimi	N;ACC;PL;PSS1S
hörümçək	hörümçəklərim	N;NOM;PL;PSS1S
texnologiya	texnologiyadan	N;ABL;SG
zəfəran	zəfəranı	N;ACC;DEF;SG
düşman	düşmanlarımızı	N;ACC;PL;PSS3P
alət	alətindən	N;ABL;SG;PSS3P
beyin	beyinlərimdən	N;ABL;PL;PSS1S
tələbə	tələbələrinə	N;DAT;PL;PSS2S
cəsəd	cəsədə	N;ACC;DEF;SG
bağban	bağbana	N;ACC;DEF;SG
kölgə	kölgələri	N;ACC;DEF;PL
buynuz	buynuzlarında	N;LOC;PL;PSS2S
vəziyyət	vəziyyətimdə	N;LOC;SG;PSS1S
şaftalı	şaftalımıza	N;DAT;SG;PSS3P
qəlb	qəlbimə	N;DAT;SG;PSS1S
qardaş	qardaşımı	N;ACC;SG;PSS1S
yaquar	yaquarlardan	N;ABL;PL
qardaş	qardaşı	N;ACC;DEF;SG
gün	gün	N;NOM;SG
dalğa	dalğalarınız	N;NOM;PL;PSS2P
dayanacaq	dayanacaqlarda	N;LOC;PL
mitoxondri	mitoxondrilər	N;NOM;PL
bacı	bacımızı	N;ACC;SG;PSS3P
alça	alçalarında	N;LOC;PL;PSS3S
xəzinə	xəzinəm	N;NOM;SG;PSS1S
qızılgül	qızılgüllərə	N;ACC;DEF;PL
tısbağa	tısbağaları	N;ACC;DEF;PL
tələbə	tələbələrimin	N;GEN;PL;PSS1S
ereksiya	ereksiyalarımda	N;LOC;PL;PSS1S
birlik	birlikdən	N;ABL;SG
rəhbər	rəhbəri	N;ACC;DEF;SG
fəaliyyət	fəaliyyətini	N;ACC;SG;PSS3P
düşmən	düşmənin	N;NOM;SG;PSS2S
şaftalı	şaftalılarıma	N;DAT;PL;PSS1S
arxiv	arxivlərində	N;LOC;PL;PSS3P
penis	penislərinin	N;GEN;PL;PSS3S
sözlük	sözlüyün	N;GEN;DEF;SG
bulaq	bulaqlardan	N;ABL;PL
ana	analarından	N;ABL;PL;PSS3P
süd	südlərin	N;GEN;DEF;PL
bağırtı	bağırtı	N;NOM;SG
uçan xalça	uçan xalçaları	N;ACC;DEF;PL
kraliça	kraliçalarından	N;ABL;PL;PSS3S
yemiş	yemiş	N;NOM;SG
ərik	əriklərinə	N;DAT;PL;PSS3P
üzüm	üzüm	N;NOM;SG
ördək	ördəyin	N;GEN;DEF;SG
körfəz	körfəzləri	N;ACC;DEF;PL
canavar	canavarlar	N;NOM;PL
diz	dizdə	N;LOC;SG
sabun	sabunlardan	N;ABL;PL
brilyant	brilyantların	N;GEN;DEF;PL
xəritə	xəritəsini	N;ACC;SG;PSS3S
dibçək	dibçəkdə	N;LOC;SG
qaloş	qaloşlarda	N;LOC;PL
müsabiqə	müsabiqələrə	N;ACC;DEF;PL
meyvə	meyvələrin	N;GEN;DEF;PL
yemiş	yemişimizdə	N;LOC;SG;PSS3P
texnologiya	texnologiyada	N;LOC;SG
şaftalı	şaftalılarınızdan	N;ABL;PL;PSS2P
qəlb	qəlblərimizə	N;DAT;PL;PSS3P
hüceyrə	hüceyrələrimizdə	N;LOC;PL;PSS3P
kraliça	kraliçanın	N;GEN;DEF;SG
dirsək	dirsəklərinə	N;DAT;PL;PSS3S
kölgə	kölgəmizdə	N;LOC;SG;PSS3P
kömək	köməyindən	N;ABL;SG;PSS3S
dalğa	dalğaların	N;NOM;PL;PSS2S
psixoterapiya	psixoterapiyadan	N;ABL;SG
skripka	skripka	N;NOM;SG
köpək	köpəkləri	N;ACC;DEF;PL
yemiş	yemişlərinə	N;DAT;PL;PSS2S
öpüş	öpüşlər	N;NOM;PL
əqrəb	əqrəbləri	N;ACC;DEF;PL
bulud	buludun	N;GEN;DEF;SG
fakültə	fakültələr	N;NOM;PL
busə	busələr	N;NOM;PL
beyin	beynimizdən	N;ABL;SG;PSS3P
içmək	içəcəyik	V;PL;1;FUT
gön	gönləri	N;ACC;DEF;PL
dünya	dünyamızı	N;ACC;SG;PSS3P
film	film	N;NOM;SG
cücü	cücülərdə	N;LOC;PL
temperatur	temperaturların	N;GEN;DEF;PL
ütü	ütülərdə	N;LOC;PL
diqqət	diqqət	N;NOM;SG
tələbə	tələbəsindən	N;ABL;SG;PSS3S
ana	analarımızdan	N;ABL;PL;PSS3P
buynuz	buynuzları	N;ACC;DEF;PL
sümük	sümüyü	N;NOM;SG;PSS3S
əqrəb	əqrəbinin	N;GEN;SG;PSS2S
fırtına	fırtınanı	N;ACC;DEF;SG
yemiş	yemişi	N;NOM;SG;PSS3S
mənzərə	mənzərələrimizə	N;DAT;PL;PSS3P
baldız	baldızlarının	N;GEN;PL;PSS3S
bağırtı	bağırtıları	N;ACC;DEF;PL
nəticə	nəticədə	N;LOC;SG
vertolyot	vertolyotu	N;ACC;DEF;SG
xəritə	xəritəsinin	N;GEN;SG;PSS3S
süpürgə	süpürgələrə	N;ACC;DEF;PL
beyin	beyni	N;NOM;SG;PSS3S
bıçaq	bıçaqlarına	N;DAT;PL;PSS2S
mənzərə	mənzərəmdən	N;ABL;SG;PSS1S
sümük	sümüyü	N;NOM;SG;PSS3P
kəfgir	kəfgirlərimdə	N;LOC;PL;PSS1S
bıçaq	bıçaqların	N;NOM;PL;PSS2S
bəbək	bəbəklərin	N;GEN;DEF;PL
namaz	namazlarınızı	N;ACC;PL;PSS2P
rəngləmək	rəngləyirlər	V;PROG;PL;3;PRS
ensiklopediya	ensiklopediyalardan	N;ABL;PL
vəziyyət	vəziyyətimi	N;ACC;SG;PSS1S
müzakirə	müzakirəmdən	N;ABL;SG;PSS1S
ördək	ördəklərə	N;ACC;DEF;PL
sünnət	sünnətlərə	N;ACC;DEF;PL
at	ata	N;ACC;DEF;SG
gecə	gecəyə	N;ACC;DEF;SG
yağış	yağışdan	N;ABL;SG
fəaliyyət	fəaliyyətlərimə	N;DAT;PL;PSS1S
qəlb	qəlbini	N;ACC;SG;PSS3S
penis	penisinə	N;DAT;SG;PSS3P
xəzinə	xəzinələrimin	N;GEN;PL;PSS1S
dəvəquşu	dəvəquşunun	N;GEN;DEF;SG
dayanacaq	dayanacağı	N;ACC;DEF;SG
dırnaq	dırnaqlarından	N;ABL;PL;PSS2S
süngü	süngüləriniz	N;NOM;PL;PSS2P
öpüş	öpüşlərə	N;ACC;DEF;PL
düşmən	düşmənlərindən	N;ABL;PL;PSS2S
söyüd	söyüddə	N;LOC;SG
balıq	balıqların	N;GEN;DEF;PL
mələk	mələklərində	N;LOC;PL;PSS3P
oğraş	oğraşları	N;ACC;DEF;PL
qəlb	qəlblərində	N;LOC;PL;PSS2S
mismar	mismarlar	N;NOM;PL
penis	penisinə	N;DAT;SG;PSS2S
dağ	dağa	N;ACC;DEF;SG
ana	analarınızın	N;GEN;PL;PSS2P
alça	alçasından	N;ABL;SG;PSS3P
kraliça	kraliçasına	N;DAT;SG;PSS3P
müzakirə	müzakirələrinizin	N;GEN;PL;PSS2P
hörümçək	hörümçəyini	N;ACC;SG;PSS3S
geodeziya	geodeziyalardan	N;ABL;PL
bozbaş	bozbaşları	N;ACC;DEF;PL
fəlsəfə	fəlsəfələrinin	N;GEN;PL;PSS3P
yarasa	yarasalardan	N;ABL;PL
ereksiya	ereksiyalarımızın	N;GEN;PL;PSS3P
alət	aləti	N;NOM;SG;PSS3S
arxiv	arxivlərinə	N;DAT;PL;PSS2S
kraliça	kraliçanızın	N;GEN;SG;PSS2P
qonşu	qonşulara	N;ACC;DEF;PL
dəvə	dəvədən	N;ABL;SG
tilişkə	tilişkədə	N;LOC;SG
biçin	biçinlərdən	N;ABL;PL
günbəz	günbəzlər	N;NOM;PL
kölgə	kölgələrində	N;LOC;PL;PSS3S
vəziyyət	vəziyyətinin	N;GEN;SG;PSS2S
dırnaq	dırnağını	N;ACC;SG;PSS2S
kölgə	kölgələrimizin	N;GEN;PL;PSS3P
əjdəha	əjdəhalar	N;NOM;PL
fəaliyyət	fəaliyyətlərin	N;GEN;DEF;PL
alça	alçamı	N;ACC;SG;PSS1S
dinozavr	dinozavrlara	N;ACC;DEF;PL
düşman	düşmanlarınızı	N;ACC;PL;PSS2P
mənzərə	mənzərələrinizə	N;DAT;PL;PSS2P
kraliça	kraliçasının	N;GEN;SG;PSS3P
düşmən	düşmənimə	N;DAT;SG;PSS1S
rəhbər	rəhbəri	N;NOM;SG;PSS3S
bacı	bacıların	N;NOM;PL;PSS2S
keçi	keçilərin	N;GEN;DEF;PL
fleyta	fleytalara	N;ACC;DEF;PL
oğraş	oğraşlardan	N;ABL;PL
piano	pianoları	N;ACC;DEF;PL
birlik	birliyi	N;ACC;DEF;SG
göl	göllər	N;NOM;PL
qoxu	qoxularda	N;LOC;PL
vəziyyət	vəziyyətimdən	N;ABL;SG;PSS1S
yemiş	yemişinin	N;GEN;SG;PSS2S
sarımsaq	sarımsağa	N;ACC;DEF;SG
minarə	minarədə	N;LOC;SG
piano	pianodan	N;ABL;SG
oturmaq	oturacaqlar	V;PL;3;FUT
yəhudi	yəhudinin	N;GEN;DEF;SG
dalğa	dalğanızı	N;ACC;SG;PSS2P
mənzərə	mənzərələrini	N;ACC;PL;PSS2S
kömək	köməklərdə	N;LOC;PL
ana	ana	N;NOM;SG
qardaş	qardaşlarımıza	N;DAT;PL;PSS3P
kərgədan	kərgədanlardan	N;ABL;PL
balıq	balığı	N;ACC;DEF;SG
qan	qanda	N;LOC;SG
cib	ciblərin	N;GEN;DEF;PL
gülüş	gülüşünün	N;GEN;SG;PSS3P
gülüş	gülüşlərində	N;LOC;PL;PSS3P
uşaqlıq	uşaqlıqlarından	N;ABL;PL;PSS3S
dırnaq	dırnaqları	N;ACC;DEF;PL
göydələn	göydələnlərin	N;GEN;DEF;PL
fəlsəfə	fəlsəfələrinizdə	N;LOC;PL;PSS2P
tərcümə	tərcümələrimin	N;GEN;PL;PSS1S
fəlsəfə	fəlsəfəsindən	N;ABL;SG;PSS3P
kraliça	kraliçalarına	N;DAT;PL;PSS3S
yemiş	yemişinin	N;GEN;SG;PSS3P
son	sonlarda	N;LOC;PL
ana	analarını	N;ACC;PL;PSS3S
amfiteatr	amfiteatrlardan	N;ABL;PL
vertolyot	vertolyotdan	N;ABL;SG
meyvə	meyvə	N;NOM;SG
uşaqlıq	uşaqlıqlarımdan	N;ABL;PL;PSS1S
yarasa	yarasaya	N;ACC;DEF;SG
qarpız	qarpızlara	N;ACC;DEF;PL
nar	nara	N;ACC;DEF;SG
bıçaq	bıçaqlarıma	N;DAT;PL;PSS1S
dövri cədvəl	dövri cədvəlin	N;GEN;DEF;SG
geyşa	geyşalar	N;NOM;PL
gülmək	güləcəyəm	V;SG;1;FUT
ox	oxa	N;ACC;DEF;SG
şahmat	şahmatlarda	N;LOC;PL
ərik	əriyinizi	N;ACC;SG;PSS2P
xəritə	xəritəmizin	N;GEN;SG;PSS3P
arxiv	arxivimizə	N;DAT;SG;PSS3P
meyvə	meyvələrdən	N;ABL;PL
açar	açarıma	N;DAT;SG;PSS1S
mələk	mələyinizdə	N;LOC;SG;PSS2P
quş	quş	N;NOM;SG
dələ	dələni	N;ACC;DEF;SG
qəlb	qəlblərini	N;ACC;PL;PSS2S
vaza	vazalarının	N;GEN;PL;PSS2S
uşaqlıq	uşaqlığına	N;DAT;SG;PSS2S
leşyeyən	leşyeyəndə	N;LOC;SG
fəaliyyət	fəaliyyətinizin	N;GEN;SG;PSS2P
qoxu	qoxusuna	N;DAT;SG;PSS3P
ana	anamdan	N;ABL;SG;PSS1S
saqqal	saqqal	N;NOM;SG
ayaq	ayağa	N;ACC;DEF;SG
dirsək	dirsəklərini	N;ACC;PL;PSS2S
beyin	beyinlərimiz	N;NOM;PL;PSS3P
tərcümə	tərcümələrinin	N;GEN;PL;PSS3P
dirsək	dirsəyini	N;ACC;SG;PSS3S
ana	analarıma	N;DAT;PL;PSS1S
öpüş	öpüşlərdən	N;ABL;PL
ərik	əriklərinin	N;GEN;PL;PSS3P
dinozavr	dinozavrlar	N;NOM;PL
kəpənək	kəpənəyin	N;GEN;DEF;SG
xəritə	xəritədən	N;ABL;SG
süngü	süngülərini	N;ACC;PL;PSS2S
şaftalı	şaftalımın	N;GEN;SG;PSS1S
şaftalı	şaftalımızı	N;ACC;SG;PSS3P
ürək	ürəkdən	N;ABL;SG
günbəz	günbəzdə	N;LOC;SG
düşman	düşmanımız	N;NOM;SG;PSS3P
dalğa	dalğanıza	N;DAT;SG;PSS2P
penis	penisindən	N;ABL;SG;PSS2S
kaktus	kaktusların	N;GEN;DEF;PL
fəlsəfə	fəlsəfəndən	N;ABL;SG;PSS2S
tarix	tarixdə	N;LOC;SG
mətbəx	mətbəxi	N;ACC;DEF;SG
sümük	sümüyünüzə	N;DAT;SG;PSS2P
ərik	əriyindən	N;ABL;SG;PSS3S
kömək	köməklərinizdə	N;LOC;PL;PSS2P
dinozavr	dinozavrınızı	N;ACC;SG;PSS2P
tərcümə	tərcüməyə	N;ACC;DEF;SG
alça	alçamız	N;NOM;SG;PSS3P
vəziyyət	vəziyyətinizin	N;GEN;SG;PSS2P
rəngləmək	rəngləyir	V;PROG;SG;3;PRS
alça	alçaları	N;NOM;PL;PSS3S
ayaqqabı	ayaqqabıya	N;ACC;DEF;SG
lüğət	lüğətlər	N;NOM;PL
dinozavr	dinozavrlarımda	N;LOC;PL;PSS1S
xəritə	xəritəmizə	N;DAT;SG;PSS3P
vəziyyət	vəziyyət	N;NOM;SG
ana	ananı	N;ACC;SG;PSS2S
yoldaş	yoldaşlarda	N;LOC;PL
isim	isimləri	N;ACC;DEF;PL
uşaqlıq	uşaqlığınızın	N;GEN;SG;PSS2P
içmək	içirsən	V;PROG;SG;2;PRS
bacı	bacılarımızın	N;GEN;PL;PSS3P
rəng	rənglərdən	N;ABL;PL
zürafə	zürafədən	N;ABL;SG
vaza	vazalarını	N;ACC;PL;PSS3P
yoldaş	yoldaşların	N;GEN;DEF;PL
müzakirə	müzakirələri	N;NOM;PL;PSS3S
alət	alətlərimdə	N;LOC;PL;PSS1S
yemiş	yemişlərini	N;ACC;PL;PSS2S
hüceyrə	hüceyrələrimizi	N;ACC;PL;PSS3P
şkaf	şkaflardan	N;ABL;PL
isim	isimlərə	N;ACC;DEF;PL
alça	alçasından	N;ABL;SG;PSS3S
minarə	minarədən	N;ABL;SG
soğan	soğanlara	N;ACC;DEF;PL
tısbağa	tısbağaya	N;ACC;DEF;SG
dinozavr	dinozavrı	N;ACC;DEF;SG
məktəb	məktəbimizdən	N;ABL;SG;PSS3P
kəfgir	kəfgirinizdən	N;ABL;SG;PSS2P
sözlük	sözlüyə	N;ACC;DEF;SG
müzakirə	müzakirələrdən	N;ABL;PL
süngü	süngülərini	N;ACC;PL;PSS3S
dəmir	dəmirlərin	N;GEN;DEF;PL
mənzərə	mənzərələrimdə	N;LOC;PL;PSS1S
böyrək	böyrəklərin	N;GEN;DEF;PL
baldız	baldızlara	N;ACC;DEF;PL
ereksiya	ereksiyamıza	N;DAT;SG;PSS3P
qəlb	qəlbinin	N;GEN;SG;PSS3S
köpük	köpüklərin	N;GEN;DEF;PL
göbək	göbəklərin	N;GEN;DEF;PL
açar	açarlarımın	N;GEN;PL;PSS1S
ördək	ördəkləri	N;ACC;DEF;PL
qardaş	qardaşlarda	N;LOC;PL
günəbaxan	günəbaxanlarda	N;LOC;PL
dirsək	dirsəklərində	N;LOC;PL;PSS3S
buynuz	buynuzun	N;NOM;SG;PSS2S
qaloş	qaloşda	N;LOC;SG
şaftalı	şaftalında	N;LOC;SG;PSS2S
hüceyrə	hüceyrənizdən	N;ABL;SG;PSS2P
dünya	dünyanıza	N;DAT;SG;PSS2P
isim	isimlər	N;NOM;PL
qulaq	qulağımız	N;NOM;SG;PSS3P
dayanacaq	dayanacaqdan	N;ABL;SG
ərik	əriyə	N;ACC;DEF;SG
göz	gözündə	N;LOC;SG;PSS3P
yemiş	yemişini	N;ACC;SG;PSS3P
qulaq	qulaq	N;NOM;SG
gümüş	gümüşdə	N;LOC;SG
bülbül	bülbüllərdən	N;ABL;PL
dirsək	dirsəklərimin	N;GEN;PL;PSS1S
yaquar	yaquarlar	N;NOM;PL
od	odlara	N;ACC;DEF;PL
meymun	meymundan	N;ABL;SG
bahar	bahar	N;NOM;SG
mələk	mələyinizi	N;ACC;SG;PSS2P
zürafə	zürafələrdən	N;ABL;PL
vəziyyət	vəziyyətlərimizin	N;GEN;PL;PSS3P
kəfgir	kəfgirlərində	N;LOC;PL;PSS3P
köynək	köynəklərimizdə	N;LOC;PL;PSS3P
silah	silahlara	N;ACC;DEF;PL
kəlbətin	kəlbətində	N;LOC;SG
oraq	orağa	N;ACC;DEF;SG
düşmən	düşmənlərimdən	N;ABL;PL;PSS1S
fəlsəfə	fəlsəfəmizdən	N;ABL;SG;PSS3P
mətbəx	mətbəxlərə	N;ACC;DEF;PL
qoxu	qoxunu	N;ACC;DEF;SG
mənzərə	mənzərələrimizdə	N;LOC;PL;PSS3P
əqrəb	əqrəbləri	N;NOM;PL;PSS3S
bağban	bağbanlara	N;ACC;DEF;PL
hüceyrə	hüceyrələrimizə	N;DAT;PL;PSS3P
ereksiya	ereksiyalarda	N;LOC;PL
qoxu	qoxuları	N;NOM;PL;PSS3S
buynuz	buynuzlarına	N;DAT;PL;PSS3S
penis	penislərdən	N;ABL;PL
damcı	damcının	N;GEN;DEF;SG
xəbər	xəbərdə	N;LOC;SG
əqrəb	əqrəbində	N;LOC;SG;PSS3P
kişi	kişidə	N;LOC;SG
vaza	vazalarımız	N;NOM;PL;PSS3P
ad	adlardan	N;ABL;PL
kölgə	kölgənizi	N;ACC;SG;PSS2P
göydələn	göydələn	N;NOM;SG
motosiklet	motosikletə	N;ACC;DEF;SG
düşmən	düşmənindən	N;ABL;SG;PSS3S
xəzinə	xəzinəmdən	N;ABL;SG;PSS1S
qələbə	qələbələrin	N;GEN;DEF;PL
tilişkə	tilişkələrdən	N;ABL;PL
bıçaq	bıçaq	N;NOM;SG
bülbül	bülbüllər	N;NOM;PL
dalğa	dalğasından	N;ABL;SG;PSS3P
dalğa	dalğasına	N;DAT;SG;PSS3S
saqqal	saqqalda	N;LOC;SG
uçan xalça	uçan xalçaların	N;GEN;DEF;PL
qulaq	qulaqlarınızda	N;LOC;PL;PSS2P
ana	anamızdan	N;ABL;SG;PSS3P
bazar	bazarın	N;GEN;DEF;SG
müzakirə	müzakirələrin	N;GEN;DEF;PL
rəngləmək	rəngləyəcəksiniz	V;PL;2;FUT
xəzinə	xəzinən	N;NOM;SG;PSS2S
tərcümə	tərcüməm	N;NOM;SG;PSS1S
tələbə	tələbələrimə	N;DAT;PL;PSS1S
dırnaq	dırnağının	N;GEN;SG;PSS2S
uşaqlıq	uşaqlıqlarım	N;NOM;PL;PSS1S
göz	gözümüzü	N;ACC;SG;PSS3P
köynək	köynəyimizi	N;ACC;SG;PSS3P
hörümçək	hörümçəyinin	N;GEN;SG;PSS2S
alça	alçalarınızdan	N;ABL;PL;PSS2P
penis	penisinə	N;DAT;SG;PSS3S
göz	gözünü	N;ACC;SG;PSS3S
arxiv	arxivlərdə	N;LOC;PL
düşmən	düşmənini	N;ACC;SG;PSS3P
kəfgir	kəfgirinin	N;GEN;SG;PSS3P
almaz	almazda	N;LOC;SG
penis	penislərimizi	N;ACC;PL;PSS3P
ət	ətlərdən	N;ABL;PL
penis	penislərə	N;ACC;DEF;PL
əqrəb	əqrəbində	N;LOC;SG;PSS3S
qoxu	qoxularınız	N;NOM;PL;PSS2P
buynuz	buynuzdan	N;ABL;SG
kamerton	kamertonda	N;LOC;SG
skripka	skripkanı	N;ACC;DEF;SG
yardım	yardımlarda	N;LOC;PL
qoxu	qoxularında	N;LOC;PL;PSS3P
qaz	qazda	N;LOC;SG
biçin	biçinlərin	N;GEN;DEF;PL
qardaş	qardaşa	N;ACC;DEF;SG
kömək	köməklərə	N;ACC;DEF;PL
namaz	namazın	N;GEN;DEF;SG
qulaq	qulaqlarımıza	N;DAT;PL;PSS3P
hüceyrə	hüceyrələrin	N;GEN;DEF;PL
məktəb	məktəblərimizi	N;ACC;PL;PSS3P
üz	üzlər	N;NOM;PL
mehrab	mehrabların	N;GEN;DEF;PL
zoğ	zoğdan	N;ABL;SG
xəzinə	xəzinəsi	N;NOM;SG;PSS3P
bazar	bazarlara	N;ACC;DEF;PL
dirsək	dirsəyiniz	N;NOM;SG;PSS2P
düşmən	düşməndən	N;ABL;SG
gön	göndə	N;LOC;SG
ada	adadan	N;ABL;SG
xalqa	xalqalar	N;NOM;PL
öpüş	öpüşün	N;GEN;DEF;SG
xəritə	xəritələrimizə	N;DAT;PL;PSS3P
bardaq	bardaqların	N;GEN;DEF;PL
gülüş	gülüşü	N;NOM;SG;PSS3P
surə	surələr	N;NOM;PL
dünya	dünyalarınızdan	N;ABL;PL;PSS2P
bibər	bibərə	N;ACC;DEF;SG
qızılgül	qızılgüllərdə	N;LOC;PL
fəlsəfə	fəlsəfəmin	N;GEN;SG;PSS1S
təyyarə	təyyarələrdə	N;LOC;PL
göz	gözünü	N;ACC;SG;PSS2S
ürək	ürəkdə	N;LOC;SG
mələk	mələkləriniz	N;NOM;PL;PSS2P
gülüş	gülüşündən	N;ABL;SG;PSS3S
at	atı	N;ACC;DEF;SG
mənzərə	mənzərələrimə	N;DAT;PL;PSS1S
xəzinə	xəzinələrinizi	N;ACC;PL;PSS2P
qəlb	qəlbimizin	N;GEN;SG;PSS3P
qardaş	qardaşları	N;ACC;DEF;PL
qəlb	qəlbimiz	N;NOM;SG;PSS3P
onurğa	onurğasına	N;DAT;SG;PSS3S
xarici dil	xarici dilləri	N;ACC;DEF;PL
kişi	kişi	N;NOM;SG
tüstü	tüstünün	N;GEN;DEF;SG
penis	penislərindən	N;ABL;PL;PSS3P
xəzinə	xəzinəmizdən	N;ABL;SG;PSS3P
kölgə	kölgələrinin	N;GEN;PL;PSS2S
uşaqlıq	uşaqlığımızı	N;ACC;SG;PSS3P
ovçu	ovçuda	N;LOC;SG
məktəb	məktəbimə	N;DAT;SG;PSS1S
ər	ərlər	N;NOM;PL
əqrəb	əqrəblərimizi	N;ACC;PL;PSS3P
qadın	qadını	N;ACC;DEF;SG
uşaqlıq	uşaqlığınıza	N;DAT;SG;PSS2P
qaranquş	qaranquşlarda	N;LOC;PL
süd	süddə	N;LOC;SG
uşaqlıq	uşaqlığının	N;GEN;SG;PSS3P
tilişkə	tilişkələri	N;ACC;DEF;PL
skripka	skripkada	N;LOC;SG
məktəb	məktəbi	N;NOM;SG;PSS3P
qardaş	qardaşlara	N;ACC;DEF;PL
kölgə	kölgələrimizdə	N;LOC;PL;PSS3P
bıçaq	bıçaqdan	N;ABL;SG
meymun	meymunu	N;ACC;DEF;SG
düşman	düşmanlarım	N;NOM;PL;PSS1S
ana	ananız	N;NOM;SG;PSS2P
mələk	mələyimizin	N;GEN;SG;PSS3P
ərik	əriyimizin	N;GEN;SG;PSS3P
geodeziya	geodeziyalara	N;ACC;DEF;PL
tələbə	tələbəndə	N;LOC;SG;PSS2S
buynuz	buynuzlarını	N;ACC;PL;PSS3P
şaftalı	şaftalısında	N;LOC;SG;PSS3S
məktəb	məktəbində	N;LOC;SG;PSS3P
milçək	milçəklərin	N;GEN;DEF;PL
hüceyrə	hüceyrələrində	N;LOC;PL;PSS3S
pişik	pişiklər	N;NOM;PL
arxiv	arxivimdə	N;LOC;SG;PSS1S
söyüd	söyüddən	N;ABL;SG
ereksiya	ereksiyanın	N;GEN;DEF;SG
düşmən	düşməninizdən	N;ABL;SG;PSS2P
birlik	birlikdə	N;LOC;SG
işıq	işığın	N;GEN;DEF;SG
dirsək	dirsəkdə	N;LOC;SG
müzakirə	müzakirələr	N;NOM;PL
şirkət	şirkətlərə	N;ACC;DEF;PL
alça	alçamızdan	N;ABL;SG;PSS3P
şamisen	şamisenlər	N;NOM;PL
xəritə	xəritələrindən	N;ABL;PL;PSS3S
qəlb	qəlbindən	N;ABL;SG;PSS2S
yemiş	yemişinə	N;DAT;SG;PSS3P
kölgə	kölgələrinizi	N;ACC;PL;PSS2P
dırnaq	dırnağına	N;DAT;SG;PSS2S
uşaqlıq	uşaqlığını	N;ACC;SG;PSS3P
əjdaha	əjdahanın	N;GEN;DEF;SG
mələk	mələklərinin	N;GEN;PL;PSS3P
futbolçu	futbolçularda	N;LOC;PL
ulduz	ulduzlarda	N;LOC;PL
yarasa	yarasaların	N;GEN;DEF;PL
fleyta	fleytaya	N;ACC;DEF;SG
kəfgir	kəfgirlərin	N;GEN;DEF;PL
qərənfil	qərənfildən	N;ABL;SG
vaza	vazalarına	N;DAT;PL;PSS3S
quş	quşa	N;ACC;DEF;SG
kraliça	kraliçasına	N;DAT;SG;PSS3S
cəsəd	cəsəddən	N;ABL;SG
qulaq	qulağına	N;DAT;SG;PSS2S
meymun	meymunun	N;GEN;DEF;SG
qaçmaq	qaçdılar	V;PL;3;PST
əjdaha	əjdahalara	N;ACC;DEF;PL
psixoterapiya	psixoterapiyanı	N;ACC;DEF;SG
qoxu	qoxumuza	N;DAT;SG;PSS3P
avqust	avqusta	N;ACC;DEF;SG
xəzinə	xəzinəsi	N;NOM;SG;PSS3S
səbəb	səbəblərdən	N;ABL;PL
müzakirə	müzakirələrimiz	N;NOM;PL;PSS3P
avtomobil	avtomobildə	N;LOC;SG
darçın	darçına	N;ACC;DEF;SG
qəlb	qəlblərində	N;LOC;PL;PSS3P
ereksiya	ereksiyamız	N;NOM;SG;PSS3P
kəlbətin	kəlbətinlərin	N;GEN;DEF;PL
namaz	namazlarım	N;NOM;PL;PSS1S
çəyirtkə	çəyirtkədə	N;LOC;SG
qardaş	qardaşlarında	N;LOC;PL;PSS3S
qardaş	qardaşından	N;ABL;SG;PSS3P
gülmək	güləcəksən	V;SG;2;FUT
damcı	damcıdan	N;ABL;SG
ox	oxların	N;GEN;DEF;PL
qoxu	qoxularıma	N;DAT;PL;PSS1S
hörümçək	hörümçəyinizdən	N;ABL;SG;PSS2P
vaza	vazamdan	N;ABL;SG;PSS1S
qarpız	qarpızların	N;GEN;DEF;PL
kraliça	kraliça	N;NOM;SG
üzüm	üzümlər	N;NOM;PL
sünnət	sünnətdən	N;ABL;SG
qardaşlıq	qardaşlıqları	N;ACC;DEF;PL
dırnaq	dırnaqların	N;GEN;DEF;PL
günəş	günəşdən	N;ABL;SG
fəaliyyət	fəaliyyətimi	N;ACC;SG;PSS1S
kilsə	kilsədə	N;LOC;SG
göz	gözlərini	N;ACC;PL;PSS3S
qardaşlıq	qardaşlıqların	N;GEN;DEF;PL
amfiteatr	amfiteatrlar	N;NOM;PL
şirkət	şirkətə	N;ACC;DEF;SG
alət	alətimdə	N;LOC;SG;PSS1S
mətbəx	mətbəxin	N;GEN;DEF;SG
açar	açarları	N;ACC;DEF;PL
damcı	damcı	N;NOM;SG
buynuz	buynuzlarda	N;LOC;PL
dırnaq	dırnağınızın	N;GEN;SG;PSS2P
tülpan	tülpanda	N;LOC;SG
dırnaq	dırnaqlarını	N;ACC;PL;PSS2S
dövri cədvəl	dövri cədvəli	N;ACC;DEF;SG
köynək	köynəklərinə	N;DAT;PL;PSS2S
vaza	vazanın	N;GEN;DEF;SG
dinozavr	dinozavrından	N;ABL;SG;PSS3P
dalğa	dalğaya	N;ACC;DEF;SG
mələk	mələyin	N;NOM;SG;PSS2S
qəlb	qəlblərinizə	N;DAT;PL;PSS2P
otaq	otaqlarda	N;LOC;PL
dinozavr	dinozavrlarımız	N;NOM;PL;PSS3P
keçi	keçiyə	N;ACC;DEF;SG
dinozavr	dinozavrına	N;DAT;SG;PSS3S
ana	analarını	N;ACC;PL;PSS3P
inək	inək	N;NOM;SG
köynək	köynəyinə	N;DAT;SG;PSS2S
bağırtı	bağırtıya	N;ACC;DEF;SG
tərcümə	tərcümələri	N;NOM;PL;PSS3S
fəlsəfə	fəlsəfələrimizdən	N;ABL;PL;PSS3P
oyuncaq	oyuncaqdan	N;ABL;SG
futbolçu	futbolçunu	N;ACC;DEF;SG
jurnalist	jurnalistdən	N;ABL;SG
dalğa	dalğanı	N;ACC;DEF;SG
xəritə	xəritən	N;NOM;SG;PSS2S
kəpənək	kəpənəkdən	N;ABL;SG
kərpic	kərpicdən	N;ABL;SG
buynuz	buynuzunu	N;ACC;SG;PSS3S
gümüş	gümüşün	N;GEN;DEF;SG
bacı	bacılarım	N;NOM;PL;PSS1S
dirsək	dirsəyimdən	N;ABL;SG;PSS1S
fəaliyyət	fəaliyyətdən	N;ABL;SG
onurğa	onurğanızın	N;GEN;SG;PSS2P
fəlsəfə	fəlsəfələrində	N;LOC;PL;PSS3S
osminoq	osminoqların	N;GEN;DEF;PL
gümüş	gümüşləri	N;ACC;DEF;PL
gəmi	gəmi	N;NOM;SG
çəyirtkə	çəyirtkənin	N;GEN;DEF;SG
dinozavr	dinozavrımda	N;LOC;SG;PSS1S
canavar	canavarı	N;ACC;DEF;SG
fəlsəfə	fəlsəfələrini	N;ACC;PL;PSS2S
xəzinə	xəzinəsinin	N;GEN;SG;PSS3S
qulaq	qulaqları	N;NOM;PL;PSS3P
fəlsəfə	fəlsəfəsinin	N;GEN;SG;PSS3S
üzüm	üzümlərdən	N;ABL;PL
ərik	ərikdən	N;ABL;SG
hüceyrə	hüceyrələrini	N;ACC;PL;PSS3P
qardaş	qardaşlar	N;NOM;PL
dalğa	dalğanız	N;NOM;SG;PSS2P
cümə	cümələrdən	N;ABL;PL
arxiv	arxivinə	N;DAT;SG;PSS3S
qaçmaq	qaçır	V;PROG;SG;3;PRS
isim	isim	N;NOM;SG
mənzərə	mənzərələrinin	N;GEN;PL;PSS2S
qarğa	qarğadan	N;ABL;SG
yemiş	yemişlərinizdən	N;ABL;PL;PSS2P
ərik	əriklərimi	N;ACC;PL;PSS1S
buynuz	buynuzlarından	N;ABL;PL;PSS3S
bacı	bacını	N;ACC;SG;PSS2S
hüceyrə	hüceyrələri	N;ACC;DEF;PL
alov	alovun	N;GEN;DEF;SG
arxiv	arxivlərində	N;LOC;PL;PSS3S
xəritə	xəritəsi	N;NOM;SG;PSS3S
ereksiya	ereksiya	N;NOM;SG
bürc	bürclər	N;NOM;PL
rəhbər	rəhbərlərinin	N;GEN;PL;PSS3S
dalğa	dalğamı	N;ACC;SG;PSS1S
göz	gözündən	N;ABL;SG;PSS3P
günəbaxan	günəbaxanlar	N;NOM;PL
axşam	axşam	N;NOM;SG
quş	quşda	N;LOC;SG
əjdəha	əjdəhalarda	N;LOC;PL
qulaq	qulaqlarının	N;GEN;PL;PSS2S
ət	ətdə	N;LOC;SG
köynək	köynəklərdən	N;ABL;PL
avtomobil	avtomobilləri	N;ACC;DEF;PL
sözlük	sözlüklərə	N;ACC;DEF;PL
ağlamaq	ağlayırsınız	V;PROG;PL;2;PRS
xəzinə	xəzinəsində	N;LOC;SG;PSS3S
boya	boyadan	N;ABL;SG
cib	cibdən	N;ABL;SG
açar	açarlarınızdan	N;ABL;PL;PSS2P
bəbək	bəbəklərə	N;ACC;DEF;PL
kağız	kağızlarda	N;LOC;PL
axşam	axşamdan	N;ABL;SG
vaza	vazadan	N;ABL;SG
xəzinə	xəzinəniz	N;NOM;SG;PSS2P
kamerton	kamertonun	N;GEN;DEF;SG
ana	anaları	N;NOM;PL;PSS3P
ereksiya	ereksiyamızda	N;LOC;SG;PSS3P
ereksiya	ereksiyalarına	N;DAT;PL;PSS3S
uçan xalça	uçan xalça	N;NOM;SG
buynuz	buynuzlarına	N;DAT;PL;PSS3P
rəng	rənglərdə	N;LOC;PL
ərik	ərikləri	N;NOM;PL;PSS3S
piano	pianoda	N;LOC;SG
onurğa	onurğamın	N;GEN;SG;PSS1S
səbəb	səbəblər	N;NOM;PL
həqiqət	həqiqətlərə	N;ACC;DEF;PL
vaza	vazalarını	N;ACC;PL;PSS2S
uşaqlıq	uşaqlığınızda	N;LOC;SG;PSS2P
gecə	gecələri	N;ACC;DEF;PL
kölgə	kölgənizin	N;GEN;SG;PSS2P
qələbə	qələbədə	N;LOC;SG
ereksiya	ereksiyalarından	N;ABL;PL;PSS3P
pişik	pişik	N;NOM;SG
uşaqlıq	uşaqlığında	N;LOC;SG;PSS3S
qardaş	qardaşlarıma	N;DAT;PL;PSS1S
dünya	dünyada	N;LOC;SG
kölgə	kölgələrinizdə	N;LOC;PL;PSS2P
xəzinə	xəzinənizdən	N;ABL;SG;PSS2P
ön	ön	N;NOM;SG
birlik	birliyin	N;GEN;DEF;SG
rəngləmək	rəngləyəcəksən	V;SG;2;FUT
qarışqa	qarışqa	N;NOM;SG
geyşa	geyşaların	N;GEN;DEF;PL
gülmək	güldü	V;SG;3;PST
baldız	baldızları	N;NOM;PL;PSS3P
amfiteatr	amfiteatrların	N;GEN;DEF;PL
kağız	kağızın	N;GEN;DEF;SG
vəziyyət	vəziyyətlərimizi	N;ACC;PL;PSS3P
gülüş	gülüşü	N;NOM;SG;PSS3S
bacı	bacılarınızı	N;ACC;PL;PSS2P
qardaş	qardaşın	N;GEN;DEF;SG
mənzərə	mənzərəmin	N;GEN;SG;PSS1S
din	dinlərə	N;ACC;DEF;PL
bibər	bibərlərdən	N;ABL;PL
gülüş	gülüşümüzdə	N;LOC;SG;PSS3P
motosiklet	motosikletlərə	N;ACC;DEF;PL
son	sonun	N;GEN;DEF;SG
köynək	köynək	N;NOM;SG
film	filmə	N;ACC;DEF;SG
xəritə	xəritələrini	N;ACC;PL;PSS3S
açar	açarının	N;GEN;SG;PSS3S
beyin	beyinlərinin	N;GEN;PL;PSS3P
tələbə	tələbəsinin	N;GEN;SG;PSS3S
portağal	portağallar	N;NOM;PL
açar	açarınızdan	N;ABL;SG;PSS2P
rəhbər	rəhbərinizi	N;ACC;SG;PSS2P
baldız	baldızlarına	N;DAT;PL;PSS2S
təsadüf	təsadüfdə	N;LOC;SG
süngü	süngümdə	N;LOC;SG;PSS1S
kərtənkələ	kərtənkələlər	N;NOM;PL
can	canların	N;GEN;DEF;PL
ədəbiyyat	ədəbiyyatların	N;GEN;DEF;PL
düşman	düşmanlarınızda	N;LOC;PL;PSS2P
əqrəb	əqrəblərimizə	N;DAT;PL;PSS3P
bacı	bacıları	N;ACC;DEF;PL
yaquar	yaquara	N;ACC;DEF;SG
tısbağa	tısbağalara	N;ACC;DEF;PL
siçan	siçan	N;NOM;SG
bıçaq	bıçağımıza	N;DAT;SG;PSS3P
son	sonu	N;ACC;DEF;SG
dondurma	dondurmalardan	N;ABL;PL
xəritə	xəritə	N;NOM;SG
kölgə	kölgəsinin	N;GEN;SG;PSS3P
kömək	köməkləri	N;ACC;DEF;PL
ana	anasının	N;GEN;SG;PSS3P
bağırtı	bağırtının	N;GEN;DEF;SG
fəaliyyət	fəaliyyətinə	N;DAT;SG;PSS2S
gön	gönlərə	N;ACC;DEF;PL
alça	alçanı	N;ACC;SG;PSS2S
gön	gönlərdə	N;LOC;PL
bulud	buludlar	N;NOM;PL
hörümçək	hörümçəyimizin	N;GEN;SG;PSS3P
düşərgə	düşərgələri	N;ACC;DEF;PL
bacı	bacınıza	N;DAT;SG;PSS2P
ürək	ürək	N;NOM;SG
tələbə	tələbələrimiz	N;NOM;PL;PSS3P
bağırtı	bağırtını	N;ACC;DEF;SG
ayaqqabı	ayaqqabılar	N;NOM;PL
möcüzə	möcüzə	N;NOM;SG
kölgə	kölgələrindən	N;ABL;PL;PSS2S
geyşa	geyşa	N;NOM;SG
baldız	baldızlarında	N;LOC;PL;PSS2S
bıçaq	bıçağımı	N;ACC;SG;PSS1S
dodaq	dodaqlardan	N;ABL;PL
onurğa	onurğalarınız	N;NOM;PL;PSS2P
alça	alçalarından	N;ABL;PL;PSS2S
fakültə	fakültədə	N;LOC;SG
kərgədan	kərgədanlar	N;NOM;PL
xəzinə	xəzinələrin	N;NOM;PL;PSS2S
sivilizasiya	sivilizasiyaların	N;GEN;DEF;PL
sivilizasiya	sivilizasiyanı	N;ACC;DEF;SG
nəfəs	nəfəslərin	N;GEN;DEF;PL
dalğa	dalğamızda	N;LOC;SG;PSS3P
sevgi	sevgi	N;NOM;SG
buynuz	buynuzunda	N;LOC;SG;PSS2S
ereksiya	ereksiyalarım	N;NOM;PL;PSS1S
qardaş	qardaşlarımız	N;NOM;PL;PSS3P
kölgə	kölgələrində	N;LOC;PL;PSS2S
düşman	düşmanında	N;LOC;SG;PSS3P
düşman	düşmanlarımı	N;ACC;PL;PSS1S
kölgə	kölgəmin	N;GEN;SG;PSS1S
səviyyə	səviyyənin	N;GEN;DEF;SG
peyğəmbər	peyğəmbər	N;NOM;SG
kəlbətin	kəlbətini	N;ACC;DEF;SG
kraliça	kraliçalarına	N;DAT;PL;PSS3P
maşın	maşından	N;ABL;SG
dirsək	dirsəkləriniz	N;NOM;PL;PSS2P
göydələn	göydələnlərə	N;ACC;DEF;PL
lüğət	lüğətləri	N;ACC;DEF;PL
qardaş	qardaşımız	N;NOM;SG;PSS3P
jurnalist	jurnalistlərdə	N;LOC;PL
yardım	yardımları	N;ACC;DEF;PL
qızılgül	qızılgüldə	N;LOC;SG
cücü	cücülərin	N;GEN;DEF;PL
çiyələk	çiyələk	N;NOM;SG
bulud	bulud	N;NOM;SG
gülüş	gülüşlərimi	N;ACC;PL;PSS1S
ox	oxdan	N;ABL;SG
qoxu	qoxularınıza	N;DAT;PL;PSS2P
ayaq	ayaqlarda	N;LOC;PL
müzakirə	müzakirənin	N;GEN;SG;PSS2S
düşman	düşmanlarınıza	N;DAT;PL;PSS2P
penis	penisim	N;NOM;SG;PSS1S
qoxu	qoxumuz	N;NOM;SG;PSS3P
yemiş	yemişlərində	N;LOC;PL;PSS2S
tərcümə	tərcüməsini	N;ACC;SG;PSS3S
sabun	sabun	N;NOM;SG
qılınc	qılıncları	N;ACC;DEF;PL
sümük	sümüklərimdən	N;ABL;PL;PSS1S
qapı	qapıdan	N;ABL;SG
fırtına	fırtınalarda	N;LOC;PL
gülüş	gülüşləri	N;NOM;PL;PSS3P
əqrəb	əqrəblərimi	N;ACC;PL;PSS1S
ereksiya	ereksiyalar	N;NOM;PL
gülüş	gülüşlərimizin	N;GEN;PL;PSS3P
xarici dil	xarici dilə	N;ACC;DEF;SG
dünya	dünyalarımızın	N;GEN;PL;PSS3P
peyğəmbər	peyğəmbərlərin	N;GEN;DEF;PL
vəziyyət	vəziyyətlərində	N;LOC;PL;PSS3P
dayanacaq	dayanacaqlardan	N;ABL;PL
can	canda	N;LOC;SG
şəhər	şəhəri	N;ACC;DEF;SG
mənzərə	mənzərəsində	N;LOC;SG;PSS3S
qoxu	qoxuya	N;ACC;DEF;SG
çiyələk	çiyələklərə	N;ACC;DEF;PL
rəhbər	rəhbərimi	N;ACC;SG;PSS1S
onurğa	onurğanızı	N;ACC;SG;PSS2P
düşman	düşmanlarımın	N;GEN;PL;PSS1S
beyin	beyinlərimizdən	N;ABL;PL;PSS3P
rəhbər	rəhbərinizə	N;DAT;SG;PSS2P
dalğa	dalğanı	N;ACC;SG;PSS2S
hüceyrə	hüceyrəmizə	N;DAT;SG;PSS3P
qaçmaq	qaçdı	V;SG;3;PST
ana	anasında	N;LOC;SG;PSS3P
qardaş	qardaşlardan	N;ABL;PL
günbəz	günbəzlərdə	N;LOC;PL
süngü	süngülərimizi	N;ACC;PL;PSS3P
köynək	köynəklərindən	N;ABL;PL;PSS3S
göz	gözlərinin	N;GEN;PL;PSS3P
meyvə	meyvəni	N;ACC;DEF;SG
rəhbər	rəhbərimizi	N;ACC;SG;PSS3P
mələk	mələklərdən	N;ABL;PL
tilişkə	tilişkə	N;NOM;SG
qardaş	qardaşlarında	N;LOC;PL;PSS2S
mələk	mələklərimdə	N;LOC;PL;PSS1S
düşman	düşmanlarından	N;ABL;PL;PSS3P
kömək	köməklərimizə	N;DAT;PL;PSS3P
göydələn	göydələnin	N;GEN;DEF;SG
at	atlardan	N;ABL;PL
onurğa	onurğalarımızı	N;ACC;PL;PSS3P
şaftalı	şaftalılarınızı	N;ACC;PL;PSS2P
ağlamaq	ağlayırlar	V;PROG;PL;3;PRS
ana	ananın	N;GEN;DEF;SG
kölgə	kölgəmizin	N;GEN;SG;PSS3P
fırtına	fırtınaların	N;GEN;DEF;PL
tərcümə	tərcümələrimə	N;DAT;PL;PSS1S
almaz	almazlarda	N;LOC;PL
səhifə	səhifənin	N;GEN;DEF;SG
penis	penisinizi	N;ACC;SG;PSS2P
xəbər	xəbərin	N;GEN;DEF;SG
dalğa	dalğalarınızı	N;ACC;PL;PSS2P
üzüm	üzümü	N;ACC;DEF;SG
xəstəlik	xəstəliyin	N;GEN;DEF;SG
ön	önü	N;ACC;DEF;SG
ər	ərdə	N;LOC;SG
göyərçin	göyərçinə	N;ACC;DEF;SG
dalğıc	dalğıc	N;NOM;SG
dirsək	dirsəkləri	N;ACC;DEF;PL
dirsək	dirsəklərinizin	N;GEN;PL;PSS2P
tülkü	tülküdə	N;LOC;SG
dırnaq	dırnaqlarımıza	N;DAT;PL;PSS3P
göydələn	göydələni	N;ACC;DEF;SG
fəaliyyət	fəaliyyətlərinizə	N;DAT;PL;PSS2P
məktəb	məktəbi	N;ACC;DEF;SG
böyürtkən	böyürtkən	N;NOM;SG
osminoq	osminoqlardan	N;ABL;PL
xəritə	xəritələrində	N;LOC;PL;PSS3S
süngü	süngülərimizdən	N;ABL;PL;PSS3P
kompüter	kompüterin	N;GEN;DEF;SG
buynuz	buynuzda	N;LOC;SG
bacı	bacımın	N;GEN;SG;PSS1S
qəlb	qəlbini	N;ACC;SG;PSS2S
məktəb	məktəblərin	N;NOM;PL;PSS2S
hörümçək	hörümçəyindən	N;ABL;SG;PSS2S
qardaş	qardaşlarından	N;ABL;PL;PSS3S
bulud	buludlara	N;ACC;DEF;PL
həftə	həftələrdən	N;ABL;PL
düşman	düşmanımızı	N;ACC;SG;PSS3P
amfiteatr	amfiteatra	N;ACC;DEF;SG
bürc	bürclərə	N;ACC;DEF;PL
xəritə	xəritəmdə	N;LOC;SG;PSS1S
kaktus	kaktuslarda	N;LOC;PL
hüceyrə	hüceyrələrini	N;ACC;PL;PSS2S
sünnət	sünnətdə	N;LOC;SG
bazar	bazarı	N;ACC;DEF;SG
fleyta	fleytanın	N;GEN;DEF;SG
şaftalı	şaftalılarımıza	N;DAT;PL;PSS3P
mehrab	mehrabı	N;ACC;DEF;SG
nəfəs	nəfəslərdə	N;LOC;PL
yemiş	yemişimə	N;DAT;SG;PSS1S
qardaşlıq	qardaşlıqlara	N;ACC;DEF;PL
düşmən	düşməninin	N;GEN;SG;PSS3S
şkaf	şkafı	N;ACC;DEF;SG
hörümçək	hörümçəyinizə	N;DAT;SG;PSS2P
xloroplast	xloroplastlardan	N;ABL;PL
dırnaq	dırnağıma	N;DAT;SG;PSS1S
kəfgir	kəfgirlərinin	N;GEN;PL;PSS3P
baldız	baldızlarında	N;LOC;PL;PSS3S
bıçaq	bıçaqda	N;LOC;SG
baldız	baldızımın	N;GEN;SG;PSS1S
rəhbər	rəhbərdə	N;LOC;SG
namaz	namazlarımızın	N;GEN;PL;PSS3P
son	sonlar	N;NOM;PL
can	canı	N;ACC;DEF;SG
ərik	əriklərinizin	N;GEN;PL;PSS2P
təbiət	təbiətlərdən	N;ABL;PL
silah	silahda	N;LOC;SG
süpürgə	süpürgələri	N;ACC;DEF;PL
kömək	köməyinizin	N;GEN;SG;PSS2P
müzakirə	müzakirələrinizi	N;ACC;PL;PSS2P
qəlb	qəlbində	N;LOC;SG;PSS3P
göz	gözlərinin	N;GEN;PL;PSS2S
yaquar	yaquarın	N;GEN;DEF;SG
qoxu	qoxundan	N;ABL;SG;PSS2S
ürək	ürəyə	N;ACC;DEF;SG
qarpız	qarpızı	N;ACC;DEF;SG
qonşu	qonşuların	N;GEN;DEF;PL
tələbə	tələbələrinin	N;GEN;PL;PSS3S
bıçaq	bıçaqlarda	N;LOC;PL
psixoterapiya	psixoterapiyalar	N;NOM;PL
ereksiya	ereksiyalarımızda	N;LOC;PL;PSS3P
milçək	milçəkdən	N;ABL;SG
onurğa	onurğasına	N;DAT;SG;PSS3P
kəfgir	kəfgiriniz	N;NOM;SG;PSS2P
film	filmdən	N;ABL;SG
xəzinə	xəzinəsinin	N;GEN;SG;PSS3P
qoxu	qoxusundan	N;ABL;SG;PSS3P
qaranquş	qaranquşlardan	N;ABL;PL
şaftalı	şaftalını	N;ACC;DEF;SG
vəziyyət	vəziyyətlərimizdən	N;ABL;PL;PSS3P
xəbər	xəbərlərin	N;GEN;DEF;PL
dovşan	dovşanları	N;ACC;DEF;PL
penis	penislərində	N;LOC;PL;PSS3P
mələk	mələklərin	N;NOM;PL;PSS2S
oyuncaq	oyuncağı	N;ACC;DEF;SG
dünya	dünyalar	N;NOM;PL
minarə	minarələrin	N;GEN;DEF;PL
mələk	mələyimizə	N;DAT;SG;PSS3P
göz	gözünə	N;DAT;SG;PSS3P
onurğa	onurğalarından	N;ABL;PL;PSS3S
ər	ər	N;NOM;SG
fəaliyyət	fəaliyyətindən	N;ABL;SG;PSS2S
tələbə	tələbəsinin	N;GEN;SG;PSS3P
möcüzə	möcüzələrə	N;ACC;DEF;PL
biçin	biçinə	N;ACC;DEF;SG
pendir	pendirlər	N;NOM;PL
namaz	namazlarınızın	N;GEN;PL;PSS2P
sümük	sümüyünüzü	N;ACC;SG;PSS2P
tələbə	tələbəmizə	N;DAT;SG;PSS3P
qaçmaq	qaçıram	V;PROG;SG;1;PRS
rəndə	rəndəni	N;ACC;DEF;SG
köynək	köynəyində	N;LOC;SG;PSS3P
qəlb	qəlbdən	N;ABL;SG
uşaqlıq	uşaqlıqların	N;NOM;PL;PSS2S
möcüzə	möcüzədən	N;ABL;SG
oraq	oraqlara	N;ACC;DEF;PL
busə	busələrdə	N;LOC;PL
yoldaş	yoldaşda	N;LOC;SG
gülüş	gülüşlərinə	N;DAT;PL;PSS2S
düşman	düşmanıma	N;DAT;SG;PSS1S
yemiş	yemişlərimizin	N;GEN;PL;PSS3P
körfəz	körfəzlərə	N;ACC;DEF;PL
dinozavr	dinozavrlarının	N;GEN;PL;PSS3S
boya	boyalara	N;ACC;DEF;PL
əqrəb	əqrəblərinizi	N;ACC;PL;PSS2P
penis	penisimizə	N;DAT;SG;PSS3P
kərtənkələ	kərtənkələnin	N;GEN;DEF;SG
dırnaq	dırnaqlarımızın	N;GEN;PL;PSS3P
həqiqət	həqiqət	N;NOM;SG
gön	gönlər	N;NOM;PL
sümük	sümüklərinizi	N;ACC;PL;PSS2P
köynək	köynəyimizin	N;GEN;SG;PSS3P
oyuncaq	oyuncağa	N;ACC;DEF;SG
xəzinə	xəzinəsində	N;LOC;SG;PSS3P
alça	alçalardan	N;ABL;PL
müzakirə	müzakirəmizdən	N;ABL;SG;PSS3P
ilan	ilanlarda	N;LOC;PL
qulaq	qulaqda	N;LOC;SG
fəlsəfə	fəlsəfələrimizi	N;ACC;PL;PSS3P
dolab	dolabların	N;GEN;DEF;PL
baldız	baldızlarımda	N;LOC;PL;PSS1S
mehrab	mehrablardan	N;ABL;PL
keçi	keçini	N;ACC;DEF;SG
kəfgir	kəfgirlərinin	N;GEN;PL;PSS2S
düşman	düşmana	N;ACC;DEF;SG
fəlsəfə	fəlsəfəsinə	N;DAT;SG;PSS3S
göbək	göbəklərə	N;ACC;DEF;PL
dırnaq	dırnaqlarınız	N;NOM;PL;PSS2P
pilləkən	pilləkənləri	N;ACC;DEF;PL
qardaş	qardaşlarımda	N;LOC;PL;PSS1S
tərcümə	tərcümələrini	N;ACC;PL;PSS2S
vaza	vazalar	N;NOM;PL
xəritə	xəritəsinə	N;DAT;SG;PSS3P
fəlsəfə	fəlsəfələrimizə	N;DAT;PL;PSS3P
zəfəran	zəfəranda	N;LOC;SG
temperatur	temperturdan	N;ABL;SG
dinozavr	dinozavr	N;NOM;SG
tərcümə	tərcüməsində	N;LOC;SG;PSS3S
göz	gözlərə	N;ACC;DEF;PL
üz	üzlərdən	N;ABL;PL
kölgə	kölgəsini	N;ACC;SG;PSS3S
həqiqət	həqiqətlərin	N;GEN;DEF;PL
bağırtı	bağırtılara	N;ACC;DEF;PL
onurğa	onurğası	N;NOM;SG;PSS3S
baldız	baldızlarınız	N;NOM;PL;PSS2P
alça	alçalarıma	N;DAT;PL;PSS1S
kaktus	kaktusa	N;ACC;DEF;SG
əqrəb	əqrəbimdə	N;LOC;SG;PSS1S
mizrab	mizrablarda	N;LOC;PL
buynuz	buynuzlarının	N;GEN;PL;PSS3P
xər	xərin	N;GEN;DEF;SG
skripka	skripkadan	N;ABL;SG
vəziyyət	vəziyyətindən	N;ABL;SG;PSS3P
hörümçək	hörümçəklərin	N;NOM;PL;PSS2S
baldız	baldızında	N;LOC;SG;PSS3S
diqqət	diqqətlərdən	N;ABL;PL
ensiklopediya	ensiklopediyaların	N;GEN;DEF;PL
yemiş	yemişlərini	N;ACC;PL;PSS3S
qələbə	qələbələrdə	N;LOC;PL
təzyiq	təzyiqlərdə	N;LOC;PL
dünya	dünyamda	N;LOC;SG;PSS1S
uşaqlıq	uşaqlıqlarına	N;DAT;PL;PSS3S
dayanacaq	dayanacaqları	N;ACC;DEF;PL
buynuz	buynuzlarında	N;LOC;PL;PSS3S
bağırsaq	bağırsaqların	N;GEN;DEF;PL
amfiteatr	amfiteatrda	N;LOC;SG
şaftalı	şaftalıları	N;NOM;PL;PSS3S
qardaş	qardaşınızı	N;ACC;SG;PSS2P
arxiv	arxivimizin	N;GEN;SG;PSS3P
dirsək	dirsəyimizdən	N;ABL;SG;PSS3P
dibçək	dibçəyə	N;ACC;DEF;SG
buynuz	buynuzum	N;NOM;SG;PSS1S
dirsək	dirsəyində	N;LOC;SG;PSS3S
cəsəd	cəsəddə	N;LOC;SG
açar	açarının	N;GEN;SG;PSS2S
hüceyrə	hüceyrələrim	N;NOM;PL;PSS1S
sarımsaq	sarımsaqlardan	N;ABL;PL
yağış	yağışları	N;ACC;DEF;PL
vəziyyət	vəziyyətlərindən	N;ABL;PL;PSS3S
kəfgir	kəfgirimizdən	N;ABL;SG;PSS3P
kəfgir	kəfgirinin	N;GEN;SG;PSS3S
mənzərə	mənzərələrində	N;LOC;PL;PSS3P
təyyarə	təyyarədə	N;LOC;SG
qardaş	qardaşının	N;GEN;SG;PSS2S
vaza	vazalarında	N;LOC;PL;PSS3P
qəlb	qəlblərində	N;LOC;PL;PSS3S
uşaqlıq	uşaqlıqlarınızı	N;ACC;PL;PSS2P
vertolyot	vertolyotları	N;ACC;DEF;PL
düşmən	düşmənlərdə	N;LOC;PL
arxiv	arxivini	N;ACC;SG;PSS2S
fahişə	fahişəni	N;ACC;DEF;SG
tülpan	tülpandan	N;ABL;SG
şahmat	şahmatlardan	N;ABL;PL
təbiət	təbiətin	N;GEN;DEF;SG
istifadəçi	istifadəçilərin	N;GEN;DEF;PL
dovşan	dovşandan	N;ABL;SG
süngü	süngünüzdən	N;ABL;SG;PSS2P
ana	anasına	N;DAT;SG;PSS3S
hörümçək	hörümçəklərinə	N;DAT;PL;PSS3S
qəlsəmə	qəlsəmədə	N;LOC;SG
bayraq	bayraqlardan	N;ABL;PL
düşərgə	düşərgələrdən	N;ABL;PL
mismar	mismarda	N;LOC;SG
tərcümə	tərcümələrin	N;NOM;PL;PSS2S
kəlbətin	kəlbətindən	N;ABL;SG
cücü	cücülərdən	N;ABL;PL
ana	anama	N;DAT;SG;PSS1S
motosiklet	motosikletlərdə	N;LOC;PL
canavar	canavar	N;NOM;SG
sümük	sümüyündən	N;ABL;SG;PSS3P
film	filmlər	N;NOM;PL
yəhudi	yəhudi	N;NOM;SG
biçin	biçinin	N;GEN;DEF;SG
qatar	qatarı	N;ACC;DEF;SG
əqrəb	əqrəb	N;NOM;SG
fəaliyyət	fəaliyyətlərindən	N;ABL;PL;PSS3S
tısbağa	tısbağadan	N;ABL;SG
bağban	bağbanların	N;GEN;DEF;PL
mədrəsə	mədrəsələrdə	N;LOC;PL
can	candan	N;ABL;SG
silah	silahları	N;ACC;DEF;PL
dırnaq	dırnağın	N;NOM;SG;PSS2S
dirsək	dirsəklərim	N;NOM;PL;PSS1S
vəziyyət	vəziyyəti	N;NOM;SG;PSS3S
qızılgül	qızılgülləri	N;ACC;DEF;PL
ilan	ilanları	N;ACC;DEF;PL
saqqal	saqqalları	N;ACC;DEF;PL
ördək	ördəklərdən	N;ABL;PL
dinozavr	dinozavrlarınız	N;NOM;PL;PSS2P
ərik	əriyinin	N;GEN;SG;PSS2S
nəticə	nəticəyə	N;ACC;DEF;SG
dinozavr	dinozavrlarından	N;ABL;PL;PSS3S
beyin	beynindən	N;ABL;SG;PSS3P
dəyirman	dəyirmana	N;ACC;DEF;SG
dirsək	dirsəyində	N;LOC;SG;PSS3P
müzakirə	müzakirələrini	N;ACC;PL;PSS3S
xoruz	xoruzda	N;LOC;SG
açar	açarların	N;NOM;PL;PSS2S
mələk	mələyimizdən	N;ABL;SG;PSS3P
süngü	süngülərinizdə	N;LOC;PL;PSS2P
diqqət	diqqətdən	N;ABL;SG
uşaqlıq	uşaqlığını	N;ACC;SG;PSS3S
sivilizasiya	sivilizasiyalar	N;NOM;PL
namaz	namazımda	N;LOC;SG;PSS1S
baldız	baldızdan	N;ABL;SG
qonşu	qonşudan	N;ABL;SG
süngü	süngümüzə	N;DAT;SG;PSS3P
müzakirə	müzakirələrimizdə	N;LOC;PL;PSS3P
qulaq	qulaqlarımda	N;LOC;PL;PSS1S
açar	açarı	N;ACC;DEF;SG
böyürtkən	böyürtkəndə	N;LOC;SG
