motabang	motabang	V;FUT
mobuhat	ningbuhat	V;PROG;PRS
molingkod	molingkod	V;NFIN
mosulat	ningsulat	V;PROG;PRS
mogawas	ninggawas	V;PROG;PRS
molupad	ninglupad	V;PROG;PRS
magkinahanglan	magkinahanglan	V;FUT
mohikap	nahikap	V;PRF;PST
mohinumdom	ninghinumdom	V;PROG;PRS
mobasa	mobasa	V;FUT
mohikap	ninghikap	V;PROG;PRS
modagan	nidagan	V;PST
moadto	ning-adto	V;PROG;PRS
moangkon	ningangkon	V;PROG;PRS
daw	daw	V;PRS
mohigugma	naghigugma	V;PRS
mopaila	mopaila	V;FUT
maganahan	naganahan	V;PRF;PST
mokaon	nikaon	V;PST
mokatawa	mokatawa	V;NFIN
magluto	magluto	V;NFIN
makat-on	makat-on	V;NFIN
makat-on	nakat-on	V;PRF;PST
mopakita	mopakita	V;FUT
makadungog	makadungog	V;NFIN
mohalok	nakahalok	V;PRF;PST
mokanta	nakanta	V;PRF;PST
daw	daw	V;PROG;PRS
mohuna-huna	mohuna-huna	V;FUT
mokatawa	ningkatawa	V;PROG;PRS
masayod	nasayod	V;PST
moaway	ning-away	V;PROG;PRS
mahulog	nahulog	V;PST
motrabaho	natrabaho	V;PRF;PST
momaneho	nagmaneho	V;PRS
mopahiyom	mopahiyom	V;NFIN
modagan	modagan	V;FUT
makadungog	nakadungog	V;PRF;PST
mohigda	mohigda	V;FUT
mobalik	nabalik	V;PRF;PST
mobaligya	nabaligya	V;PRF;PST
masayod	masayod	V;NFIN
mohikap	nihikap	V;PST
mosugod	nakasugod	V;PRF;PST
moimbitar	nangimbitar	V;PRS
mahulog	nahulog	V;PRF;PST
maminaw	maminaw	V;FUT
mamatay	mamatay	V;FUT
mohilak	nihilak	V;PRF;PST
momaneho	ningmaneho	V;PROG;PRS
mohalok	mohalok	V;NFIN
motawag	ningtawag	V;PROG;PRS
mohilak	naghilak	V;PRS
mohikap	mohikap	V;NFIN
moginhawa	moginhawa	V;NFIN
mogawas	gawas	V;PRS
makadungog	nakadungog	V;PRS
makahibalo	makahibalo	V;NFIN
mosulat	nisulat	V;PST
mamati	namati	V;PRS
makat-on	ningkat-on	V;PROG;PRS
mogamit	ninggamit	V;PROG;PRS
mobati	mobati	V;NFIN
mopataas	mopataas	V;FUT
mohuman	nahuman	V;PRF;PST
motrabaho	motrabaho	V;FUT
mokuha	nakuha	V;PRF;PST
mopahiyom	nipahiyom	V;PST
moduwa	nagduwa	V;PRF;PST
mahimo nga	nahimo nga	V;PST
mosabot	nasabot	V;PRF;PST
mohinumdom	mohinumdom	V;FUT
moabli	ning-abli	V;PROG;PRS
makahibalo	makahibalo	V;FUT
magtinguha	nagtinguha	V;PROG;PRS
mobuak	nabuak	V;PRF;PST
mopahiyom	nagpahiyom	V;PRS
mobyahe	nabyahe	V;PRF;PST
mopaila	ningpaila	V;PROG;PRS
motubag	nagtubag	V;PRS
mohuna-huna	naghuna-huna	V;PRS
mopabilin	mopabilin	V;NFIN
makahibalo	nahibalo-an	V;PRF;PST
mabuhi	nabuhi	V;PRF;PST
motan-aw	motan-aw	V;FUT
mahulog	mahulog	V;NFIN
mopabilin	nipabilin	V;PST
moestorya	ni-estorya	V;PST
matulog	natulog	V;PST
magluto	nagluto	V;PRS
mokanta	nikanta	V;PST
mawad-an	nawad-an	V;PST
moinom	ninginom	V;PROG;PRS
magtinguha	nagtinguha	V;PRF;PST
makat-on	nagkat-on	V;PRS
mohatod	ninghatod	V;PROG;PRS
mohalok	ninghalok	V;PROG;PRS
motudlo	motudlo	V;NFIN
mohatag	nihatag	V;PST
moimbitar	ningimbitar	V;PROG;PRS
aduna	aduna	V;NFIN
magkinahanglan	nagkinahanglan	V;PRS
daw	daw	V;NFIN
moginhawa	nagginhawa	V;PRS
mohinumdom	mohinumdom	V;NFIN
motrabaho	motrabaho	V;NFIN
aduna	aduna	V;PROG;PRS
modesider	nakadesider	V;PRF;PST
motan-aw	nagtan-aw	V;PRS
makahibalo	nahibalo	V;PRS
mawad-an	nawad-an	V;PRS
