epitet	epitetke	N;DAT
matros	matrosnıñ	N;GEN
İskoçiya	İskoçiyağa	N;DAT
qalav	qalavdan	N;ABL
arnavut	arnavut	ADJ;NOM
avlaq	avlaqtan	ADJ;ABL
konveyer	konveyerge	N;DAT
baytal	baytalnıñ	N;GEN
metr	metrden	N;ABL
bulğar	bulğarnı	ADJ;ACC
kontrol	kontrol	N;NOM
ravvin	ravvinni	N;ACC
ekstremizm	ekstremizmden	N;ABL
marafon	marafonğa	N;DAT
qol	qolnı	N;ACC
ayatiyat	ayatiyatqa	N;DAT
bürçe	bürçege	N;DAT
kontributsiya	kontributsiyada	N;LOC
felyeton	felyetonğa	N;DAT
ziytin	ziytinde	N;LOC
kontrol	kontrolniñ	N;GEN
fetr	fetr	N;NOM
cemiş	cemiş	N;NOM
markof	markof	N;NOM
öç	öçniñ	N;GEN
radiy	radiyden	N;ABL
avgustos	avgustosnı	N;ACC
segregatsiya	segregatsiyağa	N;DAT
qar	qar	N;NOM
tegenek	tegenek	N;NOM
radius	radiusta	N;LOC
domatis	domatisni	N;ACC
figura	figura	N;NOM
radiy	radiyge	N;DAT
kilim	kilimge	N;DAT
buksir	buksirni	N;ACC
çömüç	çömüçten	N;ABL
kilometr	kilometrni	N;ACC
yastıq	yastıqğa	N;DAT
elifbe	elifbeden	N;ABL
kapitalist	kapitalistten	N;ABL
kontsert	kontsertte	N;LOC
abonent	abonentten	N;ABL
radiotehnika	radiotehnikanıñ	N;GEN
ağıl	ağıldan	N;ABL
amamlıq	amamlıqnıñ	N;GEN
hastahane	hastahaneniñ	N;GEN
havuz	havuznı	N;ACC
kinoteatr	kinoteatrden	N;ABL
eskalator	eskalatornı	N;ACC
emşek	emşekke	N;DAT
klinika	klinikanıñ	N;GEN
qıta	qıtadan	N;ABL
komediya	komediyağa	N;DAT
qabaqbaş	qabaqbaşnıñ	N;GEN
Utarit	Utaritni	N;ACC
qardaş	qardaşta	N;LOC
ziytin	ziytinden	N;ABL
kaloriya	kaloriyada	N;LOC
qamır	qamırnıñ	N;GEN
abay	abaydan	N;ABL
embrion	embrion	N;NOM
manjet	manjette	N;LOC
regata	regatanıñ	N;GEN
islâatçı	islâatçığa	N;DAT
avtograf	avtograftan	N;ABL
cürmek	cüre	V;SG;3;PRS
raps	rapsnıñ	N;GEN
şeklemek	şekley	V;SG;3;PRS
millimetr	millimetrge	N;DAT
düve	düveni	N;ACC
flang	flangnı	N;ACC
burçaq	burçaqta	N;LOC
sipirtki	sipirtkide	N;LOC
konservatoriya	konservatoriyanı	N;ACC
repatriatsiya	repatriatsiyanı	N;ACC
qoşqar	qoşqardan	N;ABL
şayba	şaybanıñ	N;GEN
çoban	çoban	N;NOM
zeer	zeer	N;NOM
kollektiv	kollektiv	N;NOM
avantüra	avantüranıñ	N;GEN
faktor	faktornı	N;ACC
agressiya	agressiyanıñ	N;GEN
zeer	zeerge	N;DAT
raport	raportnı	N;ACC
ekşimek	ekşi	V;IMP;SG;2
trampete	trampeteniñ	N;GEN
qaramaq	qara	V;IMP;SG;2
kuporos	kuporosnıñ	N;GEN
reformizm	reformizmden	N;ABL
para	paradan	N;ABL
kapital	kapitalda	ADJ;LOC
qapatmaq	qapatmaq	V;NFIN
yumruq	yumruqnıñ	N;GEN
şkala	şkalağa	N;DAT
emçek	emçekni	N;ACC
vazife	vazifede	N;LOC
metr	metrniñ	N;GEN
reproduktor	reproduktorda	N;LOC
aborigen	aborigen	N;NOM
kapitan	kapitan	N;NOM
batareya	batareyağa	N;DAT
cuvmaq	cuvdı	V;SG;3;PST
kongress	kongress	N;NOM
cengil	cengilni	ADJ;ACC
serbestlik	serbestlikniñ	N;GEN
qudret	qudretni	N;ACC
ayle	ayleden	N;ABL
sirke	sirkege	N;DAT
relâtivizm	relâtivizmniñ	N;GEN
ferüze	ferüzeniñ	N;GEN
kiçik parmaq	kiçik parmaqnıñ	N;GEN
sektantlıq	sektantlıqnı	N;ACC
yipek	yipekte	N;LOC
begitmek	begite	V;SG;3;PRS
balıqçı	balıqçığa	N;DAT
qoçqar	qoçqardan	N;ABL
brigada	brigadadan	N;ABL
matematik	matematik	N;NOM
başmaq	başmaqta	N;LOC
buksir	buksir	N;NOM
lektsiya	lektsiyağa	N;DAT
tegenek	tegenekni	N;ACC
evolütsiya	evolütsiyanıñ	N;GEN
avangard	avangardnıñ	N;GEN
servi	serviden	N;ABL
ekspress	ekspress	N;NOM
qolçaq	qolçaqqa	N;DAT
massa	massadan	N;ABL
şosse	şosseden	N;ABL
ırmaq	ırmaqta	N;LOC
moğol	moğoldan	N;ABL
ökmek	ökmekniñ	N;GEN
bank	bankqa	N;DAT
epitet	epitetten	N;ABL
eskadrilya	eskadrilya	N;NOM
sıqlıq	sıqlıq	N;NOM
taqta	taqta	N;NOM
şip	şipni	N;ACC
maşna	maşnanıñ	N;GEN
zar	zarnıñ	N;GEN
qımırsqa	qımırsqadan	N;ABL
kooperativ	kooperativni	ADJ;ACC
konspiratsiya	konspiratsiya	N;NOM
kollektsiya	kollektsiyanı	N;ACC
rantye	rantye	N;NOM
radiostantsiya	radiostantsiya	N;NOM
tırnaq	tırnaqnıñ	N;GEN
sektsiya	sektsiyadan	N;ABL
süngü	süngüden	N;ABL
icviyci	icviyciniñ	N;GEN
estetika	estetikanı	N;ACC
ana til	ana tilge	N;DAT
capmaq	capa	V;SG;3;PRS
resurs	resursnı	N;ACC
keşe	keşege	N;DAT
material	materialda	N;LOC
tamir	tamirnı	N;ACC
cengil	cengil	ADJ;NOM
selektsiya	selektsiyanı	N;ACC
calbarmaq	calbara	V;SG;3;PRS
labirint	labirint	N;NOM
elevator	elevator	N;NOM
laqşa	laqşanı	N;ACC
eşelon	eşelonğa	N;DAT
kombinatsiya	kombinatsiyadan	N;ABL
bank	bank	N;NOM
kompozitor	kompozitornıñ	N;GEN
tiz	tizge	N;DAT
roman	romanğa	N;DAT
tuman	tumannıñ	N;GEN
riñg	riñgnıñ	N;GEN
material	material	N;NOM
ağır	ağır	ADJ;NOM
Zemin	Zeminde	N;LOC
küntabaq	küntabaqnı	N;ACC
faşizm	faşizmden	N;ABL
reministsentsiya	reministsentsiyanı	N;ACC
mıh	mıhqa	N;DAT
massiv	massivge	N;DAT
koeffitsiyent	koeffitsiyentni	N;ACC
reportör	reportörnıñ	N;GEN
sıra	sıranı	N;ACC
ayvan	ayvannı	N;ACC
brigada	brigadanı	N;ACC
şertmek	şertti	V;SG;3;PST
nomera	nomera	N;NOM
ada	adağa	N;DAT
ekstremizm	ekstremizmni	N;ACC
elifbe	elifbe	N;NOM
şive	şiveden	N;ABL
kapital	kapital	N;NOM
basseyn	basseynni	N;ACC
yemiş	yemişke	N;DAT
makaron	makaronnıñ	N;GEN
fransız	fransızğa	N;DAT
krem	kremni	N;ACC
qapı	qapıda	N;LOC
revanşizm	revanşizmni	N;ACC
energiya	energiyanı	N;ACC
meydan	meydannı	N;ACC
şontuq	şontuqta	ADJ;LOC
abonent	abonentniñ	N;GEN
çoqraq	çoqraqtan	N;ABL
rekord	rekordda	N;LOC
monopoliya	monopoliyağa	N;DAT
sandalet	sandaletten	N;ABL
monarhiya	monarhiyanı	N;ACC
konvoy	konvoyğa	N;DAT
qap	qapnıñ	N;GEN
paket	paketten	N;ABL
analiz	analizniñ	N;GEN
bav	bavga	N;DAT
erinşek	erinşekke	ADJ;DAT
müzey	müzeyge	N;DAT
bödene	bödene	N;NOM
radikal	radikaldan	N;ABL
qum	qumda	N;LOC
kinofilm	kinofilmden	N;ABL
kuporos	kuporosqa	N;DAT
marksizm	marksizm	N;NOM
burav	buravnı	N;ACC
pala	paladan	N;ABL
ada	adanı	N;ACC
amam	amamnıñ	N;GEN
sekundant	sekundantnıñ	N;GEN
vişne	vişneye	N;DAT
revolver	revolver	N;NOM
karikatura	karikatura	N;NOM
ventilâtor	ventilâtordan	N;ABL
cemiş	cemişni	N;ACC
qurna	qurnada	N;LOC
çini	çinide	ADJ;LOC
burşaq	burşaqta	N;LOC
brezent	brezentniñ	N;GEN
yuvğuç	yuvğuçnıñ	N;GEN
model	model	N;NOM
fetr	fetrde	N;LOC
baba	babadan	N;ABL
cuvaş	cuvaş	ADJ;NOM
reflektor	reflektornı	N;ACC
kinostudiya	kinostudiyağa	N;DAT
şoför	şoförniñ	N;GEN
ekspress	ekspressniñ	N;GEN
şontuq	şontuqnı	ADJ;ACC
kooperativ	kooperativniñ	N;GEN
alabota	alabotağa	N;DAT
komandan	komandannıñ	N;GEN
kürek	kürekke	N;DAT
kriteriy	kriteriyde	N;LOC
endokrin bezler	endokrin bezlerni	N;ACC
senek	senekniñ	N;GEN
şura	şuranı	N;ACC
qavun	qavundan	N;ABL
banq	banqnıñ	N;GEN
apay	apaydan	N;ABL
şorap	şorapğa	N;DAT
kubalı	kubalığa	N;DAT
domuz	domuz	N;NOM
ağır	ağırğa	ADJ;DAT
komediya	komediya	N;NOM
akkord	akkordğa	N;DAT
ratsionalizatsiya	ratsionalizatsiya	N;NOM
kod	kodda	N;LOC
amam	amamnı	N;ACC
fotosüret	fotosüretni	N;ACC
labirint	labirintniñ	N;GEN
rıtsar	rıtsarda	N;LOC
ayaz	ayaznı	N;ACC
fortepyano	fortepyanoğa	N;DAT
qar	qarnı	N;ACC
cuvmaq	cuvmaq	V;NFIN
maskarad	maskaraddan	N;ABL
çoqraq	çoqraqnıñ	N;GEN
kadâ	kadâ	N;NOM
sarplıq	sarplıqnıñ	N;GEN
köküs	köküsten	N;ABL
embargo	embargonı	N;ACC
büst	büstten	N;ABL
şip	şipke	N;DAT
gemi	gemide	N;LOC
imza	imza	N;NOM
qoy	qoydan	N;ABL
ekskursiya	ekskursiya	N;NOM
reaktsiya	reaktsiya	N;NOM
cırtmaq	cırtdı	V;SG;3;PST
final	finalnı	ADJ;ACC
sazan	sazannı	N;ACC
riñg	riñg	N;NOM
komissar	komissarğa	N;DAT
mehanik	mehanikten	N;ABL
kesertki	kesertkini	N;ACC
memorial	memorialda	ADJ;LOC
molekula	molekulağa	N;DAT
komplekt	komplektten	N;ABL
cara	caranıñ	N;GEN
büst	büst	N;NOM
nebatat	nebatatta	N;LOC
çadır	çadırdan	N;ABL
reformator	reformatordan	N;ABL
evolütsiya	evolütsiya	N;NOM
tüzetme	tüzetmeden	N;ABL
ayaqqap	ayaqqapnıñ	N;GEN
mektüp	mektüpten	N;ABL
adım	adımğa	N;DAT
agronom	agronomnı	N;ACC
öç	öçte	N;LOC
memorial	memorialnıñ	N;GEN
tamğa	tamğağa	N;DAT
ventilâtor	ventilâtornıñ	N;GEN
advokat	advokattan	N;ABL
monolog	monologdan	N;ABL
magistral	magistralge	N;DAT
coğrafiya	coğrafiyanı	N;ACC
noyabr	noyabrden	N;ABL
kondensator	kondensatornı	N;ACC
duşman	duşmandan	N;ABL
fişenk	fişenk	N;NOM
eserli	eserliniñ	ADJ;GEN
fligel	fligelde	N;LOC
mandarin	mandarinde	N;LOC
kayuta	kayuta	N;NOM
cığılmaq	cığılmaq	V;NFIN
dımlıq	dımlıqtan	N;ABL
qırmısqa	qırmısqa	N;NOM
öşek	öşekte	N;LOC
qabaqbaş	qabaqbaşnı	N;ACC
mektep	mektepni	N;ACC
paket	paketke	N;DAT
imza	imzanı	N;ACC
çinke	çinkeden	N;ABL
mayor	mayor	N;NOM
çot	çotta	N;LOC
ratsionalizm	ratsionalizmge	N;DAT
refleksologiya	refleksologiyada	N;LOC
qavun	qavunğa	N;DAT
cibermek	ciberdi	V;SG;3;PST
matematik	matematikni	ADJ;ACC
kokos	kokosqa	N;DAT
qan	qan	N;NOM
krossvord	krossvordda	N;LOC
qampa	qampanıñ	N;GEN
sazan	sazannıñ	N;GEN
deñizci	deñizcini	N;ACC
çorap	çoraptan	N;ABL
uyalmaq	uyaldı	V;SG;3;PST
efir	efirni	N;ACC
sarı turup	sarı turupnıñ	N;GEN
replika	replika	N;NOM
fransız	fransızdan	ADJ;ABL
referendum	referendumda	N;LOC
ayvan	ayvanğa	N;DAT
dögme	dögmeden	N;ABL
bödene	bödeneni	N;ACC
barja	barja	N;NOM
köküs	köküsniñ	N;GEN
kâr	kârğa	N;DAT
sığırçıq	sığırçıqtan	N;ABL
kölek	kölekıñ	N;GEN
estafeta	estafetağa	N;DAT
çontuq	çontuqnıñ	ADJ;GEN
elektrostantsiya	elektrostantsiya	N;NOM
islâatçı	islâatçıdan	N;ABL
reportaj	reportajnıñ	N;GEN
mebel	mebelge	N;DAT
bazar	bazar	N;NOM
sanitar	sanitar	ADJ;NOM
tuvar	tuvarnıñ	N;GEN
reforma	reformada	N;LOC
adet	adetniñ	N;GEN
cılıtmaq	cılıtdı	V;SG;3;PST
cibermek	ciber	V;IMP;SG;2
yaba	yabanı	N;ACC
saylamaq	saylay	V;SG;3;PRS
qolbez	qolbez	N;NOM
kinofilm	kinofilm	N;NOM
kevde	kevde	N;NOM
afişa	afişadan	N;ABL
magistr	magistrge	N;DAT
narat	naratnıñ	N;GEN
revizionizm	revizionizmniñ	N;GEN
seysmologiya	seysmologiyanıñ	N;GEN
küntabaq	küntabaqnıñ	N;GEN
yanvar	yanvarge	N;DAT
bulvar	bulvarğa	N;DAT
aşhane	aşhaneni	N;ACC
manifestatsiya	manifestatsiya	N;NOM
bayır	bayırnıñ	N;GEN
şimşir	şimşir	N;NOM
baqır	baqırda	N;LOC
adet	adetten	N;ABL
rayon	rayonda	N;LOC
karp	karp	N;NOM
kondensator	kondensator	N;NOM
ferüze	ferüzede	N;LOC
mehanizm	mehanizm	N;NOM
rele	rele	N;NOM
frenk	frenk	N;NOM
radiologiya	radiologiyanı	N;ACC
qaynata	qaynatadan	N;ABL
flot	flotta	N;LOC
massa	massanıñ	N;GEN
aciz	acizniñ	ADJ;GEN
keşe	keşeni	N;ACC
şamata	şamata	N;NOM
caş	caşta	N;LOC
fransız	fransızda	ADJ;LOC
avtomat	avtomatnı	N;ACC
mototsikl	mototsiklden	N;ABL
sangvinik	sangvinikten	N;ABL
yoqlamaq	yoqla	V;IMP;SG;2
montör	montörnıñ	N;GEN
yapraq	yapraqtan	N;ABL
kâinat	kâinatnı	N;ACC
eccav	eccavnı	N;ACC
format	format	N;NOM
kabina	kabina	N;NOM
rükzak	rükzaktan	N;ABL
cılınmaq	cılınmaq	V;NFIN
ekvator	ekvatordan	N;ABL
cercumuran	cercumuranga	N;DAT
ekvator	ekvatorda	N;LOC
satellit	satellitte	N;LOC
cabışmaq	cabış	V;IMP;SG;2
barazna	baraznanı	N;ACC
komandan	komandan	N;NOM
cara	cara	N;NOM
tayare	tayarede	N;LOC
çorap	çorapnı	N;ACC
qıta	qıtağa	N;DAT
qampa	qampağa	N;DAT
elektriçka	elektriçkanıñ	N;GEN
qadaq	qadaqnıñ	N;GEN
imtian	imtianğa	N;DAT
bas	basnıñ	N;GEN
bedel	bedel	N;NOM
cedvel	cedvelniñ	N;GEN
ağaç	ağaçqa	N;DAT
cürek	cürekniñ	N;GEN
torğay	torğayda	N;LOC
quyruq kemigi	quyruq kemiginden	N;ABL
endokrin bezler	endokrin bezlerde	N;LOC
sarplıq	sarplıqta	N;LOC
süyek	süyekniñ	N;GEN
baş	başta	N;LOC
rapira	rapiranı	N;ACC
finiş	finişte	N;LOC
krem	kremniñ	N;GEN
çorap	çorap	N;NOM
saharoza	saharozadan	N;ABL
onğarmaq	onğar	V;IMP;SG;2
domuz	domuznı	N;ACC
biber	biber	N;NOM
mikroskop	mikroskopnı	N;ACC
relâtivizm	relâtivizmde	N;LOC
basketbol	basketbolnı	N;ACC
capmaq	cap	V;IMP;SG;2
kofta	koftanı	N;ACC
vişne	vişneni	N;ACC
şlüz	şlüzde	N;LOC
çempion	çempionnı	N;ACC
çabaq	çabaqta	N;LOC
konditer	konditerge	N;DAT
bürokrat	bürokrattan	N;ABL
regressiya	regressiyanı	N;ACC
reaktsioner	reaktsionerge	N;DAT
bet	bette	N;LOC
tirsek	tirsekniñ	N;GEN
bürşe	bürşeni	N;ACC
patates	patatese	N;DAT
aleket	aleketke	N;DAT
köşe	köşeniñ	N;GEN
yapraq	yapraq	N;NOM
rıtsar	rıtsarnı	N;ACC
çirkiy	çirkiyden	N;ABL
qısqartma	qısqartmanıñ	N;GEN
karp	karpta	N;LOC
kollektiv	kollektivniñ	ADJ;GEN
sevmek	sevdi	V;SG;3;PST
komendant	komendantqa	N;DAT
komissarlıq	komissarlıqtan	N;ABL
bina	binanıñ	N;GEN
paqla	paqlanı	N;ACC
reformizm	reformizmniñ	N;GEN
kompromiss	kompromissten	N;ABL
vişne	vişneden	N;ABL
Çolpan	Çolpanda	N;LOC
şahmat	şahmatnı	N;ACC
bilet	bilette	N;LOC
qoy	qoynıñ	N;GEN
bint	bint	N;NOM
bayır	bayırnı	N;ACC
kibernetika	kibernetika	N;NOM
funktsiya	funktsiyanıñ	N;GEN
kitabe	kitabege	N;DAT
feodalizm	feodalizm	N;NOM
büst	büstni	N;ACC
rupor	rupornıñ	N;GEN
çavke	çavkede	N;LOC
massa	massada	N;LOC
sarı turup	sarı turupnı	N;ACC
amam	amamdan	N;ABL
botqa	botqanı	N;ACC
rentgenografiya	rentgenografiyanıñ	N;GEN
şahmat	şahmatqa	N;DAT
filatelist	filatelistte	N;LOC
atmaca	atmacağa	N;DAT
matros	matrostan	N;ABL
balavuz	balavuznı	N;ACC
davuş	davuştan	N;ABL
mevsim	mevsimge	N;DAT
sıñarça parmaq	sıñarça parmaq	N;NOM
toqmaq	toqmaqdan	N;ABL
reyting	reytingniñ	N;GEN
baytal	baytaldan	N;ABL
burçaq	burçaqnıñ	N;GEN
altın	altında	N;LOC
Utarit	Utaritten	N;ABL
etika	etikada	N;LOC
böcek	böcek	N;NOM
büllür	büllürge	N;DAT
mehanizatsiya	mehanizatsiyada	N;LOC
rayon	rayonnı	N;ACC
kontributsiya	kontributsiyanıñ	N;GEN
talyar	talyarda	N;LOC
erişmek	erişe	V;SG;3;PRS
çalğı	çalğı	N;NOM
revizionizm	revizionizmde	N;LOC
sığır	sığırnı	N;ACC
fotograf	fotograf	N;NOM
vazife	vazifeni	N;ACC
fleyta	fleytağa	N;DAT
qırmısqa	qırmısqanı	N;ACC
oluq	oluqda	N;LOC
trampete	trampete	N;NOM
qartop	qartop	N;NOM
tamğa	tamğanıñ	N;GEN
köşe	köşeni	N;ACC
reportör	reportörğa	N;DAT
abiy	abiyni	N;ACC
büro	büroğa	N;DAT
rekonstruktsiya	rekonstruktsiyanıñ	N;GEN
Rumıniya	Rumıniya	N;NOM
manövr	manövrniñ	N;GEN
cez	cez	N;NOM
qımırsqa	qımırsqanı	N;ACC
domuz	domuzğa	N;DAT
ana til	ana tilde	N;LOC
uçucı	uçucığa	N;DAT
mikroskop	mikroskopqa	N;DAT
kupüra	kupüranı	N;ACC
kodein	kodeinde	N;LOC
abbat	abbatqa	N;DAT
dua	duada	N;LOC
foye	foyege	N;DAT
bestekâr	bestekârda	N;LOC
folklor	folklordan	N;ABL
abiy	abiyniñ	N;GEN
emblema	emblemada	N;LOC
kölek	kölekge	N;DAT
saga	sagada	N;LOC
kodein	kodein	N;NOM
qarılğaş	qarılğaşta	N;LOC
satellit	satellit	N;NOM
saat	saattan	N;ABL
belâ	belâ	N;NOM
ahır	ahırda	N;LOC
komendatura	komendatura	N;NOM
tamır	tamır	N;NOM
çoqluq	çoqluqqa	N;DAT
komendatura	komendaturada	N;LOC
ırğaq	ırğaqğa	N;DAT
fligel	fligelniñ	N;GEN
kâtip	kâtipte	N;LOC
şeşmek	şeş	V;IMP;SG;2
şpat	şpatnıñ	N;GEN
mayasıl	mayasıldan	N;ABL
klub	klubğa	N;DAT
uçucı	uçucıda	N;LOC
rahit	rahitten	N;ABL
ayvan	ayvanda	N;LOC
kit	kitte	N;LOC
ferma	fermağa	N;DAT
namzet	namzetke	N;DAT
oymaq	oymaq	N;NOM
başmaq	başmaqnı	N;ACC
adet	adette	N;LOC
qazaq	qazaqnı	N;ACC
tavuq	tavuqtan	N;ABL
vişne	vişnenin	N;GEN
rebus	rebustan	N;ABL
domatis	domatisten	N;ABL
paalı	paalı	ADJ;NOM
mühbir	mühbirde	N;LOC
cılamaq	cılamaq	V;NFIN
cavun	cavunğa	N;DAT
mayasıl	mayasılğa	N;DAT
kommutator	kommutatorğa	N;DAT
amam	amamda	N;LOC
qaburğa	qaburğanıñ	N;GEN
korpus	korpusta	N;LOC
balıq	balıqtan	N;ABL
pepiy	pepiyge	N;DAT
ekran	ekran	N;NOM
dimağ	dimağnıñ	N;GEN
agent	agentni	N;ACC
sol	solğa	ADJ;DAT
kristall	kristallnı	N;ACC
emulsiya	emulsiya	N;NOM
flüger	flügerniñ	N;GEN
segment	segment	N;NOM
flora	flora	N;NOM
koeffitsiyent	koeffitsiyentte	N;LOC
vişne	vişne	N;NOM
depter	depterni	N;ACC
millimetr	millimetrniñ	N;GEN
energiya	energiyağa	N;DAT
sığır	sığırğa	N;DAT
kümes	kümesni	N;ACC
dişi	dişini	N;ACC
uyalmaq	uyala	V;SG;3;PRS
qap	qapqa	N;DAT
erinçek	erinçekte	ADJ;LOC
bücet	bücette	N;LOC
uçaq	uçaqta	N;LOC
eksport	eksporttan	N;ABL
afta	aftanı	N;ACC
mıqnatis	mıqnatiske	N;DAT
çöküç	çöküçten	N;ABL
domates	domatesten	N;ABL
tolu	toluğa	ADJ;DAT
sangvinik	sangvinikke	N;DAT
köşe	köşede	N;LOC
avlaq	avlaqnıñ	N;GEN
marşrut	marşrut	N;NOM
quvet	quvet	N;NOM
egoizm	egoizm	N;NOM
qıyış	qıyışqa	ADJ;DAT
süymek	süydi	V;SG;3;PST
solaqay	solaqayda	ADJ;LOC
kreditor	kreditor	N;NOM
filtr	filtrniñ	N;GEN
qaynana	qaynanada	N;LOC
mineral	mineral	ADJ;NOM
reanimatsiya	reanimatsiyanıñ	N;GEN
şpon	şponnıñ	N;GEN
karton	kartondan	N;ABL
batareya	batareyadan	N;ABL
sektsiya	sektsiyanı	N;ACC
sabalıq aş	sabalıq aştan	N;ABL
militsiya	militsiyanıñ	N;GEN
çabaq	çabaqtan	N;ABL
eskadrilya	eskadrilyadan	N;ABL
yamav	yamavnı	N;ACC
koridor	koridorğa	N;DAT
tilşınaslıq	tilşınaslıqtan	N;ABL
revanşizm	revanşizmge	N;DAT
çirkiy	çirkiyde	N;LOC
çöküç	çöküçni	N;ACC
çaynik	çaynikni	N;ACC
imza	imzada	N;LOC
erinçek	erinçekten	ADJ;ABL
cavlıq	cavlıqnıñ	N;GEN
oluq	oluqqa	N;DAT
eşek	eşekten	N;ABL
ada	adanıñ	N;GEN
apay	apay	N;NOM
maşna	maşnanı	N;ACC
reparatsiya	reparatsiyadan	N;ABL
şimşir	şimşirden	N;ABL
el işi	el işinde	N;LOC
lirika	lirika	N;NOM
sekundomer	sekundomerni	N;ACC
kurs	kursnı	N;ACC
arqan	arqan	N;NOM
estafeta	estafetanı	N;ACC
kvitantsiya	kvitantsiyada	N;LOC
şuvultı	şuvultı	N;NOM
kreyser	kreyserni	N;ACC
cılınmaq	cılına	V;SG;3;PRS
toramaq	toramaq	V;NFIN
taqta	taqtanı	ADJ;ACC
miniatüra	miniatürada	N;LOC
yağmur	yağmurnı	N;ACC
ketek	ketekten	N;ABL
aran	aranğa	N;DAT
keşe	keşeden	N;ABL
abulqat	abulqattan	N;ABL
ravvin	ravvinge	N;DAT
estetika	estetikağa	N;DAT
sırlı keten	sırlı ketenni	N;ACC
yağ	yağnıñ	N;GEN
limon	limondan	N;ABL
kölekse	kölekseniñ	N;GEN
yavluq	yavluqta	N;LOC
kapital	kapitalğa	N;DAT
duşman	duşman	N;NOM
cıyın	cıyından	N;ABL
epizod	epizodğa	N;DAT
eroziya	eroziyağa	N;DAT
abrakadabra	abrakadabrada	N;LOC
sarkazm	sarkazmda	N;LOC
cıynamaq	cıyna	V;IMP;SG;2
makaron	makarondan	N;ABL
kontributsiya	kontributsiyadan	N;ABL
relyef	relyeften	N;ABL
lirika	lirikanı	N;ACC
repressiya	repressiyağa	N;DAT
duvadaq	duvadaqta	N;LOC
ekstremizm	ekstremizm	N;NOM
elektrostantsiya	elektrostantsiyanıñ	N;GEN
balaq	balaq	N;NOM
dım	dımda	N;LOC
qıçıruv	qıçıruvğa	N;DAT
kompozitsiya	kompozitsiyada	N;LOC
frenk	frenkte	ADJ;LOC
şökiş	şökişte	N;LOC
çarşı	çarşını	N;ACC
qaburğa	qaburğanı	N;ACC
iqtisat	iqtisatnı	N;ACC
qaramaq	qaramaq	V;NFIN
blok	bloknıñ	N;GEN
pencere	pencereni	N;ACC
çinke	çinkede	N;LOC
kapital	kapitalda	N;LOC
iyül	iyülge	N;DAT
egida	egida	N;NOM
qopqa	qopqada	N;LOC
cez	cezde	N;LOC
şlak	şlaknıñ	N;GEN
gece	geceniñ	N;GEN
yamav	yamavnıñ	N;GEN
qora	qoradan	N;ABL
agronom	agronom	N;NOM
bulğar	bulğarnıñ	ADJ;GEN
fırçı	fırçıda	N;LOC
urum	urumğa	N;DAT
felsefe	felsefeden	N;ABL
köşe	köşege	N;DAT
aşıtmaq	aşıtmaq	V;NFIN
massiv	massivde	N;LOC
devir	devirge	N;DAT
tazbaş	tazbaştan	N;ABL
kontrol	kontrolni	N;ACC
konservatoriya	konservatoriyanıñ	N;GEN
reformator	reformatordan	ADJ;ABL
abbreviatura	abbreviaturanı	N;ACC
ambar	ambardan	N;ABL
fırçı	fırçıdan	N;ABL
format	formatnı	N;ACC
mebel	mebelde	N;LOC
qolşaq	qolşaqnı	N;ACC
mayıs	mayısqa	N;DAT
şeklemek	şekle	V;IMP;SG;2
basketbol	basketboldan	N;ABL
kare	kareni	N;ACC
metro	metroğa	N;DAT
qolbez	qolbezge	N;DAT
brezent	brezentni	N;ACC
analıq	analıq	ADJ;NOM
egoizm	egoizmge	N;DAT
termen	termenniñ	N;GEN
şamek	şamekni	N;ACC
klassik	klassikke	ADJ;DAT
sıyırcıq	sıyırcıqnıñ	N;GEN
ferüze	ferüzege	N;DAT
komendant	komendanttan	N;ABL
fırçı	fırçı	N;NOM
laborant	laborantnı	N;ACC
kran	krandan	N;ABL
tırnak	tırnak	N;NOM
radio	radioğa	N;DAT
sabun	sabunğa	N;DAT
buzdağ	buzdağnıñ	N;GEN
burav	burav	N;NOM
cantaymaq	cantay	V;IMP;SG;2
cara	carağa	N;DAT
rebus	rebus	N;NOM
aqsüyek	aqsüyekke	N;DAT
qotur	qoturnı	N;ACC
miniatüra	miniatüra	N;NOM
barrikada	barrikadağa	N;DAT
allegim	allegimde	ADJ;LOC
reaktsioner	reaktsioner	N;NOM
tırtır	tırtırdan	N;ABL
segregatsiya	segregatsiya	N;NOM
sebep	sebepni	N;ACC
kompensatsiya	kompensatsiya	N;NOM
solaqay	solaqayğa	ADJ;DAT
gögercin	gögercinge	N;DAT
konspekt	konspekt	N;NOM
jirafe	jirafeniñ	N;GEN
kvartal	kvartalğa	N;DAT
oluq	oluqnıñ	N;GEN
adım	adım	N;NOM
salüt	salütnıñ	N;GEN
büro	büro	N;NOM
kontinent	kontinent	N;NOM
kriteriy	kriteriy	N;NOM
ana til	ana tilden	N;ABL
şontuq	şontuqnıñ	ADJ;GEN
ana	ananıñ	N;GEN
şeklemek	şekledi	V;SG;3;PST
qaynana	qaynana	N;NOM
botqa	botqanıñ	N;GEN
kiparis	kipariske	N;DAT
regbi	regbiden	N;ABL
vatmaq	vata	V;SG;3;PRS
qazaq	qazaq	N;NOM
qardaş	qardaşnı	N;ACC
bestekâr	bestekârdan	N;ABL
qabınmaq	qabınmaq	V;NFIN
kommuna	kommunanıñ	N;GEN
memorial	memorialnıñ	ADJ;GEN
qoşqar	qoşqarnıñ	N;GEN
karton	kartonda	N;LOC
magistral	magistralni	N;ACC
çinatiy parmaq	çinatiy parmaqnı	N;ACC
elevator	elevatorda	N;LOC
yigit	yigitke	N;DAT
tırnak	tırnaknıñ	N;GEN
bas	basqa	N;DAT
devir	devirden	N;ABL
senek	senekke	N;DAT
abonent	abonentte	N;LOC
figura	figuranı	N;ACC
tenbel	tenbelniñ	N;GEN
çalğı	çalğıdan	N;ABL
toqmaq	toqmaqnı	N;ACC
baqla	baqlada	N;LOC
agitator	agitatordan	N;ABL
rekonstruktsiya	rekonstruktsiyada	N;LOC
filial	filialğa	N;DAT
başmaq	başmaqnıñ	N;GEN
qımırsqa	qımırsqağa	N;DAT
folklor	folklornıñ	ADJ;GEN
serbestlik	serbestlik	N;NOM
gimn	gimnge	N;DAT
çaynik	çaynikten	N;ABL
marinad	marinadnı	N;ACC
hastahane	hastahaneden	N;ABL
arnavut	arnavutnı	N;ACC
mayor	mayornıñ	N;GEN
tüyreviç	tüyreviçniñ	N;GEN
qısqaç	qısqaç	N;NOM
pötük	pötükniñ	N;GEN
qıraliçe	qıraliçeden	N;ABL
mobilizatsiya	mobilizatsiya	N;NOM
tepmek	tepmek	V;NFIN
klassik	klassikke	N;DAT
sarkazm	sarkazmğa	N;DAT
noyabr	noyabrde	N;LOC
tırnaq	tırnaqtan	N;ABL
kombayncı	kombayncığa	N;DAT
skemle	skemleniñ	N;GEN
mıyıq	mıyıq	N;NOM
manifest	manifest	N;NOM
eşek	eşekte	N;LOC
şaynik	şaynikten	N;ABL
parça	parçadan	N;ABL
sviter	sviterni	N;ACC
poçtacı	poçtacı	N;NOM
reministsentsiya	reministsentsiyada	N;LOC
skemle	skemle	N;NOM
sadizm	sadizmni	N;ACC
regbi	regbide	N;LOC
makaron	makaronda	N;LOC
qaarli	qaarli	ADJ;NOM
komissarlıq	komissarlıqnı	N;ACC
buz	buzda	N;LOC
köz	közden	N;ABL
reministsentsiya	reministsentsiya	N;NOM
militarizm	militarizmge	N;DAT
massiv	massiv	N;NOM
şlâpa	şlâpanı	N;ACC
fransız	fransızğa	ADJ;DAT
saylıq	saylıqnı	N;ACC
bronhit	bronhitni	N;ACC
çot	çotnıñ	N;GEN
magistr	magistr	N;NOM
künesuv	künesuv	N;NOM
karnaval	karnaval	N;NOM
panca	pancanıñ	N;GEN
sandalet	sandaletniñ	N;GEN
rele	releden	N;ABL
kürpe	kürpede	N;LOC
funktsiya	funktsiyanı	N;ACC
begitmek	begitmek	V;NFIN
kilogramm	kilogrammdan	N;ABL
Zemin	Zeminniñ	N;GEN
allegim	allegimniñ	ADJ;GEN
öpmek	öp	V;IMP;SG;2
kvitantsiya	kvitantsiyağa	N;DAT
öküz	öküzge	N;DAT
top qundağı	top qundağından	N;ABL
qısqaayaq	qısqaayaq	N;NOM
yaba	yabanıñ	N;GEN
kombayncı	kombayncıdan	N;ABL
restavratsiya	restavratsiyada	N;LOC
soğan	soğannıñ	N;GEN
el	elde	N;LOC
marka	markadan	N;ABL
fikir	fikirniñ	N;GEN
aqquş	aqquştan	N;ABL
vatmaq	vat	V;IMP;SG;2
ferik	ferik	N;NOM
kooperativ	kooperativ	N;NOM
radiologiya	radiologiyadan	N;ABL
sır	sırda	N;LOC
quvet	quvetniñ	N;GEN
kodein	kodeinni	N;ACC
capmaq	capmaq	V;NFIN
qoñuz	qoñuzda	N;LOC
köşe	köşe	N;NOM
egeşmek	egeşti	V;SG;3;PST
şahmat	şahmattan	N;ABL
parmaq	parmaq	N;NOM
qona	qonanıñ	N;GEN
şosse	şosse	N;NOM
tüzetme	tüzetmeni	N;ACC
riyaziyat	riyaziyattan	N;ABL
lirika	lirikada	N;LOC
şot	şottan	N;ABL
ceviz	cevizde	N;LOC
qısqartma	qısqartmada	N;LOC
epitet	epitetniñ	N;GEN
kooperatsiya	kooperatsiyanı	N;ACC
mehanizm	mehanizmni	N;ACC
Çolpan	Çolpannı	N;ACC
qampa	qampadan	N;ABL
pul	pulğa	N;DAT
hardal	hardalda	N;LOC
ceviz	cevizden	N;ABL
namaz	namaz	N;NOM
qona	qonadan	N;ABL
kabina	kabinanıñ	N;GEN
sıyır	sıyırnı	N;ACC
qapulbaqa	qapulbaqa	N;NOM
kodein	kodeinden	N;ABL
çinke	çinke	N;NOM
reytuz	reytuznıñ	N;GEN
duş	duşta	N;LOC
imza	imzadan	N;ABL
iytemek	iytey	V;SG;3;PRS
fligel	fligelden	N;ABL
akkord	akkordnı	N;ACC
gemi	gemini	N;ACC
qan taş	qan taşta	N;LOC
manjet	manjetni	N;ACC
ölçü	ölçüge	N;DAT
köpük	köpükte	N;LOC
mebel	mebelniñ	N;GEN
avantüra	avantüradan	N;ABL
ceviz	cevizni	N;ACC
brilliant	brilliant	N;NOM
kombinatsiya	kombinatsiyanı	N;ACC
sapfir	sapfir	N;NOM
karp	karpnıñ	N;GEN
dostluq	dostluqtan	N;ABL
konstatatsiya	konstatatsiyanı	N;ACC
sıyırcıq	sıyırcıqtan	N;ABL
cürek	cürekni	N;ACC
caş	caşqa	ADJ;DAT
maqsat	maqsatta	N;LOC
radiator	radiatorda	N;LOC
mühbir	mühbirniñ	N;GEN
dada	dadağa	N;DAT
kit	kitni	N;ACC
cıltıramaq	cıltıra	V;IMP;SG;2
minus	minusnı	N;ACC
kesquyruq	kesquyruqtan	N;ABL
konsul	konsul	ADJ;NOM
baton	batonnı	N;ACC
semafor	semaforğa	N;DAT
folklor	folklorğa	ADJ;DAT
narat	naratqa	N;DAT
fikir	fikirni	N;ACC
kinostudiya	kinostudiya	N;NOM
cel	celden	N;ABL
torğay	torğayğa	N;DAT
korpus	korpusnıñ	N;GEN
kotlet	kotletten	N;ABL
brigadir	brigadirge	N;DAT
agronom	agronomnıñ	N;GEN
ayvanat	ayvanatqa	N;DAT
depter	depterge	N;DAT
filial	filialdan	N;ABL
model	modelni	N;ACC
fortepyano	fortepyano	N;NOM
estetika	estetika	N;NOM
agronom	agronomda	N;LOC
iyül	iyülde	N;LOC
çabaq	çabaqqa	N;DAT
cığılmaq	cığıldı	V;SG;3;PST
el	elden	N;ABL
fortepyano	fortepyanonıñ	N;GEN
uyalmaq	uyalmaq	V;NFIN
qoçqar	qoçqarğa	N;DAT
fosfor	fosfordan	N;ABL
çini	çininiñ	N;GEN
şipşe	şipşeden	N;ABL
kare	karede	N;LOC
qan	qanda	N;LOC
cemiş	cemişten	N;ABL
cantaymaq	cantaymaq	V;NFIN
apis	apisten	N;ABL
qarğa	qarğa	N;NOM
keten	ketenge	N;DAT
materializm	materializmda	N;LOC
qapıcı	qapıcıda	N;LOC
yastıq	yastıqnı	N;ACC
şoför	şoförge	N;DAT
brigada	brigadağa	N;DAT
ağaş	ağaşnıñ	N;GEN
kapital	kapitalğa	ADJ;DAT
kubalı	kubalı	N;NOM
saninstruktor	saninstruktornı	N;ACC
top qundağı	top qundağınıñ	N;GEN
cuqa	cuqağa	ADJ;DAT
fenerlik	fenerlikniñ	N;GEN
raport	raport	N;NOM
cengil	cengilde	ADJ;LOC
gaz	gaznıñ	N;GEN
isveç	isveç	N;NOM
ştan	ştannıñ	N;GEN
quyruq kemigi	quyruq kemiginde	N;LOC
şamata	şamatanıñ	N;GEN
qoçqar	qoçqarnı	N;ACC
şorap	şorapda	N;LOC
kontakt	kontaktqa	N;DAT
şpatel	şpatel	N;NOM
renegat	renegatnı	N;ACC
ayaz	ayazda	N;LOC
asker	askerniñ	N;GEN
bilet	biletke	N;DAT
camanlamaq	camanla	V;IMP;SG;2
avtobus	avtobusnı	N;ACC
büst	büstniñ	N;GEN
kiriş	kirişniñ	N;GEN
şura	şurada	N;LOC
süyek	süyekten	N;ABL
uyalmaq	uyal	V;IMP;SG;2
kiosk	kioskta	N;LOC
minder	minderde	N;LOC
arnavut	arnavutnı	ADJ;ACC
qıçıruv	qıçıruvnıñ	N;GEN
sirke	sirkeni	N;ACC
boğday	boğdayda	N;LOC
reabilitatsiya	reabilitatsiyanı	N;ACC
şok	şoknıñ	N;GEN
elevator	elevatornı	N;ACC
molla	molladan	N;ABL
riñg	riñgnı	N;ACC
evolütsiya	evolütsiyada	N;LOC
sığır	sığırdan	N;ABL
sviter	sviterde	N;LOC
fotograf	fotografnıñ	N;GEN
kombayn	kombayn	N;NOM
radioaktivlilik	radioaktivlilikni	N;ACC
gerdanlıq	gerdanlıq	N;NOM
anbar	anbardan	N;ABL
sol	solda	ADJ;LOC
qamır	qamırdan	N;ABL
düve	düveden	N;ABL
kombayn	kombaynnı	N;ACC
tüyreviş	tüyrevişte	N;LOC
çarşı	çarşı	N;NOM
bergi	bergige	N;DAT
reaktsioner	reaktsionerden	N;ABL
qar	qarğa	N;DAT
frazeologiya	frazeologiya	N;NOM
afta	aftağa	N;DAT
ball	ballnı	N;ACC
manövr	manövrden	N;ABL
kirpik	kirpikni	N;ACC
tazbaş	tazbaşta	N;LOC
agent	agentke	N;DAT
azbar	azbardan	N;ABL
qampa	qampa	N;NOM
altın	altınğa	N;DAT
cürmek	cürmek	V;NFIN
belâ	belâğa	N;DAT
icviyci	icviycige	N;DAT
laborant	laborantta	N;LOC
reket	reketten	N;ABL
konstitutsiya	konstitutsiyada	N;LOC
fenomen	fenomenni	N;ACC
eşelon	eşelonnı	N;ACC
avur	avurda	ADJ;LOC
baza	baza	N;NOM
segregatsiya	segregatsiyadan	N;ABL
para	parada	N;LOC
avgustos	avgustosnıñ	N;GEN
raps	rapsqa	N;DAT
balerina	balerinağa	N;DAT
serbestlik	serbestlikke	N;DAT
revmatizm	revmatizm	N;NOM
kreditor	kreditorğa	N;DAT
emblema	emblemadan	N;ABL
ıslamaq	ıslamaq	V;NFIN
ekologiya	ekologiyadan	N;ABL
şey	şeyge	N;DAT
ayvanat	ayvanatnı	N;ACC
vatan	vatanğa	N;DAT
savanna	savanna	N;NOM
registr	registr	N;NOM
bürçe	bürçede	N;LOC
reket	reketni	N;ACC
domuz	domuzdan	N;ABL
tolu	tolunıñ	ADJ;GEN
komandan	komandanğa	N;DAT
kommuna	kommunağa	N;DAT
millimetr	millimetr	N;NOM
federatsiya	federatsiyağa	N;DAT
fizika	fizika	N;NOM
estrada	estradağa	N;DAT
kvitantsiya	kvitantsiyadan	N;ABL
funktsiya	funktsiyadan	N;ABL
bolmaq	bola	V;SG;3;PRS
kadâ	kadâdan	N;ABL
agressiya	agressiyadan	N;ABL
ağlamaq	ağlay	V;SG;3;PRS
çempion	çempionnıñ	N;GEN
segment	segmentte	N;LOC
bavur	bavur	N;NOM
avans	avansnıñ	N;GEN
laureat	laureatqa	N;DAT
komandan	komandannı	N;ACC
fransız	fransıznıñ	N;GEN
bala-çağa	bala-çağanı	N;ACC
bürşe	bürşeniñ	N;GEN
domalan	domalannı	N;ACC
mobilizatsiya	mobilizatsiyadan	N;ABL
kurs	kursta	N;LOC
start	startta	N;LOC
korrespondentsiya	korrespondentsiyanıñ	N;GEN
tırtır	tırtırda	N;LOC
federatsiya	federatsiyanıñ	N;GEN
regata	regata	N;NOM
mevsim	mevsimniñ	N;GEN
cel	celde	N;LOC
reformator	reformatorda	ADJ;LOC
bufet	bufetke	N;DAT
ataman	atamanda	N;LOC
qamır	qamır	N;NOM
komandan	komandanda	N;LOC
ekipaj	ekipajnı	N;ACC
eksport	eksport	N;NOM
kombinat	kombinatnı	N;ACC
apay	apaynıñ	N;GEN
paket	paket	N;NOM
kooperatsiya	kooperatsiyada	N;LOC
kolonna	kolonnadan	N;ABL
kupüra	kupüra	N;NOM
defter	defterden	N;ABL
fırçı	fırçınıñ	N;GEN
kreyser	kreyserniñ	N;GEN
qaarli	qaarlini	ADJ;ACC
kinofestival	kinofestivalde	N;LOC
vodoprovod	vodoprovod	N;NOM
qıraliçe	qıraliçege	N;DAT
capma	capma	N;NOM
zeer	zeerden	N;ABL
bolmaq	boldı	V;SG;3;PST
hulya	hulyanı	N;ACC
namzet	namzetten	N;ABL
qonaq	qonaqtan	N;ABL
şökiş	şökişniñ	N;GEN
leopard	leopard	N;NOM
ekvator	ekvatorğa	N;DAT
ana	anağa	N;DAT
qazah	qazahnı	N;ACC
yamav	yamavğa	N;DAT
sekundomer	sekundomerniñ	N;GEN
referendum	referendumğa	N;DAT
qıcıtqan	qıcıtqannıñ	N;GEN
reportaj	reportajda	N;LOC
angiş	angişten	N;ABL
filatelist	filatelistke	N;DAT
agent	agent	N;NOM
şey	şeyniñ	N;GEN
kafe	kafege	N;DAT
agressiya	agressiyada	N;LOC
arslan	arslan	N;NOM
egeşmek	egeşe	V;SG;3;PRS
paalı	paalığa	ADJ;DAT
arqan	arqandan	N;ABL
cinayet	cinayetke	N;DAT
cabışmaq	cabışa	V;SG;3;PRS
ırmaq	ırmaq	N;NOM
mayasıl	mayasılnıñ	N;GEN
qolbez	qolbezniñ	N;GEN
zeytün	zeytün	N;NOM
emce	emceniñ	N;GEN
montör	montörnı	N;ACC
ekipaj	ekipaj	N;NOM
faner	fanerniñ	N;GEN
rapira	rapiranıñ	N;GEN
cedvel	cedvelden	N;ABL
karton	kartonnı	N;ACC
qarğa	qarğağa	N;DAT
mimika	mimikadan	N;ABL
qamır	qamırda	N;LOC
imza	imzanıñ	N;GEN
resurs	resurs	N;NOM
konstruktor	konstruktordan	N;ABL
getralar	getralardan	N;ABL
kümüş	kümüşke	N;DAT
ravvin	ravvinden	N;ABL
matematik	matematikte	ADJ;LOC
saharin	saharinniñ	N;GEN
qaar	qaarniñ	N;GEN
maskarad	maskaradnı	N;ACC
ekstremizm	ekstremizmniñ	N;GEN
kompensatsiya	kompensatsiyanıñ	N;GEN
fırçı	fırçını	N;ACC
tamir	tamirğa	N;DAT
eroziya	eroziyadan	N;ABL
çorap	çorapta	N;LOC
aydayıcı	aydayıcığa	N;DAT
missiya	missiyağa	N;DAT
kombinatsiya	kombinatsiyada	N;LOC
filcan	filcandan	N;ABL
sentâbr	sentâbrge	N;DAT
kriteriy	kriteriyniñ	N;GEN
roman	romanda	N;LOC
oymaq	oymaqnı	N;ACC
tilşınaslıq	tilşınaslıqnı	N;ACC
caş	caşta	ADJ;LOC
çipçe	çipçede	N;LOC
tükân	tükândan	N;ABL
çarşı	çarşıda	N;LOC
şipşe	şipşeniñ	N;GEN
gamma	gammağa	N;DAT
cez	cezden	N;ABL
degirmen	degirmenniñ	N;GEN
abajur	abajurda	N;LOC
sapfir	sapfirni	N;ACC
yağmur	yağmurnıñ	N;GEN
futbol	futbolda	N;LOC
fleyta	fleytanı	N;ACC
manikür	manikürni	N;ACC
buz	buz	N;NOM
mutlaqiyet	mutlaqiyetke	N;DAT
trampete	trampeteden	N;ABL
resurs	resursnıñ	N;GEN
kloun	klounnı	N;ACC
fakultet	fakultette	N;LOC
ağaş	ağaşqa	N;DAT
qıyış	qıyışta	ADJ;LOC
makulatura	makulaturanı	N;ACC
kabinet	kabinetke	N;DAT
qadaq	qadaqnı	N;ACC
boynuz	boynuznı	N;ACC
kassa	kassa	N;NOM
el	elniñ	N;GEN
manövr	manövrde	N;LOC
bödene	bödenege	N;DAT
trampete	trampeteni	N;ACC
kinostudiya	kinostudiyada	N;LOC
karp	karpqa	N;DAT
rezervuar	rezervuarğa	N;DAT
fauna	faunadan	N;ABL
ferik	ferikniñ	N;GEN
çömüç	çömüçniñ	N;GEN
kurator	kuratornı	N;ACC
mevsim	mevsimni	N;ACC
yel	yel	N;NOM
qap	qaptan	N;ABL
aborigen	aborigenni	N;ACC
ğağa	ğağanıñ	N;GEN
kafe	kafeni	N;ACC
testimal	testimaldan	N;ABL
epopeya	epopeya	N;NOM
kontrolör	kontrolörda	N;LOC
baqa	baqanı	N;ACC
bücet	bücetniñ	N;GEN
balıq	balıqqa	N;DAT
ranets	ranetste	N;LOC
menü	menüden	N;ABL
rekord	rekordnı	N;ACC
calanğaş	calanğaştan	ADJ;ABL
şortı	şortıda	N;LOC
saylamaq	sayla	V;IMP;SG;2
reformatsiya	reformatsiyada	N;LOC
rezidentsiya	rezidentsiyadan	N;ABL
kommunist	kommunistke	ADJ;DAT
lider	liderni	N;ACC
qırğınlıq	qırğınlıqqa	N;DAT
adım	adımdan	N;ABL
vazife	vazife	N;NOM
qazaq	qazaqnıñ	N;GEN
çibin	çibinden	N;ABL
qapı	qapı	N;NOM
qaynana	qaynanağa	N;DAT
sebep	sebepten	N;ABL
büro	büronı	N;ACC
parça	parça	N;NOM
tize	tizeniñ	N;GEN
küneş	küneşte	N;LOC
molla	molla	N;NOM
kooperativ	kooperativde	ADJ;LOC
feodalizm	feodalizmnıñ	N;GEN
tüyreviş	tüyreviş	N;NOM
qaynata	qaynatanı	N;ACC
pul	pulnıñ	N;GEN
ögey baba	ögey babanıñ	N;GEN
tañ	tañğa	N;DAT
aruv bolmaq	aruv bola	V;SG;3;PRS
abbat	abbatta	N;LOC
oktâbr	oktâbr	N;NOM
massiv	massivniñ	N;GEN
narat	naratta	N;LOC
dım	dım	N;NOM
kürek	kürekni	N;ACC
marinad	marinaddan	N;ABL
gerdanlıq	gerdanlıqqa	N;DAT
monolog	monolognıñ	N;GEN
şive	şivege	N;DAT
final	final	N;NOM
sazan	sazan	N;NOM
lava	lavadan	N;ABL
bik	bikniñ	N;GEN
an	anni	N;ACC
alşaymaq	alşaya	V;SG;3;PRS
reportör	reportör	N;NOM
sekta	sektadan	N;ABL
qave	qaveni	N;ACC
reabilitatsiya	reabilitatsiyağa	N;DAT
konstatatsiya	konstatatsiyağa	N;DAT
qırmısqa	qırmısqanıñ	N;GEN
süyek	süyek	N;NOM
lava	lavada	N;LOC
muqayt olmaq	muqayt ol	V;IMP;SG;2
boğaz	boğazğa	N;DAT
yipek	yipek	N;NOM
havyar	havyarnıñ	N;GEN
ekşimek	ekşimek	V;NFIN
yemiş	yemiş	N;NOM
konferentsiya	konferentsiya	N;NOM
dara	dara	N;NOM
bint	bintke	N;DAT
şerenga	şerengadan	N;ABL
oluq	oluqnı	N;ACC
kreditor	kreditorda	N;LOC
epitsentr	epitsentrden	N;ABL
kategoriya	kategoriyadan	N;ABL
furtuna	furtunanıñ	N;GEN
repetitor	repetitornıñ	N;GEN
kontakt	kontaktta	ADJ;LOC
narat	narattan	N;ABL
tüyreviş	tüyrevişke	N;DAT
alaşa	alaşanı	N;ACC
linza	linzanıñ	N;GEN
kater	katerge	N;DAT
qoñuz	qoñuzğa	N;DAT
ada	adada	N;LOC
dondurma	dondurmanı	N;ACC
balıqçı	balıqçını	N;ACC
kupüra	kupüranıñ	N;GEN
kitabe	kitabeni	N;ACC
kontrol	kontrolde	N;LOC
ekspress	ekspresste	N;LOC
flüger	flügerge	N;DAT
frenk	frenkke	N;DAT
emçek	emçekke	N;DAT
anbar	anbar	N;NOM
qalav	qalavnı	N;ACC
sentâbr	sentâbrniñ	N;GEN
talil	talilniñ	N;GEN
toplaşuv	toplaşuvdan	N;ABL
format	formattan	N;ABL
yımırta	yımırtanıñ	N;GEN
sadizm	sadizmge	N;DAT
cıqmaq	cıqdı	V;SG;3;PST
senek	senek	N;NOM
gerdanlıq	gerdanlıqnı	N;ACC
çipçe	çipçege	N;DAT
kombinat	kombinat	N;NOM
kategoriya	kategoriyada	N;LOC
bayğuş	bayğuş	ADJ;NOM
monolog	monolognı	N;ACC
balet	baletniñ	N;GEN
alaşa	alaşanıñ	N;GEN
kinoteatr	kinoteatr	N;NOM
şinel	şinelge	N;DAT
labirint	labirintten	N;ABL
brilliant	brilliantqa	N;DAT
arış	arıştan	N;ABL
rekonstruktsiya	rekonstruktsiyanı	N;ACC
tayare	tayareniñ	N;GEN
kafe	kafeden	N;ABL
fener	fenerniñ	N;GEN
defter	defterge	N;DAT
ev	evde	N;LOC
yapraq	yapraqnı	N;ACC
radiola	radiolanıñ	N;GEN
aqça	aqçadan	N;ABL
ekipaj	ekipajda	N;LOC
süngü	süngüni	N;ACC
coğrafiya	coğrafiyadan	N;ABL
bulğar	bulğarda	ADJ;LOC
bavını tapmaq	bavını tapmaq	V;NFIN
maqtav	maqtavğa	N;DAT
çıplaq	çıplaqnıñ	N;GEN
qamus	qamusta	N;LOC
sangvinik	sangvinikni	N;ACC
dirhem	dirhem	N;NOM
cuvurmaq	cuvur	V;IMP;SG;2
brilliant	brilliantnı	N;ACC
dirhem	dirhemniñ	N;GEN
cavmaq	cavmaq	V;NFIN
avlaq	avlaq	N;NOM
kapitalist	kapitalist	N;NOM
reformator	reformator	ADJ;NOM
yamav	yamav	N;NOM
taş	taştan	N;ABL
kontsert	kontsertten	N;ABL
kooperativ	kooperativniñ	ADJ;GEN
matç	matç	N;NOM
aqquş	aqquşnıñ	N;GEN
qabaqbaş	qabaqbaştan	N;ABL
sıyırcıq	sıyırcıqta	N;LOC
radikal	radikal	ADJ;NOM
fener	fenerge	N;DAT
tamir	tamirdan	N;ABL
elifbe	elifbede	N;LOC
saninstruktor	saninstruktorda	N;LOC
bağ	bağda	N;LOC
sarı turup	sarı turupta	N;LOC
öpmek	öpmek	V;NFIN
saylıq	saylıqnıñ	N;GEN
keşe	keşe	N;NOM
duvadaq	duvadaq	N;NOM
retsenziya	retsenziyağa	N;DAT
minder	minderniñ	N;GEN
kadr	kadrnıñ	N;GEN
radiola	radiolada	N;LOC
bata	batanıñ	N;GEN
abort	abortqa	N;DAT
küzgü	küzgüge	N;DAT
semantika	semantikadan	N;ABL
koridor	koridorda	N;LOC
cara	caradan	N;ABL
miy	miyde	N;LOC
landşaft	landşaft	N;NOM
canmaq	can	V;IMP;SG;2
rentgenoskopiya	rentgenoskopiyada	N;LOC
feodalizm	feodalizmğa	N;DAT
yunan	yunannı	N;ACC
bilyard	bilyardnıñ	N;GEN
qartana	qartanada	N;LOC
şeker	şekerniñ	N;GEN
firma	firmağa	N;DAT
saylamaq	sayladı	V;SG;3;PST
bavur	bavurğa	N;DAT
maden	maden	N;NOM
camav	camavnı	N;ACC
regata	regatanı	N;ACC
abrakadabra	abrakadabradan	N;ABL
derebeylik	derebeylikte	N;LOC
temir	temirde	N;LOC
qırmısqa	qırmısqadan	N;ABL
kayuta	kayutanı	N;ACC
reflektor	reflektorda	N;LOC
çek	çekten	N;ABL
cırtmaq	cırta	V;SG;3;PRS
şlüz	şlüzni	N;ACC
mikrob	mikrobğa	N;DAT
dam	damdan	N;ABL
bağır	bağırnı	N;ACC
estoniyalı	estoniyalınıñ	N;GEN
dekabr	dekabrden	N;ABL
leopard	leopardğa	N;DAT
tilşınas	tilşınasta	N;LOC
avtoqalem	avtoqalemde	N;LOC
mata	matağa	N;DAT
retsenziya	retsenziya	N;NOM
Zual	Zualge	N;DAT
süngü	süngü	N;NOM
regbi	regbige	N;DAT
menü	menüni	N;ACC
balet	balette	N;LOC
qaynata	qaynatada	N;LOC
rezeda	rezedada	N;LOC
madde	maddeye	N;DAT
qudanay	qudanayğa	N;DAT
ayaqqap	ayaqqapqa	N;DAT
buzdağ	buzdağta	N;LOC
