i-k-ikwą	nkw-i-k-ikwą	V;PFV
s-uwi¹	nte-suwi¹	V;PROG
u-ka¹ti²	nka-ka¹ti²	V;PFV
u-la¹ti²ʔ	nt-u-la¹ti²ʔ	V;HAB
ta²kwi	nte¹-ta²kwi	V;PROG
xiti	ki-xiti	V;POT
u¹-ke²ʔ	nch-u¹-ke²ʔ	V;PROG
wi¹ʔi²	nti-wi¹ʔi²	V;HAB
ta¹a²ʔ	nku-ta¹a²ʔ	V;PFV
a¹su²ʔ	nti¹-su²ʔ	V;HAB
i-ty-ala¹	nkw-i-ty-ala¹	V;PFV
y-atą	ch-atą	V;POT
lu²u¹	ki-luu	V;POT
tza²	nku-tza²	V;PFV
ka²ʔne¹	nte-ka²ʔne¹	V;PROG
i¹-hni²	k-i¹-hni²	V;POT
tuuʔ	nka-tuuʔ	V;PFV
hu²ʔu¹	nka-hu²ʔu¹	V;PFV
u¹-hni²	hni²	V;POT
u-sa¹na²	k-u-sana¹	V;POT
katzǫ¹	nte-katzǫ¹	V;PROG
u-tita¹	k-u-tita¹	V;POT
u-s-a¹a²ʔ	k-u-s-aa¹ʔ	V;POT
u-te²e¹ʔ	nte-te²e¹ʔ	V;PROG
witi	nti-witi	V;HAB
tyehna¹	n-tyehna¹	V;HAB
yaʔne	nte-chaʔne	V;PROG
y-a¹lu²	nte-y-a¹lu²	V;PROG
u²ti¹	k-uti	V;POT
u-tzu	nte²-tzu¹	V;PROG
y-u²kwa¹ʔ	nk-y-u²kwa¹ʔ	V;PFV
u-kaʔa	k-u-kaʔa	V;POT
ta¹a²	n-ta¹a²	V;HAB
li²hi¹	nku-li²hi¹	V;PFV
u²ti¹	nka-y-u²ti¹	V;PFV
i-lyu²u¹	nt-i-lyuu	V;HAB
oʔǫ¹	nka-y-oʔǫ¹	V;PFV
tz-u¹kų²ʔ	nkwi-tz-u¹kų²ʔ	V;PFV
i¹ʔya²	nte-k-iʔya¹	V;PROG
nee	nti-nii	V;HAB
yu¹kwą²	nk-yu¹kwą²	V;PFV
ala¹	nti¹-la²	V;HAB
u¹ra²	nte¹-ra²	V;PROG
nyą¹ʔ	nte-nyą¹ʔ	V;PROG
tza²	nte¹-tza²	V;PROG
u-sa¹na²	nt-u-sana¹	V;HAB
oʔǫ¹	k-o¹ʔǫ²	V;POT
la²kwi	nti¹-la²kwi	V;HAB
u-lakwa¹	nte-lakwa¹	V;PROG
sǫ²	nti¹-sǫ²	V;HAB
ka²ʔne¹	nku-ka²ʔne¹	V;PFV
tiyaą	n-tiyaą	V;HAB
yakwa	nte-chakwa	V;PROG
y-aha¹	n-ch-aha¹	V;HAB
i-ki¹-hnya²	nte-ki¹-hnya²	V;PROG
y-u¹kwa²	ch-u¹kwa²	V;POT
i²chaa¹	k-ichaa	V;POT
u-suʔu¹	nte-suʔu¹	V;PROG
i-ly-a²su	nt-i-ly-asu	V;HAB
u-ki¹į²	k-u-ki¹į²	V;POT
lala¹	nte-lala¹	V;PROG
i-lyu²u¹	k-i-lyuu	V;POT
ukwą¹	nt-ukwą¹	V;HAB
u-tikwę	k-u-tikwę	V;POT
i-ni¹i²	k-i-ni¹i²	V;POT
yaʔne	ch–aʔne	V;POT
lyaʔa¹	nka-lyaʔa¹	V;PFV
u-lukwa¹	nte-lukwa¹	V;PROG
y-atzu	nk-y-atzu	V;PFV
li²nto¹	ki-linto	V;POT
i-k-isu	k-i-kisu	V;POT
yatę¹	nte-chatę¹	V;PROG
y-aką¹ʔ	ch-aką¹ʔ	V;POT
u²ne¹	y-u²ne¹	V;PFV
yu¹kwą²	n-chu¹kwą²	V;HAB
wini	ki-wini	V;POT
u¹-hlya²	nte¹-hlya²	V;PROG
kalaʔ	ki-kalaʔ	V;POT
u-hnya¹ʔ	nka-hnya¹ʔ	V;PFV
lala¹	nku-lala¹	V;PFV
u-ni¹tza²ʔ	nt-u-ni¹tza²ʔ	V;HAB
sesu	nka-sesu	V;PFV
u-nakǫʔ	k-u-nakǫʔ	V;POT
tu²ʔu	tyu²ʔu	V;POT
ala¹	nch-ala¹	V;PROG
i¹-ty-e²ʔe	nt-i¹-ty-e²ʔe	V;HAB
ka¹ʔa²	nku-ka¹ʔa²	V;PFV
u-l-a²su¹	nka-l-a²su¹	V;PFV
aʔna¹	nch-aʔna¹	V;PROG
yata	nk-yata	V;PFV
u-s-atiʔ	nte-s-atiʔ	V;PROG
sana¹	ki-sana¹	V;POT
u-ʔne	nt-u-ʔne	V;HAB
lya	ki-lya	V;POT
a¹lu²	nti¹-lu²	V;HAB
itzu	nkw-itzu¹	V;PFV
u-loʔo	nte-loʔo	V;PROG
wi¹ʔi²	ki-wi¹ʔi²	V;POT
tza²	ki¹-tza²	V;POT
u-tikąʔ	nte-tikąʔ	V;PROG
u-xu¹ʔu²	nte-xu¹ʔu²	V;PROG
u-ti¹te²	nte-ti¹te²	V;PROG
yu¹kwą²	nte-yu¹kwą²	V;PROG
ya¹a²	n-cha¹a²	V;HAB
u-s-atę¹	nt-u-s-atę¹	V;HAB
u¹-li¹hi²	nka¹-li¹hi²	V;PFV
saʔą	nku-saʔą	V;PFV
su¹	nku-su¹	V;PFV
eʔe	k-eʔe	V;POT
na¹ʔa²	nku-na¹ʔa²	V;PFV
u-ka¹ta²	nka-ka¹ta²	V;PFV
hiʔį¹	nti-hiʔį¹	V;HAB
hya¹	nte-hya¹	V;PROG
u-ko¹ʔo²	nte-ko¹ʔo²	V;PROG
witi	ki-witi	V;POT
u¹-tu²kwi	nka¹-tu²kwi	V;PFV
suuʔ	nka-suuʔ	V;PFV
hu²ʔu¹	nte-hu²ʔu¹	V;PROG
i-ch-ukwą¹	k-i-ch-ukwą¹	V;POT
u-suʔu¹	nt-u-suʔu¹	V;HAB
y-asu	ch-asu	V;POT
u-tzu	k-u-tzu	V;POT
u-ke¹la²	nte-ke¹la²	V;PROG
su¹	nti-su	V;HAB
ʔni	ki-ʔni	V;POT
te¹tza²	ki-te¹tza²	V;POT
u¹-so²ʔ	nka¹-so²ʔ	V;PFV
y-u¹kwa²	nk-y-u¹kwa²	V;PFV
u-ne¹ʔe²	nka¹-ne¹ʔe²	V;PFV
u-tu¹su²ʔ	n-tusu¹ʔ	V;HAB
y-asu	nk-y-asu	V;PFV
u-la¹ʔa²	nka-la¹ʔa²	V;PFV
yakwa	n-chakwa	V;HAB
u-sa¹na²	nte-sa¹na²	V;PROG
ichi¹	nti-k-ichi¹	V;PROG
tihi	ki-tihi	V;POT
u-ti¹kų²	k-u-ti¹kų²	V;POT
yaą	nk-yaą	V;PFV
u-kachi¹ʔ	k-u-kachi¹ʔ	V;POT
i¹-s-a²ta	k-i¹-s-a²ta	V;POT
tza¹ʔą²	nte-tza¹ʔą²	V;PROG
u-t-u¹ʔu²	nt-u-t-u¹ʔu²	V;HAB
i-ty-alaʔ	k-i-ty-alaʔ	V;POT
s-uwi¹	ki-suwi¹	V;POT
i-lyatza	nkw-i-lyatza	V;PFV
atiʔ	k-atiʔ	V;POT
li²tiʔ	nti¹-li²tiʔ	V;HAB
u-xu¹ʔu²	nt-u-xu¹ʔu²	V;HAB
hnii	nti-hnii	V;HAB
xę²	nku-xę²	V;PFV
u¹la²	y-u¹la²	V;PFV
u-ke¹la²	k-u-ke¹la²	V;POT
y-a²na¹	ch–ana	V;POT
toǫ	nku-toǫ	V;PFV
ya²ʔą	n-cha²ʔą	V;HAB
aa	nch-aa	V;PROG
i-ni¹ʔi²	nkw-i-ni¹ʔi²	V;PFV
oo¹	nch-oo¹	V;PROG
se²su	nte¹-se²su	V;PROG
u-ki¹į²	nt-u-ki¹į²	V;HAB
i²kwą¹	nt-ikwą	V;HAB
kalaʔ	nti-kalaʔ	V;HAB
u-hwi	k-u-hwi	V;POT
a¹tzu²ʔ	nti¹-tzu²ʔ	V;HAB
tu²ʔu	nku-tu²ʔu	V;PFV
tu¹kwa²	nte-tu¹kwa²	V;PROG
tee¹	nku-tee¹	V;PFV
katzǫ¹	ki-katzǫ¹	V;POT
u¹-x-i²ti	nt-u¹-x-i²ti	V;HAB
ya¹a²	ch–a¹a²	V;POT
ti¹te²	nti-ti¹te²	V;HAB
ki¹į²	ki-ki¹į²	V;POT
y-asu	n-ch-asu	V;HAB
y-atzu	ch-atzu	V;POT
ya¹ʔne²	nk-ya¹ʔne²	V;PFV
ta¹a²	nte-ta¹a²	V;PROG
u-la¹ha²	k-u-la¹ha²	V;POT
y-uwi	nte-ch-uwi	V;PROG
y-a²ta	nk-y-a²ta	V;PFV
la¹la²	nte-la¹la²	V;PROG
u-ko¹ʔo²	nka-ko¹ʔo²	V;PFV
a¹lu²	k-a¹lu²	V;POT
ala¹	nku-la¹	V;PFV
xę	nku-xę	V;PFV
u-laʔa	nte-laʔa	V;PROG
nyą¹ʔ	ki-nyą¹ʔ	V;POT
atzu	k-atzu	V;POT
i-lyu²u¹	nkw-i-lyu²u¹	V;PFV
eta	nkw-eta	V;PFV
ya²ʔą¹	nte-chaʔą	V;PROG
y-a¹ʔwe²	nte-y-a¹ʔwe²	V;PROG
t-a²ha¹	nku-t-a²ha¹	V;PFV
hnii	nte-hnii	V;PROG
tu²ʔya	n-tyu²ʔya	V;HAB
lakwi	nte-lakwi	V;PROG
u¹-tu²we	nte¹-tu²we	V;PROG
i-s-uwi¹ʔ	nte-s-uwi¹ʔ	V;PROG
ata	y-ata	V;PFV
i-tyotza	nti-tyotza	V;HAB
i-s-e¹lu²	nkw-i-s-e¹lu²	V;PFV
sana¹	nti-sana¹	V;HAB
ti¹kų²	nte-ti¹kų²	V;PROG
t-uʔu	nte-t-uʔu	V;PROG
u-s-a¹ʔwe²	nt-u-s-a¹ʔwe²	V;HAB
u-ti¹kų²	nkwi-ti¹kų²	V;PFV
kehę	ki-kehę	V;POT
u¹-ke²ʔ	nkay-u¹-ke²ʔ	V;PFV
tita	nte-tita	V;PROG
y-ukwą	ch–ukwą	V;POT
nee	nte-nee	V;PROG
u-t-a²ha¹	nt-u-t-aha	V;HAB
u-ko¹ʔo²	nt-u-ko¹ʔo²	V;HAB
u-t-ano	nka-t-ano	V;PFV
anaʔ	nti-naʔ	V;HAB
u-s-u²kwa¹ʔ	nte-s-u²kwa¹ʔ	V;PROG
u-l-a²su¹	nte-l-a²su¹	V;PROG
u-kaʔa	nt-u-kaʔa	V;HAB
tza¹ʔą²	nti-tza¹ʔą²	V;HAB
y-a¹la²	ch-ala¹	V;POT
hu²ų¹	nte-hu²ų¹	V;PROG
ichi¹	nt-ichi¹	V;HAB
y-atiʔ	ch-atiʔ	V;POT
i-tyunu	nte-tyunu	V;PROG
u-ni¹tza²ʔ	nka-ni¹tza²ʔ	V;PFV
u-na¹kwą²	nt-u-nakwą¹	V;HAB
u-hwi	nt-u-hwi	V;HAB
naa	ki-naa	V;POT
yakwa¹	nte-chakwa¹	V;PROG
u¹-ke²ʔ	k-u-ke¹ʔ	V;POT
i-s-uweʔ	nkw-i-s-uweʔ	V;PFV
nyaxęʔ	nti-nyaxęʔ	V;HAB
i-xi¹-ką²ʔ	nkw-i-xi¹-ką²ʔ	V;PFV
hnaʔ	ki-hnaʔ	V;POT
nyaxęʔ	nte-nyaxęʔ	V;PROG
yaa	n-chaa	V;HAB
u-sa¹ʔą²	nt-u-sa¹ʔą²	V;HAB
nakwą¹	nku-nakwą¹	V;PFV
u¹-kų²	nka¹-kų²	V;PFV
y-akę¹	nte-y-akę¹	V;PROG
ala	nku-la	V;PFV
u-tisa¹ʔ	k-u-tisa¹ʔ	V;POT
u-li¹ti²ʔ	nka-li¹ti²ʔ	V;PFV
kili	nti-kili	V;HAB
ukwęʔ	nch-ukwęʔ	V;PROG
u¹-hna²ʔ	nt-u¹-hna²ʔ	V;HAB
hlya¹	nti-hlya¹	V;HAB
i-lyaa	k-i-lyaa	V;POT
na¹a²	nti-na¹a²	V;HAB
u²ti¹	nch-u²ti¹	V;PROG
u-la¹ti²ʔ	nka-la¹ti²ʔ	V;PFV
i-s-uwi¹ʔ	nt-i-s-uwi¹ʔ	V;HAB
lu²u¹	nku-lu²u¹	V;PFV
i-katzǫ¹	nkw-i-katzǫ¹	V;PFV
isę	nkw-isę	V;PFV
i-tyunu	nkw-i-tyunu	V;PFV
i-lyatza	nt-i-lyatza	V;HAB
sę²	nti¹-sę²	V;HAB
u-so¹sa²	nte-so¹sa²	V;PROG
ku¹na²ʔ	ki-ku¹na²ʔ	V;POT
ti¹kų²	nti-ti¹kų²	V;HAB
i-s-e¹lu²	nt-i-s-e¹lu²	V;HAB
lya	nti-lya	V;HAB
ka¹ta²	nku-ka¹ta²	V;PFV
i-lyo¹o²	nte-lyo¹o²	V;PROG
y-atą	nk-y-atą	V;PFV
lya	nte-lya	V;PROG
u¹ra²	nt-u¹ra²	V;HAB
u-katę¹	nt-u-katę¹	V;HAB
u¹-na²na	nte¹-na²na	V;PROG
i-tyaʔą	nte-tyaʔą	V;PROG
ahi¹	nti¹-hi²	V;HAB
u-tihi	k-u-tihi	V;POT
u-s-ene¹	nt-u-s-ene¹	V;HAB
i-k-isu	nt-i-kisu	V;HAB
kachi¹ʔ	nte-kachi¹ʔ	V;PROG
u¹-ba²ʔa¹	nt-u-baʔa	V;HAB
u¹-li²nto	nt-u¹-li²nto	V;HAB
su¹	ki-su	V;POT
u-hnya¹	nte-hnya¹	V;PROG
u-tzaʔ	nt-u-tzaʔ	V;HAB
a¹ta²ʔ	y-a¹ta²ʔ	V;PFV
ta²su¹	tya²su¹	V;POT
tzoʔo	nte-tzoʔo	V;PROG
taʔą	nku-taʔą	V;PFV
u-t-a²ha¹	k-u-t-aha	V;POT
akwaʔ	nti-kwaʔ	V;HAB
i-lyatza	k-i-lyatza	V;POT
laha	nte-laha	V;PROG
u-xikwą	k-u-xikwą	V;POT
yee	nte-k-yee¹	V;PROG
u-s-uweʔ	nka-s-uweʔ	V;PFV
ka¹ta²	nti-kata¹	V;HAB
y-a²ha¹	ch-aha	V;POT
tya²na	nkwi¹-tya²na	V;PFV
u-xi¹-ką²ʔ	nt-u-xi-ką¹ʔ	V;HAB
hnaʔ	nka-hnaʔ	V;PFV
hiʔį¹	nku-hiʔį¹	V;PFV
u-kachi¹ʔ	nte-kachi¹ʔ	V;PROG
hlya¹	ki-hlya¹	V;POT
u-xiką	nka-xiką	V;PFV
s-uwi¹	nka-suwi¹	V;PFV
i-ni¹i²	nt-i-ni¹i²	V;HAB
sukwa¹	nte-sukwa¹	V;PROG
ya¹chi²ʔ	nk-ya¹chi²ʔ	V;PFV
y-u¹kų²ʔ	nk-y-u¹kų²ʔ	V;PFV
