dagiː	dagiːf	ADJ;PSS1S
ukunmiː	ukunmiːwə	N;ACC;DEF;SG
kərgə	kərgəhəlin	N;NOM;PL;PSS3S
beːγaltan	beːγaltan	ADJ
ə	ət͡ʃəsun	V;IPFV;FIN;IND;PL;2;ACT
hokori	hokoriwundə	V;FIN;IND;SG;2;PST;PASS
amaːkaː	amaːkaːf	N;NOM;SG;PSS1S
ʃamanitkaːn	ʃamanitkaːn	N;NOM;SG
haːrgi	haːrgil	N;NOM;PL
ə	ətəːn	V;FIN;IND;SG;3;FUT+IMMED;ACT
bega	begaja	N;ACC;INDF;SG
gərbiːśiː	gərbiːśiːduː	ADJ;DAT
dantaki	dantakilwə	N;ACC;DEF;PL
aγata	aγataduk	N;ABL;SG
amar	amaritpi	N;INS;SG;PSSRS
kaʃuna	kaʃunarə	V;FIN;IND;PL;3;PST;ACT
uśit	uśitt͡ʃaːn	V;FIN;IND;SG;3;PST;ACT
urə	urəlduː	N;DAT;PL
doːldiː	doːldiːt͡ʃaw	V;FIN;IND;SG;1;PST;ACT
əkspeditsiji	əkspeditsijil	N;NOM;PL
guːɲ	guːɲďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
aːnŋət	aːnŋətt͡ʃəːw	V;FIN;IND;PL;1+EXCL;PST;ACT
noː	noːkəllu	V;FIN;IMP;PL;2;ACT
guďeːj	guďeːj	ADJ
śəwərnaj	śəwərnajduloː	N;TERM;SG
inŋəktəśi	inŋəktəśi	ADJ
ďəp	ďəpďəŋnərə	V;HAB+IPFV;FIN;IND;PL;3;PRS;ACT
lu	lulba	N;ACC;DEF;PL
kaltaka	kaltakan	N;NOM;SG;PSS3S
uďa	uďaliːtin	N;PROL;SG;PSS3P
uŋtuwun	uŋtuwunmi	N;SG;PSSRS+ACC
əmə	əməwďəŋoːw	V;FIN;IND;SG;1;FUT;ACT
ďəptilə	ďəptilətin	N;NOM;SG;PSS3P
hoktə	hoktət	N;INS;SG
bargidaː	bargidaːduk	N;ABL;SG
inoŋi	inoŋil	N;NOM;PL
umun	umundu	N;DAT;SG
əkśə	əkśəktəsoːtin	V;FIN;IND;PL;3;PST;ACT
duː	duːlaː	N;TERM;SG
hawal	hawalďiŋərəwun	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
ɲuŋi	ɲuŋin	ADJ;PSS3S
goro	gorowo	N;ACC;DEF;SG
ərdi	ərdin	ADJ;PSS3S
tuksa	tuksasta	V;SEMEL;FIN;IND;PL;3;PST;ACT
ďəlakiːwəl	ďəlakiːwəl	N;NOM;SG
peːreːm	peːreːm	ADJ
hukti	huktiwgəːt	V;FIN;IMP;PL;1+INCL;ACT
haː	haːm	V;FIN;IND;SG;1;PST;ACT
hutə	hutəi	N;SG;PSSRS+ACC
t͡ʃok	t͡ʃokt͡ʃaw	V;FIN;IND;SG;1;PST;ACT
hitəːn	hitəːnduloː	N;TERM;SG
muldiːka	muldiːkar	N;NOM;PL
ijo	ijon	N;NOM;SG
inŋəni	inŋənil	N;NOM;PL
hukti	huktiďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
putoran	putoranduː	N;DAT;SG
bi	biďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
homoːtiː	homoːtiː	N;NOM;SG
haː	haːt͡ʃaːw	V;FIN;IND;SG;1;PST;ACT
tuŋaɲama	tuŋaɲama	N;NOM;SG
ili	iliŋkiːwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
otojo	otojodəŋkiːn	V;IPFV;FIN;IND;SG;3;PRS;ACT
ulgut͡ʃəː	ulgut͡ʃəːmaːtt͡ʃəm	V;IPFV;FIN;IND;SG;1;PRS;ACT
duku	dukuďam	V;FIN;IND;SG;1;FUT+IMMED;ACT
əki	əkim	N;NOM;SG;PSS1S
hokto	hoktoliːm	N;PROL;SG;PSS1S
hilba	hilbaďandə	V;IPFV;FIN;IND;SG;2;ACT
doːldiː	doːldiːrən	V;FIN;IND;SG;3;PST;ACT
ďuː	ďuːlaːwər	N;TERM;SG;PSSRP
awa	awa	N;NOM;SG
əmkəŋoti	əmkəŋotiw	N;NOM;SG
irəksə	irəksəŋilbi	N;PL;PSSRS+ACC+ALN
umnə	umnət	N;INS;SG
inməruk	inməruktukpi	N;ABL;SG;PSSRS
doːldiː	doːldiːlləw	V;FIN;IND;PL;1+EXCL;PST;ACT
gurusmoːdə	gurusmoːdəlnun	V;COM;FIN;IND;PL;ACT
tikəɲiː	tikəɲiːl	ADJ;PL
doːɲťa	doːɲťaďaŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
adili	adililwə	N;ACC;DEF;PL
bagdama	bagdamalba	ADJ;ACC;DEF;PL
hawal	hawalďaŋnam	V;HAB+IPFV;FIN;IND;SG;1;PRS;ACT
ŋəli	ŋəlifśipt͡ʃu	ADJ
kalan	kalandu	N;DAT;SG
ulgut͡ʃoːn	ulgut͡ʃoːndim	V;FIN;IND;SG;1;FUT;ACT
nəkun	nəkunmi	N;NOM;SG;PSSRS
in	inďiśoːtin	V;IPFV;FIN;IND;PL;3;PST;ACT
papal	papal	N;NOM;SG
kahi	kahirgarə	V;FIN;IND;PST;ANTIP
tuksaː	tuksaːďaran	V;IPFV;FIN;IND;SG;3;PRS;ACT
adiːkuː	adiːkuːr	ADJ;PL
ŋənə	ŋənəďət͡ʃoːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
bi	bisoːtin	V;FIN;IND;PSS3P;PST;ACT
taptigin	taptigin	N;NOM;SG
tuliː	tuliːliː	N;PROL;SG
bimɲin	bimɲin	N;NOM;SG
swarśik	swarśiktuː	N;DAT;SG
ŋinakin	ŋinakinmi	N;NOM;SG;PSS1S
baďaːlə	baďaːlə	ADJ
dukto	duktonun	N;COM;SG
ga	gadan	V;FIN;IND;SG;3;PST;ACT
jənt͡ʃəmbu	jənt͡ʃəmbuliː	N;PROL;SG
uru	urujə	N;ACC;INDF;SG
huju	hujuwďəŋoːn	V;FIN;IND;SG;3;FUT;ACT
armije	armijelaː	N;TERM;SG
arnold	arnold	N;NOM;SG
birigadir	birigadir	N;NOM;SG
ti	ti	N;NOM;SG
toγo	toγoji	N;NOM;SG;PSSRS
bulta	bultaŋkiwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
əniːn	əniːndukpi	N;ABL;SG;PSSRS
bəjŋoː	bəjŋoːlďi	N;INS;PL
ila	ilara	V;FIN;IND;PL;3;PST;ACT
moːtiː	moːtiːlə	N;ACC;INDF;PL
əməgənə	əməgənən	N;NOM;SG;PSS3S
tikt͡ʃaki	tikt͡ʃakiwə	N;ACC;DEF;SG
baldi	baldidəsaːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
ilmakta	ilmaktawa	N;ACC;DEF;SG
hərəki	hərəkit͡ʃoːw	V;FIN;IND;SG;1;PST;ACT
əmə	əməŋnərəwun	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
ŋoːlə	ŋoːləpkoːśildə	V;DUR;FIN;IND;PL;3;PST;CAUS;ACT
kuŋaka	kuŋakarwi	N;NOM;PL;PSS1S
ďuwu	ďuwurəw	V;FIN;IND;PL;1+EXCL;PST;ACT
uliː	uliːďəŋoːn	V;FIN;IND;SG;3;FUT;ACT
uku	ukubďəγin	V;IPFV;FIN;IMP;SG;3;CAUS;ACT
kaŋki	kaŋkititin	ADJ;PSS3P
tətigə	tətigəjə	N;ACC;INDF;SG
hoːŋə	hoːŋəriktatin	N;NOM;SG;PSS3P
ŋaːlə	ŋaːləlďiji	N;INS;PL;PSSRS
aja	ajaduk	ADJ;ABL;SG
hulu	hulukukor	ADJ;PL
oldo	oldortikiwar	N;ALL;PL;PSSRP
ʃoːmnaː	ʃoːmnaːst͡ʃəːw	V;SEMEL;FIN;IND;SG;1;PST;ACT
lu	lujə	N;ACC;INDF;SG
it͡ʃə	it͡ʃəpkoːniŋkiːn	V;FIN;IND;SG;3;PST+RMT;CAUS;ACT
təpkə	təpkəlkokuttən	V;FIN;IND;SG;3;PST;ACT
trafim	trafim	N;NOM;SG
teːteː	teːteːlaː	N;TERM;SG
buru	buruŋnəm	V;HAB;FIN;IND;SG;1;PST;ACT
ulgur	ulgurwi	N;SG;PSSRS+ACC
tuksaːn	tuksaːnkəl	V;FIN;IMP;SG;2;ACT
aďili	aďililə	N;ACC;INDF;PL
ti	tittəw	V;FIN;IND;PL;1+EXCL;PST;ACT
kartiʃka	kartiʃkahiniːŋkiːtin	V;SEMEL;FIN;IND;PL;3;PST+RMT;ACT
ulgut͡ʃoːn	ulgut͡ʃoːnďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
pəktirəːwun	pəktirəːwunmər	N;NOM;SG;PSSRP
in	inďət͡ʃoːn	V;IPFV;FIN;IND;SG;3;PST;ACT
ekologit͡ʃeskaji	ekologit͡ʃeskajil	ADJ;PL
ŋənə	ŋənəďəďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
hərə	hərəlgəduː	N;DAT;SG
bargidaː	bargidaːwan	N;ACC;DEF;SG;PSS3S
in	induːi	N;DAT;SG;PSSRS
tas	tassuhinəw	V;SEMEL;FIN;IND;PL;1+EXCL;PST;ACT
t͡ʃanku	t͡ʃankulduː	N;DAT;PL
əŋəhiː	əŋəhiːngu	V;FIN;IND;SG;3;ACT
ďiktə	ďiktəlwə	N;ACC;DEF;PL
hokto	hoktoliːtin	N;PROL;SG;PSS3P
ʃuru	ʃururən	V;FIN;IND;SG;3;PST;ACT
o	oďam	V;FIN;IND;SG;1;PRS;ACT
benzin	benzinilwə	N;ACC;DEF;PL
waśilij	waśilij	N;NOM;SG
mukətə	mukətəlin	N;PROL;SG;PSS3S
di	diŋkiːwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
musaːn	musaːnəw	V;FIN;IND;PL;1+EXCL;PST;ACT
obligatsə	obligatsəwə	N;ACC;DEF;SG
it͡ʃənoː	it͡ʃənoːkəl	V;FIN;IMP;SG;2;ACT
umukta	umuktawa	N;ACC;DEF;SG
oldo	oldol	N;NOM;PL
lambaraː	lambaraːldirə	V;FIN;IND;PL;3;PST;ACT
adili	adililwa	N;ACC;DEF;PL
bu	budan	V;FIN;IND;SG;3;PST;ACT
nəptalə	nəptalə	ADJ
tara	tarawa	N;ACC;DEF;SG
ďa	ďalwi	N;NOM;PL;PSSRS
uːt͡ʃak	uːt͡ʃakpi	N;SG;PSSRS+ACC
it͡ʃə	it͡ʃətnoːm	V;DUR;FIN;IND;SG;1;PST;ACT
ut͡ʃaːmi	ut͡ʃaːmila	N;TERM;SG
hawalmɲiː	hawalmɲiːtin	N;NOM;SG;PSS3P
ŋəliwśipt͡ʃu	ŋəliwśipt͡ʃu	ADJ
təwu	təwula	N;ACC;INDF;PL
gunə	gunəlim	V;FIN;IND;SG;1;PST;ACT
pamiɲať	pamiɲať	N;NOM;SG
ŋoːlə	ŋoːləlim	V;FIN;IND;SG;1;PST;ACT
uldə	uldəjə	N;ACC;INDF;SG
ogdiŋo	ogdiŋo	ADJ
hanŋukta	hanŋuktaran	V;FIN;IND;SG;3;PST;ACT
ətəjə	ətəjətt͡ʃə	V;IPFV;FIN;IND;ACT
hawal	hawalďət͡ʃaːn	V;IPFV;FIN;IND;SG;3;PST;ACT
t͡ʃuɲa	t͡ʃuɲatkiː	N;ALL;SG
tuŋə	tuŋəwa	N;ACC;DEF;SG
huru	hurupďəŋoːw	V;FIN;IND;SG;1;FUT;ACT
tunŋaďat͡ʃi	tunŋaďat͡ʃiduː	ADJ;DAT
uːt͡ʃak	uːt͡ʃak	N;NOM;SG
bi	biďaŋkiːf	V;IPFV;FIN;IND;SG;1;PST+RMT;ACT
hawa	hawalaːi	N;TERM;SG;PSSRS
ɲəŋɲə	ɲəŋɲə	ADJ
oː	oːt͡ʃəːn	V;FIN;IND;SG;3;PST;ACT
śevərgidaː	śevərgidaːtkiː	N;ALL;SG
heːn	heːnman	N;ACC;DEF;SG;PSS3S
teːteː	teːteːtkiː	N;ALL;SG
ɲama	ɲamawa	N;ACC;DEF;SG
duli	dulilga	N;NOM;SG
dili	dilin	N;NOM;SG;PSS3S
butilka	butilkaduː	N;DAT;SG
əməgən	əməgən	N;NOM;SG
jəgor	jəgor	N;NOM;SG
samoloti	samolotit	N;INS;SG
nəːku	nəːku	N;NOM;SG
omolgiː	omolgiː	N;NOM;SG
awadiwal	awadiwal	ADJ
hulda	huldala	N;ACC;INDF;PL
həgdi	həgdiməmə	ADJ
buru	buruďəm	V;FIN;IND;SG;1;FUT+IMMED;ACT
mari	maril	N;NOM;PL
bi	biśoːtin	V;FIN;IND;SG;3;PST;ACT
haŋiː	haŋiːttan	V;DUR;FIN;IND;SG;3;PST;ACT
oː	oː	N;NOM;SG
ďupkun	ďupkuntikiː	N;ALL;SG
o	odam	V;FIN;IND;SG;1;PST;ACT
həgdi	həgdimomowətin	N;ACC;DEF;SG;PSS3P
grus	grus	N;NOM;SG
ďəw	ďəwďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
guluwun	guluwun	N;NOM;SG
kərgə	kərgəhəl	N;NOM;PL
bəjŋoː	bəjŋoːlbo	N;ACC;DEF;PL
uːt͡ʃak	uːt͡ʃaktuː	N;DAT;SG
darimaː	darimaːstan	V;SEMEL;FIN;IND;SG;3;PST;ACT
prokop	prokop	N;NOM;SG
moːkaːn	moːkaːnmə	N;ACC;DEF;SG
pəktəruː	pəktəruːrən	V;FIN;IND;SG;3;PST;ACT
moː	moːduː	N;DAT;SG
haŋaːri	haŋaːril	N;NOM;PL
urkə	urkələː	N;TERM;SG
itiki	itikirwiː	N;PL;PSSRS+ACC
goro	gorogit	N;IN+ABL;SG
ďaw	ďawduː	N;DAT;SG
lapta	laptawə	N;ACC;DEF;SG
ətirkoːt͡ʃə	ətirkoːt͡ʃər	N;NOM;PL
əďiːloː	əďiːloː	N;NOM;SG
ŋənə	ŋənəpdərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
luďi	luďi	N;NOM;SG
oro	orortiki	N;ALL;PL
umukta	umuktawə	N;ACC;DEF;SG
ďirikat͡ʃaːn	ďirikat͡ʃaːn	N;NOM;SG
ŋənə	ŋənəďəŋnəw	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
hutə	hutəlwun	N;NOM;PL;PSS1PE
akini	akiniw	N;NOM;SG;PSS1S
oro	ororduːjiː	N;DAT;PL;PSSRS
aminŋaha	aminŋaha	N;NOM;SG
t͡ʃajiŋ	t͡ʃajiŋrərəw	V;FIN;IND;PL;1+EXCL;PST;ACT
śiɲťabr	śiɲťabrduː	N;DAT;SG
vərhnəimbaskə	vərhnəimbaskəduː	N;DAT;SG
talu	talulduk	N;ABL;PL
halga	halgarwə	N;ACC;DEF;PL
amaskaː	amaskaːlaːji	N;TERM;SG;PSSRS
də	də	N;NOM;SG
in	inďəsoːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
ŋinakisi	ŋinakisil	ADJ;PL
ŋolomo	ŋolomo	N;NOM;SG
homoːti	homoːtidukhint͡ʃə	N;ABL;POT;SG
t͡ʃiskowoj	t͡ʃiskowoj	N;NOM;SG
ďawi	ďawitin	N;NOM;SG;PSS3P
ďu	ďujai	N;ACC;INDF;SG;PSSRS
kərgəni	kərgənin	N;NOM;SG;PSS3S
hulukun	hulukunduːf	N;DAT;SG;PSS1S
ďoromo	ďoromom	V;FIN;IND;SG;1;PST;ACT
hulda	huldalwatin	N;ACC;DEF;PL;PSS3P
dukuwu	dukuwurba	N;ACC;DEF;PL
imuːkśə	imuːkśəwə	N;ACC;DEF;SG
həktəwu	həktəwurduː	N;DAT;PL
həgdiko	həgdikor	ADJ;PL
waː	waːďaŋaːw	V;FIN;IND;SG;1;FUT;ACT
noː	noːŋkiːn	V;FIN;IND;SG;3;PST+RMT;ACT
huru	hurukəl	V;FIN;IMP;SG;2;ACT
atirkaːn	atirkaːnmi	N;SG;PSSRS+ACC
jivo	jivo	ADJ
izbuʃka	izbuʃkalaːji	N;TERM;SG;PSSRS
bira	birala	N;TERM;SG
əɲiːn	əɲiːnmi	N;NOM;SG;PSS1S
hawal	hawaldam	V;IPFV;FIN;IND;SG;1;PRS;ACT
ulumo	ulumoŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
həlakiː	həlakiːla	N;ACC;INDF;PL
akini	akinim	N;NOM;SG;PSS1S
hoγorkiː	hoγorkiː	N;NOM;SG
o	oďarəwun	V;IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
soː	soː	ADJ
meːwan	meːwandukin	N;ABL;SG;PSS3S
bi	bigələwə	N;ACC;DEF;SG
ďu	ďuloː	N;TERM;SG
amar	amarduːn	N;DAT;SG;PSS3S
iďoʃ	iďoʃ	N;NOM;SG
tozəfka	tozəfkawi	N;SG;PSSRS+ACC
ďuktə	ďuktəwə	N;ACC;DEF;SG
ďirika	ďirikaltuk	N;ABL;PL
taw	tawďan	V;IPFV;FIN;IND;SG;3;ACT
hukuləːmɲi	hukuləːmɲihəl	N;NOM;PL
adilisi	adilisiliŋnəm	V;HAB;FIN;IND;SG;1;PST;ACT
ut͡ʃami	ut͡ʃami	N;NOM;SG
ŋəːlə	ŋəːləldən	V;FIN;IND;SG;3;PST;ACT
koŋimnə	koŋimnəwətin	N;ACC;DEF;SG;PSS3P
biraja	birajalduliː	N;PROL;PL
t͡ʃenokoːn	t͡ʃenokoːnmon	N;ACC;DEF;SG;PSS3S
ili	ilittaw	V;DUR;FIN;IND;PL;1+EXCL;PST;ACT
ʃargaśin	ʃargaśin	ADJ;EQTV
dulini	dulinin	N;NOM;SG;PSS3S
dəgilməːktə	dəgilməːktəduː	N;DAT;SG
buː	buːrə	V;FIN;IND;PL;3;PST;ACT
gorod	gorod	N;NOM;SG
dəptiləː	dəptiləːlwə	N;ACC;DEF;PL
ďuː	ďuːlaːtin	N;TERM;SG;PSS3P
o	olalan	V;FIN;IND;SG;3;PST;ACT
uj	ujdən	V;FIN;IND;SG;3;PST;ACT
ŋəːləkəhiː	ŋəːləkəhiːw	N;NOM;SG;PSS1S
uːt͡ʃaki	uːt͡ʃakilduwar	N;DAT;PL;PSSRP
moːtiː	moːtiːwo	N;ACC;DEF;SG
t͡ʃoknaː	t͡ʃoknaːγaːt	V;FIN;IMP;PL;1+INCL;ACT
dərə	dərəloːtin	N;TERM;SG;PSS3P
ďə	ďəmuːďərə	V;IPFV;FIN;IND;SG;3;PRS;ACT
urkə	urkə	N;NOM;SG
bəjŋoː	bəjŋoːwo	N;ACC;DEF;SG
braʃka	braʃkawa	N;ACC;DEF;SG
kaɲeʃna	kaɲeʃna	N;NOM;SG
ŋəli	ŋəlifkəːnďəŋoːw	V;FIN;IND;SG;1;FUT;CAUS;ACT
hoːŋə	hoːŋətin	N;NOM;SG;PSS3P
amakaː	amakaː	N;NOM;SG
gu	guldə	V;FIN;IND;PL;3;PST;ACT
mu	mu	N;NOM;SG
əmə	əməhinə	V;SEMEL;FIN;IND;PL;3;PST;ACT
aliksandr	aliksandr	N;NOM;SG
in	inďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
warwara	warwara	N;NOM;SG
hawal	hawalďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
tuk	tukt͡ʃən	V;FIN;IND;SG;3;FUT+IMMED;ACT
baka	bakat͡ʃawun	V;FIN;IND;PL;1+EXCL;PST;ACT
ŋəlifśə	ŋəlifśə	ADJ
geː	geːlaː	N;TERM;SG
śinťabr	śinťabrduː	N;DAT;SG
tan	tant͡ʃəkəl	V;STAT;FIN;IMP;SG;2;ACT
təγə	təγətt͡ʃəlim	V;DUR+STAT;FIN;IND;SG;1;PST;ACT
amiːni	amiːnin	N;NOM;SG;PSS3S
əwədi	əwədit	ADJ
it͡ʃə	it͡ʃəpkoːtt͡ʃəm	V;IPFV;FIN;IND;SG;1;PRS;CAUS;ACT
t͡ʃikti	t͡ʃikti	N;NOM;SG
klasi	klasil	N;NOM;PL
ilalda	ilaldawa	N;ACC;DEF;SG
ahi	ahi	N;NOM;SG
noːku	noːkudu	N;DAT;SG
moː	moːlə	N;ACC;INDF;PL
bəjə	bəjəjə	N;ACC;INDF;SG
hihə	hihəkoːkunmə	N;ACC;DEF;SG
bi	biďirən	V;IPFV;FIN;IND;SG;3;PRS;ACT
hiŋkəriː	hiŋkəriːďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
hulaki	hulakil	N;NOM;PL
dap	dapdərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
əmə	əməpt͡ʃəːwun	V;FIN;IND;PL;1+EXCL;PST;CAUS;ACT
ďəfkit	ďəfkittikiːwun	N;ALL;SG;PSS1PE
hutə	hutəlnunndə	N;COM;PL;PSS2S
timatnə	timatnəlaː	N;TERM;SG
kuklaka	kuklakardi	N;INS;PL
o	oda	V;FIN;IND;PL;3;PST;ACT
rimontəkaːn	rimontəkaːnwə	N;ACC;DEF;SG
ulumiː	ulumiːdəśoːtin	V;IPFV;FIN;IND;PL;3;PST;ACT
hirbaː	hirbaːwə	N;ACC;DEF;SG
amtiːl	amtiːldulaːwi	N;TERM;SG;PSSRS
aŋani	aŋaniduː	N;DAT;SG
turu	turuduː	N;DAT;SG
hiː	hiːwon	N;ACC;DEF;SG;PSS3S
oː	oːsaːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
soloγuː	soloγuː	N;NOM;SG
amki	amkir	N;NOM;PL
huliŋ	huliŋ	ADJ
hagdi	hagdil	ADJ;PL
ŋənə	ŋənəpt͡ʃaːn	V;FIN;IND;SG;3;PST;ACT
ɲaŋta	ɲaŋtalə	N;ACC;INDF;PL
dawa	dawaŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
uldə	uldəŋiśil	N;NOM;PL;ALN
aj	ajdan	V;FIN;IND;SG;3;PST;ACT
pramhos	pramhostuː	N;DAT;SG
ŋənə	ŋənətt͡ʃiŋnərəwun	V;DUR;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
halga	halgartin	N;NOM;PL;PSS3P
bi	biďəkəldu	V;IPFV;FIN;IMP;PL;2;ACT
t͡ʃapumə	t͡ʃapuməʃaːl	ADJ;PL
ďiwə	ďiwəʃinən	V;SEMEL;FIN;IND;SG;3;PST;ACT
əmkə	əmkəjəw	N;ACC;DEF;SG;PSS1S
turu	turuloː	N;TERM;SG
ila	ilalduliː	N;PROL;SG
himuːrga	himuːrgaran	V;FIN;IND;SG;3;PST;ACT
həhəni	həhəniŋkiːn	V;FIN;IND;SG;3;PST+RMT;ACT
aŋaɲiː	aŋaɲiːs	N;NOM;SG;PSS2S
toγo	toγojo	N;ACC;INDF;SG
haːrgi	haːrgikaːkuːn	N;NOM;SG
tuksa	tuksasinim	V;SEMEL;FIN;IND;SG;1;PST;ACT
kilometr	kilometr	N;NOM;SG
koto	kotojo	N;ACC;INDF;SG
irgi	irgin	N;NOM;SG;PSS3S
nurgoːwul	nurgoːwulwə	N;ACC;DEF;SG
hawali	hawalitt͡ʃaran	V;DUR;IPFV;FIN;IND;SG;3;PRS;ACT
burdukariki	burdukarikir	ADJ;PL
əmə	əməhinəm	V;SEMEL;FIN;IND;SG;1;PST;ACT
dəruːmkisa	dəruːmkisaďəm	V;IPFV;FIN;IND;SG;1;PRS;ACT
ili	ilim	V;FIN;IND;SG;1;PST;ACT
nul	nullan	V;FIN;IND;SG;3;PST;ACT
atirkaːn	atirkaːnnun	N;COM;SG
tukalan	tukalanmə	N;ACC;DEF;SG
saːtirə	saːtirə	N;NOM;SG
əmə	əmədəlanən	V;FIN;IND;SG;3;ACT
nikolajiʃ	nikolajiʃ	N;NOM;SG
lukiː	lukiːlwən	N;ACC;DEF;PL;PSS3S
amargu	amargut	ADJ;INS
kor	korduk	N;ABL;SG
umukoːn	umukoːnmən	N;ACC;DEF;SG;PSS3S
bultakit	bultakittikiːji	N;ALL;SG;PSSRS
ďukə	ďukə	ADJ
valenťinovit͡ʃ	valenťinovit͡ʃ	N;NOM;SG
geːw	geːwran	V;FIN;IND;SG;3;PST;ACT
gaksaː	gaksaːŋitin	N;NOM;SG;ALN+PSS3P
oron	oronŋiːtin	N;NOM;SG;ALN+PSS3P
girani	giranilim	V;FIN;IND;SG;1;PST;ACT
dimeɲťjəf	dimeɲťjəf	N;NOM;SG
trenin	treninduː	N;DAT;SG
kutu	kutujə	N;ACC;INDF;SG
əməːn	əməːnmurən	V;FIN;IND;SG;3;PST;PASS
lurgi	lurgildən	V;FIN;IND;SG;3;PST;ACT
heːlakiː	heːlakiːnun	N;COM;SG
wiťakaːn	wiťakaːnmə	N;ACC;DEF;SG
nado	nado	V;FIN;IND;ACT
pəťorkə	pəťorkəlwə	N;ACC;DEF;PL
koːŋaːktə	koːŋaːktəwan	N;ACC;DEF;SG;PSS3S
ami	amim	N;NOM;SG;PSS1S
tunŋaďar	tunŋaďarduː	N;DAT;SG
amini	aminiw	N;NOM;SG;PSS1S
staːdə	staːdəwətin	N;ACC;DEF;SG;PSS3P
noː	noːsiŋkiːn	V;DUR;FIN;IND;SG;3;PST+RMT;ACT
irəksə	irəksəwon	N;ACC;DEF;SG;PSS3S
bira	bira	N;NOM;SG
bi	biŋkiːn	V;FIN;IND;SG;3;PST+RMT;ACT
anŋaniː	anŋaniːs	N;NOM;SG;PSS2S
gəwariť	gəwariť	N;NOM;SG
huto	hutoldulaːji	N;TERM;PL;PSSRS
mere	meretpi	N;INS;SG;PSSRS
ohotit	ohotitt͡ʃarə	V;IPFV;FIN;IND;PL;3;PRS;ACT
goro	goroγiːt	N;IN+ABL;SG
suglan	suglan	N;NOM;SG
ďu	ďuduːn	N;DAT;SG;PSS3S
urə	urəwa	N;ACC;DEF;SG
halgan	halgannunin	N;COM;SG;PSS3S
wirtoloti	wirtolotit	N;INS;SG
təwuː	təwuːktəďəsoːn	V;IPFV;FIN;IND;SG;3;PST;ACT
uγa	uγaďəŋnarawun	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
ŋənə	ŋənəďəŋnəm	V;HAB+IPFV;FIN;IND;SG;1;PRS;ACT
kira	kiraduː	N;DAT;SG
bi	bihiwun	V;FIN;IND;PL;1+EXCL;PST;ACT
daurskij	daurskij	N;NOM;SG
adil	adil	N;NOM;SG
himiktə	himiktəlwə	N;ACC;DEF;PL
kətə	kətəwa	N;ACC;DEF;SG
ɲiruśan	ɲiruśan	N;NOM;SG
jukələ	jukələwə	N;ACC;DEF;SG
irgit͡ʃiː	irgit͡ʃiːl	N;NOM;PL
ak	akkəldu	V;FIN;IMP;PL;2;ACT
hawal	hawalďat͡ʃaːn	V;IPFV;FIN;IND;SG;3;PST;ACT
pa	pa	N;NOM;SG
bi	biśon	V;FIN;IND;SG;3;PST;ACT
tuγəniː	tuγəniːduː	N;DAT;SG
inmək	inməkpətin	N;ACC;DEF;SG;PSS3P
amari	amariŋdulaːwər	N;TERM;SG;ALN+PSSRP
ulguśoːn	ulguśoːnən	V;FIN;IND;SG;3;PST;ACT
hurkoːkoːśoːn	hurkoːkoːśoːn	N;NOM;SG
n	n	N;NOM;SG
tan	tant͡ʃaďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
hunaːďi	hunaːďiw	N;NOM;SG;PSS1S
suru	surupďet	V;FIN;IND;PL;1+INCL;FUT+IMMED;ACT
ga	gaŋkiːn	V;FIN;IND;SG;3;PST+RMT;ACT
ahatka	ahatkarnun	N;COM;PL
alba	albaďaraw	V;IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
bagdakə	bagdakəlduː	N;DAT;PL
moːtiː	moːtiːwə	N;ACC;DEF;SG
tamnaː	tamnaːhisinŋərəwun	V;DUR+SEMEL;HAB;FIN;IND;PL;1+EXCL;PST;ACT
ullə	ulləduː	N;DAT;SG
ganna	gannarəw	V;FIN;IND;PL;1+EXCL;PST;ACT
wirtolot	wirtolottulaː	N;TERM;SG
ʃapka	ʃapkanŋərə	V;HAB;FIN;IND;PL;3;PST;ACT
ďən	ďənŋiďitin	N;IN+ABL;SG;PSS3P
uγiː	uγiːkoːkunďi	N;INS;SG
buː	buːŋnəm	V;HAB;FIN;IND;SG;1;PST;ACT
ďaw	ďawduːwun	N;DAT;SG;PSS1PE
oːha	oːhalba	N;ACC;DEF;PL
tuganiː	tuganiːduː	N;DAT;SG
jakutska	jakutskaduː	N;DAT;SG
ili	ilisinŋarawun	V;DUR;HAB;FIN;IND;PL;1+EXCL;PST;ACT
sagdi	sagdiŋilwun	V;SPRL;FIN;IND;PL;1+EXCL;ACT
ilaniː	ilaniː	N;NOM;SG
aŋaďakoː	aŋaďakoːrduloː	N;TERM;PL
virtalot	virtalot	N;NOM;SG
ənəlŋə	ənəlŋəs	ADJ;PSS2S
ʃiγun	ʃiγun	N;NOM;SG
unta	untalgali	N;COM;PL
ga	gada	V;FIN;IND;PL;3;PST;ACT
pəktiru	pəktirulləw	V;FIN;IND;PL;1+EXCL;PST;ACT
iśə	iśətkəldo	V;FIN;IMP;PL;2;ACT
nanmakta	nanmaktalduk	N;NOM;PL
naːŋmakta	naːŋmaktaduː	N;DAT;SG
omoːn	omoːnəw	V;FIN;IND;PL;1+EXCL;PST;ACT
wəki	wəkit	N;INS;SG
kapkaśi	kapkaśiliŋnaraw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
ahiː	ahiːs	N;NOM;SG;PSS2S
dəg	dəgďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
tuganiː	tuganiːwa	N;ACC;DEF;SG
musu	musurən	V;FIN;IND;SG;3;PST;ACT
həgdi	həgdiməməl	ADJ;PL
śuːkə	śuːkəlwa	N;ACC;DEF;PL
ďapda	ďapdadaː	N;NOM;SG
ŋoːnimi	ŋoːnimil	ADJ;PL
kəŋiloː	kəŋiloːr	N;NOM;PL
virtaloťi	virtaloťi	N;NOM;SG
ďəwu	ďəwuŋnəs	V;HAB;FIN;IND;PL;2;PST;ACT
buran	buran	N;NOM;SG
ŋənə	ŋənəďəktə	V;IPFV;FIN;IMP;SG;1;ACT
əniːn	əniːnmiː	N;NOM;SG;PSSRS
togo	togodu	N;DAT;SG
tiksa	tiksalďiwər	N;INS;PL;PSSRP
dawi	dawildə	N;INS;PL
ďuːtaː	ďuːtaːďagaːt	V;IPFV;FIN;IMP;PL;1+INCL;ACT
kuŋakaː	kuŋakaːrwə	N;ACC;DEF;PL
klara	klara	N;NOM;SG
ďan	ďanduk	N;ABL;SG
prezidənt	prezidənt	N;NOM;SG
əruː	əruːpt͡ʃu	ADJ
hərəkə	hərəkətmərit	N;NOM;CMPR;SG
gun	gundəm	V;FIN;IND;SG;1;FUT+IMMED;ACT
ŋənə	ŋənəpdəŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
suglan	suglandulaː	N;TERM;SG
moːtiːkuːn	moːtiːkuːn	N;NOM;SG
toγo	toγot	N;INS;SG
ja	ja	N;NOM;SG
bi	bit͡ʃəwun	V;FIN;IND;PL;1+EXCL;PST;ACT
buriː	buriːkəldu	V;FIN;IMP;PL;2;ACT
ɲuŋun	ɲuŋunduː	N;DAT;SG
bəjŋoː	bəjŋoː	N;NOM;SG
bəjə	bəjəduː	N;DAT;SG
ŋaːlə	ŋaːləldukiw	N;ABL;PL;PSS1S
həraŋi	həraŋilwa	N;ACC;DEF;PL
ətets	ətets	N;NOM;SG
darkin	darkinduliː	N;PROL;SG
soliːlaː	soliːlaː	N;NOM;SG
śergejif	śergejif	N;NOM;SG
ŋinaki	ŋinakirwi	N;NOM;PL;PSS1S
ďapkun	ďapkundulaː	N;TERM;SG
əmə	əməśən	V;FIN;IND;SG;3;PST;ACT
ďaw	ďawwər	N;SG;PSSRP+ACC
wibari	wibaril	N;NOM;PL
bi	biʃoːn	V;FIN;IND;SG;3;PST;ACT
amin	aminmər	N;SG;PSSRP+ACC
boroŋkon	boroŋkon	N;NOM;SG
a	aďiŋkiːtin	V;IPFV;FIN;IND;PL;3;PST+RMT;ACT
ŋənə	ŋənəďəkəl	V;IPFV;FIN;IMP;SG;2;ACT
moːlkə	moːlkəwutt͡ʃam	V;DUR;IPFV;FIN;IND;SG;1;PRS;PASS
əjəː	əjəːhino	V;SEMEL;FIN;IND;PL;3;PST;ACT
hawal	hawalďasaːn	V;IPFV;FIN;IND;SG;3;PST;ACT
nevəďili	nevəďili	N;NOM;SG
ɲəkə	ɲəkərəw	V;FIN;IND;PL;1+EXCL;PST;ACT
ďawaptun	ďawaptun	N;NOM;SG
lihat͡ʃow	lihat͡ʃownun	N;COM;SG
tuːruːm	tuːruːmďəŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
aha	ahalin	N;NOM;PL;PSS3S
stado	stadoduːwun	N;DAT;SG;PSS1PE
haŋuːkt͡ʃa	haŋuːkt͡ʃaďaran	V;IPFV;FIN;IND;SG;3;PRS;ACT
uďa	uďalaːn	N;TERM;SG;PSS3S
virtolot	virtolot	N;NOM;SG
hoktə	hoktəwər	N;SG;PSSRP+ACC
oro	ororduliː	N;PROL;PL
puʃnomehowoj	puʃnomehowojduː	N;DAT;SG
mi	mi	N;NOM;SG
waː	waːrən	V;FIN;IND;SG;3;PST;ACT
ďu	ďulawi	N;TERM;SG;PSSRS
haŋukta	haŋuktat͡ʃaw	V;FIN;IND;SG;1;PST;ACT
logiː	logiːrən	V;FIN;IND;SG;3;PST;ACT
əɲokə	əɲokənun	N;COM;SG
ďukt͡ʃa	ďukt͡ʃaduːwər	N;DAT;SG;PSSRP
ďuː	ďuːduːwar	N;DAT;SG;PSSRP
hilki	hilkidəŋnərəwun	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
kilomətər	kilomətər	N;NOM;SG
doːldi	doːldiďam	V;IPFV;FIN;IND;SG;1;PRS;ACT
ozəro	ozəro	N;NOM;SG
guː	guːśoːtin	V;FIN;IND;PL;3;PST;ACT
til	tillə	V;FIN;IND;PL;3;PST;ACT
maŋiː	maŋiːl	N;NOM;PL
orokoː	orokoːrwə	N;ACC;DEF;PL
ama	amawun	V;FIN;IND;PL;1+EXCL;ACT
siŋilgən	siŋilgən	N;NOM;SG
aja	ajaduː	ADJ;DAT;SG
iɲiːp	iɲiːpďəŋnərəw	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
huŋtu	huŋtuwi	ADJ;PSSRS
pəktiruː	pəktiruːllə	V;FIN;IND;PL;3;PST;ACT
əmə	əməďəŋnərəw	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
ŋəni	ŋənin	N;NOM;SG;PSS3S
girku	girkuran	V;FIN;IND;SG;3;PST;ACT
luporoː	luporoːrən	V;FIN;IND;SG;3;PST;ACT
ɲina	ɲina	N;NOM;SG
ďuː	ďuː	N;NOM;SG
kəməďisə	kəməďisə	ADJ
uśitnaːďi	uśitnaːďil	V;FIN;IND;PL;ACT
əmə	əməďaŋaːn	V;FIN;IND;SG;3;FUT;ACT
ŋənə	ŋənəsoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
iɲ	iɲdəm	V;IPFV;FIN;IND;SG;1;PRS;ACT
goroloː	goroloːwo	N;ACC;DEF;SG
həgdi	həgdi	ADJ
selhosťehɲikum	selhosťehɲikum	N;NOM;SG
hot͡ʃ	hot͡ʃ	N;NOM;SG
dəγi	dəγillən	V;FIN;IND;SG;3;PST;ACT
bultana	bultanahinə	V;SEMEL;FIN;IND;PL;3;PST;ACT
gələːktənəː	gələːktənəːhinďəŋoːw	V;SEMEL;FIN;IND;SG;1;FUT;ACT
əɲiː	əɲiːwə	N;ACC;DEF;SG
amar	amardun	N;DAT;SG;PSS3S
ďagda	ďagdaduː	N;DAT;SG
alaguːmniː	alaguːmniːt	N;INS;SG
saŋaːr	saŋaːrwə	N;ACC;DEF;SG
turumnəː	turumnəːŋkiːwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
giramda	giramdalďi	N;INS;PL
mundukan	mundukan	N;NOM;SG
bultahikta	bultahiktadun	N;DAT;SG;PSS3S
inti	intikəl	V;FIN;IMP;SG;2;ACT
nidələ	nidələwə	N;ACC;DEF;SG
moːtiːtkoːn	moːtiːtkoːn	N;NOM;SG
zimowjo	zimowjotki	N;ALL;SG
aśin	aśin	V;FIN;IND;ACT
bəjə	bəjəŋilbəw	N;ACC;DEF;PL;ALN+PSS1S
oɲo	oɲotoːlis	N;NOM;SG
toγo	toγowun	V;FIN;IND;PL;1+EXCL;ACT
bəjə	bəjəlbə	N;ACC;DEF;PL
əmə	əməwuŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
ajaː	ajaːrduliː	N;PROL;PL
ganat	ganat	N;NOM;SG
tətiː	tətiːlwi	N;PL;PSSRS+ACC
t͡ʃurgiː	t͡ʃurgiːďarən	V;IPFV;FIN;IND;SG;3;PRS;ACT
haːki	haːkirwətin	N;ACC;DEF;PL;PSS3P
bulta	bultaliŋkiːw	V;FIN;IND;SG;1;PST+RMT;ACT
sewer	sewertikiː	N;ALL;SG
kalakat͡ʃaːn	kalakat͡ʃaːn	N;NOM;SG
umukkoː	umukkoːr	ADJ;PL
bolʃə	bolʃə	N;NOM;SG
abligatsə	abligatsəlwə	N;ACC;DEF;PL
əmə	əmərə	V;FIN;IND;PL;3;PST;ACT
həgdiŋo	həgdiŋo	ADJ
wrak	wrak	N;NOM;SG
ami	aminən	N;COM;SG
irgiː	irgiːďərəmu	V;FIN;IND;PL;3;FUT+IMMED;ACT
ər	ərda	V;FIN;IND;PL;3;PST;ACT
soliː	soliːγit	N;IN+ABL;SG
kolədʒ	kolədʒwə	N;ACC;DEF;SG
gogo	gogolt͡ʃoː	V;FIN;IND;PST;ACT
həgdiŋəmi	həgdiŋəmi	ADJ
huru	huruldiŋkiːf	V;FIN;IND;SG;1;PST+RMT;ACT
sərkəw	sərkəwduː	N;DAT;SG
ŋinaki	ŋinakirtin	N;NOM;PL;PSS3P
haː	haːsaːm	V;FIN;IND;PST;ACT
bələ	bələpkoːniŋkiːn	V;FIN;IND;SG;3;PST+RMT;CAUS;ACT
hoːŋnaː	hoːŋnaːďan	V;FIN;IND;SG;3;FUT+IMMED;ACT
ila	ilaran	V;FIN;IND;SG;3;PST;ACT
dundə	dundəltikiː	N;ALL;PL
əɲokə	əɲokərwun	N;NOM;PL;PSS1PE
həwəkiː	həwəkiːlaː	N;TERM;SG
ďəb	ďəbďəŋoːn	V;FIN;IND;SG;3;FUT;ACT
armija	armijaduː	N;DAT;SG
ər	ərdən	V;FIN;IND;SG;3;PST;ACT
oldoko	oldokorə	N;ACC;INDF;PL
dəgilməːktə	dəgilməːktəl	N;NOM;PL
amin	amin	N;NOM;SG
akin	akinmi	N;NOM;SG;PSS1S
nulgiː	nulgiːďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
ajaːwriː	ajaːwriː	ADJ
bultaγit	bultaγit	ADJ
sogdonno	sogdonnoduː	N;DAT;SG
kuwrik	kuwriktuː	N;DAT;SG
hoːksələːn	hoːksələːn	ADJ
ham	hamna	V;FIN;IND;PL;3;PST;ACT
əniː	əniː	N;NOM;SG
girkumat	girkumat	ADJ
oloki	olokit	N;INS;SG
saďik	saďiktuː	N;DAT;SG
iltəni	iltənilim	V;FIN;IND;SG;1;PST;ACT
hogdiŋo	hogdiŋo	ADJ
ďurməːnďi	ďurməːnďi	ADJ
ɲama	ɲamaja	N;ACC;INDF;SG
amaːkaː	amaːkaːwə	N;ACC;DEF;SG
əpti	əptihinən	V;SEMEL;FIN;IND;SG;3;PST;ACT
huru	hurudən	V;FIN;IND;SG;3;FUT+IMMED;ACT
tuksa	tuksara	V;FIN;IND;PL;3;PST;ACT
t͡ʃajti	t͡ʃajtirəwun	V;FIN;IND;PL;1+EXCL;PST;ACT
ɲiŋtə	ɲiŋtəŋilwatin	N;ACC;DEF;PL;ALN+PSS3P
məsto	məstoji	N;SG;PSSRS+ACC
girku	girkuďana	V;IPFV;FIN;IND;ACT
ulguson	ulgusondəśon	V;IPFV;FIN;IND;SG;3;PST;ACT
əŋnəkoː	əŋnəkoːrwə	N;ACC;DEF;PL
iŋini	iŋinin	N;NOM;SG;PSS3S
ďujapt͡ʃu	ďujapt͡ʃulwə	N;ACC;DEF;PL
janwar	janwar	N;NOM;SG
omoː	omoːt͡ʃəːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
olgiː	olgiːtt͡ʃan	V;FIN;IND;SG;3;FUT+IMMED;ACT
duː	duːlaːwər	N;TERM;SG;PSSRP
ahi	ahinun	N;COM;SG
irgi	irgiďərə	V;FIN;IND;PL;3;FUT+IMMED;ACT
huju	hujukukor	ADJ;PL
kolhos	kolhostuː	N;DAT;SG
udigir	udigir	N;NOM;SG
əbəːj	əbəːj	N;NOM;SG
vətəran	vətəran	N;NOM;SG
nəkuː	nəkuːm	N;NOM;SG;PSS1S
mudaka	mudakarin	N;NOM;PL;PSS3P
hoːgin	hoːginən	V;FIN;IND;SG;3;PST;ACT
tigə	tigəhun	V;FIN;IND;PL;2;ACT
ʃukʃilrə	ʃukʃilrəwə	N;ACC;DEF;SG
staːdo	staːdoduk	N;ABL;SG
duləːməː	duləːməːrən	V;FIN;IND;SG;3;PST;ACT
poruh	poruhwa	N;ACC;DEF;SG
martə	martəldulaː	N;TERM;SG
toγo	toγotkiː	N;ALL;SG
ɲəkə	ɲəkəďəm	V;IPFV;FIN;IND;SG;1;PRS;ACT
tirgaɲiː	tirgaɲiːwa	N;ACC;DEF;SG
aŋaɲiːśiː	aŋaɲiːśiː	ADJ
kanskij	kanskij	N;NOM;SG
ŋinaki	ŋinakirwa	N;ACC;DEF;PL
ə	ətəm	V;FIN;IND;PSS1S;FUT+IMMED;ACT
biraja	birajan	V;FIN;IND;SG;3;ACT
akir	akirwiw	N;NOM;SG;PSS1S
moːla	moːlaďaŋaːw	V;FIN;IND;SG;1;FUT;ACT
heː	heːrwatin	N;ACC;DEF;PL;PSS3P
ɲimok	ɲimoktuːwər	N;DAT;SG;PSSRP
tətiγəː	tətiγəːlon	N;ACC;INDF;PL;PSS3S
bəjətka	bəjətkar	N;NOM;PL
śədmoj	śədmojduː	N;DAT;SG
nəŋə	nəŋəďəďən	V;IPFV;FIN;IND;SG;3;FUT+IMMED;ACT
eː	eː	N;NOM;SG
oː	oːŋnam	V;HAB;FIN;IND;SG;1;PST;ACT
kiləmetra	kiləmetra	N;NOM;SG
ga	gaďaŋkiːtin	V;IPFV;FIN;IND;PL;3;PST+RMT;ACT
ugu	uguduː	N;DAT;SG
dəgi	dəgi	N;NOM;SG
əmə	əməγoːt	V;FIN;IMP;PL;1+INCL;ACT
əɲiː	əɲiːtin	N;NOM;SG;PSS3P
oː	oːkaldu	V;FIN;IMP;PL;2;ACT
hujukuːn	hujukuːndukpiː	N;ABL;SG;PSSRS
səktələďək	səktələďəkwətin	V;ACC;DEF;FIN;IND;PSS3P;ACT
bi	bit͡ʃoːtin	V;FIN;IND;PL;3;PST;ACT
oldo	oldojo	N;ACC;INDF;SG
bi	biśoːn	V;FIN;IND;SG;3;PST;ACT
umuːnup	umuːnuptaːwər	V;FIN;IMP+RMT;PL;2;ACT
ɲi	ɲi	N;NOM;SG
talu	taluduː	N;DAT;SG
oro	ororwəw	N;ACC;DEF;PL;PSS1S
səktə	səktəkərwə	N;ACC;DEF;PL
gə	gəniw	N;NOM;SG;ALN+PSS1S
girki	girkitin	N;NOM;SG;PSS3P
suru	suruďərə	V;FIN;IND;PL;3;FUT+IMMED;ACT
bargidaː	bargidaːduː	N;DAT;SG
tundrə	tundrəlaː	N;TERM;SG
bi	biśoːtin	V;FIN;IND;PL;3;PST;ACT
ekspeditija	ekspeditijalduː	N;DAT;PL
goro	goro	ADJ
kuŋaːkaː	kuŋaːkaːr	N;NOM;PL
naparniki	naparnikilwi	N;PL;PSSRS+ACC
əmə	əmət͡ʃoːn	V;FIN;IND;SG;3;PST;ACT
haktiraː	haktiraːlalan	V;FIN;IND;SG;3;PST;ACT
doː	doː	V;FIN;IND;ACT
kətə	kətəjə	N;ACC;INDF;SG
gələːktə	gələːktəllən	V;FIN;IND;SG;3;PST;ACT
lurgi	lurgilkokuttən	V;FIN;IND;SG;3;PST;ACT
ilmakta	ilmaktalba	N;ACC;DEF;PL
haŋkə	haŋkələjə	N;PL;PSSRS+ACC
ďoro	ďorotpi	N;INS;SG;PSSRS
əɲiː	əɲiːjaduː	N;DAT;SG
bira	biralaː	N;TERM;SG
jaŋ	jaŋkaːkuːndulaː	N;TERM;SG
dariski	dariski	N;NOM;SG
amaːkaː	amaːkaː	N;NOM;SG
uji	ujigot	V;FIN;IMP;PL;1+INCL;ACT
til	tilt͡ʃoːtin	V;FIN;IND;PL;3;PST;ACT
ila	ilaśiŋnakaldu	V;DUR;HAB;FIN;IMP;PL;2;ACT
aťets	aťets	N;NOM;SG
ʃo	ʃo	ADJ
ďawa	ďawaraw	V;FIN;IND;PL;1+EXCL;PST;ACT
hərəlgəːn	hərəlgəːnmə	N;ACC;DEF;SG
towuli	towuliloːn	N;COM;SG
bargidaː	bargidaːlaːn	N;TERM;SG;PSS3S
aːnŋə	aːnŋəduwər	N;DAT;SG;PSSRP
bi	biśoːn	V;FIN;IND;PL;3;PST;ACT
ismiɲi	ismiɲi	N;NOM;SG
ŋənə	ŋənərəw	V;FIN;IND;PL;1+EXCL;PST;ACT
təγə	təγətmə	V;DUR;FIN;IND;ACT
amiːn	amiːnduːw	N;DAT;SG;PSS1S
staːdo	staːdolaː	N;TERM;SG
istanoki	istanokil	N;NOM;PL
aŋa	aŋawrən	V;FIN;IND;SG;3;PST;PASS
ďu	ďukakanə	N;ACC;INDF;SG
ə	ətondə	V;FIN;IND;SG;2;FUT+IMMED;ACT
sarśikan	sarśikanmə	N;ACC;DEF;SG
homoːtiː	homoːtiːjaj	N;VOC;SG
girku	girkuŋkiːtin	V;FIN;IND;PL;3;PST+RMT;ACT
urə	urələː	N;TERM;SG
hawal	hawalďit͡ʃaːn	V;IPFV;FIN;IND;SG;3;PST;ACT
talu	talulduktin	N;ABL;PL;PSS3P
oː	oːdaf	V;FIN;IND;PST;ACT
doːldiː	doːldiːŋkiːw	V;FIN;IND;SG;1;PST+RMT;ACT
dil	dilgiďin	N;IN+ABL;SG;PSS3S
koŋnomo	koŋnomo	ADJ
dulin	dulin	N;NOM;SG
hunti	huntil	ADJ;PL
amini	aminin	N;NOM;SG;PSS3S
alba	albaldəw	V;FIN;IND;PL;1+EXCL;PST;ACT
heːktakaː	heːktakaːrbə	N;ACC;DEF;PL
irəksə	irəksət	N;INS;SG
haːrgi	haːrgildulaː	N;TERM;PL
tərgəksə	tərgəksəlwatin	N;ACC;DEF;PL;PSS3P
vasiljəvna	vasiljəvna	N;NOM;SG
beːga	beːga	N;NOM;SG
hokto	hoktowə	N;ACC;DEF;SG
iruː	iruːktəďət͡ʃən	V;IPFV;FIN;IND;SG;3;PST;ACT
ďaďa	ďaďanunmi	N;COM;SG;PSSRS
həgdi	həgdilduloːtin	N;TERM;SG;PSS3P
ŋəkə	ŋəkəďem	V;FIN;IND;SG;1;PST;ACT
pensijə	pensijəduːji	N;DAT;SG;PSSRS
tuγaɲiː	tuγaɲiːduː	N;DAT;SG
bu	but͡ʃən	V;FIN;IND;SG;3;PST;ACT
oro	ororduː	N;DAT;PL
adil	adiljawər	N;ACC;INDF;SG;PSSRP
bəjŋoː	bəjŋoːl	N;NOM;PL
əŋnəkəː	əŋnəkəːr	N;NOM;PL
əriː	əriːγin	V;FIN;IMP;SG;3;ACT
dur	dur	N;NOM;SG
rewolutśija	rewolutśija	N;NOM;SG
əntil	əntiltin	N;NOM;SG;PSS3P
mudani	mudaniŋiːw	N;NOM;SG;ALN+PSS1S
ďuganiː	ďuganiːwə	N;ACC;DEF;SG
ďu	ďuduwar	N;DAT;SG;PSSRP
ďəptəl	ďəptəl	N;NOM;SG
ďəw	ďəwďəŋnəs	V;HAB+IPFV;FIN;IND;PL;2;PRS;ACT
kolan	kolannun	N;COM;SG
oha	ohalwə	N;ACC;DEF;PL
isə	isəwkoːśilďəndə	V;FIN;IND;SG;2;FUT+IMMED;CAUS;ACT
hujukuː	hujukuːrdukkər	N;ABL;PL;PSSRP
uγu	uγutki	N;ALL;SG
ələːkəːn	ələːkəːnin	ADJ;PSS3S
kiŋgiloːn	kiŋgiloːn	N;NOM;SG
rot	rottuː	N;DAT;SG
nulgiː	nulgiːhinə	V;SEMEL;FIN;IND;PL;3;PST;ACT
ətirkoːn	ətirkoːnduːji	N;DAT;SG;PSSRS
bər	bərwi	N;SG;PSSRS+ACC
oldoː	oldoːlbə	N;ACC;DEF;PL
anŋaɲiː	anŋaɲiːwə	N;ACC;DEF;SG
dilasa	dilasa	N;NOM;SG
bagatiji	bagatijil	ADJ;PL
fśu	fśu	ADJ
huŋta	huŋta	ADJ
amtil	amtilnun	N;COM;SG
muː	muːwə	N;ACC;DEF;SG
ďuː	ďuːlduːtin	N;DAT;PL;PSS3P
don	donťaďam	V;STAT;IPFV;FIN;IND;SG;1;PRS;ACT
dəginti	dəgintit	ADJ
huɲiː	huɲiːlin	N;NOM;PL;PSS3S
t͡ʃemo	t͡ʃemokokoːn	N;NOM;SG
huŋtuki	huŋtuki	ADJ
tərgəksə	tərgəksəlwətin	N;ACC;DEF;PL;PSS3P
ir	irgaťin	N;NOM;CMPR;SG
ďawa	ďawakśiďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
biːwun	biːwun	N;NOM;SG
əksə	əksəktəŋkiːtin	V;FIN;IND;PL;3;PST+RMT;ACT
siksiŋa	siksiŋalwə	N;ACC;DEF;PL
irgiʃi	irgiʃilwun	N;NOM;PL;PSS1PE
in	indərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
ďa	ďalduːji	N;DAT;PL;PSSRS
ila	ilaśildan	V;DUR;FIN;IND;SG;3;PST;ACT
əːs	əːstən	V;FIN;IND;SG;3;PST;ACT
hitəːn	hitəːnmə	N;ACC;DEF;SG
it͡ʃə	it͡ʃətnoːγinim	V;DUR+SEMEL;FIN;IND;SG;1;PST;ACT
bi	bilďəp	V;FIN;IND;PL;1+INCL;FUT+IMMED;ACT
habəl	habəl	N;NOM;SG
togo	togowun	N;NOM;SG;PSS1PE
ɲimŋakaːnmə	ɲimŋakaːnmə	ADJ
talaka	talakaďaŋaw	V;FIN;IND;SG;1;FUT;ACT
ribakil	ribakildan	V;FIN;IND;SG;3;PST;ACT
uγut͡ʃak	uγut͡ʃaktuː	N;DAT;SG
ədi	ədidui	N;DAT;SG;PSSRS
o	odaŋaːtin	V;FIN;IND;PL;3;FUT;ACT
amin	aminman	N;ACC;DEF;SG;PSS3S
adiːraː	adiːraː	V;FIN;IND;ACT
palatka	palatkalaː	N;TERM;SG
tiksa	tiksawa	N;ACC;DEF;SG
puruliwun	puruliwunmi	N;SG;PSSRS+ACC
uːt͡ʃak	uːt͡ʃakjan	N;ACC;INDF;SG;PSS3S
atirkaːn	atirkaːnmə	N;ACC;DEF;SG
kuːkti	kuːktirən	V;FIN;IND;SG;3;PST;ACT
ahami	ahamil	N;NOM;PL
wojna	wojna	N;NOM;SG
iɲ	iɲďit͡ʃoːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
alagu	alaguďaŋaːw	V;FIN;IND;SG;1;FUT;ACT
o	oďaŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
an	anŋit	N;IN+ABL;SG
tirganiː	tirganiː	N;NOM;SG
haruːkka	haruːkkar	N;NOM;PL
armija	armijam	N;ACC;DEF;SG
oron	oronə	N;ACC;INDF;SG
haːrgi	haːrgiduː	N;DAT;SG
ənə	ənə	N;NOM;SG
iːkəːriː	iːkəːriːwon	N;ACC;DEF;SG;PSS3S
əŋnəko	əŋnəkorduː	N;DAT;PL
iɲ	iɲďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
hukti	huktilt͡ʃaːn	V;FIN;IND;SG;3;PST;ACT
papal	papallən	V;FIN;IND;SG;3;PST;ACT
buktarani	buktaranim	V;FIN;IND;SG;1;PST;ACT
namaː	namaːrə	V;FIN;IND;PL;3;PST;ACT
hutə	hutəduː	N;DAT;SG
ribzəvod	ribzəvodtuː	N;DAT;SG
əmkə	əmkəduː	N;DAT;SG
oldo	oldolbo	N;ACC;DEF;PL
huru	hurupďən	V;FIN;IND;SG;3;FUT+IMMED;ACT
halga	halgardiwi	N;INS;PL;PSS1S
tətiγə	tətiγəlwə	N;ACC;DEF;PL
təgə	təgərə	V;FIN;IND;PL;3;PST;ACT
hərmə	hərməldu	N;DAT;PL
ɲəkə	ɲəkəlləw	V;FIN;IND;PL;1+EXCL;PST;ACT
idəhəti	idəhətiγisiŋkiːwun	V;DUR+SEMEL;FIN;IND;PL;1+EXCL;PST+RMT;ACT
kəŋiloːn	kəŋiloːn	N;NOM;SG
ojogir	ojogir	N;NOM;SG
mukoːto	mukoːton	N;NOM;SG;PSS3S
kurəː	kurəːloːw	N;TERM;SG;PSS1S
haktiraː	haktiraːduː	N;DAT;SG
ikoː	ikoːγoːt	V;FIN;IMP;PL;1+INCL;ACT
bəjə	bəjəŋiltin	N;NOM;PL;ALN+PSS3P
ďu	ďulawər	N;TERM;SG;PSSRP
girku	girkuďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
kəŋginə	kəŋginəllən	V;FIN;IND;SG;3;PST;ACT
howos	howospatin	N;ACC;DEF;SG;PSS3P
ɲaŋta	ɲaŋtal	N;NOM;PL
təγə	təγərən	V;FIN;IND;SG;3;PST;ACT
amar	amarduliːwun	N;PROL;SG;PSS1PE
norma	norma	N;NOM;SG
ďiko	ďikont͡ʃəďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
tsəntralka	tsəntralkadukpi	N;ABL;SG;PSSRS
gərbiː	gərbiːsoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
gogo	gogodaran	V;IPFV;FIN;IND;SG;3;PRS;ACT
bi	bimt͡ʃow	V;FIN;COND;SG;1;ACT
hələ	hələlwə	N;ACC;DEF;PL
muːliː	muːliːŋnəďəŋəːw	V;HAB;FIN;IND;SG;1;FUT;ACT
kərt͡ʃimə	kərt͡ʃiməŋiltin	N;NOM;PL;ALN+PSS3P
gorokon	gorokonmə	N;ACC;DEF;SG
ami	amija	N;NOM;SG
zajafka	zajafkaja	N;ACC;INDF;SG
bi	biŋkiːn	V;FIN;IND;PST+RMT;ACT
əɲi	əɲim	N;NOM;SG;PSS1S
gənnoː	gənnoːʃu	V;SEMEL;FIN;IND;PL;3;PST;ACT
tumɲina	tumɲinaďin	N;INS;SG;PSS3S
ga	galďaŋaːs	V;FIN;IND;SG;2;FUT;ACT
tukʃa	tukʃaməlt͡ʃəmt͡ʃo	V;FIN;COND;ACT
prəʃol	prəʃol	N;NOM;SG
iɲəktə	iɲəktəďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
ɲuŋun	ɲuŋunma	N;ACC;DEF;SG
ɲorma	ɲorma	N;NOM;SG
majgu	majgulwə	N;ACC;DEF;PL
olgiː	olgiːkta	V;FIN;IMP;SG;1;ACT
tutont͡ʃanə	tutont͡ʃanəduː	N;DAT;SG
hawa	hawajawi	N;ACC;INDF;SG;PSSRS
agiː	agiːla	N;TERM;SG
obeda	obedat	N;INS;SG
sergejew	sergejew	N;NOM;SG
abdun	abdunma	N;ACC;DEF;SG
dulapti	dulaptirwon	N;ACC;DEF;PL;PSS3S
joːkə	joːkəlkoːkuttə	V;FIN;IND;PL;3;PST;ACT
opiti	opitiw	N;NOM;SG;PSS1S
iŋin	iŋin	N;NOM;SG
bulta	bultaŋkiːn	V;FIN;IND;PST+RMT;ACT
ďərewɲə	ďərewɲəlaː	N;TERM;SG
it͡ʃə	it͡ʃətt͡ʃəm	V;DUR;FIN;IND;SG;1;FUT+IMMED;ACT
girku	girkuďit͡ʃoːn	V;IPFV;FIN;IND;SG;3;PST;ACT
ini	iniktin	V;FIN;IMP;PL;3;ACT
tuŋa	tuŋawa	N;ACC;DEF;SG
ɲamapt͡ʃu	ɲamapt͡ʃujə	ADJ;ACC;INDF
irəkśə	irəkśəlduː	N;DAT;PL
t͡ʃipkaːn	t͡ʃipkaːn	N;NOM;SG
ratsija	ratsijat	N;INS;SG
molda	moldahinan	V;SEMEL;FIN;IND;SG;3;PST;ACT
gələːktənaː	gələːktənaːďəkəl	V;IPFV;FIN;IMP;SG;2;ACT
t͡ʃiːwaː	t͡ʃiːwaːďəďən	V;IPFV;FIN;IND;SG;3;FUT;ACT
ŋələfśi	ŋələfśikoː	ADJ
iː	iːrən	V;FIN;IND;SG;3;PST;ACT
hamaːn	hamaːn	N;NOM;SG
dulin	dulindun	N;DAT;SG;PSS3S
hilba	hilbaśilďaŋaːf	V;DUR;FIN;IND;PSS1S;FUT;ACT
tehnikum	tehnikumduː	N;DAT;SG
ɲəkə	ɲəkəďət͡ʃoːw	V;IPFV;FIN;IND;SG;1;PST;ACT
ije	ijellukin	N;ABL;PL;PSS3S
arakukaːn	arakukaːn	N;NOM;SG
ŋələ	ŋələllə	V;FIN;IND;PL;3;PST;ACT
huru	huruwrə	V;FIN;IND;PL;3;PST;ACT
irəkśə	irəkśəwə	N;ACC;DEF;SG
bagdakəː	bagdakəːlwə	N;ACC;DEF;PL
oro	ororwə	N;ACC;DEF;PL
ɲama	ɲamalgiːďaŋaːn	V;FIN;IND;SG;3;FUT;ACT
bultahit	bultahit	ADJ
tolgokiː	tolgokiːduː	N;DAT;SG
meːwa	meːwamďəroran	V;FIN;IND;SG;3;PST;ACT
ilkəːɲ	ilkəːɲďəkiśiltin	V;IPFV;FIN;IND;PL;PSS3P;ACT
aŋaɲiː	aŋaɲiː	N;NOM;SG
aː	aːhindajatin	V;SEMEL;ACC;INDF;FIN;IND;PSS3P;ACT
ajalə	ajalə	ADJ
boroʃi	boroʃilwə	N;ACC;DEF;PL
amiːn	amiːnmi	N;NOM;SG;PSS1S
əɲiːnmə	əɲiːnməw	ADJ
hama	hama	N;NOM;SG
tulə	tuləśiliŋərəw	V;DUR;HAB;FIN;IND;PL;1+EXCL;PST;ACT
girku	girkuďat͡ʃaːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
heːktakaː	heːktakaːrduk	N;ABL;PL
uldi	uldiŋnəm	V;HAB;FIN;IND;SG;1;PST;ACT
ŋəli	ŋəliśiŋnəm	V;DUR;HAB;FIN;IND;SG;1;PST;ACT
ďebŋənə	ďebŋənəlwə	N;ACC;DEF;PL
bəjo	bəjoda	V;FIN;IND;PL;3;PST;ACT
nakanno	nakanno	N;NOM;SG
bi	bit͡ʃoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
ɲaŋta	ɲaŋtala	N;ACC;INDF;PL
diliː	diliː	N;NOM;SG
oro	ororbor	N;PL;PSSRP+ACC
śila	śilatt͡ʃillaw	V;DUR;IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
ŋinakin	ŋinakinməwun	N;ACC;DEF;SG;PSS1PE
hamɲiːka	hamɲiːkarə	N;ACC;INDF;PL
jaŋi	jaŋiltikiː	N;ALL;PL
huru	huruγoːt	V;FIN;IMP;PL;1+INCL;ACT
ə	əŋkiːwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
boloniː	boloniːwə	N;ACC;DEF;SG
śipkaː	śipkaːkakaːn	N;NOM;SG
hujukuːn	hujukuːn	ADJ
bi	bihe	V;FIN;IND;PL;3;PST;ACT
diŋniːləːn	diŋniːləːnən	V;FIN;IND;SG;3;PST;ACT
vobʃəm	vobʃəm	ADJ
o	okta	V;FIN;IMP;SG;1;ACT
aknil	aknilwi	N;NOM;SG;PSSRS
hutakat͡ʃaːn	hutakat͡ʃaːnə	N;ACC;INDF;SG
agdi	agdiďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
bira	biraliː	N;PROL;SG
ŋolə	ŋolətt͡ʃu	V;DUR;FIN;IND;PL;3;PST;ACT
pə	pə	N;NOM;SG
dundə	dundəwə	N;ACC;DEF;SG
dunnə	dunnəma	N;NOM;SG
ďaďa	ďaďa	N;NOM;SG
aŋanisi	aŋanisi	ADJ
umaːn	umaːnman	N;ACC;DEF;SG;PSS3S
əbəj	əbəj	N;NOM;SG
ahatawet	ahatawettulaː	N;TERM;SG
hukulo	hukulodərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
aleksejewna	aleksejewna	N;NOM;SG
əɲin	əɲindujiː	N;DAT;SG;PSSRS
aŋani	aŋanis	N;NOM;SG;PSS2S
aːnŋə	aːnŋəttə	V;DUR;FIN;IND;PL;3;PST;ACT
terapefťə	terapefťə	N;NOM;SG
ə	əsəwun	V;FIN;IND;PL;1+EXCL;PST;ACT
ďə	ďəmuːldən	V;FIN;IND;SG;3;PST;ACT
aloʃa	aloʃa	N;NOM;SG
samolot	samolot	N;NOM;SG
ɲimoki	ɲimokildulaːji	N;TERM;PL;PSSRS
altaśi	altaśildan	V;FIN;IND;SG;3;PST;ACT
tolgoki	tolgokildulaːwər	N;TERM;PL;PSSRP
təwə	təwəkəllə	V;FIN;IMP;PL;2;ACT
beːgaśi	beːgaśi	ADJ
ili	ilitt͡ʃaːn	V;DUR;FIN;IND;SG;3;PST;ACT
ŋoːlə	ŋoːləfkoːnďəm	V;FIN;IND;SG;1;FUT+IMMED;CAUS;ACT
ďəpti	ďəptil	N;NOM;PL
murdaː	murdaːrəw	V;FIN;IND;PL;1+EXCL;PST;ACT
ini	inilďərəs	V;IPFV;FIN;IND;PL;2;FUT+IMMED;ACT
bi	bit͡ʃəːtin	V;FIN;IND;PL;3;PST;ACT
haŋaːri	haŋaːrilwan	N;ACC;DEF;PL;PSS3S
in	induː	N;DAT;SG
sudə	sudəwə	N;ACC;DEF;SG
t͡ʃanku	t͡ʃankulwə	N;ACC;DEF;PL
ɲutə	ɲutəlwə	N;ACC;DEF;PL
umukən	umukən	ADJ
baloki	balokilduːtin	N;DAT;PL;PSS3P
dərumkiśə	dərumkiśəďəkəl	V;IPFV;FIN;IMP;SG;2;ACT
mənmaktə	mənmaktəl	N;NOM;PL
prəmhos	prəmhostuː	N;DAT;SG
ŋənə	ŋənəďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
ďu	ďulaːwər	N;TERM;SG;PSSRP
kapka	kapkarwi	N;PL;PSSRS+ACC
ŋoːlə	ŋoːləpkoːnən	V;FIN;IND;SG;3;PST;CAUS;ACT
amiː	amiːriktatin	N;NOM;SG;PSS3P
aː	aːďiŋnandə	V;HAB+IPFV;FIN;IND;SG;2;PRS;ACT
ubdun	ubdundukin	N;ABL;SG;3
iŋiɲipt͡ʃu	iŋiɲipt͡ʃukoːkun	ADJ
tuŋi	tuŋiwə	N;ACC;DEF;SG
itiγaː	itiγaːďəŋnərəwun	V;HAB+IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
t͡ʃikti	t͡ʃiktilwə	N;ACC;DEF;PL
doldi	doldit͡ʃim	V;DUR;FIN;IND;SG;1;PST;ACT
t͡ʃokoksoːn	t͡ʃokoksoːnmo	N;ACC;DEF;SG
kəŋiloːn	kəŋiloːnə	N;ACC;INDF;SG
ulukiː	ulukiː	N;NOM;SG
ruʒjom	ruʒjom	N;NOM;SG
ďantakiː	ďantakiːlwa	N;ACC;DEF;PL
ďəm	ďəmmulləw	V;FIN;IND;PL;1+EXCL;PST;ACT
ulgot͡ʃoː	ulgot͡ʃoːwaːtt͡ʃəŋkiːf	V;IPFV;FIN;IND;SG;1;PST+RMT;ACT
ďuːr	ďuːrwə	N;ACC;DEF;SG
bokonə	bokonəm	V;FIN;IND;SG;1;PST;ACT
uda	udalwan	N;ACC;DEF;PL;PSS3S
omo	omofśoːtin	V;FIN;IND;PL;3;PST;ACT
samoloːt	samoloːttu	N;DAT;SG
birə	birəldulaː	N;TERM;PL
hujet	hujett͡ʃoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
orohəmə	orohəmə	ADJ
japə	japət͡ʃoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
ohoto	ohotowa	N;ACC;DEF;SG
ďawi	ďawilwa	N;ACC;DEF;PL
kilometr	kilometrduliː	N;PROL;SG
t͡ʃatti	t͡ʃattirəwun	V;FIN;IND;PL;1+EXCL;PST;ACT
həgdiŋə	həgdiŋəkoːkurďi	V;IPFV;FIN;IND;PL;ACT
hukśilla	hukśillalďi	N;INS;PL
moti	motilvə	N;ACC;DEF;PL
bi	bit͡ʃoːm	V;FIN;IND;SG;1;PST;ACT
oro	ororbi	N;NOM;PL;PSS1S
ɲəŋɲəɲiː	ɲəŋɲəɲiːt	N;INS;SG
amaka	amakaw	N;NOM;SG;PSS1S
buː	buːŋkitin	V;FIN;IND;PL;3;PST+RMT;ACT
jest	jest	N;NOM;SG
amkin	amkinə	N;ACC;INDF;SG
hələ	hələwə	N;ACC;DEF;SG
oldo	oldolə	N;ACC;INDF;PL
ili	ilitt͡ʃim	V;DUR;IPFV;FIN;IND;SG;1;PRS;ACT
əmə	əməpďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
buː	buːŋkiːtin	V;FIN;IND;PL;3;PST+RMT;ACT
pəɲśija	pəɲśija	N;NOM;SG
tijəpkoːn	tijəpkoːnďiwi	V;IPFV;FIN;IND;PSSRS;ACT
zaʃiʃati	zaʃiʃatilďəm	V;FIN;IND;SG;1;FUT+IMMED;ACT
kislokan	kislokandulaː	N;DAT;SG
in	inďit͡ʃoːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
amaːkaː	amaːkaːdukpi	N;ABL;SG;PSSRS
anŋaɲiː	anŋaɲiːlduləː	N;TERM;PL
uďa	uďaliːn	N;PROL;SG;PSS3S
hamaːn	hamaːnŋiduːtin	N;DAT;SG;ALN+PSS3P
bolnisa	bolnisa	N;NOM;SG
oː	oːran	V;FIN;IND;SG;3;PST;ACT
asin	asinduː	N;DAT;SG
umuko	umuko	ADJ
ilan	ilanďi	N;INS;SG
haŋiː	haŋiːsinəw	V;SEMEL;FIN;IND;PL;1+EXCL;PST;ACT
śimja	śimjaduk	N;ABL;SG
zaatehnik	zaatehnik	N;NOM;SG
at͡ʃi	at͡ʃir	N;NOM;PL
grus	gruspa	N;ACC;DEF;SG
kuŋakan	kuŋakandujiː	N;DAT;SG;PSSRS
dinŋiːləː	dinŋiːləːďəŋəːn	V;FIN;IND;SG;3;FUT;ACT
a	aďiŋkiːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST+RMT;ACT
pramhoz	pramhoz	N;NOM;SG
ulgut͡ʃəːni	ulgut͡ʃəːnim	V;FIN;IND;SG;1;PST;ACT
waː	waːt͡ʃaw	V;FIN;IND;SG;1;PST;ACT
nulgiː	nulgiːst͡ʃəwun	V;SEMEL;FIN;IND;PL;1+EXCL;PST;ACT
hənŋə	hənŋə	N;NOM;SG
uldə	uldəlwə	N;ACC;DEF;PL
kapkan	kapkanduːn	N;DAT;SG;PSS3S
uďa	uďalwaw	N;ACC;DEF;PL;PSS1S
o	oγin	V;FIN;IMP;SG;3;ACT
marʃruti	marʃrutin	N;NOM;SG;PSS3S
ɲikə	ɲikəďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
əː	əː	N;NOM;SG
turəːni	turəːnin	N;NOM;SG;PSS3S
ənin	əninnunmi	N;COM;SG;PSS1S
tərgəksəkəː	tərgəksəkəːrwər	N;NOM;PL;PSSRP
uləː	uləːrən	V;FIN;IND;SG;3;PST;ACT
saʃka	saʃka	N;NOM;SG
naː	naːpkaːnən	V;FIN;IND;SG;3;PST;PASS
kuptu	kupturan	V;FIN;IND;SG;3;PST;ACT
ďuː	ďuːl	N;NOM;PL
kuŋakan	kuŋakanmə	N;ACC;DEF;SG
ɲimŋakaːn	ɲimŋakaːn	N;NOM;SG
produkta	produktala	N;ACC;INDF;PL
buː	buːŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
bəjə	bəjəhint͡ʃə	V;FIN;POT;ACT
hoː	hoːŋmatin	N;ACC;DEF;SG;ALN+PSS3P
vəťərantruda	vəťərantrudaduː	N;DAT;SG
ahiːla	ahiːlarən	V;FIN;IND;SG;3;PST;ACT
ɲimnoʃkato	ɲimnoʃkato	ADJ
ga	gaďas	V;FIN;IND;PL;2;FUT+IMMED;ACT
amin	aminməs	N;ACC;DEF;SG;PSS2S
ətəji	ətəjitt͡ʃəndə	V;DUR;IPFV;FIN;IND;SG;2;PRS;ACT
baka	bakaraw	V;FIN;IND;PL;1+EXCL;PST;ACT
awgusta	awgustatkiː	N;ALL;SG
umuktaγat͡ʃini	umuktaγat͡ʃinin	ADJ;EQTV;PSS3S
tirəː	tirəːrən	V;FIN;IND;SG;3;PST;ACT
nulgiː	nulgiːt͡ʃoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
ɲəkə	ɲəkəďəm	V;FIN;IND;SG;1;FUT+IMMED;ACT
uksədikəːn	uksədikəːn	ADJ;EQTV
guluwun	guluwuntikiːn	N;ALL;SG;PSS3S
buː	buː	N;NOM;SG
amaː	amaː	N;NOM;SG
ut͡ʃami	ut͡ʃamilaː	N;TERM;SG
ďuː	ďuːji	N;NOM;SG;PSSRS
əkniːl	əkniːlwə	N;NOM;SG;PSS1S
hukti	huktillən	V;FIN;IND;SG;3;PST;ACT
etitə	etitə	ADJ
ollo	ollolo	N;ACC;INDF;PL
dundə	dundəlduloːn	N;TERM;PL;PSS3S
ribat͡ʃiťtə	ribat͡ʃiťtə	ADJ
kujkiː	kujkiː	ADJ
kujiː	kujiːkoːtt͡ʃərkəl	V;IPFV;FIN;POT;PL;3;ACT
hokto	hoktoduː	N;DAT;SG
ŋinaγiː	ŋinaγiːrawun	V;FIN;IND;PL;1+EXCL;PST;ACT
koto	kotolduːhun	N;DAT;PL;PSS2P
ďiwo	ďiwolda	V;FIN;IND;PL;3;PST;ACT
sok	sokt͡ʃaːtin	V;FIN;IND;PL;3;PST;ACT
ili	iliduː	N;DAT;SG
buː	buːďəm	V;FIN;IND;SG;1;FUT+IMMED;ACT
əməːn	əməːnmuďən	V;FIN;IND;SG;3;FUT+IMMED;PASS
ənŋə	ənŋəkəl	V;FIN;IMP;SG;2;ACT
bəjatsə	bəjatsə	N;NOM;SG
moː	moːlaː	N;TERM;SG
həgdiŋoko	həgdiŋokor	ADJ;PL
dulin	dulinduːn	N;DAT;SG;PSS3S
buɲiː	buɲiːlwər	N;PL;PSSRP+ACC
dəγi	dəγiktəśoːw	V;FIN;IND;SG;1;PST;ACT
ʒe	ʒe	N;NOM;SG
amini	aminiw	N;NOM;SG;PSS3S
dəgi	dəgil	N;NOM;PL
ijəko	ijəkor	N;NOM;PL
bira	biraŋiwi	N;NOM;SG;ALN+PSSRS
siŋilgən	siŋilgənďi	N;INS;SG
iɲ	iɲďam	V;IPFV;FIN;IND;SG;1;PRS;ACT
ďəpi	ďəpiŋkiːwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
tawu	tawuŋnarəwun	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
ďaw	ďaw	N;NOM;SG
atirkaːn	atirkaːnnundulaː	N;COM+TERM;SG
huru	huruldirən	V;FIN;IND;SG;3;PST;ACT
irəkʃə	irəkʃəwon	N;ACC;DEF;SG;PSS3S
ugu	uguwuŋkin	V;FIN;IND;SG;3;PST+RMT;ACT
gun	gun	V;FIN;IND;ACT
ɲikə	ɲikəsəːw	V;FIN;IND;SG;1;PST;ACT
huďi	huďilďəŋoːt	V;FIN;IND;PL;1+INCL;FUT;ACT
irgi	irgitt͡ʃəŋkiːtin	V;DUR;IPFV;FIN;IND;PL;3;PST+RMT;ACT
soːkaːn	soːkaːnďit͡ʃaːtin	V;IPFV;FIN;IND;PL;3;PST;ACT
nəkə	nəkəďəm	V;IPFV;FIN;IND;SG;1;PRS;ACT
kolan	kolan	N;NOM;SG
iśə	iśətnoːdə	V;DUR;FIN;IND;ACT
luk	lukta	V;FIN;IND;PL;3;PST;ACT
igďamakaːn	igďamakaːn	ADJ
aha	ahalnun	N;COM;PL
asi	asir	N;NOM;PL
təro	tərom	V;FIN;IND;SG;1;PST;ACT
baka	bakam	V;FIN;IND;SG;1;PST;ACT
awu	awuŋkiːw	V;FIN;IND;SG;1;PST+RMT;ACT
pastuhi	pastuhiďət͡ʃaːw	V;IPFV;FIN;IND;SG;1;PST;ACT
əmə	əməwrən	V;FIN;IND;SG;3;PST;ACT
həgdiloːn	həgdiloːn	ADJ
ośin	ośin	N;NOM;SG
ŋənə	ŋənəktəďəndə	V;FIN;IMP;SG;1;ACT
ďuγuː	ďuγuːlin	N;PROL;SG;PSS3S
turoː	turoː	N;NOM;SG
haː	haːndə	V;FIN;IND;SG;2;PST;ACT
irkutskaj	irkutskajduː	N;DAT;SG
tawu	tawuŋnərə	V;HAB;FIN;IND;PL;3;PST;ACT
əďiː	əďiːγit	N;IN+ABL;SG
hulu	hulukukon	ADJ
əməːn	əməːnďən	V;FIN;IND;SG;3;FUT+IMMED;ACT
wertoloːti	wertoloːtit	N;INS;SG
kantora	kantora	N;NOM;SG
ŋinakin	ŋinakinmun	N;NOM;SG;PSS1PE
bi	biśiwun	V;FIN;IND;PL;1+EXCL;PST;ACT
ini	inihit͡ʃoːw	V;SEMEL;FIN;IND;SG;1;PST;ACT
hoːm	hoːmnən	V;FIN;IND;SG;3;PST;ACT
ili	ilitt͡ʃərəw	V;DUR;IPFV;FIN;IND;PL;1+EXCL;PRS;ACT
aŋaɲiː	aŋaɲiːn	V;FIN;IND;SG;3;ACT
majgu	majgu	N;NOM;SG
dinŋiːləːn	dinŋiːləːnďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
amut	amut	N;NOM;SG
girkumət	girkumət	ADJ
kazak	kazak	N;NOM;SG
hawal	hawalt͡ʃaː	V;FIN;IND;FUT;ACT
mukurə	mukurətta	V;FIN;IND;PL;3;PST;ACT
ijə	ijəlwon	N;ACC;DEF;PL;PSS3S
hawal	hawalďit͡ʃaːw	V;IPFV;FIN;IND;SG;1;PST;ACT
ərdikoːn	ərdikoːn	ADJ
da	dalduji	N;DAT;PL;PSSRS
amin	amintin	N;NOM;SG;PSS3P
oroni	oronin	N;NOM;SG;PSS3S
hukuləː	hukuləːďəkoːkuttən	V;IPFV;FIN;IND;SG;3;PRS;ACT
toγo	toγon	N;NOM;SG;PSS3S
ulukiː	ulukiːwə	N;ACC;DEF;SG
hujət	hujətt͡ʃoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
bəju	bəjurə	N;ACC;INDF;PL
aha	ahaďərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
ɲiďəla	ɲiďəladuː	N;DAT;SG
dəktəndə	dəktəndəlbi	N;NOM;PL;PSS1S
moː	moːlwə	N;ACC;DEF;PL
həgdihə	həgdihəlim	V;FIN;IND;SG;1;PST;ACT
plemaniki	plemanikiw	N;NOM;SG;PSS1S
ŋinaki	ŋinakirďi	N;INS;PL
tolgokiː	tolgokiːlďi	N;INS;PL
pəktirəː	pəktirəːməːt͡ʃillə	V;FIN;IND;PL;3;PST;RECP;ACT
tiha	tihaktaďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
təwlaː	təwlaːhiďət͡ʃaːwun	V;SEMEL;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
aminŋəhə	aminŋəhə	N;NOM;SG
ŋəli	ŋəlifśijoj	N;VOC;SG
ə	ələtin	V;FIN;IND;PL;3;PST;ACT
əjəː	əjəːskəl	V;SEMEL;FIN;IMP;SG;2;ACT
najabra	najabra	N;NOM;SG
suːko	suːkolwun	N;NOM;PL;PSS1PE
amin	aminmun	N;NOM;SG;PSS1PE
aja	ajatmər	ADJ;NOM;CMPR;SG
halgaliʃu	halgaliʃu	N;NOM;SG
ďu	ďudu	N;DAT;SG
huru	hurusoːwun	V;FIN;IND;PL;1+EXCL;PST;ACT
pəktiroː	pəktiroːwunmə	V;ACC;DEF;FIN;IND;PL;1+EXCL;ACT
maluːgida	maluːgidatkiː	N;ALL;SG
bulta	bultan	N;NOM;SG;PSS3S
ďaďa	ďaďaji	N;NOM;SG;PSS1S
umukoːn	umukoːn	ADJ
jakut	jakut	N;NOM;SG
haktira	haktirallən	V;FIN;IND;SG;3;PST;ACT
bagdama	bagdama	ADJ
ila	ilatt͡ʃikaldu	V;DUR;IPFV;FIN;IMP;PL;2;ACT
ďawa	ďawamt͡ʃaw	V;FIN;COND;SG;1;ACT
bi	bihip	V;FIN;IND;PL;1+INCL;PST;ACT
ərupt͡ʃu	ərupt͡ʃujə	ADJ;ACC;INDF
hamaːn	hamaːnmə	N;ACC;DEF;SG
ďugani	ďuganiduː	N;DAT;SG
pəktiron	pəktironďəŋoːs	V;FIN;IND;SG;2;FUT;ACT
biraja	birajalwə	N;ACC;DEF;PL
bi	biďət͡ʃoːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST;ACT
mikt͡ʃan	mikt͡ʃanən	V;FIN;IND;SG;3;PST;ACT
varənjə	varənjəwa	N;ACC;DEF;SG
abet	abet	N;NOM;SG
tugəɲiː	tugəɲiː	N;NOM;SG
dəγi	dəγiktiːt͡ʃoːn	V;FIN;IND;SG;3;PST;ACT
hokto	hoktowom	N;ACC;DEF;SG;PSS1S
suːləmə	suːləmətin	ADJ;PSS3P
ilkəːɲ	ilkəːɲďənəːl	V;IPFV;FIN;IND;PL;ACT
əvənkiju	əvənkiju	N;NOM;SG
turaːmi	turaːmiwa	N;ACC;DEF;SG
baka	bakaďaŋaːw	V;FIN;IND;SG;1;FUT;ACT
paśolok	paśoloktulaː	N;TERM;SG
əɲiːŋəhə	əɲiːŋəhəw	N;NOM;SG;1
doːldiː	doːldiːttən	V;DUR;FIN;IND;SG;3;PST;ACT
uśitnaː	uśitnaːhit͡ʃaːw	V;SEMEL;FIN;IND;SG;1;PST;ACT
ďukt͡ʃa	ďukt͡ʃalaːn	N;TERM;SG;PSS3S
uŋku	uŋkutt͡ʃən	V;DUR;FIN;IND;SG;3;FUT+IMMED;ACT
kalhos	kalhos	N;NOM;SG
hiγi	hiγilim	V;FIN;IND;SG;1;PST;ACT
kuŋakaːr	kuŋakaːr	N;NOM;SG
ďə	ďəmuːďəm	V;IPFV;FIN;IND;SG;1;PRS;ACT
t͡ʃenokoːn	t͡ʃenokoːn	N;NOM;SG
nikalajəvit͡ʃ	nikalajəvit͡ʃ	N;NOM;SG
koːtuj	koːtuj	N;NOM;SG
miri	miriśoːn	V;FIN;IND;SG;3;PST;ACT
bəjətkon	bəjətkon	N;NOM;SG
gus	gus	N;NOM;SG
iɲ	iɲďiśoːn	V;IPFV;FIN;IND;SG;3;PST;ACT
amtil	amtilwi	N;NOM;SG;PSS1S
saːtira	saːtirawa	N;ACC;DEF;SG
irgiśi	irgiśi	N;NOM;SG
tirə	tirəďərə	V;FIN;IND;PL;3;FUT+IMMED;ACT
ilə	iləlduː	N;DAT;PL
inə	inəŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
nulgi	nulgisinə	V;SEMEL;FIN;IND;PL;3;ACT
ďumi	ďumilduː	N;DAT;PL
hərgiː	hərgiːn	N;NOM;SG;PSS3S
powar	powarďaŋkiːkiːw	V;IPFV;FIN;IND;SG;1;PST+RMT;ACT
golo	golowo	N;ACC;DEF;SG
hukuləː	hukuləːďirən	V;IPFV;FIN;IND;SG;3;PRS;ACT
ɲəmuləmɲi	ɲəmuləmɲihəl	N;NOM;PL
abdun	abdundukki	N;ABL;SG;PSSRS
pəktirəːwuni	pəktirəːwunin	N;NOM;SG;PSS3S
ir	irduk	N;ABL;SG
ihə	ihəldulaː	N;TERM;PL
tuksaː	tuksaːktaďaŋkiːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST+RMT;ACT
oː	oːdan	V;FIN;IND;SG;3;PST;ACT
pol	polwa	N;ACC;DEF;SG
əmukin	əmukin	ADJ
hutə	hutəw	N;NOM;SG;PSS1S
hawal	hawalďaŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
hurunən	hurunənmə	N;ACC;DEF;SG
əmə	əməďin	V;FIN;IND;SG;3;FUT+IMMED;ACT
goro	gorowoː	N;ACC;DEF;SG
hargi	hargiltiki	N;ALL;PL
amkin	amkin	N;NOM;SG
hulakiːkuːn	hulakiːkuːn	N;NOM;SG
təďoː	təďoː	N;NOM;SG
ahiː	ahiːwan	N;ACC;DEF;SG;PSS3S
noː	noːŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
guluwun	guluwundulaːwər	N;TERM;SG;PSSRP
ďadaŋi	ďadaŋilduː	N;DAT;PL
hutə	hutəlduːji	N;DAT;PL;PSSRS
hogdiŋo	hogdiŋol	ADJ;PL
luk	luktawun	V;FIN;IND;PL;1+EXCL;PST;ACT
nulgiːmdə	nulgiːmdətin	N;NOM;SG;PSS3P
inmərukkoːn	inmərukkoːnmi	N;SG;PSSRS+ACC
kiki	kikisinən	V;SEMEL;FIN;IND;SG;3;PST;ACT
dili	diliw	N;NOM;SG;PSS1S
iɲ	iɲďəŋkitin	V;IPFV;FIN;IND;PL;3;PST+RMT;ACT
olromi	olromidərə	V;IPFV;FIN;IND;PL;3;PRS;ACT
guluwun	guluwundulaː	N;TERM;SG
huru	huruŋnərəw	V;HAB;FIN;IND;PL;1+EXCL;PST;ACT
ďawa	ďawaďap	V;IPFV;FIN;IND;PL;1+INCL;PRS;ACT
tajmen	tajmenduk	N;ABL;SG
art͡ʃa	art͡ʃaran	V;FIN;IND;SG;3;PST;ACT
ərjokloː	ərjokloː	N;NOM;SG
swaďba	swaďbalďap	V;FIN;IND;PL;1+INCL;FUT+IMMED;ACT
daːr	daːrrəw	V;FIN;IND;PL;1+EXCL;PST;ACT
ə	ət͡ʃəw	V;FIN;IND;PL;1+EXCL;PST;ACT
ďapka	ďapkatkiːn	N;ALL;SG;PSS3S
təpkə	təpkəliŋkiːn	V;FIN;IND;SG;3;PST+RMT;ACT
hutəkoː	hutəkoːrwun	N;NOM;PL;PSS1PE
duwukiː	duwukiːwan	N;ACC;DEF;SG;PSS3S
əɲiː	əɲiːm	N;NOM;SG;PSS1S
bi	bisoːw	V;FIN;IND;SG;1;PST;ACT
amin	aminnunin	N;COM;SG;PSS3S
liʒi	liʒi	N;NOM;SG
dolboltonə	dolboltonəduləː	N;TERM;SG
huru	huruwrən	V;FIN;IND;SG;3;PST;ACT
pəktəroni	pəktəroniŋnəndə	V;HAB;FIN;IND;SG;2;PST;ACT
gala	gala	N;NOM;SG
gə	gəduː	N;DAT;SG
bi	biśim	V;FIN;IND;SG;1;PST;ACT
itiγaː	itiγaːt͡ʃawun	V;FIN;IND;PL;1+EXCL;PST;ACT
akini	akinin	N;NOM;SG;PSS3S
əldun	əldun	N;NOM;SG
uŋku	uŋkuďan	V;FIN;IND;SG;3;PRS;ACT
dəγi	dəγillə	V;FIN;IND;PL;3;PST;ACT
bolʃoj	bolʃoj	N;NOM;SG
doːldiː	doːldiːrəw	V;FIN;IND;PL;1+EXCL;PST;ACT
ənəli	ənəliwrə	V;FIN;IND;ACT
aki	akim	N;NOM;SG;PSS1S
amaːkaːtkan	amaːkaːtkanduk	N;ABL;SG
əŋəhiː	əŋəhiːjəs	N;ACC;INDF;SG;PSS2S
həkuːhiː	həkuːhiːt	N;INS;SG
ila	ilaśiŋkiːn	V;FIN;IND;SG;3;PST+RMT;ACT
o	oďara	V;IPFV;FIN;IND;PL;3;FUT+IMMED;ACT
oron	oronmotin	N;ACC;DEF;SG;PSS3P
prədukt	prəduktilwa	N;ACC;DEF;PL
alba	albaŋnam	V;HAB;FIN;IND;SG;1;PST;ACT
tatar	tatarwən	N;ACC;DEF;SG;PSS3S
moːtiːtkoːn	moːtiːtkoːnmə	N;ACC;DEF;SG
śirəktə	śirəktəlwi	N;PL;PSSRS+ACC
o	omə	V;FIN;IND;SG;1;PST;ACT
amkin	amkinduː	N;DAT;SG
tolgoki	tolgokil	N;NOM;PL
bə	bə	N;NOM;SG
bi	bit͡ʃow	V;FIN;IND;SG;1;PST;ACT
warak	warak	N;NOM;SG
hulakiː	hulakiːwa	N;ACC;DEF;SG
uďa	uďalwatin	N;ACC;DEF;PL;PSS3P
ganalt͡ʃi	ganalt͡ʃi	N;NOM;SG
biraja	birajawa	N;ACC;DEF;SG
təti	tətiwďəŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
goγo	goγoldə	V;FIN;IND;PL;3;PST;ACT
ďawut͡ʃa	ďawut͡ʃaďaŋkiːn	V;IPFV;FIN;IND;SG;3;PST+RMT;ACT
poːta	poːtalwər	N;PL;PSSRP+ACC
kuŋakan	kuŋakannun	N;COM;SG
oː	oːlďan	V;FIN;IND;SG;3;FUT+IMMED;ACT
baka	bakanam	V;FIN;IND;SG;1;PST;ACT
uďa	uďalwa	N;ACC;DEF;PL
ə	əkallu	V;FIN;IMP;PL;2;ACT
ɲiďela	ɲiďela	N;NOM;SG
spit͡ʃka	spit͡ʃkawa	N;ACC;DEF;SG
jigorəwiʃ	jigorəwiʃ	N;NOM;SG
ogdokoː	ogdokoːlowor	N;ACC;INDF;PL;PSSRP
əməːn	əməːnmurəw	V;FIN;IND;PL;1+EXCL;PST;PASS
ollomoː	ollomoːhinuŋkiːwun	V;SEMEL;FIN;IND;PL;1+EXCL;PST+RMT;ACT
ŋənə	ŋənəśoːw	V;FIN;IND;SG;1;PST;ACT
ďoni	ďoniŋnəm	V;HAB;FIN;IND;SG;1;PST;ACT
vərtalot	vərtalot	N;NOM;SG
hamɲiː	hamɲiːro	N;ACC;INDF;PL
tuksa	tuksahinəwun	V;SEMEL;FIN;IND;PL;1+EXCL;PST;ACT
ilanma	ilanma	ADJ
muː	muːduː	N;DAT;SG
ədi	ədinunmi	N;COM;SG;PSSRS
ŋənə	ŋənəwrə	V;FIN;IND;PST;PASS
ďawut͡ʃa	ďawut͡ʃaďaŋkiːtin	V;IPFV;FIN;IND;PL;3;PST+RMT;ACT
ədin	ədin	N;NOM;SG
ďəw	ďəwrə	N;NOM;SG
uldiː	uldiːďan	V;IPFV;FIN;IND;SG;3;ACT
bargidaː	bargidaːdulin	N;PROL;SG;PSS3S
kormeː	kormeːdukin	N;ABL;SG;PSS3S
soliːloː	soliːloː	N;NOM;SG
oː	oːttan	V;FIN;IND;SG;3;PST;ACT
du	dutin	N;NOM;SG;PSS3P
duku	dukuŋkiːtin	V;FIN;IND;PL;3;PST+RMT;ACT
haŋkə	haŋkəlwər	N;NOM;PL;PSSRP
o	osoːn	V;FIN;IND;SG;3;PST;ACT
ikoː	ikoːďət͡ʃəːn	V;IPFV;FIN;IND;SG;3;PST;ACT
oro	ororbo	N;ACC;DEF;PL
jaŋgu	jaŋgulda	V;FIN;IND;PL;3;PST;ACT
ollomo	ollomosinaw	V;SEMEL;FIN;IND;PL;1+EXCL;PST;ACT
oron	oronmi	N;NOM;SG;PSSRS
ətə	ətərəw	V;FIN;IND;PL;1+EXCL;FUT+IMMED;ACT
muːkoːn	muːkoːnďi	N;INS;SG
waː	waːttən	V;FIN;IND;SG;3;PST;ACT
naptara	naptarara	V;FIN;IND;PL;3;PST;ACT
tukti	tuktirən	V;FIN;IND;SG;3;PST;ACT
nimɲaːkaːn	nimɲaːkaːnmə	N;ACC;DEF;SG
bi	bisoːn	V;FIN;IND;SG;3;PST;ACT
əmə	əməlləw	V;FIN;IND;PL;1+EXCL;PST;ACT
maluː	maluːduː	N;DAT;SG
hoγorkiː	hoγorkiːliː	N;PROL;SG
baji	bajilka	ADJ;PL
jewgenija	jewgenija	N;NOM;SG
uγut͡ʃak	uγut͡ʃakkər	N;NOM;SG;PSSRP
əwiːwun	əwiːwun	N;NOM;SG
gorot	gorottulaː	N;TERM;SG
o	oŋkiːwun	V;FIN;IND;PL;1+EXCL;PST+RMT;ACT
dulinma	dulinman	ADJ;PSS3S
ďəptilə	ďəptiləlwə	N;ACC;DEF;PL
hukti	huktiwuhinəm	V;SEMEL;FIN;IND;SG;1;PST;ACT
gu	gut͡ʃoːn	V;FIN;IND;SG;3;PST;ACT
ďələki	ďələkilwə	N;ACC;DEF;PL
lawaːdaːp	lawaːdaːpďərən	V;IPFV;FIN;IND;SG;3;PRS;ACT
abat͡ʃiː	abat͡ʃiːwa	N;ACC;DEF;SG
talu	taluwa	N;ACC;DEF;SG
ďaldaː	ďaldaːm	V;FIN;IND;SG;1;PST;ACT
in	inďəmt͡ʃəl	V;IPFV;FIN;COND;PL;3;ACT
tələ	tələlďəŋəːw	V;FIN;IND;SG;1;FUT;ACT
ahiː	ahiːŋiː	N;NOM;SG
nidim	nidimduː	N;DAT;SG
vnis	vnistiki	N;ALL;SG
gənnəː	gənnəːrən	V;FIN;IND;SG;3;PST;ACT
ďəgdəː	ďəgdəː	N;NOM;SG
krasnojarska	krasnojarskalaː	N;TERM;SG
əwədit	əwədit	ADJ
ə	əʃən	V;FIN;IND;SG;3;PST;ACT
oːha	oːhaŋiltin	N;NOM;PL;ALN+PSS3P
iɲ	iɲďəkələdu	V;IPFV;FIN;IMP;PL;2;ACT
bi	bimt͡ʃes	V;FIN;COND;SG;2;ACT
komojəmi	komojəmiwə	N;ACC;DEF;SG
tirga	tirgaldan	V;FIN;IND;SG;3;PST;ACT
śiruː	śiruːw	N;NOM;SG;PSS1S
təγə	təγətkəllu	V;DUR;FIN;IMP;PL;2;ACT
holiːləː	holiːləː	N;NOM;SG
ə	ə	N;NOM;SG
waːnaː	waːnaːhinnə	V;SEMEL;FIN;IND;SG;2;PST;ACT
ɲikə	ɲikəsoːs	V;FIN;IND;SG;2;PST;ACT
ə	ərə	V;FIN;IND;PL;3;PST;ACT
gun	gunən	V;FIN;IND;SG;3;PST;ACT
pesoki	pesokit	N;INS;SG
ulgut͡ʃoː	ulgut͡ʃoːmott͡ʃit͡ʃoːwun	V;DUR;FIN;IND;PL;1+EXCL;PST;RECP;ACT
hawal	hawaldasaːn	V;IPFV;FIN;IND;SG;3;PST;ACT
makarit͡ʃ	makarit͡ʃ	N;NOM;SG
ə	ətoːn	V;FIN;IND;SG;3;FUT+IMMED;ACT
ollomiːmniː	ollomiːmniːl	V;FIN;IND;PL;ACT
kujumbə	kujumbəduː	N;DAT;SG
hiśi	hiśihinən	V;SEMEL;FIN;IND;SG;3;PST;ACT
uwaʒaśi	uwaʒaśiŋkiːtin	V;FIN;IND;PL;3;PST+RMT;ACT
ir	irtikiː	N;ALL;SG
metər	metər	N;NOM;SG
gənnə	gənnəm	V;FIN;IND;SG;1;PST;ACT
it͡ʃə	it͡ʃətt͡ʃərəw	V;DUR;IPFV;FIN;IND;SG;1;PRS;ACT
uliː	uliːďəŋkiːwun	V;IPFV;FIN;IND;PL;1+EXCL;PST+RMT;ACT
ďu	ďulbi	N;NOM;PL;PSS1S
