servî	servìs	V;IND;PL;2;PRS
segnâ	segni	V;IND;SG;1;PRS
scjadê	scjadìn	V;IND;PL;1;PRS
malfâ	malfasarès	V;COND;SG;3
tentâ	tentavis	V;IPFV;IND;PL;2;PST
trivelâ	trivelarìn	V;IND;PL;1;FUT
soflâ	soflavis	V;IPFV;IND;SG;2;PST
scjaldâ	scjaldis	V;IND;SG;2;PRS
convidâ	convidarà	V;IND;SG;3;FUT
armâ	armavi	V;IPFV;IND;SG;1;PST
cenâ	cenaressin	V;COND;PL;3
menâ	menave	V;IPFV;IND;SG;3;PST
vendemâ	vendemaris	V;PFV;IND;PL;2;PST
supâ	suparìn	V;IND;PL;1;FUT
bussâ	bussavin	V;IPFV;IND;PL;3;PST
scurtâ	scurtavis	V;IPFV;IND;PL;2;PST
scrivi	scrivevi	V;IPFV;IND;SG;1;PST
dâ	davis	V;IPFV;IND;SG;2;PST
supâ	supàs	V;IPFV;SBJV;SG;1;PST
fassâ	fassaran	V;IND;PL;3;FUT
svolâ	svolaressin	V;COND;PL;1
spudâ	spudin	V;IND;PL;3;PRS
lâ	larès	V;COND;SG;1
vendemâ	vendemassin	V;IPFV;SBJV;PL;3;PST
lusî	lusiressis	V;COND;SG;2
parê	pararès	V;COND;SG;3
viodi	viodaressin	V;COND;PL;3
lassâ	lassin	V;SBJV;PL;3;PRS
menaçâ	menaçassin	V;IPFV;SBJV;PL;3;PST
netâ	nete	V;IND;SG;3;PRS
sangloçâ	sangloci	V;IND;SG;1;PRS
tiessi	tiessevis	V;IPFV;IND;SG;2;PST
judâ	judis	V;SBJV;SG;2;PRS
bagnâ	bagnâ	V;NFIN
sudâ	sude	V;IMP;SG;2
finî	finirès	V;COND;SG;3
cori	cori	V;SBJV;SG;1;PRS
spaurî	spaurive	V;IPFV;IND;SG;3;PST
salâ	salìn	V;SBJV;PL;1;PRS
netâ	netìn	V;SBJV;PL;1;PRS
lusî	lusirès	V;COND;SG;3
dî	disevin	V;IPFV;IND;PL;3;PST
cenâ	cenìn	V;IND;PL;1;PRS
salvâ	salvarai	V;IND;SG;1;FUT
tonâ	tonaressis	V;COND;SG;2
glaçâ	glaçavin	V;IPFV;IND;PL;3;PST
messedâ	messedâ	V;NFIN
fumâ	fumaris	V;PFV;IND;SG;2;PST
dreçâ	dreçavi	V;IPFV;IND;SG;1;PST
començâ	començaran	V;IND;PL;3;FUT
sanganâ	sanganassin	V;IPFV;SBJV;PL;3;PST
scjampâ	scjampe	V;IND;SG;3;PRS
florî	floriris	V;PFV;IND;PL;2;PST
cjatâ	cjatais	V;IND;PL;2;PRS
cenâ	cenarès	V;COND;SG;1
florî	florissis	V;IND;SG;2;PRS
alçâ	alci	V;SBJV;SG;1;PRS
dâ	davi	V;IPFV;IND;SG;1;PST
semenâ	semeni	V;SBJV;SG;1;PRS
contâ	contìn	V;SBJV;PL;1;PRS
trivelâ	trivelavis	V;IPFV;IND;PL;2;PST
semenâ	semenìn	V;IMP;PL;1
cjastrâ	cjastravin	V;IPFV;IND;PL;3;PST
tasê	tasaei	V;PFV;IND;SG;1;PST
amâ	amaressis	V;COND;SG;2
comandâ	comandarès	V;COND;SG;3
pesâ	pesavin	V;IPFV;IND;PL;3;PST
cori	corarès	V;COND;SG;3
perî	perivin	V;IPFV;IND;PL;3;PST
amâ	amarês	V;IND;PL;2;FUT
comprâ	comprarès	V;COND;SG;3
contâ	contìn	V;IMP;PL;1
petenâ	petenâ	V;NFIN
comprâ	compravin	V;IPFV;IND;PL;1;PST
dreçâ	drecis	V;IND;SG;2;PRS
cenâ	cenais	V;IND;PL;2;PRS
pensâ	pensai	V;PFV;IND;SG;1;PST
sunâ	sunàs	V;IPFV;SBJV;SG;1;PST
discjantâ	discjantìn	V;IMP;PL;1
soflâ	soflis	V;IND;SG;2;PRS
cuietâ	cuietassin	V;IPFV;SBJV;PL;1;PST
finî	finiressis	V;COND;PL;2
vê	varês	V;IND;PL;2;FUT
discjantâ	discjantàs	V;IPFV;SBJV;SG;3;PST
balâ	balarês	V;IND;PL;2;FUT
tirâ	tiravin	V;IPFV;IND;PL;1;PST
parê	pâreve	V;IPFV;IND;SG;3;PST
menaçâ	menaçarês	V;IND;PL;2;FUT
vistî	vistìs	V;IMP;SG;2
lavorâ	lavoraressis	V;COND;SG;2
scovâ	scovait	V;IMP;PL;2
ordenâ	ordenassis	V;IPFV;SBJV;SG;2;PST
scrivi	scrivêt	V;IMP;PL;2
mertâ	mertaran	V;IND;PL;3;FUT
trimulâ	trimulìn	V;IMP;PL;1
contâ	contarìn	V;IND;PL;1;FUT
scrivi	scrivarês	V;IND;PL;2;FUT
jentrâ	jentre	V;IMP;SG;2
ardi	arderis	V;PFV;IND;PL;2;PST
tosâ	tosà	V;PFV;IND;SG;3;PST
netâ	netìn	V;IND;PL;1;PRS
zunâ	zunìn	V;IND;PL;1;PRS
scurtâ	scurtàs	V;IPFV;SBJV;SG;1;PST
convidâ	convidassin	V;IPFV;SBJV;PL;3;PST
amâ	ame	V;IND;SG;3;PRS
amâ	amavis	V;IPFV;IND;PL;2;PST
copâ	coparìn	V;IND;PL;1;FUT
invidâ	invidais	V;SBJV;PL;2;PRS
temê	temeris	V;PFV;IND;PL;2;PST
ubidî	ubidîs	V;SBJV;PL;2;PRS
tirâ	tirarìn	V;IND;PL;1;FUT
netâ	neti	V;SBJV;SG;3;PRS
mertâ	mertarâs	V;IND;SG;2;FUT
sunâ	sunavin	V;IPFV;IND;PL;3;PST
maridâ	maridarês	V;IND;PL;2;FUT
convidâ	convidin	V;SBJV;PL;3;PRS
viodi	viodarà	V;IND;SG;3;FUT
starnudâ	starnudavin	V;IPFV;IND;PL;1;PST
tirâ	tirâ	V;NFIN
scjaldâ	scjaldarâs	V;IND;SG;2;FUT
discjantâ	discjantâ	V;NFIN
incoronâ	incoronarin	V;PFV;IND;PL;1;PST
tiessi	tiessevin	V;IPFV;IND;PL;1;PST
tornâ	tornarês	V;IND;PL;2;FUT
comprâ	comprassis	V;IPFV;SBJV;SG;2;PST
soflâ	soflìn	V;SBJV;PL;1;PRS
glaçâ	glacìn	V;IND;PL;1;PRS
sgjavâ	sgjavin	V;SBJV;PL;3;PRS
lusî	lusìs	V;IND;SG;3;PRS
scori	scorevis	V;IPFV;IND;SG;2;PST
trivelâ	trivelìn	V;IND;PL;1;PRS
discolçâ	discolçai	V;PFV;IND;SG;1;PST
jessi	sarà	V;IND;SG;3;FUT
malfâ	malfasarà	V;IND;SG;3;FUT
viodi	viodarai	V;IND;SG;1;FUT
pelâ	pelis	V;IND;SG;2;PRS
curâ	curarai	V;IND;SG;1;FUT
dâ	dedis	V;SBJV;SG;2;PRS
jessi	sedin	V;SBJV;PL;3;PRS
spietâ	spietaressin	V;COND;PL;3
sangloçâ	sangloçarâs	V;IND;SG;2;FUT
mostrâ	mostrais	V;SBJV;PL;2;PRS
starnudâ	starnudàs	V;IPFV;SBJV;SG;1;PST
amâ	amavin	V;IPFV;IND;PL;1;PST
trimulâ	trimularâs	V;IND;SG;2;FUT
tastâ	taste	V;IMP;SG;2
spietâ	spietavin	V;IPFV;IND;PL;1;PST
sunâ	sunassis	V;IPFV;SBJV;SG;2;PST
cjalçâ	cjalçarês	V;IND;PL;2;FUT
patî	patirin	V;PFV;IND;PL;3;PST
lotâ	lotavin	V;IPFV;IND;PL;3;PST
tonâ	tonarìn	V;IND;PL;1;FUT
slançâ	slançarès	V;COND;SG;3
jentrâ	jentrìn	V;SBJV;PL;1;PRS
tonâ	tonarâs	V;IND;SG;2;FUT
olsâ	olsarà	V;IND;SG;3;FUT
rivâ	rivìn	V;SBJV;PL;1;PRS
bati	batarês	V;IND;PL;2;FUT
tastâ	tastarâs	V;IND;SG;2;FUT
spietâ	spietais	V;SBJV;PL;2;PRS
salvâ	salvìn	V;SBJV;PL;1;PRS
perî	perirês	V;IND;PL;2;FUT
copâ	coparis	V;PFV;IND;SG;2;PST
comandâ	comandarâs	V;IND;SG;2;FUT
temê	temeris	V;PFV;IND;SG;2;PST
scjadê	scjaderin	V;PFV;IND;PL;1;PST
jessi	jeri	V;IPFV;IND;SG;1;PST
ricuardâ	ricuardàs	V;IPFV;SBJV;SG;1;PST
pelâ	pelarès	V;COND;SG;3
judâ	judaran	V;IND;PL;3;FUT
judâ	judis	V;IND;SG;2;PRS
lassâ	lassaran	V;IND;PL;3;FUT
jentrâ	jentrai	V;PFV;IND;SG;1;PST
tornâ	tornàs	V;IPFV;SBJV;SG;3;PST
lagrimâ	lagrimaressis	V;COND;SG;2
curâ	curi	V;SBJV;SG;3;PRS
salvâ	salve	V;IMP;SG;2
sunâ	sunai	V;PFV;IND;SG;1;PST
levâ	levarin	V;PFV;IND;PL;3;PST
nadâ	nadassin	V;IPFV;SBJV;PL;1;PST
contâ	contis	V;IND;SG;2;PRS
scovâ	scove	V;IND;SG;3;PRS
vendi	vend	V;IND;SG;3;PRS
ardi	ardin	V;IND;PL;3;PRS
judâ	jude	V;IND;SG;3;PRS
clamâ	clamai	V;PFV;IND;SG;1;PST
cjantâ	cjantàs	V;IPFV;SBJV;SG;3;PST
sangloçâ	sangloçassin	V;IPFV;SBJV;PL;3;PST
maridâ	maridàs	V;IPFV;SBJV;SG;1;PST
trimulâ	trimulavi	V;IPFV;IND;SG;1;PST
ordenâ	ordenarà	V;IND;SG;3;FUT
meti	metaressin	V;COND;PL;3
invidâ	invide	V;IND;SG;3;PRS
scovâ	scovassis	V;IPFV;SBJV;SG;2;PST
spudâ	spudassis	V;IPFV;SBJV;PL;2;PST
tentâ	tentaressin	V;COND;PL;1
sanganâ	sanganave	V;IPFV;IND;SG;3;PST
insegnâ	insegnais	V;SBJV;PL;2;PRS
sintî	sintaran	V;IND;PL;3;FUT
cusinâ	cusinavin	V;IPFV;IND;PL;3;PST
vendemâ	vendemavin	V;IPFV;IND;PL;3;PST
unî	unìn	V;SBJV;PL;1;PRS
stralusî	stralusìn	V;SBJV;PL;1;PRS
lassâ	lassà	V;PFV;IND;SG;3;PST
inglaçâ	inglaçarês	V;IND;PL;2;FUT
dî	dìs	V;IMP;SG;2
scjampâ	scjamparès	V;COND;SG;1
sierâ	sierarès	V;COND;SG;3
ardi	ard	V;IND;SG;1;PRS
supâ	supis	V;SBJV;SG;2;PRS
patî	patìs	V;IND;SG;1;PRS
jentrâ	jentraressin	V;COND;PL;1
sierâ	sieraressis	V;COND;PL;2
remâ	reme	V;IMP;SG;2
starnudâ	starnudassis	V;IPFV;SBJV;SG;2;PST
tentâ	tentis	V;SBJV;SG;2;PRS
cjaçâ	cjaçassis	V;IPFV;SBJV;PL;2;PST
cjastrâ	cjastraris	V;PFV;IND;SG;2;PST
scjadê	scjadevin	V;IPFV;IND;PL;3;PST
sangloçâ	sangloçaressin	V;COND;PL;1
zontâ	zontis	V;IND;SG;2;PRS
vê	vessin	V;IPFV;SBJV;PL;1;PST
plasê	plasarès	V;COND;SG;3
començâ	comencis	V;IND;SG;2;PRS
cenâ	cenaris	V;PFV;IND;PL;2;PST
meti	meti	V;SBJV;SG;1;PRS
vistî	vistii	V;PFV;IND;SG;1;PST
netâ	netà	V;PFV;IND;SG;3;PST
saludâ	saludarin	V;PFV;IND;PL;3;PST
puartâ	puartais	V;IND;PL;2;PRS
tiessi	tiessin	V;IND;PL;3;PRS
vivi	viv	V;IND;SG;1;PRS
comandâ	comande	V;IND;SG;3;PRS
tastâ	tastin	V;IND;PL;3;PRS
ricuardâ	ricuardi	V;SBJV;SG;1;PRS
costâ	costaris	V;PFV;IND;PL;2;PST
crevâ	crevassin	V;IPFV;SBJV;PL;3;PST
convidâ	convidi	V;IND;SG;1;PRS
bussâ	bussà	V;PFV;IND;SG;3;PST
pesâ	pesìn	V;IMP;PL;1
dî	disessis	V;IPFV;SBJV;PL;2;PST
copâ	cope	V;IND;SG;3;PRS
olsâ	olsarès	V;COND;SG;1
sposâ	sposarin	V;PFV;IND;PL;1;PST
vendi	vendei	V;PFV;IND;SG;1;PST
concuistâ	concuiste	V;IND;SG;3;PRS
incoronâ	incoronais	V;IND;PL;2;PRS
valê	valaressis	V;COND;PL;2
puartâ	puartâ	V;NFIN
crodi	crodès	V;IPFV;SBJV;SG;1;PST
durmî	durmivin	V;IPFV;IND;PL;3;PST
meti	metarês	V;IND;PL;2;FUT
lassâ	lassavis	V;IPFV;IND;SG;2;PST
jessî	jessi	V;SBJV;SG;1;PRS
tonâ	tonai	V;PFV;IND;SG;1;PST
domandâ	domandassis	V;IPFV;SBJV;PL;2;PST
nadâ	nadais	V;SBJV;PL;2;PRS
nadâ	nadassin	V;IPFV;SBJV;PL;3;PST
mostrâ	mostraran	V;IND;PL;3;FUT
trivelâ	trivelarin	V;PFV;IND;PL;1;PST
cori	coreris	V;PFV;IND;PL;2;PST
dî	diserin	V;PFV;IND;PL;1;PST
costâ	costarìn	V;IND;PL;1;FUT
zunâ	zunaressis	V;COND;SG;2
supâ	supavis	V;IPFV;IND;SG;2;PST
cjapâ	cjapin	V;IND;PL;3;PRS
clamâ	clami	V;SBJV;SG;1;PRS
vendi	vendis	V;SBJV;SG;2;PRS
scovâ	scovìn	V;IMP;PL;1
copâ	copassis	V;IPFV;SBJV;SG;2;PST
spietâ	spietais	V;IND;PL;2;PRS
tentâ	tentassin	V;IPFV;SBJV;PL;3;PST
amâ	amaris	V;PFV;IND;SG;2;PST
pelâ	pelàs	V;IPFV;SBJV;SG;3;PST
infassâ	infasse	V;IND;SG;3;PRS
cenâ	cenavis	V;IPFV;IND;SG;2;PST
misurâ	misurìn	V;SBJV;PL;1;PRS
fevelâ	fevelin	V;SBJV;PL;3;PRS
vistî	vistirai	V;IND;SG;1;FUT
durmî	durmaran	V;IND;PL;3;FUT
perî	perìs	V;IPFV;SBJV;SG;1;PST
comandâ	comandin	V;SBJV;PL;3;PRS
urdî	urdirès	V;COND;SG;3
blestemâ	blestemavin	V;IPFV;IND;PL;3;PST
clamâ	clamavis	V;IPFV;IND;PL;2;PST
discolçâ	discolcìn	V;SBJV;PL;1;PRS
sierâ	sieravin	V;IPFV;IND;PL;1;PST
menaçâ	menaçave	V;IPFV;IND;SG;3;PST
glaçâ	glaçai	V;PFV;IND;SG;1;PST
cjastrâ	cjastraressis	V;COND;PL;2
blestemâ	blestemi	V;SBJV;SG;3;PRS
sunâ	sunavi	V;IPFV;IND;SG;1;PST
suspirâ	suspiraressin	V;COND;PL;1
vê	varessis	V;COND;PL;2
spietâ	spietarà	V;IND;SG;3;FUT
bussâ	bussaressin	V;COND;PL;3
lagrimâ	lagrimâ	V;NFIN
scovâ	scovarìn	V;IND;PL;1;FUT
laudâ	laudi	V;SBJV;SG;3;PRS
copâ	copis	V;IND;SG;2;PRS
patî	patin	V;IND;PL;1;PRS
parê	paressis	V;IPFV;SBJV;SG;2;PST
temê	temessis	V;IPFV;SBJV;PL;2;PST
segnâ	segnaris	V;PFV;IND;SG;2;PST
scurtâ	scurtìn	V;IMP;PL;1
passâ	passìn	V;SBJV;PL;1;PRS
jessî	jessìs	V;IND;PL;2;PRS
fumâ	fumavin	V;IPFV;IND;PL;1;PST
salvâ	salvarès	V;COND;SG;3
urdî	urdiressis	V;COND;SG;2
glaçâ	glaçait	V;IMP;PL;2
ardi	ardês	V;SBJV;PL;2;PRS
urdî	urdissin	V;IPFV;SBJV;PL;3;PST
pecjâ	pecjaressis	V;COND;PL;2
scjadê	scjâd	V;IND;SG;1;PRS
durmî	durmarès	V;COND;SG;3
copâ	coparin	V;PFV;IND;PL;3;PST
vendi	vendeve	V;IPFV;IND;SG;3;PST
cjastrâ	cjastrin	V;SBJV;PL;3;PRS
cenâ	cenaris	V;PFV;IND;SG;2;PST
jessi	fossin	V;IPFV;SBJV;PL;3;PST
sossedâ	sossedarà	V;IND;SG;3;FUT
ubidî	ubidìs	V;IND;PL;2;PRS
costâ	costâ	V;NFIN
scjadê	scjadarìn	V;IND;PL;1;FUT
provâ	provai	V;PFV;IND;SG;1;PST
scjadê	scjadês	V;IND;PL;2;PRS
cerni	cernevin	V;IPFV;IND;PL;3;PST
spudâ	spudai	V;PFV;IND;SG;1;PST
supâ	supassin	V;IPFV;SBJV;PL;1;PST
saltâ	salte	V;IMP;SG;2
vendemâ	vendemarai	V;IND;SG;1;FUT
ferî	ferìs	V;IPFV;SBJV;SG;3;PST
discjantâ	discjantavi	V;IPFV;IND;SG;1;PST
zurâ	zurassin	V;IPFV;SBJV;PL;3;PST
sintî	sintìs	V;IPFV;SBJV;SG;1;PST
durmî	durmissin	V;IPFV;SBJV;PL;1;PST
ricuardâ	ricuardaressis	V;COND;PL;2
maridâ	maridassis	V;IPFV;SBJV;PL;2;PST
contâ	conti	V;SBJV;SG;1;PRS
fâ	fasarès	V;COND;SG;3
spudâ	spudaressis	V;COND;PL;2
segnâ	segnaran	V;IND;PL;3;FUT
trimulâ	trimulave	V;IPFV;IND;SG;3;PST
vendemâ	vendemave	V;IPFV;IND;SG;3;PST
dreçâ	dreci	V;SBJV;SG;3;PRS
urlâ	urlavin	V;IPFV;IND;PL;1;PST
rivâ	rivarâs	V;IND;SG;2;FUT
lavorâ	lavore	V;IND;SG;3;PRS
discolçâ	discolçàs	V;IPFV;SBJV;SG;1;PST
gomitâ	gomitarâs	V;IND;SG;2;FUT
ordenâ	ordenarai	V;IND;SG;1;FUT
starnudâ	starnudaris	V;PFV;IND;SG;2;PST
vendi	vendin	V;SBJV;PL;3;PRS
tasê	tasaarès	V;COND;SG;3
jevâ	jevaressin	V;COND;PL;3
slançâ	slançavis	V;IPFV;IND;PL;2;PST
enflâ	enflin	V;SBJV;PL;3;PRS
dreçâ	dreçassis	V;IPFV;SBJV;PL;2;PST
lagrimâ	lagrimavin	V;IPFV;IND;PL;1;PST
discolçâ	discolçavi	V;IPFV;IND;SG;1;PST
dâ	dassin	V;IPFV;SBJV;PL;1;PST
invidâ	invidi	V;SBJV;SG;1;PRS
puartâ	puarti	V;IND;SG;1;PRS
clamâ	clamis	V;SBJV;SG;2;PRS
pensâ	pensait	V;IMP;PL;2
costâ	costaressis	V;COND;SG;2
scori	scorevin	V;IPFV;IND;PL;1;PST
pelâ	pelavin	V;IPFV;IND;PL;1;PST
girâ	girarâs	V;IND;SG;2;FUT
gomitâ	gomitais	V;SBJV;PL;2;PRS
salvâ	salvarès	V;COND;SG;1
sentâ	sentavin	V;IPFV;IND;PL;1;PST
inglaçâ	inglaçaran	V;IND;PL;3;FUT
cuietâ	cuietaressin	V;COND;PL;1
servî	servîs	V;SBJV;PL;2;PRS
provâ	provaressin	V;COND;PL;1
mudâ	mudassin	V;IPFV;SBJV;PL;3;PST
miorâ	mioris	V;IND;SG;2;PRS
supâ	supàs	V;IPFV;SBJV;SG;3;PST
zontâ	zonte	V;IND;SG;3;PRS
provâ	provi	V;SBJV;SG;3;PRS
fumâ	fumaressis	V;COND;SG;2
finî	finivin	V;IPFV;IND;PL;1;PST
saludâ	saludi	V;SBJV;SG;3;PRS
misurâ	misurassis	V;IPFV;SBJV;PL;2;PST
vistî	vistìs	V;IND;PL;2;PRS
urdî	urdìn	V;IMP;PL;1
convidâ	convidà	V;PFV;IND;SG;3;PST
zurâ	zuri	V;SBJV;SG;3;PRS
gustâ	gustassis	V;IPFV;SBJV;PL;2;PST
sudâ	sudìn	V;SBJV;PL;1;PRS
sentâ	senti	V;IND;SG;1;PRS
remâ	remìn	V;SBJV;PL;1;PRS
laudâ	laudarin	V;PFV;IND;PL;1;PST
mertâ	merti	V;SBJV;SG;1;PRS
scrivi	scriv	V;IND;SG;3;PRS
cjapâ	cjapais	V;IND;PL;2;PRS
cusinâ	cusinarìn	V;IND;PL;1;FUT
passâ	passassis	V;IPFV;SBJV;SG;2;PST
tornâ	tornaressis	V;COND;SG;2
girâ	girassin	V;IPFV;SBJV;PL;3;PST
judâ	judais	V;IND;PL;2;PRS
scovâ	scovarin	V;PFV;IND;PL;3;PST
lavâ	lavarès	V;COND;SG;3
slançâ	slançarès	V;COND;SG;1
valê	valin	V;IND;PL;3;PRS
cjapâ	cjaparìn	V;IND;PL;1;FUT
cjalçâ	cjalçassin	V;IPFV;SBJV;PL;1;PST
comandâ	comande	V;IMP;SG;2
tasê	tasaêt	V;IMP;PL;2
clamâ	clamà	V;PFV;IND;SG;3;PST
armâ	armìn	V;SBJV;PL;1;PRS
capî	capîs	V;SBJV;PL;2;PRS
passâ	passai	V;PFV;IND;SG;1;PST
balâ	bale	V;IMP;SG;2
levâ	levi	V;SBJV;SG;1;PRS
durmî	durmiris	V;PFV;IND;SG;2;PST
trimulâ	trimulais	V;IND;PL;2;PRS
vendi	vendessis	V;IPFV;SBJV;PL;2;PST
pelâ	pelarin	V;PFV;IND;PL;3;PST
amâ	amavis	V;IPFV;IND;SG;2;PST
servî	servissis	V;IPFV;SBJV;SG;2;PST
lagrimâ	lagrimai	V;PFV;IND;SG;1;PST
gustâ	gustarâs	V;IND;SG;2;FUT
lotâ	lotarês	V;IND;PL;2;FUT
bagnâ	bagnais	V;IND;PL;2;PRS
invidâ	invidave	V;IPFV;IND;SG;3;PST
armâ	armave	V;IPFV;IND;SG;3;PST
plasê	plasevi	V;IPFV;IND;SG;1;PST
lotâ	lotarìn	V;IND;PL;1;FUT
masanâ	masanarin	V;PFV;IND;PL;1;PST
temê	temès	V;IPFV;SBJV;SG;1;PST
zunâ	zunis	V;SBJV;SG;2;PRS
jessi	jere	V;IPFV;IND;SG;3;PST
cerni	cernessis	V;IPFV;SBJV;PL;2;PST
discjantâ	discjantin	V;SBJV;PL;3;PRS
tasê	tasaaressis	V;COND;PL;2
sossedâ	sossedìn	V;IND;PL;1;PRS
dâ	dassin	V;IPFV;SBJV;PL;3;PST
jessî	jessarès	V;COND;SG;1
sentâ	sentaressis	V;COND;SG;2
durmî	durmìn	V;IMP;PL;1
temê	temevin	V;IPFV;IND;PL;1;PST
cjalçâ	cjalcìn	V;IMP;PL;1
scoltâ	scoltaressin	V;COND;PL;3
fâ	fasarês	V;IND;PL;2;FUT
jentrâ	jentrarà	V;IND;SG;3;FUT
semenâ	semenai	V;PFV;IND;SG;1;PST
sintî	sintìn	V;SBJV;PL;1;PRS
cjatâ	cjatin	V;IND;PL;3;PRS
servî	servissis	V;IND;SG;2;PRS
menaçâ	menaçarin	V;PFV;IND;PL;1;PST
invidâ	invidaressis	V;COND;SG;2
starnudâ	starnudi	V;SBJV;SG;3;PRS
spietâ	spietavis	V;IPFV;IND;SG;2;PST
fâ	fasês	V;IND;PL;2;PRS
fâ	fasìn	V;IMP;PL;1
enflâ	enflarin	V;PFV;IND;PL;3;PST
discolçâ	discolçarès	V;COND;SG;3
tentâ	tentaressin	V;COND;PL;3
balâ	balassin	V;IPFV;SBJV;PL;3;PST
scrivi	scriveris	V;PFV;IND;PL;2;PST
valê	valìn	V;IND;PL;1;PRS
temê	temês	V;SBJV;PL;2;PRS
masanâ	masanìn	V;IMP;PL;1
plasê	plasarês	V;IND;PL;2;FUT
scori	scorìn	V;IMP;PL;1
tonâ	tonis	V;IND;SG;2;PRS
unî	unirai	V;IND;SG;1;FUT
fumâ	fumìn	V;IMP;PL;1
misurâ	misuri	V;SBJV;SG;1;PRS
cenâ	cenarà	V;IND;SG;3;FUT
masanâ	masane	V;IMP;SG;2
blestemâ	blestemìn	V;SBJV;PL;1;PRS
sossedâ	sossedi	V;SBJV;SG;3;PRS
stralusî	stralusìs	V;IND;SG;1;PRS
trimulâ	trimularai	V;IND;SG;1;FUT
scori	scori	V;SBJV;SG;3;PRS
miorâ	miori	V;SBJV;SG;1;PRS
viodi	viodaressis	V;COND;SG;2
durmî	durmarai	V;IND;SG;1;FUT
malfâ	malfasin	V;SBJV;PL;3;PRS
scoltâ	scoltavin	V;IPFV;IND;PL;1;PST
ordenâ	ordenarìn	V;IND;PL;1;FUT
arâ	araris	V;PFV;IND;SG;2;PST
svolâ	svolarai	V;IND;SG;1;FUT
fassâ	fassi	V;IND;SG;1;PRS
bati	batis	V;IND;SG;2;PRS
scoltâ	scoltin	V;SBJV;PL;3;PRS
scjadê	scjâdeve	V;IPFV;IND;SG;3;PST
sierâ	sieravi	V;IPFV;IND;SG;1;PST
tasê	tasais	V;IND;SG;2;PRS
dî	disin	V;SBJV;PL;3;PRS
sudâ	sudaran	V;IND;PL;3;FUT
cjapâ	cjapà	V;PFV;IND;SG;3;PST
armâ	armais	V;SBJV;PL;2;PRS
puartâ	puartaris	V;PFV;IND;PL;2;PST
sgjavâ	sgjavaris	V;PFV;IND;SG;2;PST
tornâ	tornis	V;SBJV;SG;2;PRS
discjantâ	discjantavin	V;IPFV;IND;PL;1;PST
suspirâ	suspirassis	V;IPFV;SBJV;SG;2;PST
curâ	curarà	V;IND;SG;3;FUT
lusî	lusissin	V;IPFV;SBJV;PL;3;PST
començâ	comenci	V;SBJV;SG;3;PRS
mostrâ	mostràs	V;IPFV;SBJV;SG;1;PST
puartâ	puartavi	V;IPFV;IND;SG;1;PST
cenâ	cenìn	V;SBJV;PL;1;PRS
tirâ	tirarès	V;COND;SG;1
scovâ	scovi	V;SBJV;SG;3;PRS
scurtâ	scurtaressin	V;COND;PL;3
florî	florivin	V;IPFV;IND;PL;3;PST
scori	scorei	V;PFV;IND;SG;1;PST
perî	perìs	V;IMP;SG;2
ferî	ferissis	V;IPFV;SBJV;PL;2;PST
vendi	vendarai	V;IND;SG;1;FUT
spudâ	spudis	V;IND;SG;2;PRS
copâ	coparà	V;IND;SG;3;FUT
rivâ	rivìn	V;IND;PL;1;PRS
sentâ	sentin	V;IND;PL;3;PRS
scrivi	scriv	V;IND;SG;1;PRS
cjalçâ	cjalcìn	V;SBJV;PL;1;PRS
costâ	costaran	V;IND;PL;3;FUT
cerni	cerni	V;SBJV;SG;1;PRS
fassâ	fassis	V;IND;SG;2;PRS
scori	scoris	V;IND;SG;2;PRS
cenâ	cene	V;IND;SG;3;PRS
sangloçâ	sangloci	V;SBJV;SG;1;PRS
salâ	salassin	V;IPFV;SBJV;PL;1;PST
scjadê	scjâdès	V;IPFV;SBJV;SG;3;PST
pelâ	pelaris	V;PFV;IND;PL;2;PST
armâ	armaran	V;IND;PL;3;FUT
girâ	girâ	V;NFIN
cusinâ	cusinarês	V;IND;PL;2;FUT
jessî	jessarès	V;COND;SG;3
gomitâ	gomitai	V;PFV;IND;SG;1;PST
inglaçâ	inglacìn	V;IND;PL;1;PRS
alçâ	alçavi	V;IPFV;IND;SG;1;PST
fâ	fasìn	V;IND;PL;1;PRS
urlâ	urlai	V;PFV;IND;SG;1;PST
costâ	costavin	V;IPFV;IND;PL;3;PST
lotâ	lotaris	V;PFV;IND;PL;2;PST
crevâ	crevave	V;IPFV;IND;SG;3;PST
tonâ	tonàs	V;IPFV;SBJV;SG;3;PST
jevâ	jevais	V;SBJV;PL;2;PRS
gjavâ	gjavai	V;PFV;IND;SG;1;PST
jessî	jessissis	V;IPFV;SBJV;PL;2;PST
patî	pative	V;IPFV;IND;SG;3;PST
pesâ	pesave	V;IPFV;IND;SG;3;PST
cjalçâ	cjalçarin	V;PFV;IND;PL;1;PST
menaçâ	menacin	V;IND;PL;3;PRS
sierâ	sierà	V;PFV;IND;SG;3;PST
tasê	tasaessin	V;IPFV;SBJV;PL;1;PST
domandâ	domandarin	V;PFV;IND;PL;1;PST
sunâ	sunais	V;SBJV;PL;2;PRS
sudâ	sudaressin	V;COND;PL;3
fassâ	fassà	V;PFV;IND;SG;3;PST
crevâ	crevarâs	V;IND;SG;2;FUT
insegnâ	insegne	V;IMP;SG;2
bagnâ	bagni	V;SBJV;SG;3;PRS
discolçâ	discolçaressis	V;COND;SG;2
slançâ	slançarà	V;IND;SG;3;FUT
bati	bati	V;NFIN
discolçâ	discolçave	V;IPFV;IND;SG;3;PST
saltâ	saltaris	V;PFV;IND;SG;2;PST
saltâ	saltaressin	V;COND;PL;1
perî	periris	V;PFV;IND;SG;2;PST
gomitâ	gomitavin	V;IPFV;IND;PL;3;PST
ubidî	ubidiressis	V;COND;SG;2
vistî	vistiressin	V;COND;PL;1
fevelâ	fevelìn	V;IMP;PL;1
supâ	supassis	V;IPFV;SBJV;SG;2;PST
sintî	sint	V;IND;SG;1;PRS
lusî	lusirin	V;PFV;IND;PL;1;PST
maridâ	maridâ	V;NFIN
glaçâ	glaçaressin	V;COND;PL;3
clamâ	clamassis	V;IPFV;SBJV;SG;2;PST
cjantâ	cjantaressis	V;COND;PL;2
jevâ	jevìn	V;IMP;PL;1
lotâ	lotaran	V;IND;PL;3;FUT
durmî	durmi	V;SBJV;SG;1;PRS
dâ	davis	V;IPFV;IND;PL;2;PST
infassâ	infassaressin	V;COND;PL;3
viodi	viodessin	V;IPFV;SBJV;PL;1;PST
pensâ	pensaressis	V;COND;PL;2
ordenâ	ordenin	V;IND;PL;3;PRS
comprâ	comprave	V;IPFV;IND;SG;3;PST
concuistâ	concuistis	V;SBJV;SG;2;PRS
invidâ	invidavin	V;IPFV;IND;PL;1;PST
masanâ	masani	V;IND;SG;1;PRS
sentâ	sentavis	V;IPFV;IND;SG;2;PST
saludâ	saludàs	V;IPFV;SBJV;SG;1;PST
fassâ	fassais	V;SBJV;PL;2;PRS
slançâ	slançassin	V;IPFV;SBJV;PL;3;PST
trimâ	trimàs	V;IPFV;SBJV;SG;1;PST
meti	metarès	V;COND;SG;1
levâ	levassin	V;IPFV;SBJV;PL;1;PST
lagrimâ	lagrimis	V;IND;SG;2;PRS
ardi	arderin	V;PFV;IND;PL;1;PST
cjaçâ	cjaci	V;IND;SG;1;PRS
ferî	ferirès	V;COND;SG;1
cjadê	cjadis	V;IND;SG;2;PRS
scovâ	scovaressin	V;COND;PL;3
vendemâ	vendemavis	V;IPFV;IND;PL;2;PST
cuietâ	cuietarès	V;COND;SG;1
arâ	arâ	V;NFIN
scoltâ	scoltis	V;SBJV;SG;2;PRS
sangloçâ	sangloçais	V;SBJV;PL;2;PRS
vivi	vivês	V;IND;PL;2;PRS
sgjavâ	sgjavàs	V;IPFV;SBJV;SG;3;PST
lavorâ	lavoraran	V;IND;PL;3;FUT
cusinâ	cusinait	V;IMP;PL;2
maridâ	maridavis	V;IPFV;IND;PL;2;PST
fumâ	fumais	V;SBJV;PL;2;PRS
tonâ	toni	V;SBJV;SG;1;PRS
servî	servissin	V;IPFV;SBJV;PL;1;PST
meti	metei	V;PFV;IND;SG;1;PST
provâ	provavis	V;IPFV;IND;PL;2;PST
misurâ	misuri	V;SBJV;SG;3;PRS
sanganâ	sanganis	V;SBJV;SG;2;PRS
mostrâ	mostrin	V;SBJV;PL;3;PRS
jentrâ	jentravis	V;IPFV;IND;SG;2;PST
capî	capiran	V;IND;PL;3;FUT
capî	capî	V;NFIN
incoronâ	incoronait	V;IMP;PL;2
tosâ	tose	V;IND;SG;3;PRS
sposâ	sposìn	V;IMP;PL;1
puartâ	puartarin	V;PFV;IND;PL;1;PST
sanganâ	sanganarà	V;IND;SG;3;FUT
cjastrâ	cjastrarai	V;IND;SG;1;FUT
lâ	lin	V;IND;PL;1;PRS
trimulâ	trimulìn	V;SBJV;PL;1;PRS
florî	florìs	V;IPFV;SBJV;SG;3;PST
spietâ	spietassis	V;IPFV;SBJV;PL;2;PST
parê	pararessin	V;COND;PL;3
saludâ	saludait	V;IMP;PL;2
scurtâ	scurtarìn	V;IND;PL;1;FUT
spudâ	spudais	V;SBJV;PL;2;PRS
vivi	vivi	V;NFIN
bati	bataran	V;IND;PL;3;FUT
patî	patissi	V;SBJV;SG;3;PRS
vendi	vendè	V;PFV;IND;SG;3;PST
lâ	ledis	V;SBJV;SG;2;PRS
velenâ	velenaran	V;IND;PL;3;FUT
slançâ	slance	V;IND;SG;3;PRS
tasê	tasaerin	V;PFV;IND;PL;3;PST
balâ	balìn	V;IND;PL;1;PRS
lusî	lusirin	V;PFV;IND;PL;3;PST
glaçâ	glacis	V;IND;SG;2;PRS
gustâ	gustaressis	V;COND;SG;2
judâ	judassin	V;IPFV;SBJV;PL;1;PST
pesâ	pesarai	V;IND;SG;1;FUT
urlâ	urlarès	V;COND;SG;1
cjapâ	cjapave	V;IPFV;IND;SG;3;PST
incoronâ	incoronin	V;SBJV;PL;3;PRS
zurâ	zuravi	V;IPFV;IND;SG;1;PST
concuistâ	concuistave	V;IPFV;IND;SG;3;PST
jevâ	jevavin	V;IPFV;IND;PL;1;PST
judâ	judàs	V;IPFV;SBJV;SG;3;PST
lusî	lusìs	V;IND;PL;2;PRS
arâ	ararês	V;IND;PL;2;FUT
malfâ	malfasêt	V;IMP;PL;2
urdî	urdin	V;IND;PL;1;PRS
contâ	contarai	V;IND;SG;1;FUT
cjalçâ	cjalcin	V;SBJV;PL;3;PRS
vendemâ	vendemarìn	V;IND;PL;1;FUT
lassâ	lassarìn	V;IND;PL;1;FUT
scjaldâ	scjaldais	V;IND;PL;2;PRS
cerni	cernin	V;SBJV;PL;3;PRS
urdî	urdissin	V;SBJV;PL;3;PRS
levâ	levìn	V;IMP;PL;1
malfâ	malfasìn	V;IMP;PL;1
maridâ	maridi	V;SBJV;SG;3;PRS
slançâ	slançassin	V;IPFV;SBJV;PL;1;PST
provâ	provìn	V;IND;PL;1;PRS
zontâ	zontarês	V;IND;PL;2;FUT
soflâ	soflarà	V;IND;SG;3;FUT
soflâ	sofle	V;IMP;SG;2
maçâ	maçassis	V;IPFV;SBJV;PL;2;PST
curâ	curàs	V;IPFV;SBJV;SG;3;PST
sgjavâ	sgjavavin	V;IPFV;IND;PL;1;PST
spudâ	spudà	V;PFV;IND;SG;3;PST
pecjâ	pecjin	V;IND;PL;3;PRS
salvâ	salvin	V;SBJV;PL;3;PRS
cerni	cernevin	V;IPFV;IND;PL;1;PST
tentâ	tentâ	V;NFIN
ubidî	ubidirès	V;COND;SG;1
maçâ	maçavis	V;IPFV;IND;PL;2;PST
starnudâ	starnudaressin	V;COND;PL;1
discolçâ	discolçarês	V;IND;PL;2;FUT
blestemâ	blestemis	V;IND;SG;2;PRS
cjastrâ	cjastrarin	V;PFV;IND;PL;3;PST
arâ	aràs	V;IPFV;SBJV;SG;3;PST
florî	floriressis	V;COND;SG;2
tirâ	tiraressis	V;COND;SG;2
començâ	comencìn	V;SBJV;PL;1;PRS
zontâ	zontais	V;IND;PL;2;PRS
discolçâ	discolçassis	V;IPFV;SBJV;PL;2;PST
spietâ	spietarâs	V;IND;SG;2;FUT
mostrâ	mostri	V;SBJV;SG;1;PRS
vendi	vendi	V;NFIN
trimulâ	trimulin	V;IND;PL;3;PRS
maridâ	maridaressis	V;COND;SG;2
salâ	salin	V;IND;PL;3;PRS
fumâ	fumi	V;SBJV;SG;3;PRS
passâ	passin	V;IND;PL;3;PRS
suspirâ	suspiraressin	V;COND;PL;3
miorâ	miore	V;IMP;SG;2
unî	unissin	V;IPFV;SBJV;PL;1;PST
alçâ	alçave	V;IPFV;IND;SG;3;PST
pecjâ	pecjai	V;PFV;IND;SG;1;PST
jevâ	jevarês	V;IND;PL;2;FUT
saltâ	saltin	V;IND;PL;3;PRS
scrivi	scrivês	V;SBJV;PL;2;PRS
nadâ	nadarès	V;COND;SG;3
tasê	tasaerin	V;PFV;IND;PL;1;PST
domandâ	domandaran	V;IND;PL;3;FUT
mostrâ	mostrais	V;IND;PL;2;PRS
cenâ	cenaran	V;IND;PL;3;FUT
inglaçâ	inglaçarà	V;IND;SG;3;FUT
sangloçâ	sangloçait	V;IMP;PL;2
sunâ	sunaressin	V;COND;PL;3
cuietâ	cuietaran	V;IND;PL;3;FUT
urlâ	urli	V;SBJV;SG;1;PRS
començâ	començarai	V;IND;SG;1;FUT
ardi	ardìn	V;SBJV;PL;1;PRS
laudâ	laudaris	V;PFV;IND;SG;2;PST
provâ	provavis	V;IPFV;IND;SG;2;PST
olsâ	olsarin	V;PFV;IND;PL;3;PST
lagrimâ	lagrimaressin	V;COND;PL;1
comprâ	compravis	V;IPFV;IND;PL;2;PST
provâ	provassis	V;IPFV;SBJV;SG;2;PST
cenâ	cenà	V;PFV;IND;SG;3;PST
spaurî	spaurissi	V;SBJV;SG;3;PRS
discjantâ	discjantarin	V;PFV;IND;PL;3;PST
invidâ	invidait	V;IMP;PL;2
sunâ	sune	V;IMP;SG;2
puartâ	puartin	V;SBJV;PL;3;PRS
mertâ	mertarès	V;COND;SG;3
laudâ	laudarai	V;IND;SG;1;FUT
provâ	provarin	V;PFV;IND;PL;1;PST
vistî	vistivis	V;IPFV;IND;PL;2;PST
pensâ	pensavin	V;IPFV;IND;PL;3;PST
pesâ	pesassis	V;IPFV;SBJV;PL;2;PST
cjadê	cjadarà	V;IND;SG;3;FUT
judâ	judarês	V;IND;PL;2;FUT
cerni	cern	V;IMP;SG;2
judâ	judìn	V;SBJV;PL;1;PRS
arâ	ararai	V;IND;SG;1;FUT
pensâ	pensassis	V;IPFV;SBJV;SG;2;PST
valê	valis	V;IND;SG;2;PRS
viodi	viodin	V;IND;PL;3;PRS
menaçâ	menaçais	V;SBJV;PL;2;PRS
suspirâ	suspirìn	V;IMP;PL;1
cjastrâ	cjastrarès	V;COND;SG;3
mertâ	mertai	V;PFV;IND;SG;1;PST
passâ	passavis	V;IPFV;IND;PL;2;PST
saludâ	saludis	V;IND;SG;2;PRS
cjadê	cjadês	V;SBJV;PL;2;PRS
dreçâ	drecìn	V;SBJV;PL;1;PRS
pelâ	pelarai	V;IND;SG;1;FUT
lusî	lusirès	V;COND;SG;1
bagnâ	bagnarà	V;IND;SG;3;FUT
cuietâ	cuietaris	V;PFV;IND;SG;2;PST
sangloçâ	sangloçassin	V;IPFV;SBJV;PL;1;PST
sierâ	sieraressin	V;COND;PL;1
jessî	jessaressin	V;COND;PL;1
ardi	arderis	V;PFV;IND;SG;2;PST
sanganâ	sanganin	V;IND;PL;3;PRS
florî	florii	V;PFV;IND;SG;1;PST
cuietâ	cuietassis	V;IPFV;SBJV;SG;2;PST
jevâ	jevaris	V;PFV;IND;PL;2;PST
jentrâ	jentri	V;SBJV;SG;1;PRS
patî	patissin	V;IPFV;SBJV;PL;1;PST
cuietâ	cuietais	V;SBJV;PL;2;PRS
sanganâ	sanganais	V;SBJV;PL;2;PRS
tasê	tasaès	V;IPFV;SBJV;SG;1;PST
jentrâ	jentravi	V;IPFV;IND;SG;1;PST
spaurî	spauriressin	V;COND;PL;1
pesâ	pesassin	V;IPFV;SBJV;PL;1;PST
miorâ	miore	V;IND;SG;3;PRS
contâ	contassin	V;IPFV;SBJV;PL;1;PST
scrivi	scrivevis	V;IPFV;IND;PL;2;PST
olsâ	olsà	V;PFV;IND;SG;3;PST
costâ	costais	V;IND;PL;2;PRS
scjaldâ	scjaldi	V;IND;SG;1;PRS
sintî	sintive	V;IPFV;IND;SG;3;PST
sudâ	sudavin	V;IPFV;IND;PL;1;PST
tiessi	tiessessin	V;IPFV;SBJV;PL;1;PST
cjaçâ	cjaçassin	V;IPFV;SBJV;PL;1;PST
spudâ	spudavin	V;IPFV;IND;PL;3;PST
ubidî	ubidît	V;IMP;PL;2
unî	univin	V;IPFV;IND;PL;1;PST
meti	meti	V;SBJV;SG;3;PRS
saltâ	saltassis	V;IPFV;SBJV;SG;2;PST
mertâ	mertais	V;SBJV;PL;2;PRS
comprâ	compravin	V;IPFV;IND;PL;3;PST
contâ	contai	V;PFV;IND;SG;1;PST
spietâ	spietai	V;PFV;IND;SG;1;PST
fassâ	fassàs	V;IPFV;SBJV;SG;3;PST
saltâ	saltarâs	V;IND;SG;2;FUT
bagnâ	bagnavin	V;IPFV;IND;PL;1;PST
fassâ	fassaressin	V;COND;PL;3
tirâ	tiris	V;SBJV;SG;2;PRS
sierâ	sieraris	V;PFV;IND;SG;2;PST
cenâ	cenassin	V;IPFV;SBJV;PL;1;PST
cuietâ	cuietâ	V;NFIN
enflâ	enflarês	V;IND;PL;2;FUT
cenâ	cenìn	V;IMP;PL;1
tasê	tasaìn	V;IND;PL;1;PRS
saltâ	saltà	V;PFV;IND;SG;3;PST
fassâ	fassavin	V;IPFV;IND;PL;1;PST
trimâ	trimin	V;SBJV;PL;3;PRS
tentâ	tentarès	V;COND;SG;3
gomitâ	gomitarìn	V;IND;PL;1;FUT
bagnâ	bagnassis	V;IPFV;SBJV;SG;2;PST
remâ	remi	V;IND;SG;1;PRS
florî	florirès	V;COND;SG;3
maridâ	maridai	V;PFV;IND;SG;1;PST
masanâ	masanâ	V;NFIN
viodi	viôt	V;IMP;SG;2
zunâ	zunaris	V;PFV;IND;PL;2;PST
fassâ	fassìn	V;SBJV;PL;1;PRS
salvâ	salvà	V;PFV;IND;SG;3;PST
tastâ	taste	V;IND;SG;3;PRS
bussâ	bussarìn	V;IND;PL;1;FUT
gjavâ	gjavaressis	V;COND;SG;2
maridâ	maridarai	V;IND;SG;1;FUT
sintî	sintivi	V;IPFV;IND;SG;1;PST
mudâ	mudìn	V;IMP;PL;1
semenâ	semenarès	V;COND;SG;3
supâ	supavin	V;IPFV;IND;PL;1;PST
arâ	ararès	V;COND;SG;3
pecjâ	pecjarês	V;IND;PL;2;FUT
unî	unìs	V;IND;SG;1;PRS
vivi	vivaressis	V;COND;SG;2
judâ	judaressis	V;COND;SG;2
sgjavâ	sgjavarin	V;PFV;IND;PL;3;PST
pecjâ	pecjavin	V;IPFV;IND;PL;1;PST
cjastrâ	cjastrai	V;PFV;IND;SG;1;PST
miorâ	miori	V;SBJV;SG;3;PRS
cjalçâ	cjalçà	V;PFV;IND;SG;3;PST
provâ	provave	V;IPFV;IND;SG;3;PST
urdî	urdirâs	V;IND;SG;2;FUT
domandâ	domandassin	V;IPFV;SBJV;PL;3;PST
inglaçâ	inglaçavis	V;IPFV;IND;SG;2;PST
costâ	costi	V;SBJV;SG;3;PRS
salâ	salarin	V;PFV;IND;PL;1;PST
passâ	passaris	V;PFV;IND;PL;2;PST
vendemâ	vendemin	V;IND;PL;3;PRS
scurtâ	scurtis	V;SBJV;SG;2;PRS
olsâ	olsaressin	V;COND;PL;1
capî	capivin	V;IPFV;IND;PL;3;PST
levâ	levìn	V;SBJV;PL;1;PRS
messedâ	messedassis	V;IPFV;SBJV;SG;2;PST
trivelâ	trivelâ	V;NFIN
cjadê	cjadei	V;PFV;IND;SG;1;PST
cjantâ	cjantarâs	V;IND;SG;2;FUT
netâ	netaris	V;PFV;IND;SG;2;PST
maridâ	maridarès	V;COND;SG;1
salâ	salarà	V;IND;SG;3;FUT
dreçâ	drecìn	V;IMP;PL;1
saludâ	saludaressis	V;COND;PL;2
patî	patît	V;IMP;PL;2
pecjâ	pecjis	V;SBJV;SG;2;PRS
cjantâ	cjantavi	V;IPFV;IND;SG;1;PST
parê	parêt	V;IMP;PL;2
pesâ	pesìn	V;SBJV;PL;1;PRS
lavâ	lave	V;IND;SG;3;PRS
sunâ	sunavis	V;IPFV;IND;PL;2;PST
cjantâ	cjantin	V;IND;PL;3;PRS
sposâ	sposarìn	V;IND;PL;1;FUT
comprâ	comprìn	V;SBJV;PL;1;PRS
parê	pararessin	V;COND;PL;1
temê	temessis	V;IPFV;SBJV;SG;2;PST
gjavâ	gjavâ	V;NFIN
laudâ	laudaressin	V;COND;PL;3
sangloçâ	sanglocin	V;SBJV;PL;3;PRS
rivâ	rivi	V;IND;SG;1;PRS
trivelâ	trivelìn	V;SBJV;PL;1;PRS
clamâ	clamarìn	V;IND;PL;1;FUT
bati	batìn	V;SBJV;PL;1;PRS
pecjâ	pecji	V;SBJV;SG;3;PRS
menâ	menis	V;IND;SG;2;PRS
insegnâ	insegnait	V;IMP;PL;2
dî	disaran	V;IND;PL;3;FUT
contâ	contaris	V;PFV;IND;SG;2;PST
bagnâ	bagnaressis	V;COND;PL;2
bati	bataressin	V;COND;PL;3
scjaldâ	scjaldaressis	V;COND;PL;2
trimâ	trimaressin	V;COND;PL;3
mudâ	mudàs	V;IPFV;SBJV;SG;3;PST
cjantâ	cjantarês	V;IND;PL;2;FUT
contâ	contave	V;IPFV;IND;SG;3;PST
costâ	costarin	V;PFV;IND;PL;3;PST
sierâ	sierassis	V;IPFV;SBJV;PL;2;PST
scori	scori	V;SBJV;SG;1;PRS
segnâ	segnaressis	V;COND;PL;2
laudâ	laudarès	V;COND;SG;3
pelâ	pelassis	V;IPFV;SBJV;PL;2;PST
contâ	contìn	V;IND;PL;1;PRS
lotâ	lotìn	V;SBJV;PL;1;PRS
dreçâ	dreçaressin	V;COND;PL;3
tornâ	tornassis	V;IPFV;SBJV;PL;2;PST
scovâ	scovarai	V;IND;SG;1;FUT
lagrimâ	lagrimarès	V;COND;SG;1
crevâ	crevarai	V;IND;SG;1;FUT
lagrimâ	lagrimarin	V;PFV;IND;PL;1;PST
saltâ	saltarà	V;IND;SG;3;FUT
bussâ	bussaressin	V;COND;PL;1
perî	perii	V;PFV;IND;SG;1;PST
tosâ	tosassin	V;IPFV;SBJV;PL;1;PST
vistî	vistissin	V;IPFV;SBJV;PL;1;PST
cjastrâ	cjastravin	V;IPFV;IND;PL;1;PST
perî	perìs	V;IND;SG;3;PRS
copâ	copavin	V;IPFV;IND;PL;3;PST
copâ	copais	V;SBJV;PL;2;PRS
olsâ	olsarès	V;COND;SG;3
glaçâ	glaçaris	V;PFV;IND;PL;2;PST
sposâ	sposavin	V;IPFV;IND;PL;3;PST
vendi	vend	V;IMP;SG;2
glaçâ	glacin	V;IND;PL;3;PRS
cuietâ	cuietarìn	V;IND;PL;1;FUT
gomitâ	gomitarês	V;IND;PL;2;FUT
scoltâ	scoltaressis	V;COND;SG;2
petenâ	petenìn	V;IMP;PL;1
inglaçâ	inglaci	V;SBJV;SG;3;PRS
cjastrâ	cjastrarès	V;COND;SG;1
vendi	vendaressis	V;COND;PL;2
pesâ	pesin	V;IND;PL;3;PRS
sudâ	sudarès	V;COND;SG;3
infassâ	infassaressis	V;COND;SG;2
scurtâ	scurtai	V;PFV;IND;SG;1;PST
jevâ	jevis	V;IND;SG;2;PRS
unî	unìs	V;IND;PL;2;PRS
dâ	deris	V;PFV;IND;SG;2;PST
clamâ	clamaressin	V;COND;PL;3
masanâ	masanais	V;SBJV;PL;2;PRS
lavorâ	lavorassis	V;IPFV;SBJV;SG;2;PST
armâ	arme	V;IND;SG;3;PRS
suspirâ	suspirarâs	V;IND;SG;2;FUT
vendi	vendarès	V;COND;SG;3
spudâ	spudassis	V;IPFV;SBJV;SG;2;PST
scoltâ	scoltaran	V;IND;PL;3;FUT
fassâ	fassavi	V;IPFV;IND;SG;1;PST
zontâ	zontin	V;IND;PL;3;PRS
discolçâ	discolcin	V;SBJV;PL;3;PRS
lotâ	lotarai	V;IND;SG;1;FUT
scjaldâ	scjaldin	V;SBJV;PL;3;PRS
masanâ	masanaressin	V;COND;PL;1
amâ	amais	V;IND;PL;2;PRS
plasê	plasis	V;IND;SG;2;PRS
sposâ	sposaris	V;PFV;IND;PL;2;PST
salvâ	salvarin	V;PFV;IND;PL;1;PST
dreçâ	dreçaran	V;IND;PL;3;FUT
provâ	provâ	V;NFIN
dreçâ	dreci	V;SBJV;SG;1;PRS
enflâ	enflìn	V;SBJV;PL;1;PRS
comandâ	comandìn	V;IND;PL;1;PRS
ferî	ferissis	V;IPFV;SBJV;SG;2;PST
sentâ	sentaris	V;PFV;IND;SG;2;PST
glaçâ	glaçà	V;PFV;IND;SG;3;PST
spaurî	spauriran	V;IND;PL;3;FUT
jessi	sedin	V;SBJV;PL;1;PRS
zunâ	zunà	V;PFV;IND;SG;3;PST
ubidî	ubidiran	V;IND;PL;3;FUT
convidâ	convidassin	V;IPFV;SBJV;PL;1;PST
maçâ	maçàs	V;IPFV;SBJV;SG;1;PST
enflâ	enflarà	V;IND;SG;3;FUT
zurâ	zure	V;IMP;SG;2
ardi	ardessin	V;IPFV;SBJV;PL;3;PST
bussâ	bussin	V;IND;PL;3;PRS
puartâ	puarte	V;IND;SG;3;PRS
infassâ	infassassis	V;IPFV;SBJV;SG;2;PST
urdî	urdiris	V;PFV;IND;PL;2;PST
trimâ	trimaressis	V;COND;PL;2
domandâ	domandis	V;IND;SG;2;PRS
spaurî	spaurivis	V;IPFV;IND;SG;2;PST
tonâ	tonarès	V;COND;SG;3
cjadê	cjaderis	V;PFV;IND;PL;2;PST
urlâ	urlassin	V;IPFV;SBJV;PL;3;PST
unî	unissis	V;IND;SG;2;PRS
mertâ	mertavin	V;IPFV;IND;PL;1;PST
convidâ	convidìn	V;IMP;PL;1
cjadê	cjadi	V;SBJV;SG;3;PRS
maridâ	maride	V;IMP;SG;2
tiessi	tiessessis	V;IPFV;SBJV;SG;2;PST
segnâ	segnarin	V;PFV;IND;PL;3;PST
patî	patiran	V;IND;PL;3;FUT
vistî	vistirês	V;IND;PL;2;FUT
rivâ	rivai	V;PFV;IND;SG;1;PST
scjampâ	scjampi	V;IND;SG;1;PRS
insegnâ	insegnin	V;IND;PL;3;PRS
scori	scorarà	V;IND;SG;3;FUT
gjavâ	gjavave	V;IPFV;IND;SG;3;PST
zontâ	zontave	V;IPFV;IND;SG;3;PST
finî	finirâs	V;IND;SG;2;FUT
bati	bateve	V;IPFV;IND;SG;3;PST
vendi	vendevis	V;IPFV;IND;PL;2;PST
mertâ	mertis	V;SBJV;SG;2;PRS
maridâ	maridà	V;PFV;IND;SG;3;PST
sintî	sintissis	V;IPFV;SBJV;SG;2;PST
spietâ	spietìn	V;IMP;PL;1
bati	batevin	V;IPFV;IND;PL;3;PST
cerni	cernis	V;IND;SG;2;PRS
valê	valaressis	V;COND;SG;2
masanâ	masanaris	V;PFV;IND;PL;2;PST
lâ	lavin	V;IPFV;IND;PL;3;PST
parê	parevin	V;IPFV;IND;PL;3;PST
miorâ	mioraressin	V;COND;PL;1
netâ	netaressis	V;COND;SG;2
sintî	sintis	V;IND;SG;2;PRS
trivelâ	trivelaressin	V;COND;PL;1
fâ	fasaran	V;IND;PL;3;FUT
segnâ	segnavin	V;IPFV;IND;PL;3;PST
incoronâ	incorone	V;IMP;SG;2
lusî	lusissis	V;SBJV;SG;2;PRS
dâ	daressis	V;COND;SG;2
jevâ	jevassin	V;IPFV;SBJV;PL;3;PST
crevâ	crevais	V;IND;PL;2;PRS
insegnâ	insegnaressis	V;COND;SG;2
costâ	costaressin	V;COND;PL;1
trivelâ	trivelassis	V;IPFV;SBJV;PL;2;PST
tonâ	tonassis	V;IPFV;SBJV;PL;2;PST
tasê	tasaessin	V;IPFV;SBJV;PL;3;PST
menâ	menìn	V;IND;PL;1;PRS
tonâ	tonaressin	V;COND;PL;1
cjastrâ	cjastrìn	V;IND;PL;1;PRS
discjantâ	discjantarìn	V;IND;PL;1;FUT
fâ	faserin	V;PFV;IND;PL;1;PST
lâ	laressin	V;COND;PL;3
tiessi	tiessìn	V;SBJV;PL;1;PRS
crevâ	crevarês	V;IND;PL;2;FUT
velenâ	velenin	V;SBJV;PL;3;PRS
olsâ	olsìn	V;SBJV;PL;1;PRS
unî	unìs	V;IPFV;SBJV;SG;1;PST
comandâ	comandavin	V;IPFV;IND;PL;1;PST
mertâ	mertassin	V;IPFV;SBJV;PL;1;PST
ardi	ardessis	V;IPFV;SBJV;SG;2;PST
slançâ	slancìn	V;IMP;PL;1
jessî	jess	V;IND;SG;1;PRS
scjadê	scjadaressis	V;COND;PL;2
infassâ	infassarès	V;COND;SG;1
lavâ	lavait	V;IMP;PL;2
velenâ	velenaressis	V;COND;SG;2
urlâ	urlais	V;IND;PL;2;PRS
cuietâ	cuietaris	V;PFV;IND;PL;2;PST
sunâ	sunarès	V;COND;SG;1
ardi	ardessin	V;IPFV;SBJV;PL;1;PST
gomitâ	gomiti	V;IND;SG;1;PRS
gomitâ	gomitarai	V;IND;SG;1;FUT
messedâ	messedarìn	V;IND;PL;1;FUT
començâ	començassis	V;IPFV;SBJV;PL;2;PST
trimâ	trimaressin	V;COND;PL;1
mostrâ	mostris	V;SBJV;SG;2;PRS
jessi	son	V;IND;PL;3;PRS
gomitâ	gomitassin	V;IPFV;SBJV;PL;3;PST
sudâ	sudaressis	V;COND;SG;2
pesâ	pesassin	V;IPFV;SBJV;PL;3;PST
jentrâ	jentravin	V;IPFV;IND;PL;1;PST
spudâ	spudavis	V;IPFV;IND;SG;2;PST
zunâ	zunaran	V;IND;PL;3;FUT
tonâ	tonavi	V;IPFV;IND;SG;1;PST
salvâ	salvassin	V;IPFV;SBJV;PL;3;PST
començâ	començarès	V;COND;SG;1
plasê	plasaressin	V;COND;PL;1
gjavâ	gjavìn	V;IMP;PL;1
dreçâ	dreçaressis	V;COND;SG;2
semenâ	semenassis	V;IPFV;SBJV;SG;2;PST
spietâ	spietaran	V;IND;PL;3;FUT
armâ	armis	V;SBJV;SG;2;PRS
concuistâ	concuisti	V;IND;SG;1;PRS
zunâ	zunarès	V;COND;SG;1
temê	temès	V;IPFV;SBJV;SG;3;PST
spaurî	spaurirês	V;IND;PL;2;FUT
petenâ	petenàs	V;IPFV;SBJV;SG;1;PST
sgjavâ	sgjavarìn	V;IND;PL;1;FUT
olsâ	olsin	V;IND;PL;3;PRS
zurâ	zurarin	V;PFV;IND;PL;3;PST
vê	veve	V;IPFV;IND;SG;3;PST
misurâ	misurai	V;PFV;IND;SG;1;PST
ordenâ	ordenis	V;SBJV;SG;2;PRS
vivi	vivevis	V;IPFV;IND;SG;2;PST
maçâ	maçarà	V;IND;SG;3;FUT
olsâ	olsi	V;SBJV;SG;3;PRS
tentâ	tentarin	V;PFV;IND;PL;1;PST
comprâ	comprarês	V;IND;PL;2;FUT
cjaçâ	cjaçassis	V;IPFV;SBJV;SG;2;PST
glaçâ	glaçarès	V;COND;SG;1
discjantâ	discjantait	V;IMP;PL;2
plasê	plasêt	V;IMP;PL;2
scjaldâ	scjaldaran	V;IND;PL;3;FUT
ferî	ferirìn	V;IND;PL;1;FUT
bati	batin	V;IND;PL;3;PRS
durmî	durmivi	V;IPFV;IND;SG;1;PST
maçâ	maci	V;IND;SG;1;PRS
scurtâ	scurte	V;IND;SG;3;PRS
menâ	menaris	V;PFV;IND;PL;2;PST
stralusî	stralusissis	V;SBJV;SG;2;PRS
maridâ	maridaressis	V;COND;PL;2
starnudâ	starnudaressis	V;COND;PL;2
cerni	cernês	V;IND;PL;2;PRS
urlâ	urlàs	V;IPFV;SBJV;SG;3;PST
incoronâ	incoronaran	V;IND;PL;3;FUT
spaurî	spaurissis	V;SBJV;SG;2;PRS
sangloçâ	sangloçais	V;IND;PL;2;PRS
alçâ	alçait	V;IMP;PL;2
tirâ	tirassin	V;IPFV;SBJV;PL;3;PST
contâ	contarès	V;COND;SG;3
sierâ	sieravis	V;IPFV;IND;SG;2;PST
glaçâ	glaçarin	V;PFV;IND;PL;1;PST
parê	paressis	V;IPFV;SBJV;PL;2;PST
trimâ	trimait	V;IMP;PL;2
vê	varessin	V;COND;PL;1
vistî	vistin	V;IND;PL;1;PRS
comandâ	comandarà	V;IND;SG;3;FUT
sudâ	sudais	V;SBJV;PL;2;PRS
perî	perissin	V;IPFV;SBJV;PL;1;PST
cjaçâ	cjacìn	V;SBJV;PL;1;PRS
remâ	remavin	V;IPFV;IND;PL;1;PST
jessi	sarès	V;COND;SG;1
spudâ	spudi	V;SBJV;SG;3;PRS
cjaçâ	cjaçarai	V;IND;SG;1;FUT
sudâ	sudaressin	V;COND;PL;1
messedâ	messedais	V;SBJV;PL;2;PRS
armâ	armarâs	V;IND;SG;2;FUT
crodi	crodarà	V;IND;SG;3;FUT
puartâ	puartàs	V;IPFV;SBJV;SG;1;PST
scovâ	scovaris	V;PFV;IND;SG;2;PST
patî	patissis	V;IND;SG;2;PRS
starnudâ	starnudave	V;IPFV;IND;SG;3;PST
tonâ	tonaressis	V;COND;PL;2
nadâ	nadin	V;IND;PL;3;PRS
fumâ	fumarâs	V;IND;SG;2;FUT
plasê	plasessin	V;IPFV;SBJV;PL;3;PST
miorâ	mioraressin	V;COND;PL;3
bagnâ	bagnaris	V;PFV;IND;PL;2;PST
comprâ	compràs	V;IPFV;SBJV;SG;1;PST
tiessi	tiesserin	V;PFV;IND;PL;3;PST
girâ	girait	V;IMP;PL;2
trimulâ	trimulàs	V;IPFV;SBJV;SG;3;PST
lâ	larâs	V;IND;SG;2;FUT
gustâ	gusti	V;IND;SG;1;PRS
scurtâ	scurtarês	V;IND;PL;2;FUT
scrivi	scrivarai	V;IND;SG;1;FUT
durmî	durmarìn	V;IND;PL;1;FUT
messedâ	messede	V;IMP;SG;2
domandâ	domandavi	V;IPFV;IND;SG;1;PST
spaurî	spaurin	V;IND;PL;1;PRS
armâ	armassis	V;IPFV;SBJV;SG;2;PST
semenâ	semenarìn	V;IND;PL;1;FUT
urlâ	urlave	V;IPFV;IND;SG;3;PST
copâ	cope	V;IMP;SG;2
balâ	balaran	V;IND;PL;3;FUT
enflâ	enflassis	V;IPFV;SBJV;SG;2;PST
balâ	balais	V;SBJV;PL;2;PRS
misurâ	misuravis	V;IPFV;IND;SG;2;PST
semenâ	semenin	V;IND;PL;3;PRS
contâ	contassis	V;IPFV;SBJV;SG;2;PST
lavorâ	lavoraris	V;PFV;IND;PL;2;PST
menaçâ	menaçarà	V;IND;SG;3;FUT
misurâ	misurìn	V;IMP;PL;1
spaurî	spauriressin	V;COND;PL;3
balâ	balaressin	V;COND;PL;1
temê	temei	V;PFV;IND;SG;1;PST
urdî	urdìs	V;IND;SG;3;PRS
vendemâ	vendemin	V;SBJV;PL;3;PRS
finî	finissi	V;SBJV;SG;3;PRS
cuietâ	cuietavis	V;IPFV;IND;SG;2;PST
lotâ	lotarin	V;PFV;IND;PL;1;PST
misurâ	misuraressin	V;COND;PL;3
armâ	armarin	V;PFV;IND;PL;3;PST
convidâ	convide	V;IMP;SG;2
semenâ	semenis	V;IND;SG;2;PRS
comandâ	comandarin	V;PFV;IND;PL;1;PST
servî	servirês	V;IND;PL;2;FUT
fâ	fasevin	V;IPFV;IND;PL;3;PST
crodi	crodis	V;IND;SG;2;PRS
salâ	salai	V;PFV;IND;SG;1;PST
olsâ	olsaris	V;PFV;IND;PL;2;PST
passâ	passassin	V;IPFV;SBJV;PL;3;PST
vivi	vivês	V;SBJV;PL;2;PRS
semenâ	semenassin	V;IPFV;SBJV;PL;3;PST
valê	valarès	V;COND;SG;1
sudâ	sudarès	V;COND;SG;1
patî	patì	V;PFV;IND;SG;3;PST
cjalçâ	cjalçarin	V;PFV;IND;PL;3;PST
discolçâ	discolçais	V;SBJV;PL;2;PRS
dî	disìn	V;SBJV;PL;1;PRS
tiessi	tiess	V;IND;SG;1;PRS
cjapâ	cjape	V;IMP;SG;2
scjampâ	scjampis	V;IND;SG;2;PRS
sierâ	sierait	V;IMP;PL;2
scovâ	scovà	V;PFV;IND;SG;3;PST
enflâ	enflaressis	V;COND;PL;2
sintî	sinti	V;SBJV;SG;1;PRS
dâ	din	V;IND;PL;1;PRS
sposâ	sposarès	V;COND;SG;3
cjadê	cjadaressis	V;COND;SG;2
copâ	coparessis	V;COND;PL;2
puartâ	puartavin	V;IPFV;IND;PL;1;PST
invidâ	invidaressin	V;COND;PL;1
laudâ	laudi	V;IND;SG;1;PRS
jevâ	jevin	V;SBJV;PL;3;PRS
cerni	cernês	V;SBJV;PL;2;PRS
vê	ves	V;IPFV;SBJV;SG;1;PST
ricuardâ	ricuardarai	V;IND;SG;1;FUT
finî	finirês	V;IND;PL;2;FUT
cjapâ	cjaparâs	V;IND;SG;2;FUT
pesâ	pesi	V;SBJV;SG;1;PRS
plasê	plaseris	V;PFV;IND;PL;2;PST
urdî	urdissis	V;IPFV;SBJV;PL;2;PST
inglaçâ	inglaçaressin	V;COND;PL;3
suspirâ	suspirarès	V;COND;SG;1
ricuardâ	ricuardìn	V;IND;PL;1;PRS
amâ	amaressis	V;COND;PL;2
judâ	judin	V;SBJV;PL;3;PRS
ubidî	ubidirin	V;PFV;IND;PL;3;PST
supâ	supin	V;IND;PL;3;PRS
misurâ	misuraressin	V;COND;PL;1
ferî	feriris	V;PFV;IND;SG;2;PST
slançâ	slance	V;IMP;SG;2
maçâ	maçâ	V;NFIN
tosâ	tosi	V;SBJV;SG;1;PRS
cjatâ	cjatavin	V;IPFV;IND;PL;3;PST
ardi	ardevi	V;IPFV;IND;SG;1;PST
segnâ	segnìn	V;IND;PL;1;PRS
infassâ	infassàs	V;IPFV;SBJV;SG;3;PST
ardi	ardarà	V;IND;SG;3;FUT
mudâ	mudà	V;PFV;IND;SG;3;PST
cjantâ	cjanti	V;SBJV;SG;3;PRS
tonâ	tonarin	V;PFV;IND;PL;3;PST
menâ	menarin	V;PFV;IND;PL;3;PST
ardi	ard	V;IMP;SG;2
lavorâ	lavorin	V;SBJV;PL;3;PRS
masanâ	masanà	V;PFV;IND;SG;3;PST
valê	valevis	V;IPFV;IND;SG;2;PST
cjadê	cjaderis	V;PFV;IND;SG;2;PST
discjantâ	discjantavis	V;IPFV;IND;PL;2;PST
viodi	vioderis	V;PFV;IND;SG;2;PST
saltâ	saltâ	V;NFIN
copâ	copàs	V;IPFV;SBJV;SG;1;PST
cjatâ	cjatin	V;SBJV;PL;3;PRS
cerni	cernevis	V;IPFV;IND;PL;2;PST
tastâ	tastarès	V;COND;SG;1
glaçâ	glacis	V;SBJV;SG;2;PRS
fevelâ	fevelaris	V;PFV;IND;PL;2;PST
blestemâ	blestemaressis	V;COND;PL;2
malfâ	malfasarès	V;COND;SG;1
stralusî	stralusissin	V;SBJV;PL;3;PRS
lusî	lusin	V;IND;PL;1;PRS
alçâ	alcis	V;IND;SG;2;PRS
puartâ	puartarìn	V;IND;PL;1;FUT
incoronâ	incoronassin	V;IPFV;SBJV;PL;3;PST
vê	ve	V;IMP;SG;2
servî	servissin	V;IPFV;SBJV;PL;3;PST
cusinâ	cusinave	V;IPFV;IND;SG;3;PST
comprâ	comprà	V;PFV;IND;SG;3;PST
fassâ	fassave	V;IPFV;IND;SG;3;PST
spaurî	spaurît	V;IMP;PL;2
cjatâ	cjatarâs	V;IND;SG;2;FUT
tosâ	tosassis	V;IPFV;SBJV;PL;2;PST
cjaçâ	cjaçaressis	V;COND;SG;2
soflâ	soflavis	V;IPFV;IND;PL;2;PST
dâ	dassis	V;IPFV;SBJV;SG;2;PST
maçâ	maçarin	V;PFV;IND;PL;3;PST
vivi	vivi	V;SBJV;SG;1;PRS
viodi	viodè	V;PFV;IND;SG;3;PST
crevâ	crevà	V;PFV;IND;SG;3;PST
jentrâ	jentris	V;IND;SG;2;PRS
girâ	giravi	V;IPFV;IND;SG;1;PST
tentâ	tentàs	V;IPFV;SBJV;SG;1;PST
fumâ	fume	V;IMP;SG;2
amâ	amavin	V;IPFV;IND;PL;3;PST
sgjavâ	sgjavarai	V;IND;SG;1;FUT
copâ	coparessin	V;COND;PL;3
supâ	supavin	V;IPFV;IND;PL;3;PST
domandâ	domandarin	V;PFV;IND;PL;3;PST
fevelâ	fevelai	V;PFV;IND;SG;1;PST
tirâ	tire	V;IND;SG;3;PRS
tornâ	tornait	V;IMP;PL;2
crevâ	crevassis	V;IPFV;SBJV;PL;2;PST
saludâ	saludarâs	V;IND;SG;2;FUT
mudâ	mudavis	V;IPFV;IND;SG;2;PST
mudâ	mudarin	V;PFV;IND;PL;3;PST
saltâ	saltaressin	V;COND;PL;3
ferî	ferin	V;IND;PL;1;PRS
temê	temessin	V;IPFV;SBJV;PL;3;PST
finî	finì	V;PFV;IND;SG;3;PST
lavorâ	lavoravis	V;IPFV;IND;PL;2;PST
olsâ	olsis	V;IND;SG;2;PRS
vendemâ	vendemavi	V;IPFV;IND;SG;1;PST
judâ	judais	V;SBJV;PL;2;PRS
messedâ	messedai	V;PFV;IND;SG;1;PST
mertâ	mertarin	V;PFV;IND;PL;3;PST
finî	finirai	V;IND;SG;1;FUT
patî	patìs	V;IMP;SG;2
jessî	jessissin	V;IPFV;SBJV;PL;3;PST
temê	temìn	V;IND;PL;1;PRS
concuistâ	concuistavis	V;IPFV;IND;PL;2;PST
lâ	làs	V;IPFV;SBJV;SG;1;PST
crodi	crodês	V;SBJV;PL;2;PRS
concuistâ	concuistàs	V;IPFV;SBJV;SG;3;PST
dreçâ	dreçâ	V;NFIN
vê	ve	V;PFV;IND;SG;3;PST
scurtâ	scurtais	V;SBJV;PL;2;PRS
maridâ	maridaris	V;PFV;IND;SG;2;PST
amâ	amin	V;IND;PL;3;PRS
tonâ	tonavis	V;IPFV;IND;PL;2;PST
lagrimâ	lagrimìn	V;IMP;PL;1
cerni	cernìn	V;IND;PL;1;PRS
passâ	passaressin	V;COND;PL;1
soflâ	soflaressis	V;COND;PL;2
scovâ	scovàs	V;IPFV;SBJV;SG;1;PST
jessi	fossis	V;IPFV;SBJV;PL;2;PST
girâ	girais	V;IND;PL;2;PRS
tosâ	tosavin	V;IPFV;IND;PL;1;PST
alçâ	alci	V;IND;SG;1;PRS
crodi	crodevin	V;IPFV;IND;PL;1;PST
urlâ	urlassin	V;IPFV;SBJV;PL;1;PST
stralusî	stralusiris	V;PFV;IND;PL;2;PST
amâ	amaris	V;PFV;IND;PL;2;PST
capî	capive	V;IPFV;IND;SG;3;PST
dreçâ	dreçaris	V;PFV;IND;SG;2;PST
ordenâ	ordenaris	V;PFV;IND;PL;2;PST
meti	metevin	V;IPFV;IND;PL;1;PST
misurâ	misurarès	V;COND;SG;1
levâ	levarês	V;IND;PL;2;FUT
fumâ	fumin	V;IND;PL;3;PRS
parê	parès	V;IPFV;SBJV;SG;1;PST
vendemâ	vendemaressis	V;COND;PL;2
mertâ	mertaris	V;PFV;IND;SG;2;PST
zurâ	zurarês	V;IND;PL;2;FUT
semenâ	semenaris	V;PFV;IND;PL;2;PST
stralusî	stralusissin	V;IPFV;SBJV;PL;3;PST
armâ	armaressin	V;COND;PL;3
salâ	salais	V;IND;PL;2;PRS
servî	servive	V;IPFV;IND;SG;3;PST
enflâ	enflavis	V;IPFV;IND;PL;2;PST
inglaçâ	inglaci	V;IND;SG;1;PRS
cjaçâ	cjacìn	V;IMP;PL;1
scjampâ	scjampin	V;SBJV;PL;3;PRS
vistî	vistirâs	V;IND;SG;2;FUT
tasê	tasaìn	V;IMP;PL;1
bagnâ	bagnavis	V;IPFV;IND;PL;2;PST
pecjâ	pecjarâs	V;IND;SG;2;FUT
blestemâ	blesteme	V;IMP;SG;2
scoltâ	scoltà	V;PFV;IND;SG;3;PST
vendemâ	vendemavis	V;IPFV;IND;SG;2;PST
trivelâ	trivelarâs	V;IND;SG;2;FUT
plasê	plasessis	V;IPFV;SBJV;SG;2;PST
jessî	jessin	V;IND;PL;3;PRS
svolâ	svolavin	V;IPFV;IND;PL;1;PST
cjatâ	cjatarès	V;COND;SG;3
trivelâ	trivelave	V;IPFV;IND;SG;3;PST
stralusî	stralusìs	V;IPFV;SBJV;SG;1;PST
cori	coris	V;IND;SG;2;PRS
cusinâ	cusinaressin	V;COND;PL;3
mudâ	mudaris	V;PFV;IND;PL;2;PST
blestemâ	blestemarâs	V;IND;SG;2;FUT
fassâ	fassai	V;PFV;IND;SG;1;PST
salâ	salarai	V;IND;SG;1;FUT
girâ	giràs	V;IPFV;SBJV;SG;1;PST
tasê	tasaarà	V;IND;SG;3;FUT
tornâ	tornais	V;IND;PL;2;PRS
infassâ	infassaris	V;PFV;IND;PL;2;PST
discolçâ	discolçaressin	V;COND;PL;3
comprâ	comprarès	V;COND;SG;1
puartâ	puartarà	V;IND;SG;3;FUT
fâ	fasis	V;SBJV;SG;2;PRS
gustâ	gustà	V;PFV;IND;SG;3;PST
cenâ	cenarâs	V;IND;SG;2;FUT
discjantâ	discjantis	V;IND;SG;2;PRS
mudâ	mudassis	V;IPFV;SBJV;PL;2;PST
scori	scorin	V;SBJV;PL;3;PRS
trimulâ	trimularessin	V;COND;PL;1
urdî	urdissin	V;IPFV;SBJV;PL;1;PST
mertâ	mertìn	V;SBJV;PL;1;PRS
vivi	vivarês	V;IND;PL;2;FUT
sossedâ	sossedavin	V;IPFV;IND;PL;1;PST
domandâ	domandavis	V;IPFV;IND;SG;2;PST
perî	perirìn	V;IND;PL;1;FUT
messedâ	messedavis	V;IPFV;IND;SG;2;PST
malfâ	malfasis	V;IND;SG;2;PRS
messedâ	messedàs	V;IPFV;SBJV;SG;3;PST
cjastrâ	cjastrarâs	V;IND;SG;2;FUT
zunâ	zunaris	V;PFV;IND;SG;2;PST
sossedâ	sossedave	V;IPFV;IND;SG;3;PST
petenâ	petenavin	V;IPFV;IND;PL;3;PST
ricuardâ	ricuardai	V;PFV;IND;SG;1;PST
sunâ	sunin	V;SBJV;PL;3;PRS
olsâ	olsi	V;IND;SG;1;PRS
nadâ	nadaris	V;PFV;IND;SG;2;PST
lusî	lusî	V;NFIN
tasê	tasâ	V;IMP;SG;2
levâ	levave	V;IPFV;IND;SG;3;PST
arâ	are	V;IMP;SG;2
ferî	feriressis	V;COND;PL;2
concuistâ	concuistassis	V;IPFV;SBJV;SG;2;PST
perî	perìn	V;SBJV;PL;1;PRS
spaurî	spaurivin	V;IPFV;IND;PL;1;PST
soflâ	sofli	V;SBJV;SG;3;PRS
pensâ	pensarès	V;COND;SG;3
vê	vedin	V;SBJV;PL;1;PRS
mudâ	mudavin	V;IPFV;IND;PL;1;PST
sossedâ	sossedassin	V;IPFV;SBJV;PL;3;PST
scovâ	scovassin	V;IPFV;SBJV;PL;3;PST
salâ	salaris	V;PFV;IND;SG;2;PST
miorâ	miorìn	V;SBJV;PL;1;PRS
menaçâ	menaçais	V;IND;PL;2;PRS
fumâ	fumis	V;IND;SG;2;PRS
ordenâ	ordenai	V;PFV;IND;SG;1;PST
blestemâ	blestemaressis	V;COND;SG;2
trivelâ	trivelaris	V;PFV;IND;SG;2;PST
sossedâ	sossedassis	V;IPFV;SBJV;SG;2;PST
ardi	ardarìn	V;IND;PL;1;FUT
zunâ	zunassin	V;IPFV;SBJV;PL;1;PST
rivâ	rivin	V;SBJV;PL;3;PRS
bagnâ	bagnà	V;PFV;IND;SG;3;PST
masanâ	masanait	V;IMP;PL;2
dâ	davin	V;IPFV;IND;PL;3;PST
sposâ	sposin	V;SBJV;PL;3;PRS
girâ	girìn	V;IND;PL;1;PRS
nadâ	nadavis	V;IPFV;IND;PL;2;PST
scurtâ	scurtassin	V;IPFV;SBJV;PL;3;PST
cjastrâ	cjastrâ	V;NFIN
sgjavâ	sgjavassin	V;IPFV;SBJV;PL;1;PST
gjavâ	gjavarin	V;PFV;IND;PL;3;PST
bussâ	bussai	V;PFV;IND;SG;1;PST
gjavâ	gjavàs	V;IPFV;SBJV;SG;3;PST
balâ	balaressis	V;COND;SG;2
domandâ	domandarâs	V;IND;SG;2;FUT
sudâ	sudarin	V;PFV;IND;PL;3;PST
sossedâ	sossedavis	V;IPFV;IND;PL;2;PST
provâ	provi	V;IND;SG;1;PRS
discjantâ	discjantaran	V;IND;PL;3;FUT
cori	coraressin	V;COND;PL;3
cjaçâ	cjaçavis	V;IPFV;IND;PL;2;PST
starnudâ	starnudaran	V;IND;PL;3;FUT
clamâ	clamaran	V;IND;PL;3;FUT
supâ	supis	V;IND;SG;2;PRS
girâ	girassis	V;IPFV;SBJV;PL;2;PST
vendi	vendês	V;IND;PL;2;PRS
cusinâ	cusinis	V;IND;SG;2;PRS
scoltâ	scoltavis	V;IPFV;IND;PL;2;PST
slançâ	slançavin	V;IPFV;IND;PL;1;PST
messedâ	messedavin	V;IPFV;IND;PL;1;PST
enflâ	enfle	V;IMP;SG;2
cusinâ	cusinaris	V;PFV;IND;SG;2;PST
valê	valessin	V;IPFV;SBJV;PL;1;PST
scrivi	scrivis	V;SBJV;SG;2;PRS
segnâ	segne	V;IND;SG;3;PRS
vendemâ	vendemarà	V;IND;SG;3;FUT
sunâ	suni	V;SBJV;SG;1;PRS
vendi	vendis	V;IND;SG;2;PRS
cori	corês	V;SBJV;PL;2;PRS
spaurî	spaurii	V;PFV;IND;SG;1;PST
sgjavâ	sgjavi	V;SBJV;SG;1;PRS
lassâ	lassarès	V;COND;SG;1
tastâ	tastàs	V;IPFV;SBJV;SG;1;PST
servî	servissi	V;SBJV;SG;3;PRS
menâ	menàs	V;IPFV;SBJV;SG;3;PST
cusinâ	cusinarin	V;PFV;IND;PL;3;PST
concuistâ	concuistarâs	V;IND;SG;2;FUT
trimâ	trimai	V;PFV;IND;SG;1;PST
maçâ	maçavi	V;IPFV;IND;SG;1;PST
laudâ	laudarès	V;COND;SG;1
sunâ	sunarai	V;IND;SG;1;FUT
tosâ	tosis	V;SBJV;SG;2;PRS
insegnâ	insegne	V;IND;SG;3;PRS
salvâ	salvarà	V;IND;SG;3;FUT
miorâ	mioràs	V;IPFV;SBJV;SG;3;PST
starnudâ	starnudis	V;SBJV;SG;2;PRS
clamâ	clamaris	V;PFV;IND;SG;2;PST
cjatâ	cjati	V;SBJV;SG;3;PRS
trimâ	trimaris	V;PFV;IND;SG;2;PST
salâ	sali	V;IND;SG;1;PRS
spudâ	spudarin	V;PFV;IND;PL;1;PST
plasê	plasi	V;SBJV;SG;1;PRS
lâ	lâ	V;NFIN
parê	pareris	V;PFV;IND;PL;2;PST
dreçâ	drecin	V;IND;PL;3;PRS
unî	univis	V;IPFV;IND;SG;2;PST
maridâ	maridarà	V;IND;SG;3;FUT
contâ	contavis	V;IPFV;IND;PL;2;PST
discjantâ	discjanti	V;IND;SG;1;PRS
scurtâ	scurtavis	V;IPFV;IND;SG;2;PST
sgjavâ	sgjavassis	V;IPFV;SBJV;SG;2;PST
lotâ	lotâ	V;NFIN
urdî	urdirès	V;COND;SG;1
misurâ	misurarin	V;PFV;IND;PL;3;PST
mudâ	mudaran	V;IND;PL;3;FUT
bati	batin	V;SBJV;PL;3;PRS
ricuardâ	ricuardaris	V;PFV;IND;PL;2;PST
malfâ	malfasevi	V;IPFV;IND;SG;1;PST
tonâ	tonìn	V;IND;PL;1;PRS
patî	pativi	V;IPFV;IND;SG;1;PST
segnâ	segnaris	V;PFV;IND;PL;2;PST
laudâ	laudassin	V;IPFV;SBJV;PL;3;PST
valê	valìn	V;IMP;PL;1
lâ	lè	V;PFV;IND;SG;3;PST
semenâ	semenavis	V;IPFV;IND;PL;2;PST
vê	vevin	V;IPFV;IND;PL;3;PST
cjalçâ	cjalci	V;IND;SG;1;PRS
balâ	balaressin	V;COND;PL;3
meti	meteve	V;IPFV;IND;SG;3;PST
jevâ	jevà	V;PFV;IND;SG;3;PST
lotâ	lotarin	V;PFV;IND;PL;3;PST
patî	patîs	V;SBJV;PL;2;PRS
passâ	passaris	V;PFV;IND;SG;2;PST
jessî	jessarìn	V;IND;PL;1;FUT
capî	capin	V;IND;PL;1;PRS
lusî	lusiran	V;IND;PL;3;FUT
infassâ	infassavi	V;IPFV;IND;SG;1;PST
cjadê	cjadevin	V;IPFV;IND;PL;1;PST
malfâ	malfasaressin	V;COND;PL;1
maridâ	maridavi	V;IPFV;IND;SG;1;PST
pecjâ	pecjarès	V;COND;SG;3
menaçâ	menaçâ	V;NFIN
curâ	curìn	V;IND;PL;1;PRS
enflâ	enflarin	V;PFV;IND;PL;1;PST
discjantâ	discjantaressin	V;COND;PL;1
sudâ	sudavin	V;IPFV;IND;PL;3;PST
ardi	ardevis	V;IPFV;IND;PL;2;PST
slançâ	slançarâs	V;IND;SG;2;FUT
sierâ	sierarâs	V;IND;SG;2;FUT
gjavâ	gjavaressis	V;COND;PL;2
spaurî	spauririn	V;PFV;IND;PL;3;PST
sentâ	sentarin	V;PFV;IND;PL;1;PST
fevelâ	fevelaressis	V;COND;PL;2
menaçâ	menace	V;IND;SG;3;PRS
laudâ	laudìn	V;IMP;PL;1
gomitâ	gomitarà	V;IND;SG;3;FUT
cerni	cernès	V;IPFV;SBJV;SG;3;PST
sposâ	sposassin	V;IPFV;SBJV;PL;3;PST
menâ	menìn	V;SBJV;PL;1;PRS
cjantâ	cjanti	V;IND;SG;1;PRS
crodi	croderin	V;PFV;IND;PL;1;PST
comandâ	comandi	V;SBJV;SG;1;PRS
segnâ	segnarai	V;IND;SG;1;FUT
parê	pâr	V;IND;SG;1;PRS
durmî	durmìs	V;IPFV;SBJV;SG;3;PST
sangloçâ	sanglocis	V;SBJV;SG;2;PRS
sintî	sintivin	V;IPFV;IND;PL;3;PST
nadâ	nadave	V;IPFV;IND;SG;3;PST
cori	corêt	V;IMP;PL;2
