jaa	jaa	V;HAB;PST
du	duee	V;HAB;NEG;PST
ŋmaa	ŋmaaee	V;HAB;NEG;FUT
ŋmɔɔ	ŋmɔɔ	V;HAB;PST
fala	falaee	V;HAB;NEG;PST
sele	sele	V;HAB;PST
lɛmɔ	lɛmɔee	V;HAB;NEG;PST
kai	kaiee	V;HAB;NEG;FUT
tsine	tsine	V;HAB;PST
bɛɛ	bɛɛ	V;HAB;PST
nuu	nuu	V;NFIN
kwɛ	kwɛ	V;HAB;PST
mɛ	baamɛ	V;HAB;FUT
wo	wo	V;HAB;PST
ŋmɔ	baaŋmɔ	V;HAB;FUT
taa	ŋtaa	V;PRS
hia	hiaee	V;HAB;NEG;PST
nu	ŋnu	V;PRS
tswa	tswaee	V;HAB;NEG;FUT
he	ŋhe	V;PRS
wa	wako	V;HAB;NEG;PRS
mɛ	mɛ	V;HAB;PRS
ya	ŋya	V;PRS
fo	foee	V;HAB;NEG;PST
diki	diki	V;HAB;PST
ye nkunim	ŋye nkunim	V;PRS
ba	ba	V;HAB;PST
ŋa	ŋŋa	V;PRS
blɛ	blɛee	V;HAB;NEG;PST
kpɛtɛ	baakpɛtɛ	V;HAB;FUT
diki	dikiee	V;HAB;NEG;FUT
ba	baee	V;HAB;NEG;PST
taa	taa	V;HAB;PRS
fo	ŋfo	V;PRS
kafo	baakafo	V;HAB;FUT
ba	baee	V;HAB;NEG;FUT
kpɛtɛ	kpɛtɛee	V;NEG;PRS
sele	seleee	V;HAB;NEG;FUT
je	je	V;HAB;PRS
hɔɔ	ŋhɔɔ	V;PRS
bo	baabo	V;HAB;FUT
ya	baaya	V;HAB;FUT
faa	baafaa	V;HAB;FUT
shamɔ	shamɔko	V;HAB;NEG;PRS
ŋmɔ	ŋmɔko	V;HAB;NEG;PRS
kafo	ŋkafo	V;PRS
mɔ	baamɔ	V;HAB;FUT
jaa	jaako	V;HAB;NEG;PRS
tswa	tswako	V;HAB;NEG;PRS
kafo	kafoko	V;HAB;NEG;PRS
nyiɛ	nyiɛ	V;HAB;PST
nuu	ŋnuu	V;PRS
mɔ	mɔ	V;NFIN
kɔ	kɔ	V;HAB;PST
kota	ŋkota	V;PRS
kota	kotaee	V;HAB;NEG;FUT
hiɛ	hiɛ	V;NFIN
futu	ŋfutu	V;PRS
tsɔse	tsɔse	V;HAB;PRS
kota	baakota	V;HAB;FUT
tsɛ	ŋtsɛ	V;PRS
fala	fala	V;HAB;PRS
tawɔ	tawɔee	V;NEG;PRS
wo	woee	V;HAB;NEG;PST
kɔ	kɔko	V;HAB;NEG;PRS
gbele	gbeleko	V;HAB;NEG;PRS
sɔle	ŋsɔle	V;PRS
ju	ju	V;HAB;PST
mi	miee	V;HAB;NEG;FUT
gblɛ	gblɛ	V;NFIN
kpɛtɛ	kpɛtɛ	V;HAB;PRS
tsine	baatsine	V;HAB;FUT
yɛ	yɛee	V;NEG;PRS
nyiɛ	baanyiɛ	V;HAB;FUT
hiɛ	hiɛko	V;HAB;NEG;PRS
gbo	gboee	V;HAB;NEG;FUT
tsuku	ŋtsuku	V;PRS
tsɔse	tsɔseko	V;HAB;NEG;PRS
ye	ye	V;HAB;PST
kane	kaneee	V;HAB;NEG;FUT
ju	ŋju	V;PRS
yɛ	yɛ	V;HAB;PST
bɔ	bɔ	V;HAB;PRS
ŋa	ŋa	V;HAB;PST
gbee	gbeeee	V;HAB;NEG;FUT
sumɔ	sumɔ	V;HAB;PRS
ju	ju	V;NFIN
ha	haee	V;NEG;PRS
nu	nu	V;HAB;PST
wɔdɔi	ŋwɔdɔi	V;PRS
je	jeee	V;HAB;NEG;FUT
fɔflɔ	ŋfɔflɔ	V;PRS
tswa	tswaee	V;HAB;NEG;PST
ye nkunim	ye nkunimee	V;HAB;NEG;FUT
ba	bako	V;HAB;NEG;PRS
fu	fu	V;HAB;PRS
jɔ	jɔ	V;HAB;PRS
tsɛ	tsɛee	V;HAB;NEG;PST
tawɔ	tawɔko	V;HAB;NEG;PRS
tsine	tsineee	V;NEG;PRS
mi	miee	V;HAB;NEG;PST
ha	ŋha	V;PRS
fɔflɔ	baafɔflɔ	V;HAB;FUT
kwɛ	kwɛko	V;HAB;NEG;PRS
tswa	tswaee	V;NEG;PRS
ye	yeee	V;HAB;NEG;PST
diki	baadiki	V;HAB;FUT
shwishwia	baashwishwia	V;HAB;FUT
je	ŋje	V;PRS
blɛ	blɛee	V;HAB;NEG;FUT
mɛ	mɛee	V;NEG;PRS
fɔflɔ	fɔflɔee	V;HAB;NEG;FUT
fɔ	baafɔ	V;HAB;FUT
ŋmaa	ŋmaa	V;HAB;PRS
futu	futu	V;HAB;PST
tsi	ŋtsi	V;PRS
wo	wo	V;HAB;PRS
jie	jieee	V;NEG;PRS
gbee	gbeeee	V;HAB;NEG;PST
daa	daa	V;HAB;PST
kane	baakane	V;HAB;FUT
ta	ta	V;NFIN
gbi	gbiko	V;HAB;NEG;PRS
hia	hia	V;HAB;PST
sele	ŋsele	V;PRS
tsɛmɔ	baatsɛmɔ	V;HAB;FUT
tsɛmɔ	tsɛmɔee	V;HAB;NEG;PST
jɔ	jɔko	V;HAB;NEG;PRS
kase	kaseee	V;HAB;NEG;PST
nuu	nuu	V;HAB;PST
da	baada	V;HAB;FUT
wie	ŋwie	V;PRS
kpasa	kpasako	V;HAB;NEG;PRS
ta	ta	V;HAB;PST
fɔflɔ	fɔflɔ	V;NFIN
hia	hiako	V;HAB;NEG;PRS
wɔlɔmɔ	wɔlɔmɔee	V;HAB;NEG;FUT
nyiɛ	nyiɛee	V;HAB;NEG;FUT
bɔ	bɔee	V;HAB;NEG;FUT
tswa	ŋtswa	V;PRS
diki	dikiee	V;HAB;NEG;PST
bi	bi	V;NFIN
tuu	tuuee	V;HAB;NEG;FUT
jɔ	baajɔ	V;HAB;FUT
kafo	kafoee	V;HAB;NEG;PST
tsɛ	tsɛ	V;HAB;PRS
bo	bo	V;NFIN
tsu	baatsu	V;HAB;FUT
jie	baajie	V;HAB;FUT
yɛ	yɛ	V;HAB;PRS
gbee	gbee	V;NFIN
sha	shaee	V;HAB;NEG;FUT
kase	kaseee	V;HAB;NEG;FUT
sha	sha	V;NFIN
bɛɛ	bɛɛee	V;HAB;NEG;PST
wie	wie	V;HAB;PST
sele	sele	V;NFIN
fo	foee	V;NEG;PRS
tsɔse	tsɔseee	V;HAB;NEG;PST
gbi	gbiee	V;HAB;NEG;FUT
futu	futu	V;HAB;PRS
hi	hi	V;NFIN
ya	yako	V;HAB;NEG;PRS
hia	hia	V;HAB;PRS
daa	daaee	V;NEG;PRS
gblɛ	gblɛee	V;NEG;PRS
sha	baasha	V;HAB;FUT
ŋmaa	ŋmaaee	V;NEG;PRS
wo	ŋwo	V;PRS
