binden	bünde	V;IND;SG;2;PST
verswinden	verswind	V;IMP;SG;2
göu	göuwe	N;NOM;PL
ziehen	zühe	V;SBJV;SG;3;PST
werfen	wërfe	V;SBJV;SG;1;PRS
slahen	geslagen	V.PTCP;PST
rinnen	rinnet	V;SBJV;SG;3;PRS
slahen	slagen	V;IND;PL;1;PRS
triegen	triegen	V;NFIN
biegen	biegen	V;IMP;PL;1
verswinden	verswindest	V;IND;SG;2;PRS
werden	würdest	V;SBJV;SG;2;PST
werfen	würfest	V;SBJV;SG;2;PST
ziehen	ziehet	V;SBJV;SG;3;PRS
verswinden	verswindet	V;IND;SG;3;PRS
burcgrave	burcgrâven	N;DAT;SG
binden	bünden	V;SBJV;PL;3;PST
swern	swüre	V;SBJV;SG;3;PST
biegen	biuget	V;IND;SG;3;PRS
enpfinden	enpfindest	V;SBJV;SG;2;PRS
verswinden	verswünden	V;SBJV;PL;3;PST
beginnen	beginnen	V;IMP;PL;1
bruoder	brüeder	N;NOM;PL
wahsen	wüehsest	V;SBJV;SG;2;PST
ziehen	ziuch	V;IMP;SG;2
werfen	wërfet	V;IMP;PL;2
kiesen	kieset	V;IMP;PL;2
sieden	siedet	V;IND;PL;2;PRS
slahen	slegest	V;IND;SG;2;PRS
swimmen	swimmest	V;IND;SG;2;PRS
binden	bindet	V;SBJV;SG;3;PRS
kiesen	kuret	V;IND;PL;2;PST
singen	sünge	V;SBJV;SG;1;PST
ziehen	ziehen	V;IND;PL;1;PRS
betriegen	betrieget	V;IMP;PL;2
betriegen	betriegende	V.PTCP;PRS
vinden	vindet	V;IMP;PL;2
slahen	sluoc	V;IND;SG;1;PST
engel	engeles	N;GEN;SG
wahsen	wahsen	V;NFIN
wahsen	wahsende	V.PTCP;PRS
triegen	triugest	V;IND;SG;2;PRS
tac	tac	N;ACC;SG
enpfinden	enpfindet	V;SBJV;SG;3;PRS
binden	bindest	V;IND;SG;2;PRS
verswinden	verswundet	V;IND;PL;2;PST
werden	würde	V;SBJV;SG;3;PST
werden	ward	V;IND;SG;1;PST
biegen	bügen	V;SBJV;PL;3;PST
biegen	bouc	V;IND;SG;1;PST
trinken	trunken	V;IND;PL;3;PST
vinden	vinde	V;IND;SG;1;PRS
vinden	vinden	V;SBJV;PL;3;PRS
swern	swerest	V;IND;SG;2;PRS
kiesen	gekorn	V.PTCP;PST
burcgrave	burcgrâven	N;ACC;PL
betriegen	betrugen	V;IND;PL;1;PST
sieden	siudest	V;IND;SG;2;PRS
rinnen	rünne	V;SBJV;SG;1;PST
betriegen	betrügen	V;SBJV;PL;1;PST
swimmen	swimmen	V;SBJV;PL;3;PRS
bruoder	bruoder	N;DAT;SG
wahsen	wahset	V;IMP;PL;2
beginnen	begunnen	V;IND;PL;1;PST
trinken	trinken	V;IND;PL;1;PRS
verswinden	verswündest	V;SBJV;SG;2;PST
triegen	trieget	V;SBJV;PL;2;PRS
swern	swüren	V;SBJV;PL;1;PST
biegen	biuc	V;IMP;SG;2
betriegen	betrüge	V;IND;SG;2;PST
göugrave	göugrâven	N;DAT;PL
vinden	vinden	V;SBJV;PL;1;PRS
burcgrave	burcgrâven	N;NOM;PL
triegen	triegen	V;IMP;PL;1
singen	süngen	V;SBJV;PL;1;PST
helfen	hülfest	V;SBJV;SG;2;PST
wahsen	wuohsen	V;IND;PL;1;PST
wahsen	wüehse	V;SBJV;SG;1;PST
slahen	slagest	V;SBJV;SG;2;PRS
grave	grâven	N;NOM;PL
rinnen	rünnet	V;SBJV;PL;2;PST
beginnen	beginnen	V;SBJV;PL;3;PRS
biegen	büge	V;SBJV;SG;3;PST
verswinden	verswindest	V;SBJV;SG;2;PRS
singen	sang	V;IND;SG;3;PST
swimmen	swamm	V;IND;SG;3;PST
swern	swuor	V;IND;SG;1;PST
sieden	sôt	V;IND;SG;3;PST
ziehen	zôch	V;IND;SG;1;PST
engel	engel	N;NOM;SG
biegen	bieget	V;SBJV;SG;3;PRS
vinden	vindet	V;SBJV;PL;2;PRS
vinden	vünde	V;SBJV;SG;1;PST
kiesen	kurn	V;IND;PL;1;PST
binden	bunden	V;IND;PL;1;PST
singen	singen	V;SBJV;PL;1;PRS
vinden	vand	V;IND;SG;1;PST
betriegen	betriegen	V;SBJV;PL;3;PRS
werden	wurden	V;IND;PL;3;PST
enpfinden	enpfündest	V;SBJV;SG;2;PST
engel	engel	N;NOM;PL
kiesen	küsen	V;SBJV;PL;1;PST
binden	bünde	V;SBJV;SG;3;PST
helfen	hëlfest	V;SBJV;SG;2;PRS
binden	binden	V;IND;PL;1;PRS
göu	göuwe	N;ACC;PL
trinken	trunken	V;IND;PL;1;PST
beginnen	beginnent	V;IND;PL;3;PRS
triegen	trieget	V;IMP;PL;2
verswinden	verswand	V;IND;SG;1;PST
göugrave	göugrâven	N;ACC;PL
biegen	biugest	V;IND;SG;2;PRS
singen	singet	V;SBJV;SG;3;PRS
verswinden	verswündet	V;SBJV;PL;2;PST
rinnen	rinnen	V;NFIN
sieden	sütet	V;SBJV;PL;2;PST
triegen	triuge	V;IND;SG;1;PRS
betriegen	betrügen	V;SBJV;PL;3;PST
werfen	wërfen	V;SBJV;PL;1;PRS
betriegen	betriegen	V;SBJV;PL;1;PRS
ziehen	ziuhest	V;IND;SG;2;PRS
überganc	übergange	N;DAT;SG
binden	binde	V;IND;SG;1;PRS
betriegen	betruget	V;IND;PL;2;PST
kiesen	kieset	V;SBJV;SG;3;PRS
enpfinden	enpfand	V;IND;SG;3;PST
enpfinden	enpfinden	V;IND;PL;1;PRS
sieden	sôt	V;IND;SG;1;PST
helfen	hulfet	V;IND;PL;2;PST
göu	göu	N;NOM;SG
beginnen	beginne	V;IND;SG;1;PRS
vinden	vinden	V;NFIN
vinden	vünden	V;SBJV;PL;1;PST
trinken	trink	V;IMP;SG;2
swern	swere	V;IND;SG;1;PRS
wahsen	wahsest	V;SBJV;SG;2;PRS
triegen	triegent	V;IND;PL;3;PRS
sieden	sieden	V;IMP;PL;1
beginnen	begünne	V;SBJV;SG;3;PST
trinken	trinkest	V;SBJV;SG;2;PRS
kiesen	kôs	V;IND;SG;3;PST
