grosche	groschi	V;SBJV;SG;1;PRS
ässe	ässid	V;SBJV;PL;3;PRS
ligge	liittid	V;SBJV;PL;1;PST
lüüte	lüütid	V;SBJV;PL;2;PRS
tue	tüegsch	V;SBJV;SG;2;PRS
schnöre	schnöred	V;IND;PL;2;PRS
lauffe	lauffsch	V;IND;SG;2;PRS
leere	leeri	V;SBJV;SG;3;PRS
verlüüre	verlüürisch	V;SBJV;SG;2;PRS
trääge	träiti	V;SBJV;SG;1;PST
zünde	zündid	V;SBJV;PL;3;PRS
bruuche	bruucht	V;IND;SG;3;PRS
schlaaffe	schlaaffe	V;IND;SG;1;PRS
bruuche	bruuchsch	V;IND;SG;2;PRS
tuusche	tuusched	V;IND;PL;2;PRS
fèèle	fèèlid	V;SBJV;PL;3;PRS
faare	faarisch	V;SBJV;SG;2;PRS
schiisse	schiissi	V;SBJV;SG;1;PRS
gsee	gsèèch	V;SBJV;SG;3;PST
lose	losisch	V;SBJV;SG;2;PRS
sitze	sitzed	V;IND;PL;2;PRS
räise	räisid	V;SBJV;PL;2;PRS
gsee	gsächsch	V;SBJV;SG;2;PRS
lauffe	lauffed	V;IND;PL;1;PRS
boue	bouisch	V;SBJV;SG;2;PRS
schnüüze	schnüüzi	V;SBJV;SG;1;PRS
wöische	wöisct	V;IND;SG;3;PRS
gèè	gisch	V;IND;SG;2;PRS
winke	winked	V;IND;PL;2;PRS
möge	möged	V;IND;PL;3;PRS
prichte	prichti	V;SBJV;SG;3;PRS
rede	reded	V;IND;PL;2;PRS
verrate	verrati	V;SBJV;SG;3;PRS
chöne	chönid	V;SBJV;PL;1;PRS
bhalte	bhalted	V;IND;PL;1;PRS
verlüüre	verlüüred	V;IND;PL;1;PRS
sii	wèèr	V;SBJV;SG;3;PST
sele	sell	V;SBJV;SG;3;PRS
uufpasse	uufpassed	V;IND;PL;1;PRS
zöisle	zöisled	V;IND;PL;2;PRS
fiire	fiired	V;IND;PL;2;PRS
lauffe	lauffi	V;SBJV;SG;1;PRS
müese	müesid	V;SBJV;PL;2;PRS
chöne	chasch	V;IND;SG;2;PRS
lauffe	lauffid	V;SBJV;PL;3;PRS
gaume	gaume	V;IND;SG;1;PRS
legge	läit	V;IND;SG;3;PRS
rede	redsch	V;IND;SG;2;PRS
lauffe	lauffed	V;IND;PL;2;PRS
schaffe	schaffi	V;SBJV;SG;1;PRS
gèè	gibe	V;IND;SG;1;PRS
bruuche	bruuchi	V;SBJV;SG;1;PRS
rüere	rüered	V;IND;PL;3;PRS
danke	dankid	V;SBJV;PL;1;PRS
güne	günid	V;SBJV;PL;1;PRS
zöisle	zöislid	V;SBJV;PL;2;PRS
staa	stöngid	V;SBJV;PL;2;PRS
trääge	träägid	V;SBJV;PL;2;PRS
butze	butzed	V;IND;PL;2;PRS
enttüüsche	enttüüschid	V;SBJV;PL;3;PRS
hälffe	hèèffid	V;SBJV;PL;3;PST
zeere	zeerid	V;SBJV;PL;1;PRS
hebe	hebed	V;IND;PL;3;PRS
ruusche	ruuschi	V;SBJV;SG;3;PRS
schwüme	schwümid	V;SBJV;PL;1;PRS
möge	möged	V;IND;PL;1;PRS
bruume	bruuet	V;IND;SG;3;PRS
hange	hangi	V;SBJV;SG;1;PRS
säge	sägi	V;SBJV;SG;1;PRS
poschte	poschted	V;IND;PL;1;PRS
bhalte	bhalted	V;IND;PL;3;PRS
zie	zienid	V;SBJV;PL;2;PRS
chratze	chratzisch	V;SBJV;SG;2;PRS
danke	dankid	V;SBJV;PL;2;PRS
zünde	zünde	V;IND;SG;1;PRS
faare	faart	V;IND;SG;3;PRS
passe	passid	V;SBJV;PL;2;PRS
finde	finded	V;IND;PL;2;PRS
faare	faarid	V;SBJV;PL;2;PRS
trööschte	trööschtisch	V;IND;SG;2;PRS
chöne	chönt	V;SBJV;SG;3;PST
biige	biigi	V;SBJV;SG;3;PRS
schnöre	schnörisch	V;SBJV;SG;2;PRS
staa	stöngisch	V;SBJV;SG;2;PRS
haa	hät	V;IND;SG;3;PRS
nütze	nützed	V;IND;PL;2;PRS
hänke	hänkid	V;SBJV;PL;2;PRS
hebe	hebid	V;SBJV;PL;1;PRS
gnüüsse	gnüüssid	V;SBJV;PL;1;PRS
lüüte	lüütid	V;SBJV;PL;3;PRS
zaale	zaalisch	V;SBJV;SG;2;PRS
möge	mögid	V;SBJV;PL;1;PRS
enttüüsche	enttüüt	V;IND;SG;3;PRS
lüüte	lüüted	V;IND;PL;3;PRS
gaa	giengid	V;SBJV;PL;1;PST
ghööre	ghööri	V;SBJV;SG;1;PRS
hange	hanged	V;IND;PL;3;PRS
staa	stiend	V;SBJV;SG;1;PST
flueche	fluechid	V;SBJV;PL;3;PRS
fale	fali	V;SBJV;SG;3;PRS
folge	folged	V;IND;PL;2;PRS
mäine	mäini	V;SBJV;SG;1;PRS
träffe	trèèffid	V;SBJV;PL;2;PST
schreie	schreiid	V;SBJV;PL;1;PRS
bhalte	bhalted	V;IND;PL;2;PRS
hänke	hänkt	V;IND;SG;3;PRS
lose	losisch	V;IND;SG;2;PRS
flueche	fluechsch	V;IND;SG;2;PRS
trucke	trucki	V;SBJV;SG;3;PRS
staa	stiendid	V;SBJV;PL;2;PST
lupfe	lupfi	V;SBJV;SG;1;PRS
bruuche	bruuchisch	V;SBJV;SG;2;PRS
schüürge	schüürged	V;IND;PL;1;PRS
zaale	zaali	V;SBJV;SG;1;PRS
lösche	löschid	V;SBJV;PL;2;PRS
schwitze	schwitzid	V;SBJV;PL;1;PRS
wone	wonid	V;SBJV;PL;3;PRS
leere	leerid	V;SBJV;PL;1;PRS
zünde	zündt	V;IND;SG;3;PRS
rö̀ö̀tle	rö̀ö̀tle	V;IND;SG;1;PRS
schaffe	schaffi	V;SBJV;SG;3;PRS
hüete	hüeted	V;IND;PL;2;PRS
choche	chochi	V;SBJV;SG;1;PRS
waarte	waartisch	V;SBJV;SG;2;PRS
tue	tèèt	V;SBJV;SG;3;PST
lösche	löschi	V;SBJV;SG;3;PRS
zügle	züglid	V;SBJV;PL;2;PRS
häize	häized	V;IND;PL;1;PRS
schiisse	schiisse	V;IND;SG;1;PRS
wüsse	wüssid	V;SBJV;PL;1;PRS
gèè	gèèb	V;SBJV;SG;1;PST
chöne	chönd	V;IND;PL;2;PRS
möge		V;IMP;SG;2
pfuuse	pfuusid	V;SBJV;PL;1;PRS
gnüüsse	gnüüssid	V;SBJV;PL;2;PRS
bruuche	bruuchi	V;SBJV;SG;3;PRS
binde	bindisch	V;SBJV;SG;2;PRS
troue	trouid	V;SBJV;PL;2;PRS
haa	hettsch	V;SBJV;SG;2;PST
lange	langi	V;SBJV;SG;1;PRS
bschiisse	bschiisse	V;IND;SG;1;PRS
gaume	gaumid	V;SBJV;PL;2;PRS
läbe	läbi	V;SBJV;SG;3;PRS
haa	heb	V;IMP;SG;2
tusche	tusche	V;IND;SG;1;PRS
zäige	zäigi	V;SBJV;SG;1;PRS
troue	troui	V;SBJV;SG;1;PRS
finde	finded	V;IND;PL;3;PRS
frö̀ö̀ge	frö̀ö̀gi	V;SBJV;SG;3;PRS
sii	seigid	V;SBJV;PL;3;PRS
gspüüre	gspüürsch	V;IND;SG;2;PRS
läse	lèès	V;SBJV;SG;3;PST
trucke	trucked	V;IND;PL;3;PRS
gaa	göngid	V;SBJV;PL;2;PRS
bschiisse	bschiissi	V;SBJV;SG;1;PRS
hole	holid	V;SBJV;PL;1;PRS
laa	las	V;IMP;SG;2
hüete	hüetisch	V;SBJV;SG;2;PRS
wäsche	wäsched	V;IND;PL;1;PRS
fange	fanged	V;IND;PL;2;PRS
räise	räisi	V;SBJV;SG;1;PRS
schläike	schläikt	V;IND;SG;3;PRS
laa	lönd	V;IND;PL;3;PRS
wüsse	wüsstisch	V;SBJV;SG;2;PST
hange	hangid	V;SBJV;PL;3;PRS
trääge	trääged	V;IND;PL;2;PRS
ruusche	ruusche	V;IND;SG;1;PRS
finde	findid	V;SBJV;PL;2;PRS
zügle	zügle	V;IND;SG;1;PRS
choo	chömid	V;SBJV;PL;3;PRS
wüsse	wüssid	V;SBJV;PL;3;PRS
uufpasse	uufpassi	V;SBJV;SG;3;PRS
tue	tüegid	V;SBJV;PL;2;PRS
uufpasse	uufpassed	V;IND;PL;2;PRS
chöie	chöiisch	V;SBJV;SG;2;PRS
winke	winki	V;SBJV;SG;1;PRS
chützle	chützlisch	V;SBJV;SG;2;PRS
gèè	gäbid	V;SBJV;PL;2;PRS
staa	stöngid	V;SBJV;PL;1;PRS
rächne	rächned	V;IND;PL;1;PRS
chratze	chratzid	V;SBJV;PL;1;PRS
lose	losi	V;SBJV;SG;1;PRS
lupfe	lupfisch	V;SBJV;SG;2;PRS
sueche	suecht	V;IND;SG;3;PRS
zäige	zäigid	V;SBJV;PL;2;PRS
chauffe	chauffi	V;SBJV;SG;3;PRS
grüesse	grüessisch	V;IND;SG;2;PRS
hälffe	hälffi	V;SBJV;SG;3;PRS
passe	passid	V;SBJV;PL;3;PRS
hebe	hebid	V;SBJV;PL;2;PRS
luege	luegi	V;SBJV;SG;3;PRS
rö̀ö̀tle	rö̀ö̀tlid	V;SBJV;PL;2;PRS
gèè	gäbid	V;SBJV;PL;1;PRS
flueche	fluechisch	V;SBJV;SG;2;PRS
legge	legge	V;IND;SG;1;PRS
schwüme	schwümi	V;SBJV;SG;1;PRS
lange	langed	V;IND;PL;1;PRS
rüere	rüerid	V;SBJV;PL;1;PRS
legge	läitid	V;SBJV;PL;1;PST
gnüüsse	gnüüt	V;IND;SG;3;PRS
soorge	soorge	V;IND;SG;1;PRS
hange	hangeet	V;IND;SG;3;PRS
ruusche	ruuschid	V;SBJV;PL;1;PRS
staa	stönd	V;IND;PL;2;PRS
bschiisse	bschiissid	V;SBJV;PL;3;PRS
läse	lèès	V;SBJV;SG;1;PST
danke	dankeet	V;IND;SG;3;PRS
höre	hörid	V;SBJV;PL;2;PRS
choche	chocet	V;IND;SG;3;PRS
säge	sägi	V;SBJV;SG;3;PRS
schwüme	schwümid	V;SBJV;PL;3;PRS
hänke	hänkid	V;SBJV;PL;3;PRS
chauffe	chauffisch	V;SBJV;SG;2;PRS
bruume	bruume	V;IND;SG;1;PRS
wüsse	wüssed	V;IND;PL;2;PRS
zünde	zündid	V;SBJV;PL;1;PRS
rö̀ö̀tle	rö̀ö̀tlid	V;SBJV;PL;3;PRS
springe	springi	V;SBJV;SG;3;PRS
gaa	gönd	V;IND;PL;1;PRS
danke	danked	V;IND;PL;1;PRS
wone	wonisch	V;SBJV;SG;2;PRS
hüete	hüeti	V;SBJV;SG;1;PRS
schäle	schäled	V;IND;PL;3;PRS
soorge	soorgsch	V;IND;SG;2;PRS
chratze	chratzed	V;IND;PL;1;PRS
räne	räni	V;SBJV;SG;3;PRS
bhalte	bhalte	V;IND;SG;1;PRS
verrate	verratid	V;SBJV;PL;1;PRS
gsee	gsächid	V;SBJV;PL;2;PRS
biige	biiged	V;IND;PL;2;PRS
tue	tüeg	V;SBJV;SG;3;PRS
nütze	nützi	V;SBJV;SG;3;PRS
faare	faari	V;SBJV;SG;1;PRS
choo	chèèmid	V;SBJV;PL;2;PST
nütze	nützed	V;IND;PL;1;PRS
räne	räne	V;IND;SG;1;PRS
ässe	ässid	V;SBJV;PL;2;PRS
tue	tuet	V;IND;SG;3;PRS
schwitze	schwitzed	V;IND;PL;1;PRS
fiire	fiirsch	V;IND;SG;2;PRS
schlaaffe	schlaaffi	V;SBJV;SG;1;PRS
hälffe	hälffi	V;SBJV;SG;1;PRS
gspüüre	gspüürid	V;SBJV;PL;3;PRS
bruuche	bruuchid	V;SBJV;PL;2;PRS
hüete	hüetid	V;SBJV;PL;1;PRS
rede	redid	V;SBJV;PL;1;PRS
danke	danke	V;IND;SG;1;PRS
häisse	häisset	V;IND;SG;3;PRS
schreie	schreiid	V;SBJV;PL;2;PRS
troue	troui	V;SBJV;SG;3;PRS
güne	günsch	V;IND;SG;2;PRS
zäige	zäiged	V;IND;PL;3;PRS
bliibe	bliibed	V;IND;PL;2;PRS
trääge	träit	V;IND;SG;3;PRS
sii	sine	V;IND;PL;3;PRS
schniide	schniided	V;IND;PL;3;PRS
läbe	läbi	V;SBJV;SG;1;PRS
rüere	rüeri	V;SBJV;SG;3;PRS
zie	zieti	V;SBJV;SG;1;PST
bliibe	bliibt	V;IND;SG;3;PRS
bruuche	bruuched	V;IND;PL;3;PRS
hälffe	hälffid	V;SBJV;PL;3;PRS
frö̀ö̀ge	frö̀ö̀gi	V;SBJV;SG;1;PRS
lache	lachi	V;SBJV;SG;3;PRS
trööschte	trööschted	V;IND;PL;3;PRS
bschiisse	bschiissisch	V;IND;SG;2;PRS
grüesse	grüessed	V;IND;PL;3;PRS
boue	boue	V;IND;SG;1;PRS
riisse	riissed	V;IND;PL;3;PRS
rächne	rächned	V;IND;PL;3;PRS
läse	läsisch	V;SBJV;SG;2;PRS
trööschte	trööschti	V;SBJV;SG;1;PRS
chauffe	chauffid	V;SBJV;PL;1;PRS
schletze	schletzed	V;IND;PL;1;PRS
lupfe	lupfsch	V;IND;SG;2;PRS
güne	günt	V;IND;SG;3;PRS
gaa	giengsch	V;SBJV;SG;2;PST
biige	biiged	V;IND;PL;1;PRS
wèèrde	wèèrded	V;IND;PL;2;PRS
schriibe	schriibed	V;IND;PL;2;PRS
käne	käni	V;SBJV;SG;3;PRS
sprütze	sprützid	V;SBJV;PL;2;PRS
springe	springid	V;SBJV;PL;2;PRS
wele	wett	V;SBJV;SG;3;PST
grüesse	grüessi	V;SBJV;SG;3;PRS
grosche	groschid	V;SBJV;PL;2;PRS
butze	butzisch	V;IND;SG;2;PRS
legge	legged	V;IND;PL;1;PRS
haa	ha	V;IND;SG;1;PRS
trääge	trääg	V;IMP;SG;2
gsee	gsèèch	V;SBJV;SG;1;PST
passe	passisch	V;SBJV;SG;2;PRS
chräble	chräbli	V;SBJV;SG;3;PRS
waarte	waarted	V;IND;PL;3;PRS
träffe	träffi	V;SBJV;SG;1;PRS
zügle	züglisch	V;IND;SG;2;PRS
läse	läsed	V;IND;PL;1;PRS
müese	müestid	V;SBJV;PL;1;PST
tue	tüend	V;IND;PL;2;PRS
verlüüre	verlüürt	V;IND;SG;3;PRS
schwitze	schwitze	V;IND;SG;1;PRS
luege	luegid	V;SBJV;PL;3;PRS
saage	saagid	V;SBJV;PL;2;PRS
choo	chömed	V;IND;PL;2;PRS
läse	lèèsid	V;SBJV;PL;2;PST
müese	müesid	V;SBJV;PL;1;PRS
choo	chömsch	V;SBJV;SG;2;PRS
nèè	nèèmid	V;SBJV;PL;3;PST
wäsche	wäschi	V;SBJV;SG;1;PRS
ghööre	ghöörid	V;SBJV;PL;1;PRS
grosche	grosched	V;IND;PL;2;PRS
räise	räist	V;IND;SG;3;PRS
gnüüsse	gnüüssed	V;IND;PL;3;PRS
schaffe	schaffid	V;SBJV;PL;1;PRS
schlaaffe	schlaafft	V;IND;SG;3;PRS
winke	winkid	V;SBJV;PL;1;PRS
waarte	waartid	V;SBJV;PL;3;PRS
luege	lueged	V;IND;PL;3;PRS
büeze	büezet	V;IND;SG;3;PRS
chräble	chräblid	V;SBJV;PL;2;PRS
zügle	züglid	V;SBJV;PL;3;PRS
butze	butzed	V;IND;PL;3;PRS
sele	sell	V;IND;SG;3;PRS
schäle	schälid	V;SBJV;PL;1;PRS
gèè	gäbid	V;SBJV;PL;3;PRS
schnöre	schnörid	V;SBJV;PL;3;PRS
sitze	sitzid	V;SBJV;PL;1;PRS
schüürge	schüürgi	V;SBJV;SG;3;PRS
hole	holid	V;SBJV;PL;3;PRS
träffe	träffi	V;SBJV;SG;3;PRS
prichte	prichte	V;IND;SG;1;PRS
bruume	bruumid	V;SBJV;PL;2;PRS
früüre	früüri	V;SBJV;SG;1;PRS
chratze	chratzid	V;SBJV;PL;2;PRS
tue	tèètid	V;SBJV;PL;3;PST
gsee	gseend	V;IND;PL;1;PRS
sueche	sueched	V;IND;PL;1;PRS
waarte	waarti	V;SBJV;SG;3;PRS
schlaaffe	schlaaffid	V;SBJV;PL;2;PRS
ässe	èèss	V;SBJV;SG;3;PST
biige	biigid	V;SBJV;PL;2;PRS
troue	trout	V;IND;SG;3;PRS
ässe	èèss	V;SBJV;SG;1;PST
pfuuse	pfuused	V;IND;PL;2;PRS
fange	fangt	V;IND;SG;3;PRS
schiisse	schiissid	V;SBJV;PL;2;PRS
müese	müesid	V;SBJV;PL;3;PRS
versoorge	versoorgisch	V;SBJV;SG;2;PRS
tüüsche	tüüschisch	V;IND;SG;2;PRS
binde	bindt	V;IND;SG;3;PRS
trööschte	trööschted	V;IND;PL;1;PRS
gèè	gèèbid	V;SBJV;PL;1;PST
höre	höre	V;IND;SG;1;PRS
ässe	èèssid	V;SBJV;PL;3;PST
lose	loseet	V;IND;SG;3;PRS
staa	staasch	V;IND;SG;2;PRS
zie	zietid	V;SBJV;PL;1;PST
häisse	häissed	V;IND;PL;3;PRS
chräble	chräblisch	V;SBJV;SG;2;PRS
güne	günid	V;SBJV;PL;3;PRS
hüete	hüeti	V;SBJV;SG;3;PRS
schwitze	schwitt	V;IND;SG;3;PRS
choo	chèèm	V;SBJV;SG;1;PST
uufpasse	uufpassisch	V;SBJV;SG;2;PRS
bruume	bruumsch	V;IND;SG;2;PRS
zie	ziet	V;IND;SG;3;PRS
müese	muesch	V;IMP;SG;2
legge	leggi	V;SBJV;SG;1;PRS
träffe	triffe	V;IND;SG;1;PRS
trucke	truckid	V;SBJV;PL;1;PRS
lösche	lösched	V;IND;PL;1;PRS
sii	wèèrsch	V;SBJV;SG;2;PST
winke	winkid	V;SBJV;PL;2;PRS
rächne	rächned	V;IND;PL;2;PRS
träffe	träffed	V;IND;PL;1;PRS
butze	butze	V;IND;SG;1;PRS
luure	luure	V;IND;SG;1;PRS
lange	langed	V;IND;PL;2;PRS
tue	tèètid	V;SBJV;PL;1;PST
lüüte	lüüti	V;SBJV;SG;3;PRS
rö̀ö̀tle	rö̀ö̀tli	V;SBJV;SG;3;PRS
höre	höred	V;IND;PL;2;PRS
chotze	chotzed	V;IND;PL;1;PRS
haa	heb	V;SBJV;SG;3;PRS
ässe	ässed	V;IND;PL;1;PRS
