kevät	keväiks	N;TRANS;PL
mäki	mäkkee	N;IN+ALL;SG
jää	jäilt	N;AT+ABL;PL
hammaz	hampahalle	N;AT+ALL;SG
kukka	kukaaz	N;IN+ESS;SG
leipä	leippää	N;PRT;SG
lupa	luppaa	N;PRT;SG
jalka	jaloille	N;AT+ALL;PL
ikä	ikääz	N;IN+ESS;SG
iez	ikehiil	N;AT+ESS;PL
daatša	daatšast	N;IN+ABL;SG
nain	naizilt	N;AT+ABL;PL
seppä	seppoja	N;PRT;PL
kaunehusse	kaunehuksille	N;AT+ALL;PL
öö	öötä	N;PRT;SG
seppä	sepälle	N;AT+ALL;SG
variz	varikseel	N;AT+ESS;SG
pää	päälle	N;AT+ALL;SG
kaunehusse	kaunehuksii	N;IN+ALL;PL
lapsi	lapseen	N;ESS;SG
meez	meehiä	N;PRT;PL
tüär	tüttääret	N;NOM;PL
korppi	korpilt	N;AT+ABL;SG
näkö	näkkööää	N;PRT;SG
voi	voist	N;IN+ABL;PL
meez	meehille	N;AT+ALL;PL
ikä	ikält	N;AT+ABL;SG
lammaz	lampahiil	N;AT+ESS;PL
kassen	kastmelt	N;AT+ABL;SG
jalka	jalalle	N;AT+ALL;SG
korppi	korppiloja	N;PRT;PL
maa	maalle	N;AT+ALL;SG
pökköiheinä	pökköiheinääz	N;IN+ESS;SG
daatša	daatšoja	N;PRT;PL
hüvä	hüviiz	ADJ;IN+ESS;PL
kaunehusse	kaunehuen	N;GEN;SG
käzi	käen	N;GEN;SG
kevät	keväeel	N;AT+ESS;SG
lammaz	lampahaaz	N;IN+ESS;SG
silmä	silmmiin	N;ESS;PL
seppä	sepäst	N;IN+ABL;SG
hüvä	hüvälle	ADJ;AT+ALL;SG
iez	ikkeehen	N;GEN;SG
tüär	tütäresse	N;IN+ALL;SG
järvi	järvilöjä	N;PRT;PL
velli	vellilöil	N;AT+ESS;PL
hammaz	hampahaaz	N;IN+ESS;SG
säkki	säkkii	N;IN+ALL;SG
hammaz	hampahaks	N;TRANS;SG
vezi	vezi	N;NOM;SG
velli	velli	N;NOM;SG
voi	voin	N;ESS;SG
izä	izääl	N;AT+ESS;SG
kassen	kastmet	N;NOM;PL
leipä	leippiin	N;GEN;PL
aika	aijjoilt	N;AT+ABL;PL
velli	vellilöjä	N;PRT;PL
kukka	kukiiz	N;IN+ESS;PL
leipä	leippiiä	N;PRT;PL
aampuussen	aampuustmiiz	N;IN+ESS;PL
ikä	ikiks	N;TRANS;PL
pökköiheinä	pökköiheiniil	N;AT+ESS;PL
voi	voi	N;NOM;SG
izä	izöille	N;AT+ALL;PL
jalka	jalkoja	N;PRT;PL
kaunehusse	kaunehuttee	N;IN+ALL;SG
meez	meehiks	N;TRANS;PL
leipä	leiviks	N;TRANS;PL
ikä	ikkää	N;IN+ALL;SG
jää	jäijjen	N;GEN;PL
mäki	mäki	N;NOM;SG
voi	voijjen	N;GEN;PL
juusso	juusoks	N;TRANS;SG
päivä	päiville	N;AT+ALL;PL
lupa	luppaal	N;AT+ESS;SG
päivä	päivän	N;GEN;SG
süän	süämeez	N;IN+ESS;SG
kaunehusse	kaunehuelt	N;AT+ABL;SG
käzi	käeel	N;AT+ESS;SG
kaunehusse	kaunehuksiil	N;AT+ESS;PL
maa	maaz	N;IN+ESS;SG
tüär	tütäreel	N;AT+ESS;SG
lapsi	lapset	N;NOM;PL
meez	meehen	N;GEN;SG
süän	süämille	N;AT+ALL;PL
ikkuna	ikkunoin	N;GEN;PL
maa	maijen	N;GEN;PL
joki	joet	N;NOM;PL
tähti	täheks	N;TRANS;SG
hüvä	hüvvää	ADJ;PRT;SG
siar	sissaaret	N;NOM;PL
hüvä	hüväst	ADJ;IN+ABL;SG
kassen	kastmilt	N;AT+ABL;PL
nain	naizet	N;NOM;PL
korppi	korpist	N;IN+ABL;SG
ikkuna	ikkunaan	N;ESS;SG
variz	variksest	N;IN+ABL;SG
jää	jäihe	N;IN+ALL;PL
leipä	leiviiz	N;IN+ESS;PL
tähti	tähelle	N;AT+ALL;SG
luu	luil	N;AT+ESS;PL
vezi	veet	N;NOM;PL
lupa	luppaaz	N;IN+ESS;SG
korppi	korpille	N;AT+ALL;SG
kuu	kuuha	N;IN+ALL;SG
korppi	korppiloil	N;AT+ESS;PL
tüär	tütäriil	N;AT+ESS;PL
säkki	säkiks	N;TRANS;SG
pökköiheinä	pökköiheiniiä	N;PRT;PL
nain	naisee	N;IN+ALL;SG
siar	sizareel	N;AT+ESS;SG
lumi	lumiloja	N;PRT;PL
daatša	daatšaaz	N;IN+ESS;SG
säkki	säkist	N;IN+ABL;SG
öö	öihe	N;IN+ALL;PL
öö	ööz	N;IN+ESS;SG
variz	variksiil	N;AT+ESS;PL
kala	kaloille	N;AT+ALL;PL
silmä	silmmäin	N;GEN;PL
velli	vellilöiks	N;TRANS;PL
kaunehusse	kaunehueez	N;IN+ESS;SG
tähti	täheez	N;IN+ESS;SG
kevät	keväii	N;IN+ALL;PL
maa	maihe	N;IN+ALL;PL
kaunehusse	kaunehuksiin	N;GEN;PL
mäki	mäkilöin	N;ESS;PL
aika	aijjalle	N;AT+ALL;SG
joki	jokiloille	N;AT+ALL;PL
ikkuna	ikkunoille	N;AT+ALL;PL
silmä	silmille	N;AT+ALL;PL
päivä	päivää	N;PRT;SG
luu	luihe	N;IN+ALL;PL
joki	jokiloist	N;IN+ABL;PL
tüär	tütäreks	N;TRANS;SG
järvi	järvet	N;NOM;PL
velli	vellelle	N;AT+ALL;SG
velli	vellilöilt	N;AT+ABL;PL
lumi	lunt	N;PRT;SG
juusso	juussoo	N;IN+ALL;SG
kaunehusse	kaunehueks	N;TRANS;SG
päivä	päiviin	N;GEN;PL
daatša	daatšoin	N;GEN;PL
mäki	mäkilöist	N;IN+ABL;PL
süän	süämmiia	N;PRT;PL
käzi	käest	N;IN+ABL;SG
kassen	kastmeen	N;ESS;SG
tähti	tähilöilt	N;AT+ABL;PL
kevät	keväesse	N;IN+ALL;SG
järvi	järvilöis	N;IN+ESS;PL
näkö	näöks	N;TRANS;SG
vezi	vessiin	N;GEN;PL
tähti	tähet	N;NOM;PL
lumi	lumiloihe	N;IN+ALL;PL
juusso	juussoloist	N;IN+ABL;PL
säkki	säkkilöil	N;AT+ESS;PL
siar	sizaria	N;PRT;PL
käzi	käeks	N;TRANS;SG
päivä	päänä	N;ESS;SG
meez	meehelt	N;AT+ABL;SG
daatša	daatšoiz	N;IN+ESS;PL
näkö	näkölöilt	N;AT+ABL;PL
meez	meehesse	N;IN+ALL;SG
lupa	luviks	N;AT+ABL;PL
jää	jääst	N;IN+ABL;SG
luu	luult	N;AT+ABL;SG
kala	kalalt	N;AT+ABL;SG
maa	maist	N;IN+ABL;PL
lammaz	lampahisse	N;IN+ALL;PL
luu	luut	N;NOM;PL
joki	joeks	N;TRANS;SG
jalka	jalkaa	N;IN+ALL;SG
ikä	ikkiin	N;ESS;PL
päivä	päiväst	N;IN+ABL;SG
aampuussen	aampuustmiin	N;GEN;PL
ikkuna	ikkunaa	N;IN+ALL;SG
aika	aijjast	N;IN+ABL;SG
voi	voilt	N;AT+ABL;SG
mäki	mäkkiiä	N;PRT;SG
olut	oluizilt	N;AT+ABL;PL
ikä	ikilt	N;AT+ABL;PL
lammaz	lampahilt	N;AT+ABL;PL
tähti	tähilöjä	N;PRT;PL
kuu	kuille	N;AT+ALL;PL
lammaz	lampahalt	N;AT+ABL;SG
joki	joelt	N;AT+ABL;SG
kukka	kukalt	N;AT+ABL;SG
luu	luuhu	N;IN+ALL;SG
karhu	karhu	N;NOM;SG
hüvä	hüvvii	ADJ;IN+ALL;PL
käzi	kässiin	N;ESS;PL
pökköiheinä	pökköiheinille	N;AT+ALL;PL
hammaz	hampahaal	N;AT+ESS;SG
lapsi	lapseel	N;AT+ESS;SG
mäki	mäest	N;IN+ABL;SG
lupa	luppiin	N;GEN;PL
olut	olutta	N;PRT;SG
süän	süämelt	N;AT+ABL;SG
kala	kallaan	N;ESS;SG
seppä	sepoil	N;AT+ESS;PL
variz	variz	N;NOM;SG
seppä	sepäks	N;TRANS;SG
siar	sizariin	N;GEN;PL
järvi	järvilöil	N;AT+ESS;PL
süän	süänt	N;PRT;SG
kala	kalan	N;GEN;SG
maa	maan	N;GEN;SG
joki	jokiloja	N;PRT;PL
nain	naizille	N;AT+ALL;PL
luu	luilt	N;AT+ABL;PL
tüär	tütärisse	N;IN+ALL;PL
seppä	seppään	N;ESS;SG
olut	oluiziin	N;ESS;PL
pökköiheinä	pökköiheinälle	N;AT+ALL;SG
meez	meehilt	N;AT+ABL;PL
karhu	karhuuz	N;IN+ESS;SG
daatša	daatšaan	N;ESS;SG
jää	jääl	N;AT+ESS;SG
kala	kaloil	N;AT+ESS;PL
tüär	tütäriin	N;GEN;PL
daatša	daatšalt	N;AT+ABL;SG
lupa	luvast	N;IN+ABL;SG
vezi	vessii	N;IN+ALL;PL
nain	naiziks	N;TRANS;PL
lupa	luvist	N;IN+ESS;PL
