ಹೋಗು	ಹೋಗುವರು	V;MASC;PL;3;FUT
ಆಗು	ಆಗಿಯೇವು	V;PL;1;FUT
ಸಾಯಿಸು	ಸಾಯಿಸಿಯಾವು	V;NEUT;PL;3;FUT
ಕೊಡು	ಅವಳು	V;FEM;POT;SG;3
ನಡೆ	ನೀವು	V;POT;PL;2
ಆಗು	ನಾನು	V;SG;1;POS
ಆಗಮಿಸು	ಆಗಮಿಸುವಾ	V;IMP;PL;1
ಘೂಕ	ಘೂಕಗಳು	N;NOM;PL
ಕರೆ	ಕರೆಯುವ	V;MASC;SG;3;FUT
ತೊಳೆ	ತೊಳೆಯುವುವು	V;NEUT;PL;3;FUT
ಕೆಮ್ಮು	ಕೆಮ್ಮುವುವು	V;NEUT;PL;3;FUT
ಕೇಳು	ಕೇಳುತ್ತೀರಿ	V;PL;2;PRS
ಸಾಯಿಸು	ಸಾಯಿಸಿದರು	V;FEM;PL;3;PST
ಕಾಪಾಡು	ಕಾಪಾಡುವುದು	V;NEUT;SG;3;FUT
ಕೆಮ್ಮು	ನೀನು	V;SG;2;POS
ಪುಷ್ಕರಿಣಿ	ಪುಷ್ಕರಿಣಿಯ	N;GEN;SG
ಹಾಡು	ಹಾಡವು	V;NEUT;PL;3
ಆಗು	ಅವಳು	V;FEM;SG;3;POS
ಹೊರಡು	ನಾನು	V;SG;1;POS
ಕಾಡು	ಅವನು	V;MASC;POT;SG;3
ಹೇಳು	ಹೇಳಿದರೆ	V;NFIN;COND
ಬಯಸು	ಬಯಸಲು	V;NFIN
ಹಲ್ಲು	ಹಲ್ಲುಗಳ	N;GEN;PL
ಕೇಳು	ಕೇಳನು	V;MASC;SG;3
ಮಡಿಮಾಡು	ನೀವು	V;IMP;PL;2
ಬಂಬು	ಬಂಬುಗಳು	N;NOM;PL
ಆಗು	ಆದೆ	V;SG;2;PST
ಈಡಾಡು	ಅವರು	V;MASC;PL;3;POS
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಿಯೇನು	V;SG;1;FUT
ಹಾಲು	ಹಾಲಿನ	N;GEN;SG
ತೊಳೆ	ತೊಳೆಯುವುದು	V;NEUT;SG;3;FUT
ಹೋಗು	ನಾವು	V;POT;PL;1
ಸಾಯಿಸು	ಸಾಯಿಸೆವು	V;PL;1
ತೊಳೆ	ತೊಳೆಯಳು	V;FEM;SG;3
ಮಗ	ಮಗನು	N;NOM;SG
ಆಗು	ಆದನು	V;MASC;SG;3;PST
ಆಗಮಿಸು	ಆಗಮಿಸುತ್ತೀಯೆ	V;SG;2;PRS
ಓದು	ಓದಿದಿ	V;SG;2;PST
ಗಾಳಿ	ಗಾಳಿಯಿಂದ	N;INS;SG
ಕಾಡು	ಕಾಡನ್ನು	N;ACC;SG
ಕೊಡು	ಕೊಟ್ಟರು	V;MASC;PL;3;PST
ಆಗಮಿಸು	ಅವಳು	V;FEM;SG;3;NEG
ಕುಡಿ	ಕುಡಿಯವು	V;NEUT;PL;3
ನಾಯಿ	ನಾಯಿಗಳನ್ನು	N;ACC;PL
ವಿಮುಕ್ತಿ	ವಿಮುಕ್ತಿಯ	N;GEN;SG
ಸಾಯಿಸು	ಸಾಯಿಸುವಿ	V;SG;2;FUT
ಆಯಿಸು	ಆಯಿಸುವುವು	V;NEUT;PL;3;FUT
ಓಡು	ಓಡುತ್ತದೆ	V;NEUT;SG;3;PRS
ಕಾಡು	ಕಾಡುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ತಂಡೆ	ತಂಡೆಗಳಿಂದ	N;INS;PL
ಬಯಸು	ಬಯಸಿದರು	V;MASC;PL;3;PST
ನಡೆ	ನಡೆಯುವಿ	V;SG;2;FUT
ತಡೆ	ತಡೆದುವು	V;NEUT;PL;3;PST
ಕನಸು	ಕನಸುಗಳನ್ನು	N;ACC;PL
ಬೆಂಕಿ	ಬೆಂಕಿಗಳು	N;NOM;PL
ತೊಳೆ	ನೀನು	V;SG;2;NEG
ಓಡು	ಓಡಿದರು	V;MASC;PL;3;PST
ಚದರು	ಚದರುವಿರಿ	V;PL;2;FUT
ನಾಯಿ	ನಾಯಿಯ	N;GEN;SG
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡುವೆ	V;SG;1;FUT
ಆದಿ	ಆದಿಗಳಿಂದ	N;INS;PL
ಕೇಳು	ಕೇಳಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಹೆಸರಿಸು	ಹೆಸರಿಸಿಯಾವು	V;NEUT;PL;3;FUT
ಈಡಾಡು	ಈಡಾಡಿಯಾರು	V;MASC;PL;3;FUT
ಪಡಿಯಚ್ಚು	ಪಡಿಯಚ್ಚುಗಳು	N;NOM;PL
ದಾಟು	ದಾಟುವಳು	V;FEM;SG;3;FUT
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ಅವರು	V;FEM;PL;3;NEG
ಬೆವರು	ಬೆವರುಗಳಿಂದ	N;INS;PL
ಹಾಡು	ಹಾಡನು	V;MASC;SG;3
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸಿಯೇನು	V;SG;1;FUT
ಸೂರ್ಯಧಾತು	ಸೂರ್ಯಧಾತುಗಳನ್ನು	N;ACC;PL
ಓಡು	ಓಡುತ್ತೇನೆ	V;SG;1;PRS
ವಿದ್ಯುತ್ತು	ವಿದ್ಯುತ್ತುಗಳು	N;NOM;PL
ಮಡಿಮಾಡು	ಮಡಿಮಾಡುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಹೊರಡು	ಹೊರಡರು	V;FEM;PL;3
ಪುಸ್ತಕ	ಪುಸ್ತಕದ	N;GEN;SG
ಬಯಸು	ಅವರು	V;MASC;PL;3;NEG
ಆದಿ	ಆದಿಗಳನ್ನು	N;ACC;PL
ಗೆಲ್ಲು	ಗೆಲ್ಲುವೆ	V;SG;2;FUT
ಚಲ್ಲು	ಚಲ್ಲಲಿ	V;NFIN;OPT
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಲು	V;NFIN
ಚಲ್ಲು	ಚಲ್ಲುತ್ತೀರಿ	V;PL;2;PRS
ಈಡಾಡು	ಈಡಾಡಿಯಾರು	V;FEM;PL;3;FUT
ಈಜು	ಈಜುತ್ತೇನೆ	V;SG;1;PRS
ನಡೆ	ಅವು	V;NEUT;PL;3;POS
ಆಗಮಿಸು	ನಾನು	V;IMP;SG;1
ಟೊಣೆ	ನೀನು	V;IMP;SG;2
ನಾಯಿ	ನಾಯಿಗಳಿಂದ	N;INS;PL
ಉಗುರು	ಉಗುರುಗಳಿಂದ	N;INS;PL
ನೋಡು	ನೋಡಿಯಾನು	V;MASC;SG;3;FUT
ಹೋಗು	ಅವರು	V;MASC;POT;PL;3
ತಡೆ	ತಡೆಯುವಿರಿ	V;PL;2;FUT
ಉಪಯೋಗ	ಉಪಯೋಗವು	N;NOM;SG
ಗೆಳೆತನ	ಗೆಳೆತನವನ್ನು	N;ACC;SG
ಕೇಳು	ನೀವು	V;PL;2;POS
ಚಲ್ಲು	ಚಲ್ಲುವಳು	V;FEM;SG;3;FUT
ಅಗ್ನಿ	ಅಗ್ನಿಯರು	N;NOM;PL
ಈಜು	ಅವರು	V;MASC;POT;PL;3
ಗೆಲ್ಲು	ನಾನು	V;SG;1;NEG
ಕಾಪಾಡು	ಅವಳು	V;FEM;SG;3;NEG
ಮೀ	ಮೀಯಲಿ	V;NFIN;OPT
ಪರ್ವತ	ಪರ್ವತಗಳನ್ನು	N;ACC;PL
ಕೊಲ್ಲು	ಅವರು	V;MASC;PL;3;POS
ಮೀ	ಮಿಂದಿ	V;SG;2;PST
ಕಾಡು	ಕಾಡುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಹಾಡು	ಹಾಡುವೆವು	V;PL;1;FUT
ನಡೆ	ನಡೆದೆ	V;SG;1;PST
ಕೇಳು	ಕೇಳೋಣ	V;IMP;PL;1
ಕರೆ	ನಾವು	V;IMP;PL;1
ಅಂಟು	ಅಂಟುವಿರಿ	V;PL;2;FUT
ತಾಯಿ	ತಾಯಿಯಿಂದ	N;INS;SG
ಬಿರುಗಾಳಿ	ಬಿರುಗಾಲಿಗಳು	N;NOM;PL
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡೀತು	V;NEUT;SG;3;FUT
ತೊಳೆ	ತೊಳೆಯನು	V;MASC;SG;3
ಹೊರಡು	ಹೊರಡೀರಿ	V;PL;2;FUT
ಈಜು	ನೀನು	V;SG;2;POS
ಹೊರಡು	ಹೊರಡವು	V;NEUT;PL;3
ಗೆಲ್ಲು	ಗೆದ್ದರೆ	V;NFIN;COND
ಓಡು	ಅವರು	V;MASC;PL;3;POS
ಕೊಲ್ಲು	ಕೊಂದೆ	V;SG;1;PST
ಸೂರ್ಯ	ಸೂರ್ಯಗಳನ್ನು	N;ACC;PL
ಕೊಡು	ಕೊಡುತ್ತವೆ	V;NEUT;PL;3;PRS
ಮರ	ಮರಗಳಿಂದ	N;INS;PL
ಗೆಲ್ಲು	ಗೆಲ್ಲುವರು	V;MASC;PL;3;FUT
ಪುಸ್ತಕ	ಪುಸ್ತಕಗಳಿಗೆ	N;DAT;PL
ಬಯಕೆ	ಬಯಕೆಗಳಿಂದ	N;INS;PL
ಅಗ್ನಿ	ಅಗ್ನಿಯರಿಂದ	N;INS;PL
ಕರೆ	ಕರೆದಿ	V;SG;2;PST
ಹಾಡು	ಹಾಡುತ್ತೀ	V;SG;2;PRS
ಕೊಲ್ಲು	ಕೊಂದನು	V;MASC;SG;3;PST
ಘೂಕ	ಘೂಕವು	N;NOM;SG
ಬೆಣ್ಣೆ	ಬೆಣ್ಣೆಗೆ	N;DAT;SG
ನೋಡು	ನೋಡುವರು	V;FEM;PL;3;FUT
ಹೆಸರಿಸು	ಹೆಸರಿಸಿದನು	V;MASC;SG;3;PST
ಕಾಡು	ಕಾಡಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಆಗು	ಆಗಿರಿ	V;IMP;PL;2
ಕೊಡು	ಕೊಡುತ್ತೀ	V;SG;2;PRS
ಮಡಿಮಾಡು	ಮಡಿಮಾಡಿದರೆ	V;NFIN;COND
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸುವನು	V;MASC;SG;3;FUT
ಟೊಣೆ	ನೀನು	V;POT;SG;2
ಹಾಡು	ಹಾಡೋಣ	V;IMP;PL;1
ಹೇಳು	ನೀನು	V;SG;2;POS
ಹೆಸರಿಸು	ಹೆಸರಿಸಿದರು	V;FEM;PL;3;PST
ಗೆಲ್ಲು	ಅವರು	V;FEM;POT;PL;3
ಉಪಯೋಗ	ಉಪಯೋಗಗಳಿಂದ	N;INS;PL
ಹೊರಡು	ನೀನು	V;IMP;SG;2
ಪರ್ವತ	ಪರ್ವತವನ್ನು	N;ACC;SG
ಆಗು	ನೀನು	V;SG;2;POS
ಕಾಪಾಡು	ಕಾಪಾಡಿದೆ	V;SG;1;PST
ಕುಡಿ	ಕುಡಿಯುವೆವು	V;PL;1;FUT
ಆಯಿಸು	ಆಯಿಸುವೆನು	V;SG;1;FUT
ಮಾಡು	ಮಾಡಿದಳು	V;FEM;SG;3;PST
ತುತ್ತೂರಿ	ತುತ್ತೂರಿಗಳನ್ನು	N;ACC;PL
ಎಲೆ	ಎಲೆಯನ್ನು	N;ACC;SG
ಕಾಡು	ಕಾಡರು	V;FEM;PL;3
ಟೊಣೆ	ನಾನು	V;IMP;SG;1
ಕರೆ	ಕರೆಯೋಣ	V;IMP;PL;1
ಕಾಪು	ಕಾಪುಗಳನ್ನು	N;ACC;PL
ಓದು	ಅದು	V;NEUT;POT;SG;3
ಬಿದು	ಬಿದುಗಳಿಗೆ	N;DAT;PL
ಮಗು	ಮಗುವು	N;NOM;SG
ಯಾತ್ರಾರ್ಥಿ	ಯಾತ್ರಾರ್ಥಿಗಳಿಗೆ	N;DAT;PL
ವನ	ವನದಿಂದ	N;INS;SG
ಕುಡಿ	ಕುಡಿಯುತ್ತಾರೆ	V;MASC;PL;3;PRS
ಕೆಮ್ಮು	ನೀನು	V;SG;2;NEG
ಕೆಮ್ಮು	ಅವಳು	V;FEM;SG;3;NEG
ಕರೆ	ಕರೆಯುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಸಾಯಿಸು	ಅವಳು	V;FEM;SG;3;NEG
ಬೆಣ್ಣೆ	ಬೆಣ್ಣೆಗಳಿಂದ	N;INS;PL
ಸಿಂಹ	ಸಿಂಹವು	N;NOM;SG
ಬಯಸು	ಬಯಸಿಯೇವು	V;PL;1;FUT
ಈಜು	ಈಜುವೆವು	V;PL;1;FUT
ಆಯಿಸು	ಆಯಿಸಲು	V;NFIN
ಕೊಡು	ಕೊಡುವಾ	V;IMP;PL;1
ಈಜು	ಅದು	V;NEUT;POT;SG;3
ಚಲ್ಲು	ನೀನು	V;SG;2;POS
ಆಗಮಿಸು	ಆಗಮಿಸವು	V;NEUT;PL;3
ಈಜು	ನಾವು	V;PL;1;POS
ಹೊರಡು	ಹೊರಟ್ಟೆ	V;SG;2;PST
ತೊಳೆ	ತೊಳೆದಿರಿ	V;PL;2;PST
ಓಡು	ಓಡಲಿ	V;NFIN;OPT
ನೋಡು	ನೋಡುವಿ	V;SG;2;FUT
ಇಳಿ	ನೀನು	V;SG;2;NEG
ಚದರು	ಚದರಿಯಾನು	V;MASC;SG;3;FUT
ಕಂಪ	ಕಂಪದಿಂದ	N;INS;SG
ತಡೆ	ತಡೆದೇನು	V;SG;1;FUT
ಯುರೋಪ	ಯುರೋಪಗಳ	N;GEN;PL
ಎಲೆ	ಎಲೆಗಳಿಂದ	N;INS;PL
ನಿಯಮ	ನಿಯಮದ	N;GEN;SG
ಗೆಲ್ಲು	ಗೆಲ್ಲುತ್ತವೆ	V;NEUT;PL;3;PRS
ದಾಟು	ದಾಟಿದ	V;MASC;SG;3;PST
ಹುಟ್ಟು	ಹುಟ್ಟಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಶಕ್ತಿ	ಶಕ್ತಿಯು	N;NOM;SG
ಓಡು	ಅವಳು	V;FEM;SG;3;NEG
ಓಡು	ಓಡುತ್ತೇವೆ	V;PL;1;PRS
ನೋಡು	ನೋಡುವೆ	V;SG;2;FUT
ಹೋಗು	ನಾವು	V;PL;1;NEG
ಇಳಿ	ನಾವು	V;POT;PL;1
ಕಾಪಾಡು	ಕಾಪಾಡಳು	V;FEM;SG;3
ಚಲ್ಲು	ಚಲ್ಲುತ್ತೀಯೆ	V;SG;2;PRS
ಚದರು	ಚದರಿಯಾವು	V;NEUT;PL;3;FUT
ಹೊರಡು	ಹೊರಡೆ	V;SG;1
ಅಂಟು	ಅವು	V;NEUT;PL;3;POS
ಹೊರಡು	ನಾವು	V;IMP;PL;1
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡರಿ	V;PL;2
ಟೊಣೆ	ಅವನು	V;MASC;POT;SG;3
ಓದು	ಓದುತ್ತಾರೆ	V;MASC;PL;3;PRS
ನಡೆ	ನಡೆಯುತ್ತೇವೆ	V;PL;1;PRS
ಹಾಡು	ಹಾಡಿದರು	V;FEM;PL;3;PST
ಆಗು	ಆಗನು	V;MASC;SG;3
ಹೇಳು	ಹೇಳುತ್ತದೆ	V;NEUT;SG;3;PRS
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಳು	V;FEM;SG;3
ಕಾಪು	ಕಾಪಿನಿಂದ	N;INS;SG
ಓಡು	ಓಡುತ್ತೀ	V;SG;2;PRS
ಹೊರಡು	ಅದು	V;NEUT;POT;SG;3
ಮಡಿಮಾಡು	ಮಡಿಮಾಡೆವು	V;PL;1
ಸಂದೇಹ	ಸಂದೇಹವನ್ನು	N;ACC;SG
ಚಲ್ಲು	ಅವರು	V;FEM;POT;PL;3
ಬಯಸು	ಬಯಸುವುವು	V;NEUT;PL;3;FUT
ಹೇಳು	ಅವಳು	V;FEM;SG;3;NEG
ತೊಳೆ	ನಾವು	V;PL;1;NEG
ಹಾಡು	ಹಾಡೀರಿ	V;PL;2;FUT
ಆಯಿಸು	ಆಯಿಸಳು	V;FEM;SG;3
ಕೊಡು	ಅದು	V;NEUT;SG;3;NEG
ಬಿರುಗಾಳಿ	ಬಿರುಗಾಲಿಗಳನ್ನು	N;ACC;PL
ಕಾಪು	ಕಾಪು	N;NOM;SG
ಕರೆ	ಕರೆದ	V;MASC;SG;3;PST
ಆಯಿಸು	ಆಯಿಸಿರಿ	V;IMP;PL;2
ಕುಡಿ	ನಾವು	V;IMP;PL;1
ಮಾಡು	ಮಾಡಿದೆನು	V;SG;1;PST
ಮಗು	ಮಕ್ಕಳ	N;GEN;PL
ಕೇಳು	ನೀನು	V;IMP;SG;2
ಓಡು	ಓಡರಿ	V;PL;2
ಹೋಗು	ಹೋಗಿಯಾನು	V;MASC;SG;3;FUT
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡುವಿರಿ	V;PL;2;FUT
ಅಂಗ	ಅಂಗವು	N;NOM;SG
ಕಾಡು	ಅವರು	V;FEM;PL;3;POS
ತೊಳೆ	ತೊಳೆದಳು	V;FEM;SG;3;PST
ದಾಟು	ದಾಟುತ್ತೀರಿ	V;PL;2;PRS
ಈಡಾಡು	ಅವಳು	V;FEM;SG;3;POS
ತೊಳೆ	ತೊಳೆದ	V;MASC;SG;3;PST
ನೀರು	ನೀರುಗಳ	N;GEN;PL
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸ	V;MASC;SG;3
ಚದರು	ಚದರುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಕೆಮ್ಮು	ಕೆಮ್ಮುಗಳ	N;GEN;PL
ಆಯಿಸು	ಆಯಿಸುವುದು	V;NEUT;SG;3;FUT
ಹೋಗು	ಅವಳು	V;FEM;SG;3;POS
ಹುಟ್ಟು	ಅವರು	V;MASC;PL;3;NEG
ಕೇಳು	ನಾವು	V;PL;1;NEG
ಕೆಮ್ಮು	ಕೆಮ್ಮಿದಳು	V;FEM;SG;3;PST
ಪಡಿಯಚ್ಚು	ಪಡಿಯಚ್ಚುಗಳ	N;GEN;PL
ಅಂಟು	ಅಂಟಿನಿಂದ	N;INS;SG
ನಡೆ	ನಡೆಯಿತು	V;NEUT;SG;3;PST
ಹಾಡು	ಅವು	V;NEUT;PL;3;NEG
ಮೀ	ನಾನು	V;SG;1;NEG
ತಡೆ	ತಡೆಯುತ್ತಾನೆ	V;MASC;SG;3;PRS
ಕೇಳು	ಕೇಳಿದ	V;MASC;SG;3;PST
ಟೊಣೆ	ಅವರು	V;FEM;POT;PL;3
ಚದರು	ಅವರು	V;MASC;PL;3;POS
ತುಟಿ	ತುಟಿಯಿಂದ	N;INS;SG
ಅಂಟು	ಅಂಟಿದೆವು	V;PL;1;PST
ಒದವಿ	ಒದವಿಗಳು	N;NOM;PL
ಮಡಿಮಾಡು	ಅವನು	V;MASC;POT;SG;3
ಕಾಪಾಡು	ಕಾಪಾಡೆ	V;SG;1
ಆಗು	ಆಗರಿ	V;PL;2
ಆಗಮಿಸು	ಆಗಮಿಸುವಳು	V;FEM;SG;3;FUT
ಓದು	ಓದುವನು	V;MASC;SG;3;FUT
ಈಡಾಡು	ಈಡಾಡಿಯಾನು	V;MASC;SG;3;FUT
ಯಾತ್ರಿಕ	ಯಾತ್ರಿಕನನ್ನು	N;ACC;SG
ಓದು	ಓದೆ	V;SG;1
ಗೆಲ್ಲು	ಅವನು	V;MASC;SG;3;POS
ಯುರೋಪ	ಯುರೋಪಗಳಿಗೆ	N;DAT;PL
ಚದರು	ಚದರವು	V;NEUT;PL;3
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಿಯಾಳು	V;FEM;SG;3;FUT
ಕಾಡು	ಕಾಡುವ	V;MASC;SG;3;FUT
ಈಜು	ನಾನು	V;SG;1;NEG
ಕೊಲ್ಲು	ಕೊಂದೆವು	V;PL;1;PST
ಹೋಗು	ನೀವು	V;IMP;PL;2
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಿದರು	V;FEM;PL;3;PST
ಚಲ್ಲು	ಚಲ್ಲೆ	V;SG;1
ಗಿರಿ	ಗಿರಿಗಳಿಗೆ	N;DAT;PL
ಅಂತಃಕಲಹ	ಅಂತಃಕಲಹಗಳ	N;GEN;PL
ಹೇಳು	ಅವರು	V;FEM;PL;3;POS
ಕಲ್ಲು	ಕಲ್ಲುಗಳಿಗೆ	N;DAT;PL
ಮೀ	ಮೀಯರು	V;FEM;PL;3
ಅಂಟು	ಅವು	V;NEUT;POT;PL;3
ಅಗ್ನಿಪರ್ವತ	ಅಗ್ನಿಪರ್ವತವನ್ನು	N;ACC;SG
ಜ್ವಾಲಾಮುಖಿ	ಜ್ವಾಲಾಮುಖಿಗಳ	N;GEN;PL
ಓದು	ನೀನು	V;SG;2;NEG
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸರು	V;FEM;PL;3
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡೋಣ	V;IMP;PL;1
ಘೂಕ	ಘೂಕಕ್ಕೆ	N;DAT;SG
ಈಡಾಡು	ನಾನು	V;IMP;SG;1
ಆಗಮಿಸು	ಆಗಮಿಸುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಕೊಲ್ಲು	ಕೊಲ್ಲುವೆ	V;IMP;SG;1
ಬಯಸು	ಬಯಸುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಓದು	ಓದಿಯೇನು	V;SG;1;FUT
ಕಾಡು	ಕಾಡಲು	V;NFIN
ಉಪಯೋಗಿಸು	ನೀವು	V;PL;2;NEG
ಕೇಳು	ಕೇಳಿಯಾರು	V;FEM;PL;3;FUT
ಆಗು	ಆಗುತ್ತದೆ	V;NEUT;SG;3;PRS
ಹಾಡು	ನಾನು	V;SG;1;NEG
ಅಂಟು	ಅಂಟಿಯಾನು	V;MASC;SG;3;FUT
ಕಾಪಾಡು	ಕಾಪಾಡುತ್ತಾರೆ	V;MASC;PL;3;PRS
ಹಾಡು	ಹಾಡಳು	V;FEM;SG;3
ಆಗಮಿಸು	ಆಗಮಿಸಿಯಾರು	V;FEM;PL;3;FUT
ಕೇಳು	ಕೇಳು	V;IMP;SG;2
ಕೆಮ್ಮು	ಕೆಮ್ಮುವರು	V;MASC;PL;3;FUT
ಗೆಲ್ಲು	ನಾವು	V;POT;PL;1
ದಾಟು	ದಾಟುವಿರಿ	V;PL;2;FUT
ಬಯಸು	ಬಯಸಿದಿ	V;SG;2;PST
ಓದು	ಓದುವಿ	V;SG;2;FUT
ಅಂಟು	ಅಂಟಿದುವು	V;NEUT;PL;3;PST
ಹಾಡು	ಹಾಡಿದೆ	V;SG;1;PST
ಸಾಯಿಸು	ಸಾಯಿಸೆ	V;SG;2
ನಡೆ	ನಡೆಯಿಯಾರು	V;FEM;PL;3;FUT
ಓದು	ಓದಿದುವು	V;NEUT;PL;3;PST
ಓಡು	ಓಡುವೆ	V;SG;1;FUT
ಗೆಲ್ಲು	ಗೆಲ್ಲರು	V;MASC;PL;3
ಆಗು	ಆಗುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ನೋಡು	ನೋಡುವನು	V;MASC;SG;3;FUT
ಮಡಿಮಾಡು	ಮಡಿಮಾಡಿಯಾಳು	V;FEM;SG;3;FUT
ಇತಿಹಾಸ	ಇತಿಹಾಸವನ್ನು	N;ACC;SG
ಖೂನಿ	ಖೂನಿಗಳ	N;GEN;PL
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸಿಯಾವು	V;NEUT;PL;3;FUT
ಮಡಿಮಾಡು	ಮಡಿಮಾಡುವುವು	V;NEUT;PL;3;FUT
ಚಲ್ಲು	ಚಲ್ಲದು	V;NEUT;SG;3
ನಡೆ	ಅದು	V;NEUT;SG;3;NEG
ಹೊರಡು	ಅವು	V;NEUT;POT;PL;3
ಎಣ್ಣೆ	ಎಣ್ಣೆಗೆ	N;DAT;SG
ಕುರ್ಚಿ	ಕುರ್ಚಿಗಳನ್ನು	N;ACC;PL
ಕನಸು	ಕನಸುಗಳಿಂದ	N;INS;PL
ಆಗಮಿಸು	ನಾವು	V;IMP;PL;1
ಪ್ರಯತ್ನ	ಪ್ರಯತ್ನವನ್ನು	N;ACC;SG
ಕೊಡು	ಅವರು	V;MASC;PL;3;NEG
ಕಾಪಾಡು	ಕಾಪಾಡರಿ	V;PL;2
ಕಾನನ	ಕಾನನಗಳ	N;GEN;PL
ಈಜು	ಅವರು	V;FEM;POT;PL;3
ಹಾಡು	ಅವು	V;NEUT;POT;PL;3
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡದು	V;NEUT;SG;3
ಬರೆಕೋಲು	ಬರೆಕೋಲನ್ನು	N;ACC;SG
ಕೈ	ಕೈಗಳು	N;NOM;PL
ಅಂತಃಕರಣ	ಅಂತಃಕರಣದಿಂದ	N;INS;SG
ಗೆಳೆತನ	ಗೆಳೆತನಗಳು	N;NOM;PL
ನದಿ	ನದಿಗಳು	N;NOM;PL
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡುತ್ತದೆ	V;NEUT;SG;3;PRS
ತೊಳೆ	ತೊಳೆ	V;IMP;SG;2
ಆಯಿಸು	ನಾವು	V;PL;1;POS
ಕೊಲ್ಲು	ನೀನು	V;IMP;SG;2
ಚದರು	ಚದರೆನು	V;SG;1
ಮೀ	ಮಿಂದಾನು	V;MASC;SG;3;FUT
ಅಂಟು	ಅಂಟುಗಳಿಗೆ	N;DAT;PL
ಸಾಯಿಸು	ಸಾಯಿಸುತ್ತೇನೆ	V;SG;1;PRS
ಬೆಂಕಿ	ಬೆಂಕಿಗಳ	N;GEN;PL
ಮಗ	ಮಗನನ್ನು	N;ACC;SG
ಈಡಾಡು	ಅವರು	V;MASC;PL;3;NEG
ಹೇಳು	ಹೇಳುವ	V;MASC;SG;3;FUT
ಎಲೆ	ಎಲೆಯಿಂದ	N;INS;SG
ಮಾಡು	ಮಾಡೀತು	V;NEUT;SG;3;FUT
ಓದು	ಅವು	V;NEUT;POT;PL;3
ನೋಡು	ನೋಡುವೆವು	V;PL;1;FUT
ಹಾಡು	ಹಾಡಿದೆ	V;SG;2;PST
ಬಿಡುಗಡೆ	ಬಿಡುಗಡೆಗಳ	N;GEN;PL
ಟೊಣೆ	ಅವಳು	V;FEM;SG;3;NEG
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಸಾಯಿಸು	ಅವರು	V;MASC;PL;3;POS
ಆಗಮಿಸು	ನೀನು	V;SG;2;NEG
ಕಂಪ	ಕಂಪಗಳಿಂದ	N;INS;PL
ಚದರು	ಚದರರು	V;MASC;PL;3
ಮಡಿಮಾಡು	ಮಡಿಮಾಡಿದೆ	V;SG;2;PST
ಕೊಲ್ಲು	ನೀವು	V;POT;PL;2
ತುಟಿ	ತುಟಿಗಳನ್ನು	N;ACC;PL
ಕೆಮ್ಮು	ಅವು	V;NEUT;POT;PL;3
ಕಾಡು	ಕಾಡಿದರು	V;FEM;PL;3;PST
ನಡೆ	ಅವರು	V;FEM;PL;3;NEG
ಅಂಟು	ಅಂಟುವಳು	V;FEM;SG;3;FUT
ಆಗು	ನೀನು	V;IMP;SG;2
ತಡೆ	ತಡೆದ	V;MASC;SG;3;PST
ಕುಡಿ	ಕುಡಿಯಲಿ	V;NFIN;OPT
ಹಾಡು	ಹಾಡುವರು	V;MASC;PL;3;FUT
ಕರೆ	ಕರೆದೀಯೆ	V;SG;2;FUT
ಈಡಾಡು	ಈಡಾಡುವಿರಿ	V;PL;2;FUT
ಗಾಂಜಾ	ಗಾಂಜಾಗಳಿಂದ	N;INS;PL
ಎಣ್ಣೆ	ಎಣ್ಣೆಯ	N;GEN;SG
ಹಾಡು	ನಾನು	V;IMP;SG;1
ಆಗು	ನೀನು	V;POT;SG;2
ಪ್ರಯತ್ನಿಸು	ನೀನು	V;POT;SG;2
ತೊಳೆ	ತೊಳೆದಾರು	V;FEM;PL;3;FUT
ಕಾಪಾಡು	ಅವರು	V;FEM;POT;PL;3
ಪ್ರಯತ್ನಿಸು	ಅದು	V;NEUT;SG;3;NEG
ನೋಡು	ನೋಡರು	V;FEM;PL;3
ತುಟಿ	ತುಟಿಗಳ	N;GEN;PL
ಕರೆ	ಕರೆಯುವಾ	V;IMP;PL;1
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುತ್ತೀಯೆ	V;SG;2;PRS
ಬಯಕೆ	ಬಯಕೆಗಳ	N;GEN;PL
ಹುಟ್ಟು	ಅದು	V;NEUT;SG;3;NEG
ಮೀ	ನಾನು	V;POT;SG;1
ಜಲಪಾತ	ಜಲಪಾತಗಳನ್ನು	N;ACC;PL
ಸಾಕುಗ	ಸಾಕುಗರಿಗೆ	N;DAT;PL
ಈಜು	ಈಜುವಳು	V;FEM;SG;3;FUT
ಟೊಣೆ	ನೀವು	V;IMP;PL;2
ಓದು	ಓದಿದೆನು	V;SG;1;PST
ವಿಮುಕ್ತಿ	ವಿಮುಕ್ತಿಗಳಿಂದ	N;INS;PL
ಕೊಡು	ಕೊಡುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಮೀ	ಅವರು	V;FEM;PL;3;POS
ಕಾಪಾಡು	ಕಾಪಾಡುವೆವು	V;PL;1;FUT
ಸೂರ್ಯ	ಸೂರ್ಯನನ್ನು	N;ACC;SG
ಸಾಯಿಸು	ಅದು	V;NEUT;SG;3;NEG
ತುತ್ತೂರಿ	ತುತ್ತೂರಿಗಳಿಂದ	N;INS;PL
ವಿಮೋಚನೆ	ವಿಮೋಚನೆಗಳಿಂದ	N;INS;PL
ಕರೆ	ಕರೆದನು	V;MASC;SG;3;PST
ಕೆಮ್ಮು	ಅವರು	V;FEM;POT;PL;3
ಮೀ	ನಾವು	V;POT;PL;1
ಚಲ್ಲು	ಚಲ್ಲುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ತೊಳೆ	ತೊಳೆಯಿತು	V;NEUT;SG;3;PST
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಿಯಾರು	V;FEM;PL;3;FUT
ಕೊಡು	ಕೊಡುವೆ	V;SG;1;FUT
ಆಗು	ನಾವು	V;PL;1;NEG
ಕುಡಿ	ಕುಡಿದೇನು	V;SG;1;FUT
ಕೊಡು	ಕೊಡುವೆನು	V;SG;1;FUT
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸಿಯೇವು	V;PL;1;FUT
ಬೆರಳು	ಬೆರಳುಗಳಿಗೆ	N;DAT;PL
ಪ್ರಯತ್ನಿಸು	ಅವರು	V;MASC;PL;3;NEG
ಆಗಮಿಸು	ಅವರು	V;MASC;POT;PL;3
ಹಾಸಿಗೆ	ಹಾಸಿಗೆಗಳನ್ನು	N;ACC;PL
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡರು	V;FEM;PL;3
ಅಂಗಡಿ	ಅಂಗಡಿಯನ್ನು	N;ACC;SG
ನೆಮ್ಮದಿ	ನೆಮ್ಮದಿಯನ್ನು	N;ACC;SG
ಸಿಂಹ	ಸಿಂಹದ	N;GEN;SG
ಕೆಮ್ಮು	ಕೆಮ್ಮಿದೆ	V;SG;1;PST
ಗೆಲ್ಲು	ಅದು	V;NEUT;SG;3;NEG
ಈಜು	ಈಜುವುವು	V;NEUT;PL;3;FUT
ಮಾಡು	ನಾನು	V;IMP;SG;1
ನಡೆ	ನಡೆಯನು	V;MASC;SG;3
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಿಯಾರು	V;MASC;PL;3;FUT
ಕೇಳು	ಕೇಳುವೆ	V;SG;1;FUT
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡನು	V;MASC;SG;3
ಚಲ್ಲು	ಅದು	V;NEUT;SG;3;POS
ಓಡು	ಓಡಿಯಾನು	V;MASC;SG;3;FUT
ಸಾಯಿಸು	ಸಾಯಿಸಿದನು	V;MASC;SG;3;PST
ಪ್ರಯತ್ನಿಸು	ಅವರು	V;MASC;PL;3;POS
ಹೊರಡು	ನೀವು	V;IMP;PL;2
ಕುಡಿ	ಅವು	V;NEUT;PL;3;NEG
ಈಡಾಡು	ಈಡಾಡಿದಿರಿ	V;PL;2;PST
ಹಾಲು	ಹಾಲುಗಳಿಂದ	N;INS;PL
ಹೆಸರಿಸು	ಹೆಸರಿಸುವಿ	V;SG;2;FUT
ಕಾಪಾಡು	ನಾವು	V;POT;PL;1
ಕೆಮ್ಮು	ಕೆಮ್ಮುವಿ	V;SG;2;FUT
ಆಯಿಸು	ಆಯಿಸನು	V;MASC;SG;3
ಆಗು	ಆಗೀರಿ	V;PL;2;FUT
ತೊಳೆ	ತೊಳೆಯುವಳು	V;FEM;SG;3;FUT
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುವಾ	V;IMP;PL;1
ಎಣ್ಣೆ	ಎಣ್ಣೆಯು	N;NOM;SG
ಗುಂಪು	ಗುಂಪುಗಳ	N;GEN;PL
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಟ್ಟುವು	V;NEUT;PL;3;PST
ಜ್ವಾಲಾಮುಖಿ	ಜ್ವಾಲಾಮುಖಿಯು	N;NOM;SG
ಗೆಲ್ಲು	ಗೆಲ್ಲುವನು	V;MASC;SG;3;FUT
ಕುಡಿ	ಕುಡಿಯರು	V;MASC;PL;3
ಬೆಣ್ಣೆ	ಬೆಣ್ಣೆಯು	N;NOM;SG
ಬಯಸು	ಅವರು	V;MASC;POT;PL;3
ಸರೋವರ	ಸರೋವರಕ್ಕೆ	N;DAT;SG
ಬೆಣ್ಣೆ	ಬೆಣ್ಣೆಯಿಂದ	N;INS;SG
ಕೊಡು	ಕೊಡುವಿ	V;SG;2;FUT
ಕರೆ	ನಾವು	V;POT;PL;1
ತೊಳೆ	ತೊಳೆಯುತ್ತೀರಿ	V;PL;2;PRS
ಸಾಯಿಸು	ಸಾಯಿಸಿಯಾರು	V;MASC;PL;3;FUT
ಹಾಡು	ಹಾಡಿತು	V;NEUT;SG;3;PST
ಹುಟ್ಟು	ಹುಟ್ಟಿದರೆ	V;NFIN;COND
ಮೀ	ಅವಳು	V;FEM;SG;3;NEG
ಅಂಟು	ನೀನು	V;SG;2;NEG
ಆಯಿಸು	ಆಯಿಸಿದಳು	V;FEM;SG;3;PST
ಮಡಿಮಾಡು	ನೀನು	V;POT;SG;2
ಹುಟ್ಟು	ಹುಟ್ಟಿದರು	V;MASC;PL;3;PST
ಹಾಸಿಗೆ	ಹಾಸಿಗೆಗಳ	N;GEN;PL
ಗಿಡ	ಗಿಡವು	N;NOM;SG
ಮಾರ್ಗ	ಮಾರ್ಗಗಳನ್ನು	N;ACC;PL
ಚದರು	ಚದರರಿ	V;PL;2
ಹೊರಡು	ನೀವು	V;POT;PL;2
ಕಾಡು	ನೀನು	V;SG;2;NEG
ಮಾಡು	ಮಾಡುವೆ	V;IMP;SG;1
ಕುದುರೆ	ಕುದುರೆಗಳನ್ನು	N;ACC;PL
ಕೊಲ್ಲು	ನೀವು	V;PL;2;NEG
ಹೊರಡು	ಹೊರಡುತ್ತೀಯೆ	V;SG;2;PRS
ಸೂರ್ಯ	ಸೂರ್ಯಕ್ಕೆ	N;DAT;SG
ಸಾಯಿಸು	ಸಾಯಿಸಿದರೆ	V;NFIN;COND
ಆಗು	ಅವರು	V;FEM;POT;PL;3
ನೋಡು	ನಾವು	V;POT;PL;1
ಕೆಮ್ಮು	ಅವರು	V;FEM;PL;3;POS
ಆಯಿಸು	ನೀನು	V;SG;2;NEG
ನೆಮ್ಮದಿ	ನೆಮ್ಮದಿಯ	N;GEN;SG
ಹೆಸರಿಸು	ಹೆಸರಿಸಿದೆವು	V;PL;1;PST
ಕುಡಿ	ಕುಡಿಯುವೆ	V;IMP;SG;1
ಆಯಿಸು	ಆಯಿಸಿಯಾಳು	V;FEM;SG;3;FUT
ಕೊಲ್ಲು	ಅವರು	V;MASC;PL;3;NEG
ಕಾಲು	ಕಾಲುಗಳನ್ನು	N;ACC;PL
ಕೊಡು	ನಾನು	V;SG;1;POS
ಕೊಡು	ಕೊಟ್ಟನು	V;MASC;SG;3;PST
ಈಡಾಡು	ಈಡಾಡಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಆಗು	ಆದಳು	V;FEM;SG;3;PST
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಿದರು	V;MASC;PL;3;PST
ಅಂಟು	ಅಂಟಿದ	V;MASC;SG;3;PST
ಆಗು	ಅವನು	V;MASC;SG;3;POS
ಮೀ	ಮಿಂದೇನು	V;SG;1;FUT
ಓದು	ನಾವು	V;POT;PL;1
ಹೊರಡು	ಹೊರಡನು	V;MASC;SG;3
ಓಡು	ಅವಳು	V;FEM;POT;SG;3
ಕೊಲ್ಲು	ಅವರು	V;MASC;POT;PL;3
ಹುಟ್ಟು	ನೀನು	V;IMP;SG;2
ನೀರು	ನೀರುಗಳನ್ನು	N;ACC;PL
ನೀರು	ನೀರುಗಳು	N;NOM;PL
ಮಾಡು	ಮಾಡುವುವು	V;NEUT;PL;3;FUT
ಕೆಮ್ಮು	ಕೆಮ್ಮನು	V;MASC;SG;3
ಕೆಮ್ಮು	ಕೆಮ್ಮಿಯಾರು	V;MASC;PL;3;FUT
ಅಂಟು	ನಾನು	V;SG;1;POS
ಕಾಡು	ಅವು	V;NEUT;PL;3;NEG
ಚದರು	ಚದರೀರಿ	V;PL;2;FUT
ಸಾಯಿಸು	ಅದು	V;NEUT;POT;SG;3
ಅಗ್ನಿಪರ್ವತ	ಅಗ್ನಿಪರ್ವತವು	N;NOM;SG
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುತ್ತಾನೆ	V;MASC;SG;3;PRS
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುವಿರಿ	V;PL;2;FUT
ನಿಯಮ	ನಿಯಮಗಳನ್ನು	N;ACC;PL
ಅಂಟು	ಅಂಟೀರಿ	V;PL;2;FUT
ಬಯಸು	ನಾವು	V;POT;PL;1
ಕೇಳು	ಕೇಳೀಯೆ	V;SG;2;FUT
ಮಗ	ಮಕ್ಕಳು	N;NOM;PL
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸೆ	V;SG;2
ಬಯಸು	ಬಯಸದು	V;NEUT;SG;3
ಕೊಡು	ನಾವು	V;PL;1;NEG
ಹುಟ್ಟು	ಹುಟ್ಟುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಅಂಟು	ಅಂಟುಗಳ	N;GEN;PL
ಆಗು	ಆಗುವನು	V;MASC;SG;3;FUT
ಅಂಟು	ಅಂಟುತ್ತೀ	V;SG;2;PRS
ಆಯಿಸು	ಆಯಿಸುವೆವು	V;PL;1;FUT
ಹಾಡು	ಹಾಡಿಯಾರು	V;FEM;PL;3;FUT
ಬಯಸು	ನಾನು	V;IMP;SG;1
ಆಯಿಸು	ಅವನು	V;MASC;POT;SG;3
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	V;IMP;SG;2
ನೋಡು	ನೋಡನು	V;MASC;SG;3
ಕರೆ	ಕರೆಯುತ್ತೇನೆ	V;SG;1;PRS
ಕೆಮ್ಮು	ನೀವು	V;IMP;PL;2
ಕೊಲ್ಲು	ಕೊಲ್ಲಿಯೇನು	V;SG;1;FUT
ಗುಂಪು	ಗುಂಪುಗಳಿಗೆ	N;DAT;PL
ತಡೆ	ತಡೆಯರಿ	V;PL;2
ದಾಟು	ನಾನು	V;POT;SG;1
ನಡೆ	ನಡೆದೆನು	V;SG;1;PST
ಕೊಡು	ನೀವು	V;IMP;PL;2
ಗೆಲ್ಲು	ಅದು	V;NEUT;POT;SG;3
ಟೊಣೆ	ಅವು	V;NEUT;POT;PL;3
ಅಗ್ನಿಪರ್ವತ	ಅಗ್ನಿಪರ್ವತಗಳನ್ನು	N;ACC;PL
ಕುಡಿ	ನಾವು	V;PL;1;NEG
ಕೊಲ್ಲು	ನೀನು	V;POT;SG;2
ಹುಟ್ಟು	ಹುಟ್ಟೀರಿ	V;PL;2;FUT
ಇಗ್ಗಾಲಿ	ಇಗ್ಗಾಲಿಗಳಿಂದ	N;INS;PL
ಕಲ್ಲು	ಕಲ್ಲುಗಳು	N;NOM;PL
ಉಪಯೋಗಿಸು	ನಾವು	V;POT;PL;1
ಆಯಿಸು	ಆಯಿಸುತ್ತೇನೆ	V;SG;1;PRS
ಇಳಿ	ನೀವು	V;PL;2;POS
ತಡೆ	ತಡೆಯುವಿ	V;SG;2;FUT
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುತ್ತದೆ	V;NEUT;SG;3;PRS
ಕೊಳ	ಕೊಳದ	N;GEN;SG
ಎಣ್ಣೆ	ಎಣ್ಣೆಗಳ	N;GEN;PL
ಕಣ್ಣು	ಕಣ್ಣುಗಳಿಂದ	N;INS;PL
ಗಾಳಿ	ಗಾಳಿಗಳ	N;GEN;PL
ಹೆಸರಿಸು	ನಾವು	V;PL;1;POS
ತಡೆ	ತಡೆಯುವ	V;MASC;SG;3;FUT
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುತ್ತೀರಿ	V;PL;2;PRS
ಸುದ್ದಿ	ಸುದ್ದಿಯು	N;NOM;SG
ಕಾಡು	ಕಾಡುಗಳ	N;GEN;PL
ತೊಳೆ	ತೊಳೆದೆ	V;SG;1;PST
ಆದಿ	ಆದಿಗಳು	N;NOM;PL
ಈಡಾಡು	ಈಡಾಡುವೆ	V;SG;2;FUT
ಹೇಳು	ಹೇಳುವಿರಿ	V;PL;2;FUT
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡಿಯಾರು	V;MASC;PL;3;FUT
ಆಗಮಿಸು	ಆಗಮಿಸಿದೆವು	V;PL;1;PST
ಮಾಡು	ಮಾಡವು	V;NEUT;PL;3
ಕೊಲ್ಲು	ಕೊಲ್ಲೀಯೆ	V;SG;2;FUT
ಹಾಸಿಗೆ	ಹಾಸಿಗೆಯಿಂದ	N;INS;SG
ಗೆಲ್ಲು	ಅವರು	V;MASC;PL;3;NEG
ಸಂತೋಷ	ಸಂತೋಷದಿಂದ	N;INS;SG
ಹೃದಯ	ಹೃದಯಕ್ಕೆ	N;DAT;SG
ಈಡಾಡು	ಈಡಾಡುವೆವು	V;PL;1;FUT
ಕುಡಿ	ನಾವು	V;PL;1;POS
ಬಿರುಗಾಳಿ	ಬಿರುಗಾಲಿಯಿಂದ	N;INS;SG
ಕೇಳು	ಕೇಳುವಳು	V;FEM;SG;3;FUT
ನಡೆ	ನಡೆಯುತ್ತವೆ	V;NEUT;PL;3;PRS
ಓಡು	ಓಡಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಬಯಸು	ಅವನು	V;MASC;SG;3;NEG
ಓಡು	ಓಡುತ್ತಾರೆ	V;MASC;PL;3;PRS
ಓಡು	ಓಡಿರಿ	V;IMP;PL;2
ಕೊಲ್ಲು	ಕೊಲ್ಲುವೆ	V;SG;1;FUT
ಈಡಾಡು	ಈಡಾಡರು	V;FEM;PL;3
ಮೀ	ಮಿಂದೀತು	V;NEUT;SG;3;FUT
ಕೈ	ಕೈಗಳ	N;GEN;PL
ಕರೆ	ಕರೆಯುವರು	V;MASC;PL;3;FUT
ಹುಟ್ಟು	ಹುಟ್ಟು	V;IMP;SG;2
ಕುಡಿ	ಕುಡಿಯಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಹುಟ್ಟು	ಹುಟ್ಟಿಯೇವು	V;PL;1;FUT
ಮಡಿಮಾಡು	ಮಡಿಮಾಡುವಿ	V;SG;2;FUT
ಮಾಡು	ಅವಳು	V;FEM;SG;3;NEG
ಓಡು	ಅವು	V;NEUT;POT;PL;3
ಹೋಗು	ಹೋಗಲ್	V;NFIN
ಹೃದಯ	ಹೃದಯದಿಂದ	N;INS;SG
ಓದು	ಓದಿಯೇವು	V;PL;1;FUT
ಕುಡಿ	ಕುಡಿಯುತ್ತೇನೆ	V;SG;1;PRS
ಓಡು	ಓಡಲು	V;NFIN
ಕುಡಿ	ಅವು	V;NEUT;PL;3;POS
ಓಡು	ಓಡಿಯಾರು	V;MASC;PL;3;FUT
ಈಡಾಡು	ಈಡಾಡಿದನು	V;MASC;SG;3;PST
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡುವರು	V;FEM;PL;3;FUT
ಹೊರಡು	ನೀನು	V;POT;SG;2
ಕಂಪ	ಕಂಪಗಳಿಗೆ	N;DAT;PL
ಜೇಡಿ	ಜೇಡಿಯನ್ನು	N;ACC;SG
ಹೇಳು	ಹೇಳಿದುವು	V;NEUT;PL;3;PST
ಅಂಟು	ಅಂಟಲು	V;NFIN
ಹಾಡು	ಹಾಡುವಳು	V;FEM;SG;3;FUT
ಆಗು	ಆಗುವಿ	V;SG;2;FUT
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡೀಯೆ	V;SG;2;FUT
ಪುಷ್ಕರಿಣಿ	ಪುಷ್ಕರಿಣಿಯು	N;NOM;SG
ಓಡು	ಓಡಿದೆನು	V;SG;1;PST
ಹಾಡು	ಹಾಡುವರು	V;FEM;PL;3;FUT
ಕೆಮ್ಮು	ಕೆಮ್ಮುವೆ	V;IMP;SG;1
ಚಲ್ಲು	ಅವನು	V;MASC;SG;3;NEG
ಮಾಡು	ಮಾಡು	V;IMP;SG;2
ಕೊಲ್ಲು	ಕೊಲ್ಲರು	V;MASC;PL;3
ನೋಡು	ನೋಡುವಾ	V;IMP;PL;1
ಗೋಮಾಯು	ಗೋಮಾಯುಗಳ	N;GEN;PL
ತಡೆ	ತಡೆಗಳ	N;GEN;PL
ಕುಡಿ	ಕುಡಿಯೆವು	V;PL;1
ಪುಷ್ಕರಿಣಿ	ಪುಷ್ಕರಿಣಿಯನ್ನು	N;ACC;SG
ಗೆಲ್ಲು	ಗೆಲ್ಲುವಿ	V;SG;2;FUT
ಅಂಟು	ಅಂಟುತ್ತೇವೆ	V;PL;1;PRS
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ನೀನು	V;IMP;SG;2
ಜೇಡಿ	ಜೇಡಿಗೆ	N;DAT;SG
ಹೇಳು	ಹೇಳಿದರು	V;FEM;PL;3;PST
ತಡೆ	ತಡೆಯುತ್ತವೆ	V;NEUT;PL;3;PRS
ಹೆಸರಿಸು	ಹೆಸರಿಸೋಣ	V;IMP;PL;1
ಹೃದಯ	ಹೃದಯಗಳಿಂದ	N;INS;PL
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಲಿ	V;NFIN;OPT
ಆಯಿಸು	ನಾನು	V;POT;SG;1
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಲಿ	V;NFIN;OPT
ವನ	ವನವನ್ನು	N;ACC;SG
ಬೆಟ್ಟ	ಬೆಟ್ಟಗಳಿಂದ	N;INS;PL
ಅಂಟು	ಅಂಟುವೆ	V;SG;1;FUT
ಚದರು	ಚದರುವಾ	V;IMP;PL;1
ಗ್ರಹ	ಗ್ರಹದ	N;GEN;SG
ಕೊಡು	ಕೊಡು	V;IMP;SG;2
ಉಗುರು	ಉಗುರಿನ	N;GEN;SG
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡುವರು	V;MASC;PL;3;FUT
ಸುದ್ದಿ	ಸುದ್ದಿಯ	N;GEN;SG
ನಡೆ	ನಡೆದಳು	V;FEM;SG;3;PST
ಕೆಮ್ಮು	ಅವರು	V;MASC;PL;3;POS
ವಿದ್ಯುತ್ತು	ವಿದ್ಯುತ್ತನ್ನು	N;ACC;SG
ಗೆಲ್ಲು	ಗೆಲ್ಲುತ್ತದೆ	V;NEUT;SG;3;PRS
ಗೆಲ್ಲು	ಗೆಲ್ಲೀತು	V;NEUT;SG;3;FUT
ಈಜು	ಈಜುತ್ತೀ	V;SG;2;PRS
ಚಲ್ಲು	ನಾವು	V;PL;1;NEG
ಈಡಾಡು	ಈಡಾಡೆನು	V;SG;1
ತಡೆ	ತಡೆಯುವೆನು	V;SG;1;FUT
ಮಾಡು	ಅವನು	V;MASC;POT;SG;3
ಹೊಲ	ಹೊಲದ	N;GEN;SG
ಅಂಟು	ನೀವು	V;POT;PL;2
ಹೋಗು	ನೀವು	V;PL;2;POS
ಬಂಬು	ಬಂಬನ್ನು	N;ACC;SG
ಓದುಗೆ	ಓದುಗೆಗಳು	N;NOM;PL
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸಿದನು	V;MASC;SG;3;PST
ಈಡಾಡು	ನಾವು	V;POT;PL;1
ಗೆಲ್ಲು	ಅವು	V;NEUT;PL;3;NEG
ಕೊಡು	ಕೊಡಿಯಾಳು	V;FEM;SG;3;FUT
ದಾಟು	ದಾಟಿದರು	V;MASC;PL;3;PST
ಪುಷ್ಕರಿಣಿ	ಪುಷ್ಕರಿಣಿಗೆ	N;DAT;SG
ಓದು	ಓದಿದ	V;MASC;SG;3;PST
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಿದಿ	V;SG;2;PST
ಕರೆ	ಅದು	V;NEUT;SG;3;NEG
ಉಪಯೋಗಿಸು	ಅವರು	V;MASC;PL;3;NEG
ಕಾಪಾಡು	ಅವು	V;NEUT;POT;PL;3
ಹೋಗು	ನೀನು	V;SG;2;POS
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುವುದು	V;NEUT;SG;3;FUT
ದೂರದರ್ಶನ	ದೂರದರ್ಶನಗಳ	N;GEN;PL
ಈಡಾಡು	ಈಡಾಡುವೆ	V;IMP;SG;1
ಬಯಸು	ಬಯಸುವನು	V;MASC;SG;3;FUT
ಅಂಗಡಿ	ಅಂಗಡಿಗಳನ್ನು	N;ACC;PL
ಕೆಮ್ಮು	ಕೆಮ್ಮಿದರೆ	V;NFIN;COND
ಸಾಯಿಸು	ಸಾಯಿಸರು	V;FEM;PL;3
ಬಯಸು	ಅವನು	V;MASC;POT;SG;3
ಓಡು	ಓಡರು	V;MASC;PL;3
ವಾಕ್ಯ	ವಾಕ್ಯದ	N;GEN;SG
ಕೆಲಸ	ಕೆಲಸಗಳನ್ನು	N;ACC;PL
ಅಗ್ನಿ	ಅಗ್ನಿಯು	N;NOM;SG
ತಡೆ	ನಾನು	V;SG;1;NEG
ಗೆಳೆತನ	ಗೆಳೆತನಗಳ	N;GEN;PL
ಇಗ್ಗಾಲಿ	ಇಗ್ಗಾಲಿಯನ್ನು	N;ACC;SG
ಮಗ	ಮಕ್ಕಳ	N;GEN;PL
ತೊಳೆ	ತೊಳೆಯುವ	V;MASC;SG;3;FUT
ಮೀ	ಅವರು	V;FEM;PL;3;NEG
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸೆ	V;SG;2
ಕೆಮ್ಮು	ಅವು	V;NEUT;PL;3;POS
ಕೇಳು	ಅವನು	V;MASC;POT;SG;3
ಬಂಬು	ಬಂಬಿನಿಂದ	N;INS;SG
ಉಪಯೋಗ	ಉಪಯೋಗಗಳಿಗೆ	N;DAT;PL
ಚಲ್ಲು	ಚಲ್ಲ	V;MASC;SG;3
ಕೊಡು	ಕೊಟ್ಟಳು	V;FEM;SG;3;PST
ತಾಯಿ	ತಾಯಿಗಳು	N;NOM;PL
ಆಗು	ಆಗುತ್ತಾರೆ	V;MASC;PL;3;PRS
ಸಾಯಿಸು	ನಾನು	V;POT;SG;1
ಕರೆ	ಕರೆದಳು	V;FEM;SG;3;PST
ಕೆಲಸ	ಕೆಲಸಗಳಿಗೆ	N;DAT;PL
ಈಜು	ಈಜೋಣ	V;IMP;PL;1
ಹೆಸರಿಸು	ಅವನು	V;MASC;SG;3;POS
ಕುಡಿ	ಅವಳು	V;FEM;POT;SG;3
ಕೈ	ಕೈಗಳನ್ನು	N;ACC;PL
ಓಡು	ಓಡುವೆವು	V;PL;1;FUT
ಉಸಿರಾಟ	ಉಸಿರಾಟಗಳಿಗೆ	N;DAT;PL
ಹೋಗು	ಹೋದಿರಿ	V;PL;2;PST
ಈಜು	ಅವಳು	V;FEM;SG;3;NEG
ನೋಡು	ನೋಡುತ್ತೀರಿ	V;PL;2;PRS
ಕುಡಿ	ಕುಡಿದೀಯೆ	V;SG;2;FUT
ಬೆಟ್ಟ	ಬೆಟ್ಟಗಳ	N;GEN;PL
ಮನೆ	ಮನೆಗಳಿಂದ	N;INS;PL
ಅಂಟು	ಅಂಟುವೆ	V;SG;2;FUT
ಚದರು	ಚದರುತ್ತೀ	V;SG;2;PRS
ಕರೆ	ಕರೆದೆನು	V;SG;1;PST
ಮಡಿಮಾಡು	ನೀನು	V;SG;2;NEG
ಹೇಳು	ಹೇಳೆ	V;SG;2
ಈಜು	ಈಜಿಯಾವು	V;NEUT;PL;3;FUT
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಟ್ಟೆವು	V;PL;1;PST
ಚಲ್ಲು	ಚಲ್ಲನು	V;MASC;SG;3
ತಂದೆ	ತಂದೆಗಳನ್ನು	N;ACC;PL
ದಾಟು	ಅವು	V;NEUT;PL;3;POS
ಹೇಳು	ಅವನು	V;MASC;SG;3;POS
ಹುಟ್ಟು	ಹುಟ್ಟುವುವು	V;NEUT;PL;3;FUT
ಭಕ್ತಿ	ಭಕ್ತಿಗಳ	N;GEN;PL
ಆಗಮಿಸು	ಅವು	V;NEUT;PL;3;NEG
ಚಲ್ಲು	ಚಲ್ಲರಿ	V;PL;2
ಕೆಮ್ಮು	ಅವು	V;NEUT;PL;3;NEG
ನಿಯಮ	ನಿಯಮವನ್ನು	N;ACC;SG
ನೋಡು	ಅದು	V;NEUT;POT;SG;3
ವಿದ್ಯುತ್ತು	ವಿದ್ಯುತ್ತುಗಳಿಗೆ	N;DAT;PL
ಆಯಿಸು	ನೀನು	V;POT;SG;2
ತಡೆ	ತಡೆದೀಯೆ	V;SG;2;FUT
ಜೇಡಿ	ಜೇಡಿಗಳಿಂದ	N;INS;PL
ಚಲ್ಲು	ಚಲ್ಲೆನು	V;SG;1
ಕೇಳು	ಕೇಳುವನು	V;MASC;SG;3;FUT
ಈಡಾಡು	ಈಡಾಡುತ್ತೇನೆ	V;SG;1;PRS
ಆಗಮಿಸು	ಆಗಮಿಸಿದ	V;MASC;SG;3;PST
ಬಂಬು	ಬಂಬುಗಳನ್ನು	N;ACC;PL
ಕೆಮ್ಮು	ಅದು	V;NEUT;SG;3;NEG
ಆಯಿಸು	ಆಯಿಸಿದಿ	V;SG;2;PST
ಸೂರ್ಯಧಾತು	ಸೂರ್ಯಧಾತುವಿಗೆ	N;DAT;SG
ಬೆಣ್ಣೆ	ಬೆಣ್ಣೆಗಳು	N;NOM;PL
ಬಯಸು	ಬಯಸಿದೆ	V;SG;2;PST
ತಡೆ	ತಡೆಯುತ್ತದೆ	V;NEUT;SG;3;PRS
ಮಾಡು	ಮಾಡುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಹೆಸರಿಸು	ನಾನು	V;POT;SG;1
ನೋಡು	ನೋಡಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಅಂಟು	ಅಂಟಿಗೆ	N;DAT;SG
ಯಾತ್ರಿಕ	ಯಾತ್ರಿಕರಿಂದ	N;INS;PL
ಹುಟ್ಟು	ಹುಟ್ಟಿದ	V;MASC;SG;3;PST
ಸೂರ್ಯಧಾತು	ಸೂರ್ಯಧಾತುಗಳಿಗೆ	N;DAT;PL
ಕುಡಿ	ಕುಡಿಯಿರಿ	V;IMP;PL;2
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸರು	V;MASC;PL;3
ಈಜು	ಈಜೆ	V;SG;2
ಸರೋವರ	ಸರೋವರವು	N;NOM;SG
ಗೆಲ್ಲು	ಗೆಲ್ಲೆ	V;SG;1
ಹೋಗು	ಅವು	V;NEUT;PL;3;NEG
ಸಾಯಿಸು	ಸಾಯಿಸರಿ	V;PL;2
ತಡೆ	ಅವರು	V;FEM;PL;3;POS
ತಡೆ	ತಡೆಗಳಿಗೆ	N;DAT;PL
ನೀರು	ನೀರಿಗೆ	N;DAT;SG
ಗಿಡ	ಗಿಡವನ್ನು	N;ACC;SG
ಬಯಸು	ಅವಳು	V;FEM;SG;3;POS
ತೊಳೆ	ತೊಳೆಯುವೆನು	V;SG;1;FUT
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸುವೆ	V;IMP;SG;1
ಉರಿಬೆಟ್ಟ	ಉರಿಬೆಟ್ಟವನ್ನು	N;ACC;SG
ಮಾಡು	ನೀನು	V;SG;2;POS
ವಿಮುಕ್ತಿ	ವಿಮುಕ್ತಿಯಿಂದ	N;INS;SG
ಕುರ್ಚಿ	ಕುರ್ಚಿಯ	N;GEN;SG
ಮಗು	ಮಕ್ಕಳು	N;NOM;PL
ಹಾಡು	ಹಾಡೆನು	V;SG;1
ಹೋಗು	ಅದು	V;NEUT;POT;SG;3
ಹೆಸರಿಸು	ನಾವು	V;PL;1;NEG
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸಿದರೆ	V;NFIN;COND
ಕೊಳ	ಕೊಳಗಳಿಂದ	N;INS;PL
ಓದು	ನೀವು	V;IMP;PL;2
ಆಗಮಿಸು	ಆಗಮಿಸುವರು	V;MASC;PL;3;FUT
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸುವರು	V;MASC;PL;3;FUT
ಅಂತಃಕಲಹ	ಅಂತಃಕಲಹಗಳಿಂದ	N;INS;PL
ಆಯಿಸು	ಆಯಿಸೀತು	V;NEUT;SG;3;FUT
ಈಡಾಡು	ನಾನು	V;POT;SG;1
ಬಯಸು	ಬಯಸೋಣ	V;IMP;PL;1
ಚದರು	ಅವನು	V;MASC;SG;3;POS
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡಿಯಾಳು	V;FEM;SG;3;FUT
ಮೀ	ನೀನು	V;SG;2;POS
ಹಾಸಿಗೆ	ಹಾಸಿಗೆಯ	N;GEN;SG
ಈಜು	ಈಜುವೆ	V;SG;1;FUT
ಕೊಲ್ಲು	ಕೊಲ್ಲುತ್ತದೆ	V;NEUT;SG;3;PRS
ಸಾಯಿಸು	ಸಾಯಿಸುವೆ	V;SG;1;FUT
ಮೀ	ಮೀಯುವಾ	V;IMP;PL;1
ಮಾಡು	ಮಾಡುವಾ	V;IMP;PL;1
ಪ್ರಯತ್ನಿಸು	ಅವಳು	V;FEM;SG;3;NEG
ಸಣ್ಣಗಿಡ	ಸಣ್ಣಗಿಡವು	N;NOM;SG
ಕೆಮ್ಮು	ಕೆಮ್ಮು	V;IMP;SG;2
ಬಯಸು	ಬಯಸುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಮಾಡು	ನಾವು	V;POT;PL;1
ಈಡಾಡು	ನೀವು	V;PL;2;NEG
ಹುಟ್ಟು	ಹುಟ್ಟದು	V;NEUT;SG;3
ಓದು	ಅವರು	V;MASC;POT;PL;3
ತೊಳೆ	ನೀವು	V;IMP;PL;2
ಕರೆ	ಅವರು	V;MASC;PL;3;POS
ಕರೆ	ಕರೆಯಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಚದರು	ಚದರುತ್ತಾನೆ	V;MASC;SG;3;PRS
ಆದಿ	ಆದಿಯನ್ನು	N;ACC;SG
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡೀರಿ	V;PL;2;FUT
ಆಗು	ಆಗುತ್ತೇನೆ	V;SG;1;PRS
ಓಡು	ಅವು	V;NEUT;PL;3;NEG
ಮೀ	ನೀನು	V;POT;SG;2
ಬಿರುಗಾಳಿ	ಬಿರುಗಾಲಿಗೆ	N;DAT;SG
ಮಾಡು	ನೀನು	V;SG;2;NEG
ಹೆಸರಿಸು	ಅವರು	V;MASC;POT;PL;3
ಪುಸ್ತಕ	ಪುಸ್ತಕದಿಂದ	N;INS;SG
ದಾಟು	ದಾಟಿದೆವು	V;PL;1;PST
ಕಾಪಾಡು	ಕಾಪಾಡೀತು	V;NEUT;SG;3;FUT
ಹಾಡು	ಹಾಡಿದಳು	V;FEM;SG;3;PST
ದಾಟು	ದಾಟುವಿ	V;SG;2;FUT
ಸಾಯಿಸು	ನಾವು	V;IMP;PL;1
ಕುಡಿ	ಅವನು	V;MASC;SG;3;POS
ಆಗಮಿಸು	ಆಗಮಿಸಿಯೇನು	V;SG;1;FUT
ತಡೆ	ತಡೆಯುವೆ	V;SG;1;FUT
ಹೇಳು	ಅವರು	V;MASC;POT;PL;3
ಆಗು	ಆಗುವಳು	V;FEM;SG;3;FUT
ಮಡಿಮಾಡು	ಮಡಿಮಾಡುತ್ತಾನೆ	V;MASC;SG;3;PRS
ಪೊಳೆ	ಪೊಳೆಗಳ	N;GEN;PL
ಅಂಗ	ಅಂಗಗಳನ್ನು	N;ACC;PL
ಚಲ್ಲು	ಚಲ್ಲು	V;IMP;SG;2
ಹೊರಡು	ಹೊರಡುತ್ತೇವೆ	V;PL;1;PRS
ಕೊಡು	ಕೊಡಿಯೇವು	V;PL;1;FUT
ಅಂಟು	ಅಂಟಿದನು	V;MASC;SG;3;PST
ಚಲ್ಲು	ಅವರು	V;FEM;PL;3;POS
ಉಪಯೋಗಿಸು	ನಾವು	V;IMP;PL;1
ಓದು	ಓದುತ್ತವೆ	V;NEUT;PL;3;PRS
ದೂರದರ್ಶನ	ದೂರದರ್ಶನಗಳಿಂದ	N;INS;PL
ಕಾಡು	ಕಾಡುತ್ತದೆ	V;NEUT;SG;3;PRS
ಹೆಸರಿಸು	ಅದು	V;NEUT;SG;3;NEG
ಕೇಳು	ಕೇಳುವುದು	V;NEUT;SG;3;FUT
ವಾಕ್ಯ	ವಾಕ್ಯಗಳಿಗೆ	N;DAT;PL
ಗ್ರಹ	ಗ್ರಹಗಳು	N;NOM;PL
ಕಾಡು	ನೀನು	V;POT;SG;2
ಬಯಸು	ನಾನು	V;POT;SG;1
ತಡೆ	ಅವು	V;NEUT;POT;PL;3
ಎರವಲುಕೊಡು	ನಾನು	V;POT;SG;1
ಬಯಸು	ಬಯಸುತ್ತೇವೆ	V;PL;1;PRS
ಕಾಲು	ಕಾಲುಗಳ	N;GEN;PL
ಆಯಿಸು	ಅವರು	V;FEM;PL;3;POS
ನಾಯಿ	ನಾಯಿಗೆ	N;DAT;SG
ನಡೆ	ನಡೆಯುವೆ	V;SG;1;FUT
ಹಾಡು	ಹಾಡಿದ	V;MASC;SG;3;PST
ಅಂಟು	ಅಂಟಿಯಾರು	V;FEM;PL;3;FUT
ಆಗಮಿಸು	ಆಗಮಿಸರು	V;FEM;PL;3
ದಾಟು	ದಾಟುವರು	V;FEM;PL;3;FUT
ಪೊಳೆ	ಪೊಳೆಯನ್ನು	N;ACC;SG
ಇಳಿ	ನೀವು	V;IMP;PL;2
ನೋಡು	ನೋಡೀಯೆ	V;SG;2;FUT
ಬೆಟ್ಟ	ಬೆಟ್ಟಗಳಿಗೆ	N;DAT;PL
ಗೆಲ್ಲು	ಗೆಲ್ಲುತ್ತಾರೆ	V;FEM;PL;3;PRS
ಆಯಿಸು	ಆಯಿಸಿಯಾನು	V;MASC;SG;3;FUT
ಕೊಲ್ಲು	ಅವು	V;NEUT;PL;3;NEG
ಹಾಡು	ಹಾಡಿಯೇನು	V;SG;1;FUT
ಓಡು	ಓಡುತ್ತೀರಿ	V;PL;2;PRS
ಯಾತ್ರಾರ್ಥಿ	ಯಾತ್ರಾರ್ಥಿಗಳಿಂದ	N;INS;PL
ಹಾಸಿಗೆ	ಹಾಸಿಗೆಗೆ	N;DAT;SG
ಓಡು	ಓಡುವ	V;MASC;SG;3;FUT
ಅಂಟು	ಅವರು	V;FEM;PL;3;NEG
ಕೇಳು	ಕೇಳರಿ	V;PL;2
ಹೊರಡು	ಅವರು	V;FEM;PL;3;POS
ಬೆವರು	ಬೆವರನ್ನು	N;ACC;SG
ಓಡು	ನೀವು	V;IMP;PL;2
ಕೆಮ್ಮು	ಕೆಮ್ಮಿದೆವು	V;PL;1;PST
ಗೆಲ್ಲು	ಅವು	V;NEUT;PL;3;POS
ಮಡಿಮಾಡು	ಮಡಿಮಾಡುತ್ತದೆ	V;NEUT;SG;3;PRS
ಅಂಟು	ಅಂಟುವ	V;MASC;SG;3;FUT
ಕರೆ	ಕರೆದಾನು	V;MASC;SG;3;FUT
ಕೊಡು	ಕೊಡರು	V;FEM;PL;3
ಹೆಸರಿಸು	ಹೆಸರಿಸುತ್ತೀಯೆ	V;SG;2;PRS
ಕೊಲ್ಲು	ನಾನು	V;POT;SG;1
ಬೆರಳು	ಬೆರಳಿನಿಂದ	N;INS;SG
ಚದರು	ನಾವು	V;POT;PL;1
ಹಾಡು	ಹಾಡಿಯಾನು	V;MASC;SG;3;FUT
ಕಾಡು	ಕಾಡೋಣ	V;IMP;PL;1
ಓದು	ಓದಿಯಾಳು	V;FEM;SG;3;FUT
ಸಾಯಿಸು	ಸಾಯಿಸೋಣ	V;IMP;PL;1
ಗುಂಪು	ಗುಂಪನ್ನು	N;ACC;SG
ಮಾಡು	ಅವರು	V;MASC;PL;3;NEG
ಚಕ್ರ	ಚಕ್ರಗಳ	N;GEN;PL
ದಾಟು	ದಾಟೆವು	V;PL;1
ಕುಡಿ	ಕುಡಿದಾಳು	V;FEM;SG;3;FUT
ಕೆಮ್ಮು	ಕೆಮ್ಮುವನು	V;MASC;SG;3;FUT
ಕೊಲ್ಲು	ಕೊಲ್ಲಿರಿ	V;IMP;PL;2
ದಾಟು	ದಾಟುವೆ	V;SG;2;FUT
ತಡೆ	ನೀವು	V;PL;2;POS
ಹೊರಡು	ನೀವು	V;PL;2;POS
ಅಂಟು	ಅಂಟಿಯಾವು	V;NEUT;PL;3;FUT
ಆಗು	ನಾವು	V;IMP;PL;1
ಕರೆ	ನಾನು	V;SG;1;NEG
ಲೋಟ	ಲೋಟಗಳ	N;GEN;PL
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸುವೆ	V;SG;1;FUT
ಅಂಟು	ನೀನು	V;IMP;SG;2
ಓದುಗೆ	ಓದುಗೆಗಳಿಗೆ	N;DAT;PL
ಚದರು	ಚದರಿಯಾರು	V;MASC;PL;3;FUT
ಕಾಪಾಡು	ಅದು	V;NEUT;SG;3;NEG
ದಾಟು	ದಾಟುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಹೆಸರಿಸು	ಹೆಸರಿಸಿದುವು	V;NEUT;PL;3;PST
ಮೀ	ನೀವು	V;POT;PL;2
ನನಸು	ನನಸುಗಳು	N;NOM;PL
ಪ್ರಯತ್ನ	ಪ್ರಯತ್ನಗಳು	N;NOM;PL
ಓಡು	ಓಡ	V;MASC;SG;3
ಹೊರಡು	ಅದು	V;NEUT;SG;3;NEG
ಆಗಮಿಸು	ಅವನು	V;MASC;SG;3;POS
ಹುಡುಗ	ಹುಡುಗರ	N;GEN;PL
ಚದರು	ನಾವು	V;PL;1;POS
ಮಡಿಮಾಡು	ನಾವು	V;POT;PL;1
ಗಿರಿ	ಗಿರಿಯಿಂದ	N;INS;SG
ಅಂಟು	ಅಂಟಿದಿರಿ	V;PL;2;PST
ಕೊಡು	ಕೊಡುವರು	V;MASC;PL;3;FUT
ಉಪಯೋಗಿಸು	ಉಪಯೋಗಿಸಲು	V;NFIN
ಬರೆಕೋಲು	ಬರೆಕೋಲಿನಿಂದ	N;INS;SG
ಆಗಮಿಸು	ಅವನು	V;MASC;SG;3;NEG
ಹೋಗು	ಹೋಗಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಹೃದಯ	ಹೃದಯವು	N;NOM;SG
ನೋಡು	ನೋಡೀತು	V;NEUT;SG;3;FUT
ಆಗಮಿಸು	ಆಗಮಿಸ	V;MASC;SG;3
ಕುಡಿ	ಕುಡಿಯೆ	V;SG;1
ಕುಡಿ	ಅವರು	V;FEM;PL;3;NEG
ಕೊಡು	ನಾನು	V;IMP;SG;1
ಹಾಡು	ಅವಳು	V;FEM;POT;SG;3
ಕೊಲ್ಲು	ಕೊಲ್ಲ	V;MASC;SG;3
ದಾಟು	ಅವು	V;NEUT;PL;3;NEG
ತುತ್ತೂರಿ	ತುತ್ತೂರಿಗಳಿಗೆ	N;DAT;PL
ಪೊಳೆ	ಪೊಳೆಗಳನ್ನು	N;ACC;PL
ನಡೆ	ನಡೆಯು	V;IMP;SG;2
ಆಗು	ಆಯಿತು	V;NEUT;SG;3;PST
ಹೆಸರಿಸು	ಹೆಸರಿಸುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಕಾಡು	ಕಾಡೆನು	V;SG;1
ಓಡು	ಅವರು	V;MASC;PL;3;NEG
ಮಗು	ಮಕ್ಕಳಿಗೆ	N;DAT;PL
ಆಗು	ಆಗೀತು	V;NEUT;SG;3;FUT
ಸಂತೋಷ	ಸಂತೋಷವು	N;NOM;SG
ಪ್ರಯತ್ನಿಸು	ಪ್ರಯತ್ನಿಸುತ್ತವೆ	V;NEUT;PL;3;PRS
ಸಾಯಿಸು	ಸಾಯಿಸುತ್ತೀಯೆ	V;SG;2;PRS
ಕೊಲ್ಲು	ಕೊಲ್ಲಳು	V;FEM;SG;3
ಚದರು	ಚದರುತ್ತಾರೆ	V;MASC;PL;3;PRS
ಕೆಮ್ಮು	ಕೆಮ್ಮುತ್ತದೆ	V;NEUT;SG;3;PRS
ಕರೆ	ಕರೆಯುವೆ	V;SG;2;FUT
ಹಾಡು	ಹಾಡುತ್ತೀರಿ	V;PL;2;PRS
ಆಗಮಿಸು	ಆಗಮಿಸುವುವು	V;NEUT;PL;3;FUT
ಕಾಡು	ಕಾಡರು	V;MASC;PL;3
ನಡೆ	ನಾನು	V;SG;1;NEG
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ನಾನು	V;POT;SG;1
ಮಾಡು	ಮಾಡದು	V;NEUT;SG;3
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡೆವು	V;PL;1
ನೆಮ್ಮದಿ	ನೆಮ್ಮದಿಗಳ	N;GEN;PL
ಚಹಾ	ಚಹಾಗಳನ್ನು	N;ACC;PL
ಅಂಟು	ಅಂಟಿದೆ	V;SG;1;PST
ನೋಡು	ನೋಡುತ್ತಾನೆ	V;MASC;SG;3;PRS
ಕೊಡು	ಕೊಡುವ	V;MASC;SG;3;FUT
ಹೆಸರಿಸು	ಹೆಸರಿಸುತ್ತೇವೆ	V;PL;1;PRS
ತೊಳೆ	ಅವು	V;NEUT;PL;3;NEG
ಕಾಪಾಡು	ಅವಳು	V;FEM;SG;3;POS
ಹೋಗು	ಹೋಗುವೆನು	V;SG;1;FUT
ಕೆಲಸ	ಕೆಲಸಕ್ಕೆ	N;DAT;SG
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸೀರಿ	V;PL;2;FUT
ಮಾಡು	ಅವರು	V;MASC;POT;PL;3
ಬೆವರು	ಬೆವರಿಗೆ	N;DAT;SG
ಗೆಳೆತನ	ಗೆಳೆತನಗಳನ್ನು	N;ACC;PL
ಎರವಲುಕೊಡು	ನೀವು	V;PL;2;NEG
ಹಾಡು	ಹಾಡುವೆ	V;SG;1;FUT
ಮಗು	ಮಗುವಿಗೆ	N;DAT;SG
ಕೇಳು	ನೀನು	V;SG;2;NEG
ಬಯಸು	ಬಯಸಿದೆನು	V;SG;1;PST
ಓಡು	ಓಡು	V;IMP;SG;2
ಹೆಸರಿಸು	ಅವರು	V;MASC;PL;3;NEG
ಆಗು	ಆಗದು	V;NEUT;SG;3
ಕೊಡು	ಕೊಟ್ಟೆವು	V;PL;1;PST
ಬಯಸು	ಬಯಸುತ್ತದೆ	V;NEUT;SG;3;PRS
ತಡೆ	ತಡೆದಾರು	V;MASC;PL;3;FUT
ಸಾಯಿಸು	ಸಾಯಿಸುವೆವು	V;PL;1;FUT
ಶಕ್ತಿ	ಶಕ್ತಿಗಳಿಂದ	N;INS;PL
ನೋಡು	ನೋಡಿದ	V;MASC;SG;3;PST
ಕೇಳು	ಅವರು	V;FEM;PL;3;NEG
ಅಂಟು	ಅವರು	V;FEM;PL;3;POS
ಹೊರಡು	ಹೊರಡೆವು	V;PL;1
ಈಜು	ನೀವು	V;PL;2;NEG
ಹೆಸರು	ಹೆಸರುಗಳಿಂದ	N;INS;PL
ಕೊಡು	ಕೊಡುತ್ತೀಯೆ	V;SG;2;PRS
ಕೊಡು	ಕೊಡೆ	V;SG;2
ಪುಷ್ಕರಿಣಿ	ಪುಷ್ಕರಿಣಿಗಳ	N;GEN;PL
ಕೇಳು	ಕೇಳವು	V;NEUT;PL;3
ಗೆಲ್ಲು	ಗೆದ್ದರು	V;MASC;PL;3;PST
ಕೊಲ್ಲು	ನೀವು	V;PL;2;POS
ಆಯಿಸು	ನೀವು	V;PL;2;NEG
ಕೆಮ್ಮು	ಕೆಮ್ಮುಗಳನ್ನು	N;ACC;PL
ತಲೆ	ತಲೆಗಳು	N;NOM;PL
ನಡೆ	ಅವಳು	V;FEM;SG;3;POS
ಈಜು	ಈಜದು	V;NEUT;SG;3
ಬಂಬು	ಬಂಬಿಗೆ	N;DAT;SG
ಮಡಿಮಾಡು	ನಾವು	V;PL;1;POS
ನಡೆ	ನಡೆಯುವೆ	V;SG;2;FUT
ಮೀ	ನಾವು	V;IMP;PL;1
ಅಂಗಡಿ	ಅಂಗಡಿಗಳು	N;NOM;PL
ಆಗಮಿಸು	ನಾವು	V;PL;1;NEG
ಚಲ್ಲು	ಚಲ್ಲುವಾ	V;IMP;PL;1
ಕೆಮ್ಮು	ಕೆಮ್ಮೆನು	V;SG;1
ಚದರು	ನೀವು	V;IMP;PL;2
ಓದು	ಓದುವಾ	V;IMP;PL;1
ಕುಡಿ	ಕುಡಿಯರಿ	V;PL;2
ನೋಡು	ನೋಡೀರಿ	V;PL;2;FUT
ಜ್ವಾಲಾಮುಖಿ	ಜ್ವಾಲಾಮುಖಿಗಳನ್ನು	N;ACC;PL
ಆಯಿಸು	ಆಯಿಸುತ್ತೀಯೆ	V;SG;2;PRS
ಕಾಡು	ಕಾಡು	V;IMP;SG;2
ಈಜು	ಈಜುತ್ತವೆ	V;NEUT;PL;3;PRS
ಹೇಳು	ಹೇಳವು	V;NEUT;PL;3
ಹೆಸರಿಸು	ಹೆಸರಿಸಲಿಕ್ಕೆ	V;NFIN;LGSPEC2
ಹೊರಡು	ಹೊರಡುವರು	V;FEM;PL;3;FUT
ಕೆಮ್ಮು	ನಾವು	V;IMP;PL;1
ಮಡಿಮಾಡು	ಅವನು	V;MASC;SG;3;NEG
ಗೆಲ್ಲು	ಗೆಲ್ಲೆ	V;SG;2
ತುಟಿ	ತುಟಿಯು	N;NOM;SG
ಹೆಸರಿಸು	ಹೆಸರಿಸುವ	V;MASC;SG;3;FUT
ಒದವಿ	ಒದವಿಗಳಿಂದ	N;INS;PL
ಹುಟ್ಟು	ಹುಟ್ಟಲು	V;NFIN
ಗೆಲ್ಲು	ಗೆಲ್ಲೆನು	V;SG;1
ಹೊರಡು	ಅವರು	V;MASC;PL;3;POS
ಹುಟ್ಟು	ನೀನು	V;POT;SG;2
ಮರ	ಮರಗಳ	N;GEN;PL
ಕೊಲ್ಲು	ಕೊಲ್ಲನು	V;MASC;SG;3
ದಾಟು	ದಾಟಿಯೇನು	V;SG;1;FUT
ಅಂಟು	ಅವನು	V;MASC;POT;SG;3
ಹೋಗು	ಹೋಗನು	V;MASC;SG;3
ಕರೆ	ಕರೆದಿರಿ	V;PL;2;PST
ಮಾಡು	ನಾನು	V;SG;1;NEG
ಓಡು	ನೀನು	V;IMP;SG;2
ಅಂಟು	ಅಂಟ	V;MASC;SG;3
ಹೊರಡು	ನಾನು	V;IMP;SG;1
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸುತ್ತಾಳೆ	V;FEM;SG;3;PRS
ಈಜು	ಈಜುವೆ	V;SG;2;FUT
ಎರವಲುಕೊಡು	ಎರವಲುಕೊಡಿಯಾನು	V;MASC;SG;3;FUT
ನೋಡು	ನೋಡಿಯಾವು	V;NEUT;PL;3;FUT
ದ್ಯುತಿಸಂಶ್ಲೇಷಿಸು	ನೀವು	V;POT;PL;2
ನನಸು	ನನಸುಗಳ	N;GEN;PL
ಚದರು	ಚದರುವುವು	V;NEUT;PL;3;FUT
ಹೆಸರಿಸು	ನಾವು	V;POT;PL;1
