tek	koteka	V;FUT
tindik	tindikaki	V;PST
yeb	yebaki	V;PST
yeb	koyeba	V;NFIN
vand	vandi	V;PRS
mem	memi	V;PRS
yamb	koyamba	V;NFIN
bom	koboma	V;NFIN
lob	lobaki	V;PST
kende	kendei	V;PRS
mel	komela	V;NFIN
ling	lingaki	V;PST
luk	koluka	V;NFIN
lamb	kolamba	V;NFIN
tek	koteka	V;NFIN
tun	tunaki	V;PST
tang	kotanga	V;FUT
telem	telemaki	V;PST
yebis	yebisi	V;PRS
bal	kobala	V;NFIN
salis	kosalisa	V;FUT
bal	balaki	V;PST
salis	salisaki	V;PST
li	kolia	V;FUT
mel	melaki	V;PST
kim	kokima	V;FUT
simb	kosimba	V;NFIN
tind	tindaki	V;PST
lob	koloba	V;FUT
lob	koloba	V;NFIN
kol	kokola	V;NFIN
su	kosua	V;NFIN
kom	kokoma	V;FUT
kom	kokoma	V;NFIN
kang	kangi	V;PRS
yib	yibi	V;PRS
kim	kimaki	V;PST
telem	telemi	V;PRS
kat	kokata	V;FUT
somb	sombaki	V;PST
yemb	koyemba	V;FUT
pumbu	pumbuaki	V;PST
zuw	kozuwa	V;FUT
yib	koyiba	V;FUT
tindik	kotindika	V;NFIN
pes	pesaki	V;PST
