istituir	istituesc	V;IND;PL;3;PRS;LGSPEC2
cunvalider	cunvalidaré	V;IND;SG;1;FUT
produjer	produj	V;IND;PL;3;PRS
adoter	adoteia	V;NFIN;SG;2;LGSPEC2
acrediter	acreditasse	V;IPFV;SBJV;SG;1;PST
secuestrer	secuestron	V;IND;PL;1;PRS
giudicher	giudiche	V;SBJV;PL;3;PRS
destumer	destumeie	V;IND;SG;1;PRS;LGSPEC2
comprer	compreia	V;IND;PL;3;PRS;LGSPEC2
cunzeder	cunzedessais	V;IPFV;SBJV;PL;2;PST
renunzier	renunzieie	V;IND;SG;1;PRS;LGSPEC2
renunzier	renunziassa	V;IPFV;SBJV;SG;3;PST
coordiner	coordinova	V;IPFV;IND;PL;3;PST
spartir	spartide	V;NFIN;PL;2
volei	voleis	V;SBJV;PL;2;PRS
detlarer	detlarassa	V;IPFV;SBJV;PL;3;PST
romper	rompon	V;SBJV;PL;1;PRS
delibrer	delibron	V;IND;PL;1;PRS
gaujer	gaujea	V;IND;SG;3;PRS;LGSPEC3
garantir	garantiva	V;IPFV;IND;PL;3;PST
garantir	garante	V;SBJV;SG;1;PRS;LGSPEC1
mirer	mirassa	V;IPFV;SBJV;SG;3;PST
cruzier	cruziovan	V;IPFV;IND;PL;1;PST
reguler	regulova	V;IPFV;IND;SG;3;PST
messei	messon	V;IND;PL;1;PRS
nascer	nascessa	V;IPFV;SBJV;SG;3;PST
redujer	redujon	V;SBJV;PL;1;PRS
acrediter	acredites	V;SBJV;SG;2;PRS;LGSPEC1
adater	adates	V;SBJV;SG;2;PRS;LGSPEC1
coordener	coordeneia	V;NFIN;SG;2;LGSPEC2
marider	maridareis	V;IND;PL;2;FUT
arjonjer	arjonjessa	V;IPFV;SBJV;SG;3;PST
capir	cap	V;NFIN;SG;2;LGSPEC1
comprer	comprassan	V;IPFV;SBJV;PL;1;PST
coster	costes	V;SBJV;SG;2;PRS;LGSPEC1
volei	volessa	V;IPFV;SBJV;SG;3;PST
furmer	furmoves	V;IPFV;IND;SG;2;PST
deslier	desliova	V;IPFV;IND;PL;3;PST
cumporter	cumportede	V;NFIN;PL;2
cunferir	cunferesc	V;NFIN;SG;2;LGSPEC2
romper	rompe	V;SBJV;SG;1;PRS
ndicher	ndicharé	V;IND;SG;1;FUT
alesirer	alesiraré	V;IND;SG;1;FUT
rejoner	rejoneia	V;IND;SG;3;PRS;LGSPEC2
numiner	numine	V;IND;SG;1;PRS;LGSPEC1
dé	darà	V;IND;SG;3;FUT
perde	perdaron	V;IND;PL;1;FUT
storjer	storjoves	V;IPFV;IND;SG;2;PST
tramuder	tramudede	V;NFIN;PL;2
stipuler	stipula	V;IND;PL;3;PRS;LGSPEC1
parteziper	partezipa	V;IND;SG;3;PRS;LGSPEC1
morir	morisse	V;IPFV;SBJV;SG;1;PST
avei	à	V;IND;PL;3;PRS
perder	perdesse	V;IPFV;SBJV;SG;1;PST
ncurajer	ncurajer	V;NFIN;LGSPEC1
someter	sometes	V;SBJV;SG;2;PRS;LGSPEC1
ressolver	ressolvovais	V;IPFV;IND;PL;2;PST
trasferir	trasferes	V;IND;SG;2;PRS;LGSPEC1
vedei	veides	V;SBJV;SG;2;PRS
desgorjer	desgorjarà	V;IND;SG;3;FUT
jì	vae	V;SBJV;SG;3;PRS
educher	educhovais	V;IPFV;IND;PL;2;PST
sustenir	susten	V;IND;SG;3;PRS;LGSPEC1
promulgher	promulghove	V;IPFV;IND;SG;1;PST
cherder	cherdarà	V;IND;PL;3;FUT
azerter	azerteies	V;SBJV;SG;2;PRS;LGSPEC2
acurder	acurdassa	V;IPFV;SBJV;PL;3;PST
cumporter	cumporteis	V;IND;PL;2;PRS
renunzier	renunziaron	V;IND;PL;1;FUT
furmer	furmeia	V;IND;PL;3;PRS;LGSPEC2
nfurmer	nfurmeis	V;SBJV;PL;2;PRS
costituir	costituissa	V;IPFV;SBJV;SG;3;PST
corompe	coromparas	V;IND;SG;2;FUT
rester	restassan	V;IPFV;SBJV;PL;1;PST
prejenter	prejenteie	V;SBJV;SG;1;PRS;LGSPEC2
damander	damandeie	V;SBJV;SG;3;PRS;LGSPEC2
tramuder	tramudon	V;IND;PL;1;PRS
curespuender	curespuendes	V;IND;SG;2;PRS;LGSPEC1
publicher	publichove	V;IPFV;IND;SG;1;PST
mirer	miraré	V;IND;SG;1;FUT
messei	messova	V;IPFV;IND;PL;3;PST
damander	damandeia	V;NFIN;SG;2;LGSPEC2
storjer	storj	V;IND;SG;3;PRS
spidler	spidler	V;NFIN;LGSPEC1
acrediter	acreditaron	V;IND;PL;1;FUT
limiter	limitove	V;IPFV;IND;SG;1;PST
pruibir	pruibe	V;SBJV;PL;3;PRS;LGSPEC1
cunvalider	cunvalideie	V;SBJV;SG;1;PRS;LGSPEC2
scuter	scutarà	V;IND;PL;3;FUT
slunger	slungeie	V;SBJV;SG;3;PRS;LGSPEC2
segurer	segurove	V;IPFV;IND;SG;1;PST
danejer	daneje	V;SBJV;SG;3;PRS;LGSPEC1
purter	purtarà	V;IND;SG;3;FUT
mander	mandeie	V;SBJV;SG;1;PRS;LGSPEC2
tradujer	tradujaré	V;IND;SG;1;FUT
delibrer	delibre	V;SBJV;SG;1;PRS;LGSPEC1
acrediter	acrediteies	V;SBJV;SG;2;PRS;LGSPEC2
istruir	istruiré	V;IND;SG;1;FUT
slunger	slunges	V;IND;SG;2;PRS;LGSPEC1
cherder	cherdeia	V;NFIN;SG;2;LGSPEC2
desvier	desvioves	V;IPFV;IND;SG;2;PST
furmer	furma	V;NFIN;SG;2;LGSPEC1
usserver	usservove	V;IPFV;IND;SG;1;PST
capir	capesc	V;IND;PL;3;PRS;LGSPEC2
furmer	furmeies	V;SBJV;SG;2;PRS;LGSPEC2
anuler	anulon	V;IND;PL;1;PRS
mander	mandes	V;SBJV;SG;2;PRS;LGSPEC1
arbitrer	arbitrer	V;NFIN;LGSPEC1
deslier	desliasses	V;IPFV;SBJV;SG;2;PST
reprejenter	reprejenton	V;IND;PL;1;PRS
determiner	determineies	V;IND;SG;2;PRS;LGSPEC2
acuser	acusaré	V;IND;SG;1;FUT
adoter	adote	V;SBJV;SG;1;PRS;LGSPEC1
comunicher	comunicheies	V;SBJV;SG;2;PRS;LGSPEC2
sporjer	sporjaré	V;IND;SG;1;FUT
cunzeder	cunzed	V;NFIN;SG;2
depenjer	depenjove	V;IPFV;IND;SG;1;PST
parteziper	partezipeia	V;IND;PL;3;PRS;LGSPEC2
respuender	respuendeies	V;SBJV;SG;2;PRS;LGSPEC2
seurander	seurandaras	V;IND;SG;2;FUT
marider	maridede	V;NFIN;PL;2
istituir	istituissais	V;IPFV;SBJV;PL;2;PST
aplicher	aplichon	V;IND;PL;1;PRS
volei	volova	V;IPFV;IND;SG;3;PST
limiter	limitede	V;NFIN;PL;2
scurter	scurtove	V;IPFV;IND;SG;1;PST
dé	dé	V;IND;SG;1;PRS
udir	udesc	V;NFIN;SG;2;LGSPEC2
dormir	dormesce	V;SBJV;PL;3;PRS;LGSPEC2
capir	capissa	V;IPFV;SBJV;SG;3;PST
tramuder	tramudarà	V;IND;PL;3;FUT
aplicher	aplicharas	V;IND;SG;2;FUT
istruir	istruissan	V;IPFV;SBJV;PL;1;PST
pruibir	pruibesce	V;SBJV;SG;1;PRS;LGSPEC2
revucher	revuchova	V;IPFV;IND;SG;3;PST
deslier	desliaron	V;IND;PL;1;FUT
comunicher	comunicheia	V;NFIN;SG;2;LGSPEC2
autoriser	autorisassa	V;IPFV;SBJV;SG;3;PST
cianter	ciantede	V;NFIN;PL;2
onjer	onje	V;NFIN;LGSPEC2
njinier	njiniassan	V;IPFV;SBJV;PL;1;PST
finanzier	finanziovan	V;IPFV;IND;PL;1;PST
spartir	spartesce	V;SBJV;PL;3;PRS;LGSPEC2
scuter	scutova	V;IPFV;IND;PL;3;PST
mander	mandeis	V;SBJV;PL;2;PRS
atribuir	atribu	V;IND;PL;3;PRS;LGSPEC1
eserziter	eserzita	V;NFIN;SG;2;LGSPEC1
cianter	ciantovan	V;IPFV;IND;PL;1;PST
destiner	destine	V;SBJV;PL;3;PRS
furmer	furmon	V;IND;PL;1;PRS
scuter	scouteie	V;SBJV;SG;1;PRS;LGSPEC2
mirer	mirasses	V;IPFV;SBJV;SG;2;PST
cunzeder	cunzedessa	V;IPFV;SBJV;PL;3;PST
produjer	produjova	V;IPFV;IND;SG;3;PST
mpartir	mparte	V;SBJV;SG;3;PRS;LGSPEC1
manifester	manifesteie	V;IND;SG;1;PRS;LGSPEC2
entenjer	entenjeis	V;IND;PL;2;PRS
cundaner	cundanon	V;SBJV;PL;1;PRS
vedei	vedarà	V;IND;SG;3;FUT
cunferir	cunferisses	V;IPFV;SBJV;SG;2;PST
cherder	cherde	V;IND;SG;1;PRS;LGSPEC1
cumander	cumandasses	V;IPFV;SBJV;SG;2;PST
detlarer	detlareie	V;SBJV;SG;3;PRS;LGSPEC2
tramuder	tramudeies	V;IND;SG;2;PRS;LGSPEC2
mander	mande	V;SBJV;PL;3;PRS
cumporter	cumportovais	V;IPFV;IND;PL;2;PST
giudicher	giudichova	V;IPFV;IND;SG;3;PST
usserver	usservaras	V;IND;SG;2;FUT
rater	rate	V;IND;SG;1;PRS;LGSPEC1
jonjer	jonjon	V;IND;PL;1;PRS
cianter	cianteia	V;IND;PL;3;PRS;LGSPEC2
rester	restarà	V;IND;SG;3;FUT
erjer	erje	V;NFIN;LGSPEC2
dé	dova	V;IPFV;IND;SG;3;PST
adater	adata	V;NFIN;SG;2;LGSPEC1
rejoner	rejonarà	V;IND;PL;3;FUT
condujer	condujessa	V;IPFV;SBJV;SG;3;PST
segurer	segurovan	V;IPFV;IND;PL;1;PST
cianter	cianteis	V;IND;PL;2;PRS
sponjer	sponjeis	V;IND;PL;2;PRS
ancunter	ancuntea	V;IND;SG;3;PRS;LGSPEC3
prufesser	prufessaron	V;IND;PL;1;FUT
entenjer	entenjarà	V;IND;SG;3;FUT
condujer	conduje	V;SBJV;SG;1;PRS
strenjer	strenje	V;NFIN;LGSPEC2
adater	adateie	V;SBJV;SG;3;PRS;LGSPEC2
coordiner	coordinove	V;IPFV;IND;SG;1;PST
garantir	garantiron	V;IND;PL;1;FUT
prejenter	prejenta	V;NFIN;SG;2;LGSPEC1
marider	maride	V;IND;SG;1;PRS;LGSPEC1
fisser	fissoves	V;IPFV;IND;SG;2;PST
purter	purtova	V;IPFV;IND;SG;3;PST
marider	marides	V;SBJV;SG;2;PRS;LGSPEC1
romper	rompova	V;IPFV;IND;SG;3;PST
acurder	acurdove	V;IPFV;IND;SG;1;PST
afermer	afermasse	V;IPFV;SBJV;SG;1;PST
prufesser	prufessa	V;IND;PL;3;PRS;LGSPEC1
istruir	istru	V;IND;PL;3;PRS;LGSPEC1
usserver	usservé	V;NFIN;LGSPEC2
storjer	storjovais	V;IPFV;IND;PL;2;PST
spartir	spartireis	V;IND;PL;2;FUT
destumer	destumer	V;NFIN;LGSPEC1
anuler	anulon	V;SBJV;PL;1;PRS
publicher	publicha	V;IND;SG;3;PRS;LGSPEC1
autoriser	autorisova	V;IPFV;IND;PL;3;PST
ncurajer	ncurajaras	V;IND;SG;2;FUT
stabilir	stabilesce	V;SBJV;PL;3;PRS;LGSPEC2
nascer	nascoves	V;IPFV;IND;SG;2;PST
acuser	acuse	V;SBJV;PL;3;PRS
publicher	publicharas	V;IND;SG;2;FUT
afermer	afermea	V;IND;SG;3;PRS;LGSPEC3
comprer	compraras	V;IND;SG;2;FUT
perde	perde	V;SBJV;SG;1;PRS
coster	costeie	V;SBJV;SG;3;PRS;LGSPEC2
remander	remandeis	V;SBJV;PL;2;PRS
trater	traté	V;NFIN;LGSPEC2
muder	mudes	V;IND;SG;2;PRS;LGSPEC1
damander	damandeie	V;SBJV;SG;1;PRS;LGSPEC2
sponjer	sponjessais	V;IPFV;SBJV;PL;2;PST
damander	damandassan	V;IPFV;SBJV;PL;1;PST
jonjer	jonjaras	V;IND;SG;2;FUT
redujer	redujaron	V;IND;PL;1;FUT
scurter	scurtova	V;IPFV;IND;PL;3;PST
onjer	onjarà	V;IND;SG;3;FUT
resserver	resservova	V;IPFV;IND;SG;3;PST
determiner	determinassa	V;IPFV;SBJV;PL;3;PST
goder	godasse	V;IPFV;SBJV;SG;1;PST
mander	mandaras	V;IND;SG;2;FUT
redujer	redujes	V;IND;SG;2;PRS
trasferir	trasferives	V;IPFV;IND;SG;2;PST
cuntroler	cuntrole	V;SBJV;PL;3;PRS
comprer	compraron	V;IND;PL;1;FUT
detlarer	detlarassan	V;IPFV;SBJV;PL;1;PST
ndrezer	ndrezé	V;NFIN;LGSPEC2
damander	damandarà	V;IND;PL;3;FUT
segurer	segura	V;IND;PL;3;PRS;LGSPEC1
damander	damandassa	V;IPFV;SBJV;SG;3;PST
spidler	spidlé	V;NFIN;LGSPEC2
sustenir	sustenes	V;SBJV;SG;2;PRS;LGSPEC1
istituir	istitue	V;SBJV;SG;1;PRS;LGSPEC1
dovei	dovan	V;IPFV;IND;PL;1;PST;LGSPEC1
porter	portarà	V;IND;PL;3;FUT
cumporter	cumportova	V;IPFV;IND;PL;3;PST
alesirer	alesiré	V;NFIN;LGSPEC2
adoter	adote	V;SBJV;SG;3;PRS;LGSPEC1
cunferir	cunferieis	V;IND;PL;2;PRS
detlarer	detlareis	V;SBJV;PL;2;PRS
acurder	acurdasses	V;IPFV;SBJV;SG;2;PST
trater	trataré	V;IND;SG;1;FUT
reguler	regulova	V;IPFV;IND;PL;3;PST
romper	rompe	V;SBJV;SG;3;PRS
finanzier	finanzieie	V;SBJV;SG;3;PRS;LGSPEC2
finanzier	finanziaras	V;IND;SG;2;FUT
coordiner	coordineie	V;SBJV;SG;3;PRS;LGSPEC2
jì	vas	V;SBJV;SG;2;PRS
viuler	viula	V;IND;SG;3;PRS;LGSPEC1
garantir	garantissa	V;IPFV;SBJV;PL;3;PST
manifester	manifesta	V;NFIN;SG;2;LGSPEC1
franjer	franjarà	V;IND;SG;3;FUT
proibir	proibion	V;SBJV;PL;1;PRS
arjonjer	arjonjeis	V;SBJV;PL;2;PRS
passer	passeie	V;SBJV;SG;3;PRS;LGSPEC2
acrediter	acreditassan	V;IPFV;SBJV;PL;1;PST
sponjer	sponjon	V;SBJV;PL;1;PRS
resulter	resultasses	V;IPFV;SBJV;SG;2;PST
vegnì	vegnì	V;NFIN
remander	remandeie	V;SBJV;SG;3;PRS;LGSPEC2
istituir	istituion	V;SBJV;PL;1;PRS
spieter	spieteie	V;IND;SG;1;PRS;LGSPEC2
secuestrer	secuestrasses	V;IPFV;SBJV;SG;2;PST
seurander	seurandeia	V;IND;PL;3;PRS;LGSPEC2
rejoner	rejona	V;IND;PL;3;PRS;LGSPEC1
rater	ratasse	V;IPFV;SBJV;SG;1;PST
adater	adateies	V;SBJV;SG;2;PRS;LGSPEC2
secuestrer	secuestrarà	V;IND;SG;3;FUT
cunvalider	cunvalidassan	V;IPFV;SBJV;PL;1;PST
mpartir	mparte	V;IND;SG;1;PRS;LGSPEC1
istituir	istituesces	V;IND;SG;2;PRS;LGSPEC2
ejaminer	ejamina	V;NFIN;SG;2;LGSPEC1
fé	fajarà	V;IND;SG;3;FUT
afermer	aferme	V;IND;SG;1;PRS;LGSPEC1
acuser	acuseia	V;NFIN;SG;2;LGSPEC2
istituir	istituissa	V;IPFV;SBJV;SG;3;PST
purter	purton	V;SBJV;PL;1;PRS
perder	perdon	V;IND;PL;1;PRS
mener	menove	V;IPFV;IND;SG;1;PST
jonjer	jonjes	V;IND;SG;2;PRS
mander	mandova	V;IPFV;IND;PL;3;PST
sporjer	sporjesse	V;IPFV;SBJV;SG;1;PST
arjonjer	arjonjove	V;IPFV;IND;SG;1;PST
franjer	franjede	V;NFIN;PL;2
meter	metovan	V;IPFV;IND;PL;1;PST
dejeujer	dejëujassa	V;IPFV;SBJV;PL;3;PST
furmer	furmeie	V;IND;SG;1;PRS;LGSPEC2
schiver	schiveis	V;SBJV;PL;2;PRS
slunger	slungeis	V;SBJV;PL;2;PRS
arbitrer	arbitreis	V;IND;PL;2;PRS
perder	perd	V;NFIN;SG;2
eserziter	eserzites	V;SBJV;SG;2;PRS;LGSPEC1
defrenzier	defrenziaras	V;IND;SG;2;FUT
atribuir	atribuivais	V;IPFV;IND;PL;2;PST
manifester	manifestova	V;IPFV;IND;SG;3;PST
schiver	schivassan	V;IPFV;SBJV;PL;1;PST
messei	messe	V;SBJV;PL;3;PRS
passer	passer	V;NFIN;LGSPEC1
mantenir	mantenissa	V;IPFV;SBJV;SG;3;PST
dormir	dorm	V;NFIN;SG;2;LGSPEC1
aproer	aproarà	V;IND;SG;3;FUT
mander	manda	V;NFIN;SG;2;LGSPEC1
reguler	reguleis	V;IND;PL;2;PRS
ratificher	ratificheie	V;SBJV;SG;3;PRS;LGSPEC2
strenjer	strenjon	V;IND;PL;1;PRS
sporjer	sporjovan	V;IPFV;IND;PL;1;PST
dovei	desses	V;IPFV;SBJV;SG;2;PST;LGSPEC1
strenjer	strenjovan	V;IPFV;IND;PL;1;PST
prufesser	prufesseia	V;IND;SG;3;PRS;LGSPEC2
autoriser	autorisé	V;NFIN;LGSPEC2
reprejenter	reprejente	V;SBJV;SG;3;PRS;LGSPEC1
unir	unive	V;IPFV;IND;SG;1;PST
assegurer	assegurassais	V;IPFV;SBJV;PL;2;PST
afermer	afermove	V;IPFV;IND;SG;1;PST
destumer	destumeia	V;NFIN;SG;2;LGSPEC2
arester	arestassais	V;IPFV;SBJV;PL;2;PST
promulgher	promulghasses	V;IPFV;SBJV;SG;2;PST
rejoner	rejone	V;SBJV;PL;3;PRS
garantir	garant	V;NFIN;SG;2;LGSPEC1
purter	purtede	V;NFIN;PL;2
comunicher	comunicha	V;IND;PL;3;PRS;LGSPEC1
destumer	destumé	V;NFIN;LGSPEC2
furmer	furmeis	V;SBJV;PL;2;PRS
trasferir	trasferesces	V;IND;SG;2;PRS;LGSPEC2
azerter	azerteis	V;IND;PL;2;PRS
cogner	cognes	V;SBJV;SG;2;PRS;LGSPEC1
gaujer	gaujareis	V;IND;PL;2;FUT
cunvalider	cunvalideis	V;IND;PL;2;PRS
passer	passeia	V;IND;PL;3;PRS;LGSPEC2
respuender	respuenda	V;NFIN;SG;2;LGSPEC1
avei	oves	V;IPFV;IND;SG;2;PST;LGSPEC1
marider	maridova	V;IPFV;IND;SG;3;PST
promulgher	promulghes	V;SBJV;SG;2;PRS;LGSPEC1
marider	marida	V;NFIN;SG;2;LGSPEC1
revucher	revuches	V;IND;SG;2;PRS;LGSPEC1
desgorjer	desgorj	V;IND;PL;3;PRS
marider	marideis	V;SBJV;PL;2;PRS
romper	romper	V;NFIN;LGSPEC1
ncurajer	ncuraje	V;SBJV;PL;3;PRS
garantir	garant	V;IND;SG;3;PRS;LGSPEC1
rejoner	rejonareis	V;IND;PL;2;FUT
delibrer	delibroves	V;IPFV;IND;SG;2;PST
anuler	anule	V;SBJV;SG;1;PRS;LGSPEC1
entenjer	entenjaré	V;IND;SG;1;FUT
comprer	comprove	V;IPFV;IND;SG;1;PST
delegher	delegheies	V;SBJV;SG;2;PRS;LGSPEC2
arester	arestede	V;NFIN;PL;2
tradujer	tradujove	V;IPFV;IND;SG;1;PST
comprer	compra	V;IND;PL;3;PRS;LGSPEC1
anuler	anulasse	V;IPFV;SBJV;SG;1;PST
dormir	dormiré	V;IND;SG;1;FUT
adurver	adurvon	V;SBJV;PL;1;PRS
passer	passeis	V;SBJV;PL;2;PRS
unir	unir	V;NFIN;LGSPEC1
spidler	spidleia	V;IND;PL;3;PRS;LGSPEC2
secuestrer	secuestres	V;IND;SG;2;PRS;LGSPEC1
seurander	seurandon	V;SBJV;PL;1;PRS
ancunter	ancuntovais	V;IPFV;IND;PL;2;PST
emaner	emaneis	V;IND;PL;2;PRS
romper	rompessan	V;IPFV;SBJV;PL;1;PST
cuntroler	cuntrolaré	V;IND;SG;1;FUT
ndicher	ndichede	V;NFIN;PL;2
arjonjer	arjonj	V;IND;PL;3;PRS
numiner	numinasses	V;IPFV;SBJV;SG;2;PST
rater	rataras	V;IND;SG;2;FUT
goder	godeie	V;IND;SG;1;PRS;LGSPEC2
mpartir	mpartivais	V;IPFV;IND;PL;2;PST
scuter	scoute	V;IND;SG;1;PRS;LGSPEC1
adater	adate	V;SBJV;PL;3;PRS
tramuder	tramudeia	V;IND;SG;3;PRS;LGSPEC2
cogner	cognon	V;SBJV;PL;1;PRS
rester	restasses	V;IPFV;SBJV;SG;2;PST
produjer	produje	V;IND;SG;1;PRS
desvier	desvia	V;NFIN;SG;2;LGSPEC1
schiver	schiva	V;IND;SG;3;PRS;LGSPEC1
mpartir	mpartiron	V;IND;PL;1;FUT
adoter	adotassan	V;IPFV;SBJV;PL;1;PST
atuer	atuassais	V;IPFV;SBJV;PL;2;PST
acrediter	acreditarà	V;IND;PL;3;FUT
acurder	acurdassa	V;IPFV;SBJV;SG;3;PST
marider	maridarà	V;IND;SG;3;FUT
schiver	schiva	V;NFIN;SG;2;LGSPEC1
purter	purtoves	V;IPFV;IND;SG;2;PST
arbitrer	arbitrassais	V;IPFV;SBJV;PL;2;PST
ratificher	ratifichede	V;NFIN;PL;2
entenjer	entenje	V;SBJV;SG;1;PRS
sporjer	sporje	V;IND;SG;1;PRS
urganiser	urganisé	V;NFIN;LGSPEC2
porter	porteis	V;SBJV;PL;2;PRS
acurder	acurdea	V;IND;SG;3;PRS;LGSPEC3
ndicher	ndicha	V;IND;PL;3;PRS;LGSPEC1
populer	populovais	V;IPFV;IND;PL;2;PST
furmer	furmeie	V;SBJV;SG;3;PRS;LGSPEC2
alesirer	alesireies	V;SBJV;SG;2;PRS;LGSPEC2
segurer	segureie	V;SBJV;SG;1;PRS;LGSPEC2
goder	goda	V;IND;SG;3;PRS;LGSPEC1
resulter	resulté	V;NFIN;LGSPEC2
stabilir	stabilesces	V;IND;SG;2;PRS;LGSPEC2
ndicher	ndicheia	V;IND;PL;3;PRS;LGSPEC2
depenjer	depenjaras	V;IND;SG;2;FUT
adurver	adurvoves	V;IPFV;IND;SG;2;PST
franjer	franjarà	V;IND;PL;3;FUT
remplazer	remplaze	V;SBJV;SG;1;PRS;LGSPEC1
secuestrer	secuestra	V;IND;PL;3;PRS;LGSPEC1
porter	portassan	V;IPFV;SBJV;PL;1;PST
reurganiser	reurganisassan	V;IPFV;SBJV;PL;1;PST
volei	volei	V;NFIN;LGSPEC1
parteziper	partezipasses	V;IPFV;SBJV;SG;2;PST
njinier	njinieie	V;SBJV;SG;3;PRS;LGSPEC2
educher	educha	V;IND;PL;3;PRS;LGSPEC1
alesirer	alesiraras	V;IND;SG;2;FUT
cianter	cianteia	V;IND;SG;3;PRS;LGSPEC2
ressolver	ressolvassa	V;IPFV;SBJV;SG;3;PST
adoter	adotarà	V;IND;PL;3;FUT
arjonjer	arjonjaré	V;IND;SG;1;FUT
cunferir	cunferion	V;SBJV;PL;1;PRS
determiner	determineia	V;IND;SG;3;PRS;LGSPEC2
cunferir	cunferide	V;NFIN;PL;2
podei	pos	V;IND;SG;2;PRS
ejaminer	ejaminova	V;IPFV;IND;PL;3;PST
anuler	anulé	V;NFIN;LGSPEC2
urganiser	urganisaras	V;IND;SG;2;FUT
promulgher	promulghareis	V;IND;PL;2;FUT
muder	mudeies	V;SBJV;SG;2;PRS;LGSPEC2
capir	capiva	V;IPFV;IND;PL;3;PST
pronunzier	pronunzier	V;NFIN;LGSPEC1
dormir	dormion	V;IND;PL;1;PRS
spieter	spietaré	V;IND;SG;1;FUT
scriver	scrivon	V;IND;PL;1;PRS
giudicher	giudiche	V;SBJV;SG;1;PRS;LGSPEC1
pronunzier	pronunzia	V;NFIN;SG;2;LGSPEC1
arester	aresta	V;IND;PL;3;PRS;LGSPEC1
erjer	erjede	V;NFIN;PL;2
registrer	registrova	V;IPFV;IND;PL;3;PST
meter	meton	V;IND;PL;1;PRS
renunzier	renunziaras	V;IND;SG;2;FUT
jì	jivais	V;IPFV;IND;PL;2;PST
trasferir	trasfere	V;IND;SG;1;PRS;LGSPEC1
dormir	dormesces	V;IND;SG;2;PRS;LGSPEC2
furmer	furmarà	V;IND;SG;3;FUT
azerter	azertareis	V;IND;PL;2;FUT
passer	passassan	V;IPFV;SBJV;PL;1;PST
arester	arestaré	V;IND;SG;1;FUT
limiter	limitarà	V;IND;PL;3;FUT
giudicher	giudiche	V;IND;SG;1;PRS;LGSPEC1
furmer	furmasse	V;IPFV;SBJV;SG;1;PST
schiver	schivasse	V;IPFV;SBJV;SG;1;PST
scriver	scrivesse	V;IPFV;SBJV;SG;1;PST
coordener	coordenassais	V;IPFV;SBJV;PL;2;PST
produjer	produjessa	V;IPFV;SBJV;PL;3;PST
muder	mudarà	V;IND;SG;3;FUT
partir	pert	V;SBJV;PL;3;PRS
furmer	furmeies	V;IND;SG;2;PRS;LGSPEC2
sotscriver	sotscrivessan	V;IPFV;SBJV;PL;1;PST
mutiver	mutivon	V;IND;PL;1;PRS
entenjer	entenje	V;SBJV;PL;3;PRS
produjer	produjessa	V;IPFV;SBJV;SG;3;PST
publicher	publicheies	V;SBJV;SG;2;PRS;LGSPEC2
messei	messove	V;IPFV;IND;SG;1;PST
ratificher	ratificha	V;IND;SG;3;PRS;LGSPEC1
scurter	scurtarà	V;IND;PL;3;FUT
passer	passeia	V;NFIN;SG;2;LGSPEC2
messei	messarà	V;IND;SG;3;FUT
tramuder	tramudaron	V;IND;PL;1;FUT
dejeujer	dejëujes	V;IND;SG;2;PRS;LGSPEC1
acuser	acusé	V;NFIN;LGSPEC2
vedei	vedessan	V;IPFV;SBJV;PL;1;PST
autoriser	autoriseis	V;IND;PL;2;PRS
produjer	produjon	V;IND;PL;1;PRS
desvier	desviovan	V;IPFV;IND;PL;1;PST
muder	mudareis	V;IND;PL;2;FUT
manifester	manifestassa	V;IPFV;SBJV;PL;3;PST
deslier	deslie	V;SBJV;SG;3;PRS;LGSPEC1
nfurmer	nfurme	V;IND;SG;1;PRS;LGSPEC1
prejenter	prejentassan	V;IPFV;SBJV;PL;1;PST
marider	maridaron	V;IND;PL;1;FUT
jonjer	jonje	V;SBJV;PL;3;PRS
populer	populeies	V;IND;SG;2;PRS;LGSPEC2
comunicher	comunicha	V;NFIN;SG;2;LGSPEC1
reurganiser	reurganison	V;SBJV;PL;1;PRS
cogner	cognede	V;NFIN;PL;2
perder	perdaras	V;IND;SG;2;FUT
furmer	furmeie	V;SBJV;SG;1;PRS;LGSPEC2
mantenir	manteniré	V;IND;SG;1;FUT
publicher	publichovan	V;IPFV;IND;PL;1;PST
passer	passa	V;NFIN;SG;2;LGSPEC1
cuntroler	cuntrole	V;SBJV;SG;1;PRS;LGSPEC1
lascer	lascovais	V;IPFV;IND;PL;2;PST
mener	menea	V;IND;SG;3;PRS;LGSPEC3
destiner	destinassa	V;IPFV;SBJV;SG;3;PST
finanzier	finanzieie	V;SBJV;SG;1;PRS;LGSPEC2
scriver	scrive	V;SBJV;PL;3;PRS
costituir	costituive	V;IPFV;IND;SG;1;PST
cunferir	cunfer	V;NFIN;SG;2;LGSPEC1
danejer	danejassais	V;IPFV;SBJV;PL;2;PST
delibrer	delibrea	V;IND;SG;3;PRS;LGSPEC3
delibrer	delibrassa	V;IPFV;SBJV;SG;3;PST
acuser	acusaras	V;IND;SG;2;FUT
messei	messe	V;SBJV;SG;1;PRS
revucher	revuché	V;NFIN;LGSPEC2
resulter	resultarà	V;IND;SG;3;FUT
spieter	spiete	V;SBJV;SG;3;PRS;LGSPEC1
aplicher	apliche	V;SBJV;SG;3;PRS;LGSPEC1
eserziter	eserzitede	V;NFIN;PL;2
condujer	condujesse	V;IPFV;SBJV;SG;1;PST
rester	resteie	V;IND;SG;1;PRS;LGSPEC2
finanzier	finanzia	V;NFIN;SG;2;LGSPEC1
strenjer	strenjova	V;IPFV;IND;PL;3;PST
detlarer	detlararé	V;IND;SG;1;FUT
reverir	reverion	V;IND;PL;1;PRS
adurver	adurvaron	V;IND;PL;1;FUT
schiver	schivea	V;IND;SG;3;PRS;LGSPEC3
coordener	coordeneie	V;SBJV;SG;3;PRS;LGSPEC2
manifester	manifestarà	V;IND;SG;3;FUT
fisser	fisson	V;IND;PL;1;PRS
parteziper	partezipovan	V;IPFV;IND;PL;1;PST
istruir	istruiva	V;IPFV;IND;SG;3;PST
parteziper	parteziparé	V;IND;SG;1;FUT
renunzier	renunziede	V;NFIN;PL;2
secuestrer	secuestre	V;IND;SG;1;PRS;LGSPEC1
defrenzier	defrenzion	V;IND;PL;1;PRS
gaujer	gaujer	V;NFIN;LGSPEC1
depenjer	depenjeis	V;SBJV;PL;2;PRS
cuntroler	cuntroleia	V;IND;SG;3;PRS;LGSPEC2
cruzier	cruziaré	V;IND;SG;1;FUT
capir	capissais	V;IPFV;SBJV;PL;2;PST
eserziter	eserzitasse	V;IPFV;SBJV;SG;1;PST
dé	daras	V;IND;SG;2;FUT
costituir	costitu	V;IND;SG;3;PRS;LGSPEC1
mpartir	mpartieis	V;SBJV;PL;2;PRS
cherder	cherdoves	V;IPFV;IND;SG;2;PST
podei	podon	V;SBJV;PL;1;PRS
aproer	aproovan	V;IPFV;IND;PL;1;PST
corompe	corompe	V;NFIN;LGSPEC2
rater	rateia	V;IND;PL;3;PRS;LGSPEC2
afermer	afermeies	V;SBJV;SG;2;PRS;LGSPEC2
cruzier	cruziove	V;IPFV;IND;SG;1;PST
educher	educhede	V;NFIN;PL;2
passer	passaron	V;IND;PL;1;FUT
publicher	publiche	V;SBJV;PL;3;PRS
tramuder	tramudovan	V;IPFV;IND;PL;1;PST
revucher	revuche	V;IND;SG;1;PRS;LGSPEC1
sponjer	sponjon	V;IND;PL;1;PRS
pronunzier	pronunzieie	V;SBJV;SG;3;PRS;LGSPEC2
stabilir	stabilieis	V;SBJV;PL;2;PRS
danejer	daneje	V;SBJV;SG;1;PRS;LGSPEC1
goder	godassais	V;IPFV;SBJV;PL;2;PST
cianter	cianta	V;NFIN;SG;2;LGSPEC1
marider	maridasse	V;IPFV;SBJV;SG;1;PST
destumer	destumeies	V;IND;SG;2;PRS;LGSPEC2
numiner	numinaron	V;IND;PL;1;FUT
cunzeder	cunzedeis	V;SBJV;PL;2;PRS
dormir	dormieis	V;SBJV;PL;2;PRS
cumander	cumandede	V;NFIN;PL;2
defrenzier	defrenzieis	V;SBJV;PL;2;PRS
mander	mandovais	V;IPFV;IND;PL;2;PST
atuer	atueis	V;SBJV;PL;2;PRS
aproer	aproeia	V;IND;PL;3;PRS;LGSPEC2
scuter	scutaras	V;IND;SG;2;FUT
corompe	corompessais	V;IPFV;SBJV;PL;2;PST
strenjer	strenjovais	V;IPFV;IND;PL;2;PST
reprejenter	reprejenteies	V;IND;SG;2;PRS;LGSPEC2
tradujer	tradujessa	V;IPFV;SBJV;PL;3;PST
lascer	lasce	V;SBJV;SG;3;PRS;LGSPEC1
remplazer	remplazareis	V;IND;PL;2;FUT
volei	volovan	V;IPFV;IND;PL;1;PST
istituir	istitue	V;SBJV;PL;3;PRS;LGSPEC1
promulgher	promulghassais	V;IPFV;SBJV;PL;2;PST
cruzier	cruzieie	V;IND;SG;1;PRS;LGSPEC2
perde	perdovais	V;IPFV;IND;PL;2;PST
ressolver	ressolvova	V;IPFV;IND;PL;3;PST
depenjer	depenjes	V;SBJV;SG;2;PRS
acuser	acusova	V;IPFV;IND;PL;3;PST
resserver	resservassa	V;IPFV;SBJV;SG;3;PST
cianter	cianton	V;SBJV;PL;1;PRS
cianter	cianteies	V;IND;SG;2;PRS;LGSPEC2
jonjer	jonj	V;NFIN;SG;2
emaner	emaner	V;NFIN;LGSPEC1
afermer	aferma	V;NFIN;SG;2;LGSPEC1
onjer	onj	V;IND;PL;3;PRS
gaujer	gaujé	V;NFIN;LGSPEC2
assegurer	assegureis	V;IND;PL;2;PRS
podei	podessais	V;IPFV;SBJV;PL;2;PST
cunvalider	cunvalidarà	V;IND;SG;3;FUT
seurander	seurandeie	V;SBJV;SG;3;PRS;LGSPEC2
anuler	anuleia	V;IND;SG;3;PRS;LGSPEC2
unir	univais	V;IPFV;IND;PL;2;PST
manifester	manifesteia	V;IND;SG;3;PRS;LGSPEC2
educher	educhassais	V;IPFV;SBJV;PL;2;PST
arbitrer	arbitreia	V;NFIN;SG;2;LGSPEC2
emaner	emanon	V;SBJV;PL;1;PRS
ndicher	ndiche	V;SBJV;PL;3;PRS
stipuler	stipuleia	V;IND;PL;3;PRS;LGSPEC2
alesirer	alesireie	V;SBJV;SG;1;PRS;LGSPEC2
erjer	erje	V;IND;SG;1;PRS
coordiner	coordine	V;SBJV;SG;3;PRS;LGSPEC1
rater	ratasses	V;IPFV;SBJV;SG;2;PST
strenjer	strenjessa	V;IPFV;SBJV;SG;3;PST
giudicher	giudicharé	V;IND;SG;1;FUT
podei	podeis	V;IND;PL;2;PRS
acuser	acusaron	V;IND;PL;1;FUT
seurander	seurandaron	V;IND;PL;1;FUT
populer	populeie	V;SBJV;SG;1;PRS;LGSPEC2
seurander	seurandareis	V;IND;PL;2;FUT
rejoner	rejonassan	V;IPFV;SBJV;PL;1;PST
viuler	viuleies	V;IND;SG;2;PRS;LGSPEC2
emaner	emaneis	V;SBJV;PL;2;PRS
nascer	nasc	V;IND;PL;3;PRS
stabilir	stabilireis	V;IND;PL;2;FUT
adoter	adotea	V;IND;SG;3;PRS;LGSPEC3
gaujer	gaujassais	V;IPFV;SBJV;PL;2;PST
partir	pert	V;IND;SG;3;PRS
reverir	rever	V;IND;PL;3;PRS;LGSPEC1
populer	populassais	V;IPFV;SBJV;PL;2;PST
danejer	danejaron	V;IND;PL;1;FUT
capir	capide	V;NFIN;PL;2
reprejenter	reprejenteie	V;SBJV;SG;1;PRS;LGSPEC2
udir	udion	V;SBJV;PL;1;PRS
numiner	numinassais	V;IPFV;SBJV;PL;2;PST
viver	vivon	V;SBJV;PL;1;PRS
dormir	dormesce	V;SBJV;SG;1;PRS;LGSPEC2
sotscriver	sotscrivaron	V;IND;PL;1;FUT
muder	mudeie	V;SBJV;SG;3;PRS;LGSPEC2
cuntroler	cuntrolassa	V;IPFV;SBJV;PL;3;PST
reprejenter	reprejentede	V;NFIN;PL;2
avei	arà	V;IND;SG;3;FUT
scriver	scrivarà	V;IND;PL;3;FUT
cundaner	cundanarà	V;IND;SG;3;FUT
trasferir	trasferireis	V;IND;PL;2;FUT
promulgher	promulghes	V;IND;SG;2;PRS;LGSPEC1
comunicher	comunichasses	V;IPFV;SBJV;SG;2;PST
redujer	redujessais	V;IPFV;SBJV;PL;2;PST
resserver	resserveia	V;NFIN;SG;2;LGSPEC2
cherder	cherdé	V;NFIN;LGSPEC2
aproer	aproareis	V;IND;PL;2;FUT
savei	savon	V;SBJV;PL;1;PRS
marider	maridon	V;SBJV;PL;1;PRS
dormir	dormivan	V;IPFV;IND;PL;1;PST
njinier	njiniaras	V;IND;SG;2;FUT
rester	restovais	V;IPFV;IND;PL;2;PST
storjer	storjede	V;NFIN;PL;2
someter	sometassa	V;IPFV;SBJV;PL;3;PST
nfurmer	nfurmarà	V;IND;SG;3;FUT
adurver	adurveies	V;IND;SG;2;PRS;LGSPEC2
morir	muere	V;SBJV;SG;1;PRS
costituir	costituiron	V;IND;PL;1;FUT
cuntroler	cuntrolaras	V;IND;SG;2;FUT
sustenir	sustenieis	V;IND;PL;2;PRS
mantenir	mantenesc	V;NFIN;SG;2;LGSPEC2
ndicher	ndicha	V;NFIN;SG;2;LGSPEC1
mirer	mires	V;IND;SG;2;PRS;LGSPEC1
mutiver	mutiveis	V;IND;PL;2;PRS
pruibir	pruibes	V;IND;SG;2;PRS;LGSPEC1
messei	messessa	V;IPFV;SBJV;SG;3;PST
eserziter	eserzite	V;SBJV;SG;3;PRS;LGSPEC1
acurder	acurdarà	V;IND;PL;3;FUT
segurer	segureia	V;NFIN;SG;2;LGSPEC2
avei	ove	V;IPFV;IND;SG;1;PST;LGSPEC1
coordener	coordenassa	V;IPFV;SBJV;SG;3;PST
onjer	onjon	V;IND;PL;1;PRS
mantenir	mantenesces	V;IND;SG;2;PRS;LGSPEC2
proibir	proibesce	V;SBJV;PL;3;PRS;LGSPEC2
resulter	resultassais	V;IPFV;SBJV;PL;2;PST
savei	savessan	V;IPFV;SBJV;PL;1;PST
acurder	acurda	V;IND;PL;3;PRS;LGSPEC1
jonjer	jonjove	V;IPFV;IND;SG;1;PST
populer	popularon	V;IND;PL;1;FUT
seurander	seurande	V;SBJV;SG;1;PRS;LGSPEC1
emaner	emanarà	V;IND;PL;3;FUT
giudicher	giudiche	V;SBJV;SG;3;PRS;LGSPEC1
parteziper	partezipassan	V;IPFV;SBJV;PL;1;PST
udir	udiva	V;IPFV;IND;PL;3;PST
desvier	desviassa	V;IPFV;SBJV;PL;3;PST
condujer	condujovais	V;IPFV;IND;PL;2;PST
desvier	desviarà	V;IND;PL;3;FUT
azerter	azerteia	V;IND;PL;3;PRS;LGSPEC2
usserver	usserveis	V;SBJV;PL;2;PRS
comprer	comprovais	V;IPFV;IND;PL;2;PST
cumander	cumandeia	V;IND;PL;3;PRS;LGSPEC2
slunger	slungoves	V;IPFV;IND;SG;2;PST
cruzier	cruziasses	V;IPFV;SBJV;SG;2;PST
arbitrer	arbitrova	V;IPFV;IND;SG;3;PST
azerter	azertovan	V;IPFV;IND;PL;1;PST
capir	capissan	V;IPFV;SBJV;PL;1;PST
garantir	garantirà	V;IND;PL;3;FUT
remplazer	remplazarà	V;IND;PL;3;FUT
ancunter	ancuntede	V;NFIN;PL;2
mantenir	mantenirà	V;IND;PL;3;FUT
stabilir	stabile	V;IND;SG;1;PRS;LGSPEC1
dejeujer	dejëuja	V;IND;PL;3;PRS;LGSPEC1
respuender	respuendon	V;SBJV;PL;1;PRS
mpartir	mpartesc	V;NFIN;SG;2;LGSPEC2
adater	adatova	V;IPFV;IND;SG;3;PST
storjer	storj	V;IND;PL;3;PRS
franjer	franjesse	V;IPFV;SBJV;SG;1;PST
messei	messessais	V;IPFV;SBJV;PL;2;PST
autoriser	autorise	V;SBJV;SG;1;PRS;LGSPEC1
costituir	costituesc	V;IND;SG;3;PRS;LGSPEC2
scurter	scurteie	V;SBJV;SG;1;PRS;LGSPEC2
purter	purtea	V;IND;SG;3;PRS;LGSPEC3
ndrezer	ndrezeis	V;SBJV;PL;2;PRS
dejeujer	dejëuje	V;SBJV;SG;1;PRS;LGSPEC1
apurver	apurva	V;IND;PL;3;PRS;LGSPEC1
eserziter	eserzitassais	V;IPFV;SBJV;PL;2;PST
nfurmer	nfurmede	V;NFIN;PL;2
aproer	aproeia	V;IND;SG;3;PRS;LGSPEC2
cumporter	cumportareis	V;IND;PL;2;FUT
unir	unesce	V;SBJV;SG;1;PRS;LGSPEC2
pruibir	pruibe	V;SBJV;SG;1;PRS;LGSPEC1
ancunter	ancunteies	V;IND;SG;2;PRS;LGSPEC2
reverir	reveresces	V;IND;SG;2;PRS;LGSPEC2
rester	reste	V;SBJV;SG;1;PRS;LGSPEC1
istruir	istruion	V;SBJV;PL;1;PRS
comunicher	comunichove	V;IPFV;IND;SG;1;PST
unir	unissan	V;IPFV;SBJV;PL;1;PST
azerter	azerte	V;SBJV;SG;1;PRS;LGSPEC1
assenier	asseniassan	V;IPFV;SBJV;PL;1;PST
partir	partivan	V;IPFV;IND;PL;1;PST
educher	educharon	V;IND;PL;1;FUT
dormir	dormir	V;NFIN;LGSPEC1
assegurer	asseguron	V;IND;PL;1;PRS
franjer	franje	V;SBJV;SG;1;PRS
passer	passe	V;SBJV;SG;3;PRS;LGSPEC1
produjer	produjovan	V;IPFV;IND;PL;1;PST
autoriser	autorisasses	V;IPFV;SBJV;SG;2;PST
aplicher	aplicha	V;IND;SG;3;PRS;LGSPEC1
nfurmer	nfurma	V;IND;SG;3;PRS;LGSPEC1
autoriser	autorisove	V;IPFV;IND;SG;1;PST
reguler	reguleies	V;IND;SG;2;PRS;LGSPEC2
remplazer	remplazeie	V;SBJV;SG;3;PRS;LGSPEC2
giudicher	giudicha	V;IND;SG;3;PRS;LGSPEC1
atribuir	atribuivan	V;IPFV;IND;PL;1;PST
comprer	compron	V;IND;PL;1;PRS
deslier	deslies	V;IND;SG;2;PRS;LGSPEC1
porter	porte	V;SBJV;SG;1;PRS;LGSPEC1
mutiver	mutiveie	V;SBJV;SG;1;PRS;LGSPEC2
destumer	destumon	V;IND;PL;1;PRS
prejenter	prejentes	V;SBJV;SG;2;PRS;LGSPEC1
scurter	scurton	V;IND;PL;1;PRS
revucher	revucha	V;NFIN;SG;2;LGSPEC1
passer	passassa	V;IPFV;SBJV;PL;3;PST
depenjer	depenjon	V;IND;PL;1;PRS
rezever	rezevaras	V;IND;SG;2;FUT
perde	perde	V;SBJV;PL;3;PRS
jonjer	jonjaron	V;IND;PL;1;FUT
avei	à	V;IND;SG;3;PRS
tradujer	tradujovais	V;IPFV;IND;PL;2;PST
savei	savova	V;IPFV;IND;PL;3;PST
danejer	danejeia	V;IND;PL;3;PRS;LGSPEC2
resulter	resultasse	V;IPFV;SBJV;SG;1;PST
destiner	destinova	V;IPFV;IND;PL;3;PST
spieter	spietassa	V;IPFV;SBJV;PL;3;PST
ancunter	ancunta	V;NFIN;SG;2;LGSPEC1
coordener	coordenon	V;SBJV;PL;1;PRS
viuler	viularà	V;IND;PL;3;FUT
publicher	publichassais	V;IPFV;SBJV;PL;2;PST
scuter	scouteies	V;SBJV;SG;2;PRS;LGSPEC2
jonjer	jonjessa	V;IPFV;SBJV;SG;3;PST
destumer	destumeia	V;IND;PL;3;PRS;LGSPEC2
ressolver	ressolvareis	V;IND;PL;2;FUT
fisser	fisseia	V;IND;SG;3;PRS;LGSPEC2
ncurajer	ncuraje	V;IND;SG;1;PRS;LGSPEC1
muder	muda	V;IND;SG;3;PRS;LGSPEC1
ressolver	ressolvea	V;IND;SG;3;PRS;LGSPEC3
onjer	onjovan	V;IPFV;IND;PL;1;PST
proibir	proibivan	V;IPFV;IND;PL;1;PST
unir	univan	V;IPFV;IND;PL;1;PST
podei	podesse	V;IPFV;SBJV;SG;1;PST
spidler	spidlarà	V;IND;SG;3;FUT
ressolver	ressolves	V;SBJV;SG;2;PRS;LGSPEC1
mutiver	mutivova	V;IPFV;IND;SG;3;PST
meter	metarà	V;IND;PL;3;FUT
spieter	spietes	V;SBJV;SG;2;PRS;LGSPEC1
spartir	spartivais	V;IPFV;IND;PL;2;PST
numiner	numines	V;SBJV;SG;2;PRS;LGSPEC1
trater	tratassan	V;IPFV;SBJV;PL;1;PST
capir	capesc	V;NFIN;SG;2;LGSPEC2
delegher	deleghove	V;IPFV;IND;SG;1;PST
purter	purtasses	V;IPFV;SBJV;SG;2;PST
sotscriver	sotscrive	V;SBJV;SG;3;PRS
ndicher	ndichassa	V;IPFV;SBJV;SG;3;PST
porter	porteies	V;SBJV;SG;2;PRS;LGSPEC2
destiner	destinassa	V;IPFV;SBJV;PL;3;PST
proibir	proibirà	V;IND;PL;3;FUT
danejer	danejova	V;IPFV;IND;PL;3;PST
usserver	usserve	V;SBJV;SG;3;PRS;LGSPEC1
parteziper	partezipoves	V;IPFV;IND;SG;2;PST
anuler	anula	V;IND;SG;3;PRS;LGSPEC1
limiter	limite	V;SBJV;PL;3;PRS
fisser	fissarà	V;IND;SG;3;FUT
detlarer	detlarede	V;NFIN;PL;2
gaujer	gaujassa	V;IPFV;SBJV;PL;3;PST
cogner	cognasses	V;IPFV;SBJV;SG;2;PST
spieter	spietasses	V;IPFV;SBJV;SG;2;PST
ndrezer	ndrezova	V;IPFV;IND;PL;3;PST
danejer	danejeis	V;IND;PL;2;PRS
mpartir	mpartissa	V;IPFV;SBJV;PL;3;PST
coordener	coordenon	V;IND;PL;1;PRS
numiner	numines	V;IND;SG;2;PRS;LGSPEC1
corompe	corompessa	V;IPFV;SBJV;SG;3;PST
jonjer	jonjesse	V;IPFV;SBJV;SG;1;PST
adater	adate	V;SBJV;SG;1;PRS;LGSPEC1
azerter	azerton	V;IND;PL;1;PRS
resserver	resservea	V;IND;SG;3;PRS;LGSPEC3
mutiver	mutiver	V;NFIN;LGSPEC1
publicher	publichassa	V;IPFV;SBJV;PL;3;PST
mander	mandé	V;NFIN;LGSPEC2
assenier	assenie	V;SBJV;SG;3;PRS;LGSPEC1
comunicher	comunicharon	V;IND;PL;1;FUT
alesirer	alesirede	V;NFIN;PL;2
mpartir	mpartisse	V;IPFV;SBJV;SG;1;PST
spidler	spidla	V;IND;SG;3;PRS;LGSPEC1
scurter	scurtes	V;IND;SG;2;PRS;LGSPEC1
ncurajer	ncuraja	V;IND;PL;3;PRS;LGSPEC1
afermer	afermassa	V;IPFV;SBJV;SG;3;PST
morir	moriva	V;IPFV;IND;PL;3;PST
usserver	usservea	V;IND;SG;3;PRS;LGSPEC3
ncurajer	ncurajaré	V;IND;SG;1;FUT
produjer	produje	V;NFIN;LGSPEC2
lascer	lasces	V;SBJV;SG;2;PRS;LGSPEC1
comunicher	comunichon	V;IND;PL;1;PRS
arester	aresteies	V;SBJV;SG;2;PRS;LGSPEC2
adoter	adotassa	V;IPFV;SBJV;SG;3;PST
desvier	desvion	V;SBJV;PL;1;PRS
cundaner	cundanaras	V;IND;SG;2;FUT
lascer	lascareis	V;IND;PL;2;FUT
populer	populeie	V;IND;SG;1;PRS;LGSPEC2
tramuder	tramudeie	V;IND;SG;1;PRS;LGSPEC2
aplicher	aplichea	V;IND;SG;3;PRS;LGSPEC3
stipuler	stipula	V;NFIN;SG;2;LGSPEC1
destiner	destinaré	V;IND;SG;1;FUT
determiner	determine	V;SBJV;PL;3;PRS
reurganiser	reurganisarà	V;IND;PL;3;FUT
depenjer	depenjesse	V;IPFV;SBJV;SG;1;PST
rejoner	rejoneia	V;NFIN;SG;2;LGSPEC2
njinier	njiniovais	V;IPFV;IND;PL;2;PST
plovei	plueve	V;SBJV;SG;3;PRS
nfurmer	nfurmeia	V;NFIN;SG;2;LGSPEC2
terjer	terjede	V;NFIN;PL;2
promulgher	promulghé	V;NFIN;LGSPEC2
populer	popule	V;SBJV;PL;3;PRS
reprejenter	reprejenteis	V;SBJV;PL;2;PRS
comprer	compra	V;NFIN;SG;2;LGSPEC1
ejaminer	ejaminaré	V;IND;SG;1;FUT
coordener	coordenaré	V;IND;SG;1;FUT
manifester	manifestes	V;IND;SG;2;PRS;LGSPEC1
nascer	nascova	V;IPFV;IND;SG;3;PST
remplazer	remplazassais	V;IPFV;SBJV;PL;2;PST
adurver	adurvassa	V;IPFV;SBJV;PL;3;PST
atuer	atuon	V;IND;PL;1;PRS
njinier	njinieie	V;SBJV;SG;1;PRS;LGSPEC2
trater	tratareis	V;IND;PL;2;FUT
sustenir	sustenesces	V;IND;SG;2;PRS;LGSPEC2
gaujer	gaujarà	V;IND;PL;3;FUT
ressolver	ressolvovan	V;IPFV;IND;PL;1;PST
coordener	coordenova	V;IPFV;IND;SG;3;PST
trater	tratede	V;NFIN;PL;2
cundaner	cundanaron	V;IND;PL;1;FUT
tramuder	tramuda	V;NFIN;SG;2;LGSPEC1
ejaminer	ejaminassa	V;IPFV;SBJV;PL;3;PST
scriver	scriv	V;IND;PL;3;PRS
muder	mudé	V;NFIN;LGSPEC2
cunferir	cunfer	V;IND;SG;3;PRS;LGSPEC1
revucher	revucharas	V;IND;SG;2;FUT
apurver	apurvova	V;IPFV;IND;SG;3;PST
prufesser	prufesseies	V;IND;SG;2;PRS;LGSPEC2
numiner	numinon	V;SBJV;PL;1;PRS
dovei	dessove	V;IPFV;IND;SG;1;PST;LGSPEC2
delibrer	delibraras	V;IND;SG;2;FUT
destumer	destume	V;IND;SG;1;PRS;LGSPEC1
delegher	delegha	V;NFIN;SG;2;LGSPEC1
mpartir	mpartissais	V;IPFV;SBJV;PL;2;PST
storjer	storjon	V;IND;PL;1;PRS
ressolver	ressolver	V;NFIN;LGSPEC1
curespuender	curespuende	V;IND;SG;1;PRS;LGSPEC1
aplicher	aplicheia	V;NFIN;SG;2;LGSPEC2
scuter	scouteia	V;IND;PL;3;PRS;LGSPEC2
someter	someteie	V;SBJV;SG;1;PRS;LGSPEC2
furmer	furma	V;IND;SG;3;PRS;LGSPEC1
scriver	scriveis	V;SBJV;PL;2;PRS
educher	educharé	V;IND;SG;1;FUT
spidler	spidles	V;SBJV;SG;2;PRS;LGSPEC1
spidler	spidlova	V;IPFV;IND;SG;3;PST
determiner	determinove	V;IPFV;IND;SG;1;PST
sporjer	sporjes	V;SBJV;SG;2;PRS
acurder	acurdaron	V;IND;PL;1;FUT
adurver	adurvé	V;NFIN;LGSPEC2
cogner	cogneis	V;IND;PL;2;PRS
adoter	adotassa	V;IPFV;SBJV;PL;3;PST
trater	trateies	V;IND;SG;2;PRS;LGSPEC2
viuler	viulon	V;IND;PL;1;PRS
secuestrer	secuestrassais	V;IPFV;SBJV;PL;2;PST
emaner	emaneia	V;IND;SG;3;PRS;LGSPEC2
registrer	registreie	V;SBJV;SG;1;PRS;LGSPEC2
arbitrer	arbitreie	V;SBJV;SG;1;PRS;LGSPEC2
meter	met	V;NFIN;SG;2
cumporter	cumportarà	V;IND;SG;3;FUT
ncurajer	ncurajes	V;IND;SG;2;PRS;LGSPEC1
prufesser	prufessove	V;IPFV;IND;SG;1;PST
jì	vae	V;IND;SG;1;PRS
comunicher	comunichassa	V;IPFV;SBJV;SG;3;PST
cianter	ciantaras	V;IND;SG;2;FUT
morir	moride	V;NFIN;PL;2
rater	rate	V;SBJV;SG;3;PRS;LGSPEC1
garantir	garantiva	V;IPFV;IND;SG;3;PST
muder	mude	V;SBJV;SG;1;PRS;LGSPEC1
pruibir	pruibe	V;IND;SG;1;PRS;LGSPEC1
alesirer	alesireia	V;IND;PL;3;PRS;LGSPEC2
desgorjer	desgorje	V;NFIN;LGSPEC2
cumporter	cumporter	V;NFIN;LGSPEC1
determiner	determinon	V;SBJV;PL;1;PRS
fisser	fissaras	V;IND;SG;2;FUT
detlarer	detlarova	V;IPFV;IND;SG;3;PST
dejeujer	dejëujes	V;SBJV;SG;2;PRS;LGSPEC1
publicher	publicha	V;IND;PL;3;PRS;LGSPEC1
manifester	manifestoves	V;IPFV;IND;SG;2;PST
renunzier	renunziova	V;IPFV;IND;SG;3;PST
sustenir	sustenes	V;IND;SG;2;PRS;LGSPEC1
cunzeder	cunzedon	V;IND;PL;1;PRS
entenjer	entenjer	V;NFIN;LGSPEC1
defrenzier	defrenziova	V;IPFV;IND;SG;3;PST
autoriser	autorisassa	V;IPFV;SBJV;PL;3;PST
onjer	onjoves	V;IPFV;IND;SG;2;PST
cianter	ciantes	V;IND;SG;2;PRS;LGSPEC1
mander	mandove	V;IPFV;IND;SG;1;PST
afermer	afermeies	V;IND;SG;2;PRS;LGSPEC2
adurver	adurves	V;SBJV;SG;2;PRS;LGSPEC1
ratificher	ratificharà	V;IND;SG;3;FUT
perde	perdon	V;IND;PL;1;PRS
ratificher	ratifiche	V;SBJV;SG;1;PRS;LGSPEC1
publicher	publicheia	V;IND;SG;3;PRS;LGSPEC2
garantir	garantesc	V;IND;PL;3;PRS;LGSPEC2
educher	educheies	V;SBJV;SG;2;PRS;LGSPEC2
dormir	dormesc	V;NFIN;SG;2;LGSPEC2
dejeujer	dejëujon	V;IND;PL;1;PRS
fé	fajaras	V;IND;SG;2;FUT
curespuender	curespuendeis	V;SBJV;PL;2;PRS
cundaner	cundaneie	V;SBJV;SG;3;PRS;LGSPEC2
seurander	seuranda	V;IND;PL;3;PRS;LGSPEC1
morir	moriron	V;IND;PL;1;FUT
scurter	scurtovais	V;IPFV;IND;PL;2;PST
acurder	acurdareis	V;IND;PL;2;FUT
cunzeder	cunzedessa	V;IPFV;SBJV;SG;3;PST
scriver	scrivova	V;IPFV;IND;PL;3;PST
destiner	destinovais	V;IPFV;IND;PL;2;PST
aplicher	aplicha	V;IND;PL;3;PRS;LGSPEC1
atribuir	atribuion	V;SBJV;PL;1;PRS
istituir	istituiva	V;IPFV;IND;SG;3;PST
deslier	deslieie	V;IND;SG;1;PRS;LGSPEC2
reguler	regulede	V;NFIN;PL;2
dovei	dovesses	V;IPFV;SBJV;SG;2;PST;LGSPEC2
coordener	coordene	V;SBJV;PL;3;PRS
viuler	viules	V;IND;SG;2;PRS;LGSPEC1
cumander	cumandove	V;IPFV;IND;SG;1;PST
adater	adateia	V;NFIN;SG;2;LGSPEC2
curespuender	curespuendovan	V;IPFV;IND;PL;1;PST
ndrezer	ndrezeia	V;IND;SG;3;PRS;LGSPEC2
cuntroler	cuntrolassan	V;IPFV;SBJV;PL;1;PST
stabilir	stabilesce	V;SBJV;SG;3;PRS;LGSPEC2
assegurer	assegureis	V;SBJV;PL;2;PRS
entenjer	entenjes	V;IND;SG;2;PRS
someter	sometarà	V;IND;PL;3;FUT
eserziter	eserziteies	V;IND;SG;2;PRS;LGSPEC2
acurder	acurdé	V;NFIN;LGSPEC2
assenier	assenioves	V;IPFV;IND;SG;2;PST
someter	sometoves	V;IPFV;IND;SG;2;PST
ejaminer	ejaminon	V;IND;PL;1;PRS
comunicher	comunichea	V;IND;SG;3;PRS;LGSPEC3
sustenir	sustene	V;SBJV;SG;1;PRS;LGSPEC1
pruibir	pruibesce	V;IND;SG;1;PRS;LGSPEC2
rejoner	rejonaron	V;IND;PL;1;FUT
damander	damandareis	V;IND;PL;2;FUT
dovei	desseis	V;IND;PL;2;PRS
aplicher	aplicharà	V;IND;PL;3;FUT
autoriser	autorisaré	V;IND;SG;1;FUT
destumer	destumeis	V;IND;PL;2;PRS
storjer	storje	V;SBJV;SG;1;PRS
danejer	danejeies	V;IND;SG;2;PRS;LGSPEC2
educher	eduche	V;SBJV;SG;3;PRS;LGSPEC1
slunger	slungé	V;NFIN;LGSPEC2
adurver	adurvasse	V;IPFV;SBJV;SG;1;PST
vegnì	vegn	V;IND;PL;3;PRS
sotscriver	sotscrivovais	V;IPFV;IND;PL;2;PST
unir	unisse	V;IPFV;SBJV;SG;1;PST
desgorjer	desgorjove	V;IPFV;IND;SG;1;PST
cunferir	cunferivais	V;IPFV;IND;PL;2;PST
azerter	azertede	V;NFIN;PL;2
revucher	revuche	V;SBJV;PL;3;PRS
terjer	terje	V;NFIN;LGSPEC2
azerter	azertova	V;IPFV;IND;SG;3;PST
spidler	spidlassan	V;IPFV;SBJV;PL;1;PST
desgorjer	desgorjes	V;IND;SG;2;PRS
curespuender	curespuendeie	V;SBJV;SG;1;PRS;LGSPEC2
destiner	destiné	V;NFIN;LGSPEC2
eserziter	eserzitarà	V;IND;PL;3;FUT
pronunzier	pronunzieies	V;IND;SG;2;PRS;LGSPEC2
resulter	resulta	V;IND;SG;3;PRS;LGSPEC1
plovei	plovova	V;IPFV;IND;SG;3;PST
mander	mandeia	V;NFIN;SG;2;LGSPEC2
capir	capesce	V;IND;SG;1;PRS;LGSPEC2
pronunzier	pronunzie	V;SBJV;SG;3;PRS;LGSPEC1
scuter	scouta	V;IND;PL;3;PRS;LGSPEC1
mirer	mireia	V;IND;PL;3;PRS;LGSPEC2
rester	resteia	V;IND;SG;3;PRS;LGSPEC2
njinier	njiniove	V;IPFV;IND;SG;1;PST
seurander	seurandeis	V;SBJV;PL;2;PRS
giudicher	giudicharas	V;IND;SG;2;FUT
promulgher	promulgheia	V;IND;SG;3;PRS;LGSPEC2
prejenter	prejenteia	V;IND;SG;3;PRS;LGSPEC2
renunzier	renunzieis	V;IND;PL;2;PRS
detlarer	detlare	V;SBJV;SG;3;PRS;LGSPEC1
ejaminer	ejamina	V;IND;SG;3;PRS;LGSPEC1
destiner	destinarà	V;IND;PL;3;FUT
rater	ratassan	V;IPFV;SBJV;PL;1;PST
sporjer	sporjessa	V;IPFV;SBJV;PL;3;PST
dormir	dormissais	V;IPFV;SBJV;PL;2;PST
coordiner	coordineies	V;SBJV;SG;2;PRS;LGSPEC2
someter	someteie	V;SBJV;SG;3;PRS;LGSPEC2
scurter	scurteie	V;IND;SG;1;PRS;LGSPEC2
giudicher	giudichoves	V;IPFV;IND;SG;2;PST
liter	litassan	V;IPFV;SBJV;PL;1;PST
alesirer	alesirovais	V;IPFV;IND;PL;2;PST
aproer	aproea	V;IND;SG;3;PRS;LGSPEC3
finanzier	finanzies	V;IND;SG;2;PRS;LGSPEC1
secuestrer	secuestreis	V;IND;PL;2;PRS
cumporter	cumportassa	V;IPFV;SBJV;SG;3;PST
atribuir	atribuieis	V;SBJV;PL;2;PRS
spieter	spietede	V;NFIN;PL;2
educher	educhove	V;IPFV;IND;SG;1;PST
resserver	resservassa	V;IPFV;SBJV;PL;3;PST
volei	vuele	V;SBJV;PL;3;PRS
acurder	acurdeie	V;SBJV;SG;3;PRS;LGSPEC2
podei	podeis	V;SBJV;PL;2;PRS
purter	purtovais	V;IPFV;IND;PL;2;PST
romper	rompon	V;IND;PL;1;PRS
dejeujer	dejëuje	V;IND;SG;1;PRS;LGSPEC1
depenjer	depenjer	V;NFIN;LGSPEC1
cunvalider	cunvalidon	V;SBJV;PL;1;PRS
adoter	adoton	V;IND;PL;1;PRS
autoriser	autorisareis	V;IND;PL;2;FUT
detlarer	detlarasse	V;IPFV;SBJV;SG;1;PST
desvier	desvieia	V;IND;SG;3;PRS;LGSPEC2
reguler	regula	V;IND;PL;3;PRS;LGSPEC1
redujer	reduje	V;SBJV;SG;3;PRS
cruzier	cruzies	V;SBJV;SG;2;PRS;LGSPEC1
spartir	spartiva	V;IPFV;IND;PL;3;PST
urganiser	urganison	V;IND;PL;1;PRS
spartir	spartieis	V;IND;PL;2;PRS
schiver	schivaras	V;IND;SG;2;FUT
dejeujer	dejëujé	V;NFIN;LGSPEC2
capir	capes	V;SBJV;SG;2;PRS;LGSPEC1
sponjer	sponjaré	V;IND;SG;1;FUT
cundaner	cundanes	V;SBJV;SG;2;PRS;LGSPEC1
jì	vas	V;IND;SG;2;PRS
liter	litarà	V;IND;SG;3;FUT
promulgher	promulghova	V;IPFV;IND;PL;3;PST
adoter	adoter	V;NFIN;LGSPEC1
purter	purtaré	V;IND;SG;1;FUT
cunferir	cunferesce	V;IND;SG;1;PRS;LGSPEC2
costituir	costituiras	V;IND;SG;2;FUT
comunicher	comunichovais	V;IPFV;IND;PL;2;PST
meter	metoves	V;IPFV;IND;SG;2;PST
populer	popularà	V;IND;SG;3;FUT
coordener	coordenove	V;IPFV;IND;SG;1;PST
damander	damandes	V;IND;SG;2;PRS;LGSPEC1
franjer	franjessan	V;IPFV;SBJV;PL;1;PST
rejoner	rejonaré	V;IND;SG;1;FUT
desgorjer	desgorjes	V;SBJV;SG;2;PRS
apurver	apurve	V;IND;SG;1;PRS;LGSPEC1
reguler	regules	V;SBJV;SG;2;PRS;LGSPEC1
segurer	seguroves	V;IPFV;IND;SG;2;PST
danejer	danejasses	V;IPFV;SBJV;SG;2;PST
storjer	storjon	V;SBJV;PL;1;PRS
prufesser	prufessareis	V;IND;PL;2;FUT
cogner	cogneies	V;IND;SG;2;PRS;LGSPEC2
savei	sas	V;SBJV;SG;2;PRS
comprer	comprassais	V;IPFV;SBJV;PL;2;PST
educher	educharas	V;IND;SG;2;FUT
mirer	mirede	V;NFIN;PL;2
coordener	coordeneia	V;IND;SG;3;PRS;LGSPEC2
dé	daes	V;SBJV;SG;2;PRS
sustenir	sustenieis	V;SBJV;PL;2;PRS
desvier	desviassan	V;IPFV;SBJV;PL;1;PST
educher	educhova	V;IPFV;IND;SG;3;PST
avei	aessa	V;IPFV;SBJV;SG;3;PST;LGSPEC2
secuestrer	secuestraré	V;IND;SG;1;FUT
ndicher	ndicher	V;NFIN;LGSPEC1
adater	adatassa	V;IPFV;SBJV;SG;3;PST
meter	metova	V;IPFV;IND;PL;3;PST
trasferir	trasferivan	V;IPFV;IND;PL;1;PST
assegurer	assegurassan	V;IPFV;SBJV;PL;1;PST
unir	unireis	V;IND;PL;2;FUT
capir	cap	V;IND;SG;3;PRS;LGSPEC1
adoter	adotasse	V;IPFV;SBJV;SG;1;PST
dé	don	V;IND;PL;1;PRS
ejaminer	ejaminovais	V;IPFV;IND;PL;2;PST
danejer	danejovan	V;IPFV;IND;PL;1;PST
cogner	cognova	V;IPFV;IND;PL;3;PST
curespuender	curespuendasse	V;IPFV;SBJV;SG;1;PST
viver	vivon	V;IND;PL;1;PRS
mpartir	mpartes	V;IND;SG;2;PRS;LGSPEC1
capir	capesce	V;SBJV;SG;3;PRS;LGSPEC2
dejeujer	dejëujeia	V;NFIN;SG;2;LGSPEC2
sponjer	sponjareis	V;IND;PL;2;FUT
urganiser	urganisassais	V;IPFV;SBJV;PL;2;PST
autoriser	autoriseia	V;IND;PL;3;PRS;LGSPEC2
promulgher	promulgheis	V;IND;PL;2;PRS
rester	reston	V;SBJV;PL;1;PRS
secuestrer	secuestreia	V;NFIN;SG;2;LGSPEC2
respuender	respuendarà	V;IND;PL;3;FUT
depenjer	depenjovais	V;IPFV;IND;PL;2;PST
stabilir	stabilì	V;NFIN;LGSPEC2
scurter	scurta	V;IND;SG;3;PRS;LGSPEC1
registrer	registreis	V;SBJV;PL;2;PRS
someter	sometove	V;IPFV;IND;SG;1;PST
vedei	vedove	V;IPFV;IND;SG;1;PST
desgorjer	desgorjessan	V;IPFV;SBJV;PL;1;PST
proibir	proib	V;NFIN;SG;2;LGSPEC1
entenjer	entenjon	V;SBJV;PL;1;PRS
pronunzier	pronunzion	V;IND;PL;1;PRS
ndicher	ndicheia	V;NFIN;SG;2;LGSPEC2
terjer	terje	V;SBJV;SG;3;PRS
cundaner	cundanovais	V;IPFV;IND;PL;2;PST
garantir	garantesce	V;SBJV;SG;1;PRS;LGSPEC2
perder	perdessa	V;IPFV;SBJV;SG;3;PST
comprer	compreia	V;NFIN;SG;2;LGSPEC2
cumander	cumandes	V;IND;SG;2;PRS;LGSPEC1
renunzier	renunzieia	V;IND;PL;3;PRS;LGSPEC2
mener	menarà	V;IND;PL;3;FUT
registrer	registres	V;SBJV;SG;2;PRS;LGSPEC1
prejenter	prejente	V;SBJV;PL;3;PRS
registrer	registré	V;NFIN;LGSPEC2
scuter	scutove	V;IPFV;IND;SG;1;PST
parteziper	partezipove	V;IPFV;IND;SG;1;PST
lascer	lascede	V;NFIN;PL;2
comprer	comprareis	V;IND;PL;2;FUT
resulter	resultarà	V;IND;PL;3;FUT
assegurer	assegurovan	V;IPFV;IND;PL;1;PST
scriver	scrives	V;IND;SG;2;PRS
perdujer	perduj	V;NFIN;SG;2
rater	rate	V;SBJV;SG;1;PRS;LGSPEC1
istituir	istitues	V;IND;SG;2;PRS;LGSPEC1
acrediter	acrediteie	V;SBJV;SG;3;PRS;LGSPEC2
vegnì	vegnissa	V;IPFV;SBJV;PL;3;PST
cruzier	cruzie	V;SBJV;SG;3;PRS;LGSPEC1
reverir	reverissais	V;IPFV;SBJV;PL;2;PST
secuestrer	secuestrassan	V;IPFV;SBJV;PL;1;PST
atribuir	atribuirà	V;IND;SG;3;FUT
passer	passe	V;IND;SG;1;PRS;LGSPEC1
rezever	rezevessa	V;IPFV;SBJV;SG;3;PST
ancunter	ancuntaré	V;IND;SG;1;FUT
acrediter	acrediteia	V;IND;SG;3;PRS;LGSPEC2
afermer	afermeis	V;IND;PL;2;PRS
secuestrer	secuestreie	V;SBJV;SG;1;PRS;LGSPEC2
mantenir	mantenireis	V;IND;PL;2;FUT
pronunzier	pronunzia	V;IND;SG;3;PRS;LGSPEC1
revucher	revucharà	V;IND;PL;3;FUT
schiver	schiveie	V;IND;SG;1;PRS;LGSPEC2
someter	someta	V;IND;PL;3;PRS;LGSPEC1
delibrer	delibrarà	V;IND;SG;3;FUT
cogner	cogna	V;IND;SG;3;PRS;LGSPEC1
autoriser	autorises	V;IND;SG;2;PRS;LGSPEC1
cumporter	cumporta	V;IND;SG;3;PRS;LGSPEC1
gaujer	gaujoves	V;IPFV;IND;SG;2;PST
dé	dé	V;NFIN;LGSPEC1
usserver	usserveies	V;IND;SG;2;PRS;LGSPEC2
proibir	proibisses	V;IPFV;SBJV;SG;2;PST
reguler	regulovais	V;IPFV;IND;PL;2;PST
revucher	revuchon	V;IND;PL;1;PRS
spartir	spartirà	V;IND;PL;3;FUT
dejeujer	dejëujeies	V;SBJV;SG;2;PRS;LGSPEC2
aproer	aproaré	V;IND;SG;1;FUT
viver	vivovan	V;IPFV;IND;PL;1;PST
aplicher	aplicheie	V;SBJV;SG;3;PRS;LGSPEC2
aproer	aproova	V;IPFV;IND;PL;3;PST
unir	unide	V;NFIN;PL;2
terjer	terjaron	V;IND;PL;1;FUT
pruibir	pruibiron	V;IND;PL;1;FUT
lascer	lascassan	V;IPFV;SBJV;PL;1;PST
ndrezer	ndrezeia	V;IND;PL;3;PRS;LGSPEC2
delegher	delegheia	V;IND;PL;3;PRS;LGSPEC2
cunferir	cunferes	V;IND;SG;2;PRS;LGSPEC1
publicher	publichoves	V;IPFV;IND;SG;2;PST
limiter	limitassa	V;IPFV;SBJV;PL;3;PST
autoriser	autorisovais	V;IPFV;IND;PL;2;PST
scurter	scurtoves	V;IPFV;IND;SG;2;PST
assegurer	assegurea	V;IND;SG;3;PRS;LGSPEC3
desvier	desviea	V;IND;SG;3;PRS;LGSPEC3
udir	udiva	V;IPFV;IND;SG;3;PST
purter	purta	V;NFIN;SG;2;LGSPEC1
parteziper	partezipon	V;IND;PL;1;PRS
apurver	apurve	V;SBJV;SG;3;PRS;LGSPEC1
udir	udesc	V;IND;PL;3;PRS;LGSPEC2
reprejenter	reprejenteia	V;NFIN;SG;2;LGSPEC2
remander	remanda	V;IND;SG;3;PRS;LGSPEC1
entenjer	entenje	V;SBJV;SG;3;PRS
cruzier	cruzieia	V;IND;PL;3;PRS;LGSPEC2
comunicher	comunichova	V;IPFV;IND;SG;3;PST
eserziter	eserzité	V;NFIN;LGSPEC2
atuer	atuove	V;IPFV;IND;SG;1;PST
storjer	storjer	V;NFIN;LGSPEC1
njinier	njiniassais	V;IPFV;SBJV;PL;2;PST
cumander	cumandeia	V;NFIN;SG;2;LGSPEC2
scurter	scurta	V;IND;PL;3;PRS;LGSPEC1
detlarer	detlare	V;SBJV;PL;3;PRS
savei	savovan	V;IPFV;IND;PL;1;PST
mander	mandeie	V;IND;SG;1;PRS;LGSPEC2
coster	costarà	V;IND;SG;3;FUT
strenjer	strenjova	V;IPFV;IND;SG;3;PST
podei	podaré	V;IND;SG;1;FUT
delibrer	delibrassais	V;IPFV;SBJV;PL;2;PST
costituir	costituieis	V;IND;PL;2;PRS
tradujer	tradujer	V;NFIN;LGSPEC1
acuser	acusasses	V;IPFV;SBJV;SG;2;PST
cumander	cumandaras	V;IND;SG;2;FUT
stabilir	stabiliras	V;IND;SG;2;FUT
resserver	resserva	V;IND;SG;3;PRS;LGSPEC1
autoriser	autoriseia	V;IND;SG;3;PRS;LGSPEC2
ratificher	ratifichareis	V;IND;PL;2;FUT
spartir	spartissais	V;IPFV;SBJV;PL;2;PST
unir	unieis	V;IND;PL;2;PRS
cunzeder	cunzed	V;IND;SG;3;PRS
nfurmer	nfurmova	V;IPFV;IND;PL;3;PST
cumander	cumandova	V;IPFV;IND;SG;3;PST
fisser	fisseie	V;IND;SG;1;PRS;LGSPEC2
mirer	miré	V;NFIN;LGSPEC2
capir	capì	V;NFIN;LGSPEC2
cumander	cumandassais	V;IPFV;SBJV;PL;2;PST
aplicher	aplichovan	V;IPFV;IND;PL;1;PST
seurander	seurandassa	V;IPFV;SBJV;PL;3;PST
produjer	produjareis	V;IND;PL;2;FUT
acrediter	acredite	V;IND;SG;1;PRS;LGSPEC1
trasferir	trasferiva	V;IPFV;IND;SG;3;PST
adoter	adoteies	V;IND;SG;2;PRS;LGSPEC2
sotscriver	sotscrives	V;IND;SG;2;PRS
sotscriver	sotscrivarà	V;IND;PL;3;FUT
reurganiser	reurganisasses	V;IPFV;SBJV;SG;2;PST
scriver	scrivovais	V;IPFV;IND;PL;2;PST
spieter	spietarà	V;IND;SG;3;FUT
rester	restova	V;IPFV;IND;SG;3;PST
spidler	spidlovais	V;IPFV;IND;PL;2;PST
urganiser	urganisaron	V;IND;PL;1;FUT
cianter	ciantassa	V;IPFV;SBJV;PL;3;PST
ndicher	ndicheis	V;IND;PL;2;PRS
spidler	spidleis	V;IND;PL;2;PRS
comunicher	comunicheis	V;SBJV;PL;2;PRS
prufesser	prufesson	V;IND;PL;1;PRS
trasferir	trasferir	V;NFIN;LGSPEC1
someter	sometassais	V;IPFV;SBJV;PL;2;PST
alesirer	alesires	V;IND;SG;2;PRS;LGSPEC1
assenier	assenieia	V;NFIN;SG;2;LGSPEC2
podei	podovan	V;IPFV;IND;PL;1;PST
delibrer	delibre	V;IND;SG;1;PRS;LGSPEC1
finanzier	finanziaré	V;IND;SG;1;FUT
defrenzier	defrenziessa	V;IPFV;SBJV;PL;3;PST
eserziter	eserzite	V;SBJV;SG;1;PRS;LGSPEC1
atuer	atuova	V;IPFV;IND;PL;3;PST
cumander	cumandarà	V;IND;SG;3;FUT
desgorjer	desgorjesses	V;IPFV;SBJV;SG;2;PST
istituir	istituisses	V;IPFV;SBJV;SG;2;PST
autoriser	autorise	V;IND;SG;1;PRS;LGSPEC1
registrer	registre	V;IND;SG;1;PRS;LGSPEC1
partir	partivais	V;IPFV;IND;PL;2;PST
arbitrer	arbitre	V;SBJV;SG;3;PRS;LGSPEC1
coster	costovan	V;IPFV;IND;PL;1;PST
mutiver	mutivasse	V;IPFV;SBJV;SG;1;PST
prufesser	prufesseis	V;SBJV;PL;2;PRS
determiner	determine	V;IND;SG;1;PRS;LGSPEC1
reurganiser	reurganisove	V;IPFV;IND;SG;1;PST
trasferir	trasferieis	V;IND;PL;2;PRS
morir	muere	V;SBJV;SG;3;PRS
arester	areste	V;SBJV;PL;3;PRS
stipuler	stipulon	V;IND;PL;1;PRS
reurganiser	reurganisa	V;IND;PL;3;PRS;LGSPEC1
ndrezer	ndrezarà	V;IND;SG;3;FUT
mutiver	mutiveia	V;IND;SG;3;PRS;LGSPEC2
adater	adatoves	V;IPFV;IND;SG;2;PST
dejeujer	dejëujassa	V;IPFV;SBJV;SG;3;PST
alesirer	alesirareis	V;IND;PL;2;FUT
aproer	aproa	V;IND;PL;3;PRS;LGSPEC1
renunzier	renunzié	V;NFIN;LGSPEC2
proibir	proibesce	V;IND;SG;1;PRS;LGSPEC2
reverir	reveresce	V;IND;SG;1;PRS;LGSPEC2
aproer	aproaras	V;IND;SG;2;FUT
aproer	aproeie	V;SBJV;SG;1;PRS;LGSPEC2
rezever	rezevede	V;NFIN;PL;2
deslier	desliova	V;IPFV;IND;SG;3;PST
educher	educher	V;NFIN;LGSPEC1
storjer	storje	V;NFIN;LGSPEC2
cundaner	cundana	V;NFIN;SG;2;LGSPEC1
coordiner	coordinaras	V;IND;SG;2;FUT
emaner	emaneie	V;IND;SG;1;PRS;LGSPEC2
alesirer	alesireies	V;IND;SG;2;PRS;LGSPEC2
perdujer	perdujoves	V;IPFV;IND;SG;2;PST
acurder	acurdassan	V;IPFV;SBJV;PL;1;PST
ncurajer	ncurajeie	V;SBJV;SG;3;PRS;LGSPEC2
mpartir	mpartesces	V;IND;SG;2;PRS;LGSPEC2
delegher	deleghon	V;SBJV;PL;1;PRS
acrediter	acreditasses	V;IPFV;SBJV;SG;2;PST
coordiner	coordineis	V;SBJV;PL;2;PRS
stipuler	stipules	V;SBJV;SG;2;PRS;LGSPEC1
podei	podessan	V;IPFV;SBJV;PL;1;PST
goder	godeies	V;IND;SG;2;PRS;LGSPEC2
fé	fajeis	V;IND;PL;2;PRS
udir	ud	V;NFIN;SG;2;LGSPEC1
manifester	manifeste	V;SBJV;PL;3;PRS
cumporter	cumporte	V;SBJV;PL;3;PRS
ejaminer	ejaminasses	V;IPFV;SBJV;SG;2;PST
stabilir	stabilives	V;IPFV;IND;SG;2;PST
mirer	miron	V;SBJV;PL;1;PRS
coordiner	coordinon	V;IND;PL;1;PRS
franjer	franjaré	V;IND;SG;1;FUT
registrer	registrea	V;IND;SG;3;PRS;LGSPEC3
remander	remande	V;SBJV;SG;3;PRS;LGSPEC1
dejeujer	dejëujaras	V;IND;SG;2;FUT
sustenir	sustenesc	V;IND;PL;3;PRS;LGSPEC2
nascer	nasceis	V;IND;PL;2;PRS
ratificher	ratificheies	V;IND;SG;2;PRS;LGSPEC2
resulter	resultovan	V;IPFV;IND;PL;1;PST
someter	someton	V;IND;PL;1;PRS
ressolver	ressolveis	V;IND;PL;2;PRS
ratificher	ratifichassan	V;IPFV;SBJV;PL;1;PST
finanzier	finanziasse	V;IPFV;SBJV;SG;1;PST
secuestrer	secuestrova	V;IPFV;IND;PL;3;PST
usserver	usserves	V;SBJV;SG;2;PRS;LGSPEC1
acurder	acurda	V;NFIN;SG;2;LGSPEC1
aproer	aproeie	V;SBJV;SG;3;PRS;LGSPEC2
azerter	azertes	V;IND;SG;2;PRS;LGSPEC1
reurganiser	reurganisa	V;IND;SG;3;PRS;LGSPEC1
remander	remandea	V;IND;SG;3;PRS;LGSPEC3
adoter	adotovais	V;IPFV;IND;PL;2;PST
deslier	deslié	V;NFIN;LGSPEC2
populer	populassan	V;IPFV;SBJV;PL;1;PST
mander	mandon	V;SBJV;PL;1;PRS
muder	muder	V;NFIN;LGSPEC1
liter	liteie	V;SBJV;SG;3;PRS;LGSPEC2
apurver	apurva	V;IND;SG;3;PRS;LGSPEC1
comunicher	comuniche	V;IND;SG;1;PRS;LGSPEC1
morir	morissa	V;IPFV;SBJV;PL;3;PST
destumer	destumeies	V;SBJV;SG;2;PRS;LGSPEC2
remplazer	remplazeia	V;IND;SG;3;PRS;LGSPEC2
onjer	onjessan	V;IPFV;SBJV;PL;1;PST
aussei	aussova	V;IPFV;IND;SG;3;PST
resulter	resulteie	V;IND;SG;1;PRS;LGSPEC2
franjer	franj	V;IND;PL;3;PRS
goder	godeia	V;IND;SG;3;PRS;LGSPEC2
mutiver	mutivareis	V;IND;PL;2;FUT
viver	vivede	V;NFIN;PL;2
mutiver	mutiva	V;NFIN;SG;2;LGSPEC1
sponjer	sponjoves	V;IPFV;IND;SG;2;PST
condujer	condujaron	V;IND;PL;1;FUT
ndicher	ndicharà	V;IND;SG;3;FUT
onjer	onjessais	V;IPFV;SBJV;PL;2;PST
perder	perdon	V;SBJV;PL;1;PRS
assegurer	assegureia	V;IND;SG;3;PRS;LGSPEC2
remander	remande	V;SBJV;PL;3;PRS
educher	eduche	V;IND;SG;1;PRS;LGSPEC1
stipuler	stipuleie	V;SBJV;SG;3;PRS;LGSPEC2
vedei	vedeis	V;SBJV;PL;2;PRS
numiner	numina	V;IND;SG;3;PRS;LGSPEC1
mirer	mirova	V;IPFV;IND;PL;3;PST
aplicher	aplicheies	V;IND;SG;2;PRS;LGSPEC2
cogner	cognassa	V;IPFV;SBJV;SG;3;PST
viver	vives	V;IND;SG;2;PRS
prejenter	prejentassa	V;IPFV;SBJV;SG;3;PST
parteziper	partezipassais	V;IPFV;SBJV;PL;2;PST
numiner	numinasse	V;IPFV;SBJV;SG;1;PST
coordener	coordener	V;NFIN;LGSPEC1
cogner	cogner	V;NFIN;LGSPEC1
arbitrer	arbitra	V;IND;SG;3;PRS;LGSPEC1
deslier	deslia	V;IND;PL;3;PRS;LGSPEC1
schiver	schive	V;SBJV;SG;1;PRS;LGSPEC1
produjer	produjoves	V;IPFV;IND;SG;2;PST
coordiner	coordineies	V;IND;SG;2;PRS;LGSPEC2
condujer	condujoves	V;IPFV;IND;SG;2;PST
redujer	redujova	V;IPFV;IND;PL;3;PST
sporjer	sporjeis	V;IND;PL;2;PRS
perdujer	perdujesses	V;IPFV;SBJV;SG;2;PST
arbitrer	arbitrarà	V;IND;PL;3;FUT
messei	messaré	V;IND;SG;1;FUT
manifester	manifestovan	V;IPFV;IND;PL;1;PST
prejenter	prejentasses	V;IPFV;SBJV;SG;2;PST
tramuder	tramudasses	V;IPFV;SBJV;SG;2;PST
prejenter	prejentassa	V;IPFV;SBJV;PL;3;PST
adater	adaton	V;IND;PL;1;PRS
reurganiser	reurganisasse	V;IPFV;SBJV;SG;1;PST
adurver	adurveie	V;SBJV;SG;3;PRS;LGSPEC2
erjer	erjovan	V;IPFV;IND;PL;1;PST
eserziter	eserziteis	V;IND;PL;2;PRS
tradujer	tradujarà	V;IND;PL;3;FUT
adurver	adurvaré	V;IND;SG;1;FUT
jonjer	jonjoves	V;IPFV;IND;SG;2;PST
ncurajer	ncurajeies	V;IND;SG;2;PRS;LGSPEC2
slunger	slungeis	V;IND;PL;2;PRS
aplicher	aplicheie	V;SBJV;SG;1;PRS;LGSPEC2
ressolver	ressolvassan	V;IPFV;SBJV;PL;1;PST
cianter	ciantea	V;IND;SG;3;PRS;LGSPEC3
njinier	njiniova	V;IPFV;IND;PL;3;PST
ancunter	ancunté	V;NFIN;LGSPEC2
aproer	aproe	V;SBJV;SG;1;PRS;LGSPEC1
autoriser	autoriseia	V;NFIN;SG;2;LGSPEC2
mutiver	mutivede	V;NFIN;PL;2
prejenter	prejentarà	V;IND;SG;3;FUT
usserver	usservede	V;NFIN;PL;2
dejeujer	dejëujove	V;IPFV;IND;SG;1;PST
purter	purtareis	V;IND;PL;2;FUT
ndicher	ndicheie	V;SBJV;SG;3;PRS;LGSPEC2
muder	mudeies	V;IND;SG;2;PRS;LGSPEC2
reprejenter	reprejentarà	V;IND;PL;3;FUT
lascer	lascaron	V;IND;PL;1;FUT
arbitrer	arbitra	V;IND;PL;3;PRS;LGSPEC1
finanzier	finanzia	V;IND;PL;3;PRS;LGSPEC1
udir	udir	V;NFIN;LGSPEC1
cunferir	cunfere	V;SBJV;SG;1;PRS;LGSPEC1
entenjer	entenjesse	V;IPFV;SBJV;SG;1;PST
ncurajer	ncurajea	V;IND;SG;3;PRS;LGSPEC3
prufesser	prufessasse	V;IPFV;SBJV;SG;1;PST
destiner	destineia	V;IND;SG;3;PRS;LGSPEC2
depenjer	depenjede	V;NFIN;PL;2
comunicher	comunicharà	V;IND;PL;3;FUT
comunicher	comuniches	V;SBJV;SG;2;PRS;LGSPEC1
stipuler	stipule	V;SBJV;SG;1;PRS;LGSPEC1
vegnì	vegnissan	V;IPFV;SBJV;PL;1;PST
cunferir	cunferirà	V;IND;PL;3;FUT
emaner	emanaré	V;IND;SG;1;FUT
usserver	usserve	V;IND;SG;1;PRS;LGSPEC1
nfurmer	nfurmeies	V;SBJV;SG;2;PRS;LGSPEC2
destiner	destinoves	V;IPFV;IND;SG;2;PST
afermer	afermassa	V;IPFV;SBJV;PL;3;PST
istruir	istruide	V;NFIN;PL;2
comprer	compre	V;SBJV;PL;3;PRS
defrenzier	defrenzie	V;SBJV;PL;3;PRS
rater	rata	V;IND;PL;3;PRS;LGSPEC1
mpartir	mpartesc	V;IND;SG;3;PRS;LGSPEC2
someter	somete	V;IND;SG;1;PRS;LGSPEC1
vegnì	vegne	V;IND;SG;1;PRS
slunger	slungeia	V;NFIN;SG;2;LGSPEC2
franjer	franjareis	V;IND;PL;2;FUT
cumander	cumandaron	V;IND;PL;1;FUT
cunzeder	cunzedova	V;IPFV;IND;SG;3;PST
njinier	njinié	V;NFIN;LGSPEC2
anuler	anuleie	V;SBJV;SG;1;PRS;LGSPEC2
aussei	aussesse	V;IPFV;SBJV;SG;1;PST
