londa	nnonze	V;SG;1;PST+RCT
buuka	buuka	V;NFIN
ffa	bafa	V;PL;3;PRS
komawo	twakakomawo	V;PROG;PL;1;PST
yaagala	tulyagala	V;PL;1;FUT+RMT
nywegera	tunywegedde	V;PL;1;PST+RCT
wereza	banaaweereza	V;PL;3;FUT+IMMED
linda	alinda	V;3;PRS
lowooza	nalowooza	V;1;PST+RMT
sisinkana	naasisinkana	V;1;FUT+IMMED
kozesa	tulikozesa	V;PL;1;FUT+RMT
lamaga	ndilamaga	V;1;FUT+RMT
salawo	asalawo	V;3;PRS
tambula	watambula	V;2;PST+RMT
zina	tulizina	V;PL;1;FUT+RMT
salawo	munaasalawo	V;PL;2;FUT+IMMED
yaagala	onooyagala	V;2;FUT+IMMED
wuliriza	waakawuliriza	V;PROG;2;PST
yamba	oyamba	V;2;PRS
vuga	ndivuga	V;1;FUT+RMT
yamba	onooyamba	V;2;FUT+IMMED
kozesa	waakakozesa	V;PROG;2;PST
fuluma	afuluma	V;3;PRS
buuka	abuuka	V;3;PRS
elabira	elabira	V;NFIN
yiga	mwayize	V;PL;2;PST+RCT
kwaata	twakwaata	V;PL;1;PST+RMT
yimirira	yayimiridde	V;3;PST+RCT
laga	banaalaga	V;PL;3;FUT+IMMED
yita	tunaayita	V;PL;1;FUT+IMMED
buuka	sinnabuuka	V;INTEN;1;FUT
menya	mulimenya	V;PL;2;FUT+RMT
yimirira	temunnayimirira	V;INTEN;PL;2;FUT
tandika	tukyatandika	V;PROG;PL;1;PRS
yimba	yimba	V;NFIN
yimirira	tonnayimirira	V;INTEN;2;FUT
lya	walya	V;2;PST+RMT
kozesa	mulikozesa	V;PL;2;FUT+RMT
manya	yamanya	V;3;PST+RMT
zannya	nzannya	V;1;PRS
beera	bakyabeera	V;PROG;PL;3;PRS
yimba	twayimbye	V;PL;1;PST+RCT
baawo	mubaawo	V;PL;2;PRS
lowooza	temunnalowooza	V;INTEN;PL;2;FUT
tta	atta	V;3;PRS
wa	baawadde	V;PL;3;PST+RCT
nnyonnyola	wannyonnyodde	V;2;PST+RCT
elabira	alyerabira	V;3;FUT+RMT
dduka	naakadduka	V;PROG;1;PST
nywa	banaanywa	V;PL;3;FUT+IMMED
komawo	waakakomawo	V;PROG;2;PST
nywa	mwanywa	V;PL;2;PST+RMT
yogera	njogera	V;1;PRS
lamaga	mwakalamaga	V;PROG;PL;2;PST
ggulawo	mwaggulawo	V;PL;2;PST+RMT
manya	namanya	V;1;PST+RMT
fuuka	onoofuuka	V;2;FUT+IMMED
gwa	tetunnagwa	V;INTEN;PL;1;FUT
laga	mukyalaga	V;PROG;PL;2;PRS
yiga	nayiga	V;1;PST+RMT
twala	banaatwala	V;PL;3;FUT+IMMED
laba	tunaalaba	V;PL;1;FUT+IMMED
wandiika	wawandiise	V;2;PST+RCT
etaaga	yetaaga	V;3;PRS
ddamu	addamu	V;3;PRS
saanga	alisanga	V;3;FUT+RMT
yimirira	muyimirira	V;PL;2;PRS
kaaba	naakakaaba	V;PROG;1;PST
labika	okyalabika	V;PROG;2;PRS
twala	atwala	V;3;PRS
londa	yaakalonda	V;PROG;3;PST
sisinkana	tebannasisinkana	V;INTEN;PL;3;FUT
laga	baliraga	V;PL;3;FUT+RMT
lekana	sinnaleekaana	V;INTEN;1;FUT
buza	mulibuza	V;PL;2;FUT+RMT
yanjula	nyanjudde	V;SG;1;PST+RCT
wereza	tukyaweereza	V;PROG;PL;1;PRS
wa	wa	V;NFIN
wangula	mwawangula	V;PL;2;PST+RMT
kiriza	munakkiriza	V;PL;2;FUT+IMMED
laga	anaalaga	V;3;FUT+IMMED
lowooza	ndowooza	V;1;PRS
yimirira	tuliyimirira	V;PL;1;FUT+RMT
somesa	mwasomesa	V;PL;2;PST+RMT
nywegera	mwakanywegera	V;PROG;PL;2;PST
kiriza	nakkiriza	V;1;FUT+IMMED
fuluma	tebannafuluma	V;INTEN;PL;3;FUT
kwata	tunaakwata	V;PL;1;FUT+IMMED
saanga	tusanze	V;PL;1;PST+RCT
buza	twabuzizza	V;PL;1;PST+RCT
teka	baateese	V;PL;3;PST+RCT
situka	banaasituka	V;PL;3;FUT+IMMED
yaagala	njagala	V;1;PRS
gamba	agambye	V;SG;3;PST+RCT
lya	twalya	V;PL;1;PST+RMT
mala	banaamala	V;PL;3;FUT+IMMED
labika	twalabika	V;PL;1;PST+RMT
vuga	anaavuga	V;3;FUT+IMMED
zina	nkyazina	V;PROG;1;PRS
buuka	onoobuuka	V;2;FUT+IMMED
nywegera	nywegera	V;NFIN
yimirira	baayimiridde	V;PL;3;PST+RCT
menya	tulimenya	V;PL;1;FUT+RMT
laga	tebannalaga	V;INTEN;PL;3;FUT
kaaba	balikaaba	V;PL;3;FUT+RMT
seka	onooseka	V;2;FUT+IMMED
etaaga	temunnetaaga	V;INTEN;PL;2;FUT
wulira	naakawulira	V;PROG;1;PST
yongera	twongedde	V;PL;1;PST+RCT
yimirira	yimirira	V;NFIN
tuula	twatudde	V;PL;1;PST+RCT
kwaata	baakakwata	V;PROG;PL;3;PST
nywa	tunywa	V;PL;1;PRS
jjukira	najjukira	V;1;FUT+IMMED
zina	tannazina	V;INTEN;3;FUT
dduka	tannadduka	V;INTEN;3;FUT
lekana	lekana	V;NFIN
tegeera	naategeera	V;1;FUT+IMMED
kozesa	naakozesa	V;1;FUT+IMMED
etaaga	twaketaaga	V;PROG;PL;1;PST
ddamu	oliddamu	V;2;FUT+RMT
kwaata	tebannakwata	V;INTEN;PL;3;FUT
kola	sinnakola	V;INTEN;1;FUT
labika nga	nalabise nga	V;1;PST+RCT
ffa	nfa	V;1;PRS
yimirira	baliyimirira	V;PL;3;FUT+RMT
lekana	tebannaleekaana	V;INTEN;PL;3;FUT
wangula	munaawangula	V;PL;2;FUT+IMMED
ggulawo	yaakaggulawo	V;PROG;3;PST
beera	mwabeera	V;PL;2;PST+RMT
seka	wasese	V;2;PST+RCT
ggalawo	naggaddewo	V;1;PST+RCT
ebaka	baakebaka	V;PROG;PL;3;PST
buuza	nabuuza	V;1;PST+RMT
sobola	nsobodde	V;SG;1;PST+RCT
baawo	nabaddewo	V;1;PST+RCT
buuka	balibuuka	V;PL;3;FUT+RMT
vuga	mwavuze	V;PL;2;PST+RCT
laga	naakalaga	V;PROG;1;PST
sisinkana	mukyasisinkana	V;PROG;PL;2;PRS
baawo	banaabaawo	V;PL;3;FUT+IMMED
teka	tuteese	V;PL;1;PST+RCT
saanga	asanga	V;3;PRS
tunda	tutunze	V;PL;1;PST+RCT
sisinkana	mwasisinkana	V;PL;2;PST+RMT
yita	ndiyita	V;1;FUT+RMT
yingira	okyayingira	V;PROG;2;PRS
ddamu	temunnaddamu	V;INTEN;PL;2;FUT
wangula	naakawangula	V;PROG;1;PST
genda	tugenda	V;PL;1;PRS
situka	munaasituka	V;PL;2;FUT+IMMED
salawo	ndisalawo	V;1;FUT+RMT
wandiika	waakawandiika	V;PROG;2;PST
londa	munaalonda	V;PL;2;FUT+IMMED
kola	tebannakola	V;INTEN;PL;3;FUT
somesa	twasomesezza	V;PL;1;PST+RCT
somesa	nkyasomesa	V;PROG;1;PRS
kiriza	mukkiriza	V;PL;2;PRS
gwa	tukyagwa	V;PROG;PL;1;PRS
buza	twakabuza	V;PROG;PL;1;PST
seka	tuliseka	V;PL;1;FUT+RMT
wereza	tetunnaweereza	V;INTEN;PL;1;FUT
yaagala	balyagala	V;PL;3;FUT+RMT
jjukira	mwajjukidde	V;PL;2;PST+RCT
elabira	neerabidde	V;SG;1;PST+RCT
somesa	musomesezza	V;PL;2;PST+RCT
situka	baakasituka	V;PROG;PL;3;PST
kaaba	tebannakaaba	V;INTEN;PL;3;FUT
ggulawo	yaggulawo	V;3;PST+RMT
zina	balizina	V;PL;3;FUT+RMT
ba	twabadde	V;PL;1;PST+RCT
tandika	tutandika	V;PL;1;PRS
zannya	bakyazannya	V;PROG;PL;3;PRS
buuza	ndibuuza	V;1;FUT+RMT
vuga	yavuze	V;3;PST+RCT
soma	tusomye	V;PL;1;PST+RCT
seka	temunnaseka	V;INTEN;PL;2;FUT
fuluma	temunnafuluma	V;INTEN;PL;2;FUT
wulira	tonnawulira	V;INTEN;2;FUT
lya	waakalya	V;PROG;2;PST
yingira	waakayingira	V;PROG;2;PST
menya	sinnamenya	V;INTEN;1;FUT
sisinkana	mulisisinkana	V;PL;2;FUT+RMT
jja	yajja	V;3;PST+RMT
yingira	oliyingira	V;2;FUT+RMT
yamba	mukyayamba	V;PROG;PL;2;PRS
ba	baliba	V;PL;3;FUT+RMT
wandiika	sinnawandiika	V;INTEN;1;FUT
labika	tulabise	V;PL;1;PST+RCT
gula	aligula	V;3;FUT+RMT
tambula	twatambula	V;PL;1;PST+RMT
tta	sinnatta	V;INTEN;1;FUT
labika	mulirabika	V;PL;2;FUT+RMT
nywegera	olinywegera	V;2;FUT+RMT
londa	tulironda	V;PL;1;FUT+RMT
wangula	bawangula	V;PL;3;PRS
yamba	waakayamba	V;PROG;2;PST
ggalawo	banaaggalawo	V;PL;3;FUT+IMMED
tuula	tunaatuula	V;PL;1;FUT+IMMED
mala	naakamala	V;PROG;1;PST
labika nga	alabika nga	V;3;PRS
yaagala	twagala	V;PL;1;PRS
yingira	banaayingira	V;PL;3;FUT+IMMED
ggalawo	twaggaddewo	V;PL;1;PST+RCT
yanjula	mwakayanjula	V;PROG;PL;2;PST
londa	naalonda	V;1;FUT+IMMED
ggalawo	tunaaggalawo	V;PL;1;FUT+IMMED
buza	naakabuza	V;PROG;1;PST
zannya	tetunnazannya	V;INTEN;PL;1;FUT
wuliriza	tuwulirizza	V;PL;1;PST+RCT
mwennya	tonnamwennya	V;INTEN;2;FUT
zannya	tannazannya	V;INTEN;3;FUT
kiriza	akyakkiriza	V;PROG;3;PRS
kiriza	mwakakkiriza	V;PROG;PL;2;PST
nywa	munywa	V;PL;2;PRS
beera	tonnabeera	V;INTEN;2;FUT
lowooza	sinnalowooza	V;INTEN;1;FUT
mala	mulimala	V;PL;2;FUT+RMT
labika	mwakalabika	V;PROG;PL;2;PST
manya	otegedde	V;SG;2;PST+RCT
menya	naamenya	V;1;FUT+IMMED
yiga	bakyayiga	V;PROG;PL;3;PRS
kola	baakola	V;PL;3;PST+RMT
buuka	mwabuuse	V;PL;2;PST+RCT
yogera	banaayogera	V;PL;3;FUT+IMMED
dduka	baadduka	V;PL;3;PST+RMT
sisinkana	akyasisinkana	V;PROG;3;PRS
sisinkana	baakasisinkana	V;PROG;PL;3;PST
ebaka	beebaka	V;PL;3;PST+RMT
ffa	yafa	V;3;PST+RMT
komawo	tukyakomawo	V;PROG;PL;1;PRS
yanjula	mwayanjudde	V;PL;2;PST+RCT
laga	tulaga	V;PL;1;PRS
labika nga	tulabika nga	V;PL;1;PRS
jjukira	anajjukira	V;3;FUT+IMMED
wuliriza	anaawuliriza	V;3;FUT+IMMED
ddamu	wazzeemu	V;2;PST+RCT
lya	mulya	V;PL;2;PRS
lwaana	tulilwana	V;PL;1;FUT+RMT
wulira	yawulidde	V;3;PST+RCT
nywa	tulinywa	V;PL;1;FUT+RMT
linda	mwakalinda	V;PROG;PL;2;PST
nnyonnyola	tunnyonnyodde	V;PL;1;PST+RCT
fuluma	wafuluma	V;2;PST+RMT
menya	tebannamenya	V;INTEN;PL;3;FUT
wereza	tunaaweereza	V;PL;1;FUT+IMMED
ddamu	tukyaddamu	V;PROG;PL;1;PRS
gwa	twagwa	V;PL;1;PST+RMT
fuluma	bafulumye	V;PL;3;PST+RCT
wulira	naawulira	V;1;FUT+IMMED
tuula	ntuula	V;1;PRS
sobola	tusobola	V;PL;1;PRS
buuka	okyabuuka	V;PROG;2;PRS
buuka	yabuuka	V;3;PST+RMT
laba	mulaba	V;PL;2;PRS
etaaga	weetaaze	V;2;PST+RCT
tandika	otandise	V;SG;2;PST+RCT
saanga	tebannasanga	V;INTEN;PL;3;FUT
sigala	basigala	V;PL;3;PRS
kiriza	banakkiriza	V;PL;3;FUT+IMMED
seka	yaakaseka	V;PROG;3;PST
ggulawo	wagguddewo	V;2;PST+RCT
kaaba	tannakaaba	V;INTEN;3;FUT
zina	tunaazina	V;PL;1;FUT+IMMED
kiriza	sinnakkiriza	V;INTEN;1;FUT
yimba	tuyimbye	V;PL;1;PST+RCT
somesa	akyasomesa	V;PROG;3;PRS
tambula	mukyatambula	V;PROG;PL;2;PRS
nnyonnyola	tetunnannyonnyola	V;INTEN;PL;1;FUT
nnyonnyola	sinnannyonnyola	V;INTEN;1;FUT
soma	tetunnasoma	V;INTEN;PL;1;FUT
kendeza	okendeezezza	V;SG;2;PST+RCT
yiga	baayiga	V;PL;3;PST+RMT
buuka	mulibuuka	V;PL;2;FUT+RMT
dduka	yadduka	V;3;PST+RMT
buuka	mbuuka	V;1;PRS
wangula	naawangula	V;1;FUT+IMMED
situka	yasituse	V;3;PST+RCT
yimirira	baakayimirira	V;PROG;PL;3;PST
wulira	tuwulidde	V;PL;1;PST+RCT
buuka	twakabuuka	V;PROG;PL;1;PST
twala	twatwala	V;PL;1;PST+RMT
somesa	yaakasomesa	V;PROG;3;PST
soma	naakasoma	V;PROG;1;PST
mwennya	yaakamwennya	V;PROG;3;PST
wereza	waakaweereza	V;PROG;2;PST
buza	abuza	V;3;PRS
ba ne	naakaba ne	V;PROG;1;PST
linda	mwalinze	V;PL;2;PST+RCT
yita	aliyita	V;3;FUT+RMT
tambula	baatambula	V;PL;3;PST+RMT
buuza	wabuuza	V;2;PST+RMT
kola	olikola	V;2;FUT+RMT
beera	tetunnabeera	V;INTEN;PL;1;FUT
galamira	tugalamira	V;PL;1;PRS
yanjula	okyayanjula	V;PROG;2;PRS
kozesa	yakozeseza	V;3;PST+RCT
ffa	tunaafa	V;PL;1;FUT+IMMED
sobola	yasobodde	V;3;PST+RCT
buza	baakabuza	V;PROG;PL;3;PST
ba ne	ba ne	V;NFIN
ggulawo	agguddewo	V;SG;3;PST+RCT
yogera	mwayogedde	V;PL;2;PST+RCT
ebaka	bebaka	V;PL;3;PRS
kola	akola	V;3;PRS
lekana	bakyaleekaana	V;PROG;PL;3;PRS
gula	tugula	V;PL;1;PRS
zina	tuzinye	V;PL;1;PST+RCT
twala	mutwala	V;PL;2;PRS
yimba	tuliyimba	V;PL;1;FUT+RMT
tta	twase	V;PL;1;PST+RCT
yogera	tonnayogera	V;INTEN;2;FUT
komawo	mwakakomawo	V;PROG;PL;2;PST
yanjula	tetunnayanjula	V;INTEN;PL;1;FUT
kendeza	tunaakendeeza	V;PL;1;FUT+IMMED
lamaga	twakalamaga	V;PROG;PL;1;PST
gwa	anaagwa	V;3;FUT+IMMED
teka	twateeka	V;PL;1;PST+RMT
sisinkana	sinnasisinkana	V;INTEN;1;FUT
ebaka	mweebase	V;PL;2;PST+RCT
baawo	obaddewo	V;SG;2;PST+RCT
sigala	baakasigala	V;PROG;PL;3;PST
kiriza	yakkirizza	V;3;PST+RCT
tuula	watuula	V;2;PST+RMT
gwa	bagudde	V;PL;3;PST+RCT
galamira	waakagalamira	V;PROG;2;PST
sisinkana	nsisinkanye	V;SG;1;PST+RCT
sobola	sinnasobola	V;INTEN;1;FUT
tta	natta	V;1;FUT+IMMED
lamaga	walamaze	V;2;PST+RCT
buza	mbuza	V;1;PRS
ssa	yassa	V;3;PST+RMT
wuliriza	nawuliriza	V;1;PST+RMT
salawo	tannasalawo	V;INTEN;3;FUT
ddamu	twaddamu	V;PL;1;PST+RMT
kwaata	bakutte	V;PL;3;PST+RCT
yamba	bayamba	V;PL;3;PRS
laba	walaba	V;2;PST+RMT
wereza	temunnaweereza	V;INTEN;PL;2;FUT
buuza	bakyabuuza	V;PROG;PL;3;PRS
wulira	aliwulira	V;3;FUT+RMT
yingira	wayingira	V;2;PST+RMT
tandika	atandika	V;3;PRS
lekana	aleekaanye	V;SG;3;PST+RCT
seka	okyaseka	V;PROG;2;PRS
galamira	nkyagalamira	V;PROG;1;PRS
etaaga	ndyetaaga	V;1;FUT+RMT
menya	mwakamenya	V;PROG;PL;2;PST
soma	tannasoma	V;INTEN;3;FUT
baawo	yabaawo	V;3;PST+RMT
wuliriza	muwuliriza	V;PL;2;PRS
situka	alisituka	V;3;FUT+RMT
jjukira	nkyajjukira	V;PROG;1;PRS
sisinkana	tannasisinkana	V;INTEN;3;FUT
sisinkana	twasisinkanye	V;PL;1;PST+RCT
yaagala	ayagala	V;3;PRS
saanga	tusanga	V;PL;1;PRS
buuza	yabuuzizza	V;3;PST+RCT
fumba	wafumba	V;2;PST+RMT
yimirira	tetunnayimirira	V;INTEN;PL;1;FUT
gula	munaagula	V;PL;2;FUT+IMMED
komawo	anaakomawo	V;3;FUT+IMMED
ebaka	akyebaka	V;PROG;3;PRS
soma	basoma	V;PL;3;PRS
kwaata	okwata	V;2;PRS
wereza	oweereza	V;SG;2;PST+RCT
kendeza	nkendeeza	V;1;PRS
galamira	ndigalamira	V;1;FUT+RMT
ggulawo	naggulawo	V;1;PST+RMT
tta	tonnatta	V;INTEN;2;FUT
kwata	sinnakwata	V;INTEN;1;FUT
teka	muteese	V;PL;2;PST+RCT
ba	oli	V;2;PRS
wereza	onooweereza	V;2;FUT+IMMED
gwa	muligwa	V;PL;2;FUT+RMT
wandiika	baakawandiika	V;PROG;PL;3;PST
situka	yasituka	V;3;PST+RMT
manya	naakamanya	V;PROG;1;PST
ssa	tannassa	V;INTEN;3;FUT
londa	waakalonda	V;PROG;2;PST
tandika	tunaatandika	V;PL;1;FUT+IMMED
fuuka	afuuka	V;3;PRS
manya	omanyi	V;2;PRS
fumba	ofumba	V;2;PRS
linda	yalinze	V;3;PST+RCT
ggalawo	baakaggalawo	V;PROG;PL;3;PST
kola	nkoze	V;SG;1;PST+RCT
beera	mbadde	V;SG;1;PST+RCT
ba ne	babadde ne	V;PL;3;PST+RCT
gamba	ŋamba	V;1;PRS
fuluma	tufulumye	V;PL;1;PST+RCT
ssa	temunnassa	V;INTEN;PL;2;FUT
galamira	tebannagalamira	V;INTEN;PL;3;FUT
genda	mwakagenda	V;PROG;PL;2;PST
yongera	naakayongera	V;PROG;1;PST
jja	tebannajja	V;INTEN;PL;3;FUT
yaagala	yaagala	V;NFIN
buza	yabuza	V;3;PST+RMT
buuza	mulibuuza	V;PL;2;FUT+RMT
buuza	mubuuzizza	V;PL;2;PST+RCT
vuga	okyavuga	V;PROG;2;PRS
fuuka	alifuuka	V;3;FUT+RMT
kwata	yaakakwata	V;PROG;3;PST
salawo	mwasazeewo	V;PL;2;PST+RCT
kwata	tonnakwata	V;INTEN;2;FUT
londa	anaalonda	V;3;FUT+IMMED
wereza	aweereza	V;SG;3;PST+RCT
fuluma	sinnafuluma	V;INTEN;1;FUT
zina	banaazina	V;PL;3;FUT+IMMED
yamba	bayambye	V;PL;3;PST+RCT
lamaga	naakalamaga	V;PROG;1;PST
buza	banaabuza	V;PL;3;FUT+IMMED
jjukira	waakajjukira	V;PROG;2;PST
funa	mufuna	V;PL;2;PRS
jjukira	najjukira	V;1;PST+RMT
ebaka	waakebaka	V;PROG;2;PST
yaagala	twayagadde	V;PL;1;PST+RCT
tambula	batambudde	V;PL;3;PST+RCT
teka	sinnateeka	V;INTEN;1;FUT
mwennya	tunaamwennya	V;PL;1;FUT+IMMED
ba	tetunnaba	V;INTEN;PL;1;FUT
situka	tusituka	V;PL;1;PRS
nnyonnyola	balinnyonnyola	V;PL;3;FUT+RMT
lamaga	namaze	V;SG;1;PST+RCT
fuluma	tukyafuluma	V;PROG;PL;1;PRS
tuula	ntudde	V;SG;1;PST+RCT
kaaba	akaaba	V;3;PRS
tegeera	temunnategeera	V;INTEN;PL;2;FUT
ba ne	walina	V;2;PST+RMT
kwaata	tunaakwata	V;PL;1;FUT+IMMED
tambula	natambula	V;1;PST+RMT
sisinkana	tusisinkana	V;PL;1;PRS
mala	amaze	V;SG;3;PST+RCT
sisinkana	tukyasisinkana	V;PROG;PL;1;PRS
wulira	muwulira	V;PL;2;PRS
gula	agula	V;3;PRS
mala	bamala	V;PL;3;PRS
yiga	yayiga	V;3;PST+RMT
lya	nalya	V;1;PST+RMT
wulira	mwawulidde	V;PL;2;PST+RCT
sobola	twasobola	V;PL;1;PST+RMT
jjukira	alijjukira	V;3;FUT+RMT
yaagala	njagadde	V;SG;1;PST+RCT
linda	olinda	V;2;PRS
londa	tebannalonda	V;INTEN;PL;3;FUT
buuka	tubuuse	V;PL;1;PST+RCT
yimirira	tannayimirira	V;INTEN;3;FUT
tunda	yatunze	V;3;PST+RCT
fumba	ndifumba	V;1;FUT+RMT
mwennya	mwennya	V;NFIN
buuka	bakyabuuka	V;PROG;PL;3;PRS
baawo	mbaddewo	V;SG;1;PST+RCT
mala	mala	V;1;PRS
mwennya	bamwenyezza	V;PL;3;PST+RCT
kwata	waakakwata	V;PROG;2;PST
tambula	atambudde	V;SG;3;PST+RCT
linda	akyalinda	V;PROG;3;PRS
jjukira	bakyajjukira	V;PROG;PL;3;PRS
kwaata	akutte	V;SG;3;PST+RCT
nywa	anaanywa	V;3;FUT+IMMED
wuliriza	yawuliriza	V;3;PST+RMT
beera	balibeera	V;PL;3;FUT+RMT
twala	otwala	V;2;PRS
laba	baalabye	V;PL;3;PST+RCT
yimirira	akyayimirira	V;PROG;3;PRS
nywegera	bakyanywegera	V;PROG;PL;3;PRS
tunda	nkyatunda	V;PROG;1;PRS
lamaga	balamaga	V;PL;3;PRS
genda	nkyagenda	V;PROG;1;PRS
elabira	naakeerabira	V;PROG;1;PST
baawo	baakabaawo	V;PROG;PL;3;PST
buza	temunnabuza	V;INTEN;PL;2;FUT
saanga	mulisanga	V;PL;2;FUT+RMT
yingira	anaayingira	V;3;FUT+IMMED
buuza	tubuuzizza	V;PL;1;PST+RCT
labika	nalabise	V;1;PST+RCT
gula	nguze	V;SG;1;PST+RCT
ba	mwali	V;PL;2;PST+RMT
kiriza	baakakkiriza	V;PROG;PL;3;PST
mala	tannamala	V;INTEN;3;FUT
ba ne	tulina	V;PL;1;PRS
yimba	tonnayimba	V;INTEN;2;FUT
menya	okyamenya	V;PROG;2;PRS
kendeza	akendeezezza	V;SG;3;PST+RCT
tandika	mutandika	V;PL;2;PRS
tta	waakatta	V;PROG;2;PST
londa	mwalonze	V;PL;2;PST+RCT
gula	ngula	V;1;PRS
fuuka	mukyafuuka	V;PROG;PL;2;PRS
yimba	wayimba	V;2;PST+RMT
gwa	naakagwa	V;PROG;1;PST
gwa	munaagwa	V;PL;2;FUT+IMMED
nywa	yanywedde	V;3;PST+RCT
lekana	tonnaleekaana	V;INTEN;2;FUT
situka	yaakasituka	V;PROG;3;PST
yamba	ayambye	V;SG;3;PST+RCT
fuuka	naakafuuka	V;PROG;1;PST
yiga	tuyiga	V;PL;1;PRS
fumba	tannafumba	V;INTEN;3;FUT
tegeera	ategeera	V;3;PRS
kaaba	tunaakaaba	V;PL;1;FUT+IMMED
twala	temunnatwala	V;INTEN;PL;2;FUT
wa	tebannawa	V;INTEN;PL;3;FUT
tandika	temunnatandika	V;INTEN;PL;2;FUT
menya	mwamenye	V;PL;2;PST+RCT
yogera	onooyogera	V;2;FUT+IMMED
buza	mukyabuza	V;PROG;PL;2;PRS
lamaga	waakalamaga	V;PROG;2;PST
ddamu	yaddamu	V;3;PST+RMT
jjukira	yajjukira	V;3;PST+RMT
tta	ose	V;SG;2;PST+RCT
londa	twakalonda	V;PROG;PL;1;PST
somesa	onoosomesa	V;2;FUT+IMMED
manya	tumanyi	V;PL;1;PRS
elabira	oneerabira	V;2;FUT+IMMED
situka	osituse	V;SG;2;PST+RCT
ggulawo	twagguddewo	V;PL;1;PST+RCT
kendeza	wakendeezezza	V;2;PST+RCT
tuula	otudde	V;SG;2;PST+RCT
nywegera	tetunnanywegera	V;INTEN;PL;1;FUT
fumba	mukyafumba	V;PROG;PL;2;PRS
etaaga	betaaze	V;PL;3;PST+RCT
lowooza	akyalowooza	V;PROG;3;PRS
seka	mwakaseka	V;PROG;PL;2;PST
labika	yalabika	V;3;PST+RMT
etaaga	mukyetaaga	V;PROG;PL;2;PRS
kaaba	bakyakaaba	V;PROG;PL;3;PRS
lwaana	tonnalwana	V;INTEN;2;FUT
yiga	anaayiga	V;3;FUT+IMMED
laga	naalaga	V;1;FUT+IMMED
wandiika	akyawandiika	V;PROG;3;PRS
sobola	nnasobodde	V;1;PST+RCT
somesa	munaasomesa	V;PL;2;FUT+IMMED
londa	onoolonda	V;2;FUT+IMMED
jjukira	bajjukira	V;PL;3;PRS
tambula	tunaatambula	V;PL;1;FUT+IMMED
kaaba	yakaaba	V;3;PST+RMT
jja	bakyajja	V;PROG;PL;3;PRS
sigala	tonnasigala	V;INTEN;2;FUT
vuga	nkyavuga	V;PROG;1;PRS
lowooza	tunaalowooza	V;PL;1;FUT+IMMED
menya	wamenye	V;2;PST+RCT
buuza	alibuuza	V;3;FUT+RMT
ssa	assa	V;3;PRS
elabira	baneerabira	V;PL;3;FUT+IMMED
lya	mulidde	V;PL;2;PST+RCT
buza	wabuzizza	V;2;PST+RCT
wuliriza	wawulirizza	V;2;PST+RCT
labika nga	walabika nga	V;2;PST+RMT
zina	yazinye	V;3;PST+RCT
labika nga	balabise nga	V;PL;3;PST+RCT
ssa	nkyassa	V;PROG;1;PRS
ssa	mussa	V;PL;2;PRS
lwaana	nnwana	V;1;PRS
kendeza	ndikendeeza	V;1;FUT+RMT
kwaata	tonnakwata	V;INTEN;2;FUT
linda	alinze	V;SG;3;PST+RCT
wereza	waweereza	V;2;PST+RMT
wa	aliwa	V;3;FUT+RMT
fumba	baakafumba	V;PROG;PL;3;PST
yanjula	anaayanjula	V;3;FUT+IMMED
buuka	banaabuuka	V;PL;3;FUT+IMMED
genda	yagenze	V;3;PST+RCT
yiga	naayiga	V;1;FUT+IMMED
ddamu	sinnaddamu	V;INTEN;1;FUT
vuga	baakavuga	V;PROG;PL;3;PST
soma	osomye	V;SG;2;PST+RCT
laga	nalaze	V;1;PST+RCT
funa	tunaafuna	V;PL;1;FUT+IMMED
ggulawo	sinnaggulawo	V;INTEN;1;FUT
wandiika	awandiise	V;SG;3;PST+RCT
buza	ndibuza	V;1;FUT+RMT
gula	twakagula	V;PROG;PL;1;PST
yiga	yaakayiga	V;PROG;3;PST
menya	mumenya	V;PL;2;PRS
yongera	nyongedde	V;SG;1;PST+RCT
wulira	baawulira	V;PL;3;PST+RMT
beera	onoobeera	V;2;FUT+IMMED
yanjula	tannayanjula	V;INTEN;3;FUT
labika nga	nalabika nga	V;1;PST+RMT
teka	naateeka	V;1;FUT+IMMED
yogera	twogedde	V;PL;1;PST+RCT
situka	musituka	V;PL;2;PRS
sigala	tukyasigala	V;PROG;PL;1;PRS
funa	waakafuna	V;PROG;2;PST
kola	anaakola	V;3;FUT+IMMED
etaaga	netaaze	V;SG;1;PST+RCT
tuula	tebannatuula	V;INTEN;PL;3;FUT
buuka	alibuuka	V;3;FUT+RMT
yamba	yamba	V;NFIN
kiriza	nakkiriza	V;1;PST+RMT
lekana	oleekaanye	V;SG;2;PST+RCT
yanjula	ndiyanjula	V;1;FUT+RMT
twala	yatwala	V;3;PST+RMT
gamba	banaagamba	V;PL;3;FUT+IMMED
ffa	baakafa	V;PROG;PL;3;PST
buuza	tonnabuuza	V;INTEN;2;FUT
mala	balimala	V;PL;3;FUT+RMT
wuliriza	muliwuliriza	V;PL;2;FUT+RMT
twala	mwatutte	V;PL;2;PST+RCT
zannya	balizannya	V;PL;3;FUT+RMT
lowooza	tetunnalowooza	V;INTEN;PL;1;FUT
buuza	onoobuuza	V;2;FUT+IMMED
lowooza	baalowooza	V;PL;3;PST+RMT
linda	tulinda	V;PL;1;PRS
manya	mutegedde	V;PL;2;PST+RCT
soma	mulisoma	V;PL;2;FUT+RMT
londa	banaalonda	V;PL;3;FUT+IMMED
tegeera	olitegeera	V;2;FUT+RMT
wereza	baakaweereza	V;PROG;PL;3;PST
yingira	baliyingira	V;PL;3;FUT+RMT
linda	baakalinda	V;PROG;PL;3;PST
kwaata	munaakwata	V;PL;2;FUT+IMMED
gwa	ogwa	V;2;PRS
laga	sinnalaga	V;INTEN;1;FUT
situka	twasituse	V;PL;1;PST+RCT
lwaana	yaakalwana	V;PROG;3;PST
labika nga	balabika nga	V;PL;3;PRS
kendeza	munaakendeeza	V;PL;2;FUT+IMMED
tta	natta	V;1;PST+RMT
soma	okyasoma	V;PROG;2;PRS
galamira	ogalamira	V;2;PRS
wuliriza	twawuliriza	V;PL;1;PST+RMT
yamba	okyayamba	V;PROG;2;PRS
elabira	twaakeerabira	V;PROG;PL;1;PST
labika	ndabise	V;SG;1;PST+RCT
fuluma	mwafuluma	V;PL;2;PST+RMT
buuza	baabuuza	V;PL;3;PST+RMT
kiriza	tulikkiriza	V;PL;1;FUT+RMT
tunda	sinnatunda	V;INTEN;1;FUT
lwaana	mwalwana	V;PL;2;PST+RMT
mwennya	bakyamwennya	V;PROG;PL;3;PRS
tandika	twaakatandika	V;PROG;PL;1;PST
gwa	tugwa	V;PL;1;PRS
soma	bakyasoma	V;PROG;PL;3;PRS
lamaga	tulamaga	V;PL;1;PRS
elabira	tebanneerabira	V;INTEN;PL;3;FUT
wulira	baliwulira	V;PL;3;FUT+RMT
buza	babuzizza	V;PL;3;PST+RCT
kwaata	ndikwata	V;1;FUT+RMT
buuza	anaabuuza	V;3;FUT+IMMED
londa	alironda	V;3;FUT+RMT
jja	temunnajja	V;INTEN;PL;2;FUT
lekana	baleekaanye	V;PL;3;PST+RCT
labika nga	anaalabika nga	V;3;FUT+IMMED
ba ne	twabadde ne	V;PL;1;PST+RCT
soma	banaasoma	V;PL;3;FUT+IMMED
fumba	munaafumba	V;PL;2;FUT+IMMED
saanga	balisanga	V;PL;3;FUT+RMT
lamaga	twalamaga	V;PL;1;PST+RMT
ddamu	ndiddamu	V;1;FUT+RMT
fuluma	naakafuluma	V;PROG;1;PST
galamira	bakyagalamira	V;PROG;PL;3;PRS
tuula	twakatuula	V;PROG;PL;1;PST
saanga	baakasanga	V;PROG;PL;3;PST
genda	tugenze	V;PL;1;PST+RCT
zannya	tulizannya	V;PL;1;FUT+RMT
lya	balya	V;PL;3;PRS
ba	baabadde	V;PL;3;PST+RCT
elabira	aneerabira	V;3;FUT+IMMED
lwaana	mukyalwana	V;PROG;PL;2;PRS
ba ne	oliba ne	V;2;FUT+RMT
komawo	okomyevo	V;SG;2;PST+RCT
linda	yalinda	V;3;PST+RMT
ddamu	waddamu	V;2;PST+RMT
linda	walinda	V;2;PST+RMT
sigala	sigala	V;NFIN
situka	musituse	V;PL;2;PST+RCT
tambula	baatambudde	V;PL;3;PST+RCT
buza	baabuza	V;PL;3;PST+RMT
vuga	ovuga	V;2;PRS
kaaba	okaabye	V;SG;2;PST+RCT
kiriza	mwakkiriza	V;PL;2;PST+RMT
lwaana	nkyalwana	V;PROG;1;PRS
gula	tannagula	V;INTEN;3;FUT
yingira	nyingira	V;1;PRS
lya	alirya	V;3;FUT+RMT
yimirira	mwakayimirira	V;PROG;PL;2;PST
fuuka	nnafuuse	V;1;PST+RCT
wereza	aweereza	V;3;PRS
linda	twalinze	V;PL;1;PST+RCT
yamba	wayamba	V;2;PST+RMT
nywegera	onywegedde	V;SG;2;PST+RCT
lekana	oleekaana	V;2;PRS
tuula	tetunnatuula	V;INTEN;PL;1;FUT
yiga	naakayiga	V;PROG;1;PST
soma	tulisoma	V;PL;1;FUT+RMT
baawo	baawo	V;NFIN
kendeza	naakakendeeza	V;PROG;1;PST
wa	waakawa	V;PROG;2;PST
buza	akyabuza	V;PROG;3;PRS
wandiika	mpandiika	V;1;PRS
lya	yalidde	V;3;PST+RCT
yingira	wayingidde	V;2;PST+RCT
jjukira	jjukira	V;NFIN
vuga	akyavuga	V;PROG;3;PRS
komawo	akomawo	V;3;PRS
wangula	anaawangula	V;3;FUT+IMMED
tegeera	nkyategeera	V;PROG;1;PRS
sigala	temunnasigala	V;INTEN;PL;2;FUT
baawo	mubaddewo	V;PL;2;PST+RCT
buuza	akyabuuza	V;PROG;3;PRS
gula	oguze	V;SG;2;PST+RCT
laga	balaze	V;PL;3;PST+RCT
soma	tunaasoma	V;PL;1;FUT+IMMED
nywegera	onoonywegera	V;2;FUT+IMMED
menya	yaakamenya	V;PROG;3;PST
jja	sinnajja	V;INTEN;1;FUT
buuka	obuuse	V;SG;2;PST+RCT
ba ne	yaakaba ne	V;PROG;3;PST
yiga	yiga	V;NFIN
ebaka	weebaka	V;2;PST+RMT
salawo	twasazeewo	V;PL;1;PST+RCT
wulira	sinnawulira	V;INTEN;1;FUT
gamba	tetunnagamba	V;INTEN;PL;1;FUT
yimirira	twakayimirira	V;PROG;PL;1;PST
buza	naabuza	V;1;FUT+IMMED
yingira	naayingira	V;1;FUT+IMMED
jja	ndijja	V;1;FUT+RMT
beera	banaabeera	V;PL;3;FUT+IMMED
galamira	tugalamidde	V;PL;1;PST+RCT
lya	tulirya	V;PL;1;FUT+RMT
tunda	bakyatunda	V;PROG;PL;3;PRS
tandika	twatandise	V;PL;1;PST+RCT
ebaka	mwakebaka	V;PROG;PL;2;PST
somesa	asomesa	V;3;PRS
ggulawo	ndiggulawo	V;1;FUT+RMT
buuka	wabuuka	V;2;PST+RMT
kendeza	mukendeeza	V;PL;2;PRS
vuga	olivuga	V;2;FUT+RMT
wa	tetunnawa	V;INTEN;PL;1;FUT
yiga	yayize	V;3;PST+RCT
lamaga	mukyalamaga	V;PROG;PL;2;PRS
sobola	musobola	V;PL;2;PRS
kwata	nkutte	V;SG;1;PST+RCT
sobola	tulisobola	V;PL;1;FUT+RMT
sisinkana	balisisinkana	V;PL;3;FUT+RMT
elabira	yeerabira	V;3;PST+RMT
soma	musomye	V;PL;2;PST+RCT
nywa	banywa	V;PL;3;PRS
yiga	onooyiga	V;2;FUT+IMMED
kola	waakakola	V;PROG;2;PST
yiga	njiga	V;1;PRS
yongera	onooyongera	V;2;FUT+IMMED
elabira	weerabidde	V;SG;2;PST+RCT
sisinkana	tetunnasisinkana	V;INTEN;PL;1;FUT
genda	twagenda	V;PL;1;PST+RMT
buuza	nabuuzizza	V;1;PST+RCT
mwennya	temunnamwennya	V;INTEN;PL;2;FUT
ba ne	naaba ne	V;1;FUT+IMMED
londa	nkyalonda	V;PROG;1;PRS
zannya	bazannye	V;PL;3;PST+RCT
mala	mwamaze	V;PL;2;PST+RCT
ddamu	naddamu	V;1;PST+RMT
buuza	obuuza	V;2;PRS
lowooza	waakalowooza	V;PROG;2;PST
nnyonnyola	tannannyonnyola	V;INTEN;3;FUT
jja	anajja	V;3;FUT+IMMED
yogera	baliyogera	V;PL;3;FUT+RMT
dduka	waakadduka	V;PROG;2;PST
yimba	oyimbye	V;SG;2;PST+RCT
ebaka	mwebase	V;PL;2;PST+RCT
nnyonnyola	onoonnyonnyola	V;2;FUT+IMMED
galamira	agalamidde	V;SG;3;PST+RCT
buuka	ndibuuka	V;1;FUT+RMT
fuuka	bafuuka	V;PL;3;PRS
yanjula	mwanjudde	V;PL;2;PST+RCT
funa	bafunye	V;PL;3;PST+RCT
ebaka	neebaka	V;1;PST+RMT
kaaba	nkaaba	V;1;PRS
wuliriza	mwawulirizza	V;PL;2;PST+RCT
labika	tonnalabika	V;INTEN;2;FUT
somesa	alisomesa	V;3;FUT+RMT
ba ne	mbadde ne	V;SG;1;PST+RCT
kola	yakola	V;3;PST+RMT
gwa	sinnagwa	V;INTEN;1;FUT
saanga	nsanze	V;SG;1;PST+RCT
yaagala	twayagala	V;PL;1;PST+RMT
yamba	ayamba	V;3;PRS
sobola	sobola	V;NFIN
yanjula	baayanjudde	V;PL;3;PST+RCT
yita	oyita	V;2;PRS
wuliriza	tannawuliriza	V;INTEN;3;FUT
vuga	nvuga	V;1;PRS
somesa	musomesa	V;PL;2;PRS
kola	munaakola	V;PL;2;FUT+IMMED
zannya	yazannye	V;3;PST+RCT
twala	alitwala	V;3;FUT+RMT
komawo	wakomawo	V;2;PST+RMT
kola	twakoze	V;PL;1;PST+RCT
yimba	tannayimba	V;INTEN;3;FUT
vuga	muvuga	V;PL;2;PRS
buuza	balibuuza	V;PL;3;FUT+RMT
galamira	naagalamira	V;1;FUT+IMMED
wangula	baakawangula	V;PROG;PL;3;PST
nnyonnyola	twannyonnyodde	V;PL;1;PST+RCT
situka	tetunnasituka	V;INTEN;PL;1;FUT
yongera	tunaayongera	V;PL;1;FUT+IMMED
ggulawo	baaggulawo	V;PL;3;PST+RMT
nywegera	tulinywegera	V;PL;1;FUT+RMT
genda	ogenze	V;SG;2;PST+RCT
lamaga	mulamaze	V;PL;2;PST+RCT
sobola	basobodde	V;PL;3;PST+RCT
vuga	twakavuga	V;PROG;PL;1;PST
saanga	waakasanga	V;PROG;2;PST
yimba	wayimbye	V;2;PST+RCT
ggulawo	baggulawo	V;PL;3;PRS
wangula	nawangudde	V;1;PST+RCT
gwa	yaakagwa	V;PROG;3;PST
lamaga	akyalamaga	V;PROG;3;PRS
jja	okyajja	V;PROG;2;PRS
fumba	mwakafumba	V;PROG;PL;2;PST
etaaga	tuneetaaga	V;PL;1;FUT+IMMED
tta	tetunnatta	V;INTEN;PL;1;FUT
kwata	naakakwata	V;PROG;1;PST
laga	olaze	V;SG;2;PST+RCT
buza	yaakabuza	V;PROG;3;PST
ba ne	baakaba ne	V;PROG;PL;3;PST
sobola	basobola	V;PL;3;PRS
ssa	mussizza	V;PL;2;PST+RCT
kaaba	tukaabye	V;PL;1;PST+RCT
vuga	avuze	V;SG;3;PST+RCT
situka	baasituka	V;PL;3;PST+RMT
dduka	tudduse	V;PL;1;PST+RCT
mwennya	mukyamwennya	V;PROG;PL;2;PRS
kaaba	wakaaba	V;2;PST+RMT
kola	nkola	V;1;PRS
nywegera	nanywegedde	V;1;PST+RCT
funa	yaakafuna	V;PROG;3;PST
ggulawo	mwaakaggulawo	V;PROG;PL;2;PST
kaaba	wakaabye	V;2;PST+RCT
funa	afunye	V;SG;3;PST+RCT
mwennya	tumwennya	V;PL;1;PRS
buuza	mwabuuzizza	V;PL;2;PST+RCT
kola	nakola	V;1;PST+RMT
wulira	mwakawulira	V;PROG;PL;2;PST
wa	mpadde	V;SG;1;PST+RCT
buuza	okyabuuza	V;PROG;2;PRS
seka	aseka	V;3;PRS
gwa	okyagwa	V;PROG;2;PRS
londa	tulonze	V;PL;1;PST+RCT
yongera	ayongera	V;3;PRS
nywa	mulinywa	V;PL;2;FUT+RMT
gwa	mwakagwa	V;PROG;PL;2;PST
labika	tukyalabika	V;PROG;PL;1;PRS
laba	ndilaba	V;1;FUT+RMT
situka	balisituka	V;PL;3;FUT+RMT
ddamu	mukyaddamu	V;PROG;PL;2;PRS
funa	baakafuna	V;PROG;PL;3;PST
mala	mumala	V;PL;2;PRS
kaaba	kaaba	V;NFIN
tegeera	balitegeera	V;PL;3;FUT+RMT
labika	balabise	V;PL;3;PST+RCT
beera	mukyabeera	V;PROG;PL;2;PRS
ssa	wassa	V;2;PST+RMT
galamira	mugalamidde	V;PL;2;PST+RCT
laga	bakyalaga	V;PROG;PL;3;PRS
kozesa	olikozesa	V;2;FUT+RMT
mwennya	waakamwennya	V;PROG;2;PST
fuuka	bafuuse	V;PL;3;PST+RCT
kozesa	bakozeseza	V;PL;3;PST+RCT
kaaba	nakaabye	V;1;PST+RCT
wereza	mpeerezza	V;SG;1;PST+RCT
nnyonnyola	annyonnyodde	V;SG;3;PST+RCT
gula	tetunnagula	V;INTEN;PL;1;FUT
sobola	akyasobola	V;PROG;3;PRS
gwa	mugwa	V;PL;2;PRS
genda	ndigenda	V;1;FUT+RMT
etaaga	olyetaaga	V;2;FUT+RMT
yogera	tukyayogera	V;PROG;PL;1;PRS
wangula	onoowangula	V;2;FUT+IMMED
kwata	okutte	V;SG;2;PST+RCT
wandiika	owandiise	V;SG;2;PST+RCT
tambula	mutambula	V;PL;2;PRS
genda	tonnagenda	V;INTEN;2;FUT
saanga	osanze	V;SG;2;PST+RCT
laga	mwakalaga	V;PROG;PL;2;PST
lowooza	naalowooza	V;1;FUT+IMMED
dduka	twadduka	V;PL;1;PST+RMT
wuliriza	owulirizza	V;SG;2;PST+RCT
yimirira	mukyayimirira	V;PROG;PL;2;PRS
zannya	mwazannye	V;PL;2;PST+RCT
salawo	onoosalawo	V;2;FUT+IMMED
yimba	anaayimba	V;3;FUT+IMMED
laba	alaba	V;3;PRS
mwennya	omwennya	V;2;PRS
komawo	yakomawo	V;3;PST+RMT
soma	wasoma	V;2;PST+RMT
tegeera	nditegeera	V;1;FUT+RMT
etaaga	oneetaaga	V;2;FUT+IMMED
teka	tukyateeka	V;PROG;PL;1;PRS
yiga	waakayiga	V;PROG;2;PST
vuga	avuga	V;3;PRS
mwennya	olimwennya	V;2;FUT+RMT
kwata	anaakwata	V;3;FUT+IMMED
twala	tetunnatwala	V;INTEN;PL;1;FUT
lekana	tuleekaanye	V;PL;1;PST+RCT
galamira	banaagalamira	V;PL;3;FUT+IMMED
lya	mulirya	V;PL;2;FUT+RMT
buuza	tannabuuza	V;INTEN;3;FUT
funa	mulifuna	V;PL;2;FUT+RMT
dduka	nadduka	V;1;PST+RMT
wuliriza	naakawuliriza	V;PROG;1;PST
lwaana	banaalwana	V;PL;3;FUT+IMMED
mwennya	onoomwennya	V;2;FUT+IMMED
tegeera	otegedde	V;SG;2;PST+RCT
komawo	tunaakomawo	V;PL;1;FUT+IMMED
sobola	mwasobola	V;PL;2;PST+RMT
wangula	mukyawangula	V;PROG;PL;2;PRS
galamira	mwagalamira	V;PL;2;PST+RMT
gula	sinnagula	V;INTEN;1;FUT
etaaga	mweetaaga	V;PL;2;PST+RMT
mala	nkyamala	V;PROG;1;PRS
mwennya	wamwenyezza	V;2;PST+RCT
buuka	tukyabuuka	V;PROG;PL;1;PRS
yimirira	tuyimirira	V;PL;1;PRS
kiriza	yakkiriza	V;3;PST+RMT
buuza	mbuuzizza	V;SG;1;PST+RCT
kaaba	nkaabye	V;SG;1;PST+RCT
menya	akyamenya	V;PROG;3;PRS
tandika	tutandise	V;PL;1;PST+RCT
yanjula	wayanjula	V;2;PST+RMT
yiga	mukyayiga	V;PROG;PL;2;PRS
tambula	tebannatambula	V;INTEN;PL;3;FUT
kwata	bakutte	V;PL;3;PST+RCT
somesa	mukyasomesa	V;PROG;PL;2;PRS
yaagala	twakayagala	V;PROG;PL;1;PST
lamaga	balamaze	V;PL;3;PST+RCT
fumba	afumba	V;3;PRS
funa	baafuna	V;PL;3;PST+RMT
linda	ndirinda	V;1;FUT+RMT
wereza	baaweereza	V;PL;3;PST+RMT
zannya	muzannya	V;PL;2;PRS
wandiika	awandiika	V;3;PRS
seka	akyaseka	V;PROG;3;PRS
yamba	yayamba	V;3;PST+RMT
yimba	tetunnayimba	V;INTEN;PL;1;FUT
kaaba	tetunnakaaba	V;INTEN;PL;1;FUT
zina	ozinye	V;SG;2;PST+RCT
jja	twajja	V;PL;1;PST+RMT
ffa	yaakafa	V;PROG;3;PST
soma	soma	V;NFIN
laba	akyalaba	V;PROG;3;PRS
gula	naguze	V;1;PST+RCT
yamba	oyambye	V;SG;2;PST+RCT
beera	tebannabeera	V;INTEN;PL;3;FUT
twala	tonnatwala	V;INTEN;2;FUT
yimba	mwakayimba	V;PROG;PL;2;PST
zina	temunnazina	V;INTEN;PL;2;FUT
zannya	mulizannya	V;PL;2;FUT+RMT
sobola	baasobola	V;PL;3;PST+RMT
kiriza	nzikiriza	V;1;PRS
kwaata	baakutte	V;PL;3;PST+RCT
gula	mwagula	V;PL;2;PST+RMT
fuuka	tebannafuuka	V;INTEN;PL;3;FUT
sisinkana	asisinkana	V;3;PRS
ffa	wafudde	V;2;PST+RCT
menya	temunnamenya	V;INTEN;PL;2;FUT
beera	alibeera	V;3;FUT+RMT
wa	owadde	V;SG;2;PST+RCT
salawo	naasalawo	V;1;FUT+IMMED
yimirira	twayimiridde	V;PL;1;PST+RCT
kwaata	baakwaata	V;PL;3;PST+RMT
yaagala	yayagadde	V;3;PST+RCT
kendeza	anaakendeeza	V;3;FUT+IMMED
kwata	temunnakwata	V;INTEN;PL;2;FUT
kwata	onookwata	V;2;FUT+IMMED
mwennya	yamwenyezza	V;3;PST+RCT
soma	osoma	V;2;PRS
tambula	mwatambudde	V;PL;2;PST+RCT
labika	anaalabika	V;3;FUT+IMMED
ddamu	tebannaddamu	V;INTEN;PL;3;FUT
gamba	okyagamba	V;PROG;2;PRS
yiga	wayize	V;2;PST+RCT
gwa	tonnagwa	V;INTEN;2;FUT
ba	mbadde	V;SG;1;PST+RCT
etaaga	netaaga	V;1;PRS
