mahara	mahara	V;ACT
tahi	tahia	V;PASS
mahara	maharatia	V;PASS
whāngai	whāngai	V;ACT
momotu	motukia	V;PASS
hiki	hiki	V;ACT
mutu	mutua	V;PASS
aroha	aroha	V;ACT
mihi	mihi	V;ACT
tomo	tomokia	V;PASS
kī	kī	V;ACT
ako	ako	V;ACT
pātai	pātaitia	V;PASS
tūtaki	tūtakitia	V;PASS
motu	motukia	V;PASS
eke	eke	V;ACT
hora	hora	V;ACT
tuhituhi	tuhituhi	V;ACT
oho	ohokia	V;PASS
manaaki	manaakitia	V;PASS
rongo	rongo	V;ACT
hemo	hemo	V;ACT
parai	parai	V;ACT
keri	keria	V;PASS
ruruku	rurukutia	V;PASS
hoe	hoea	V;PASS
tunu	tunua	V;PASS
pā	pā	V;ACT
ruku	rukuhia	V;PASS
titiro	tirohia	V;PASS
kau	kau	V;ACT
tupu	tupuria	V;PASS
kutētē	kutētētia	V;PASS
pīrangi	pīrangi	V;ACT
hiahia	hiahiatia	V;PASS
pī	pīhia	V;PASS
tahu	tahuna	V;PASS
hīkoi	hīkoitia	V;PASS
hono	hono	V;ACT
hamu	hamua	V;PASS
paki	paki	V;ACT
wareware	warewaretia	V;PASS
