anjary	nanjary	V;PST
amoy	hamoy	V;FUT
andrakaraka	handrakaraka	V;FUT
anamasina	anamasina	V;NFIN
ifindra	nifindra	V;PST
ankatelina	mankatelina	V;PRS
ifarimbona	hifarimbona	V;FUT
iondrana	hiondrana	V;FUT
ifanila	hifanila	V;FUT
angarika	hangarika	V;FUT
anafy	anafy	V;NFIN
ikororosy	ikororosy	V;NFIN
andetsy	andetsy	V;NFIN
itangorona	hitangorona	V;FUT
ihaminkamina	nihaminkamina	V;PST
anandevo	anandevo	V;NFIN
ikororosy	hikororosy	V;FUT
ihevaheva	hihevaheva	V;FUT
anameloka	nanameloka	V;PST
andama	mandama	V;PRS
isoroka	isoroka	V;NFIN
androtsaka	androtsaka	V;NFIN
ihira	mihira	V;PRS
ilika	hilika	V;FUT
anameloka	manameloka	V;PRS
andadina	andadina	V;NFIN
ivoady	hivoady	V;FUT
ifady	nifady	V;PST
ifamofo	hifamofo	V;FUT
andrakaraka	nandrakaraka	V;PST
iangotingoty	miangotingoty	V;PRS
ianatra	ianatra	V;NFIN
isoroka	nisoroka	V;PST
iangatra	niangatra	V;PST
isotro	nisotro	V;PST
andavorary	mandavorary	V;PRS
irotsaka	irotsaka	V;NFIN
andrekitra	handrekitra	V;FUT
ahadikitra	nahadikitra	V;PST
anikina	nanikina	V;PST
ikiky	hikiky	V;FUT
amahy	namahy	V;PST
ifaratra	hifaratra	V;FUT
andahatra	andahatra	V;NFIN
ieritreritra	hieritreritra	V;FUT
atory	matory	V;PRS
anana	manana	V;PRS
andeha	andeha	V;NFIN
anapitra	anapitra	V;NFIN
amitsobitsoka	namitsobitsoka	V;PST
ihaino	nihaino	V;PST
iery	iery	V;NFIN
ifohaza	nifohaza	V;PST
ikivilivily	hikivilivily	V;FUT
anetry	hanetry	V;FUT
ampandre	mampandre	V;PRS
ampandre	nampandre	V;PST
itsoka	hitsoka	V;FUT
ivokovoko	mivokovoko	V;PRS
anadihady	hanadihady	V;FUT
ifarimbona	ifarimbona	V;NFIN
andà	nandà	V;PST
igigagiga	higigagiga	V;FUT
iery	miery	V;PRS
anapitra	hanapitra	V;FUT
anandevo	hanandevo	V;FUT
itsiriritra	hitsiriritra	V;FUT
iboboka	iboboka	V;NFIN
anadihady	manadihady	V;PRS
andova	nandova	V;PST
amilabila	hamilabila	V;FUT
anadidy	manadidy	V;PRS
ampiavaka	nampiavaka	V;PST
andrava	handrava	V;FUT
iboriaka	niboriaka	V;PST
anandevo	nanandevo	V;PST
itomany	hitomany	V;FUT
andresy	nandresy	V;PST
ieritreritra	mieritreritra	V;PRS
amokatra	namokatra	V;PST
itsiriritra	itsiriritra	V;NFIN
ijery	mijery	V;PRS
andringana	nandringana	V;PST
androtika	androtika	V;NFIN
miasa	nmiasa	V;PST
iandrandra	niandrandra	V;PST
ahary	hahary	V;FUT
ihaino	mihaino	V;PRS
ifindra	hifindra	V;FUT
irotsaka	hirotsaka	V;FUT
androtika	nandrotika	V;PST
andrenodrenoka	handrenodrenoka	V;FUT
ifaratra	mifaratra	V;PRS
ihira	hihira	V;FUT
itantara	mitantara	V;PRS
ihebinkenina	nihebinkenina	V;PST
andrava	andrava	V;NFIN
ivokovoko	hivokovoko	V;FUT
amarana	namarana	V;PST
anikina	hanikina	V;FUT
anorina	nanorina	V;PST
iboboka	niboboka	V;PST
anakà	nanakà	V;PST
ianatra	hianatra	V;FUT
anary	nanary	V;PST
itomany	itomany	V;NFIN
isalovana	isalovana	V;NFIN
ikororosy	nikororosy	V;PST
andihy	nandihy	V;PST
andama	handama	V;FUT
ipetraka	hipetraka	V;FUT
miasa	hmiasa	V;FUT
amisavisa	namisavisa	V;PST
anamaivana	nanamaivana	V;PST
amefy	namefy	V;PST
anombana	anombana	V;NFIN
amaky	amaky	V;NFIN
ikoviaviaka	nikoviaviaka	V;PST
amoy	mamoy	V;PRS
anody	hanody	V;FUT
anakora	hanakora	V;FUT
anody	nanody	V;PST
ijery	hijery	V;FUT
itambelona	mitambelona	V;PRS
anjavona	anjavona	V;NFIN
ikajy	mikajy	V;PRS
andavorary	handavorary	V;FUT
