qatel	qtilt	V;PRF;FIN;SG;1;PST
indika	jindika	V;IPFV;FIN;MASC;SG;3;PST
sama'	semgħet	V;PRF;FIN;SG;2;PST
samat	samtet	V;PRF;FIN;FEM;SG;3;PST
irrisponda	irrisponda	V;PRF;FIN;MASC;SG;3;PST
gidem	gidem	V;PRF;FIN;MASC;SG;3;PST
miet	mmut	V;IPFV;FIN;SG;1;PST
ħolom	ħolmu	V;PRF;FIN;PL;3;PST
jaf	taf	V;IPFV;FIN;SG;2;PST
iddawnlowdja	iddawnlowdjaw	V;FIN;IMP;PL;1
mar	mortu	V;PRF;FIN;PL;2;PST
indika	indikaw	V;PRF;FIN;PL;3;PST
xegħel	ixgħel	V;FIN;IMP;SG;2
tkellem	tkellimt	V;PRF;FIN;SG;2;PST
ħolom	ħlomt	V;PRF;FIN;SG;1;PST
għażel	tagħżel	V;IPFV;FIN;FEM;SG;3;PST
ammira	nammira	V;IPFV;FIN;SG;1;PST
kanta	kantajtu	V;PRF;FIN;PL;2;PST
beda	bdejna	V;PRF;FIN;PL;1;PST
ra	naraw	V;IPFV;FIN;PL;1;PST
iddawnlowdja	niddawnlowdja	V;IPFV;FIN;SG;1;PST
wieġeb	twieġbu	V;IPFV;FIN;PL;2;PST
bela'	jibilgħu	V;IPFV;FIN;PL;3;PST
niek	jnik	V;IPFV;FIN;MASC;SG;3;PST
bena	bniet	V;PRF;FIN;FEM;SG;3;PST
bidel	bdilt	V;PRF;FIN;SG;1;PST
bena	tibnu	V;IPFV;FIN;PL;2;PST
għasar	agħsar	V;FIN;IMP;SG;2
ta	agħti	V;FIN;IMP;SG;2
għamel	tagħmel	V;IPFV;FIN;FEM;SG;3;PST
beżaq	beżqet	V;PRF;FIN;FEM;SG;3;PST
ħataf	taħtaf	V;IPFV;FIN;FEM;SG;3;PST
tilef	itlef	V;FIN;IMP;SG;2
sama'	tisimgħu	V;IPFV;FIN;PL;2;PST
kiber	nikber	V;IPFV;FIN;SG;1;PST
fired	tifred	V;IPFV;FIN;FEM;SG;3;PST
żar	iżżur	V;IPFV;FIN;FEM;SG;3;PST
għoġob	togħġob	V;IPFV;FIN;FEM;SG;3;PST
ħataf	naħtfu	V;IPFV;FIN;PL;1;PST
imbotta	nimbottaw	V;IPFV;FIN;PL;1;PST
xtaq	xtaqna	V;PRF;FIN;PL;1;PST
ġie	tiġi	V;IPFV;FIN;FEM;SG;3;PST
samat	jismtu	V;IPFV;FIN;PL;3;PST
kell	kellu	V;FIN;MASC;SG;3
ittraduċa	ittraduċiet	V;PRF;FIN;FEM;SG;3;PST
kien	ikunu	V;IPFV;FIN;PL;3;PST
ippromwova	ippromwovejna	V;PRF;FIN;PL;1;PST
bela'	nibla'	V;IPFV;FIN;SG;1;PST
niek	niku	V;FIN;IMP;PL;1
kien	kienet	V;PRF;FIN;FEM;SG;3;PST
xtara	xtrajtu	V;PRF;FIN;PL;2;PST
ħolom	ħolom	V;PRF;FIN;MASC;SG;3;PST
ħalla	nħalli	V;IPFV;FIN;SG;1;PST
qara	tiqraw	V;IPFV;FIN;PL;2;PST
iddeskriva	tiddeskrivi	V;IPFV;FIN;FEM;SG;3;PST
ammira	tammira	V;IPFV;FIN;FEM;SG;3;PST
imbotta	imbottat	V;PRF;FIN;FEM;SG;3;PST
ħataf	aħtfu	V;FIN;IMP;PL;1
qal	għedt	V;PRF;FIN;SG;1;PST
ammira	ammirajt	V;PRF;FIN;SG;2;PST
qal	għid	V;FIN;IMP;SG;2
għex	jgħix	V;IPFV;FIN;MASC;SG;3;PST
ħaraq	ħraqtu	V;PRF;FIN;PL;2;PST
irreaġixxa	tirreaġixxi	V;IPFV;FIN;SG;2;PST
niek	nnik	V;IPFV;FIN;SG;1;PST
libes	libsu	V;PRF;FIN;PL;3;PST
ħabb	ħabbet	V;PRF;FIN;FEM;SG;3;PST
fehem	nifhmu	V;IPFV;FIN;PL;1;PST
irreaġixxa	irreaġixxejtu	V;PRF;FIN;PL;2;PST
ħalaq	ħalqet	V;PRF;FIN;FEM;SG;3;PST
aġġastja	taġġastjaw	V;IPFV;FIN;PL;2;PST
ħataf	ħataf	V;PRF;FIN;MASC;SG;3;PST
tilef	titlef	V;IPFV;FIN;SG;2;PST
ipprova	ipprova	V;PRF;FIN;MASC;SG;3;PST
dafar	nidfru	V;IPFV;FIN;PL;1;PST
wasal	wasalna	V;PRF;FIN;PL;1;PST
gidem	jigdmu	V;IPFV;FIN;PL;3;PST
baqa'	baqgħet	V;PRF;FIN;SG;2;PST
għorok	togħrku	V;IPFV;FIN;PL;2;PST
qasam	qasmu	V;PRF;FIN;PL;3;PST
dineb	jidneb	V;IPFV;FIN;MASC;SG;3;PST
samat	tismot	V;IPFV;FIN;SG;2;PST
rikeb	jirkbu	V;IPFV;FIN;PL;3;PST
kiteb	tikteb	V;IPFV;FIN;FEM;SG;3;PST
iddawnlowdja	tiddawnlowdja	V;IPFV;FIN;SG;2;PST
niżel	nżilt	V;PRF;FIN;SG;2;PST
kell	kellek	V;FIN;MASC+FEM;SG;2
libes	lbist	V;PRF;FIN;SG;1;PST
għamel	jagħmel	V;IPFV;FIN;MASC;SG;3;PST
kiseb	ksibt	V;PRF;FIN;SG;2;PST
għalaq	għalqet	V;PRF;FIN;FEM;SG;3;PST
ra	raw	V;PRF;FIN;PL;3;PST
ġie	ejja	V;FIN;IMP;SG;2
għorok	għorkot	V;PRF;FIN;FEM;SG;3;PST
ippromwova	ippromwovew	V;PRF;FIN;PL;3;PST
baqa'	jibqgħu	V;IPFV;FIN;PL;3;PST
daħak	daħku	V;PRF;FIN;PL;3;PST
seta'	nista'	V;IPFV;FIN;SG;1;PST
samat	ismot	V;FIN;IMP;SG;2
għażel	tagħżlu	V;IPFV;FIN;PL;2;PST
ħabb	ħobb	V;FIN;IMP;SG;2
għoġob	għoġbu	V;PRF;FIN;PL;3;PST
beżaq	nobżqu	V;IPFV;FIN;PL;1;PST
kiseb	niksbu	V;IPFV;FIN;PL;1;PST
miet	jmutu	V;IPFV;FIN;PL;3;PST
seta'	setgħu	V;PRF;FIN;PL;3;PST
ħoloq	noħolqu	V;IPFV;FIN;PL;1;PST
qasam	taqsam	V;IPFV;FIN;FEM;SG;3;PST
kiser	kisru	V;PRF;FIN;PL;3;PST
qara	iqraw	V;FIN;IMP;PL;1
esperjenza	esperjenzat	V;PRF;FIN;FEM;SG;3;PST
beżaq	bżaqtu	V;PRF;FIN;PL;2;PST
żar	żurtu	V;PRF;FIN;PL;2;PST
għasar	għasar	V;PRF;FIN;MASC;SG;3;PST
żar	żurt	V;PRF;FIN;SG;1;PST
fetaħ	tiftħu	V;IPFV;FIN;PL;2;PST
tala'	nitilgħu	V;IPFV;FIN;PL;1;PST
mexa	imxejt	V;PRF;FIN;SG;1;PST
sama'	nisimgħu	V;IPFV;FIN;PL;1;PST
aggredixxa	aggredixxiet	V;PRF;FIN;FEM;SG;3;PST
emmen	jemmnu	V;IPFV;FIN;PL;3;PST
bidel	bidlu	V;PRF;FIN;PL;3;PST
għamel	nagħmlu	V;IPFV;FIN;PL;1;PST
seta'	stajtu	V;PRF;FIN;PL;2;PST
bela'	blajt	V;PRF;FIN;SG;1;PST
dara	drajna	V;PRF;FIN;PL;1;PST
tkellem	tkellmu	V;FIN;IMP;PL;1
eżerċita	teżerċita	V;IPFV;FIN;SG;2;PST
tilef	nitlfu	V;IPFV;FIN;PL;1;PST
beda	jibdew	V;IPFV;FIN;PL;3;PST
nesa	insejt	V;PRF;FIN;SG;1;PST
ta	tat	V;PRF;FIN;FEM;SG;3;PST
ħoloq	noħloq	V;IPFV;FIN;SG;1;PST
niek	nieket	V;PRF;FIN;FEM;SG;3;PST
kiser	ksirt	V;PRF;FIN;SG;1;PST
rikeb	tirkeb	V;IPFV;FIN;FEM;SG;3;PST
rebaħ	rbaħna	V;PRF;FIN;PL;1;PST
ipprova	ipprovajtu	V;PRF;FIN;PL;2;PST
telaq	nitilqu	V;IPFV;FIN;PL;1;PST
esperjenza	esperjenza	V;FIN;IMP;SG;2
sab	sabu	V;PRF;FIN;PL;3;PST
siket	jisktu	V;IPFV;FIN;PL;3;PST
ippromwova	ippromwovejtu	V;PRF;FIN;PL;2;PST
għasar	nagħsru	V;IPFV;FIN;PL;1;PST
jaf	kun af	V;FIN;IMP;SG;2
qasam	qsamtu	V;PRF;FIN;PL;2;PST
telaq	itilqu	V;FIN;IMP;PL;1
ammira	ammiraw	V;PRF;FIN;PL;3;PST
ġie	jiġu	V;IPFV;FIN;PL;3;PST
ivvjola	ivvjolajt	V;PRF;FIN;SG;1;PST
irrisponda	tirrispondi	V;IPFV;FIN;FEM;SG;3;PST
kiser	jikser	V;IPFV;FIN;MASC;SG;3;PST
irrisponda	irrispondejtu	V;PRF;FIN;PL;2;PST
daħak	nidħku	V;IPFV;FIN;PL;1;PST
qasam	qsamt	V;PRF;FIN;SG;1;PST
kell	kell	V;NFIN
kiel	tiekol	V;IPFV;FIN;FEM;SG;3;PST
dafar	dfarna	V;PRF;FIN;PL;1;PST
kanta	kanta	V;FIN;IMP;SG;2
ġabar	iġbru	V;FIN;IMP;PL;1
ivvjola	ivvjolaw	V;PRF;FIN;PL;3;PST
ipprova	tipprova	V;IPFV;FIN;FEM;SG;3;PST
bela'	blajtu	V;PRF;FIN;PL;2;PST
beżaq	tobżoq	V;IPFV;FIN;FEM;SG;3;PST
siker	tisker	V;IPFV;FIN;FEM;SG;3;PST
ħu	ħukom	N;MASC+FEM;PL;2
żar	żaret	V;PRF;FIN;FEM;SG;3;PST
falla	fallejt	V;PRF;FIN;SG;2;PST
dara	jidraw	V;IPFV;FIN;PL;3;PST
nesa	insejna	V;PRF;FIN;PL;1;PST
gidem	igdmu	V;FIN;IMP;PL;1
eżerċita	eżerċitaw	V;FIN;IMP;PL;1
ħonoq	ħnoqtu	V;PRF;FIN;PL;2;PST
għoġob	għoġbot	V;PRF;FIN;FEM;SG;3;PST
dara	tidraw	V;IPFV;FIN;PL;2;PST
ra	rat	V;PRF;FIN;FEM;SG;3;PST
ħaseb	naħsbu	V;IPFV;FIN;PL;1;PST
fetaħ	ftaħtu	V;PRF;FIN;PL;2;PST
irrisponda	nirrispondi	V;IPFV;FIN;SG;1;PST
indika	jindikaw	V;IPFV;FIN;PL;3;PST
ipparteċipa	tipparteċipaw	V;IPFV;FIN;PL;2;PST
ħalla	ħallejna	V;PRF;FIN;PL;1;PST
esperjenza	esperjenzajt	V;PRF;FIN;SG;1;PST
bela'	belgħet	V;PRF;FIN;FEM;SG;3;PST
ħoloq	ħoloq	V;PRF;FIN;MASC;SG;3;PST
ħaseb	ħsibna	V;PRF;FIN;PL;1;PST
libes	libes	V;PRF;FIN;MASC;SG;3;PST
wasal	tasal	V;IPFV;FIN;SG;2;PST
bies	bieset	V;PRF;FIN;FEM;SG;3;PST
seta'	jista'	V;IPFV;FIN;MASC;SG;3;PST
għażel	tagħżel	V;IPFV;FIN;SG;2;PST
qara	qrajna	V;PRF;FIN;PL;1;PST
stimula	jistimula	V;IPFV;FIN;MASC;SG;3;PST
mexa	timxi	V;IPFV;FIN;SG;2;PST
għorok	jogħrok	V;IPFV;FIN;MASC;SG;3;PST
sab	insibu	V;IPFV;FIN;PL;1;PST
ittraduċa	ittraduċi	V;FIN;IMP;SG;2
nesa	insejtu	V;PRF;FIN;PL;2;PST
kiser	ksirtu	V;PRF;FIN;PL;2;PST
samat	smattu	V;PRF;FIN;PL;2;PST
qatel	qtiltu	V;PRF;FIN;PL;2;PST
kanta	kantajt	V;PRF;FIN;SG;1;PST
sab	sabet	V;PRF;FIN;FEM;SG;3;PST
baqa'	bqajna	V;PRF;FIN;PL;1;PST
siket	siket	V;PRF;FIN;MASC;SG;3;PST
bagħad	jobgħod	V;IPFV;FIN;MASC;SG;3;PST
daħal	daħlet	V;PRF;FIN;FEM;SG;3;PST
fetaħ	niftaħ	V;IPFV;FIN;SG;1;PST
wieġeb	wieġeb	V;FIN;IMP;SG;2
għasar	agħsru	V;FIN;IMP;PL;1
siker	skirna	V;PRF;FIN;PL;1;PST
iddawnlowdja	jiddawnlowdja	V;IPFV;FIN;MASC;SG;3;PST
ħaseb	naħseb	V;IPFV;FIN;SG;1;PST
bela'	tibla'	V;IPFV;FIN;SG;2;PST
aġġastja	jaġġastja	V;IPFV;FIN;MASC;SG;3;PST
iddeskriva	tiddeskrivi	V;IPFV;FIN;SG;2;PST
irreaġixxa	nirreaġixxi	V;IPFV;FIN;SG;1;PST
mexa	imxi	V;FIN;IMP;SG;2
ħaraq	taħraq	V;IPFV;FIN;SG;2;PST
iddeskriva	niddeskrivi	V;IPFV;FIN;SG;1;PST
eżerċita	eżerċitat	V;PRF;FIN;FEM;SG;3;PST
ried	trid	V;IPFV;FIN;FEM;SG;3;PST
libes	jilbsu	V;IPFV;FIN;PL;3;PST
aggredixxa	jaggredixxi	V;IPFV;FIN;MASC;SG;3;PST
kiel	kielu	V;PRF;FIN;PL;3;PST
ippenetra	ippenetrajtu	V;PRF;FIN;PL;2;PST
tala'	titilgħu	V;IPFV;FIN;PL;2;PST
beda	bdejt	V;PRF;FIN;SG;1;PST
għalaq	nagħlqu	V;IPFV;FIN;PL;1;PST
qasam	qasmet	V;PRF;FIN;FEM;SG;3;PST
ammira	ammira	V;FIN;IMP;SG;2
ippenetra	ippenetra	V;FIN;IMP;SG;2
ħa	ħadt	V;PRF;FIN;SG;2;PST
nesa	insejt	V;PRF;FIN;SG;2;PST
fetaħ	ftaħna	V;PRF;FIN;PL;1;PST
bela'	blajna	V;PRF;FIN;PL;1;PST
gidem	nigdmu	V;IPFV;FIN;PL;1;PST
kien	kienu	V;PRF;FIN;PL;3;PST
seraq	israq	V;FIN;IMP;SG;2
ippenetra	jippenetra	V;IPFV;FIN;MASC;SG;3;PST
ipparteċipa	tipparteċipa	V;IPFV;FIN;SG;2;PST
sama'	smajna	V;PRF;FIN;PL;1;PST
fehem	tifhmu	V;IPFV;FIN;PL;2;PST
qasam	naqsam	V;IPFV;FIN;SG;1;PST
jaf	jafu	V;IPFV;FIN;PL;3;PST
jisem	jisimkom	V;FIN;MASC+FEM;PL;2
rebaħ	rebħu	V;PRF;FIN;PL;3;PST
ħareġ	ħareġ	V;PRF;FIN;MASC;SG;3;PST
fetaħ	jiftħu	V;IPFV;FIN;PL;3;PST
qal	ngħid	V;IPFV;FIN;SG;1;PST
bies	tbus	V;IPFV;FIN;SG;2;PST
ħataf	taħtfu	V;IPFV;FIN;PL;2;PST
xegħel	xegħlu	V;PRF;FIN;PL;3;PST
xegħel	nixegħlu	V;IPFV;FIN;PL;1;PST
indika	indikajt	V;PRF;FIN;SG;1;PST
dara	jidra	V;IPFV;FIN;MASC;SG;3;PST
indika	indikajtu	V;PRF;FIN;PL;2;PST
rikeb	rkibna	V;PRF;FIN;PL;1;PST
iddawnlowdja	iddawnlowdja	V;PRF;FIN;MASC;SG;3;PST
bidel	tibdlu	V;IPFV;FIN;PL;2;PST
qara	qrajt	V;PRF;FIN;SG;1;PST
fetaħ	fetħu	V;PRF;FIN;PL;3;PST
tala'	telgħet	V;PRF;FIN;FEM;SG;3;PST
kien	konna	V;PRF;FIN;PL;1;PST
ħaraq	taħraq	V;IPFV;FIN;FEM;SG;3;PST
għex	għext	V;PRF;FIN;SG;1;PST
ħu	ħu	N
irreaġixxa	irreaġixxi	V;FIN;IMP;SG;2
emmen	nemmen	V;IPFV;FIN;SG;1;PST
daħak	nidħak	V;IPFV;FIN;SG;1;PST
mexa	imxejna	V;PRF;FIN;PL;1;PST
qal	qal	V;PRF;FIN;MASC;SG;3;PST
ħaraq	aħraq	V;FIN;IMP;SG;2
fehem	fehmu	V;PRF;FIN;PL;3;PST
falla	falliet	V;PRF;FIN;FEM;SG;3;PST
xtaq	nixtiequ	V;IPFV;FIN;PL;1;PST
libes	nilbsu	V;IPFV;FIN;PL;1;PST
iddeskriva	iddeskrivu	V;FIN;IMP;PL;1
tar	intiru	V;IPFV;FIN;PL;1;PST
żifen	tiżfnu	V;IPFV;FIN;PL;2;PST
irrisponda	irrispondew	V;PRF;FIN;PL;3;PST
ħonoq	toħnoq	V;IPFV;FIN;SG;2;PST
niżel	tinżlu	V;IPFV;FIN;PL;2;PST
siker	sikret	V;PRF;FIN;FEM;SG;3;PST
falla	nfalli	V;IPFV;FIN;SG;1;PST
iddeskriva	iddeskriviet	V;PRF;FIN;FEM;SG;3;PST
ħataf	aħtaf	V;FIN;IMP;SG;2
ipprojbixxa	nipprojbixxi	V;IPFV;FIN;SG;1;PST
bagħad	tobgħod	V;IPFV;FIN;SG;2;PST
dara	drajtu	V;PRF;FIN;PL;2;PST
seraq	tisirqu	V;IPFV;FIN;PL;2;PST
dafar	nidfor	V;IPFV;FIN;SG;1;PST
berred	berridt	V;PRF;FIN;SG;1;PST
baqa'	nibqgħu	V;IPFV;FIN;PL;1;PST
samat	samtu	V;PRF;FIN;PL;3;PST
kiel	tieklu	V;IPFV;FIN;PL;2;PST
stimula	stimulajtu	V;PRF;FIN;PL;2;PST
nesa	insew	V;FIN;IMP;PL;1
ippromwova	ippromwovu	V;FIN;IMP;PL;1
kiel	kiel	V;PRF;FIN;MASC;SG;3;PST
pejjep	pejpu	V;PRF;FIN;PL;3;PST
mar	immur	V;IPFV;FIN;SG;1;PST
ra	taraw	V;IPFV;FIN;PL;2;PST
kien	ikun	V;IPFV;FIN;MASC;SG;3;PST
beżaq	jobżqu	V;IPFV;FIN;PL;3;PST
stimula	stimulat	V;PRF;FIN;FEM;SG;3;PST
imbotta	imbottaw	V;PRF;FIN;PL;3;PST
xegħel	xgħelt	V;PRF;FIN;SG;2;PST
wasal	wasalt	V;PRF;FIN;SG;1;PST
kiel	kulu	V;FIN;IMP;PL;1
għażel	nagħżlu	V;IPFV;FIN;PL;1;PST
ħataf	ħtaft	V;PRF;FIN;SG;2;PST
għażel	għażilt	V;PRF;FIN;SG;2;PST
ġibed	tiġbed	V;IPFV;FIN;SG;2;PST
stimula	stimulaw	V;FIN;IMP;PL;1
għorok	għorku	V;PRF;FIN;PL;3;PST
ħa	ħu	V;FIN;IMP;SG;2
aggredixxa	aggredixxi	V;FIN;IMP;SG;2
irreaġixxa	irreaġixxejt	V;PRF;FIN;SG;2;PST
kanta	nkantaw	V;IPFV;FIN;PL;1;PST
bagħad	tobgħod	V;IPFV;FIN;FEM;SG;3;PST
xtaq	xtaqtu	V;PRF;FIN;PL;2;PST
emmen	nemmnu	V;IPFV;FIN;PL;1;PST
telaq	telqet	V;PRF;FIN;FEM;SG;3;PST
xegħel	jixegħlu	V;IPFV;FIN;PL;3;PST
sama'	isimgħu	V;FIN;IMP;PL;1
xegħel	xgħelt	V;PRF;FIN;SG;1;PST
kiber	kibru	V;PRF;FIN;PL;3;PST
għoġob	għoġobtu	V;PRF;FIN;PL;2;PST
dara	nidra	V;IPFV;FIN;SG;1;PST
daħak	tidħak	V;IPFV;FIN;SG;2;PST
rikeb	irkeb	V;FIN;IMP;SG;2
stimula	stimula	V;FIN;IMP;SG;2
miet	mietu	V;PRF;FIN;PL;3;PST
falla	nfallu	V;IPFV;FIN;PL;1;PST
fetaħ	iftaħ	V;FIN;IMP;SG;2
ġabar	ġbartu	V;PRF;FIN;PL;2;PST
fired	fridt	V;PRF;FIN;SG;1;PST
ikoll	ikollna	V;FIN;MASC+FEM;PL;1
ħalla	tħalli	V;IPFV;FIN;SG;2;PST
indika	indikat	V;PRF;FIN;FEM;SG;3;PST
kiel	kielet	V;PRF;FIN;FEM;SG;3;PST
eżerċita	jeżerċita	V;IPFV;FIN;MASC;SG;3;PST
għoġob	nogħġob	V;IPFV;FIN;SG;1;PST
mexa	jimxi	V;IPFV;FIN;MASC;SG;3;PST
irrisponda	irrispondejt	V;PRF;FIN;SG;2;PST
għażel	għażlu	V;PRF;FIN;PL;3;PST
għoġob	ogħġbu	V;FIN;IMP;PL;1
ta	agħtu	V;FIN;IMP;PL;1
baqa'	ibqa'	V;FIN;IMP;SG;2
ħa	tieħu	V;IPFV;FIN;SG;2;PST
dafar	idfru	V;FIN;IMP;PL;1
ġabar	jiġbru	V;IPFV;FIN;PL;3;PST
