ngi	pungana	V;IRR;PL;3;PST
nu	thunungam	V;SG;2;non{FUT}
la	ngule	V;IRR;SG;1;PST
ma	ngimi	V;IRR;SG;1;PST
na	tjinangam	V;SG;2;non{FUT}
i	ngu	V;IRR;SG;1
mi	numi	V;IRR;PC;2
e	ngerrena	V;PL;1;PST
ntha	nginthanyi	V;SG;1;PST
na	ninnangi	V;IRR;PC;2;PST
mi	mina	V;SG;1;PST
ma	thama	V;IRR;SG;2
la	thule	V;IRR;SG;2;PST
mi	pumim	V;PL;3;non{FUT}
mi	ngumina	V;PC;1;PST
rdi	kuddi	V;IRR;PL;3
mu	ngumune	V;PC;1;PST
mi	mim	V;SG;3;non{FUT}
ntji	nantji	V;PL;2;PST
rdu	nguddu	V;IRR;PL;1
mu	numuy	V;IRR;PC;2;PST
ma	ne	V;SG;2;PST
ya	purne	V;PC;3;PST
la	killa	V;IRR;PL;3
mu	pumu	V;IRR;SG;1+INCL
bi	dina	V;SG;2;PST
bu	pubune	V;PC;3;PST
li	ngili	V;SG;1;PST
na	ninga	V;SG;3;PST
bu	buy	V;IRR;SG;1;PST
a	ka	V;IRR;PC;3
bi	ngubi	V;IRR;PL;1
ya	nurni	V;PL;2;PST
ntha	tjinthanyi	V;SG;1+INCL;PST
bi	nubi	V;IRR;PL;2
me	ngumena	V;PL;1;PST
be	bena	V;IRR;SG;3;PST
mu	kumuy	V;IRR;PC;3;PST
nu	ngunna	V;IRR;PC;1
mu	mu	V;IRR;SG;1
na	nginnanga	V;PL;1;PST
e	ngem	V;SG;1;non{FUT}
ntji	ngantjin	V;PL;1;non{FUT}
ntji	perra	V;IRR;PC;3;PST
ntji	nerra	V;IRR;PC;2;PST
ni	narni	V;IRR;PL;2
be	bena	V;SG;3;PST
nu	punne	V;IRR;PC;3;PST
a	ngarrane	V;PC;1;PST
ngu	ngunga	V;IRR;PC;1
rra	pirri	V;SG;3;PST
buy	dana	V;SG;2;PST
ni	thani	V;IRR;SG;2
nga	tjingam	V;SG;2;non{FUT}
mi	numina	V;IRR;PL;2;PST
na	ninnangam	V;PL;2;non{FUT}
ba	da	V;IRR;SG;2
ntji	nga	V;IRR;SG;1
me	numena	V;IRR;PL;2;PST
rru	ngurran	V;SG;1;non{FUT}
a	ngerra	V;IRR;PC;1;PST
bi	bi	V;IRR;SG;3
rdi	nguddana	V;PL;1;PST
ni	thardi	V;SG;2;PST
rri	tjirri	V;SG;2;PST
ma	thamam	V;SG;1+INCL;non{FUT}
me	ngume	V;IRR;PC;1
mu	pumuni	V;PL;3;PST
e	nerrene	V;PC;2;PST
rdi	nguddana	V;PC;1;PST
na	kinna	V;IRR;PL;3
rdu	nguddi	V;IRR;PL;1;PST
la	killa	V;IRR;PC;3
bi	kubi	V;IRR;PL;3
ni	narnam	V;PL;2;non{FUT}
nu	nguna	V;SG;1;PST
la	pulle	V;IRR;PL;3;PST
bu	nubuy	V;IRR;PL;2;PST
ntji	thantji	V;SG;2;PST
ngi	thungana	V;IRR;SG;1+INCL;PST
ni	narne	V;IRR;PC;2
ntha	ninthangi	V;IRR;PL;2;PST
ngu	ngungi	V;IRR;SG;1;PST
ma	pumi	V;IRR;PL;3;PST
buy	nubuy	V;IRR;PC;2
ya	ngurni	V;PL;1;PST
buy	ngubana	V;IRR;PC;1;PST
li	ngillingi	V;IRR;PC;1;PST
bi	pubina	V;PC;3;PST
bi	dim	V;SG;2;non{FUT}
li	tjilim	V;SG;2;non{FUT}
na	ngina	V;IRR;SG;1
a	pa	V;IRR;SG;1+INCL
bi	nubi	V;IRR;PC;2
ntji	tje	V;IRR;SG;1+INCL;PST
i	nuyu	V;IRR;PL;2
ba	ngube	V;PC;1;PST
be	ngubena	V;IRR;PC;1;PST
mu	kumuy	V;IRR;PL;3;PST
bu	kubu	V;IRR;PC;3
nu	na	V;SG;3;PST
nu	thuni	V;IRR;SG;1+INCL;PST
rra	nira	V;IRR;PL;2
na	pinnangi	V;IRR;PC;3;PST
ba	nube	V;PL;2;PST
ma	nume	V;PC;2;PST
e	tjena	V;SG;1+INCL;PST
la	pulle	V;PL;3;PST
rra	pe	V;PC;3;PST
rru	ngurrini	V;SG;1;PST
nu	punnungam	V;PL;3;non{FUT}
ngi	nungana	V;IRR;PC;2;PST
be	ngubem	V;PL;1;non{FUT}
nga	pinga	V;IRR;PC;3;PST
rdu	nuddi	V;IRR;PL;2;PST
ngu	ngungan	V;SG;1;non{FUT}
a	na	V;IRR;PL;2
bi	bina	V;SG;1;PST
a	ngarrani	V;PL;1;PST
nu	nunna	V;IRR;PC;2
e	tjem	V;SG;1+INCL;non{FUT}
a	narrane	V;PC;2;PST
la	tjilangi	V;IRR;SG;1+INCL;PST
i	pirrine	V;PC;3;PST
ma	ngama	V;IRR;SG;1
mi	nim	V;SG;2;non{FUT}
ba	bam	V;SG;1;non{FUT}
ma	numi	V;IRR;PC;2;PST
mi	ngumi	V;IRR;PC;1
rri	niri	V;IRR;PC;2
bi	bim	V;SG;3;non{FUT}
rru	numpan	V;PL;2;non{FUT}
be	dena	V;SG;2;PST
buy	thubam	V;SG;1+INCL;non{FUT}
ye	nguy	V;IRR;SG;1
ngu	thunguni	V;SG;2;PST
ngu	thungu	V;IRR;SG;2
ntha	nintha	V;IRR;PL;2
e	ngena	V;SG;1;PST
bi	pubina	V;PL;3;PST
ntha	nginthanyi	V;PL;1;PST
ngu	ngungu	V;IRR;SG;1
e	ngerrem	V;PL;1;non{FUT}
ba	be	V;IRR;SG;1;PST
rru	thurran	V;SG;1+INCL;non{FUT}
rru	thurri	V;IRR;SG;1+INCL;PST
rdu	nuddene	V;PC;2;PST
rri	ngirrini	V;IRR;SG;1;PST
ngi	pungana	V;IRR;PC;3;PST
rdi	nuddana	V;PL;2;PST
rra	nira	V;IRR;PC;2
la	kila	V;IRR;SG;3
li	tjilingi	V;IRR;SG;2;PST
i	nirrini	V;PL;2;PST
la	nilla	V;IRR;PL;2
ba	de	V;IRR;SG;2;PST
buy	nubana	V;PL;2;PST
mi	mi	V;IRR;SG;3
ye	kuy	V;IRR;SG;3
e	ke	V;IRR;PL;3
la	pulle	V;IRR;PC;3;PST
e	dem	V;SG;3;non{FUT}
be	nube	V;IRR;PL;2
ntha	tjinthangi	V;IRR;SG;2;PST
na	nginnangi	V;IRR;PC;1;PST
rra	pirangi	V;IRR;PL;3;PST
ntha	kintha	V;IRR;SG;3
i	yungi	V;IRR;SG;3;PST
be	bem	V;SG;3;non{FUT}
na	tjinanga	V;SG;1+INCL;PST
la	ngulam	V;SG;1;non{FUT}
ntha	ngantjim	V;SG;1;non{FUT}
ya	ngan	V;SG;1;non{FUT}
ngu	ngungan	V;PL;1;non{FUT}
e	nerrena	V;PL;2;PST
nga	pingam	V;PL;3;non{FUT}
ni	nganam	V;SG;1;non{FUT}
li	nilli	V;IRR;PC;2
a	ka	V;IRR;SG;3
ngi	ngungana	V;IRR;PC;1;PST
rru	thurrini	V;SG;2;PST
la	ngula	V;IRR;SG;1
rdi	nudde	V;IRR;PC;2
ntji	nga	V;IRR;PC;1
be	ngubena	V;IRR;PL;1;PST
ba	pube	V;PC;3;PST
rra	ngarrim	V;SG;1;non{FUT}
rra	tjirrangi	V;IRR;SG;1+INCL;PST
ngi	nungana	V;IRR;PL;2;PST
ngu	punge	V;IRR;PC;3;PST
rdi	puddana	V;PC;3;PST
nga	pinga	V;PL;3;PST
i	nirrine	V;IRR;PC;2;PST
e	tjena	V;IRR;SG;1+INCL;PST
ngu	nungu	V;IRR;PL;2;PST
ye	nuyem	V;PL;2;non{FUT}
ma	numi	V;IRR;PL;2;PST
bu	thubuni	V;SG;1+INCL;PST
be	pubena	V;IRR;PL;3;PST
bi	pubina	V;IRR;PC;3;PST
rru	puyi	V;IRR;PL;3;PST
na	kinna	V;IRR;PC;3
rdu	nudda	V;IRR;PC;2
buy	nubana	V;IRR;PL;2;PST
la	nilla	V;IRR;PC;2
rdi	puddam	V;PL;3;non{FUT}
ngu	nungan	V;PL;2;non{FUT}
la	pila	V;IRR;SG;1+INCL
la	nulla	V;IRR;PC;2
rdu	nguddini	V;PL;1;PST
bu	nubu	V;IRR;PL;2
ye	ngana	V;IRR;SG;1;PST
nga	nge	V;IRR;PC;1
la	thule	V;IRR;SG;1+INCL;PST
nu	ngunni	V;PL;1;PST
ntji	ngantji	V;SG;1;PST
nu	nunna	V;PC;2;PST
li	kili	V;IRR;SG;3
rdi	nuddana	V;PC;2;PST
ngi	thungana	V;SG;1+INCL;PST
i	yibim	V;SG;3;non{FUT}
ba	nubam	V;PL;2;non{FUT}
