snøleopard	snøleopardane	N;DEF;PL
namibiar	namibiarane	N;DEF;PL
utdanning	utdanningane	N;DEF;PL
arkitektonisk	arkitektoniske	N;DEF;SG+PL
tryllestav	tryllestavane	N;DEF;PL
påskeegg	påskeegg	N;NDEF;PL
filosof	filosofane	N;DEF;PL
hjaltlending	hjaltlendingar	N;NDEF;PL
skjørt	skjørta	N;DEF;PL
hane	hanane	N;DEF;PL
gaffel	gaflane	N;DEF;PL
angolan	angolanar	N;NDEF;PL
vurdering	vurderingane	N;DEF;PL
smil	smila	N;DEF;PL
tomme	tommen	N;DEF;SG
skatt	skatten	N;DEF;SG
oppslagsverk	oppslagsverk	N;NDEF;PL
påskelilje	påskeliljer	N;NDEF;PL
stadion	stadionet	N;DEF;SG
måtte	måtte	V;PST
blodhund	blodhunden	N;DEF;SG
dobbelt	dobbelt	ADJ;NEUT;SG
fantasi	fantasiar	N;NDEF;PL
brun	brune	N;DEF;SG+PL
papuan	papuanar	N;NDEF;PL
bergmann	bergmennene	N;DEF;PL
sludd	sluddet	N;DEF;SG
frosk	frosken	N;DEF;SG
pilot	pilotane	N;DEF;PL
malm	malmane	N;DEF;PL
sukkerroe	sukkerroar	N;NDEF;PL
sørleg	sørleg	ADJ;NDEF;SG
plan	plane	N;DEF;SG+PL
svak	svakast	ADJ;SPRL;NDEF
bolivianar	bolivianarar	N;NDEF;PL
kalkstein	kalksteinar	N;NDEF;PL
stork	storkar	N;NDEF;PL
blodoverføring	blodoverføringa	N;DEF;SG
brenne	brennast	V;NFIN;PASS
maksimal	maksimalt	ADJ;NEUT;SG
misjonær	misjonærar	N;NDEF;PL
støpsel	støpselet	N;DEF;SG
brudgom	brudgommen	N;DEF;SG
afrikansk	afrikanske	N;DEF;SG+PL
grunnleggjande	grunnleggjande	ADJ;SG+PL
gjest	gjestar	N;NDEF;PL
fly	flyet	N;DEF;SG
granitt	granittar	N;NDEF;PL
orrhøne	orrhøner	N;NDEF;PL
hekka	hekkar	V;PRS
butikk	butikkar	N;NDEF;PL
synål	synåler	N;NDEF;PL
ettermiddag	ettermiddagen	N;DEF;SG
sanmarinar	sanmarinaren	N;DEF;SG
tam	tamme	N;DEF;SG+PL
monolog	monologane	N;DEF;PL
frukttre	frukttre	N;NDEF;PL
klubb	klubben	N;DEF;SG
særleg	særlegaste	ADJ;SPRL;DEF
søkje	søkte	V;PST
tenke	tenk	V;IMP
falk	falkane	N;DEF;PL
risiko	risikoar	N;NDEF;PL
anonym	anonymt	ADJ;NEUT;SG
kiropraktor	kiropraktorane	N;DEF;PL
barbadar	barbadarane	N;DEF;PL
kjend	kjent	ADJ;NEUT
radio	radioen	N;DEF;SG
talskvinne	talskvinna	N;DEF;SG
bringebær	bringebær	N;NDEF;PL
komorar	komorarane	N;DEF;PL
rulleskøyte	rulleskøyta	N;DEF;SG
keisam	keisamt	ADJ;NEUT
spindelvev	spindelvevane	N;DEF;PL
nakke	nakkane	N;DEF;PL
blodhund	blodhundar	N;NDEF;PL
hundreår	hundreåra	N;DEF;PL
sirkelsag	sirkelsager	N;NDEF;PL
variant	variantar	N;NDEF;PL
blodtrykk	blodtrykk	N;NDEF;PL
osean	osean	N;NDEF;PL
avgjerd	avgjerdene	N;DEF;PL
ballkjole	ballkjolar	N;NDEF;PL
passform	passformene	N;DEF;PL
vete	visste	V;PST
sjukdom	sjukdommar	N;NDEF;PL
ur	ur	N;NDEF;PL
bardage	bardagen	N;DEF;SG
jiddisch	jiddische	N;DEF;SG+PL
reservedel	reservedelar	N;NDEF;PL
rik	rike	N;DEF;SG+PL
årelang	årelangt	ADJ;NEUT;SG
angripa	angreip	V;PST
atrofi	atrofien	N;DEF;SG
førarkort	førarkort	N;NDEF;PL
grimase	grimasen	N;DEF;SG
setning	setningar	N;NDEF;PL
arbeidstakar	arbeidstakaren	N;DEF;SG
tomatpuré	tomatpuréen	N;DEF;SG
ringje	ringjer	V;PRS
edelmetall	edelmetallet	N;DEF;SG
konsis	konsist	ADJ;NEUT;SG
lomme	lommene	N;DEF;PL
sirkus	sirkus	N;NDEF;PL
ekvator	ekvatoren	N;DEF;SG
vestleg	vestleg	ADJ;NDEF;SG
maldiv	maldiven	N;DEF;SG
AUF-ar	AUF-arar	N;NDEF;PL
istid	istida	N;DEF;SG
gamalengelsk	gamalengelsken	N;DEF;SG
porøs	porøse	N;DEF;SG+PL
angra	angra	V;IMP
ungdom	ungdomar	N;NDEF;PL
pengeskap	pengeskapet	N;DEF;SG
flyfrakt	flyfrakta	N;DEF;SG
plog	plogar	N;NDEF;PL
svarttrost	svarttrostane	N;DEF;PL
biometrisk	biometrisk	ADJ;NEUT;SG
salme	salmar	N;NDEF;PL
taktfull	taktfullt	ADJ;NEUT;SG
apekatt	apekatten	N;DEF;SG
skodespelar	skodespelaren	N;DEF;SG
troll	trollet	N;DEF;SG
følge	følger	V;PRS
stasjonsvogn	stasjonsvogner	N;NDEF;PL
hyse	hyser	N;NDEF;PL
sentrifugalkraft	sentrifugalkrafta	N;DEF;SG
søka	søkast	V;NFIN;PASS
mangel	manglane	N;DEF;PL
detta	dett	V;IMP
malaysiar	malaysiaren	N;DEF;SG
angolanar	angolanaren	N;DEF;SG
sjø	sjøen	N;DEF;SG
utsyn	utsynet	N;DEF;SG
bachelorgrad	bachelorgraden	N;DEF;SG
kattedyr	kattedyr	N;NDEF;PL
potensiell	potensielt	ADJ;NEUT;SG
svensk	svenske	N;DEF;SG+PL
tanke	tanken	N;DEF;SG
guvernør	guvernørane	N;DEF;PL
verdifull	verdifulle	N;DEF;SG+PL
endeleg	endelegast	ADJ;SPRL;NDEF
avhengig	avhengige	N;DEF;SG+PL
imponera	imponer	V;IMP
ikon	ikona	N;DEF;PL
antropologi	antropologien	N;DEF;SG
debut	debuten	N;DEF;SG
spela	spelar	V;PRS
senator	senatoren	N;DEF;SG
støyttann	støyttennene	N;DEF;PL
grunn	grunnar	N;NDEF;PL
jordanar	jordanaren	N;DEF;SG
langfredag	langfredagane	N;DEF;PL
kvile	kviler	V;PRS
psykiatri	psykiatrien	N;DEF;SG
sone	sona	N;DEF;SG
tog	toget	N;DEF;SG
nase	nasar	V;PRS
slå	slår	V;PRS
T-bane	T-banene	N;DEF;PL
mexicanar	mexicanarane	N;DEF;PL
byggje	byggjer	V;PRS
meteorolog	meteorologane	N;DEF;PL
lugar	lugaren	N;DEF;SG
løfte	løfte	N;NDEF;PL
korn	kornet	N;DEF;SG
slips	slipsa	N;DEF;PL
flykropp	flykroppar	N;NDEF;PL
ost	ostane	N;DEF;PL
oppvask	oppvasket	N;DEF;SG
makrell	makrellen	N;DEF;SG
hakekross	hakekrossen	N;DEF;SG
stadion	stadiona	N;DEF;PL
gjennomsnitt	gjennomsnittet	N;DEF;SG
appell	appellane	N;DEF;PL
avgang	avgangar	N;NDEF;PL
multiplikasjon	multiplikasjonane	N;DEF;PL
musikal	musikalane	N;DEF;PL
høg	høgst	ADJ;SPRL;NDEF
orsaking	orsakingar	N;NDEF;PL
revolver	revolverane	N;DEF;PL
psykiater	psykiaterane	N;DEF;PL
levetid	levetider	N;NDEF;PL
video	videoane	N;DEF;PL
utslette	utsletta	V;PST
tittel	titlar	N;NDEF;PL
kalium	kaliumet	N;DEF;SG
alvorleg	alvorlegare	ADJ;CMPR
bangladeshar	bangladesharar	N;NDEF;PL
fløyte	fløyter	N;NDEF;PL
hemn	hemnane	N;DEF;PL
variasjon	variasjonar	N;NDEF;PL
mørke	mørke	N;NDEF;PL
nederlag	nederlaga	N;DEF;PL
univers	universa	N;DEF;PL
søsken	søskenet	N;DEF;SG
avstand	avstanden	N;DEF;SG
kroatisk	kroatisken	N;DEF;SG
væpne	væpnar	V;PRS
indonesiar	indonesiarane	N;DEF;PL
skomakar	skomakarar	N;NDEF;PL
jomfruhinne	jomfruhinna	N;DEF;SG
historisk	historiske	N;DEF;SG+PL
angripa	angripast	V;NFIN;PASS
kor	kor	N;NDEF;PL
lås	låset	N;DEF;SG
tallerken	tallerkenane	N;DEF;PL
postnummer	postnummer	N;NDEF;PL
dildo	dildoen	N;DEF;SG
premiere	premierar	N;NDEF;PL
note	noten	N;DEF;SG
bibliotek	biblioteket	N;DEF;SG
alpakka	alpakkaen	N;DEF;SG
militær	militære	N;DEF;SG+PL
muskulær	muskulære	N;DEF;SG+PL
viljug	viljugaste	ADJ;SPRL;DEF
kake	kaker	N;NDEF;PL
amatør	amatøren	N;DEF;SG
stavemåte	stavemåten	N;DEF;SG
savanne	savannane	N;DEF;PL
rund	runde	N;DEF;SG+PL
dal	dalane	N;DEF;PL
fjern	fjernast	ADJ;SPRL;NDEF
fasinera	fasinerast	V;NFIN;PASS
nederlendar	nederlendaren	N;DEF;SG
rwandar	rwandarane	N;DEF;PL
nyttelast	nyttelaster	N;NDEF;PL
rekreasjon	rekreasjonen	N;DEF;SG
verna	vernar	V;PRS
klasserom	klasserom	N;NDEF;PL
underart	underartar	N;NDEF;PL
latterleg	latterlegaste	ADJ;SPRL;DEF
smal	smalt	ADJ;NEUT;SG
lærepeng	lærepengen	N;DEF;SG
plattform	plattforma	N;DEF;SG
hugenott	hugenottane	N;DEF;PL
grunnskole	grunnskolar	N;NDEF;PL
tommelfingerregel	tommelfingerreglar	N;NDEF;PL
land	landa	N;DEF;PL
tryllestav	tryllestaven	N;DEF;SG
handballspelar	handballspelarane	N;DEF;PL
felles	felles	ADJ;SG+PL
halvfull	halvfullt	ADJ;NEUT;SG
tomat	tomaten	N;DEF;SG
fotball	fotballane	N;DEF;PL
bølgelengde	bølgelengda	N;DEF;SG
alder	aldrar	N;NDEF;PL
tastatur	tastaturet	N;DEF;SG
kule	kula	N;DEF;SG
nabolag	nabolaga	N;DEF;PL
daude	daudar	N;NDEF;PL
pulver	pulvera	N;DEF;PL
fengd	fengder	N;NDEF;PL
data	data	N;NDEF;PL
innsjå	innsåg	V;PST
moldovar	moldovaren	N;DEF;SG
ræv	rævene	N;DEF;PL
fanatikar	fanatikarar	N;NDEF;PL
oksid	oksidet	N;DEF;SG
zambisk	zambisk	ADJ;NEUT;SG
bikini	bikinien	N;DEF;SG
samlar	samlarar	N;NDEF;PL
paraguayan	paraguayanane	N;DEF;PL
blokk	blokker	N;NDEF;PL
framtid	framtidene	N;DEF;PL
væske	væska	N;DEF;SG
tru	truast	V;NFIN;PASS
bilist	bilistar	N;NDEF;PL
helikopter	helikopter	N;NDEF;PL
tuvalar	tuvalarane	N;DEF;PL
konversasjon	konversasjonar	N;NDEF;PL
jernbane	jernbanane	N;DEF;PL
midnattssol	midnattssola	N;DEF;SG
hær	hærar	N;NDEF;PL
terapeutisk	terapeutisk	ADJ;NEUT;SG
is	isane	N;DEF;PL
tidleg	tidlegast	ADJ;SPRL;NDEF
turkis	turkise	N;DEF;SG+PL
bueining	bueininga	N;DEF;SG
a	a-ane	N;DEF;PL
minutt	minuttane	N;DEF;PL
krav	krava	N;DEF;PL
komet	kometen	N;DEF;SG
tyrkisk	tyrkisken	N;DEF;SG
laurbærblad	laurbærbladet	N;DEF;SG
raudrev	raudrevar	N;NDEF;PL
åtseletar	åtseletarar	N;NDEF;PL
besteforelder	besteforeldra	N;DEF;PL
majoritet	majoritetar	N;NDEF;PL
etternamn	etternamna	N;DEF;PL
matematisk	matematisk	ADJ;NEUT;SG
myrk	myrk	ADJ;MASC+FEM
kolsvart	kolsvarte	N;DEF;SG+PL
skrivebord	skriveborda	N;DEF;PL
besøkje	besøkte	V;PST
islending	islendingen	N;DEF;SG
kreasjon	kreasjonen	N;DEF;SG
spanjol	spanjolane	N;DEF;PL
kystlinje	kystlinja	N;DEF;SG
historie	historier	N;NDEF;PL
religiøs	religiøs	ADJ;MASC+FEM
gøyme	gøym	V;IMP
mørke	mørket	N;DEF;SG
innehalde	innehaldast	V;NFIN;PASS
sierraleonar	sierraleonaren	N;DEF;SG
orsake	orsaka	V;PST
fartsgrense	fartsgrensa	N;DEF;SG
målmann	målmennene	N;DEF;PL
bosnisk	bosniske	N;DEF;SG+PL
påskelilje	påskelilja	N;DEF;SG
valuta	valutaene	N;DEF;PL
sivil	sivilt	ADJ;NEUT
lommelerke	lommelerka	N;DEF;SG
frakt	frakter	N;NDEF;PL
angolan	angolanen	N;DEF;SG
blå	blåare	ADJ;CMPR
rivjern	rivjerna	N;DEF;PL
tradisjon	tradisjonane	N;DEF;PL
gisseltakar	gisseltakaren	N;DEF;SG
albino	albinoane	N;DEF;PL
delta	delta	V;IMP
skugge	skuggen	N;DEF;SG
kjæraste	kjærastar	N;NDEF;PL
bremsepedal	bremsepedalar	N;NDEF;PL
klorid	klorida	N;DEF;PL
kald	kald	ADJ;MASC+FEM
kassett	kassettar	N;NDEF;PL
ferdast	ferdast	V;IMP
hanne	hannar	N;NDEF;PL
bjart	bjarte	N;DEF;SG+PL
afrikansk	afrikansk	ADJ;FEM
cubanar	cubanaren	N;DEF;SG
kniv	knivane	N;DEF;PL
kunstgalleri	kunstgalleria	N;DEF;PL
liggje	ligg	V;PRS
husarbeid	husarbeidet	N;DEF;SG
vest	vesten	N;DEF;SG
folkemord	folkemorda	N;DEF;PL
pasient	pasientane	N;DEF;PL
ask	askar	N;NDEF;PL
mannfolk	mannfolket	N;DEF;SG
hårbørste	hårbørstar	N;NDEF;PL
is	isen	N;DEF;SG
guineanar	guineanaren	N;DEF;SG
fossil	fossila	N;DEF;PL
serbisk	serbisk	ADJ;NEUT;SG
marokkan	marokkanar	N;NDEF;PL
etymolog	etymologen	N;DEF;SG
maksime	maksimar	N;NDEF;PL
ull	ulla	N;DEF;SG
vandra	vandra	V;PST
sjølvstende	sjølvstendet	N;DEF;SG
spiss	spissast	ADJ;SPRL;NDEF
meine	meinte	V;PST
nomadisk	nomadisk	ADJ;NEUT;SG
vokal	vokalane	N;DEF;PL
søt	søtaste	ADJ;SPRL;DEF
kollega	kollegaane	N;DEF;PL
hue	huene	N;DEF;PL
pære	pærer	N;NDEF;PL
saft	safter	N;NDEF;PL
fylgja	fylg	V;IMP
eksponering	eksponeringane	N;DEF;PL
sabbat	sabbaten	N;DEF;SG
vibrasjon	vibrasjonane	N;DEF;PL
larve	larven	N;DEF;SG
påske	påskene	N;DEF;PL
falk	falken	N;DEF;SG
formue	formuar	N;NDEF;PL
aluminiumsfolie	aluminiumsfoliar	N;NDEF;PL
hegre	hegren	N;DEF;SG
mål	målet	N;DEF;SG
geolog	geologane	N;DEF;PL
AUF-ar	AUF-aren	N;DEF;SG
søye	søyene	N;DEF;PL
brur	brurer	N;NDEF;PL
sump	sumpen	N;DEF;SG
srilankar	srilankarane	N;DEF;PL
kynisk	kynisk	ADJ;NDEF;SG
pengeskap	pengeskapa	N;DEF;PL
kakerlakk	kakerlakkane	N;DEF;PL
utsyn	utsyn	N;NDEF;PL
flyselskap	flyselskapa	N;DEF;PL
bad	badet	N;DEF;SG
lov	loven	N;DEF;SG
punktum	punktum	N;NDEF;PL
tyggja	tygg	V;IMP
byste	bystar	N;NDEF;PL
malm	malmar	N;NDEF;PL
bulevard	bulevarden	N;DEF;SG
pandemisk	pandemisk	ADJ;NEUT;SG
lengsel	lengslane	N;DEF;PL
bukse	buksa	N;DEF;SG
aksess	aksessen	N;DEF;SG
lys	lysa	N;DEF;PL
vrak	vrak	N;NDEF;PL
sloven	slovenar	N;NDEF;PL
vare	varer	N;NDEF;PL
objekt	objektet	N;DEF;SG
lager	lagera	N;DEF;PL
montenegrinar	montenegrinarane	N;DEF;PL
luxemburgar	luxemburgaren	N;DEF;SG
dansk	dansken	N;DEF;SG
pla	plar	V;PRS
naturlov	naturlovar	N;NDEF;PL
landkrabbe	landkrabbane	N;DEF;PL
filippinar	filippinarane	N;DEF;PL
kafé	kafear	N;NDEF;PL
lån	låna	N;DEF;PL
moské	moskéar	N;NDEF;PL
røykja	røykjer	V;PRS
argentinar	argentinarar	N;NDEF;PL
tommel	tommelen	N;DEF;SG
bikini	bikiniar	N;NDEF;PL
skikkeleg	skikkelegaste	ADJ;SPRL;DEF
syngja	syngjast	V;NFIN;PASS
behalda	behald	V;IMP
kambodsjan	kambodsjanar	N;NDEF;PL
forsvare	forsvare	V;IMP
rekord	rekordar	N;NDEF;PL
skotte	skottane	N;DEF;PL
kontekst	kontekstene	N;DEF;PL
sjøfugl	sjøfuglar	N;NDEF;PL
brunbjørn	brunbjørnar	N;NDEF;PL
skugga	skugga	V;PST
eksplosjon	eksplosjonane	N;DEF;PL
tunne	tunna	N;DEF;SG
kvila	kvil	V;IMP
bygd	bygda	N;DEF;SG
celle	cellene	N;DEF;PL
varsam	varsame	N;DEF;SG+PL
raud	raud	ADJ;MASC+FEM
kone	konene	N;DEF;PL
mikrobiologi	mikrobiologien	N;DEF;SG
tonn	tonna	N;DEF;PL
interjeksjon	interjeksjonar	N;NDEF;PL
antiguan	antiguanane	N;DEF;PL
streng	strengen	N;DEF;SG
obo	oboane	N;DEF;PL
hyperbol	hyperbolar	N;NDEF;PL
kommandør	kommandørane	N;DEF;PL
steinkast	steinkasta	N;DEF;PL
dreiemoment	dreiemomentet	N;DEF;SG
pronomen	pronomen	N;NDEF;PL
grossist	grossistar	N;NDEF;PL
objektiv	objektivet	N;DEF;SG
variasjon	variasjonane	N;DEF;PL
tekst	tekstane	N;DEF;PL
burmesar	burmesaren	N;DEF;SG
oppdrag	oppdraget	N;DEF;SG
målmann	målmenn	N;NDEF;PL
koloni	koloniar	N;NDEF;PL
folkerik	folkerike	N;DEF;SG+PL
alkohol	alkoholane	N;DEF;PL
falk	falkar	N;NDEF;PL
skate	skatene	N;DEF;PL
brorskap	brorskapane	N;DEF;PL
esel	esel	N;NDEF;PL
meny	menyane	N;NDEF;PL
løfte	løftet	N;DEF;SG
kjernefysikk	kjernefysikken	N;DEF;SG
borgarkrig	borgarkrigar	N;NDEF;PL
bendelorm	bendelormane	N;DEF;PL
sandstrand	sandstrender	N;NDEF;PL
nøtteknekkjar	nøtteknekkjaren	N;DEF;SG
mineral	mineralet	N;DEF;SG
ny	nytt	ADJ;NEUT;SG
generasjon	generasjonane	N;DEF;PL
utforming	utformingar	N;NDEF;PL
rektangel	rektangel	N;NDEF;PL
liggje	ligg	V;IMP
kanon	kanonen	N;DEF;SG
veranda	verandaer	N;NDEF;PL
aforisme	aforismar	N;NDEF;PL
ektemann	ektemannen	N;DEF;SG
venleg	venlege	N;DEF;SG+PL
intim	intimt	ADJ;NEUT;SG
spele	spelar	V;PRS
materiale	materiala	N;DEF;PL
einskap	einskapen	N;DEF;SG
syltetøy	syltetøyet	N;DEF;SG
god	gode	N;DEF;SG+PL
andorran	andorranar	N;NDEF;PL
ligge	liggast	V;NFIN;PASS
verdskrig	verdskrigen	N;DEF;SG
uventa	uventa	ADJ;SG+PL
finne	finnane	N;DEF;PL
maske	masker	N;NDEF;PL
hemmeleg	hemmelege	N;DEF;SG+PL
teskei	teskeiene	N;DEF;PL
ukrainsk	ukrainsk	ADJ;NEUT;SG
lager	lageret	N;DEF;SG
duge	dug	V;IMP
vekka	vekte	V;PST
bibliotek	bibliotek	N;NDEF;PL
skjere	skjer	V;PRS
vegetasjon	vegetasjonane	N;DEF;PL
emirat	emiratet	N;DEF;SG
kongle	konglene	N;DEF;PL
krav	krav	N;NDEF;PL
senegalesar	senegalesaren	N;DEF;SG
hjul	hjul	N;NDEF;PL
lett	lettaste	ADJ;SPRL;DEF
fanatikar	fanatikarane	N;DEF;PL
eiga	eig	V;PRS
delegasjon	delegasjonane	N;DEF;PL
villsvin	villsvina	N;DEF;PL
moped	mopedane	N;DEF;PL
bombe	bombar	V;PRS
ubehageleg	ubehagelegast	ADJ;SPRL;NDEF
belgiar	belgiaren	N;DEF;SG
helgen	helgenane	N;DEF;PL
kamuflasje	kamuflasjen	N;DEF;SG
hugsa	hugsar	V;PRS
lærling	lærlingar	N;NDEF;PL
kome	komast	V;NFIN;PASS
lukkeleg	lukkeleg	ADJ;NDEF;SG
ansvar	ansvara	N;DEF;PL
byrjing	byrjingar	N;NDEF;PL
kosovar	kosovarar	N;NDEF;PL
notatbok	notatbøkene	N;DEF;PL
botswanar	botswanaren	N;DEF;SG
have	hadde	V;PST
oppreist	oppreist	ADJ;NDEF;SG
saftig	saftige	N;DEF;SG+PL
godkjenning	godkjenninga	N;DEF;SG
umogeleg	umogelegaste	ADJ;SPRL;DEF
vestleg	vestlegaste	ADJ;SPRL;DEF
irakar	irakarane	N;DEF;PL
bær	bær	N;NDEF;PL
diplomat	diplomatane	N;DEF;PL
uroleg	uroleg	ADJ;NDEF;SG
koreansk	koreanske	N;DEF;SG+PL
sikte	sikte	N;NDEF;PL
hysterisk	hysterisk	ADJ;NEUT;SG
kafé	kaféar	N;NDEF;PL
skilta	skiltar	V;PRS
nynorskbrukar	nynorskbrukarane	N;DEF;PL
røyskatt	røyskattane	N;DEF;PL
bestikk	bestikk	N;NDEF;PL
sjokolade	sjokoladen	N;DEF;SG
søke	søker	V;PRS
hand	hendene	N;DEF;PL
avsnitt	avsnitta	N;DEF;PL
kromosom	kromosom	N;NDEF;PL
encyklopedi	encyklopediar	N;NDEF;PL
spela	spela	V;IMP
kosedyr	kosedyret	N;DEF;SG
styrehus	styrehus	N;NDEF;PL
grasiøs	grasiøse	N;DEF;SG+PL
drap	drapa	N;DEF;PL
moské	moskeane	N;DEF;PL
oppreist	oppreistar	N;NDEF;PL
merkeleg	merkeleg	ADJ;NDEF;SG
etiopiar	etiopiaren	N;DEF;SG
selje	seljast	V;NFIN;PASS
gabonar	gabonaren	N;DEF;SG
diamant	diamantar	N;NDEF;PL
endring	endringa	N;DEF;SG
galoppbane	galoppbanene	N;DEF;PL
åre	åra	N;DEF;SG
kiosk	kioskane	N;DEF;PL
brannmur	brannmurane	N;DEF;PL
adressat	adressatane	N;DEF;PL
lampeskjerm	lampeskjermen	N;DEF;SG
syntese	syntesen	N;DEF;SG
tenar	tenarane	N;DEF;PL
adventskalender	adventskalenderen	N;DEF;SG
undulat	undulatane	N;DEF;PL
ta	tar	V;PRS
samleie	samleiet	N;DEF;SG
rumenar	rumenarar	N;NDEF;PL
nettstad	nettstadar	N;NDEF;PL
sitta	sat	V;PST
fluor	fluoret	N;DEF;SG
rakett	rakettar	N;NDEF;PL
brannbil	brannbilen	N;DEF;SG
kattunge	kattungen	N;DEF;SG
koseleg	koselegare	ADJ;CMPR
algoritme	algoritmar	N;NDEF;PL
sår	såra	N;DEF;PL
dødsstraff	dødsstraffa	N;DEF;SG
spreie	spreiast	V;NFIN;PASS
mobiltelefon	mobiltelefonar	N;NDEF;PL
sitte	sat	V;PST
tunne	tunna	V;PST
fly	fly	N;NDEF;PL
trompet	trompeten	N;DEF;SG
framgang	framgangane	N;DEF;PL
kjøpmann	kjøpmenn	N;NDEF;PL
estetikk	estetikkar	N;NDEF;PL
brenna	brennast	V;NFIN;PASS
erme	erma	N;DEF;PL
lengdegrad	lengdegraden	N;DEF;SG
sjuk	sjuk	ADJ;MASC+FEM
fortelja	fortel	V;IMP
edelstein	edelsteinen	N;DEF;SG
samleie	samleia	N;DEF;PL
konversasjon	konversasjonen	N;DEF;SG
skorpion	skorpionane	N;DEF;PL
symaskin	symaskinene	N;DEF;PL
silisium	silisiumet	N;DEF;SG
braut	brautene	N;DEF;PL
tadsjikar	tadsjikaren	N;DEF;SG
leilegheit	leilegheita	N;DEF;SG
besetning	besetningen	N;DEF;SG
opphav	opphava	N;DEF;PL
regnskog	regnskogen	N;DEF;SG
posthum	posthumt	ADJ;NEUT;SG
alpakka	alpakkaar	N;NDEF;PL
kven	kvener	N;NDEF;PL
betra	betra	V;PST
ligge	ligg	V;PRS
oppvaskmaskin	oppvaskmaskinene	N;DEF;PL
veng	vengar	N;NDEF;PL
tyggje	togg	V;PST
sabotasje	sabotasjane	N;DEF;PL
støvel	støvlar	N;NDEF;PL
besetning	besetningane	N;DEF;PL
potte	potter	N;NDEF;PL
stryking	strykingar	N;NDEF;PL
openberring	openberringar	N;NDEF;PL
mumie	mumiar	N;NDEF;PL
tena	tenast	V;NFIN;PASS
veide	veid	V;IMP
tante	tantene	N;DEF;PL
sjå	sjåast	V;NFIN;PASS
frukttre	frukttra	N;DEF;PL
ynskje	ynskte	V;PST
lygn	lygner	N;NDEF;PL
veskenappar	veskenapparane	N;DEF;PL
stilig	stilig	ADJ;NEUT;SG
voks	voks	N;NDEF;PL
sum	sum	N;NDEF;PL
sandal	sandalen	N;DEF;SG
heite	heitte	V;PST
tidssone	tidssona	N;DEF;SG
slovak	slovakar	N;NDEF;PL
motstand	motstandane	N;DEF;PL
fysisk	fysisk	ADJ;NEUT;SG
ideell	ideelle	N;DEF;SG+PL
naturleg	naturlegast	ADJ;SPRL;NDEF
klo	kloa	N;DEF;SG
basilikum	basilikumen	N;DEF;SG
kusine	kusina	N;DEF;SG
definere	definerte	V;PST
logo	logoen	N;DEF;SG
sovjetar	sovjetarane	N;DEF;PL
arkaisk	arkaiske	N;DEF;SG+PL
tredjedel	tredjedelar	N;NDEF;PL
tjukk	tjukkast	ADJ;SPRL;NDEF
grov	grovaste	ADJ;SPRL;DEF
komité	komitéen	N;DEF;SG
uformell	uformelt	ADJ;NEUT;SG
trene	trenast	V;NFIN;PASS
klegg	klegger	N;NDEF;PL
bere	bar	V;PST
nyre	nyra	N;DEF;PL
lønn	lønnane	N;DEF;PL
ljos	ljos	ADJ;MASC+FEM
nederlandsk	nederlandsk	ADJ;NEUT;SG
kilometer	kilometeren	N;DEF;SG
skrive	skreiv	V;PST
treverk	treverket	N;DEF;SG
nyttårsdag	nyttårsdagar	N;NDEF;PL
køyre	køyr	V;IMP
kubanar	kubanarane	N;DEF;PL
påverknad	påverknaden	N;DEF;SG
busk	buskar	N;NDEF;PL
gåve	gåvene	N;DEF;PL
masse	massen	N;DEF;SG
tungetale	tungetalen	N;DEF;SG
fantastisk	fantastiske	N;DEF;SG+PL
snø	snøen	N;DEF;SG
siger	sigeren	N;DEF;SG
sau	sauane	N;DEF;PL
krabbe	krabbar	N;NDEF;PL
splitt	splitten	N;DEF;SG
tilstand	tilstanden	N;DEF;SG
fort	fort	N;NDEF;PL
halvøy	halvøyar	N;NDEF;PL
herleg	herlege	N;DEF;SG+PL
ugandar	ugandaren	N;DEF;SG
terrorangrep	terrorangrepet	N;DEF;SG
sau	sauar	N;NDEF;PL
lag	laga	N;DEF;PL
sterk	sterkt	ADJ;NEUT
lastebilsjåfør	lastebilsjåførane	N;DEF;PL
jaktar	jaktarar	N;NDEF;PL
diaré	diareen	N;DEF;SG
stele	stelar	N;NDEF;PL
ljota	lyt	V;PRS
veta	vetast	V;NFIN;PASS
ny	nye	N;DEF;SG+PL
verte	vert	V;IMP
tannlege	tannlegar	N;NDEF;PL
serviett	serviettane	N;DEF;PL
formel	formelen	N;DEF;SG
tanzaniar	tanzaniaren	N;DEF;SG
dekkje	dekk	V;IMP
superlativ	superlativen	N;DEF;SG
kontrolltårn	kontrolltårn	N;NDEF;PL
overleva	overlever	V;PRS
arkitekt	arkitektane	N;DEF;PL
dataspel	dataspela	N;DEF;PL
potteplante	potteplantene	N;DEF;PL
rykte	ryktet	N;DEF;SG
nasjon	nasjonar	N;NDEF;PL
sirup	sirupane	N;DEF;PL
øyre	øyren	N;DEF;SG
mirakel	mirakel	N;NDEF;PL
fallskjerm	fallskjermen	N;DEF;SG
militærkupp	militærkupp	N;NDEF;PL
abdikasjon	abdikasjonane	N;DEF;PL
søppel	søppelet	N;DEF;SG
skotsk	skotsk	ADJ;NEUT;SG
kjeks	kjeks	N;NDEF;PL
flyga	flyg	V;PRS
død	dødt	ADJ;NEUT
soldat	soldatar	N;NDEF;PL
gut	gutar	N;NDEF;PL
arbeidsgjevar	arbeidsgjevaren	N;DEF;SG
blome	blomast	V;NFIN;PASS
konsa	konsa	V;IMP
territorium	territoriet	N;DEF;SG
uer	ueren	N;DEF;SG
isbre	isbreane	N;DEF;PL
bloma	bloma	V;IMP
bardage	bardagar	N;NDEF;PL
ferje	ferjene	N;DEF;SG
utslette	utslette	V;IMP
grafisk	grafisk	ADJ;NEUT;SG
stolt	stolt	ADJ;NEUT;SG
heks	hekser	N;NDEF;PL
ukjent	ukjent	ADJ;NEUT;SG
vekslingskurs	vekslingskursar	N;NDEF;PL
gråte	gret	V;PST
kartagar	kartagarar	N;NDEF;PL
skisse	skissa	N;DEF;SG
palestinar	palestinaren	N;DEF;SG
regntid	regntider	N;NDEF;PL
høne	høns	N;NDEF;PL
orangutang	orangutangane	N;DEF;PL
motehus	motehus	N;NDEF;PL
grunnlag	grunnlaget	N;DEF;SG
låg	lågast	ADJ;SPRL;NDEF
kontur	konturar	N;NDEF;PL
mosambikar	mosambikarane	N;DEF;PL
låg	lågaste	ADJ;SPRL;DEF
svigerbror	svigerbrørne	N;DEF;PL
dagsavis	dagsavisa	N;DEF;SG
bakteriologi	bakteriologien	N;DEF;SG
byrja	byrja	V;IMP
komponist	komponistane	N;DEF;PL
ringe	ringer	V;PRS
tid	tide	N;DAT
ensemble	ensemblet	N;DEF;SG
bananskal	bananskala	N;DEF;PL
innkast	innkasta	N;DEF;PL
kjærast	kjærasten	N;DEF;SG
høre	hør	V;IMP
helgen	helgenen	N;DEF;SG
gammastråle	gammastrålen	N;DEF;SG
beist	beist	N;NDEF;PL
krasj	krasjar	N;NDEF;PL
kjevle	kjevle	N;NDEF;PL
gjerningsmann	gjerningsmannen	N;DEF;SG
filosofi	filosofien	N;DEF;SG
hårbørste	hårbørsten	N;DEF;SG
avhoppar	avhopparane	N;DEF;PL
legende	legenda	N;DEF;SG
byggemateriale	byggemateriala	N;DEF;PL
gevir	gevir	N;NDEF;PL
pai	paien	N;DEF;SG
tinn	tinnet	N;DEF;SG
valuta	valutaer	N;NDEF;PL
søle	søla	N;DEF;SG
kommandør	kommandørar	N;NDEF;PL
rorbu	rorbuene	N;DEF;PL
politikvinne	politikvinna	N;DEF;SG
tidleg	tidlegaste	ADJ;SPRL;DEF
vert	vertar	N;NDEF;PL
bakteriolog	bakteriologar	N;NDEF;PL
polsk	polsk	ADJ;NEUT;SG
astma	astmaen	N;DEF;SG
menstruasjon	menstruasjonen	N;DEF;SG
verkeleg	verkelegaste	ADJ;SPRL;DEF
horngjel	horngjelar	N;NDEF;PL
filolog	filologane	N;DEF;PL
forskar	forskarar	N;NDEF;PL
ledd	ledda	N;DEF;PL
rom	rommet	N;DEF;SG
spontan	spontant	ADJ;NEUT;SG
ekvator	ekvatorane	N;DEF;PL
brems	bremsar	N;NDEF;PL
sørafrikan	sørafrikanane	N;DEF;PL
byggja	byggjast	V;NFIN;PASS
singaporar	singaporarar	N;NDEF;PL
rumenar	rumenaren	N;DEF;SG
åtseletar	åtseletarane	N;DEF;PL
subkontinent	subkontinentet	N;DEF;SG
sportsbil	sportsbilane	N;DEF;PL
sjø	sjøs	N;GEN
tjukk	tjukkare	ADJ;CMPR
tadsjikar	tadsjikarane	N;DEF;PL
kystlinje	kystlinjer	N;NDEF;PL
vøla	vølast	V;NFIN;PASS
verne	vernast	V;NFIN;PASS
and	endene	N;DEF;PL
slekt	slekter	N;NDEF;PL
vinkel	vinklane	N;DEF;PL
aseksuell	aseksuelt	ADJ;NEUT;SG
sukkerroe	sukkerroa	N;DEF;SG
lekter	lekteren	N;DEF;SG
utslett	utsletta	N;DEF;PL
bekk	bekkar	N;NDEF;PL
retorisk	retorisk	ADJ;NEUT;SG
gambiar	gambiarar	N;NDEF;PL
sjettedel	sjettedelane	N;DEF;PL
streng	strengt	ADJ;NEUT;SG
hending	hendingane	N;DEF;PL
botswan	botswanane	N;DEF;PL
bukett	buketten	N;DEF;SG
postkort	postkort	N;NDEF;PL
albatross	albatrossen	N;DEF;SG
årelate	årelét	V;PST
bangladeshar	bangladesharen	N;DEF;SG
krets	kretsen	N;DEF;SG
kondensasjon	kondensasjonane	N;DEF;PL
merksemd	merksemda	N;DEF;SG
program	programma	N;DEF;PL
flass	flass	N;NDEF;PL
universitet	universitet	N;NDEF;PL
biolog	biologane	N;DEF;PL
nigerianar	nigerianaren	N;DEF;SG
verje	verjer	N;NDEF;PL
påske	påsken	N;DEF;SG
rytme	rytmen	N;DEF;SG
positiv	positive	N;DEF;SG+PL
blyant	blyantar	N;NDEF;PL
postkort	postkorta	N;DEF;PL
tunne	tunner	N;NDEF;PL
nisje	nisjane	N;DEF;PL
platespelar	platespelarane	N;DEF;PL
smil	smilar	N;NDEF;PL
dataspel	dataspel	N;NDEF;PL
trinidadar	trinidadarar	N;NDEF;PL
majones	majonesane	N;DEF;PL
viskositet	viskositeten	N;DEF;SG
fjern	fjernare	ADJ;CMPR
blindpassasjer	blindpassasjeren	N;DEF;SG
daude	daudane	N;DEF;PL
ukjent	ukjente	N;DEF;SG+PL
barnesoldat	barnesoldaten	N;DEF;SG
skinke	skinker	N;NDEF;PL
gjeva	gjev	V;IMP
måke	måkene	N;DEF;PL
studera	studer	V;IMP
folkestyrt	folkestyrte	N;DEF;SG+PL
mørk	mørkast	ADJ;SPRL;NDEF
styrke	styrkane	N;DEF;PL
tennplugg	tennpluggen	N;DEF;SG
grå	gråe	N;DEF;SG+PL
oppdage	oppdage	V;IMP
mark	markene	N;DEF;PL
snøfri	snøfritt	ADJ;NEUT;SG
slengja	slengjast	V;NFIN;PASS
gledesdrepar	gledesdreparane	N;DEF;PL
infrastruktur	infrastrukturen	N;DEF;SG
verja	verja	V;IMP
trommehinne	trommehinna	N;DEF;SG
vandra	vandrast	V;NFIN;PASS
angripe	angreip	V;PST
skjøne	skjøner	V;PRS
atomvåpen	atomvåpen	N;NDEF;PL
skrivemaskin	skrivemaskinen	N;DEF;SG
seng	senga	N;DEF;SG
spanjol	spanjolen	N;DEF;SG
litauar	litauarar	N;NDEF;PL
kompleks	kompleksa	N;DEF;PL
malm	malmen	N;DEF;SG
motehus	motehuset	N;DEF;SG
doktrine	doktrinar	N;NDEF;PL
dreiebenk	dreiebenkene	N;DEF;PL
eigenverdi	eigenverdien	N;DEF;SG
smil	smilet	N;DEF;SG
element	element	N;NDEF;PL
gullfisk	gullfiskane	N;DEF;PL
kredittkort	kredittkortet	N;DEF;SG
trombone	trombonane	N;DEF;PL
populær	populær	ADJ;MASC+FEM
odds	oddsa	N;DEF;PL
proporsjonal	proporsjonale	N;DEF;SG+PL
libyar	libyarar	N;NDEF;PL
gyngehest	gyngehestane	N;DEF;PL
hamløypar	hamløyparen	N;DEF;SG
kombinasjon	kombinasjonane	N;DEF;PL
uroleg	urolegare	ADJ;CMPR
rolle	rolla	N;DEF;SG
galopp	galoppar	N;NDEF;PL
runka	runka	V;IMP
solbrille	solbrillene	N;DEF;PL
maksimum	maksimuma	N;DEF;PL
algeriar	algeriarar	N;NDEF;PL
svineinfluensa	svineinfluensaar	N;NDEF;PL
akademikar	akademikaren	N;DEF;SG
resonans	resonansar	N;NDEF;PL
halvår	halvåret	N;DEF;SG
størrelse	størrelsar	N;NDEF;PL
dirigent	dirigenten	N;DEF;SG
drepe	drep	V;IMP
spekkhoggar	spekkhoggarane	N;DEF;PL
sitje	sit	V;PRS
ubroten	ubroten	ADJ;MASC+FEM
umoden	umodent	ADJ;NEUT;SG
fjellside	fjellsider	N;NDEF;PL
bjørn	bjørnar	N;NDEF;PL
eksistera	eksisterte	V;PST
tefat	tefat	N;NDEF;PL
verdi	verdiane	N;DEF;PL
strekk	strekka	N;DEF;PL
øydeleggje	øydela	V;PST
åsyn	åsyn	N;NDEF;PL
montenegrinar	montenegrinaren	N;DEF;SG
kaprar	kapraren	N;DEF;SG
jaktar	jaktaren	N;DEF;SG
green	greenar	N;NDEF;PL
kjendis	kjendisar	N;NDEF;PL
rulett	rulettar	N;NDEF;PL
konflikt	konflikten	N;DEF;SG
professor	professorane	N;DEF;PL
skribent	skribentar	N;NDEF;PL
koordinasjon	koordinasjonar	N;NDEF;PL
reptil	reptila	N;DEF;PL
konnotasjon	konnotasjonen	N;DEF;SG
kontinental	kontinentale	N;DEF;SG+PL
entomolog	entomologen	N;DEF;SG
dumheit	dumheita	N;DEF;SG
sandsekk	sandsekkene	N;DEF;PL
planet	planetar	N;NDEF;PL
navlestreng	navlestrengen	N;DEF;SG
kommune	kommunane	N;DEF;PL
nyzealendar	nyzealendarar	N;NDEF;PL
lever	levrene	N;DEF;PL
hemn	hemnen	N;DEF;SG
valmuefrø	valmuefrøet	N;DEF;SG
guatemalanar	guatemalanarane	N;DEF;PL
vegetabilsk	vegetabilsk	ADJ;NEUT;SG
reservoar	reservoar	N;NDEF;PL
franskmann	franskmenn	N;NDEF;PL
kjenna	kjennast	V;NFIN;PASS
jord	jorda	N;DEF;SG
kjedereaksjon	kjedereaksjonen	N;DEF;SG
høre	hørde	V;PST
eksempel	eksempel	N;NDEF;PL
sag	sagene	N;DEF;PL
papuan	papuanen	N;DEF;SG
tygga	tygg	V;IMP
brun	brunast	ADJ;SPRL;NDEF
nybyggjar	nybyggjarar	N;NDEF;PL
komparativ	komparativar	N;NDEF;PL
stråle	strålen	N;DEF;SG
hårbørste	hårbørstane	N;DEF;PL
nakke	nakken	N;DEF;SG
canadiar	canadiarane	N;DEF;PL
aktsam	aktsamt	ADJ;NEUT
konsentrere	konsentrerast	V;NFIN;PASS
menneske	mennesket	N;DEF;SG
brunsttid	brunsttider	N;NDEF;PL
politi	politiane	N;DEF;PL
prosjekt	prosjektet	N;DEF;SG
kam	kammen	N;DEF;SG
kaktus	kaktusar	N;NDEF;PL
bahrainar	bahrainaren	N;DEF;SG
konsument	konsumentane	N;DEF;PL
sengetid	sengetida	N;DEF;SG
underleg	underlegare	ADJ;CMPR
emiratarabar	emiratarabarar	N;NDEF;PL
femtedel	femtedelen	N;DEF;SG
varsam	varsamt	ADJ;NEUT
skodespel	skodespel	N;NDEF;PL
øydeleggje	øydelegg	V;IMP
horisont	horisontar	N;NDEF;PL
grunn	grunnen	N;DEF;SG
indeks	indeksar	N;NDEF;PL
fordel	fordelane	N;DEF;PL
teolog	teologar	N;NDEF;PL
permanent	permanente	N;DEF;SG+PL
svindel	svindelen	N;DEF;SG
stråling	strålinga	N;DEF;SG
behalde	behald	V;IMP
uvanleg	uvanlegast	ADJ;SPRL;NDEF
tvist	tvistar	N;NDEF;PL
bensinstasjon	bensinstasjonar	N;NDEF;PL
brennmanet	brennmanetene	N;DEF;PL
kollega	kollegaer	N;NDEF;PL
krone	kroner	N;NDEF;PL
energi	energiane	N;DEF;PL
uunngåeleg	uunngåelege	N;DEF;SG+PL
dialekt	dialekter	N;NDEF;PL
utsyn	utsynene	N;DEF;PL
seksdel	seksdelane	N;DEF;PL
rå	råaste	ADJ;SPRL;DEF
oversikt	oversikter	N;NDEF;PL
pennesplitt	pennesplittar	N;NDEF;PL
reform	reforma	N;DEF;SG
sitta	sit	V;PRS
frukthage	frukthagar	N;NDEF;PL
symja	symjast	V;NFIN;PASS
film	filmen	N;DEF;SG
diamant	diamantane	N;DEF;PL
liten	minst	ADJ;SPRL;NDEF
skatteparadis	skatteparadiset	N;DEF;SG
lang	lengre	ADJ;CMPR
tyggje	tygg	V;IMP
stålverk	stålverka	N;DEF;PL
skilt	skilta	N;DEF;PL
innkjøp	innkjøpet	N;DEF;SG
rullebane	rullebanane	N;DEF;PL
farar	fararen	N;DEF;SG
and	ender	N;NDEF;PL
finna	fann	V;PST
viktig	viktigast	ADJ;SPRL;NDEF
byrje	byrjar	V;PRS
fugleskremsel	fugleskremsel	N;NDEF;PL
eta	etast	V;NFIN;PASS
fin	finare	ADJ;CMPR
halvdel	halvdelane	N;DEF;PL
serbar	serbaren	N;DEF;SG
oppvask	oppvaskane	N;DEF;PL
automat	automatane	N;DEF;PL
spøk	spøkane	N;DEF;PL
kjegle	kjegler	N;NDEF;PL
hyperlenke	hyperlenka	N;DEF;SG
forsiktig	forsiktig	ADJ;NDEF;SG
fijian	fijianane	N;DEF;PL
vulkanutbrot	vulkanutbrot	N;NDEF;PL
kredittkort	kredittkort	N;NDEF;PL
plastfolie	plastfoliane	N;DEF;PL
alder	aldrane	N;DEF;PL
streng	strengene	N;DEF;PL
slette	sletter	N;NDEF;PL
rykte	rykta	N;DEF;PL
gammal	gammalt	ADJ;NEUT
fattig	fattigaste	ADJ;SPRL;DEF
hevda	hevda	V;IMP
rev	rev	N;NDEF;PL
fantastisk	fantastisk	ADJ;NEUT;SG
krabbe	krabbene	N;DEF;PL
hektar	hektar	N;NDEF;PL
brasme	brasma	N;DEF;SG
kanadiar	kanadiarar	N;NDEF;PL
kokke	kokka	N;DEF;SG
ringa	ringast	V;NFIN;PASS
geit	geiter	N;NDEF;PL
fjellside	fjellsidene	N;DEF;PL
ljote	laut	V;PST
instrument	instrumentet	N;DEF;SG
rapport	rapportane	N;DEF;PL
magnet	magneten	N;DEF;SG
bussjåfør	bussjåføren	N;DEF;SG
økonomisk	økonomisk	ADJ;NEUT;SG
sentralafrikan	sentralafrikanar	N;NDEF;PL
orangutang	orangutangen	N;DEF;SG
asiat	asiaten	N;DEF;SG
svolten	svoltnaste	ADJ;SPRL;DEF
kyrkje	kyrkja	N;DEF;SG
gi	givast	V;NFIN;PASS
nakke	nakkar	N;NDEF;PL
sjølvsagd	sjølvsagde	N;DEF;SG+PL
folkestyre	folkestyre	N;NDEF;PL
modellfly	modellflyet	N;DEF;SG
vanleg	vanlegare	ADJ;CMPR
animasjon	animasjonen	N;DEF;SG
velje	vel	V;PRS
tekstil	tekstilen	N;DEF;SG
tempel	tempelet	N;DEF;SG
dobbeltseng	dobbeltsengene	N;DEF;PL
tann	tanna	N;DEF;SG
sykkel	syklane	N;DEF;PL
behageleg	behageleg	ADJ;NDEF;SG
indeks	indeksane	N;DEF;PL
krystall	krystallar	N;NDEF;PL
innføring	innføringar	N;NDEF;PL
kaotisk	kaotisk	ADJ;NEUT;SG
zimbabwar	zimbabwaren	N;DEF;SG
koreansk	koreansken	N;DEF;SG
vestleg	vestlege	N;DEF;SG+PL
uruguayanar	uruguayanarar	N;NDEF;PL
bølgelengde	bølgelengder	N;NDEF;PL
franskmann	franskmannen	N;DEF;SG
massasje	massasjar	N;NDEF;PL
apostel	apostelen	N;DEF;SG
stoppekran	stoppekraner	N;NDEF;PL
optimist	optimisten	N;DEF;SG
garasje	garasjar	N;NDEF;PL
rusten	ruste	ADJ;NEUT;SG
vekke	vekte	V;PST
prosedyre	prosedyrar	N;NDEF;PL
natur	naturar	N;NDEF;PL
forhistorie	forhistorier	N;NDEF;PL
synonymordbok	synonymordboka	N;DEF;SG
samarbeida	samarbeidde	V;PST
erfaring	erfaringane	N;DEF;PL
seychellar	seychellaren	N;DEF;SG
taxisjåfør	taxisjåførar	N;NDEF;PL
gyllen	gylle	ADJ;NEUT;SG
svigerfar	svigerfedrane	N;DEF;PL
folketeljing	folketeljingane	N;DEF;PL
trussel	trusselen	N;DEF;SG
pinleg	pinlege	N;DEF;SG+PL
måse	måsane	N;DEF;PL
hydraulisk	hydraulisk	ADJ;NEUT;SG
sudanar	sudanaren	N;DEF;SG
omgivnad	omgivnadar	N;NDEF;PL
tape	tapar	V;PRS
organisasjon	organisasjonane	N;DEF;PL
laser	laserane	N;DEF;PL
gut	gutane	N;DEF;PL
verja	verja	V;PST
kran	krana	N;DEF;SG
kne	kne	N;NDEF;PL
luftforsvar	luftforsvaret	N;DEF;SG
sivil	sivil	ADJ;MASC+FEM
krasj	krasj	N;NDEF;PL
lever	levrer	N;NDEF;PL
bakside	baksider	N;NDEF;PL
rein	reint	ADJ;NEUT;SG
intervju	intervjuet	N;DEF;SG
medisin	medisinen	N;DEF;SG
tap	tapet	N;DEF;SG
guatemalanar	guatemalanaren	N;DEF;SG
grafitt	grafitten	N;DEF;SG
sjå	såg	V;PST
uklar	uklare	N;DEF;SG+PL
titan	titanet	N;DEF;SG
demokrat	demokratane	N;DEF;PL
landkrabbe	landkrabben	N;DEF;SG
gris	grisene	N;DEF;PL
ugle	uglene	N;DEF;PL
sal	sal	N;NDEF;PL
effekt	effekten	N;DEF;SG
ringa	ringer	V;PRS
helt	heltar	N;NDEF;PL
guatemalan	guatemalanane	N;DEF;PL
hjelpa	hjelp	V;IMP
forbrenning	forbrenningar	N;NDEF;PL
anneks	anneksa	N;DEF;PL
jernbanestasjon	jernbanestasjonar	N;NDEF;PL
bosniar	bosniaren	N;DEF;SG
skriva	skreiv	V;PST
prisliste	prislista	N;DEF;SG
superlativ	superlativane	N;DEF;PL
nebb	nebben	N;DEF;SG
jordskjelv	jordskjelv	N;NDEF;PL
amøbe	amøbar	N;NDEF;PL
patrulje	patruljen	N;DEF;SG
gjennomsnittleg	gjennomsnittleg	ADJ;NEUT;SG
klinikk	klinikkane	N;DEF;PL
tåre	tåra	N;DEF;SG
bachelorgrad	bachelorgradane	N;DEF;PL
lenestol	lenestolen	N;DEF;SG
millionær	millionærar	N;NDEF;PL
datasimulering	datasimuleringar	N;NDEF;PL
besøke	besøk	V;IMP
foajé	foajéar	N;NDEF;PL
samarbeida	samarbeider	V;PRS
grunnflate	grunnflata	N;DEF;SG
kontur	konturane	N;DEF;PL
våtmark	våtmarker	N;NDEF;PL
etasje	etasjar	N;NDEF;PL
selje	selde	V;PST
forord	forordet	N;DEF;SG
tusj	tusjar	N;NDEF;PL
fly	flydde	V;PST
database	databasane	N;DEF;PL
koseleg	koselegast	ADJ;SPRL;NDEF
sjølvsagd	sjølvsagt	ADJ;NEUT
andreplass	andreplassen	N;DEF;SG
svikar	svikarane	N;DEF;PL
fengsel	fengselet	N;DEF;SG
psykopat	psykopatane	N;DEF;PL
tut	tutet	N;DEF;SG
georgiar	georgiarane	N;DEF;PL
prestasjon	prestasjonar	N;NDEF;PL
isbjørn	isbjørnar	N;NDEF;PL
alfabet	alfabetet	N;DEF;SG
komparativ	komparativane	N;DEF;PL
svovel	svovelen	N;DEF;SG
baug	baugar	N;NDEF;PL
vøle	vølte	V;PST
hierarki	hierarki	N;NDEF;PL
komité	komitéane	N;DEF;PL
motiv	motiv	N;NDEF;PL
burda	bør	V;PRS
teknologi	teknologiane	N;DEF;PL
adverb	adverba	N;DEF;PL
utnytta	utnyttast	V;NFIN;PASS
innkjøp	innkjøpa	N;DEF;PL
skjøna	skjønar	V;PRS
lunsj	lunsjane	N;DEF;PL
sitron	sitronane	N;DEF;PL
vekkje	vekkjer	V;PRS
amatør	amatørane	N;DEF;PL
orkester	orkestera	N;DEF;PL
slengje	slengjast	V;NFIN;PASS
kynikar	kynikarar	N;NDEF;PL
kjedereaksjon	kjedereaksjonane	N;DEF;PL
hundeliv	hundelivet	N;DEF;SG
substantiv	substantiva	N;DEF;PL
postkontor	postkontoret	N;DEF;SG
premie	premien	N;DEF;SG
underhalding	underhaldinga	N;DEF;SG
kjøkkenbenk	kjøkkenbenken	N;DEF;SG
sideelv	sideelva	N;DEF;SG
nerve	nervane	N;DEF;PL
kalk	kalkar	N;NDEF;PL
kald	kaldaste	ADJ;SPRL;DEF
handveske	handveska	N;DEF;SG
lege	legane	N;DEF;PL
detektiv	detektiven	N;DEF;SG
øks	øksane	N;DEF;PL
grov	grove	N;DEF;SG+PL
skulptur	skulpturane	N;DEF;PL
tårn	tårn	N;NDEF;PL
mur	murane	N;DEF;PL
jarnbane	jarnbanen	N;DEF;SG
prisliste	prislister	N;NDEF;PL
sjørøye	sjørøyene	N;DEF;PL
øksla	øksla	V;PST
færøysk	færøysk	ADJ;NEUT;SG
tunne	tunnast	V;NFIN;PASS
kanin	kaninen	N;DEF;SG
vedda	vedda	V;IMP
armbrøst	armbrøsten	N;DEF;SG
eksistera	eksister	V;IMP
lauk	laukar	N;NDEF;PL
utnytta	utnytta	V;PST
soloppgang	soloppgangane	N;DEF;PL
fiken	fikenen	N;DEF;SG
kampanje	kampanjane	N;DEF;PL
erfaren	erfare	ADJ;NEUT;SG
liten	litle	ADJ;DEF;SG
snøgrense	snøgrenser	N;NDEF;PL
ynska	ynsk	V;IMP
mongol	mongolen	N;DEF;SG
kabel	kablane	N;DEF;PL
måltid	måltida	N;DEF;PL
påhengsmotor	påhengsmotorar	N;NDEF;PL
spreia	spreidde	V;PST
duga	dugde	V;PST
pattedyr	pattedyret	N;DEF;SG
krokodille	krokodillen	N;DEF;SG
økonom	økonomane	N;DEF;PL
slenga	slengast	V;NFIN;PASS
sverm	svermar	N;NDEF;PL
rose	rosene	N;DEF;PL
representant	representantane	N;DEF;PL
høyre	høyr	V;IMP
einig	einigare	ADJ;CMPR
inskripsjon	inskripsjonane	N;DEF;PL
nyttelast	nyttelastene	N;DEF;PL
kjønnshår	kjønnshåret	N;DEF;SG
purre	purrar	N;NDEF;PL
rullebane	rullebaner	N;NDEF;PL
skjøne	skjøne	V;IMP
arabisk	arabiske	N;DEF;SG+PL
definera	definerast	V;NFIN;PASS
studium	studiet	N;DEF;SG
nykomar	nykomarar	N;NDEF;PL
krevja	krev	V;PRS
gå	går	V;PRS
besøka	besøkte	V;PST
kropp	kroppar	N;NDEF;PL
synd	synda	N;DEF;SG
steinblokk	steinblokkar	N;NDEF;PL
velje	veljast	V;NFIN;PASS
natrium	natriumet	N;DEF;SG
fossefall	fossefalla	N;DEF;PL
fare	far	V;IMP
klinkekule	klinkekula	N;DEF;SG
flåte	flåtane	N;DEF;PL
jordskjelv	jordskjelva	N;DEF;PL
karm	karmane	N;DEF;PL
puré	pureen	N;DEF;SG
inflasjon	inflasjonar	N;NDEF;PL
afar	afarane	N;DEF;PL
paviljong	paviljongen	N;DEF;SG
aminosyre	aminosyrer	N;NDEF;PL
stolt	stoltaste	ADJ;SPRL;DEF
kokke	kokkene	N;DEF;PL
fjellklatrar	fjellklatrarane	N;DEF;PL
fattigdom	fattigdommen	N;DEF;SG
sardin	sardinen	N;DEF;SG
grossist	grossistane	N;DEF;PL
liggja	låg	V;PST
hi	hi	N;NDEF;PL
transport	transportane	N;DEF;PL
guatemalan	guatemalanen	N;DEF;SG
kenyanar	kenyanaren	N;DEF;SG
klasse	klassane	N;DEF;PL
snøball	snøballen	N;DEF;SG
brille	brilla	N;DEF;SG
spekter	spektera	N;DEF;PL
blokk	blokkar	N;NDEF;PL
brasiliansk	brasilianske	N;DEF;SG+PL
kosovar	kosovaren	N;DEF;SG
element	elementa	N;DEF;PL
tyda	tyd	V;IMP
lok	loket	N;DEF;SG
hjelm	hjelmane	N;DEF;PL
nettside	nettsida	N;DEF;SG
vekka	vekkast	V;NFIN;PASS
oppteken	oppteken	ADJ;MASC+FEM
forkasta	forkasta	V;IMP
parakitt	parakitten	N;DEF;SG
styrkje	styrkjer	V;PRS
bhutanar	bhutanaren	N;DEF;SG
maori	maorien	N;DEF;SG
vital	vitale	N;DEF;SG+PL
ofra	ofrar	V;PRS
sektor	sektorane	N;DEF;PL
oversikt	oversikta	N;DEF;SG
lys	lyset	N;DEF;SG
førebu	førebur	V;PRS
valdtekt	valdtekter	N;NDEF;PL
radikalar	radikalarar	N;NDEF;PL
høg	høg	ADJ;MASC+FEM
kalkun	kalkunen	N;DEF;SG
sabotør	sabotørane	N;DEF;PL
høgskole	høgskolen	N;DEF;SG
stengel	stenglar	N;NDEF;PL
vokalist	vokalisten	N;DEF;SG
umyndig	umyndige	N;DEF;SG+PL
bakterie	bakterien	N;DEF;SG
zambiar	zambiarar	N;NDEF;PL
søk	søk	N;NDEF;PL
aborigin	aboriginar	N;NDEF;PL
ekstremist	ekstremisten	N;DEF;SG
ungar	ungaren	N;DEF;SG
elbil	elbilane	N;DEF;PL
straffbar	straffbare	N;DEF;SG+PL
medlemskap	medlemskap	N;NDEF;PL
børs	børsar	N;NDEF;PL
æra	æraane	N;DEF;PL
honduranar	honduranarar	N;NDEF;PL
armenar	armenarane	N;DEF;PL
feil	feilen	N;DEF;SG
valmue	valmuar	N;NDEF;PL
rovdyr	rovdyret	N;DEF;SG
bolivian	bolivianane	N;DEF;PL
grand danois	grand danoisar	N;NDEF;PL
elektron	elektrona	N;DEF;PL
bidronning	bidronningar	N;NDEF;PL
aritmetikk	aritmetikken	N;DEF;SG
ulik	ulik	ADJ;MASC+FEM
tekstil	tekstilane	N;DEF;PL
xenofobi	xenofobien	N;DEF;SG
farge	farga	N;DEF;SG
snøleopard	snøleoparden	N;DEF;SG
gjest	gjesten	N;DEF;SG
vid	vidast	ADJ;SPRL;NDEF
våpen	våpen	N;NDEF;PL
gjensidig	gjensidig	ADJ;NEUT;SG
varemerke	varemerka	N;DEF;PL
korn	korna	N;DEF;PL
økonomikk	økonomikken	N;DEF;SG
mineralogi	mineralogien	N;DEF;SG
litteratur	litteraturar	N;NDEF;PL
tap	tapa	N;DEF;PL
T-bane	T-banen	N;DEF;SG
krevja	kravde	V;PST
hugse	hugse	V;IMP
høre	hørast	V;NFIN;PASS
bokhandel	bokhandlane	N;DEF;PL
konvolutt	konvoluttane	N;DEF;PL
svolt	svolten	N;DEF;SG
egyptar	egyptarar	N;NDEF;PL
finna	finnast	V;NFIN;PASS
hai	haiane	N;DEF;PL
kaste	kastane	N;DEF;PL
frykteleg	fryktelege	N;DEF;SG+PL
kolombian	kolombianar	N;NDEF;PL
skorpion	skorpionen	N;DEF;SG
tett	tette	N;DEF;SG+PL
utfordre	utfordra	V;PST
industriell	industrielle	N;DEF;SG+PL
hawaiar	hawaiarar	N;NDEF;PL
kaktus	kaktusen	N;DEF;SG
stad	stad	N;NDEF;PL
hevelse	hevelsane	N;DEF;PL
nicaraguanar	nicaraguanaren	N;DEF;SG
tunnel	tunnelen	N;DEF;SG
korean	koreanar	N;NDEF;PL
infeksjon	infeksjonar	N;NDEF;PL
reporter	reporteren	N;DEF;SG
bruneiar	bruneiarane	N;DEF;PL
trong	tronge	N;DEF;SG+PL
hebraisk	hebraiske	N;DEF;SG+PL
slovenar	slovenarar	N;NDEF;PL
trussel	truslane	N;DEF;PL
potteplante	potteplanten	N;DEF;SG
studera	studerte	V;PST
fattig	fattig	ADJ;NEUT;SG
pyramide	pyramidane	N;DEF;PL
honduran	honduranen	N;DEF;SG
hendig	hendige	N;DEF;SG+PL
fargeblyant	fargeblyantane	N;DEF;PL
luftskip	luftskipa	N;DEF;PL
be	bad	V;PST
gyngestol	gyngestolane	N;DEF;PL
krasj	krasjen	N;DEF;SG
svarttrast	svarttraster	N;NDEF;PL
kontinent	kontinentet	N;DEF;SG
fantom	fantoma	N;DEF;PL
gjel	gjelet	N;DEF;SG
sirkus	sirkuset	N;DEF;SG
farge	fargen	N;DEF;SG
ærleg	ærlegast	ADJ;SPRL;NDEF
bite	biter	V;PRS
ufatteleg	ufattelegaste	ADJ;SPRL;DEF
slå	slå	V;NFIN;ACT
liggja	liggjast	V;NFIN;PASS
strekning	strekningane	N;DEF;PL
ordtak	ordtaket	N;DEF;SG
konnotasjon	konnotasjonar	N;NDEF;PL
pupp	puppane	N;DEF;PL
libysk	libysk	ADJ;NEUT;SG
skoggrense	skoggrensene	N;DEF;PL
afrikansk	afrikansk	ADJ;NEUT
tredimensjonal	tredimensjonale	N;DEF;SG+PL
by	byane	N;DEF;PL
senator	senatorar	N;NDEF;PL
skøyte	skøyta	N;DEF;SG
byggjar	byggjaren	N;DEF;SG
univers	universet	N;DEF;SG
byrjing	byrjingane	N;DEF;PL
bokstavleg	bokstavlegare	ADJ;CMPR
trommestikke	trommestikka	N;DEF;SG
turbulens	turbulensen	N;DEF;SG
levering	leveringa	N;DEF;SG
sylinder	sylindrar	N;NDEF;PL
hytte	hyttene	N;DEF;PL
ballett	ballettane	N;DEF;PL
ballkjole	ballkjolen	N;DEF;SG
centiliter	centilitrane	N;DEF;PL
side	sidene	N;DEF;PL
skepsis	skepsisen	N;DEF;SG
destruksjon	destruksjonen	N;DEF;SG
utstilling	utstillinga	N;DEF;SG
duld	duldare	ADJ;CMPR
knapp	knappar	N;NDEF;PL
nattpotte	nattpotter	N;NDEF;PL
trommis	trommisen	N;DEF;SG
silhuett	silhuettar	N;NDEF;PL
bleikemiddel	bleikemiddelet	N;DEF;SG
komité	komitéar	N;NDEF;PL
kjeks	kjeksen	N;DEF;SG
kran	kranene	N;DEF;PL
gruvearbeidar	gruvearbeidaren	N;DEF;SG
mann	mannen	N;DEF;SG
besøke	besøker	V;PRS
stridsøks	stridsøksa	N;DEF;SG
steinblokk	steinblokken	N;DEF;SG
ljuge	ljug	V;IMP
snøstorm	snøstormen	N;DEF;SG
hydraulisk	hydrauliske	N;DEF;SG+PL
bursdag	bursdagane	N;DEF;PL
ambassade	ambassadar	N;NDEF;PL
inskripsjon	inskripsjonen	N;DEF;SG
par	par	N;NDEF;PL
entusiastisk	entusiastisk	ADJ;NEUT;SG
vesteuropeisk	vesteuropeiske	N;DEF;SG+PL
kulde	kulden	N;DEF;SG
smerte	smerta	N;DEF;SG
skatteflyktning	skatteflyktningen	N;DEF;SG
setning	setninga	N;DEF;SG
djiboutiar	djiboutiarar	N;NDEF;PL
stoff	stoffa	N;DEF;PL
skjønna	skjønn	V;IMP
behageleg	behagelegare	ADJ;CMPR
setning	setningane	N;DEF;PL
livbåt	livbåten	N;DEF;SG
stormfull	stormfullt	ADJ;NEUT;SG
resonans	resonansane	N;DEF;PL
konklusjon	konklusjonar	N;NDEF;PL
flykaprar	flykapraren	N;DEF;SG
mamma	mammaer	N;NDEF;PL
vilja	vil	V;IMP
boikott	boikotten	N;DEF;SG
kommunikasjon	kommunikasjonar	N;NDEF;PL
seljar	seljarar	N;NDEF;PL
sørleg	sørlegare	ADJ;CMPR
åkle	åklet	N;DEF;SG
runka	runkast	V;NFIN;PASS
hoe	hoa	N;DEF;SG
minusgrad	minusgraden	N;DEF;SG
orkester	orkesteret	N;DEF;SG
uvanleg	uvanleg	ADJ;NDEF;SG
terning	terningane	N;DEF;PL
naturressurs	naturressursar	N;NDEF;PL
engelsk	engelskast	ADJ;SPRL;NDEF
nederlendar	nederlendarane	N;DEF;PL
øydeleggja	øydelegg	V;IMP
kultur	kulturane	N;DEF;PL
sundag	sundagane	N;DEF;PL
paraply	paraplyane	N;DEF;PL
medisin	medisinane	N;DEF;PL
ærleg	ærleg	ADJ;NDEF;SG
dekke	dekk	V;IMP
optimisme	optimismen	N;DEF;SG
seie	seiast	V;NFIN;PASS
yrke	yrka	N;DEF;PL
tapar	taparen	N;DEF;SG
krona	krona	V;IMP
symaskin	symaskiner	N;NDEF;PL
handballspelar	handballspelaren	N;DEF;SG
tømmer	tømmeret	N;DEF;SG
snøplog	snøplogane	N;DEF;PL
ghanesisk	ghanesiske	N;DEF;SG+PL
program	program	N;NDEF;PL
tidsskrift	tidsskrift	N;NDEF;PL
steinblokk	steinblokker	N;NDEF;PL
øydelegge	øydeleggast	V;NFIN;PASS
grunnskole	grunnskolen	N;DEF;SG
krabbe	krabbane	N;DEF;PL
hale	halen	N;DEF;SG
spiss	spissane	N;DEF;PL
skulder	skuldrene	N;DEF;PL
isfjell	isfjell	N;NDEF;PL
skodespelar	skodespelarar	N;NDEF;PL
tanzanianar	tanzanianarar	N;NDEF;PL
brasme	brasmer	N;NDEF;PL
gullalder	gullalderar	N;NDEF;PL
peruan	peruanar	N;NDEF;PL
preposisjon	preposisjonen	N;DEF;SG
søkja	søkjast	V;NFIN;PASS
heile	heilar	V;PRS
sentral	sentralt	ADJ;NEUT;SG
zimbabwar	zimbabwarar	N;NDEF;PL
fasinere	fasinerer	V;PRS
epidemisk	epidemiske	N;DEF;SG+PL
døgn	døgn	N;NDEF;PL
ligga	ligg	V;PRS
legg	legger	N;NDEF;PL
tvilling	tvillingen	N;DEF;SG
oppvaskmaskin	oppvaskmaskiner	N;NDEF;PL
peng	pengar	N;NDEF;PL
baug	baugen	N;DEF;SG
initiativ	initiativet	N;DEF;SG
kam	kammar	N;NDEF;PL
disk	disken	N;DEF;SG
missil	missila	N;DEF;PL
bulgarsk	bulgarsken	N;DEF;SG
handledd	handledd	N;NDEF;PL
pol	polar	N;NDEF;PL
formel	formlar	N;NDEF;PL
turve	turvt	V;PST
kamuflasje	kamuflasjar	N;NDEF;PL
fyrstikk	fyrstikka	N;DEF;SG
naboland	nabolandet	N;DEF;SG
uruguayan	uruguayanane	N;DEF;PL
mann	mennene	N;DEF;PL
drone	dronar	N;NDEF;PL
tankefull	tankefullt	ADJ;NEUT;SG
ekvatorialguinean	ekvatorialguineanen	N;DEF;SG
rakett	rakettane	N;DEF;PL
muskel	musklane	N;DEF;PL
uroleg	urolegast	ADJ;SPRL;NDEF
munn	munnar	N;NDEF;PL
handelsflåte	handelsflåtar	N;NDEF;PL
svale	svalene	N;DEF;PL
kreativ	kreativt	ADJ;NEUT;SG
friksjon	friksjonar	N;NDEF;PL
trampoline	trampolinane	N;DEF;PL
matematikar	matematikarar	N;NDEF;PL
jagarfly	jagarflyet	N;DEF;SG
halda	heldt	V;PST
diaré	diareane	N;DEF;PL
mikroorganisme	mikroorganismar	N;NDEF;PL
personskade	personskadane	N;DEF;PL
styresmakt	styresmaktene	N;DEF;PL
improvisasjon	improvisasjonane	N;DEF;PL
smaksstoff	smaksstoff	N;NDEF;PL
julaftan	julaftanane	N;DEF;PL
væpne	væpne	V;IMP
peruanar	peruanaren	N;DEF;SG
astronaut	astronautane	N;DEF;PL
soge	soger	N;NDEF;PL
boble	bobler	N;NDEF;PL
teater	teateret	N;DEF;SG
samarbeid	samarbeid	N;NDEF;PL
granitt	granitten	N;DEF;SG
arkeolog	arkeologane	N;DEF;PL
filmstjerne	filmstjernene	N;DEF;PL
komisk	komiske	N;DEF;SG+PL
misteltein	mistelteinar	N;NDEF;PL
vårteikn	vårteikn	N;NDEF;PL
vintertid	vintertider	N;NDEF;PL
sørkorean	sørkoreanen	N;DEF;SG
visdomstann	visdomstanna	N;DEF;SG
sjølvmord	sjølvmord	N;NDEF;PL
man	maner	N;NDEF;PL
injeksjon	injeksjonen	N;DEF;SG
newzealendar	newzealendarar	N;NDEF;PL
infeksjon	infeksjonen	N;DEF;SG
fartøy	fartøya	N;DEF;PL
kollisjon	kollisjonen	N;DEF;SG
kart	kartane	N;DEF;PL
ubroten	ubrotne	N;DEF;SG+PL
telefonsentral	telefonsentralar	N;NDEF;PL
nyre	nyre	N;NDEF;PL
isolator	isolatorar	N;NDEF;PL
barnehage	barnehagar	N;NDEF;PL
vera	ver	V;IMP
krystall	krystalla	N;DEF;PL
byråkrati	byråkratia	N;DEF;PL
flis	flisene	N;DEF;PL
gullalder	gullalderane	N;DEF;PL
størrelse	størrelsen	N;DEF;SG
kartograf	kartografen	N;DEF;SG
andorran	andorranen	N;DEF;SG
høyre	høyrast	V;NFIN;PASS
oppgåve	oppgåvene	N;DEF;PL
rom	rom	N;NDEF;PL
modellfly	modellflya	N;DEF;PL
velje	vel	V;IMP
romantikar	romantikarar	N;NDEF;PL
årelate	årelatast	V;NFIN;PASS
krystall	krystall	N;NDEF;PL
sirkelrund	sirkelrundt	ADJ;NEUT;SG
alternativ	alternative	N;DEF;SG+PL
trollmann	trollmennene	N;DEF;PL
satellitt	satellittane	N;DEF;PL
ikon	ikon	N;NDEF;PL
aerosol	aerosolane	N;DEF;PL
svart	svartaste	ADJ;SPRL;DEF
vind	vindane	N;DEF;PL
turkis	turkisar	N;NDEF;PL
byrja	burde	V;PST
solbrille	solbriller	N;NDEF;PL
klisjé	klisjeen	N;DEF;SG
sølvtøy	sølvtøyet	N;DEF;SG
fasinera	fasinerer	V;PRS
finger	fingrane	N;DEF;PL
dominikanar	dominikanaren	N;DEF;SG
fregatt	fregattar	N;NDEF;PL
firling	firlingen	N;DEF;SG
art	artar	N;NDEF;PL
ordre	ordrar	N;NDEF;PL
spela	spelast	V;NFIN;PASS
konsentrera	konsentrerast	V;NFIN;PASS
system	system	N;NDEF;PL
munn	munnen	N;DEF;SG
songar	songaren	N;DEF;SG
fjerna	fjernast	V;NFIN;PASS
nedgang	nedgangar	N;NDEF;PL
styrkje	styrkte	V;PST
drepe	drep	V;PRS
dansk	dansk	ADJ;NEUT;SG
libyar	libyaren	N;DEF;SG
destruksjon	destruksjonar	N;NDEF;PL
horngjel	horngjeler	N;NDEF;PL
arbeid	arbeidet	N;DEF;SG
fullstendig	fullstendig	ADJ;NDEF;SG
muskel	muskelen	N;DEF;SG
støpsel	støpsel	N;NDEF;PL
apal	apalane	N;DEF;PL
komet	kometane	N;DEF;PL
tastatur	tastatura	N;DEF;PL
gyldig	gyldige	N;DEF;SG+PL
sjakkbrett	sjakkbrettet	N;DEF;SG
bite	bit	V;PRS
vott	vottane	N;DEF;PL
førebu	førebu	V;IMP
slavisk	slaviske	N;DEF;SG+PL
sal	salane	N;DEF;PL
sloven	slovenane	N;DEF;PL
åtvara	åtvarast	V;NFIN;PASS
belte	beltet	N;DEF;SG
kraftig	kraftig	ADJ;NEUT;SG
søka	søker	V;PRS
ljos	ljosare	ADJ;CMPR
klasse	klasser	N;NDEF;PL
albanar	albanaren	N;DEF;SG
nynazist	nynazistane	N;DEF;PL
mørk	mørkaste	ADJ;SPRL;DEF
duga	dugast	V;NFIN;PASS
hav	havet	N;DEF;SG
brorskap	brorskapa	N;DEF;PL
helle	hellene	N;DEF;PL
idrett	idrettar	N;NDEF;PL
eksperiment	eksperimenta	N;DEF;PL
seismologi	seismologien	N;DEF;SG
anonym	anonyme	N;DEF;SG+PL
jernmalm	jernmalmane	N;DEF;PL
sektor	sektorar	N;NDEF;PL
luktfri	luktfritt	ADJ;NEUT;SG
oppteken	opptekne	N;DEF;SG+PL
rein	reinen	N;DEF;SG
stele	stelast	V;NFIN;PASS
hekke	hekka	V;PST
auksjon	auksjonen	N;DEF;SG
behalde	beheldt	V;PST
skatt	skattane	N;DEF;PL
helt	heltane	N;DEF;PL
pingvin	pingvinen	N;DEF;SG
rev	revet	N;DEF;SG
åtvaring	åtvaringar	N;NDEF;PL
tvilling	tvillingar	N;NDEF;PL
glidelås	glidelås	N;NDEF;PL
baderom	baderommet	N;DEF;SG
jomfruhinne	jomfruhinnene	N;DEF;PL
ekvatorialguinean	ekvatorialguineanane	N;DEF;PL
spindelvev	spindelveven	N;DEF;SG
alter	alteret	N;DEF;SG
prosedyre	prosedyren	N;DEF;SG
amfiteater	amfiteatera	N;DEF;PL
grafisk	grafiske	N;DEF;SG+PL
brenna	brann	V;PST
smal	smalaste	ADJ;SPRL;DEF
utsletta	utsletta	V;PST
kvadratisk	kvadratiske	N;DEF;SG+PL
skatteflyktning	skatteflyktningane	N;DEF;PL
kjølig	kjøligaste	ADJ;SPRL;DEF
heil	heilare	ADJ;CMPR
kapitalisme	kapitalismen	N;DEF;SG
belte	belta	N;DEF;PL
shorts	shorts	N;NDEF;PL
hangarskip	hangarskip	N;NDEF;PL
sitteplass	sitteplassen	N;DEF;SG
levemann	levemenn	N;NDEF;PL
lomme	lommer	N;NDEF;PL
kongerike	kongeriket	N;DEF;SG
odds	odds	N;NDEF;PL
hage	hagar	N;NDEF;PL
diameter	diametrar	N;NDEF;PL
klinikk	klinikken	N;DEF;SG
fiskar	fiskarane	N;DEF;PL
klehengjar	klehengjarane	N;DEF;PL
nygift	nygift	ADJ;NEUT;SG
barne	barnar	V;PRS
sirkulasjon	sirkulasjonen	N;DEF;SG
vegetasjon	vegetasjonar	N;NDEF;PL
apotekar	apotekarane	N;DEF;PL
nordafrikansk	nordafrikansk	ADJ;NEUT;SG
medlem	medlemer	N;NDEF;PL
argument	argumentet	N;DEF;SG
ljuge	laug	V;PST
stige	stigane	N;DEF;PL
desimalkomma	desimalkomma	N;NDEF;PL
tunnelbane	tunnelbanene	N;DEF;PL
synonymordbok	synonymordbøkene	N;DEF;PL
forbløffe	forbløffa	V;PST
tyda	tydde	V;PST
penn	pennen	N;DEF;SG
førenamn	førenamna	N;DEF;PL
vollgrav	vollgravene	N;DEF;PL
signatur	signaturen	N;DEF;SG
luksusbil	luksusbilen	N;DEF;SG
bergmann	bergmenn	N;NDEF;PL
medlemskort	medlemskort	N;NDEF;PL
håpe	håpe	V;IMP
verktøy	verktøy	N;NDEF;PL
natur	naturane	N;DEF;PL
råolje	råoljer	N;NDEF;PL
lønn	lønnar	N;NDEF;PL
årstid	årstidene	N;DEF;PL
sjøkart	sjøkart	N;NDEF;PL
aspekt	aspektar	N;NDEF;PL
rhodium	rhodiumet	N;DEF;SG
nordmann	nordmannen	N;DEF;SG
kontakt	kontaktane	N;DEF;PL
veng	vengene	N;DEF;PL
brun	brunare	ADJ;CMPR
avstand	avstandane	N;DEF;PL
gjer	gjerast	ADJ;SPRL;NDEF
ivorianar	ivorianarane	N;DEF;PL
mikroskop	mikroskopa	N;DEF;PL
ordentleg	ordentlege	N;DEF;SG+PL
foto	fotoet	N;DEF;SG
ringe	ringast	V;NFIN;PASS
trenga	treng	V;IMP
straum	straumen	N;DEF;SG
gråaktig	gråaktige	N;DEF;SG+PL
tapa	tapa	V;PST
skrujern	skrujern	N;NDEF;PL
syklus	syklusen	N;DEF;SG
årsdag	årsdagar	N;NDEF;PL
lett	lettare	ADJ;CMPR
bomull	bomulla	N;DEF;SG
ekstrem	ekstremt	ADJ;NEUT
æra	æraar	N;NDEF;PL
have	har	V;PRS
måke	måka	N;DEF;SG
ven	venane	N;DEF;PL
lagring	lagringane	N;DEF;PL
kongefamilie	kongefamiliar	N;NDEF;PL
anarki	anarkiet	N;DEF;SG
gul	gulast	ADJ;SPRL;NDEF
plassering	plasseringane	N;DEF;PL
brystimplantat	brystimplantata	N;DEF;PL
skibakke	skibakkar	N;NDEF;PL
vekkja	vekte	V;PST
argument	argumenta	N;DEF;PL
undergang	undergangen	N;DEF;SG
influensa	influensaen	N;DEF;SG
nasa	nasa	V;PST
russisk	russisk	ADJ;NDEF;NEUT;SG
improvisasjon	improvisasjonen	N;DEF;SG
rik	rikt	ADJ;NEUT;SG
flytur	flyturen	N;DEF;SG
aksel	akselen	N;DEF;SG
annan	anna	ADJ;NEUT
bilbelte	bilbelte	N;NDEF;PL
mørketid	mørketidene	N;DEF;PL
rumensk	rumensken	N;DEF;SG
spøk	spøkar	N;NDEF;PL
følge	følgde	V;PST
tannhjul	tannhjulet	N;DEF;SG
newzealendar	newzealendarane	N;DEF;PL
symje	sym	V;PRS
svolten	svolten	ADJ;MASC+FEM
dobbeltseng	dobbeltsenger	N;NDEF;PL
terning	terningen	N;DEF;SG
vik	vikene	N;DEF;PL
shorts	shortsar	N;NDEF;PL
kvadrat	kvadratet	N;DEF;SG
kjøp	kjøpa	N;DEF;PL
raudspette	raudspetta	N;DEF;SG
kjøl	kjølane	N;DEF;PL
beita	beita	V;PST
symbol	symbola	N;DEF;PL
tatovering	tatoveringar	N;NDEF;PL
fotografi	fotografiet	N;DEF;SG
steinsopp	steinsoppane	N;DEF;PL
flyselskap	flyselskap	N;NDEF;PL
pukkel	pukkelen	N;DEF;SG
kritikk	kritikkane	N;DEF;PL
natur	naturen	N;DEF;SG
nederlandsk	nederlandske	N;DEF;SG+PL
padde	paddene	N;DEF;PL
tape	tapane	N;DEF;PL
latin	latinen	N;DEF;SG
alkan	alkana	N;DEF;PL
ferde	ferdast	V;NFIN;PASS
setebelte	setebelta	N;DEF;PL
multiplikasjon	multiplikasjonen	N;DEF;SG
jordskjelv	jordskjelvet	N;DEF;SG
magnetisk	magnetiske	N;DEF;SG+PL
venn	vennene	N;DEF;PL
hevde	hevde	V;IMP
vanskeleg	vanskelegaste	ADJ;SPRL;DEF
sylinder	sylindrane	N;DEF;PL
oppdaga	oppdagast	V;NFIN;PASS
detektiv	detektivane	N;DEF;PL
ufatteleg	ufattelegast	ADJ;SPRL;NDEF
skyting	skytingar	N;NDEF;PL
seia	sa	V;PST
samisk	samisk	ADJ;NEUT;SG
ekstremist	ekstremistar	N;NDEF;PL
tunnelbane	tunnelbana	N;DEF;SG
lufttett	lufttette	N;DEF;SG+PL
lett	lette	N;DEF;SG+PL
teknologisk	teknologiske	N;DEF;SG+PL
presang	presangar	N;NDEF;PL
tunne	tunne	V;IMP
kasino	kasinoet	N;DEF;SG
fyrverkeri	fyrverkeri	N;NDEF;PL
forstad	forstadene	N;DEF;PL
resymé	resymé	N;NDEF;PL
moped	mopedar	N;NDEF;PL
senegalesar	senegalesarane	N;DEF;PL
kunstig	kunstige	N;DEF;SG+PL
bom	bommen	N;DEF;SG
diameter	diameterane	N;DEF;PL
operasjon	operasjonar	N;NDEF;PL
drammensar	drammensarane	N;DEF;PL
upopulær	upopulært	ADJ;NEUT;SG
tene	tener	V;PRS
kapsel	kapslane	N;DEF;PL
lokomotiv	lokomotiva	N;DEF;PL
ekspedisjon	ekspedisjonar	N;NDEF;PL
rekne	reknast	V;NFIN;PASS
sal	salen	N;DEF;SG
sjølvstende	sjølvstenda	N;DEF;PL
teleskopisk	teleskopiske	N;DEF;SG+PL
konvolutt	konvoluttar	N;NDEF;PL
tena	tener	V;PRS
tablett	tabletten	N;DEF;SG
bryst	brystet	N;DEF;SG
art	arter	N;NDEF;PL
container	containeren	N;DEF;SG
abbed	abbedar	N;NDEF;PL
tunna	tunnast	V;NFIN;PASS
vaskemaskin	vaskemaskiner	N;NDEF;PL
sanddyne	sanddyner	N;NDEF;PL
gruppe	gruppene	N;DEF;PL
naudsynt	naudsynt	ADJ;NDEF;SG
vaksen	vakse	ADJ;NEUT
termostat	termostatar	N;NDEF;PL
målmann	målmannen	N;DEF;SG
sjokolade	sjokoladar	N;NDEF;PL
akillessen	akillessena	N;DEF;SG
relativ	relative	N;DEF;SG+PL
varme	varmen	N;DEF;SG
strømpe	strømpene	N;DEF;PL
svike	svik	V;PRS
hemn	hemnar	N;NDEF;PL
papegøye	papegøyar	N;NDEF;PL
produksjon	produksjonen	N;DEF;SG
meter	meter	N;NDEF;PL
vedde	vedde	V;IMP
torv	torver	N;NDEF;PL
hagle	hagla	N;DEF;SG
måndag	måndagar	N;NDEF;PL
etterretning	etterretninga	N;DEF;SG
tredel	tredelen	N;DEF;SG
trollkvinne	trollkvinnene	N;DEF;PL
håpefull	håpefulle	N;DEF;SG+PL
legering	legeringane	N;DEF;PL
etan	etanet	N;DEF;SG
påskelilje	påskeliljene	N;DEF;PL
garderobeskap	garderobeskapa	N;DEF;PL
visdomstann	visdomstanner	N;NDEF;PL
menneskeleg	menneskeleg	ADJ;NDEF;SG
papir	papiret	N;DEF;SG
appelsintre	appelsintrea	N;DEF;PL
reddast	reddast	V;IMP
ambassadør	ambassadørar	N;NDEF;PL
krone	kronar	V;PRS
jazz	jazzen	N;DEF;SG
pronomen	pronomenet	N;DEF;SG
kne	knea	N;DEF;PL
pass	passet	N;DEF;SG
fornying	fornyinga	N;DEF;SG
marmor	marmoren	N;DEF;SG
sakna	saknar	V;PRS
troll	trolla	N;DEF;PL
luftfartøy	luftfartøyet	N;DEF;SG
styrka	styrk	V;IMP
gøyme	gøymast	V;NFIN;PASS
intim	intime	N;DEF;SG+PL
krigar	krigarane	N;DEF;PL
foss	fossar	N;NDEF;PL
jernmalm	jernmalmen	N;DEF;SG
rasere	raserer	V;PRS
hestehale	hestehalen	N;DEF;SG
fjell	fjella	N;DEF;PL
delta	deltaa	N;DEF;PL
general	generalar	N;NDEF;PL
bilbelte	bilbelta	N;DEF;PL
arbeidsgivar	arbeidsgivaren	N;DEF;SG
vøla	vøl	V;IMP
angolan	angolanane	N;DEF;PL
ranar	ranarar	N;NDEF;PL
sitje	sitjast	V;NFIN;PASS
fønikisk	fønikisk	ADJ;NEUT;SG
mordvåpen	mordvåpenet	N;DEF;SG
delikatesse	delikatessa	N;DEF;SG
kolera	koleraen	N;DEF;SG
nattpotte	nattpotta	N;DEF;SG
molekylær	molekylære	N;DEF;SG+PL
talsmann	talsmannen	N;DEF;SG
belizar	belizaren	N;DEF;SG
drake	drakar	N;NDEF;PL
påskeegg	påskeegget	N;DEF;SG
venstre	venstre	ADJ;SG+PL
drammensar	drammensaren	N;DEF;SG
situasjon	situasjonane	N;DEF;PL
amfetamin	amfetaminet	N;DEF;SG
flystripe	flystripa	N;DEF;SG
skilta	skilta	V;PST
venleg	venleg	ADJ;NDEF;SG
hakekross	hakekrossane	N;DEF;PL
dekk	dekket	N;DEF;SG
råolje	råoljen	N;DEF;SG
låg	låge	N;DEF;SG+PL
spion	spionar	N;NDEF;PL
centimeter	centimetrane	N;DEF;PL
adressat	adressaten	N;DEF;SG
interiør	interiør	N;NDEF;PL
julegåve	julegåvene	N;DEF;PL
syrar	syraren	N;DEF;SG
armeniar	armeniarar	N;NDEF;PL
kommersiell	kommersielle	N;DEF;SG+PL
peika	peik	V;IMP
rauv	rauvene	N;DEF;PL
lêr	lêr	N;NDEF;PL
venleik	venleikar	N;NDEF;PL
jungel	jungelane	N;DEF;PL
indonesiar	indonesiaren	N;DEF;SG
restaurering	restaureringane	N;DEF;PL
TV	TV-ar	N;NDEF;PL
haitiar	haitiaren	N;DEF;SG
edelgass	edelgassen	N;DEF;SG
himmelseng	himmelsenga	N;DEF;SG
kivi	kiviar	N;NDEF;PL
fargeblyant	fargeblyanten	N;DEF;SG
streng	strenger	N;NDEF;PL
karm	karmen	N;DEF;SG
trofé	trofeet	N;DEF;SG
bakeri	bakeri	N;NDEF;PL
bambus	bambusane	N;DEF;PL
oppdaga	oppdaga	V;IMP
ferd	ferda	N;DEF;SG
asiat	asiatar	N;NDEF;PL
and	anda	N;DEF;SG
nobelpris	nobelprisar	N;NDEF;PL
amfibium	amfibia	N;DEF;PL
demokrat	demokraten	N;DEF;SG
rask	raskare	ADJ;CMPR
usbekar	usbekaren	N;DEF;SG
hevda	hevda	V;PST
gløyma	gløymde	V;PST
padde	padder	N;NDEF;PL
formell	formelt	ADJ;NEUT;SG
oppvask	oppvask	N;NDEF;PL
rådgjevar	rådgjevarane	N;DEF;PL
kjole	kjolar	N;NDEF;PL
heidning	heidningar	N;NDEF;PL
vekke	vekker	V;PRS
radikal	radikalet	N;DEF;SG
aristokrat	aristokratar	N;NDEF;PL
bachelorgrad	bachelorgrada	N;DEF;SG
ingrediens	ingrediensane	N;DEF;PL
selja	seljast	V;NFIN;PASS
skjønna	skjønner	V;PRS
polynesisk	polynesiske	N;DEF;SG+PL
motorvogn	motorvognene	N;DEF;PL
forkorting	forkortingane	N;DEF;PL
snøscooter	snøscooteren	N;DEF;SG
green	greenen	N;DEF;SG
varietet	varietetane	N;DEF;PL
tolk	tolkane	N;DEF;PL
krystall	krystallet	N;DEF;SG
orkan	orkanen	N;DEF;SG
oppdrag	oppdraga	N;DEF;PL
faste	fasta	N;DEF;SG
akupunktur	akupunkturen	N;DEF;SG
kollektiv	kollektive	N;DEF;SG+PL
hjelm	hjelmen	N;DEF;SG
lekse	leksa	N;DEF;SG
slagskip	slagskipa	N;DEF;PL
bombe	bomba	V;PST
svale	svala	N;DEF;SG
nordmann	nordmennene	N;DEF;PL
mistanke	mistankane	N;DEF;PL
hestekraft	hestekrafta	N;DEF;SG
rumen	rumenar	N;NDEF;PL
skilte	skilta	V;PST
reagens	reagensar	N;NDEF;PL
fanatikar	fanatikaren	N;DEF;SG
plan	planast	ADJ;SPRL;NDEF
matematikar	matematikaren	N;DEF;SG
sanksjon	sanksjonen	N;DEF;SG
sekret	sekreta	N;DEF;PL
saftig	saftig	ADJ;NEUT;SG
beita	beitast	V;NFIN;PASS
låg	låg	ADJ;MASC+FEM
tunnelbane	tunnelbanar	N;NDEF;PL
italiensk	italienske	N;DEF;SG+PL
butan	butanet	N;DEF;SG
andlet	andletet	N;DEF;SG
utsletta	utslettar	V;PRS
hakekross	hakekrossar	N;NDEF;PL
magnolia	magnoliaar	N;NDEF;PL
sjukebil	sjukebilar	N;NDEF;PL
drøyme	drøym	V;IMP
garderobeskap	garderobeskap	N;NDEF;PL
norsk	norsk	ADJ;NDEF;SG
fiskevær	fiskeværa	N;DEF;PL
paraguayanar	paraguayanaren	N;DEF;SG
larve	larvene	N;DEF;PL
fløy	fløyer	N;NDEF;PL
slagmark	slagmarkene	N;DEF;PL
feira	feira	V;IMP
or	ora	N;DEF;SG
postboks	postboksen	N;DEF;SG
paraply	paraplyar	N;NDEF;PL
hjørne	hjørnet	N;DEF;SG
rektor	rektoren	N;DEF;SG
britisk-engelsk	britisk-engelsken	N;DEF;SG
omn	omnen	N;DEF;SG
bruka	brukar	V;PRS
spektrum	spektrumet	N;DEF;SG
langfinger	langfingeren	N;DEF;SG
restaurant	restaurantar	N;NDEF;PL
ørn	ørna	N;DEF;SG
rekne	rekna	V;PST
gammal	gammal	ADJ;MASC+FEM
folkemord	folkemord	N;NDEF;PL
regjering	regjeringa	N;DEF;SG
bloggar	bloggarar	N;NDEF;PL
sendar	sendarar	N;NDEF;PL
brøk	brøkar	N;NDEF;PL
fiolin	fiolinane	N;DEF;PL
forsøk	forsøket	N;DEF;SG
livbåt	livbåtane	N;DEF;PL
museum	museum	N;NDEF;PL
vêrmelding	vêrmeldingar	N;NDEF;PL
gjennomføra	gjennomfører	V;PRS
erme	ermet	N;DEF;SG
lønn	lønna	N;DEF;SG
garasje	garasjane	N;DEF;PL
maltesar	maltesaren	N;DEF;SG
kjend	kjend	ADJ;MASC+FEM
guatemalan	guatemalanar	N;NDEF;PL
tenke	tenkte	V;PST
statsminister	statsministrar	N;NDEF;PL
bursdag	bursdagen	N;DEF;SG
kronhjort	kronhjorten	N;DEF;SG
eining	eininga	N;DEF;SG
arkitekt	arkitekten	N;DEF;SG
skyttargrav	skyttargraver	N;NDEF;PL
rullebane	rullebanar	N;NDEF;PL
keisemd	keisemdene	N;DEF;PL
bekk	bekken	N;DEF;SG
kjøtetar	kjøtetarar	N;NDEF;PL
tank	tankane	N;DEF;PL
kanal	kanalane	N;DEF;PL
salto	saltoar	N;NDEF;PL
bloggar	bloggaren	N;DEF;SG
beskjed	beskjedane	N;DEF;PL
broder	brødrar	N;NDEF;PL
kompressor	kompressorane	N;DEF;PL
tygge	tygg	V;PRS
skatteflyktning	skatteflyktningar	N;NDEF;PL
åsyn	åsynet	N;DEF;SG
rå	råa	N;DEF;SG
konditor	konditoren	N;DEF;SG
båt	båten	N;DEF;SG
tennplugg	tennpluggar	N;NDEF;PL
asiat	asiatane	N;DEF;PL
utvikle	utviklast	V;NFIN;PASS
hekkesesong	hekkesesongar	N;NDEF;PL
forferdeleg	forferdelegast	ADJ;SPRL;NDEF
spøka	spøker	V;PRS
grei	greiast	ADJ;SPRL;NDEF
reparasjon	reparasjonen	N;DEF;SG
park	parkane	N;DEF;PL
erstatning	erstatningar	N;NDEF;PL
elbil	elbilen	N;DEF;SG
leppe	leppa	N;DEF;SG
få	få	N;DEF;SG+PL
hustru	hustruene	N;DEF;PL
åsete	åsetet	N;DEF;SG
animasjon	animasjonar	N;NDEF;PL
hake	haka	N;DEF;SG
komité	komiteen	N;DEF;SG
hærførar	hærførarar	N;NDEF;PL
sitron	sitronen	N;DEF;SG
stridsøks	stridsøksene	N;DEF;PL
bøffel	bøffelen	N;DEF;SG
hegre	hegrane	N;DEF;PL
koma	komast	V;NFIN;PASS
tastatur	tastatur	N;NDEF;PL
jarnbane	jarnbanene	N;DEF;PL
turist	turisten	N;DEF;SG
perfeksjonist	perfeksjonistane	N;DEF;PL
sfære	sfærane	N;DEF;PL
vaksen	vaksnare	ADJ;CMPR
orkan	orkanane	N;DEF;PL
adverb	adverbet	N;DEF;SG
dølja	døl	V;PRS
aseksuell	aseksuelle	N;DEF;SG+PL
fossil	fossilt	ADJ;NEUT;SG
farmasøyt	farmasøytane	N;DEF;PL
prinsipp	prinsippa	N;DEF;PL
kubanar	kubanaren	N;DEF;SG
millionær	millionæren	N;DEF;SG
terrasse	terrassar	N;NDEF;PL
tenka	tenker	V;PRS
trekant	trekantar	N;NDEF;PL
trenge	trengde	V;PST
last	lasten	N;DEF;SG
nyttår	nyttåra	N;DEF;PL
komponent	komponenten	N;DEF;SG
vegetarianar	vegetarianarar	N;NDEF;PL
støvsugar	støvsugarar	N;NDEF;PL
garderobeskap	garderobeskapet	N;DEF;SG
lang	lang	ADJ;MASC+FEM
privatfly	privatflyet	N;DEF;SG
naud	nauder	N;NDEF;PL
naturgass	naturgassen	N;DEF;SG
ecuadorianar	ecuadorianaren	N;DEF;SG
oljefelt	oljefelta	N;DEF;PL
avla	avla	V;PST
ekvatorialguinean	ekvatorialguineanar	N;NDEF;PL
betra	betrast	V;NFIN;PASS
vanleg	vanlegast	ADJ;SPRL;NDEF
irsk	irsk	ADJ;NEUT;SG
åtvara	åtvara	V;IMP
modell	modellar	N;NDEF;PL
tjukk	tjukk	ADJ;MASC+FEM
ensemble	ensembla	N;DEF;PL
felt	feltet	N;DEF;SG
iskrem	iskremen	N;DEF;SG
skilnad	skilnader	N;NDEF;PL
isfjell	isfjellet	N;DEF;SG
single	singlar	N;NDEF;PL
klisjé	klisjéen	N;DEF;SG
taktfull	taktfulle	N;DEF;SG+PL
by	byar	N;NDEF;PL
lesothoar	lesothoaren	N;DEF;SG
veik	veik	ADJ;MASC+FEM
knute	knutane	N;DEF;PL
kjole	kjolen	N;DEF;SG
sviske	sviskene	N;DEF;PL
katolikk	katolikken	N;DEF;SG
drivstoff	drivstoffa	N;DEF;PL
handledd	handleddet	N;DEF;SG
konklusjon	konklusjonen	N;DEF;SG
ynskje	ynskjer	V;PRS
gen	genet	N;DEF;SG
rund	rundt	ADJ;NEUT;SG
filologi	filologien	N;DEF;SG
regnskog	regnskogane	N;DEF;PL
president	presidentane	N;DEF;PL
storleik	storleikane	N;DEF;PL
uvanleg	uvanlegaste	ADJ;SPRL;DEF
nordlys	nordlys	N;NDEF;PL
armeniar	armeniarane	N;DEF;PL
afrikanar	afrikanaren	N;DEF;SG
parodi	parodiane	N;DEF;PL
rockering	rockeringar	N;NDEF;PL
plakk	plakket	N;DEF;SG
stele	stal	V;PST
bandasje	bandasjen	N;DEF;SG
vinnar	vinnarane	N;DEF;PL
akne	aknen	N;DEF;SG
svak	svake	N;DEF;SG+PL
korsett	korsett	N;NDEF;PL
andorranar	andorranaren	N;DEF;SG
norsk	norskare	ADJ;CMPR
austleg	austlegaste	ADJ;SPRL;DEF
rosmarin	rosmarinane	N;DEF;PL
gløyme	gløymast	V;NFIN;PASS
bagasjerom	bagasjerom	N;NDEF;PL
ornitologisk	ornitologisk	ADJ;NEUT;SG
gullfisk	gullfiskar	N;NDEF;PL
verdifull	verdifullt	ADJ;NEUT;SG
kraftverk	kraftverk	N;NDEF;PL
karm	karmar	N;NDEF;PL
kose	kosa	V;PST
hjelpemiddel	hjelpemiddel	N;NDEF;PL
par	paret	N;DEF;SG
dagstur	dagsturar	N;NDEF;PL
mørk	mørkt	ADJ;NEUT
inntrykk	inntrykka	N;DEF;PL
praktisk	praktisk	ADJ;NEUT;SG
disippel	disiplar	N;NDEF;PL
nyttårsdag	nyttårsdagen	N;DEF;SG
idrett	idrettane	N;DEF;PL
gje	gjevast	V;NFIN;PASS
sitja	sitjast	V;NFIN;PASS
seremoni	seremonien	N;DEF;SG
kafé	kafeen	N;DEF;SG
older	oldrene	N;DEF;PL
kaos	kaoset	N;DEF;SG
ljota	laut	V;PST
nypotet	nypotetar	N;NDEF;PL
mikrobiolog	mikrobiologen	N;DEF;SG
leopard	leopardar	N;NDEF;PL
gipsbandasje	gipsbandasjar	N;NDEF;PL
karriere	karrierane	N;DEF;PL
vente	venta	V;PST
tekst	tekster	N;NDEF;PL
forbløffa	forbløffar	V;PRS
livmor	livmorer	N;NDEF;PL
heite	het	V;PST
granitt	granittane	N;DEF;PL
sjekk	sjekken	N;DEF;SG
arbeidsgivar	arbeidsgivarar	N;NDEF;PL
multiplum	multiplum	N;NDEF;PL
tankskip	tankskip	N;NDEF;PL
salig	salig	ADJ;NDEF;SG
gasse	gassane	N;DEF;PL
forhandling	forhandlingar	N;NDEF;PL
bok	boka	N;DEF;SG
jødisk	jødisk	ADJ;NDEF;SG
møbel	møbel	N;NDEF;PL
linse	linsa	N;DEF;SG
forsiktig	forsiktige	N;DEF;SG+PL
armé	arméar	N;NDEF;PL
supermakt	supermakter	N;NDEF;PL
brun	brunaste	ADJ;SPRL;DEF
upolitisk	upolitiske	N;DEF;SG+PL
gammal	eldre	ADJ;CMPR
sanning	sanninga	N;DEF;SG
fjernkontroll	fjernkontrollane	N;DEF;PL
yoghurt	yoghurtar	N;NDEF;PL
pianist	pianisten	N;DEF;SG
koseleg	koselege	N;DEF;SG+PL
publisitet	publisiteten	N;DEF;SG
dis	disen	N;DEF;SG
makedoniar	makedoniarar	N;NDEF;PL
offer	offer	N;NDEF;PL
seksuell	seksuelt	ADJ;NEUT
gløyma	gløymast	V;NFIN;PASS
akademi	akademia	N;DEF;PL
vendbar	vendbare	N;DEF;SG+PL
privat	privat	ADJ;NEUT;SG
abstrakt	abstrakta	N;DEF;PL
etymologi	etymologien	N;DEF;SG
kronisk	kroniske	N;DEF;SG+PL
ønskje	ønskjast	V;NFIN;PASS
kontakt	kontaktar	N;NDEF;PL
datavirus	datavirus	N;NDEF;PL
tongan	tonganen	N;DEF;SG
kompleks	komplekse	N;DEF;SG+PL
forbetre	forbetra	V;PST
kjøkken	kjøkken	N;NDEF;PL
seksualitet	seksualiteten	N;DEF;SG
jukeboks	jukeboksen	N;DEF;SG
kollega	kollegaen	N;DEF;SG
sjukepleiar	sjukepleiarar	N;NDEF;PL
pølse	pølser	N;NDEF;PL
massiv	massivt	ADJ;NEUT;SG
gaffeltruck	gaffeltruckar	N;NDEF;PL
skal	skalet	N;DEF;SG
trollmann	trollmenn	N;NDEF;PL
kostarikanar	kostarikanarane	N;DEF;PL
gjera	gjorde	V;PST
europear	europearar	N;NDEF;PL
hai	haiar	N;NDEF;PL
ven	vene	N;DEF;SG+PL
katedral	katedralar	N;NDEF;PL
kanon	kanonar	N;NDEF;PL
baby	babyen	N;DEF;SG
trofé	troféen	N;DEF;SG
identisk	identiske	N;DEF;SG+PL
kø	køane	N;DEF;PL
bever	beverane	N;DEF;PL
open	opne	N;DEF;SG+PL
kinesar	kinesarane	N;DEF;PL
dato	datoane	N;DEF;PL
røykdukkar	røykdukkarane	N;DEF;PL
mannfolk	mannfolk	N;NDEF;PL
kenguru	kenguruane	N;DEF;PL
behageleg	behagelegast	ADJ;SPRL;NDEF
bera	ber	V;PRS
ambulanse	ambulansane	N;DEF;PL
bysantin	bysantinane	N;DEF;PL
astronom	astronomane	N;DEF;PL
keisarpingvin	keisarpingvinen	N;DEF;SG
gjeng	gjengane	N;DEF;PL
samfunn	samfunna	N;DEF;PL
følga	følger	V;PRS
gull	gullet	N;DEF;SG
skodespel	skodespelet	N;DEF;SG
trikk	trikkar	N;NDEF;PL
sysken	sysken	N;NDEF;PL
diskotek	diskotek	N;NDEF;PL
moldvarp	moldvarpar	N;NDEF;PL
bokmål	bokmålet	N;DEF;SG
vakuum	vakuum	N;NDEF;PL
ekvator	ekvatorar	N;NDEF;PL
operasjon	operasjonane	N;DEF;PL
turve	turvast	V;NFIN;PASS
tortur	torturar	N;NDEF;PL
gjerde	gjerde	N;NDEF;PL
krangel	krangelet	N;DEF;SG
husdyr	husdyr	N;NDEF;PL
uer	uerane	N;DEF;PL
byråkrat	byråkratane	N;DEF;PL
tut	tuten	N;DEF;SG
herskar	herskaren	N;DEF;SG
bregne	bregnen	N;DEF;SG
eliminera	eliminerast	V;NFIN;PASS
steppe	steppene	N;DEF;PL
navle	navlar	N;NDEF;PL
andlet	andleta	N;DEF;PL
ikon	ikonet	N;DEF;SG
agenda	agendaer	N;NDEF;PL
bukse	buksene	N;DEF;PL
traktor	traktorane	N;DEF;PL
petriskål	petriskåler	N;NDEF;PL
fabrikk	fabrikkane	N;DEF;PL
falsk	falske	N;DEF;SG+PL
vietnamesar	vietnamesarar	N;NDEF;PL
basar	basarar	N;NDEF;PL
slutta	sluttast	V;NFIN;PASS
ungar	ungarane	N;DEF;PL
akne	aknar	N;NDEF;PL
himmel	himmelane	N;DEF;PL
anorakk	anorakkane	N;DEF;PL
hudlege	hudlegane	N;DEF;PL
basalt	basaltar	N;NDEF;PL
bergart	bergarten	N;DEF;SG
repertoar	repertoar	N;NDEF;PL
tyrkar	tyrkarar	N;NDEF;PL
terrasse	terrassen	N;DEF;SG
ansvar	ansvaret	N;DEF;SG
portugis	portugisane	N;DEF;PL
kome	kom	V;PST
antiguanar	antiguanarane	N;DEF;PL
romantikar	romantikaren	N;DEF;SG
shorts	shortsen	N;DEF;SG
blomsterpotte	blomsterpottene	N;DEF;PL
kateter	kateteret	N;DEF;SG
trafikkork	trafikkorkane	N;DEF;PL
tid	tider	N;NDEF;PL
metropol	metropolen	N;DEF;SG
kjenna	kjenner	V;PRS
brennbar	brennbare	N;DEF;SG+PL
graviditet	graviditeten	N;DEF;SG
kinesar	kinesaren	N;DEF;SG
protestantisk	protestantiske	N;DEF;SG+PL
vøle	vølast	V;NFIN;PASS
symje	sym	V;IMP
smeltepunkt	smeltepunktet	N;DEF;SG
blære	blærene	N;DEF;PL
feil	feil	N;NDEF;PL
minimal	minimale	N;DEF;SG+PL
peng	pengane	N;DEF;PL
tromme	tromma	N;DEF;SG
tannpirkar	tannpirkaren	N;DEF;SG
kurs	kursen	N;DEF;SG
tradisjon	tradisjonen	N;DEF;SG
aspekt	aspektet	N;DEF;SG
bekk	bekkene	N;DEF;PL
sjukepleiar	sjukepleiarane	N;DEF;PL
konsa	konsast	V;NFIN;PASS
satirisk	satirisk	ADJ;NEUT;SG
kolonne	kolonnar	N;NDEF;PL
sjakt	sjakta	N;DEF;SG
ende	endar	V;PRS
sjokoladeplate	sjokoladeplater	N;NDEF;PL
ligge	ligg	V;IMP
skytsengel	skytsenglane	N;DEF;PL
politikar	politikarar	N;NDEF;PL
sukker	sukker	N;NDEF;PL
territorium	territoria	N;DEF;PL
skodespelar	skodespelarane	N;DEF;PL
tendens	tendensar	N;NDEF;PL
by	byen	N;DEF;SG
sjukehus	sjukehuset	N;DEF;SG
obo	oboen	N;DEF;SG
polynesiar	polynesiarar	N;NDEF;PL
burda	burdast	V;NFIN;PASS
helg	helgene	N;DEF;PL
operette	operettane	N;DEF;PL
kostbar	kostbare	N;DEF;SG+PL
nordkoreanar	nordkoreanarar	N;NDEF;PL
svik	svik	N;NDEF;PL
kvinne	kvinna	N;DEF;SG
sirkel	sirklar	N;NDEF;PL
isolator	isolatoren	N;DEF;SG
hinduisme	hinduismen	N;DEF;SG
marknad	marknadane	N;DEF;PL
bombefly	bombefly	N;NDEF;PL
ønske	ønskast	V;NFIN;PASS
nymfoman	nymfomane	N;DEF;SG+PL
apparat	apparat	N;NDEF;PL
diaré	diarear	N;NDEF;PL
krasj	krasjane	N;DEF;PL
ateistisk	ateistisk	ADJ;NEUT;SG
jamaicanar	jamaicanaren	N;DEF;SG
notat	notatet	N;DEF;SG
kasta	kastast	V;NFIN;PASS
valuta	valutaane	N;DEF;PL
diaré	diaréar	N;NDEF;PL
pinse	pinsene	N;DEF;PL
relasjon	relasjonane	N;DEF;PL
strømpebukse	strømpebuksene	N;DEF;PL
kylling	kyllingen	N;DEF;SG
kilometer	kilometerane	N;DEF;PL
årelate	årelat	V;IMP
avkastning	avkastningar	N;NDEF;PL
sørkorean	sørkoreanar	N;NDEF;PL
gitar	gitaren	N;DEF;SG
bygga	bygger	V;PRS
ørliten	ørvesle	ADJ;DEF;SG
balalaika	balalaikaen	N;DEF;SG
slektskap	slektskapet	N;DEF;SG
karikatur	karikaturen	N;DEF;SG
grave	gravast	V;NFIN;PASS
truverdig	truverdig	ADJ;NDEF;SG
strategisk	strategiske	N;DEF;SG+PL
bane	banen	N;DEF;SG
forsvara	forsvarast	V;NFIN;PASS
laurdag	laurdagar	N;NDEF;PL
ektepar	ekteparet	N;DEF;SG
a	a-ar	N;NDEF;PL
partikkel	partikkelen	N;DEF;SG
skomakar	skomakarane	N;DEF;PL
stele	stelen	N;DEF;SG
mumie	mumiane	N;DEF;PL
jernbane	jernbaner	N;NDEF;PL
skina	skinast	V;NFIN;PASS
kunstnar	kunstnarane	N;DEF;PL
ynske	ynska	N;DEF;PL
naturressurs	naturressursane	N;DEF;PL
mager	magert	ADJ;NEUT;SG
fallskjerm	fallskjermar	N;NDEF;PL
teljing	teljinga	N;DEF;SG
samfunn	samfunn	N;NDEF;PL
vatn	vatnet	N;DEF;SG
sektor	sektoren	N;DEF;SG
skvadron	skvadronane	N;DEF;PL
politi	politiet	N;DEF;SG
moden	modne	N;DEF;SG+PL
larve	larver	N;NDEF;PL
teaterstykke	teaterstykka	N;DEF;PL
latterleg	latterlege	N;DEF;SG+PL
upolitisk	upolitisk	ADJ;NDEF;NEUT;SG
partikkel	partiklar	N;NDEF;PL
diagnose	diagnosane	N;DEF;PL
dørmatte	dørmatta	N;DEF;SG
vernehjelm	vernehjelmen	N;DEF;SG
stare	staren	N;DEF;SG
alkohol	alkoholar	N;NDEF;PL
årsak	årsakene	N;DEF;PL
firedel	firedelane	N;DEF;PL
armbrøst	armbrøstane	N;DEF;PL
superlativ	superlativar	N;NDEF;PL
bibliofil	bibliofilar	N;NDEF;PL
bankett	banketten	N;DEF;SG
slektning	slektningar	N;NDEF;PL
reservehjul	reservehjul	N;NDEF;PL
motorsykkel	motorsyklane	N;DEF;PL
stål	stålet	N;DEF;SG
sjuk	sjukare	ADJ;CMPR
forum	forum	N;NDEF;PL
detta	datt	V;PST
åre	årer	N;NDEF;PL
snøskred	snøskred	N;NDEF;PL
taxi	taxiar	N;NDEF;PL
undersøkje	undersøk	V;IMP
herskare	herskaren	N;DEF;SG
fest	festar	N;NDEF;PL
nøtt	nøtter	N;NDEF;PL
evolusjonær	evolusjonære	N;DEF;SG+PL
pinse	pinsane	N;DEF;PL
landssvik	landssvika	N;DEF;PL
landssvikar	landssvikarar	N;NDEF;PL
hand	hender	N;NDEF;PL
tjern	tjern	N;NDEF;PL
la	lét	V;PST
sykkelsti	sykkelstiar	N;NDEF;PL
positiv	positivt	ADJ;NEUT;SG
karibisk	karibiske	N;DEF;SG+PL
detta	dett	V;PRS
vrak	vraket	N;DEF;SG
vegetarianar	vegetarianaren	N;DEF;SG
diktator	diktatoren	N;DEF;SG
marsbuar	marsbuarar	N;NDEF;PL
irlendar	irlendarar	N;NDEF;PL
etasje	etasjane	N;DEF;PL
desimalkomma	desimalkommaet	N;DEF;SG
fengsel	fengsel	N;NDEF;PL
tyda	tyder	V;PRS
arving	arvingane	N;DEF;PL
farar	fararar	N;NDEF;PL
kalla	kallar	V;PRS
bruneiar	bruneiaren	N;DEF;SG
polynesiar	polynesiaren	N;DEF;SG
konsentrasjon	konsentrasjonane	N;DEF;PL
tenåring	tenåringar	N;NDEF;PL
råolje	råoljar	N;NDEF;PL
sukkerbete	sukkerbetar	N;NDEF;PL
balltre	balltret	N;DEF;SG
hyene	hyenen	N;DEF;SG
klimaendring	klimaendringar	N;NDEF;PL
sjøkart	sjøkarta	N;DEF;PL
framdrift	framdrifta	N;DEF;SG
veide	veidde	V;PST
influensa	influensaer	N;NDEF;PL
kjevle	kjevlast	V;NFIN;PASS
postkontor	postkontor	N;NDEF;PL
musikar	musikarane	N;DEF;PL
kynisme	kynismen	N;DEF;SG
kongle	kongler	N;NDEF;PL
ljos	ljosa	N;DEF;PL
kabriolet	kabrioletar	N;NDEF;PL
akademikar	akademikarane	N;DEF;PL
bakteriolog	bakteriologane	N;DEF;PL
savanne	savannen	N;DEF;SG
bibliotekar	bibliotekarar	N;NDEF;PL
banke	bankar	N;NDEF;PL
oseanisk	oseanisk	ADJ;NEUT;SG
vadefugl	vadefuglar	N;NDEF;PL
invasjon	invasjonen	N;DEF;SG
oppblåsbar	oppblåsbare	N;DEF;SG+PL
topp	toppar	N;NDEF;PL
tatovere	tatover	V;IMP
rytme	rytmane	N;DEF;PL
greia	grei	V;IMP
kjøttdeig	kjøttdeigen	N;DEF;SG
ramn	ramnar	N;NDEF;PL
kunstverk	kunstverket	N;DEF;SG
historikar	historikarane	N;DEF;PL
vakuum	vakuuma	N;DEF;PL
statskupp	statskuppa	N;DEF;PL
krydder	krydder	N;NDEF;PL
tibetanar	tibetanarane	N;DEF;PL
boggi	boggiar	N;NDEF;PL
kinn	kinna	N;DEF;PL
hawaiar	hawaiaren	N;DEF;SG
karantene	karantenar	N;NDEF;PL
bauxitt	bauxitten	N;DEF;SG
lov	lova	N;DEF;SG
ekstraordinær	ekstraordinære	N;DEF;SG+PL
åtvara	åtvarar	V;PRS
folkemord	folkemordet	N;DEF;SG
kunst	kunstene	N;DEF;PL
god	god	ADJ;MASC+FEM
mauritaniar	mauritaniaren	N;DEF;SG
kaldbrann	kaldbrannen	N;DEF;SG
gjeva	gjevast	V;NFIN;PASS
vaskemiddel	vaskemiddelet	N;DEF;SG
drone	dronen	N;DEF;SG
art	artene	N;DEF;PL
omgjevnad	omgjevnadar	N;NDEF;PL
herskar	herskarane	N;DEF;PL
rike	rika	N;DEF;PL
skoggrense	skoggrensa	N;DEF;SG
helg	helga	N;DEF;SG
dildo	dildoane	N;DEF;PL
akillessene	akillessenene	N;DEF;PL
næringsrik	næringsrike	N;DEF;SG+PL
farleg	farleg	ADJ;NDEF;SG
mandel	mandelen	N;DEF;SG
interiør	interiøra	N;DEF;PL
øvre	øvst	ADJ;SPRL;NDEF
teppe	teppe	N;NDEF;PL
reservedel	reservedelane	N;DEF;PL
peika	peika	V;PST
rattstamme	rattstammer	N;NDEF;PL
sein	seinast	ADJ;SPRL;NDEF
arving	arvingen	N;DEF;SG
time	timar	N;NDEF;PL
turkis	turkisen	N;DEF;SG
tysk	tysk	ADJ;NEUT;SG
midt	midten	N;DEF;SG
prinsipp	prinsipp	N;NDEF;PL
arsen	arsenet	N;DEF;SG
aluminiumsfolie	aluminiumsfoliane	N;DEF;PL
gelé	geléen	N;DEF;SG
syklisk	sykliske	N;DEF;SG+PL
ho	hoer	N;NDEF;PL
påskedag	påskedagane	N;DEF;PL
løp	løpa	N;DEF;PL
containerskip	containerskipet	N;DEF;SG
suppe	suppa	N;DEF;SG
skrivekrampe	skrivekrampane	N;DEF;PL
kontor	kontora	N;DEF;PL
garderobe	garderobane	N;DEF;PL
betaling	betalinga	N;DEF;SG
kamera	kameraa	N;DEF;PL
studium	studia	N;DEF;PL
bokhylle	bokhylla	N;DEF;SG
vase	vasen	N;DEF;SG
germansk	germansk	ADJ;NEUT;SG
symptom	symptomet	N;DEF;SG
parti	partia	N;DEF;PL
bryllaup	bryllaup	N;NDEF;PL
bluse	blusene	N;DEF;PL
madagassar	madagassarane	N;DEF;PL
vitskap	vitskapane	N;DEF;PL
addisjon	addisjonen	N;DEF;SG
ringe	ringde	V;PST
femling	femlingane	N;DEF;PL
halvdel	halvdelar	N;NDEF;PL
prest	prestane	N;DEF;PL
karbondioksid	karbondioksidet	N;DEF;SG
venleik	venleikane	N;DEF;PL
rullebane	rullebanen	N;DEF;SG
bibel	bibelen	N;DEF;SG
or	orane	N;DEF;PL
video	videoen	N;DEF;SG
engelsk	engelskare	ADJ;CMPR
vurdering	vurderingar	N;NDEF;PL
synonym	synonym	ADJ;MASC+FEM
snøras	snørasa	N;DEF;PL
krevje	krev	V;PRS
haglgevær	haglgevær	N;NDEF;PL
lang	lengste	ADJ;SPRL;DEF
tannlækjar	tannlækjarane	N;DEF;PL
serleg	serlegare	ADJ;CMPR
miniskjørt	miniskjørta	N;DEF;PL
lærepenge	lærepengane	N;DEF;PL
madagassar	madagassaren	N;DEF;SG
dominikar	dominikarane	N;DEF;PL
framtid	framtida	N;DEF;SG
konisk	koniske	N;DEF;SG+PL
atmosfære	atmosfærar	N;NDEF;PL
pingvin	pingvinar	N;NDEF;PL
kjent	kjent	ADJ;NDEF;SG
vitne	vitna	N;DEF;PL
karpe	karpene	N;DEF;PL
kjæledyr	kjæledyret	N;DEF;SG
monark	monarkar	N;NDEF;PL
syrar	syrarar	N;NDEF;PL
jackpot	jackpoten	N;DEF;SG
øydar	øydarar	N;NDEF;PL
fønikisk	fønikiske	N;DEF;SG+PL
hending	hendingar	N;NDEF;PL
erkebiskop	erkebiskopen	N;DEF;SG
abort	abortane	N;DEF;PL
påverka	påverkar	V;PRS
kjærast	kjærastane	N;DEF;PL
volum	volum	N;NDEF;PL
ringja	ringjer	V;PRS
opna	opna	V;PST
oseanograf	oseanografen	N;DEF;SG
ulykke	ulykka	N;DEF;SG
idé	idéar	N;NDEF;PL
gjeve	gjev	V;IMP
hugse	hugsa	V;PST
ung	yngste	ADJ;SPRL;DEF
førarhund	førarhundane	N;DEF;PL
gir	giret	N;DEF;SG
åtaka	åtakast	V;NFIN;PASS
herskar	herskarar	N;NDEF;PL
saudiar	saudiarar	N;NDEF;PL
ål	ålen	N;DEF;SG
minneblom	minneblomane	N;DEF;PL
forsvarsspelar	forsvarsspelarane	N;DEF;PL
stemme	stemmene	N;DEF;PL
hypnotisør	hypnotisørar	N;NDEF;PL
ha	har	V;PRS
liggja	ligg	V;IMP
moralsk	moralske	N;DEF;SG+PL
kikert	kikertane	N;DEF;PL
kugalskap	kugalskapen	N;DEF;SG
eksempel	eksempla	N;DEF;PL
konflikt	konfliktane	N;DEF;PL
nominell	nominelle	N;DEF;SG+PL
forsvar	forsvar	N;NDEF;PL
hjerne	hjernar	N;NDEF;PL
strekk	strekkane	N;DEF;PL
prinsipiell	prinsipielt	ADJ;NEUT;SG
bagasjerom	bagasjeromma	N;DEF;PL
vakuum	vakuumet	N;DEF;SG
potet	poteter	N;NDEF;PL
eid	eida	N;DEF;PL
trenga	treng	V;PRS
stilig	stiligaste	ADJ;SPRL;DEF
salomonar	salomonaren	N;DEF;SG
identisk	identisk	ADJ;NEUT;SG
fabrikant	fabrikantane	N;DEF;PL
verkeleg	verkelegast	ADJ;SPRL;NDEF
bokstavleg	bokstavlege	N;DEF;SG+PL
armé	arméen	N;DEF;SG
lesbe	lesber	N;NDEF;PL
elektrisitet	elektrisiteten	N;DEF;SG
hudlege	hudlegar	N;NDEF;PL
passasjer	passasjerane	N;DEF;PL
finne	finnen	N;DEF;SG
fregatt	fregatten	N;DEF;SG
bølgje	bølgjer	N;NDEF;PL
klima	klimaa	N;DEF;PL
anarki	anarki	N;NDEF;PL
tynn	tynne	N;DEF;SG+PL
snabel	snablar	N;NDEF;PL
feilaktig	feilaktige	N;DEF;SG+PL
butt	buttast	ADJ;SPRL;NDEF
ende	enden	N;DEF;SG
utvikla	utvikla	V;PST
amøbe	amøben	N;DEF;SG
aristokrat	aristokraten	N;DEF;SG
vennleg	vennlegast	ADJ;SPRL;NDEF
invadera	invaderast	V;NFIN;PASS
kaliumnitrat	kaliumnitratet	N;DEF;SG
munn	munnane	N;DEF;PL
nyttelast	nyttelastane	N;DEF;PL
øydelegging	øydeleggingane	N;DEF;PL
angrep	angrepa	N;DEF;PL
protein	proteinet	N;DEF;SG
mannleg	mannleg	ADJ;NDEF;SG
tørst	tørste	N;DEF;SG+PL
mudderflate	mudderflata	N;DEF;SG
astronomisk	astronomiske	N;DEF;SG+PL
regime	regimet	N;DEF;SG
diagram	diagrammet	N;DEF;SG
bokstavleg	bokstavlegast	ADJ;SPRL;NDEF
spansk	spansken	N;DEF;SG
hengebru	hengebrua	N;DEF;SG
slips	slips	N;NDEF;PL
finne	finn	V;PRS
brunsj	brunsjar	N;NDEF;PL
samarbeide	samarbeid	V;IMP
forferdeleg	forferdelegare	ADJ;CMPR
stryking	strykingane	N;DEF;PL
oseanograf	oseanografar	N;NDEF;PL
lakris	lakriset	N;DEF;SG
omgivnad	omgivnaden	N;DEF;SG
BH	BH-en	N;DEF;SG
slengja	sleng	V;IMP
trilling	trillingen	N;DEF;SG
visdomstann	visdomstannene	N;DEF;PL
plan	plant	ADJ;NEUT
kopp	koppar	N;NDEF;PL
nabolag	nabolag	N;NDEF;PL
uregistrert	uregistrert	ADJ;NEUT;SG
nepalsk	nepalske	N;DEF;SG+PL
tett	tettast	ADJ;SPRL;NDEF
zoomobjektiv	zoomobjektiv	N;NDEF;PL
sosiolog	sosiologane	N;DEF;PL
generasjon	generasjonen	N;DEF;SG
resultat	resultata	N;DEF;PL
kalla	kalla	V;PST
matte	matter	N;NDEF;PL
tsjekkisk	tsjekkisk	ADJ;NEUT;SG
tilsetning	tilsetninga	N;DEF;SG
stridsøks	stridsøksane	N;DEF;PL
tungetale	tungetala	N;DEF;SG
tante	tanta	N;DEF;SG
sitja	sat	V;PST
bjørnebær	bjørnebæret	N;DEF;SG
kvelartak	kvelartak	N;NDEF;PL
pinleg	pinlegare	ADJ;CMPR
ongel	ongelar	N;NDEF;PL
engsteleg	engstelegare	ADJ;CMPR
eplepai	eplepaiane	N;DEF;PL
golf	golfen	N;DEF;SG
muskuløs	muskuløse	N;DEF;SG+PL
julaftan	julaftanar	N;NDEF;PL
notatbok	notatbøker	N;NDEF;PL
konspirasjonsteori	konspirasjonsteoriar	N;NDEF;PL
nederlag	nederlag	N;NDEF;PL
nyre	nyrer	N;NDEF;PL
våpen	våpenet	N;DEF;SG
mauritiar	mauritiarane	N;DEF;PL
spekkhoggar	spekkhoggaren	N;DEF;SG
metafor	metaforen	N;DEF;SG
revebjølle	revebjøller	N;NDEF;PL
mikrobiolog	mikrobiologar	N;NDEF;PL
brems	bremsane	N;DEF;PL
tyrkar	tyrkaren	N;DEF;SG
liten	små	ADJ;PL
hard	hardaste	ADJ;SPRL;DEF
betaling	betalingar	N;NDEF;PL
kontroversiell	kontroversielle	N;DEF;SG+PL
solbrend	solbrende	N;DEF;SG+PL
våt	våte	N;DEF;SG+PL
forbetra	forbetra	V;PST
morter	morterar	N;NDEF;PL
erobra	erobra	V;IMP
talg	talga	N;DEF;SG
heil	heile	N;DEF;SG+PL
forkasta	forkasta	V;PST
tablett	tablettane	N;DEF;PL
lauk	laukane	N;DEF;PL
abdikasjon	abdikasjonar	N;NDEF;PL
praktisk	praktiske	N;DEF;SG+PL
start	starten	N;DEF;SG
kartografi	kartografien	N;DEF;SG
rust	rusta	N;DEF;SG
algebra	algebraen	N;DEF;SG
mexican	mexicanar	N;NDEF;PL
søndag	søndagar	N;NDEF;PL
frukost	frukosten	N;DEF;SG
syntese	syntesar	N;NDEF;PL
kvintett	kvintettar	N;NDEF;PL
vedde	veddar	V;PRS
trio	trioar	N;NDEF;PL
ongel	ongelen	N;DEF;SG
komme	kom	V;IMP
bølgje	bølgjene	N;DEF;PL
kvadratkilometer	kvadratkilometrane	N;DEF;PL
radikal	radikale	N;DEF;SG+PL
tomat	tomatar	N;NDEF;PL
sandbanke	sandbankane	N;DEF;PL
halde	haldast	V;NFIN;PASS
tørke	tørken	N;DEF;SG
spak	spaken	N;DEF;SG
vert	verten	N;DEF;SG
trengast	trongst	V;PST
fortid	fortider	N;NDEF;PL
oppvaskmiddel	oppvaskmidla	N;DEF;PL
sitte	sit	V;PRS
gjenstand	gjenstanden	N;DEF;SG
lisens	lisensane	N;DEF;PL
trekant	trekantane	N;DEF;PL
nauruar	nauruarane	N;DEF;PL
kviterussar	kviterussaren	N;DEF;SG
guinean	guineanane	N;DEF;PL
skulptur	skulpturen	N;DEF;SG
kenyanar	kenyanarar	N;NDEF;PL
lommelerke	lommelerkene	N;DEF;PL
fritte	frittane	N;DEF;PL
klesbørste	klesbørstar	N;NDEF;PL
sjarmere	sjarmerer	V;PRS
sukkerfri	sukkerfrie	N;DEF;SG+PL
