zolowera	adzazolowera	V;PL;3;FUT
ika	mumaika	V;SG;2;PRS
werenga	mumawerenga	V;PL;2;PRS
sauka	adzasauka	V;PL;3;FUT
kwata	ndimakwata	V;SG;1;PRS
sesa	munasesa	V;SG;2;PST
masula	ndimamasula	V;SG;1;PRS
bzala	ndidzabzala	V;SG;1;FUT
khudza	anakhudza	V;PL;3;PST
iwala	munaiwala	V;SG;2;PST
posa	amaposa	V;PL;3;PRS
yankha	mudzayankha	V;PL;2;FUT
pemba	ndimapemba	V;SG;1;PRS
peza	anapeza	V;SG;3;PST
kondwa	anakondwa	V;SG;3;PST
tsutsa	ndimatsutsa	V;SG;1;PRS
yankhula	amayankhula	V;PL;3;PRS
pempha	kupempha	V;NFIN
bwera	mudzabwera	V;PL;2;FUT
fupika	munafupika	V;PL;2;PST
badwa	kubadwa	V;NFIN
bisala	timabisala	V;PL;1;PRS
sauka	mumasauka	V;PL;2;PRS
masula	tinamasula	V;PL;1;PST
leka	mudzaleka	V;SG;2;FUT
ntchito	adzantchito	V;PL;3;FUT
weruza	mudzaweruza	V;SG;2;FUT
luma	amaluma	V;PL;3;PRS
chenjera	mudzachenjera	V;PL;2;FUT
yera	anayera	V;SG;3;PST
langa	timalanga	V;PL;1;PRS
baya	ndidzabaya	V;SG;1;FUT
funsani	amafunsani	V;PL;3;PRS
kamba	mudzakamba	V;SG;2;FUT
lankhula	tidzalankhula	V;PL;1;FUT
yala	amayala	V;SG;3;PRS
bwera	anabwera	V;PL;3;PST
menya	ndimamenya	V;SG;1;PRS
langa	munalanga	V;SG;2;PST
mwa	munamwa	V;PL;2;PST
tembenuka	tidzatembenuka	V;PL;1;FUT
tembenuka	kutembenuka	V;NFIN
da	adzada	V;SG;3;FUT
iwala	amaiwala	V;PL;3;PRS
leka	adzaleka	V;PL;3;FUT
boola	anaboola	V;PL;3;PST
tsogola	mudzatsogola	V;SG;2;FUT
itana	tinaitana	V;PL;1;PST
yera	adzayera	V;SG;3;FUT
gwa	adzagwa	V;SG;3;FUT
yamba	mumayamba	V;SG;2;PRS
chira	kuchira	V;NFIN
nyoza	mudzanyoza	V;SG;2;FUT
nama	kunama	V;NFIN
kumbuka	ndinakumbuka	V;SG;1;PST
sonkha	ndimasonkha	V;SG;1;PRS
ika	mudzaika	V;PL;2;FUT
kalamba	timakalamba	V;PL;1;PRS
kalamba	munakalamba	V;SG;2;PST
gula	mudzagula	V;SG;2;FUT
ba	ndidzaba	V;SG;1;FUT
chinya	adzachinya	V;SG;3;FUT
reruka	anareruka	V;PL;3;PST
nyenga	mudzanyenga	V;SG;2;FUT
pitani	mumapitani	V;PL;2;PRS
tsiriza	adzatsiriza	V;SG;3;FUT
ng'amba	mumang'amba	V;PL;2;PRS
mera	tidzamera	V;PL;1;FUT
yandkira	munayandkira	V;PL;2;PST
dya	kudya	V;NFIN
thokoza	mumathokoza	V;PL;2;PRS
khudza	kukhudza	V;NFIN
menya	timamenya	V;PL;1;PRS
thira	tinathira	V;PL;1;PST
taya	tidzataya	V;PL;1;FUT
koma	munakoma	V;PL;2;PST
funsani	mudzafunsani	V;SG;2;FUT
tembenuka	munatembenuka	V;PL;2;PST
phunzira	adzaphunzira	V;SG;3;FUT
lankhula	kulankhula	V;NFIN
imwa	adzaimwa	V;SG;3;FUT
dwala	tinadwala	V;PL;1;PST
dzala	munadzala	V;PL;2;PST
tseka	amatseka	V;PL;3;PRS
posa	adzaposa	V;SG;3;FUT
lonjeza	mudzalonjeza	V;PL;2;FUT
sanduka	amasanduka	V;SG;3;PRS
mera	munamera	V;SG;2;PST
bisa	kubisa	V;NFIN
sonkha	adzasonkha	V;SG;3;FUT
omba	munaomba	V;PL;2;PST
sintha	timasintha	V;PL;1;PRS
masula	mumamasula	V;SG;2;PRS
badwa	mudzabadwa	V;PL;2;FUT
ocha	ndimaocha	V;SG;1;PRS
lonjeza	mudzalonjeza	V;SG;2;FUT
khuta	ndimakhuta	V;SG;1;PRS
konda	mumakonda	V;PL;2;PRS
langa	analanga	V;SG;3;PST
puma	munapuma	V;SG;2;PST
tsika	amatsika	V;PL;3;PRS
khudza	mudzakhudza	V;PL;2;FUT
kwiya	adzakwiya	V;SG;3;FUT
posa	tinaposa	V;PL;1;PST
nunkha	mumanunkha	V;SG;2;PRS
thawa	anathawa	V;SG;3;PST
fewa	timafewa	V;PL;1;PRS
kana	ndidzakana	V;SG;1;FUT
phunzira	kuphunzira	V;NFIN
thamanga	amathamanga	V;SG;3;PRS
yamika	anayamika	V;PL;3;PST
yerekeza	adzayerekeza	V;SG;3;FUT
dziwa	ndimadziwa	V;SG;1;PRS
khudza	tidzakhudza	V;PL;1;FUT
lonjeza	ndidzalonjeza	V;SG;1;FUT
tuluka	ndidzatuluka	V;SG;1;FUT
tsogola	amatsogola	V;PL;3;PRS
sankha	mudzasankha	V;PL;2;FUT
patsa	mudzapatsa	V;PL;2;FUT
dzala	anadzala	V;SG;3;PST
khuta	kukhuta	V;NFIN
sonkha	munasonkha	V;SG;2;PST
kola	adzakola	V;SG;3;FUT
gaya	amagaya	V;PL;3;PRS
mva	timamva	V;PL;1;PRS
kalamba	adzakalamba	V;PL;3;FUT
mera	kumera	V;NFIN
cha	mudzacha	V;SG;2;FUT
zunza	mumazunza	V;SG;2;PRS
sirira	amasirira	V;PL;3;PRS
chepa	mudzachepa	V;PL;2;FUT
thandiza	mumathandiza	V;SG;2;PRS
itana	kuitana	V;NFIN
dzola	mumadzola	V;SG;2;PRS
sewera	munasewera	V;SG;2;PST
topa	timatopa	V;PL;1;PRS
khulupira	munakhulupira	V;SG;2;PST
tcha	mumatcha	V;SG;2;PRS
yera	amayera	V;PL;3;PRS
opsya	ndimaopsya	V;SG;1;PRS
bala	mumabala	V;PL;2;PRS
tsogola	mumatsogola	V;PL;2;PRS
opsya	mumaopsya	V;PL;2;PRS
kwera	ndinakwera	V;SG;1;PST
ongola	mumaongola	V;PL;2;PRS
samala	anasamala	V;PL;3;PST
baya	anabaya	V;SG;3;PST
nena	adzanena	V;PL;3;FUT
laika	mudzalaika	V;PL;2;FUT
sokoneza	anasokoneza	V;PL;3;PST
sazika	mudzasazika	V;SG;2;FUT
chepa	munachepa	V;SG;2;PST
kamba	amakamba	V;SG;3;PRS
vina	amavina	V;SG;3;PRS
kwiya	mumakwiya	V;SG;2;PRS
batiza	munabatiza	V;PL;2;PST
nyada	ananyada	V;SG;3;PST
menya	anamenya	V;PL;3;PST
werenga	ndinawerenga	V;SG;1;PST
kumbuka	ndimakumbuka	V;SG;1;PRS
choka	mumachoka	V;PL;2;PRS
nena	mumanena	V;SG;2;PRS
seka	munaseka	V;SG;2;PST
werenga	munawerenga	V;PL;2;PST
tuma	munatuma	V;PL;2;PST
thawa	munathawa	V;PL;2;PST
bala	anabala	V;SG;3;PST
pereka	amapereka	V;PL;3;PRS
ika	ndinaika	V;SG;1;PST
dzuka	ndimadzuka	V;SG;1;PRS
pinda	ndinapinda	V;SG;1;PST
topa	mudzatopa	V;SG;2;FUT
bvala	anabvala	V;SG;3;PST
cha	anacha	V;SG;3;PST
thamanga	amathamanga	V;PL;3;PRS
tanthauza	timatanthauza	V;PL;1;PRS
bweza	munabweza	V;PL;2;PST
imba	kuimba	V;NFIN
dzola	anadzola	V;SG;3;PST
dikira	munadikira	V;PL;2;PST
landa	mumalanda	V;PL;2;PRS
sewera	adzasewera	V;SG;3;FUT
yaka	kuyaka	V;NFIN
thira	kuthira	V;NFIN
opsya	munaopsya	V;SG;2;PST
fana	ndinafana	V;SG;1;PST
funa	anafuna	V;PL;3;PST
sunga	munasunga	V;SG;2;PST
tsanzira	munatsanzira	V;PL;2;PST
yesa	amayesa	V;SG;3;PRS
kayika	tinakayika	V;PL;1;PST
khumudwa	mumakhumudwa	V;PL;2;PRS
patsa	amapatsa	V;PL;3;PRS
nama	mumanama	V;PL;2;PRS
nyamula	tidzanyamula	V;PL;1;FUT
yang'ana	mumayang'ana	V;PL;2;PRS
kana	tinakana	V;PL;1;PST
fuula	ndinafuula	V;SG;1;PST
kayika	tidzakayika	V;PL;1;FUT
tcha	mudzatcha	V;SG;2;FUT
funa	mumafuna	V;PL;2;PRS
pinda	adzapinda	V;PL;3;FUT
sinja	timasinja	V;PL;1;PRS
chimwa	mumachimwa	V;SG;2;PRS
tola	timatola	V;PL;1;PRS
tuluka	tinatuluka	V;PL;1;PST
masula	ndidzamasula	V;SG;1;FUT
werenga	tinawerenga	V;PL;1;PST
oloka	mudzaoloka	V;SG;2;FUT
lemba	adzalemba	V;SG;3;FUT
pinda	ndimapinda	V;SG;1;PRS
gwira	mumagwira	V;SG;2;PRS
seka	ndimaseka	V;SG;1;PRS
kwana	mudzakwana	V;SG;2;FUT
wala	mumawala	V;SG;2;PRS
gaya	mudzagaya	V;PL;2;FUT
tentha	tinatentha	V;PL;1;PST
nama	adzanama	V;PL;3;FUT
imba	tinaimba	V;PL;1;PST
biriwira	mudzabiriwira	V;SG;2;FUT
nama	mumanama	V;SG;2;PRS
chuluka	tidzachuluka	V;PL;1;FUT
chira	tidzachira	V;PL;1;FUT
badwa	amabadwa	V;PL;3;PRS
thira	mudzathira	V;PL;2;FUT
gwa	mumagwa	V;SG;2;PRS
bwera	tinabwera	V;PL;1;PST
tseka	ndimatseka	V;SG;1;PRS
kola	adzakola	V;PL;3;FUT
kondwa	ndidzakondwa	V;SG;1;FUT
gwa	amagwa	V;PL;3;PRS
iwala	ndidzaiwala	V;SG;1;FUT
funsani	kufunsani	V;NFIN
tanthauza	mumatanthauza	V;SG;2;PRS
bisa	timabisa	V;PL;1;PRS
sesa	kusesa	V;NFIN
opsya	amaopsya	V;PL;3;PRS
nyansa	tidzanyansa	V;PL;1;FUT
ocha	anaocha	V;PL;3;PST
pha	adzapha	V;PL;3;FUT
zunza	adzazunza	V;SG;3;FUT
imwa	adzaimwa	V;PL;3;FUT
sowa	amasowa	V;PL;3;PRS
pala	munapala	V;SG;2;PST
tsogola	tidzatsogola	V;PL;1;FUT
mwa	timamwa	V;PL;1;PRS
gaya	kugaya	V;NFIN
cheza	ndidzacheza	V;SG;1;FUT
chapa	munachapa	V;PL;2;PST
kwera	tidzakwera	V;PL;1;FUT
lipira	amalipira	V;SG;3;PRS
talika	munatalika	V;PL;2;PST
pala	ndidzapala	V;SG;1;FUT
khuta	amakhuta	V;PL;3;PRS
fa	munafa	V;SG;2;PST
nama	tidzanama	V;PL;1;FUT
oloka	mudzaoloka	V;PL;2;FUT
sefuka	amasefuka	V;PL;3;PRS
zungulira	timazungulira	V;PL;1;PRS
khuta	anakhuta	V;PL;3;PST
tha	ndimatha	V;SG;1;PRS
sewera	ndinasewera	V;SG;1;PST
tsala	munatsala	V;PL;2;PST
yamika	munayamika	V;PL;2;PST
laika	analaika	V;SG;3;PST
pinda	mumapinda	V;PL;2;PRS
iwala	timaiwala	V;PL;1;PRS
psya	munapsya	V;SG;2;PST
fewa	mudzafewa	V;SG;2;FUT
gula	adzagula	V;PL;3;FUT
gwa	munagwa	V;PL;2;PST
ona	ndinaona	V;SG;1;PST
thandiza	tidzathandiza	V;PL;1;FUT
tha	mudzatha	V;SG;2;FUT
khulupira	anakhulupira	V;PL;3;PST
tuma	mumatuma	V;PL;2;PRS
nena	mudzanena	V;SG;2;FUT
ocha	amaocha	V;PL;3;PRS
biriwira	amabiriwira	V;SG;3;PRS
thandiza	adzathandiza	V;PL;3;FUT
landa	analanda	V;SG;3;PST
kwana	kukwana	V;NFIN
chapa	mumachapa	V;SG;2;PRS
nyenga	amanyenga	V;SG;3;PRS
yenda	munayenda	V;SG;2;PST
dzuka	anadzuka	V;PL;3;PST
dwala	anadwala	V;PL;3;PST
boola	ndimaboola	V;SG;1;PRS
nyada	ananyada	V;PL;3;PST
patsa	kupatsa	V;NFIN
dziwa	kudziwa	V;NFIN
gogoda	adzagogoda	V;SG;3;FUT
kula	amakula	V;SG;3;PRS
sirira	ndidzasirira	V;SG;1;FUT
nama	tinanama	V;PL;1;PST
tseka	munatseka	V;PL;2;PST
sowa	munasowa	V;SG;2;PST
kayika	mudzakayika	V;PL;2;FUT
dziwa	mumadziwa	V;SG;2;PRS
oloka	amaoloka	V;SG;3;PRS
mva	adzamva	V;SG;3;FUT
phika	ndimaphika	V;SG;1;PRS
swa	munaswa	V;SG;2;PST
chira	amachira	V;PL;3;PRS
itana	anaitana	V;SG;3;PST
sintha	ndidzasintha	V;SG;1;FUT
menya	munamenya	V;PL;2;PST
ponda	ndimaponda	V;SG;1;PRS
zungulira	mudzazungulira	V;SG;2;FUT
kola	timakola	V;PL;1;PRS
samala	ndidzasamala	V;SG;1;FUT
fika	kufika	V;NFIN
bvala	mumabvala	V;PL;2;PRS
imwa	ndidzaimwa	V;SG;1;FUT
nyada	kunyada	V;NFIN
imwa	mumaimwa	V;SG;2;PRS
chimwa	munachimwa	V;PL;2;PST
zindikira	munazindikira	V;SG;2;PST
werenga	anawerenga	V;PL;3;PST
gunda	ndidzagunda	V;SG;1;FUT
chedwa	amachedwa	V;PL;3;PRS
omba	mudzaomba	V;SG;2;FUT
yaka	tinayaka	V;PL;1;PST
chenjera	amachenjera	V;SG;3;PRS
nyenga	mudzanyenga	V;PL;2;FUT
yang'ana	munayang'ana	V;SG;2;PST
khazika	amakhazika	V;PL;3;PRS
fupika	anafupika	V;SG;3;PST
sintha	mudzasintha	V;SG;2;FUT
siya	amasiya	V;PL;3;PRS
thyola	mudzathyola	V;PL;2;FUT
sunga	ndidzasunga	V;SG;1;FUT
lonjeza	amalonjeza	V;SG;3;PRS
chita	anachita	V;SG;3;PST
pweteka	anapweteka	V;PL;3;PST
pemba	mudzapemba	V;PL;2;FUT
ng'amba	tidzang'amba	V;PL;1;FUT
yera	ndimayera	V;SG;1;PRS
thira	anathira	V;SG;3;PST
thandiza	adzathandiza	V;SG;3;FUT
bweza	munabweza	V;SG;2;PST
dzala	adzadzala	V;PL;3;FUT
chepa	munachepa	V;PL;2;PST
fuula	mumafuula	V;SG;2;PRS
tsata	ndimatsata	V;SG;1;PRS
chinya	munachinya	V;PL;2;PST
kwera	mumakwera	V;PL;2;PRS
fupika	kufupika	V;NFIN
pita	amapita	V;SG;3;PRS
yamba	munayamba	V;SG;2;PST
dikira	ndimadikira	V;SG;1;PRS
choka	amachoka	V;PL;3;PRS
kayika	timakayika	V;PL;1;PRS
yanja	anayanja	V;PL;3;PST
fuula	ndimafuula	V;SG;1;PRS
dza	amadza	V;SG;3;PRS
pindula	kupindula	V;NFIN
lamula	amalamula	V;PL;3;PRS
choka	adzachoka	V;PL;3;FUT
dzala	tinadzala	V;PL;1;PST
yanja	adzayanja	V;PL;3;FUT
oloka	adzaoloka	V;PL;3;FUT
tenga	ndimatenga	V;SG;1;PRS
thokoza	mumathokoza	V;SG;2;PRS
gwira	munagwira	V;PL;2;PST
nyamula	amanyamula	V;SG;3;PRS
konza	amakonza	V;PL;3;PRS
thamanga	anathamanga	V;PL;3;PST
baya	mumabaya	V;PL;2;PRS
khudza	timakhudza	V;PL;1;PRS
tsegula	amatsegula	V;SG;3;PRS
zizira	kuzizira	V;NFIN
mwa	mumamwa	V;SG;2;PRS
pambana	adzapambana	V;PL;3;FUT
tuma	ndimatuma	V;SG;1;PRS
zizira	amazizira	V;PL;3;PRS
pha	kupha	V;NFIN
ntchito	amantchito	V;PL;3;PRS
bweza	mumabweza	V;PL;2;PRS
zungulira	amazungulira	V;PL;3;PRS
lakwa	munalakwa	V;SG;2;PST
thamanga	ndimathamanga	V;SG;1;PRS
imwa	kuimwa	V;NFIN
bisa	adzabisa	V;PL;3;FUT
pita	adzapita	V;SG;3;FUT
pha	ndinapha	V;SG;1;PST
luma	mudzaluma	V;SG;2;FUT
chinya	tidzachinya	V;PL;1;FUT
ntchito	kuntchito	V;NFIN
bzala	kubzala	V;NFIN
mva	adzamva	V;PL;3;FUT
yanja	munayanja	V;SG;2;PST
bvoma	adzabvoma	V;PL;3;FUT
fulumira	ndidzafulumira	V;SG;1;FUT
dandaula	tidzadandaula	V;PL;1;FUT
lira	kulira	V;NFIN
lungama	timalungama	V;PL;1;PRS
tsiriza	adzatsiriza	V;PL;3;FUT
sanduka	mumasanduka	V;PL;2;PRS
ng'amba	ndinang'amba	V;SG;1;PST
tola	tidzatola	V;PL;1;FUT
boola	kuboola	V;NFIN
yenera	mudzayenera	V;SG;2;FUT
lankhula	adzalankhula	V;SG;3;FUT
fulumira	amafulumira	V;SG;3;PRS
chenjera	adzachenjera	V;PL;3;FUT
dza	mumadza	V;PL;2;PRS
dwala	kudwala	V;NFIN
sewera	mumasewera	V;PL;2;PRS
pala	munapala	V;PL;2;PST
tentha	munatentha	V;PL;2;PST
dzola	mudzadzola	V;PL;2;FUT
pambana	munapambana	V;PL;2;PST
tanthauza	munatanthauza	V;PL;2;PST
kola	tinakola	V;PL;1;PST
pulumutsa	tinapulumutsa	V;PL;1;PST
ponda	adzaponda	V;SG;3;FUT
chenjera	anachenjera	V;PL;3;PST
kayika	ndinakayika	V;SG;1;PST
tsala	adzatsala	V;PL;3;FUT
fana	adzafana	V;PL;3;FUT
reruka	tidzareruka	V;PL;1;FUT
fika	mumafika	V;SG;2;PRS
tsogola	ndinatsogola	V;SG;1;PST
taya	kutaya	V;NFIN
laika	adzalaika	V;PL;3;FUT
tsanzira	ndimatsanzira	V;SG;1;PRS
kwiya	tidzakwiya	V;PL;1;FUT
zolowera	mudzazolowera	V;SG;2;FUT
bisala	mudzabisala	V;SG;2;FUT
fa	mudzafa	V;SG;2;FUT
thawa	timathawa	V;PL;1;PRS
koma	tidzakoma	V;PL;1;FUT
tembenuka	adzatembenuka	V;PL;3;FUT
dala	anadala	V;SG;3;PST
landa	mudzalanda	V;PL;2;FUT
sonkha	mudzasonkha	V;PL;2;FUT
reruka	kureruka	V;NFIN
topa	mumatopa	V;SG;2;PRS
choka	mumachoka	V;SG;2;PRS
psya	mudzapsya	V;SG;2;FUT
pulumutsa	tidzapulumutsa	V;PL;1;FUT
ng'amba	tinang'amba	V;PL;1;PST
zindikira	ndinazindikira	V;SG;1;PST
yankha	tinayankha	V;PL;1;PST
laika	mudzalaika	V;SG;2;FUT
ongola	anaongola	V;PL;3;PST
ng'amba	munang'amba	V;PL;2;PST
mera	munamera	V;PL;2;PST
tsanzira	anatsanzira	V;SG;3;PST
fupika	ndidzafupika	V;SG;1;FUT
zungulira	mumazungulira	V;PL;2;PRS
ongola	mudzaongola	V;SG;2;FUT
phunzira	amaphunzira	V;PL;3;PRS
nyoza	kunyoza	V;NFIN
khulupira	anakhulupira	V;SG;3;PST
omba	anaomba	V;PL;3;PST
tsika	amatsika	V;SG;3;PRS
bvala	anabvala	V;PL;3;PST
tola	amatola	V;PL;3;PRS
bzala	adzabzala	V;SG;3;FUT
tsutsa	tidzatsutsa	V;PL;1;FUT
thyola	munathyola	V;PL;2;PST
yaka	munayaka	V;PL;2;PST
dzuka	mudzadzuka	V;SG;2;FUT
yanja	munayanja	V;PL;2;PST
sakaniza	ndinasakaniza	V;SG;1;PST
sauka	ndimasauka	V;SG;1;PRS
zunza	mudzazunza	V;PL;2;FUT
taya	mudzataya	V;SG;2;FUT
bvoma	munabvoma	V;SG;2;PST
weruza	ndimaweruza	V;SG;1;PRS
chimwa	anachimwa	V;SG;3;PST
nena	mudzanena	V;PL;2;FUT
funsani	timafunsani	V;PL;1;PRS
sokoneza	munasokoneza	V;PL;2;PST
pala	mumapala	V;PL;2;PRS
fulumira	tinafulumira	V;PL;1;PST
bweza	ndimabweza	V;SG;1;PRS
thawa	tidzathawa	V;PL;1;FUT
maliza	anamaliza	V;PL;3;PST
chuluka	timachuluka	V;PL;1;PRS
zizira	munazizira	V;SG;2;PST
topa	mumatopa	V;PL;2;PRS
gona	munagona	V;PL;2;PST
phika	kuphika	V;NFIN
yamika	amayamika	V;PL;3;PRS
peza	amapeza	V;SG;3;PRS
chita	amachita	V;SG;3;PRS
nyenga	adzanyenga	V;SG;3;FUT
dandaula	kudandaula	V;NFIN
iwala	kuiwala	V;NFIN
khudza	mumakhudza	V;PL;2;PRS
werenga	mudzawerenga	V;SG;2;FUT
da	munada	V;PL;2;PST
zizira	ndidzazizira	V;SG;1;FUT
sonkha	mudzasonkha	V;SG;2;FUT
pindula	ndinapindula	V;SG;1;PST
bvuta	tidzabvuta	V;PL;1;FUT
koma	munakoma	V;SG;2;PST
biriwira	tidzabiriwira	V;PL;1;FUT
dwala	ndimadwala	V;SG;1;PRS
opsya	timaopsya	V;PL;1;PRS
thandiza	munathandiza	V;PL;2;PST
nyada	tinanyada	V;PL;1;PST
weruza	amaweruza	V;SG;3;PRS
ganiza	tinaganiza	V;PL;1;PST
chinya	mumachinya	V;SG;2;PRS
funa	ndidzafuna	V;SG;1;FUT
gula	kugula	V;NFIN
bvina	ndinabvina	V;SG;1;PST
sankha	mudzasankha	V;SG;2;FUT
boola	mudzaboola	V;PL;2;FUT
chimwa	mumachimwa	V;PL;2;PRS
khudza	mumakhudza	V;SG;2;PRS
lowa	ndimalowa	V;SG;1;PRS
tola	mumatola	V;SG;2;PRS
dya	ndimadya	V;SG;1;PRS
luma	tinaluma	V;PL;1;PST
imba	munaimba	V;PL;2;PST
pereka	tinapereka	V;PL;1;PST
fa	timafa	V;PL;1;PRS
sonkha	ndinasonkha	V;SG;1;PST
yembekeza	munayembekeza	V;PL;2;PST
ona	munaona	V;PL;2;PST
yamba	ndimayamba	V;SG;1;PRS
dya	anadya	V;SG;3;PST
fulumira	mumafulumira	V;SG;2;PRS
nunkha	ananunkha	V;SG;3;PST
nyenga	ananyenga	V;SG;3;PST
tenga	amatenga	V;PL;3;PRS
pemba	timapemba	V;PL;1;PRS
sesa	amasesa	V;SG;3;PRS
omba	timaomba	V;PL;1;PRS
thokoza	anathokoza	V;SG;3;PST
thawa	amathawa	V;PL;3;PRS
sunga	adzasunga	V;SG;3;FUT
chepa	mudzachepa	V;SG;2;FUT
kalamba	amakalamba	V;PL;3;PRS
bzala	munabzala	V;PL;2;PST
zolowera	ndimazolowera	V;SG;1;PRS
pinda	amapinda	V;SG;3;PRS
pitani	ndidzapitani	V;SG;1;FUT
weruza	munaweruza	V;SG;2;PST
yankhula	timayankhula	V;PL;1;PRS
lonjeza	adzalonjeza	V;SG;3;FUT
thandiza	kuthandiza	V;NFIN
lowa	tidzalowa	V;PL;1;FUT
bvala	mudzabvala	V;PL;2;FUT
laika	timalaika	V;PL;1;PRS
dzala	munadzala	V;SG;2;PST
posa	anaposa	V;SG;3;PST
luma	mudzaluma	V;PL;2;FUT
posa	ndinaposa	V;SG;1;PST
seka	anaseka	V;SG;3;PST
lira	mudzalira	V;SG;2;FUT
siya	mumasiya	V;PL;2;PRS
lonjeza	ndinalonjeza	V;SG;1;PST
luma	analuma	V;SG;3;PST
thawa	mumathawa	V;PL;2;PRS
sanduka	ndidzasanduka	V;SG;1;FUT
pereka	anapereka	V;PL;3;PST
yesa	mudzayesa	V;SG;2;FUT
lima	ndidzalima	V;SG;1;FUT
menya	adzamenya	V;PL;3;FUT
bala	mudzabala	V;SG;2;FUT
pala	mudzapala	V;SG;2;FUT
gogoda	anagogoda	V;SG;3;PST
patsa	adzapatsa	V;SG;3;FUT
pempha	amapempha	V;PL;3;PRS
weruza	adzaweruza	V;PL;3;FUT
konda	ndidzakonda	V;SG;1;FUT
vina	timavina	V;PL;1;PRS
puma	ndimapuma	V;SG;1;PRS
fika	anafika	V;SG;3;PST
yankhula	munayankhula	V;PL;2;PST
mva	mudzamva	V;PL;2;FUT
yesa	adzayesa	V;SG;3;FUT
sangalala	munasangalala	V;PL;2;PST
oloka	ndidzaoloka	V;SG;1;FUT
zunza	ndimazunza	V;SG;1;PRS
fa	anafa	V;SG;3;PST
sowa	mudzasowa	V;PL;2;FUT
fika	amafika	V;SG;3;PRS
kula	adzakula	V;SG;3;FUT
nyada	amanyada	V;PL;3;PRS
opsya	mudzaopsya	V;PL;2;FUT
lipira	analipira	V;SG;3;PST
talika	timatalika	V;PL;1;PRS
samala	amasamala	V;PL;3;PRS
yaka	tidzayaka	V;PL;1;FUT
bereka	adzabereka	V;SG;3;FUT
gunda	adzagunda	V;PL;3;FUT
yesa	munayesa	V;SG;2;PST
samala	amasamala	V;SG;3;PRS
bvala	timabvala	V;PL;1;PRS
manga	ndinamanga	V;SG;1;PST
baya	amabaya	V;SG;3;PRS
sewera	kusewera	V;NFIN
sankha	anasankha	V;PL;3;PST
chira	timachira	V;PL;1;PRS
bala	timabala	V;PL;1;PRS
sewera	mumasewera	V;SG;2;PRS
kana	mumakana	V;PL;2;PRS
yaka	ndimayaka	V;SG;1;PRS
landa	ndidzalanda	V;SG;1;FUT
khala	tidzakhala	V;PL;1;FUT
funa	timafuna	V;PL;1;PRS
peza	adzapeza	V;PL;3;FUT
thamanga	kuthamanga	V;NFIN
pemba	munapemba	V;PL;2;PST
pweteka	mumapweteka	V;PL;2;PRS
tentha	amatentha	V;SG;3;PRS
bwera	adzabwera	V;PL;3;FUT
mera	ndidzamera	V;SG;1;FUT
pitani	mumapitani	V;SG;2;PRS
kalamba	tidzakalamba	V;PL;1;FUT
gwa	amagwa	V;SG;3;PRS
pindula	timapindula	V;PL;1;PRS
khulupira	mudzakhulupira	V;SG;2;FUT
wala	munawala	V;PL;2;PST
dya	adzadya	V;PL;3;FUT
konza	timakonza	V;PL;1;PRS
zizira	adzazizira	V;PL;3;FUT
ika	amaika	V;PL;3;PRS
ika	adzaika	V;PL;3;FUT
yaka	mudzayaka	V;PL;2;FUT
sewera	mudzasewera	V;SG;2;FUT
tsata	mumatsata	V;SG;2;PRS
phika	tidzaphika	V;PL;1;FUT
yang'ana	adzayang'ana	V;PL;3;FUT
laika	mumalaika	V;SG;2;PRS
psya	kupsya	V;NFIN
chita	ndidzachita	V;SG;1;FUT
chira	ndidzachira	V;SG;1;FUT
sochera	mumasochera	V;PL;2;PRS
gogoda	anagogoda	V;PL;3;PST
pana	ndimapana	V;SG;1;PRS
lakwa	adzalakwa	V;SG;3;FUT
langa	adzalanga	V;SG;3;FUT
ipa	mudzaipa	V;SG;2;FUT
chedwa	adzachedwa	V;SG;3;FUT
seka	kuseka	V;NFIN
bwera	timabwera	V;PL;1;PRS
weruza	ndidzaweruza	V;SG;1;FUT
kwata	mudzakwata	V;SG;2;FUT
omba	adzaomba	V;SG;3;FUT
chimwa	ndinachimwa	V;SG;1;PST
bereka	amabereka	V;PL;3;PRS
lakwa	mudzalakwa	V;SG;2;FUT
sakaniza	ndidzasakaniza	V;SG;1;FUT
gula	tidzagula	V;PL;1;FUT
gwira	mudzagwira	V;PL;2;FUT
kwana	ndidzakwana	V;SG;1;FUT
tuluka	mumatuluka	V;SG;2;PRS
cheka	ndimacheka	V;SG;1;PRS
oloka	amaoloka	V;PL;3;PRS
patsa	mumapatsa	V;SG;2;PRS
ika	munaika	V;SG;2;PST
sazika	adzasazika	V;SG;3;FUT
biriwira	munabiriwira	V;SG;2;PST
yamba	timayamba	V;PL;1;PRS
pweteka	adzapweteka	V;PL;3;FUT
zindikira	amazindikira	V;SG;3;PRS
lema	amalema	V;PL;3;PRS
dza	tidzadza	V;PL;1;FUT
fuula	timafuula	V;PL;1;PRS
thyola	anathyola	V;PL;3;PST
sangalala	tinasangalala	V;PL;1;PST
sokoneza	anasokoneza	V;SG;3;PST
ima	amaima	V;PL;3;PRS
yenera	kuyenera	V;NFIN
kumbuka	tinakumbuka	V;PL;1;PST
fuula	mudzafuula	V;PL;2;FUT
pana	amapana	V;PL;3;PRS
tsanzira	munatsanzira	V;SG;2;PST
mera	tinamera	V;PL;1;PST
luma	mumaluma	V;PL;2;PRS
posa	munaposa	V;PL;2;PST
ponda	kuponda	V;NFIN
tsata	tinatsata	V;PL;1;PST
lowa	mumalowa	V;PL;2;PRS
oloka	kuoloka	V;NFIN
yerekeza	ndidzayerekeza	V;SG;1;FUT
dalira	anadalira	V;SG;3;PST
choka	mudzachoka	V;PL;2;FUT
boola	mumaboola	V;PL;2;PRS
limba	analimba	V;SG;3;PST
omba	mudzaomba	V;PL;2;FUT
gwira	kugwira	V;NFIN
talika	adzatalika	V;PL;3;FUT
pambana	amapambana	V;PL;3;PRS
da	mumada	V;SG;2;PRS
puma	ndidzapuma	V;SG;1;FUT
yala	mumayala	V;PL;2;PRS
limba	mumalimba	V;SG;2;PRS
kwata	anakwata	V;SG;3;PST
oloka	mumaoloka	V;PL;2;PRS
sefuka	amasefuka	V;SG;3;PRS
sewera	tidzasewera	V;PL;1;FUT
pha	munapha	V;SG;2;PST
da	timada	V;PL;1;PRS
lipira	ndidzalipira	V;SG;1;FUT
gogoda	kugogoda	V;NFIN
fika	ndinafika	V;SG;1;PST
reruka	anareruka	V;SG;3;PST
loia	kuloia	V;NFIN
pemba	ndinapemba	V;SG;1;PST
chira	mumachira	V;PL;2;PRS
bzala	ndimabzala	V;SG;1;PRS
lema	munalema	V;SG;2;PST
pulumutsa	ndimapulumutsa	V;SG;1;PRS
zindikira	munazindikira	V;PL;2;PST
fuula	mumafuula	V;PL;2;PRS
ponda	munaponda	V;PL;2;PST
mva	kumva	V;NFIN
sewera	mudzasewera	V;PL;2;FUT
chinya	kuchinya	V;NFIN
limba	ndimalimba	V;SG;1;PRS
sonkha	munasonkha	V;PL;2;PST
yankhula	ndidzayankhula	V;SG;1;FUT
gawa	mumagawa	V;SG;2;PRS
bvina	anabvina	V;PL;3;PST
werenga	tidzawerenga	V;PL;1;FUT
masula	timamasula	V;PL;1;PRS
tsogola	anatsogola	V;SG;3;PST
batiza	amabatiza	V;SG;3;PRS
yandkira	munayandkira	V;SG;2;PST
thira	munathira	V;PL;2;PST
yankhula	ndimayankhula	V;SG;1;PRS
sangalala	ndinasangalala	V;SG;1;PST
tentha	ndimatentha	V;SG;1;PRS
sazika	mudzasazika	V;PL;2;FUT
masula	kumasula	V;NFIN
pala	amapala	V;PL;3;PRS
yerekeza	amayerekeza	V;PL;3;PRS
dala	adzadala	V;PL;3;FUT
dza	munadza	V;PL;2;PST
kumbuka	ndidzakumbuka	V;SG;1;FUT
tola	mumatola	V;PL;2;PRS
wala	mudzawala	V;PL;2;FUT
biriwira	tinabiriwira	V;PL;1;PST
zunza	munazunza	V;SG;2;PST
yesa	ndidzayesa	V;SG;1;FUT
ona	amaona	V;PL;3;PRS
manga	adzamanga	V;PL;3;FUT
sunga	amasunga	V;PL;3;PRS
konda	timakonda	V;PL;1;PRS
bvoma	munabvoma	V;PL;2;PST
sowa	ndidzasowa	V;SG;1;FUT
pambana	mumapambana	V;SG;2;PRS
nyansa	amanyansa	V;PL;3;PRS
tanthauza	mudzatanthauza	V;PL;2;FUT
kana	amakana	V;PL;3;PRS
dalira	amadalira	V;SG;3;PRS
bvala	amabvala	V;PL;3;PRS
lakwa	ndinalakwa	V;SG;1;PST
pita	mumapita	V;SG;2;PRS
dzola	ndinadzola	V;SG;1;PST
choka	kuchoka	V;NFIN
sewera	tinasewera	V;PL;1;PST
gawa	amagawa	V;PL;3;PRS
pala	adzapala	V;SG;3;FUT
thandiza	mudzathandiza	V;SG;2;FUT
gaya	timagaya	V;PL;1;PRS
thira	amathira	V;PL;3;PRS
yala	tinayala	V;PL;1;PST
ongola	munaongola	V;SG;2;PST
lungama	mumalungama	V;SG;2;PRS
chita	anachita	V;PL;3;PST
zindikira	ndidzazindikira	V;SG;1;FUT
pindula	mudzapindula	V;SG;2;FUT
yamba	mudzayamba	V;PL;2;FUT
bala	mumabala	V;SG;2;PRS
samba	mudzasamba	V;PL;2;FUT
gwa	ndidzagwa	V;SG;1;FUT
lemba	amalemba	V;PL;3;PRS
thamanga	mudzathamanga	V;SG;2;FUT
koma	mumakoma	V;PL;2;PRS
khala	adzakhala	V;PL;3;FUT
khazika	anakhazika	V;SG;3;PST
bzala	mumabzala	V;PL;2;PRS
lipira	mumalipira	V;SG;2;PRS
kumbuka	adzakumbuka	V;SG;3;FUT
tuma	tinatuma	V;PL;1;PST
tsala	timatsala	V;PL;1;PRS
chira	anachira	V;PL;3;PST
lakwa	ndimalakwa	V;SG;1;PRS
funsani	anafunsani	V;SG;3;PST
yembekeza	amayembekeza	V;SG;3;PRS
koma	ndimakoma	V;SG;1;PRS
bweza	ndinabweza	V;SG;1;PST
dwala	mudzadwala	V;PL;2;FUT
kondwa	anakondwa	V;PL;3;PST
tseka	anatseka	V;PL;3;PST
sanduka	adzasanduka	V;SG;3;FUT
nyoza	amanyoza	V;SG;3;PRS
mwa	mumamwa	V;PL;2;PRS
gwira	timagwira	V;PL;1;PRS
lonjeza	timalonjeza	V;PL;1;PRS
tanthauza	kutanthauza	V;NFIN
ba	adzaba	V;SG;3;FUT
khumudwa	ndinakhumudwa	V;SG;1;PST
kula	mudzakula	V;SG;2;FUT
limba	munalimba	V;SG;2;PST
khuta	amakhuta	V;SG;3;PRS
thyola	adzathyola	V;SG;3;FUT
tembenuka	amatembenuka	V;PL;3;PRS
lema	adzalema	V;PL;3;FUT
biriwira	amabiriwira	V;PL;3;PRS
pweteka	amapweteka	V;PL;3;PRS
khazika	kukhazika	V;NFIN
thandiza	timathandiza	V;PL;1;PRS
reruka	mudzareruka	V;PL;2;FUT
zizira	anazizira	V;PL;3;PST
yandkira	ndinayandkira	V;SG;1;PST
koma	amakoma	V;SG;3;PRS
baya	ndimabaya	V;SG;1;PRS
ng'amba	adzang'amba	V;SG;3;FUT
bwera	munabwera	V;SG;2;PST
lenga	adzalenga	V;SG;3;FUT
tsata	mumatsata	V;PL;2;PRS
lemba	ndinalemba	V;SG;1;PST
konza	mudzakonza	V;PL;2;FUT
bala	munabala	V;PL;2;PST
swa	kuswa	V;NFIN
yang'ana	timayang'ana	V;PL;1;PRS
biriwira	munabiriwira	V;PL;2;PST
werenga	anawerenga	V;SG;3;PST
lenga	tidzalenga	V;PL;1;FUT
ona	munaona	V;SG;2;PST
dziwa	tidzadziwa	V;PL;1;FUT
limba	munalimba	V;PL;2;PST
ongola	mudzaongola	V;PL;2;FUT
kondwa	kukondwa	V;NFIN
dula	anadula	V;PL;3;PST
kwana	anakwana	V;PL;3;PST
fulumira	mumafulumira	V;PL;2;PRS
imba	adzaimba	V;SG;3;FUT
sangalala	munasangalala	V;SG;2;PST
konda	mudzakonda	V;SG;2;FUT
tsika	ndidzatsika	V;SG;1;FUT
menya	adzamenya	V;SG;3;FUT
talika	ndidzatalika	V;SG;1;FUT
yankha	ndimayankha	V;SG;1;PRS
khulupira	amakhulupira	V;SG;3;PRS
tcha	mudzatcha	V;PL;2;FUT
pana	adzapana	V;PL;3;FUT
khulupira	mumakhulupira	V;SG;2;PRS
peza	munapeza	V;PL;2;PST
lira	amalira	V;PL;3;PRS
puma	mumapuma	V;SG;2;PRS
yembekeza	tidzayembekeza	V;PL;1;FUT
