s-koʼok	s-koʼok	V;IPFV;PL;PRS
hidod̥	hihidod̥	N;PL
cewaj	ceʼecwajad	V;IPFV;PL;FUT
gegosid	gegosid	V;IPFV;PL;PRS
s-baga	s-babgad	V;IPFV;PL;FUT
ʼelidag	ʼeʼelidag	N;PL
s̥oak	soañiñ	V;IMP;PL;PRS
cicwi	cicwid	V;IPFV;SG;FUT
gaʼa	gaʼa	V;IPFV;SG;PRS
mu:	koi	V;PRF;PL;PRS
ke:k	gegokiwa	V;PRF;PL;PRS
heʼed̥kad	heʼed̥kadad	V;IPFV;SG;FUT
ʼelid	ʼelĭ	V;PRF;SG;PRS
ʼul	ʼuʼul	V;PRF;PL;PRS
dai	dai	V;PRF;SG;PRS
ca:ŋgo	ca:ŋgo	N;SG
hi:wodag	hi:wodag	N;SG
s-añi:lmagĭ	s-añi:lmagiñ	V;IMP;PL;PRS
jisk	jijsi	N;PL
hodai	hohodai	N;PL
lo:go	lolgo	V;IPFV;PL;PRS
ʼuʼad	ʼuʼad	V;PRF;PL;PRS
cuʼimad	cuʼimadiñ	V;IMP;PL;PRS
kuint	kukuint	V;IPFV;PL;PRS
wamigid	wamigidiñ	V;IMP;SG;PRS
s-padma	s-papdmañ	V;IMP;PL;PRS
pikcult	pikcultad	V;IPFV;SG;FUT
baʼa	ba:	V;PRF;PL;PRS
gegosid	gegosidad	V;IPFV;PL;FUT
ʼod̥pig	ʼoʼod̥pĭ	V;PRF;PL;PRS
heʼed̥kad	heʼed̥kad	V;IPFV;SG;PRS
ceposid	ceposidiñ	V;IMP;SG;PRS
s̥onhin	s̥onhinad	V;IPFV;PL;FUT
s-ke:gaj	s-ke:gajad	V;IPFV;PL;FUT
hewek	hewekiñ	V;IMP;PL;PRS
ʼeñigadad	ʼeʼeñigadad	V;IPFV;PL;PRS
ke:li	kekel	N;PL
gaʼa	gaʼa	V;IPFV;PL;PRS
celpig	celpig	V;IPFV;SG;PRS
gaswua	gagswuañ	V;IMP;PL;PRS
huawĭ	huhuawĭ	N;PL
wegid	wepgidad	V;IPFV;PL;FUT
s̥aʼi	s̥aʼi	N;PL
ha:l	ha:l	N;SG
wu:lo	wu:lo	N;SG
hi:nk	hi:n	V;PRF;SG;PRS
ba:ñimad	ba:bañimad	V;IPFV;PL;PRS
elpig	ʼeʼelpigiñ	V;IMP;PL;PRS
a:gid	a:gidiñ	V;IMP;PL;PRS
ta:lkomad	ta:lkomad	V;PRF;SG;PRS
pimiando	pimiando	N;PL
gatwikud̥	gagtwikud̥	N;PL
kulañmad	kuklañmadiñ	V;IMP;PL;PRS
ceposid	cecposidiñ	V;IMP;PL;PRS
waid	wai	V;PRF;SG;PRS
s-hewhogĭ	s-hewhogiñ	V;IMP;PL;PRS
cendad	cecendadad	V;IPFV;PL;FUT
nowĭ	no:nhoĭ	N;PL
cehia	cehia	N;SG
koʼa	koʼa	V;IPFV;SG;PRS
to:n	to:ton	N;PL
jewed̥mad	jewed̥madiñ	V;IMP;PL;PRS
dagkon	dagkonad	V;IPFV;SG;FUT
med̥	wo:po'iñ	V;IMP;PL;PRS
s̥a:mud	s̥a:mud	V;PRF;SG;PRS
pikcult	pipikcultiñ	V;IMP;PL;PRS
ʼoimed̥	ʼoimed̥	V;IPFV;SG;PRS
ñu:kud	ñu:kudad	V;IPFV;PL;FUT
s-ce:dagĭ	s-cecdagid	V;IPFV;PL;FUT
gaʼikud̥	gagaʼikud̥	N;PL
si:s̥p	si:s̥	V;PRF;SG;PRS
ʼeñga	ʼeñgad	V;IPFV;SG;FUT
s̥onhin	s̥onhinad	V;IPFV;SG;FUT
ke:k	ke:k	V;IPFV;SG;PRS
ñeʼe	ñei	V;PRF;SG;PRS
gaʼikud̥	gaʼikud̥	N;SG
cicwikud̥	cicwikud̥	N;PL
ʼuʼuhig	ʼuʼuhig	N;SG
s-wagima	s-wagimañ	V;IMP;SG;PRS
cicwi	cicwi	V;IPFV;PL;PRS
je:ñ	je:j	V;PRF;SG;PRS
mu:ñ	mu:ñ	N;SG
s-tohă	s-tohad	V;IPFV;SG;FUT
s-kaidag	s-kaidagad	V;IPFV;PL;FUT
hewek	hewek	V;PRF;PL;PRS
ʼu:s	ʼuʼus	N;PL
Ju:kam	Jujkam	N;PL
gaʼa	gai	V;PRF;SG;PRS
s-padma	s-papdmad	V;IPFV;PL;FUT
ʼiʼihog	ʼiʼiho	V;PRF;SG;PRS
wacwi	wapcwiñ	V;IMP;PL;PRS
a:gid	a:gidiñ	V;IMP;SG;PRS
ʼu:gk	ʼu:gkad	V;IPFV;SG;FUT
ʼi:bhĕ	ʼi:bhĕ	V;IPFV;SG;PRS
mas̥camakud̥	mas̥camakud̥	N;SG
ki:	ki:k	N;PL
ʼiʼihog	ʼiʼiho	V;PRF;PL;PRS
s-muʼuk	s-muʼumkad	V;IPFV;PL;FUT
ba:bas	ba:bas	N;PL
s-ba:bigĭ	s-ba:bigiñ	V;IMP;PL;PRS
waw	waw	N;SG
celpig	celpigad	V;IPFV;SG;FUT
ñu:kud	ñu:kud	V;PRF;SG;PRS
gegosid	hugiñ	V;IMP;PL;PRS
ʼi:e	ʼi:e	V;IPFV;PL;PRS
s-ce:dagĭ	s-cecdagĭ	V;IPFV;PL;PRS
ka:k	ka:kaʼa	N;PL
mul	ʼo:mĭ	V;PRF;PL;PRS
wegid	wegĭ	V;PRF;SG;PRS
ta:ts̥akud̥	ta:ts̥akud̥	N;PL
s-muʼuk	s-muʼumk	V;IPFV;PL;PRS
s̥a:mud	s̥a:mudiñ	V;IMP;PL;PRS
s-moik	s-moikad	V;IPFV;SG;FUT
hikck	hikck	V;IPFV;SG;PRS
celpig	celpigiñ	V;IMP;SG;PRS
huks̥an	huki	V;PRF;SG;PRS
si:s̥p	sisis̥piñ	V;IMP;PL;PRS
s-hewhogĭ	s-hewhogid	V;IPFV;SG;FUT
koʼa	hu:	V;PRF;SG;PRS
huhuʼid	huhuʼidad	V;IPFV;PL;FUT
ka:	ka:d	V;IPFV;PL;FUT
pla:njakud̥	pla:njakud̥	N;SG
wua	ju:	V;PRF;PL;PRS
hewek	hewekad	V;IPFV;PL;FUT
wu:d̥	wu:d̥	V;IPFV;PL;PRS
nolawt	nolawt	V;PRF;SG;PRS
ʼed̥apig	ʼeʼed̥apig	V;IPFV;PL;PRS
s-ba:bigĭ	s-ba:bigĭ	V;IPFV;PL;PRS
geʼej	geʼej	V;IPFV;SG;PRS
golon	goloniñ	V;IMP;SG;PRS
ku:bsmad	ku:bsmad	V;PRF;PL;PRS
si:s̥p	sisis̥pad	V;IPFV;PL;FUT
gatwid	gatwi	V;PRF;SG;PRS
na:d	na:d	V;IPFV;SG;PRS
ʼeʼeñga	ʼeʼeñga	N;SG
cicwi	cicwiñ	V;IMP;PL;PRS
ʼed̥apig	ʼed̥apig	V;IPFV;SG;PRS
ba:bas	ba:bas	N;SG
ñeʼe	ñei	V;PRF;PL;PRS
hagpig	hagpĭ	V;PRF;SG;PRS
gegosid	gegos	V;PRF;SG;PRS
s-da:pk	s-da:pk	V;IPFV;SG;PRS
ʼiʼihog	ʼiʼihogad	V;IPFV;PL;FUT
na:d	nanda	V;IPFV;PL;PRS
waid	waidiñ	V;IMP;SG;PRS
daʼa	da	V;PRF;SG;PRS
bisc	bisc	V;IPFV;PL;PRS
dahă	dadhiwua	V;PRF;PL;PRS
wamigĭ	wam	V;PRF;SG;PRS
ʼi:wagĭ	ʼi:wagĭ	N;PL
bei	bei	V;PRF;SG;PRS
ha:s̥añ	ha:s̥añ	N;SG
cipkan	cicpkaniñ	V;IMP;PL;PRS
s-heʼek	s-heʼekad	V;IPFV;PL;FUT
ceʼewidakud̥	ceʼewidakud̥	N;SG
ku:bsmad	ku:bsmadiñ	V;IMP;SG;PRS
ʼoksga	ʼoksga	N;SG
s-wihonig	s-wihonigad	V;IPFV;SG;FUT
daʼa	daʼa	V;IPFV;SG;PRS
ʼu:gk	ʼuʼugkad	V;IPFV;PL;FUT
ka:	ka:	V;PRF;PL;PRS
kuint	kuintad	V;IPFV;SG;FUT
hagpig	hahagpig	V;IPFV;PL;PRS
ʼeñigadad	ʼeʼeñigadadad	V;IPFV;PL;FUT
s̥onwuikud̥	s̥onwuikud̥	N;SG
hi:nk	hi:nkad	V;IPFV;SG;FUT
ʼoksi	ʼoʼoksi	N;PL
ʼoilmad	ʼoilmadiñ	V;IMP;SG;PRS
s̥awoñ	s̥awoñiñ	V;IMP;SG;PRS
s-ap	s-apad	V;IPFV;PL;FUT
hoa	hoha	N;PL
wopopig	wopopigad	V;IPFV;PL;FUT
s-ap	s-apiñ	V;IMP;SG;PRS
sitol	sitol	N;SG
ʼi:e	ʼi:ed	V;IPFV;SG;FUT
s̥a:mud	s̥a:mudad	V;IPFV;PL;FUT
s-hu:kĭ	s-hu:kiñ	V;IMP;SG;PRS
elpig	ʼeʼelpig	V;IPFV;PL;PRS
ʼiʼihog	ʼiʼihogiñ	V;IMP;PL;PRS
ʼoilmad	ʼoilmad	V;IPFV;SG;PRS
kuintakud̥	kukuintakud̥	N;PL
gogs	gogs	N;SG
ka:	ka:ñ	V;IMP;PL;PRS
tapial	tapial	N;SG
daʼa	ñe:ñ	V;PRF;PL;PRS
pa:nt	pa:nt	V;IPFV;SG;PRS
wuhios̥a	wuphios̥a	N;PL
a:gid	a:gid	V;IPFV;SG;PRS
kulañ	kuklañ	N;PL
heʼed̥kad	heʼed̥ka	V;PRF;SG;PRS
cu:wĭ	cu:wĭ	N;SG
s-tonĭ	s-toniñ	V;IMP;PL;PRS
wosonakud̥	wopsonakud̥	N;PL
mu:ñ	mu:ñ	N;PL
tlo:gi	tlolgi	N;PL
ʼoʼohan	ʼoʼohan	V;IPFV;PL;PRS
cu:kug	cu:kug	N;SG
gatwikud̥	gatwikud̥	N;SG
wua	wuañ	V;IMP;PL;PRS
gaʼa	gaʼañ	V;IMP;PL;PRS
giʼipig	giʼipigad	V;IPFV;PL;FUT
med̥	med̥	V;IPFV;SG;PRS
na:d	nai	V;PRF;SG;PRS
ñu:kud	ñu:kudiñ	V;IMP;SG;PRS
da:k	da:k	N;SG
s-cuk	s-cuck	V;IPFV;PL;PRS
koʼokolmad	koʼokolmad	V;IPFV;SG;PRS
ʼoimed̥	ʼoimed̥añ	V;IMP;SG;PRS
med̥	med̥	V;IPFV;SG;PRS
haiwañ	haiwañ	N;SG
s-he:pid	s-he:pid	V;IPFV;SG;PRS
pisaltakud̥	pisaltakud̥	N;SG
li:wa	li:wa	N;SG
s̥a:mud	s̥a:mudad	V;IPFV;SG;FUT
dagkon	dadgkon	V;IPFV;PL;PRS
s-we:c	s-wepc	V;IPFV;PL;PRS
ʼalidag	ʼaʼalidag	N;PL
s-ke:g	s-ke:giñ	V;IMP;PL;PRS
ʼon	ʼon	N;SG
s̥oak	s̥oak	V;IPFV;SG;PRS
pa:nt	pa:nt	V;PRF;SG;PRS
ju:k	ju:kad	V;IPFV;SG;FUT
ñeok	ñeñokad	V;IPFV;PL;FUT
ʼoilmad	ʼoilmadiñ	V;IMP;PL;PRS
s-wegĭ	s-wepegĭ	V;IPFV;PL;PRS
ʼeñigadad	ʼeñigadad	V;PRF;SG;PRS
s-baga	s-babgañ	V;IMP;PL;PRS
huhuʼid	huhuʼidad	V;IPFV;SG;FUT
mu:	mu:	V;PRF;SG;PRS
ʼonpig	ʼoʼonpigiñ	V;IMP;PL;PRS
muʼa	kodka	V;PRF;PL;PRS
wakon	wakon	V;IPFV;SG;PRS
s̥onpig	s̥onpigiñ	V;IMP;PL;PRS
si:s̥p	sisis̥	V;PRF;PL;PRS
ceggia	ceceggia	V;IPFV;PL;PRS
s-ju:k	s-ju:k	V;IPFV;SG;PRS
hagpig	hagpigad	V;IPFV;SG;FUT
kuint	kukuintad	V;IPFV;PL;FUT
woson	woso	V;PRF;SG;PRS
wamigĭ	wamigid	V;IPFV;SG;FUT
ʼoʼohan	ʼoʼohanad	V;IPFV;PL;FUT
woson	woson	V;IPFV;PL;PRS
tod̥k	tod̥kad	V;IPFV;PL;FUT
s-oam	s-oʼoamiñ	V;IMP;PL;PRS
ko:ji	kokji	N;PL
ju:k	ju:k	V;IPFV;SG;PRS
s-bi:dagĭ	s-bibdagid	V;IPFV;PL;FUT
nolawt	nolawtad	V;IPFV;PL;FUT
wainom	wainom	N;SG
wakonakud̥	wapkonakud̥	N;PL
cendad	cendadad	V;IPFV;SG;FUT
hagpig	hagpig	V;IPFV;SG;PRS
ñeok	ñeñeo	V;PRF;PL;PRS
ʼonpig	ʼoʼonpigad	V;IPFV;PL;FUT
na:d	nandaiñ	V;IMP;PL;PRS
ñeʼe	ñe'iñ	V;IMP;PL;PRS
ʼelid	ʼelid	V;IPFV;PL;PRS
lo:go	lo:goñ	V;IMP;SG;PRS
siwĭ	siwiñ	V;IMP;PL;PRS
ma:k	ma:kiñ	V;IMP;SG;PRS
s-kawk	s-kakawpkiñ	V;IMP;PL;PRS
mehĭ	mehĭ	N;PL
wu:s̥ad	wu:s̥adiñ	V;IMP;PL;PRS
koʼa	hu:	V;PRF;PL;PRS
dagkon	dagkon	V;IPFV;SG;PRS
kamis̥	kamis̥	N;SG
sitolmad	sitolmad	V;PRF;PL;PRS
ʼeñga	ʼeñgad	V;IPFV;PL;FUT
ʼoʼohana	ʼoʼohana	N;PL
we:nag	we:nag	N;SG
wakon	wapko	V;PRF;PL;PRS
dahă	dahiñ	V;IMP;PL;PRS
a:gid	a:gĭ	V;PRF;SG;PRS
wakon	wako	V;PRF;SG;PRS
keickwa	keickwañ	V;IPFV;PL;FUT
ba:b	ba:bab	N;PL
s-he:pid	s-he:pidiñ	V;IMP;PL;PRS
s̥onpig	s̥onpigad	V;IPFV;PL;FUT
hewek	hewekad	V;IPFV;SG;FUT
s-moik	s-momoikiñ	V;IMP;PL;PRS
Ci:no	Ci:no	N;SG
med̥	wo:po'iñ	V;IMP;PL;PRS
siʼi	siʼiñ	V;IMP;SG;PRS
bisc	bis	V;PRF;PL;PRS
wakon	wapkoniñ	V;IMP;PL;PRS
kaij	ce'iñ	V;IMP;SG;PRS
ʼi:e	ʼi:	V;PRF;PL;PRS
wu:s̥	wu:s̥	V;PRF;SG;PRS
pisalt	pisal	V;PRF;SG;PRS
hukpig	huhukpĭ	V;PRF;PL;PRS
maistla	mamaistla	N;PL
ka:c	we:cad	V;IPFV;PL;FUT
s-kaidag	s-kaidagiñ	V;IMP;PL;PRS
s-oam	s-oam	V;IPFV;SG;PRS
cuʼimad	cuʼimadad	V;IPFV;SG;FUT
s̥onpig	s̥onpig	V;PRF;SG;PRS
ʼoimed̥	ʼoyopoiñ	V;IMP;PL;PRS
wu:s̥ad	wu:s̥adiñ	V;IMP;SG;PRS
baʼa	ba'iñ	V;IMP;SG;PRS
s-ape	s-ape	V;IPFV;SG;PRS
s-wihonig	s-wihonig	V;IPFV;SG;PRS
ceposid	cecpos	V;PRF;PL;PRS
ku:bsmad	ku:bsmad	V;IPFV;SG;PRS
wu:s̥ad	wu:s̥adad	V;IPFV;PL;FUT
ñeʼe	ñeʼed	V;IPFV;SG;FUT
ke:k	ke:kad	V;IPFV;SG;FUT
cipkan	cicpkanad	V;IPFV;PL;FUT
sitolmad	sitolmadiñ	V;IMP;PL;PRS
hihidod̥	hihihod̥añ	V;IMP;PL;PRS
kuint	kuint	V;IPFV;SG;PRS
bisc	biscad	V;IPFV;SG;FUT
hu:kajid	hu:kajidad	V;IPFV;PL;FUT
s-wohocid	s-wohocidad	V;IPFV;PL;FUT
waid	waidad	V;IPFV;SG;FUT
