bata	tabata	V;PL;1;HOD
zviratidze	wakazviratidze	V;SG;2;PST
ifa	murikufa	V;PROG;PL;2;PRS
chema	vanochema	V;PL;3;PRS
wona	munowona	V;PL;2;PRS
terera	ndaterera	V;SG;1;HOD
ipa	wakapa	V;SG;2;PST
rasa	arikurasa	V;PROG;SG;3;PRS
daidza	murikudaidza	V;PROG;PL;2;PRS
bata	anobata	V;SG;3;PRS
seka	unoseka	V;SG;2;PRS
vhura	tavhura	V;PL;1;HOD
inwa	uchanwa	V;SG;2;FUT
ziva	aziva	V;SG;3;HOD
mirira	makamirira	V;PL;2;PST
uya	takauya	V;PL;1;PST
enda	akaenda	V;SG;3;PST
dzidza	ndirikudzidza	V;PROG;SG;1;PRS
muka	makamuka	V;PL;2;PST
tenga	tichatenga	V;PL;1;FUT
tumira	takatumira	V;PL;1;PST
muka	ndamuka	V;SG;1;HOD
bhururuka	anobhururuka	V;SG;3;PRS
vhura	varikuvhura	V;PROG;PL;3;PRS
irwa	munorwa	V;PL;2;PRS
kanganwa	takanganwa	V;PL;1;HOD
verenga	waverenga	V;SG;2;HOD
wedzera	muchawedzera	V;PL;2;FUT
ifa	mafa	V;PL;2;HOD
verenga	averenga	V;SG;3;HOD
imba	ndaimba	V;SG;1;HOD
ipa	murikupa	V;PROG;PL;2;PRS
inwa	ndakanwa	V;SG;1;PST
uya	makauya	V;PL;2;PST
idya	arikudya	V;PROG;SG;3;PRS
sangana	vakasangana	V;PL;3;PST
nzwisisa	wanzwisisa	V;SG;2;HOD
wana	munowana	V;PL;2;PRS
bvunza	makabvunza	V;PL;2;PST
imba	waimba	V;SG;2;HOD
donha	akadonha	V;SG;3;PST
kanganwa	murikukanganwa	V;PROG;PL;2;PRS
kwanisa	vachakwanisa	V;PL;3;FUT
tora	watora	V;SG;2;HOD
pedza	varikupedza	V;PROG;PL;3;PRS
tenga	matenga	V;PL;2;HOD
wedzera	tawedzera	V;PL;1;HOD
pedza	makapedza	V;PL;2;PST
kwanisa	ndirikukwanisa	V;PROG;SG;1;PRS
nzwisisa	murikunzwisisa	V;PROG;PL;2;PRS
fema	vakafema	V;PL;3;PST
zviratidze	vanozviratidze	V;PL;3;PRS
pedza	muchapedza	V;PL;2;FUT
inwa	ndichanwa	V;SG;1;FUT
vhura	munovhura	V;PL;2;PRS
idya	wadya	V;SG;2;HOD
famba	ndinofamba	V;SG;1;PRS
imba	tichaimba	V;PL;1;FUT
dzidzisa	achadzidzisa	V;SG;3;FUT
gona	ndinogona	V;SG;1;PRS
uraya	anouraya	V;SG;3;PRS
tango	tirikutango	V;PROG;PL;1;PRS
vhara	anovhara	V;SG;3;PRS
imba	urikuimba	V;PROG;SG;2;PRS
mirira	wakamirira	V;SG;2;PST
enda	tirikuenda	V;PROG;PL;1;PRS
donha	wakadonha	V;SG;2;PST
fema	varikufema	V;PROG;PL;3;PRS
funga	anofunga	V;SG;3;PRS
tyora	atyora	V;SG;3;HOD
vhara	tichavhara	V;PL;1;FUT
ziva	murikuziva	V;PROG;PL;2;PRS
donha	vachadonha	V;PL;3;FUT
fema	anofema	V;SG;3;PRS
imba	muchaimba	V;PL;2;FUT
bika	urikubika	V;PROG;SG;2;PRS
bika	achabika	V;SG;3;FUT
tanga	arikutanga	V;PROG;SG;3;PRS
dzokorora	vakadzokorora	V;PL;3;PST
tsanangura	uchatsanangura	V;SG;2;FUT
pindura	achapindura	V;SG;3;FUT
funga	ndakafunga	V;SG;1;PST
iva	vakava	V;PL;3;PST
kwanisa	takakwanisa	V;PL;1;PST
sekerera	uchasekerera	V;SG;2;FUT
ratidza	murikuratidza	V;PROG;PL;2;PRS
pindura	tirikupindura	V;PROG;PL;1;PRS
kunda	vanokunda	V;PL;3;PRS
muka	muchamuka	V;PL;2;FUT
tarisa	ndatarisa	V;SG;1;HOD
nyora	tinonyora	V;PL;1;PRS
verenga	taverenga	V;PL;1;HOD
tango	atango	V;SG;3;HOD
bhururuka	wabhururuka	V;SG;2;HOD
imba	uchaimba	V;SG;2;FUT
uraya	ndirikuuraya	V;PROG;SG;1;PRS
kanganwa	unokanganwa	V;SG;2;PRS
tyora	tichatyora	V;PL;1;FUT
tyaira	vakatyaira	V;PL;3;PST
bhururuka	murikubhururuka	V;PROG;PL;2;PRS
sangana	asangana	V;SG;3;HOD
gamuchira	uchagamuchira	V;SG;2;FUT
tengesa	tichatengesa	V;PL;1;FUT
dzoka	makadzoka	V;PL;2;PST
iva	vakava	V;PL;3;PST
kunda	takakunda	V;PL;1;PST
uraya	mauraya	V;PL;2;HOD
nyora	anyora	V;SG;3;HOD
kunda	vachakunda	V;PL;3;FUT
tumira	vatumira	V;PL;3;HOD
kuva	tinokuva	V;PL;1;PRS
zviratidze	muchazviratidze	V;PL;2;FUT
kwanisa	akakwanisa	V;SG;3;PST
rangarira	tirikurangarira	V;PROG;PL;1;PRS
ipa	vachapa	V;PL;3;FUT
isa	maisa	V;PL;2;HOD
ipa	ndapa	V;SG;1;HOD
rangarira	ndinorangarira	V;SG;1;PRS
uya	urikuuya	V;PROG;SG;2;PRS
rangarira	anorangarira	V;SG;3;PRS
funga	wakafunga	V;SG;2;PST
dzoka	tinodzoka	V;PL;1;PRS
itakunge	vaitakunge	V;PL;3;HOD
imba	maimba	V;PL;2;HOD
dzokorora	munodzokorora	V;PL;2;PRS
imba	arikuimba	V;PROG;SG;3;PRS
fema	vafema	V;PL;3;HOD
rangarira	vanorangarira	V;PL;3;PRS
rara	tirikurara	V;PROG;PL;1;PRS
nyora	munonyora	V;PL;2;PRS
tsanangura	ndakatsanangura	V;SG;1;PST
shanda	vakashanda	V;PL;3;PST
kuitika	zvakaitika	V;SG;2;PST
tumira	ndirikutumira	V;PROG;SG;1;PRS
rangarira	ndirikurangarira	V;PROG;SG;1;PRS
wana	ndakawana	V;SG;1;PST
tsanangura	vakatsanangura	V;PL;3;PST
koka	achakoka	V;SG;3;FUT
shandisa	arikushandisa	V;PROG;SG;3;PRS
farira	tinofarira	V;PL;1;PRS
pindura	muchapindura	V;PL;2;FUT
gona	ndakagona	V;SG;1;PST
nyora	muchanyora	V;PL;2;FUT
bvunza	ndabvunza	V;SG;1;HOD
wana	tirikuwana	V;PROG;PL;1;PRS
rara	ndarara	V;SG;1;HOD
dzidzisa	arikudzidzisa	V;PROG;SG;3;PRS
vhura	anovhura	V;SG;3;PRS
tengesa	ndatengesa	V;SG;1;HOD
kanganwa	arikukanganwa	V;PROG;SG;3;PRS
zviratidze	ndakazviratidze	V;SG;1;PST
bvunza	vanobvunza	V;PL;3;PRS
ridzamhere	ucharidzamhere	V;SG;2;FUT
tyaira	ndinotyaira	V;SG;1;PRS
shandisa	anoshandisa	V;SG;3;PRS
terera	vaterera	V;PL;3;HOD
mhanya	murikumhanya	V;PROG;PL;2;PRS
bhururuka	tichabhururuka	V;PL;1;FUT
idya	akadya	V;SG;3;PST
tengesa	unotengesa	V;SG;2;PRS
ifa	wafa	V;SG;2;HOD
vhara	vakavhara	V;PL;3;PST
rasa	tarasa	V;PL;1;HOD
dzoka	vakadzoka	V;PL;3;PST
itakunge	tichaitakunge	V;PL;1;FUT
seka	akaseka	V;SG;3;PST
dzoka	akadzoka	V;SG;3;PST
ridzamhere	tirikuridzamhere	V;PROG;PL;1;PRS
dzidza	takadzidza	V;PL;1;PST
koka	ndakoka	V;SG;1;HOD
chema	ndakachema	V;SG;1;PST
verenga	maverenga	V;PL;2;HOD
gamuchira	magamuchira	V;PL;2;HOD
mhanya	vakamhanya	V;PL;3;PST
funga	wafunga	V;SG;2;HOD
ziva	takaziva	V;PL;1;PST
funga	afunga	V;SG;3;HOD
shandisa	ndichashandisa	V;SG;1;FUT
bata	tabata	V;PL;1;HOD
rasa	vacharasa	V;PL;3;FUT
funga	makafunga	V;PL;2;PST
tsanangura	watsanangura	V;SG;2;HOD
itakunge	munoitakunge	V;PL;2;PRS
zviratidze	tazviratidze	V;PL;1;HOD
zviratidze	achazviratidze	V;SG;3;FUT
ratidza	ndirikuratidza	V;PROG;SG;1;PRS
seka	makaseka	V;PL;2;PST
itakunge	vanoitakunge	V;PL;3;PRS
dzoka	murikudzoka	V;PROG;PL;2;PRS
gona	unogona	V;SG;2;PRS
zviratidze	ndichazviratidze	V;SG;1;FUT
ridzamhere	vanoridzamhere	V;PL;3;PRS
nzwisisa	vakanzwisisa	V;PL;3;PST
donha	uchadonha	V;SG;2;FUT
tamba	tinotamba	V;PL;1;PRS
farira	arikufarira	V;PROG;SG;3;PRS
chema	ndinochema	V;SG;1;PRS
sangana	muchasangana	V;PL;2;FUT
bata	anobata	V;SG;3;PRS
buda	muchabuda	V;PL;2;FUT
sekerera	vachasekerera	V;PL;3;FUT
imba	tinoimba	V;PL;1;PRS
kanganwa	anokanganwa	V;SG;3;PRS
gona	wakagona	V;SG;2;PST
dzidzisa	ndadzidzisa	V;SG;1;HOD
dzidzisa	takadzidzisa	V;PL;1;PST
gona	tagona	V;PL;1;HOD
tsvoda	ndinotsvoda	V;SG;1;PRS
wana	vawana	V;PL;3;HOD
bika	makabika	V;PL;2;PST
gona	ndichagona	V;SG;1;FUT
chema	tichachema	V;PL;1;FUT
mirira	takamirira	V;PL;1;PST
fema	murikufema	V;PROG;PL;2;PRS
kuitika	zvirikuitika	V;PL;2;PRS
nyora	arikunyora	V;PROG;SG;3;PRS
ratidza	vanoratidza	V;PL;3;PRS
irwa	anorwa	V;SG;3;PRS
ipa	vapa	V;PL;3;HOD
mhanya	unomhanya	V;SG;2;PRS
ita	taita	V;PL;1;HOD
funga	uchafunga	V;SG;2;FUT
wana	wakawana	V;SG;2;PST
ipa	wapa	V;SG;2;HOD
dzidza	vadzidza	V;PL;3;HOD
kuitika	zvakaitika	V;PL;1;PST
koka	ndinokoka	V;SG;1;PRS
bhururuka	munobhururuka	V;PL;2;PRS
bvuma	murikubvuma	V;PROG;PL;2;PRS
dzokorora	ndirikudzokorora	V;PROG;SG;1;PRS
iva	vachava	V;PL;3;FUT
dzidzisa	tirikudzidzisa	V;PROG;PL;1;PRS
simuka	tichasimuka	V;PL;1;FUT
sekerera	arikusekerera	V;PROG;SG;3;PRS
gamuchira	varikugamuchira	V;PROG;PL;3;PRS
pinda	achapinda	V;SG;3;FUT
ipa	vanopa	V;PL;3;PRS
batsira	munobatsira	V;PL;2;PRS
inzwa	anonzwa	V;SG;3;PRS
funga	ndirikufunga	V;PROG;SG;1;PRS
tumira	matumira	V;PL;2;HOD
batsira	wakabatsira	V;SG;2;PST
tyora	ndatyora	V;SG;1;HOD
muka	vamuka	V;PL;3;HOD
donha	ndirikudonha	V;PROG;SG;1;PRS
kanganwa	varikukanganwa	V;PROG;PL;3;PRS
kwanisa	achakwanisa	V;SG;3;FUT
koka	varikukoka	V;PROG;PL;3;PRS
uya	akauya	V;SG;3;PST
mirira	anomirira	V;SG;3;PRS
dzikisa	vakadzikisa	V;PL;3;PST
batsira	muchabatsira	V;PL;2;FUT
idya	vadya	V;PL;3;HOD
ziva	uchaziva	V;SG;2;FUT
kanganwa	urikukanganwa	V;PROG;SG;2;PRS
idya	tadya	V;PL;1;HOD
vhara	ndirikuvhara	V;PROG;SG;1;PRS
nzwisisa	munonzwisisa	V;PL;2;PRS
rasa	ndirikurasa	V;PROG;SG;1;PRS
nyora	uchanyora	V;SG;2;FUT
tarisa	ndakatarisa	V;SG;1;PST
ridzamhere	munoridzamhere	V;PL;2;PRS
donha	munodonha	V;PL;2;PRS
gona	vagona	V;PL;3;HOD
farira	ndakafarira	V;SG;1;PST
tsvoda	takatsvoda	V;PL;1;PST
pedza	anopedza	V;SG;3;PRS
sangana	ndasangana	V;SG;1;HOD
kunda	ndakunda	V;SG;1;HOD
verenga	makaverenga	V;PL;2;PST
isa	muchaisa	V;PL;2;FUT
dzoka	wakadzoka	V;SG;2;PST
zviratidze	varikuzviratidze	V;PROG;PL;3;PRS
tanga	unotanga	V;SG;2;PRS
tora	varikutora	V;PROG;PL;3;PRS
seka	murikuseka	V;PROG;PL;2;PRS
bvuma	murikubvuma	V;PROG;PL;2;PRS
tyaira	muchatyaira	V;PL;2;FUT
irwa	urikurwa	V;PROG;SG;2;PRS
uraya	arikuuraya	V;PROG;SG;3;PRS
daidza	arikudaidza	V;PROG;SG;3;PRS
rara	ndarara	V;SG;1;HOD
wona	munowona	V;PL;2;PRS
tyaira	tatyaira	V;PL;1;HOD
iva	tava	V;PL;1;HOD
kanganwa	vakakanganwa	V;PL;3;PST
tyora	anotyora	V;SG;3;PRS
nyora	varikunyora	V;PROG;PL;3;PRS
sekerera	tinosekerera	V;PL;1;PRS
tenga	ndakatenga	V;SG;1;PST
tyora	ndakatyora	V;SG;1;PST
tsvoda	anotsvoda	V;SG;3;PRS
tumira	varikutumira	V;PROG;PL;3;PRS
rangarira	ndarangarira	V;SG;1;HOD
tsanangura	tatsanangura	V;PL;1;HOD
tamba	tinotamba	V;PL;1;PRS
muka	tichamuka	V;PL;1;FUT
nzwisisa	akanzwisisa	V;SG;3;PST
dzokorora	ndinodzokorora	V;SG;1;PRS
sangana	arikusangana	V;PROG;SG;3;PRS
shandisa	makashandisa	V;PL;2;PST
bika	tichabika	V;PL;1;FUT
tumira	wakatumira	V;SG;2;PST
nyora	tirikunyora	V;PROG;PL;1;PRS
batsira	varikubatsira	V;PROG;PL;3;PRS
tsanangura	anotsanangura	V;SG;3;PRS
parura	tinoparura	V;PL;1;PRS
simuka	unosimuka	V;SG;2;PRS
dzidza	vanodzidza	V;PL;3;PRS
wedzera	vawedzera	V;PL;3;HOD
tsvoda	murikutsvoda	V;PROG;PL;2;PRS
inwa	akanwa	V;SG;3;PST
bvunza	abvunza	V;SG;3;HOD
vhura	tinovhura	V;PL;1;PRS
enda	achaenda	V;SG;3;FUT
gamuchira	wakagamuchira	V;SG;2;PST
kunda	makunda	V;PL;2;HOD
enda	unoenda	V;SG;2;PRS
bhururuka	muchabhururuka	V;PL;2;FUT
ifa	munofa	V;PL;2;PRS
chema	urikuchema	V;PROG;SG;2;PRS
enda	uchaenda	V;SG;2;FUT
kanganwa	muchakanganwa	V;PL;2;FUT
rangarira	vakarangarira	V;PL;3;PST
funga	vachafunga	V;PL;3;FUT
pedza	ndichapedza	V;SG;1;FUT
pinda	arikupinda	V;PROG;SG;3;PRS
wana	tinowana	V;PL;1;PRS
ifa	vanofa	V;PL;3;PRS
idya	madya	V;PL;2;HOD
bvunza	anobvunza	V;SG;3;PRS
irwa	ndinorwa	V;SG;1;PRS
mhanya	munomhanya	V;PL;2;PRS
kunda	vakakunda	V;PL;3;PST
ita	vakaita	V;PL;3;PST
pedza	ndakapedza	V;SG;1;PST
tsanangura	matsanangura	V;PL;2;HOD
uraya	takauraya	V;PL;1;PST
farira	afarira	V;SG;3;HOD
enda	urikuenda	V;PROG;SG;2;PRS
wedzera	ndakawedzera	V;SG;1;PST
uya	murikuuya	V;PROG;PL;2;PRS
inzwa	anonzwa	V;SG;3;PRS
rasa	ndicharasa	V;SG;1;FUT
inwa	ndinonwa	V;SG;1;PRS
irwa	mucharwa	V;PL;2;FUT
sekerera	ndirikusekerera	V;PROG;SG;1;PRS
isa	vanoisa	V;PL;3;PRS
iva	tava	V;PL;1;HOD
nzwisisa	manzwisisa	V;PL;2;HOD
isa	taisa	V;PL;1;HOD
uya	wakauya	V;SG;2;PST
dzidzisa	wadzidzisa	V;SG;2;HOD
rara	tirikurara	V;PROG;PL;1;PRS
mhanya	uchamhanya	V;SG;2;FUT
pedza	achapedza	V;SG;3;FUT
tyora	murikutyora	V;PROG;PL;2;PRS
zviratidze	makazviratidze	V;PL;2;PST
uraya	tinouraya	V;PL;1;PRS
bika	arikubika	V;PROG;SG;3;PRS
wana	makawana	V;PL;2;PST
vhura	arikuvhura	V;PROG;SG;3;PRS
dzikisa	uchadzikisa	V;SG;2;FUT
tyaira	ndatyaira	V;SG;1;HOD
tarisa	anotarisa	V;SG;3;PRS
kuva	ndakakuva	V;SG;1;PST
pindura	urikupindura	V;PROG;SG;2;PRS
nyora	anonyora	V;SG;3;PRS
ratidza	aratidza	V;SG;3;HOD
tenga	vachatenga	V;PL;3;FUT
bika	varikubika	V;PROG;PL;3;PRS
shandisa	ndinoshandisa	V;SG;1;PRS
pindura	ndapindura	V;SG;1;HOD
zviratidze	tinozviratidze	V;PL;1;PRS
famba	ndinofamba	V;SG;1;PRS
bhururuka	varikubhururuka	V;PROG;PL;3;PRS
muka	vakamuka	V;PL;3;PST
terera	varikuterera	V;PROG;PL;3;PRS
pindura	tapindura	V;PL;1;HOD
gamuchira	ndakagamuchira	V;SG;1;PST
seka	vaseka	V;PL;3;HOD
dzidzisa	akadzidzisa	V;SG;3;PST
terera	makaterera	V;PL;2;PST
bvunza	arikubvunza	V;PROG;SG;3;PRS
rangarira	varikurangarira	V;PROG;PL;3;PRS
tyora	makatyora	V;PL;2;PST
irwa	arwa	V;SG;3;HOD
ratidza	akaratidza	V;SG;3;PST
dzikisa	achadzikisa	V;SG;3;FUT
tenga	atenga	V;SG;3;HOD
shanda	arikushanda	V;PROG;SG;3;PRS
koka	tinokoka	V;PL;1;PRS
sangana	varikusangana	V;PROG;PL;3;PRS
tango	ndirikutango	V;PROG;SG;1;PRS
ratidza	taratidza	V;PL;1;HOD
funga	murikufunga	V;PROG;PL;2;PRS
tarisa	tinotarisa	V;PL;1;PRS
isa	tichaisa	V;PL;1;FUT
bata	ndakabata	V;SG;1;PST
shandisa	ndashandisa	V;SG;1;HOD
rasa	mucharasa	V;PL;2;FUT
simuka	anosimuka	V;SG;3;PRS
pinda	ndirikupinda	V;PROG;SG;1;PRS
dzoka	wadzoka	V;SG;2;HOD
ipa	akapa	V;SG;3;PST
dzidzisa	uchadzidzisa	V;SG;2;FUT
tora	uchatora	V;SG;2;FUT
itakunge	taitakunge	V;PL;1;HOD
tango	vanotango	V;PL;3;PRS
parura	vakaparura	V;PL;3;PST
isa	murikuisa	V;PROG;PL;2;PRS
chema	achema	V;SG;3;HOD
chema	munochema	V;PL;2;PRS
buda	tichabuda	V;PL;1;FUT
ipa	ndinopa	V;SG;1;PRS
batsira	vachabatsira	V;PL;3;FUT
sangana	tichasangana	V;PL;1;FUT
famba	anofamba	V;SG;3;PRS
farira	urikufarira	V;PROG;SG;2;PRS
dzoka	vachadzoka	V;PL;3;FUT
farira	takafarira	V;PL;1;PST
fema	muchafema	V;PL;2;FUT
nzwisisa	tinonzwisisa	V;PL;1;PRS
ziva	arikuziva	V;PROG;SG;3;PRS
iva	vachava	V;PL;3;FUT
ita	murikuita	V;PROG;PL;2;PRS
tora	takatora	V;PL;1;PST
irwa	arikurwa	V;PROG;SG;3;PRS
inwa	wakanwa	V;SG;2;PST
tora	atora	V;SG;3;HOD
tsvoda	unotsvoda	V;SG;2;PRS
gamuchira	takagamuchira	V;PL;1;PST
enda	makaenda	V;PL;2;PST
farira	makafarira	V;PL;2;PST
idya	ndinodya	V;SG;1;PRS
tora	tinotora	V;PL;1;PRS
koka	murikukoka	V;PROG;PL;2;PRS
famba	anofamba	V;SG;3;PRS
batsira	achabatsira	V;SG;3;FUT
fema	ndafema	V;SG;1;HOD
koka	uchakoka	V;SG;2;FUT
dzokorora	tirikudzokorora	V;PROG;PL;1;PRS
bata	ndakabata	V;SG;1;PST
sekerera	anosekerera	V;SG;3;PRS
kunda	murikukunda	V;PROG;PL;2;PRS
tyaira	unotyaira	V;SG;2;PRS
vhura	unovhura	V;SG;2;PRS
tumira	ndinotumira	V;SG;1;PRS
buda	anobuda	V;SG;3;PRS
ziva	makaziva	V;PL;2;PST
uraya	ndinouraya	V;SG;1;PRS
donha	tirikudonha	V;PROG;PL;1;PRS
kuitika	zvichaitika	V;PL;2;FUT
seka	taseka	V;PL;1;HOD
idya	ndakadya	V;SG;1;PST
tumira	tinotumira	V;PL;1;PRS
