bula	ngibula	V;SG;1;FUT
reka	bayareka	V;SG;1;PST
e	sizoe	V;PL;2;PST
rekisa	uzorekisa	V;PL;1;PST
qala	bazoqala	V;PL;3;PST
haufi	bazohaufi	V;PL;3;PST
reka	sizoreka	V;PL;2;PST
thusa	nithusa	V;PL;2;FUT
haufi	uhaufi	V;SG;3;FUT
hulaa	ngihulaa	V;SG;1;FUT
ebe	siyaebe	V;PL;2;PRS
tloo	batloo	V;PL;3;FUT
haufi	uyahaufi	V;SG;2;PRS
lumela	bazolumela	V;PL;3;PST
qala	niyaqala	V;PL;3;PRS
ithute	ithuteea	V;NFIN
qete	uzoqete	V;PL;1;PST
rekisa	bazorekisa	V;PL;3;PST
phomolo	niphomolo	V;PL;2;FUT
ema	ngiema	V;SG;1;FUT
boroko	uzoboroko	V;SG;3;PST
ebe	sizoebe	V;PL;2;PST
hulaa	ngizohulaa	V;SG;2;PST
ebe	uyaebe	V;SG;2;PRS
phomolo	sizophomolo	V;PL;2;PST
qala	niqala	V;PL;2;FUT
bala	uyabala	V;PL;1;PRS
tloo	sitloo	V;PL;1;FUT
lula	nilula	V;PL;2;FUT
lumela	balumela	V;PL;3;FUT
utloa	siutloa	V;PL;1;FUT
bula	uzobula	V;PL;1;PST
etsa	uzoetsa	V;SG;3;PST
ebe	ngiebe	V;SG;1;FUT
phomolo	uphomolo	V;SG;3;FUT
lumela	uyalumela	V;SG;3;PRS
lumela	ngiyalumela	V;SG;1;PRS
tloo	ngitloo	V;SG;1;FUT
utloa	uzoutloa	V;PL;1;PST
sututsa	bazosututsa	V;PL;3;PST
bala	sizobala	V;PL;2;PST
hulaa	uyahulaa	V;SG;2;PRS
etsa	uyaetsa	V;PL;1;PRS
thusa	bathusa	V;PL;3;FUT
qete	siqete	V;PL;1;FUT
bula	nibula	V;SG;2;FUT
fofa	ngifofa	V;SG;1;FUT
etsa	uyaetsa	V;SG;2;PRS
qala	uyaqala	V;SG;3;PRS
qala	siyaqala	V;PL;2;PRS
bula	niyabula	V;PL;3;PRS
utloa	ngiutloa	V;SG;1;FUT
rekisa	uyarekisa	V;SG;2;PRS
ebe	ngiyaebe	V;SG;1;PRS
fofa	bazofofa	V;PL;3;PST
ya	niyaya	V;PL;3;PRS
bula	sibula	V;PL;1;FUT
reka	uyareka	V;SG;3;PRS
thusa	uzothusa	V;PL;1;PST
boroko	siyaboroko	V;PL;2;PRS
utloa	ngizoutloa	V;SG;2;PST
ya	yaea	V;NFIN
lula	siyalula	V;PL;2;PRS
thusa	ngiyathusa	V;SG;1;PRS
qala	sizoqala	V;PL;2;PST
lumela	uyalumela	V;PL;1;PRS
ema	niema	V;SG;2;FUT
sututsa	ngizosututsa	V;SG;2;PST
fofa	uyafofa	V;PL;1;PRS
lula	nilula	V;SG;2;FUT
fofa	sifofa	V;PL;1;FUT
lula	uyalula	V;SG;3;PRS
ema	bazoema	V;PL;3;PST
boroko	ngiboroko	V;SG;1;FUT
lumela	uzolumela	V;PL;1;PST
ngola	ngizongola	V;SG;2;PST
lumela	uyalumela	V;SG;2;PRS
reka	nireka	V;SG;2;FUT
ithute	uyaithute	V;PL;1;PRS
bula	bayabula	V;SG;1;PST
bala	bazobala	V;PL;3;PST
e	uzoe	V;PL;1;PST
lumela	siyalumela	V;PL;2;PRS
bala	balaea	V;NFIN
fofa	uyafofa	V;SG;3;PRS
lula	uzolula	V;PL;1;PST
ithute	sizoithute	V;PL;2;PST
rekisa	uyarekisa	V;PL;1;PRS
ngola	niyangola	V;PL;3;PRS
qala	ngizoqala	V;SG;2;PST
bula	bazobula	V;PL;3;PST
lula	bazolula	V;PL;3;PST
bala	babala	V;PL;3;FUT
boroko	niyaboroko	V;PL;3;PRS
ja	uzoja	V;SG;3;PST
utloa	utloaea	V;NFIN
rekisa	urekisa	V;SG;3;FUT
lula	ulula	V;SG;3;FUT
hulaa	nihulaa	V;SG;2;FUT
