kamilisha	nitakamilisha	V;FIN;IND;SG;1;FUT
fagia	nilifagia	V;FIN;IND;SG;1;PST
ponda	wanaponda	V;DEF;FIN;IND;PL;3;PRS
mwita	tungalimwita	V;FIN;COND;PL;1;PST
ondoa	ameondoa	V;PRF;FIN;IND;SG;3;PST
chafya	tuhuchafya	V;HAB;FIN;IND;PL;1;PRS
ficha	ninaficha	V;DEF;FIN;IND;SG;1;PRS
omba	ningeomba	V;FIN;COND;SG;1;PRS
bofya	tumebofya	V;PRF;FIN;IND;PL;1;PST
fuata	mlifuata	V;FIN;IND;PL;2;PST
tembea	wahutembea	V;HAB;FIN;IND;PL;3;PRS
funza	tungefunza	V;FIN;COND;PL;1;PRS
tafuna	tumetafuna	V;PRF;FIN;IND;PL;1;PST
anguka	mnaanguka	V;DEF;FIN;IND;PL;2;PRS
osha	tumeosha	V;PRF;FIN;IND;PL;1;PST
sinzia	ninasinzia	V;DEF;FIN;IND;SG;1;PRS
soma	ningalisoma	V;FIN;COND;SG;1;PST
safisha	tungalisafisha	V;FIN;COND;PL;1;PST
sema	nilisema	V;FIN;IND;SG;1;PST
ota	unaota	V;DEF;FIN;IND;SG;2;PRS
meza	wahumeza	V;HAB;FIN;IND;PL;3;PRS
tikisa	wametikisa	V;PRF;FIN;IND;PL;3;PST
vuta	wamevuta	V;PRF;FIN;IND;PL;3;PST
ondoa	tutaondoa	V;FIN;IND;PL;1;FUT
endesha	ahuendesha	V;HAB;FIN;IND;SG;3;PRS
ondoa	wahuondoa	V;HAB;FIN;IND;PL;3;PRS
ngoja	walingoja	V;FIN;IND;PL;3;PST
pea	nitapea	V;FIN;IND;SG;1;FUT
endesha	waaendesha	V;INDF;FIN;IND;PL;3;PRS
tafuna	waatafuna	V;INDF;FIN;IND;PL;3;PRS
tikisa	mtatikisa	V;FIN;IND;PL;2;FUT
kumbuka	alikumbuka	V;FIN;IND;SG;3;PST
lala	malala	V;INDF;FIN;IND;PL;2;PRS
pea	mnapea	V;DEF;FIN;IND;PL;2;PRS
kaa	angalikaa	V;FIN;COND;SG;3;PST
nunua	angalinunua	V;FIN;COND;SG;3;PST
endesha	wangeendesha	V;FIN;COND;PL;3;PRS
paa	atapaa	V;FIN;IND;SG;3;FUT
tikisa	wangalitikisa	V;FIN;COND;PL;3;PST
bandika	atabandika	V;FIN;IND;SG;3;FUT
zaa	tumezaa	V;PRF;FIN;IND;PL;1;PST
fuata	uafuata	V;INDF;FIN;IND;SG;2;PRS
sinzia	ungesinzia	V;FIN;COND;SG;2;PRS
funga	anafunga	V;DEF;FIN;IND;SG;3;PRS
lia	angelia	V;FIN;COND;SG;3;PRS
tengeneza	umetengeneza	V;PRF;FIN;IND;SG;2;PST
kopa	tuhukopa	V;HAB;FIN;IND;PL;1;PRS
lamba	angelamba	V;FIN;COND;SG;3;PRS
fika	nitafika	V;FIN;IND;SG;1;FUT
kunja	anakunja	V;DEF;FIN;IND;SG;3;PRS
jifunza	uhujifunza	V;HAB;FIN;IND;SG;2;PRS
punguza	tumepunguza	V;PRF;FIN;IND;PL;1;PST
bandika	tutabandika	V;FIN;IND;PL;1;FUT
bandika	mmebandika	V;PRF;FIN;IND;PL;2;PST
nunua	ninanunua	V;DEF;FIN;IND;SG;1;PRS
pambua	angalipambua	V;FIN;COND;SG;3;PST
gonga	tuligonga	V;FIN;IND;PL;1;PST
pambua	aapambua	V;INDF;FIN;IND;SG;3;PRS
andika	tumeandika	V;PRF;FIN;IND;PL;1;PST
lamba	ualamba	V;INDF;FIN;IND;SG;2;PRS
bandika	tuhubandika	V;HAB;FIN;IND;PL;1;PRS
ona	wangaliona	V;FIN;COND;PL;3;PST
ambia	wangaliambia	V;FIN;COND;PL;3;PST
chukia	ningechukia	V;FIN;COND;SG;1;PRS
lia	tungalilia	V;FIN;COND;PL;1;PST
soma	watasoma	V;FIN;IND;PL;3;FUT
chapisha	tungalichapisha	V;FIN;COND;PL;1;PST
kausha	tumekausha	V;PRF;FIN;IND;PL;1;PST
lala	wanalala	V;DEF;FIN;IND;PL;3;PRS
cheka	mmecheka	V;PRF;FIN;IND;PL;2;PST
fika	niafika	V;INDF;FIN;IND;SG;1;PRS
omba	wanaomba	V;DEF;FIN;IND;PL;3;PRS
zaa	uhuzaa	V;HAB;FIN;IND;SG;2;PRS
tembea	umetembea	V;PRF;FIN;IND;SG;2;PST
chapisha	mnachapisha	V;DEF;FIN;IND;PL;2;PRS
ona	anaona	V;DEF;FIN;IND;SG;3;PRS
cheka	niacheka	V;INDF;FIN;IND;SG;1;PRS
tikisa	wanatikisa	V;DEF;FIN;IND;PL;3;PRS
kaa	nihukaa	V;HAB;FIN;IND;SG;1;PRS
funza	angalifunza	V;FIN;COND;SG;3;PST
ogelea	kuogelea	V;FIN
kimbia	tumekimbia	V;PRF;FIN;IND;PL;1;PST
chafya	mngalichafya	V;FIN;COND;PL;2;PST
simama	ningesimama	V;FIN;COND;SG;1;PRS
uwa	ninauwa	V;DEF;FIN;IND;SG;1;PRS
chafya	aachafya	V;INDF;FIN;IND;SG;3;PRS
tafuna	nitatafuna	V;FIN;IND;SG;1;FUT
uza	niliuza	V;FIN;IND;SG;1;PST
kumbuka	tungekumbuka	V;FIN;COND;PL;1;PRS
kusanya	mngalikusanya	V;FIN;COND;PL;2;PST
kwaruza	tunakwaruza	V;DEF;FIN;IND;PL;1;PRS
enda	wangeenda	V;FIN;COND;PL;3;PRS
ruka	waliruka	V;FIN;IND;PL;3;PST
chapisha	walichapisha	V;FIN;IND;PL;3;PST
chukia	tumechukia	V;PRF;FIN;IND;PL;1;PST
sukuma	wangesukuma	V;FIN;COND;PL;3;PRS
piga	alipiga	V;FIN;IND;SG;3;PST
potea	ningalipotea	V;FIN;COND;SG;1;PST
leta	tungeleta	V;FIN;COND;PL;1;PRS
lia	analia	V;DEF;FIN;IND;SG;3;PRS
jua	anajua	V;DEF;FIN;IND;SG;3;PRS
leta	nihuleta	V;HAB;FIN;IND;SG;1;PRS
punguza	atapunguza	V;FIN;IND;SG;3;FUT
safisha	ulisafisha	V;FIN;IND;SG;2;PST
mwita	mngemwita	V;FIN;COND;PL;2;PRS
choma	tuhuchoma	V;HAB;FIN;IND;PL;1;PRS
kumbuka	makumbuka	V;INDF;FIN;IND;PL;2;PRS
mwita	wanamwita	V;DEF;FIN;IND;PL;3;PRS
jifunza	mnajifunza	V;DEF;FIN;IND;PL;2;PRS
punguza	uhupunguza	V;HAB;FIN;IND;SG;2;PRS
pambua	ulipambua	V;FIN;IND;SG;2;PST
piga	tungepiga	V;FIN;COND;PL;1;PRS
omba	tunaomba	V;DEF;FIN;IND;PL;1;PRS
lamba	ningalilamba	V;FIN;COND;SG;1;PST
simama	wamesimama	V;PRF;FIN;IND;PL;3;PST
cheka	ningalicheka	V;FIN;COND;SG;1;PST
sema	mmesema	V;PRF;FIN;IND;PL;2;PST
ponda	ameponda	V;PRF;FIN;IND;SG;3;PST
leta	ualeta	V;INDF;FIN;IND;SG;2;PRS
funga	mafunga	V;INDF;FIN;IND;PL;2;PRS
elewa	wanaelewa	V;DEF;FIN;IND;PL;3;PRS
ngoja	amengoja	V;PRF;FIN;IND;SG;3;PST
pika	tutapika	V;FIN;IND;PL;1;FUT
leta	tualeta	V;INDF;FIN;IND;PL;1;PRS
jifunza	majifunza	V;INDF;FIN;IND;PL;2;PRS
meza	atameza	V;FIN;IND;SG;3;FUT
tembea	ahutembea	V;HAB;FIN;IND;SG;3;PRS
sukuma	ahusukuma	V;HAB;FIN;IND;SG;3;PRS
chukua	angechukua	V;FIN;COND;SG;3;PRS
uliza	tunauliza	V;DEF;FIN;IND;PL;1;PRS
osha	tutaosha	V;FIN;IND;PL;1;FUT
changanya	mtachanganya	V;FIN;IND;PL;2;FUT
ongea	mmeongea	V;PRF;FIN;IND;PL;2;PST
kausha	ningekausha	V;FIN;COND;SG;1;PRS
kusanya	tungekusanya	V;FIN;COND;PL;1;PRS
saga	ahusaga	V;HAB;FIN;IND;SG;3;PRS
pika	wangalipika	V;FIN;COND;PL;3;PST
shikilia	tuhushikilia	V;HAB;FIN;IND;PL;1;PRS
inuka	mngeinuka	V;FIN;COND;PL;2;PRS
taka	nitataka	V;FIN;IND;SG;1;FUT
elewa	wangeelewa	V;FIN;COND;PL;3;PRS
nunua	mmenunua	V;PRF;FIN;IND;PL;2;PST
fika	ningalifika	V;FIN;COND;SG;1;PST
shinda	ameshinda	V;PRF;FIN;IND;SG;3;PST
jisikia	aajisikia	V;INDF;FIN;IND;SG;3;PRS
cheka	uhucheka	V;HAB;FIN;IND;SG;2;PRS
osha	uhuosha	V;HAB;FIN;IND;SG;2;PRS
jua	tungejua	V;FIN;COND;PL;1;PRS
jua	alijua	V;FIN;IND;SG;3;PST
sema	nihusema	V;HAB;FIN;IND;SG;1;PRS
kohoa	nitakohoa	V;FIN;IND;SG;1;FUT
chapisha	tutachapisha	V;FIN;IND;PL;1;FUT
ota	kuota	V;FIN
saidia	tuhusaidia	V;HAB;FIN;IND;PL;1;PRS
piga	wanapiga	V;DEF;FIN;IND;PL;3;PRS
choma	tuachoma	V;INDF;FIN;IND;PL;1;PRS
bofya	ningebofya	V;FIN;COND;SG;1;PRS
ngoja	wangalingoja	V;FIN;COND;PL;3;PST
ruka	mliruka	V;FIN;IND;PL;2;PST
pea	tunapea	V;DEF;FIN;IND;PL;1;PRS
ngoja	nilingoja	V;FIN;IND;SG;1;PST
piga	ungepiga	V;FIN;COND;SG;2;PRS
paa	tutapaa	V;FIN;IND;PL;1;FUT
ona	nitaona	V;FIN;IND;SG;1;FUT
ambia	tutaambia	V;FIN;IND;PL;1;FUT
changanya	alichanganya	V;FIN;IND;SG;3;PST
chukia	tunachukia	V;DEF;FIN;IND;PL;1;PRS
chapisha	angalichapisha	V;FIN;COND;SG;3;PST
gonga	wamegonga	V;PRF;FIN;IND;PL;3;PST
chafya	mmechafya	V;PRF;FIN;IND;PL;2;PST
gusa	wangaligusa	V;FIN;COND;PL;3;PST
kamata	umekamata	V;PRF;FIN;IND;SG;2;PST
funga	alifunga	V;FIN;IND;SG;3;PST
osha	wanaosha	V;DEF;FIN;IND;PL;3;PRS
potea	angepotea	V;FIN;COND;SG;3;PRS
tikisa	uhutikisa	V;HAB;FIN;IND;SG;2;PRS
saidia	wangesaidia	V;FIN;COND;PL;3;PRS
ambia	maambia	V;INDF;FIN;IND;PL;2;PRS
jisikia	mhujisikia	V;HAB;FIN;IND;PL;2;PRS
ficha	mmeficha	V;PRF;FIN;IND;PL;2;PST
ngoja	wahungoja	V;HAB;FIN;IND;PL;3;PRS
chafya	tumechafya	V;PRF;FIN;IND;PL;1;PST
cheka	tunacheka	V;DEF;FIN;IND;PL;1;PRS
fuata	tumefuata	V;PRF;FIN;IND;PL;1;PST
oga	tungeoga	V;FIN;COND;PL;1;PRS
shinda	mtashinda	V;FIN;IND;PL;2;FUT
lia	ahulia	V;HAB;FIN;IND;SG;3;PRS
safisha	anasafisha	V;DEF;FIN;IND;SG;3;PRS
uliza	angeuliza	V;FIN;COND;SG;3;PRS
anguka	nimeanguka	V;PRF;FIN;IND;SG;1;PST
ondoa	ningaliondoa	V;FIN;COND;SG;1;PST
kimbia	tuakimbia	V;INDF;FIN;IND;PL;1;PRS
imba	aaimba	V;INDF;FIN;IND;SG;3;PRS
meza	mhumeza	V;HAB;FIN;IND;PL;2;PRS
taka	angalitaka	V;FIN;COND;SG;3;PST
anza	ningeanza	V;FIN;COND;SG;1;PRS
shikilia	mtashikilia	V;FIN;IND;PL;2;FUT
gusa	atagusa	V;FIN;IND;SG;3;FUT
chapisha	ungechapisha	V;FIN;COND;SG;2;PRS
lamba	tumelamba	V;PRF;FIN;IND;PL;1;PST
lala	ningelala	V;FIN;COND;SG;1;PRS
changanya	kuchanganya	V;FIN
tengeneza	mnatengeneza	V;DEF;FIN;IND;PL;2;PRS
punguza	niapunguza	V;INDF;FIN;IND;SG;1;PRS
piga	mmepiga	V;PRF;FIN;IND;PL;2;PST
shikilia	aashikilia	V;INDF;FIN;IND;SG;3;PRS
ondoa	utaondoa	V;FIN;IND;SG;2;FUT
ondoa	umeondoa	V;PRF;FIN;IND;SG;2;PST
gonga	atagonga	V;FIN;IND;SG;3;FUT
tafuta	watatafuta	V;FIN;IND;PL;3;FUT
sikiliza	ungesikiliza	V;FIN;COND;SG;2;PRS
pika	umepika	V;PRF;FIN;IND;SG;2;PST
simama	kusimama	V;FIN
soma	wamesoma	V;PRF;FIN;IND;PL;3;PST
soma	ningesoma	V;FIN;COND;SG;1;PRS
jua	tutajua	V;FIN;IND;PL;1;FUT
saga	tulisaga	V;FIN;IND;PL;1;PST
fanya	ulifanya	V;FIN;IND;SG;2;PST
taka	waataka	V;INDF;FIN;IND;PL;3;PRS
inuka	wangeinuka	V;FIN;COND;PL;3;PRS
chukia	mmechukia	V;PRF;FIN;IND;PL;2;PST
saidia	masaidia	V;INDF;FIN;IND;PL;2;PRS
tafuta	mhutafuta	V;HAB;FIN;IND;PL;2;PRS
tazama	watatazama	V;FIN;IND;PL;3;FUT
shikilia	tungalishikilia	V;FIN;COND;PL;1;PST
tengeneza	mhutengeneza	V;HAB;FIN;IND;PL;2;PRS
fungua	ningalifungua	V;FIN;COND;SG;1;PST
elewa	tuaelewa	V;INDF;FIN;IND;PL;1;PRS
kaa	mngalikaa	V;FIN;COND;PL;2;PST
ngoja	nimengoja	V;PRF;FIN;IND;SG;1;PST
ondoa	tuhuondoa	V;HAB;FIN;IND;PL;1;PRS
kopa	ninakopa	V;DEF;FIN;IND;SG;1;PRS
kwaruza	niakwaruza	V;INDF;FIN;IND;SG;1;PRS
mwita	kumwita	V;FIN
kwaruza	mngekwaruza	V;FIN;COND;PL;2;PRS
panguza	tumepanguza	V;PRF;FIN;IND;PL;1;PST
tikisa	nimetikisa	V;PRF;FIN;IND;SG;1;PST
kohoa	ninakohoa	V;DEF;FIN;IND;SG;1;PRS
fungua	mtafungua	V;FIN;IND;PL;2;FUT
andika	ninaandika	V;DEF;FIN;IND;SG;1;PRS
kopa	mlikopa	V;FIN;IND;PL;2;PST
nunua	mnanunua	V;DEF;FIN;IND;PL;2;PRS
chukia	nitachukia	V;FIN;IND;SG;1;FUT
ogelea	ningaliogelea	V;FIN;COND;SG;1;PST
simama	utasimama	V;FIN;IND;SG;2;FUT
tembea	nimetembea	V;PRF;FIN;IND;SG;1;PST
funga	nilifunga	V;FIN;IND;SG;1;PST
fagia	anafagia	V;DEF;FIN;IND;SG;3;PRS
gonga	waagonga	V;INDF;FIN;IND;PL;3;PRS
safisha	ungalisafisha	V;FIN;COND;SG;2;PST
lamba	tuhulamba	V;HAB;FIN;IND;PL;1;PRS
paa	ahupaa	V;HAB;FIN;IND;SG;3;PRS
oga	aaoga	V;INDF;FIN;IND;SG;3;PRS
fanya	nilifanya	V;FIN;IND;SG;1;PST
meza	ahumeza	V;HAB;FIN;IND;SG;3;PRS
fungua	mmefungua	V;PRF;FIN;IND;PL;2;PST
mwita	mlimwita	V;FIN;IND;PL;2;PST
jisikia	tungejisikia	V;FIN;COND;PL;1;PRS
ficha	alificha	V;FIN;IND;SG;3;PST
inua	tunainua	V;DEF;FIN;IND;PL;1;PRS
pika	tunapika	V;DEF;FIN;IND;PL;1;PRS
funza	ungalifunza	V;FIN;COND;SG;2;PST
imba	angaliimba	V;FIN;COND;SG;3;PST
pea	wahupea	V;HAB;FIN;IND;PL;3;PRS
zaa	anazaa	V;DEF;FIN;IND;SG;3;PRS
ficha	tutaficha	V;FIN;IND;PL;1;FUT
punguza	mngalipunguza	V;FIN;COND;PL;2;PST
pika	mmepika	V;PRF;FIN;IND;PL;2;PST
kamilisha	mngalikamilisha	V;FIN;COND;PL;2;PST
gusa	wamegusa	V;PRF;FIN;IND;PL;3;PST
lia	ningalilia	V;FIN;COND;SG;1;PST
saga	niasaga	V;INDF;FIN;IND;SG;1;PRS
bofya	umebofya	V;PRF;FIN;IND;SG;2;PST
fika	mlifika	V;FIN;IND;PL;2;PST
ruka	mmeruka	V;PRF;FIN;IND;PL;2;PST
zaa	ningezaa	V;FIN;COND;SG;1;PRS
uza	angeuza	V;FIN;COND;SG;3;PRS
andika	mmeandika	V;PRF;FIN;IND;PL;2;PST
soma	uasoma	V;INDF;FIN;IND;SG;2;PRS
ficha	umeficha	V;PRF;FIN;IND;SG;2;PST
elewa	utaelewa	V;FIN;IND;SG;2;FUT
andika	aaandika	V;INDF;FIN;IND;SG;3;PRS
kamilisha	ningekamilisha	V;FIN;COND;SG;1;PRS
punguza	watapunguza	V;FIN;IND;PL;3;FUT
fagia	amefagia	V;PRF;FIN;IND;SG;3;PST
ficha	wangalificha	V;FIN;COND;PL;3;PST
tafuna	ninatafuna	V;DEF;FIN;IND;SG;1;PRS
paa	nimepaa	V;PRF;FIN;IND;SG;1;PST
bandika	ningebandika	V;FIN;COND;SG;1;PRS
lia	ualia	V;INDF;FIN;IND;SG;2;PRS
piga	ungalipiga	V;FIN;COND;SG;2;PST
fuata	tunafuata	V;DEF;FIN;IND;PL;1;PRS
chimba	tuachimba	V;INDF;FIN;IND;PL;1;PRS
kata	wangalikata	V;FIN;COND;PL;3;PST
lala	nitalala	V;FIN;IND;SG;1;FUT
punguza	ahupunguza	V;HAB;FIN;IND;SG;3;PRS
lala	mnalala	V;DEF;FIN;IND;PL;2;PRS
vuta	niavuta	V;INDF;FIN;IND;SG;1;PRS
tazama	mnatazama	V;DEF;FIN;IND;PL;2;PRS
kata	mngalikata	V;FIN;COND;PL;2;PST
chukia	wahuchukia	V;HAB;FIN;IND;PL;3;PRS
nunua	nimenunua	V;PRF;FIN;IND;SG;1;PST
panguza	niapanguza	V;INDF;FIN;IND;SG;1;PRS
inuka	nihuinuka	V;HAB;FIN;IND;SG;1;PRS
imba	tuliimba	V;FIN;IND;PL;1;PST
uza	mliuza	V;FIN;IND;PL;2;PST
piga	tungalipiga	V;FIN;COND;PL;1;PST
meza	mtameza	V;FIN;IND;PL;2;FUT
leta	tulileta	V;FIN;IND;PL;1;PST
enda	ungeenda	V;FIN;COND;SG;2;PRS
pea	wangepea	V;FIN;COND;PL;3;PRS
tembea	tumetembea	V;PRF;FIN;IND;PL;1;PST
elewa	walielewa	V;FIN;IND;PL;3;PST
changanya	watachanganya	V;FIN;IND;PL;3;FUT
kamilisha	ninakamilisha	V;DEF;FIN;IND;SG;1;PRS
pea	atapea	V;FIN;IND;SG;3;FUT
chapisha	umechapisha	V;PRF;FIN;IND;SG;2;PST
choma	niachoma	V;INDF;FIN;IND;SG;1;PRS
enda	angalienda	V;FIN;COND;SG;3;PST
ponda	niaponda	V;INDF;FIN;IND;SG;1;PRS
bofya	aabofya	V;INDF;FIN;IND;SG;3;PRS
uliza	ungeuliza	V;FIN;COND;SG;2;PRS
kimbia	tutakimbia	V;FIN;IND;PL;1;FUT
tafuna	uatafuna	V;INDF;FIN;IND;SG;2;PRS
chimba	utachimba	V;FIN;IND;SG;2;FUT
safisha	unasafisha	V;DEF;FIN;IND;SG;2;PRS
funga	mngefunga	V;FIN;COND;PL;2;PRS
taka	mataka	V;INDF;FIN;IND;PL;2;PRS
ambia	tungeambia	V;FIN;COND;PL;1;PRS
ona	wanaona	V;DEF;FIN;IND;PL;3;PRS
ogelea	unaogelea	V;DEF;FIN;IND;SG;2;PRS
nunua	ningalinunua	V;FIN;COND;SG;1;PST
uliza	mngeuliza	V;FIN;COND;PL;2;PRS
bandika	nilibandika	V;FIN;IND;SG;1;PST
chapisha	wamechapisha	V;PRF;FIN;IND;PL;3;PST
ogelea	tunaogelea	V;DEF;FIN;IND;PL;1;PRS
vuta	alivuta	V;FIN;IND;SG;3;PST
bandika	wahubandika	V;HAB;FIN;IND;PL;3;PRS
uza	uliuza	V;FIN;IND;SG;2;PST
jua	wangejua	V;FIN;COND;PL;3;PRS
kunja	nitakunja	V;FIN;IND;SG;1;FUT
funza	mtafunza	V;FIN;IND;PL;2;FUT
ogelea	tuliogelea	V;FIN;IND;PL;1;PST
jifunza	ahujifunza	V;HAB;FIN;IND;SG;3;PRS
fungua	tuhufungua	V;HAB;FIN;IND;PL;1;PRS
chukua	tungechukua	V;FIN;COND;PL;1;PRS
simama	uasimama	V;INDF;FIN;IND;SG;2;PRS
inuka	tunainuka	V;DEF;FIN;IND;PL;1;PRS
sukuma	mtasukuma	V;FIN;IND;PL;2;FUT
gusa	uligusa	V;FIN;IND;SG;2;PST
saidia	wahusaidia	V;HAB;FIN;IND;PL;3;PRS
panguza	ungalipanguza	V;FIN;COND;SG;2;PST
ondoa	waliondoa	V;FIN;IND;PL;3;PST
oga	angalioga	V;FIN;COND;SG;3;PST
gonga	tunagonga	V;DEF;FIN;IND;PL;1;PRS
sinzia	mnasinzia	V;DEF;FIN;IND;PL;2;PRS
cheka	nihucheka	V;HAB;FIN;IND;SG;1;PRS
nusa	wangenusa	V;FIN;COND;PL;3;PRS
kwaruza	uhukwaruza	V;HAB;FIN;IND;SG;2;PRS
lia	angalilia	V;FIN;COND;SG;3;PST
gusa	ningegusa	V;FIN;COND;SG;1;PRS
punguza	wangepunguza	V;FIN;COND;PL;3;PRS
anza	ataanza	V;FIN;IND;SG;3;FUT
chapisha	ningalichapisha	V;FIN;COND;SG;1;PST
ogelea	tuaogelea	V;INDF;FIN;IND;PL;1;PRS
sukuma	masukuma	V;INDF;FIN;IND;PL;2;PRS
pambua	ningalipambua	V;FIN;COND;SG;1;PST
fuata	wamefuata	V;PRF;FIN;IND;PL;3;PST
nusa	kunusa	V;FIN
kamilisha	alikamilisha	V;FIN;IND;SG;3;PST
soma	mnasoma	V;DEF;FIN;IND;PL;2;PRS
ota	niaota	V;INDF;FIN;IND;SG;1;PRS
ficha	tuaficha	V;INDF;FIN;IND;PL;1;PRS
endesha	nimeendesha	V;PRF;FIN;IND;SG;1;PST
tafuna	mtatafuna	V;FIN;IND;PL;2;FUT
ngoja	nitangoja	V;FIN;IND;SG;1;FUT
kwaruza	mtakwaruza	V;FIN;IND;PL;2;FUT
choma	utachoma	V;FIN;IND;SG;2;FUT
chapisha	uhuchapisha	V;HAB;FIN;IND;SG;2;PRS
chukua	anachukua	V;DEF;FIN;IND;SG;3;PRS
pambua	walipambua	V;FIN;IND;PL;3;PST
nunua	uanunua	V;INDF;FIN;IND;SG;2;PRS
kimbia	ahukimbia	V;HAB;FIN;IND;SG;3;PRS
kata	ungalikata	V;FIN;COND;SG;2;PST
kunja	alikunja	V;FIN;IND;SG;3;PST
imba	mnaimba	V;DEF;FIN;IND;PL;2;PRS
funza	ninafunza	V;DEF;FIN;IND;SG;1;PRS
panguza	tunapanguza	V;DEF;FIN;IND;PL;1;PRS
safisha	kusafisha	V;FIN
chafya	mhuchafya	V;HAB;FIN;IND;PL;2;PRS
uwa	waauwa	V;INDF;FIN;IND;PL;3;PRS
osha	wataosha	V;FIN;IND;PL;3;FUT
panguza	wahupanguza	V;HAB;FIN;IND;PL;3;PRS
anguka	anaanguka	V;DEF;FIN;IND;SG;3;PRS
ota	waliota	V;FIN;IND;PL;3;PST
fungua	kufungua	V;FIN
uza	tumeuza	V;PRF;FIN;IND;PL;1;PST
kunja	makunja	V;INDF;FIN;IND;PL;2;PRS
ona	ninaona	V;DEF;FIN;IND;SG;1;PRS
anza	umeanza	V;PRF;FIN;IND;SG;2;PST
kwaruza	aakwaruza	V;INDF;FIN;IND;SG;3;PRS
kausha	nitakausha	V;FIN;IND;SG;1;FUT
simama	wanasimama	V;DEF;FIN;IND;PL;3;PRS
zaa	ulizaa	V;FIN;IND;SG;2;PST
anguka	wanaanguka	V;DEF;FIN;IND;PL;3;PRS
chukia	aachukia	V;INDF;FIN;IND;SG;3;PRS
oga	wahuoga	V;HAB;FIN;IND;PL;3;PRS
sukuma	mmesukuma	V;PRF;FIN;IND;PL;2;PST
zima	utazima	V;FIN;IND;SG;2;FUT
lala	tumelala	V;PRF;FIN;IND;PL;1;PST
jisikia	mlijisikia	V;FIN;IND;PL;2;PST
panguza	ninapanguza	V;DEF;FIN;IND;SG;1;PRS
saga	wahusaga	V;HAB;FIN;IND;PL;3;PRS
pambua	ungepambua	V;FIN;COND;SG;2;PRS
sinzia	tumesinzia	V;PRF;FIN;IND;PL;1;PST
pea	wamepea	V;PRF;FIN;IND;PL;3;PST
gonga	magonga	V;INDF;FIN;IND;PL;2;PRS
zaa	wangezaa	V;FIN;COND;PL;3;PRS
simama	unasimama	V;DEF;FIN;IND;SG;2;PRS
jifunza	nihujifunza	V;HAB;FIN;IND;SG;1;PRS
jisikia	atajisikia	V;FIN;IND;SG;3;FUT
uwa	tumeuwa	V;PRF;FIN;IND;PL;1;PST
andika	umeandika	V;PRF;FIN;IND;SG;2;PST
pambua	tumepambua	V;PRF;FIN;IND;PL;1;PST
funza	nimefunza	V;PRF;FIN;IND;SG;1;PST
kausha	uakausha	V;INDF;FIN;IND;SG;2;PRS
gusa	waligusa	V;FIN;IND;PL;3;PST
chimba	anachimba	V;DEF;FIN;IND;SG;3;PRS
choma	ungalichoma	V;FIN;COND;SG;2;PST
safisha	mlisafisha	V;FIN;IND;PL;2;PST
meza	ningalimeza	V;FIN;COND;SG;1;PST
ambia	tuhuambia	V;HAB;FIN;IND;PL;1;PRS
chimba	mtachimba	V;FIN;IND;PL;2;FUT
omba	waliomba	V;FIN;IND;PL;3;PST
chukua	ningalichukua	V;FIN;COND;SG;1;PST
panguza	unapanguza	V;DEF;FIN;IND;SG;2;PRS
kopa	mnakopa	V;DEF;FIN;IND;PL;2;PRS
fika	anafika	V;DEF;FIN;IND;SG;3;PRS
imba	ungeimba	V;FIN;COND;SG;2;PRS
potea	waapotea	V;INDF;FIN;IND;PL;3;PRS
elewa	tutaelewa	V;FIN;IND;PL;1;FUT
omba	umeomba	V;PRF;FIN;IND;SG;2;PST
cheka	anacheka	V;DEF;FIN;IND;SG;3;PRS
inuka	aliinuka	V;FIN;IND;SG;3;PST
kamata	tuhukamata	V;HAB;FIN;IND;PL;1;PRS
safisha	mnasafisha	V;DEF;FIN;IND;PL;2;PRS
gonga	uhugonga	V;HAB;FIN;IND;SG;2;PRS
fika	tungalifika	V;FIN;COND;PL;1;PST
chukua	nimechukua	V;PRF;FIN;IND;SG;1;PST
kimbia	waakimbia	V;INDF;FIN;IND;PL;3;PRS
ponda	mliponda	V;FIN;IND;PL;2;PST
oga	wataoga	V;FIN;IND;PL;3;FUT
kaa	mlikaa	V;FIN;IND;PL;2;PST
shikilia	watashikilia	V;FIN;IND;PL;3;FUT
potea	wanapotea	V;DEF;FIN;IND;PL;3;PRS
tembea	tuatembea	V;INDF;FIN;IND;PL;1;PRS
chukua	mtachukua	V;FIN;IND;PL;2;FUT
omba	ataomba	V;FIN;IND;SG;3;FUT
kusanya	angalikusanya	V;FIN;COND;SG;3;PST
saidia	alisaidia	V;FIN;IND;SG;3;PST
meza	utameza	V;FIN;IND;SG;2;FUT
jua	mngalijua	V;FIN;COND;PL;2;PST
vuta	tungalivuta	V;FIN;COND;PL;1;PST
ota	wanaota	V;DEF;FIN;IND;PL;3;PRS
simama	waasimama	V;INDF;FIN;IND;PL;3;PRS
changanya	aachanganya	V;INDF;FIN;IND;SG;3;PRS
leta	wanaleta	V;DEF;FIN;IND;PL;3;PRS
lala	tungelala	V;FIN;COND;PL;1;PRS
piga	atapiga	V;FIN;IND;SG;3;FUT
anguka	mhuanguka	V;HAB;FIN;IND;PL;2;PRS
chukua	ningechukua	V;FIN;COND;SG;1;PRS
kohoa	nilikohoa	V;FIN;IND;SG;1;PST
ambia	ungaliambia	V;FIN;COND;SG;2;PST
kimbia	mhukimbia	V;HAB;FIN;IND;PL;2;PRS
pea	tungalipea	V;FIN;COND;PL;1;PST
kausha	tunakausha	V;DEF;FIN;IND;PL;1;PRS
omba	nitaomba	V;FIN;IND;SG;1;FUT
chukia	watachukia	V;FIN;IND;PL;3;FUT
chapisha	tuachapisha	V;INDF;FIN;IND;PL;1;PRS
uwa	ungaliuwa	V;FIN;COND;SG;2;PST
ogelea	tuhuogelea	V;HAB;FIN;IND;PL;1;PRS
kopa	niakopa	V;INDF;FIN;IND;SG;1;PRS
ondoa	anaondoa	V;DEF;FIN;IND;SG;3;PRS
zaa	tulizaa	V;FIN;IND;PL;1;PST
gonga	uagonga	V;INDF;FIN;IND;SG;2;PRS
tafuna	angalitafuna	V;FIN;COND;SG;3;PST
fika	ninafika	V;DEF;FIN;IND;SG;1;PRS
saidia	niasaidia	V;INDF;FIN;IND;SG;1;PRS
chukua	alichukua	V;FIN;IND;SG;3;PST
cheka	ninacheka	V;DEF;FIN;IND;SG;1;PRS
piga	ahupiga	V;HAB;FIN;IND;SG;3;PRS
tafuta	tutatafuta	V;FIN;IND;PL;1;FUT
lala	nialala	V;INDF;FIN;IND;SG;1;PRS
ruka	mngaliruka	V;FIN;COND;PL;2;PST
pika	aapika	V;INDF;FIN;IND;SG;3;PRS
fanya	mtafanya	V;FIN;IND;PL;2;FUT
sukuma	nihusukuma	V;HAB;FIN;IND;SG;1;PRS
kamata	nimekamata	V;PRF;FIN;IND;SG;1;PST
punguza	utapunguza	V;FIN;IND;SG;2;FUT
punguza	mhupunguza	V;HAB;FIN;IND;PL;2;PRS
zima	tungezima	V;FIN;COND;PL;1;PRS
sema	uasema	V;INDF;FIN;IND;SG;2;PRS
chafya	tungechafya	V;FIN;COND;PL;1;PRS
vuta	uavuta	V;INDF;FIN;IND;SG;2;PRS
pambua	ninapambua	V;DEF;FIN;IND;SG;1;PRS
paa	nitapaa	V;FIN;IND;SG;1;FUT
fanya	nitafanya	V;FIN;IND;SG;1;FUT
sukuma	watasukuma	V;FIN;IND;PL;3;FUT
gonga	mmegonga	V;PRF;FIN;IND;PL;2;PST
kaa	kukaa	V;FIN
andika	mtaandika	V;FIN;IND;PL;2;FUT
chapisha	nilichapisha	V;FIN;IND;SG;1;PST
sukuma	niasukuma	V;INDF;FIN;IND;SG;1;PRS
chukua	walichukua	V;FIN;IND;PL;3;PST
inuka	waainuka	V;INDF;FIN;IND;PL;3;PRS
jisikia	wanajisikia	V;DEF;FIN;IND;PL;3;PRS
fuata	nilifuata	V;FIN;IND;SG;1;PST
piga	wangepiga	V;FIN;COND;PL;3;PRS
fika	angefika	V;FIN;COND;SG;3;PRS
funza	ahufunza	V;HAB;FIN;IND;SG;3;PRS
chimba	nihuchimba	V;HAB;FIN;IND;SG;1;PRS
meza	nihumeza	V;HAB;FIN;IND;SG;1;PRS
fagia	wangefagia	V;FIN;COND;PL;3;PRS
ficha	tunaficha	V;DEF;FIN;IND;PL;1;PRS
saga	anasaga	V;DEF;FIN;IND;SG;3;PRS
paa	tungalipaa	V;FIN;COND;PL;1;PST
shinda	umeshinda	V;PRF;FIN;IND;SG;2;PST
bofya	mmebofya	V;PRF;FIN;IND;PL;2;PST
zaa	angezaa	V;FIN;COND;SG;3;PRS
jisikia	anajisikia	V;DEF;FIN;IND;SG;3;PRS
tazama	waatazama	V;INDF;FIN;IND;PL;3;PRS
kamata	ungalikamata	V;FIN;COND;SG;2;PST
gusa	magusa	V;INDF;FIN;IND;PL;2;PRS
safisha	tuasafisha	V;INDF;FIN;IND;PL;1;PRS
kausha	nilikausha	V;FIN;IND;SG;1;PST
lamba	mmelamba	V;PRF;FIN;IND;PL;2;PST
lamba	kulamba	V;FIN
kamilisha	walikamilisha	V;FIN;IND;PL;3;PST
ficha	wangeficha	V;FIN;COND;PL;3;PRS
kopa	mmekopa	V;PRF;FIN;IND;PL;2;PST
tafuta	wangetafuta	V;FIN;COND;PL;3;PRS
anza	mtaanza	V;FIN;IND;PL;2;FUT
sukuma	amesukuma	V;PRF;FIN;IND;SG;3;PST
inua	niainua	V;INDF;FIN;IND;SG;1;PRS
chukia	mnachukia	V;DEF;FIN;IND;PL;2;PRS
elewa	angalielewa	V;FIN;COND;SG;3;PST
jisikia	tumejisikia	V;PRF;FIN;IND;PL;1;PST
elewa	uaelewa	V;INDF;FIN;IND;SG;2;PRS
kata	tulikata	V;FIN;IND;PL;1;PST
elewa	ningeelewa	V;FIN;COND;SG;1;PRS
chafya	mngechafya	V;FIN;COND;PL;2;PRS
ruka	mhuruka	V;HAB;FIN;IND;PL;2;PRS
funga	uafunga	V;INDF;FIN;IND;SG;2;PRS
gonga	angegonga	V;FIN;COND;SG;3;PRS
meza	wangalimeza	V;FIN;COND;PL;3;PST
funga	uhufunga	V;HAB;FIN;IND;SG;2;PRS
jisikia	ningejisikia	V;FIN;COND;SG;1;PRS
cheka	wamecheka	V;PRF;FIN;IND;PL;3;PST
shinda	watashinda	V;FIN;IND;PL;3;FUT
jifunza	wangejifunza	V;FIN;COND;PL;3;PRS
oga	tutaoga	V;FIN;IND;PL;1;FUT
panguza	atapanguza	V;FIN;IND;SG;3;FUT
saidia	nitasaidia	V;FIN;IND;SG;1;FUT
ruka	angaliruka	V;FIN;COND;SG;3;PST
ponda	mtaponda	V;FIN;IND;PL;2;FUT
enda	ulienda	V;FIN;IND;SG;2;PST
kwaruza	ninakwaruza	V;DEF;FIN;IND;SG;1;PRS
sinzia	wangesinzia	V;FIN;COND;PL;3;PRS
sema	atasema	V;FIN;IND;SG;3;FUT
endesha	angaliendesha	V;FIN;COND;SG;3;PST
fuata	uhufuata	V;HAB;FIN;IND;SG;2;PRS
chimba	tungechimba	V;FIN;COND;PL;1;PRS
panguza	tungepanguza	V;FIN;COND;PL;1;PRS
gusa	mngegusa	V;FIN;COND;PL;2;PRS
shinda	mngalishinda	V;FIN;COND;PL;2;PST
vuta	watavuta	V;FIN;IND;PL;3;FUT
sinzia	mngesinzia	V;FIN;COND;PL;2;PRS
simama	tutasimama	V;FIN;IND;PL;1;FUT
chapisha	wangalichapisha	V;FIN;COND;PL;3;PST
ambia	niliambia	V;FIN;IND;SG;1;PST
choma	mhuchoma	V;HAB;FIN;IND;PL;2;PRS
kata	mlikata	V;FIN;IND;PL;2;PST
inua	wameinua	V;PRF;FIN;IND;PL;3;PST
anza	walianza	V;FIN;IND;PL;3;PST
sinzia	nitasinzia	V;FIN;IND;SG;1;FUT
kaa	tungalikaa	V;FIN;COND;PL;1;PST
ondoa	mliondoa	V;FIN;IND;PL;2;PST
anguka	tuhuanguka	V;HAB;FIN;IND;PL;1;PRS
simama	tuhusimama	V;HAB;FIN;IND;PL;1;PRS
mwita	mhumwita	V;HAB;FIN;IND;PL;2;PRS
omba	aliomba	V;FIN;IND;SG;3;PST
ona	mmeona	V;PRF;FIN;IND;PL;2;PST
zima	mnazima	V;DEF;FIN;IND;PL;2;PRS
ondoa	uliondoa	V;FIN;IND;SG;2;PST
cheka	mtacheka	V;FIN;IND;PL;2;FUT
jisikia	uhujisikia	V;HAB;FIN;IND;SG;2;PRS
andika	ungaliandika	V;FIN;COND;SG;2;PST
paa	umepaa	V;PRF;FIN;IND;SG;2;PST
chafya	uachafya	V;INDF;FIN;IND;SG;2;PRS
chapisha	unachapisha	V;DEF;FIN;IND;SG;2;PRS
kata	tunakata	V;DEF;FIN;IND;PL;1;PRS
inuka	uainuka	V;INDF;FIN;IND;SG;2;PRS
inuka	mnainuka	V;DEF;FIN;IND;PL;2;PRS
ondoa	maondoa	V;INDF;FIN;IND;PL;2;PRS
kimbia	wahukimbia	V;HAB;FIN;IND;PL;3;PRS
uliza	utauliza	V;FIN;IND;SG;2;FUT
potea	tutapotea	V;FIN;IND;PL;1;FUT
choma	ungechoma	V;FIN;COND;SG;2;PRS
uliza	tungeuliza	V;FIN;COND;PL;1;PRS
andika	aliandika	V;FIN;IND;SG;3;PST
pambua	tutapambua	V;FIN;IND;PL;1;FUT
uwa	mnauwa	V;DEF;FIN;IND;PL;2;PRS
simama	tulisimama	V;FIN;IND;PL;1;PST
saga	uhusaga	V;HAB;FIN;IND;SG;2;PRS
shinda	alishinda	V;FIN;IND;SG;3;PST
pambua	ahupambua	V;HAB;FIN;IND;SG;3;PRS
inuka	mngaliinuka	V;FIN;COND;PL;2;PST
ponda	waaponda	V;INDF;FIN;IND;PL;3;PRS
vuta	tunavuta	V;DEF;FIN;IND;PL;1;PRS
kaa	tumekaa	V;PRF;FIN;IND;PL;1;PST
jifunza	tungejifunza	V;FIN;COND;PL;1;PRS
elewa	tumeelewa	V;PRF;FIN;IND;PL;1;PST
enda	nimeenda	V;PRF;FIN;IND;SG;1;PST
ruka	wataruka	V;FIN;IND;PL;3;FUT
piga	ulipiga	V;FIN;IND;SG;2;PST
panguza	tutapanguza	V;FIN;IND;PL;1;FUT
leta	mngeleta	V;FIN;COND;PL;2;PRS
chafya	nihuchafya	V;HAB;FIN;IND;SG;1;PRS
tembea	nitatembea	V;FIN;IND;SG;1;FUT
shinda	ungalishinda	V;FIN;COND;SG;2;PST
chimba	mlichimba	V;FIN;IND;PL;2;PST
jifunza	niajifunza	V;INDF;FIN;IND;SG;1;PRS
kimbia	ningalikimbia	V;FIN;COND;SG;1;PST
soma	tuhusoma	V;HAB;FIN;IND;PL;1;PRS
uza	atauza	V;FIN;IND;SG;3;FUT
chukua	mmechukua	V;PRF;FIN;IND;PL;2;PST
osha	ungaliosha	V;FIN;COND;SG;2;PST
vuta	utavuta	V;FIN;IND;SG;2;FUT
nunua	watanunua	V;FIN;IND;PL;3;FUT
pambua	mlipambua	V;FIN;IND;PL;2;PST
punguza	nitapunguza	V;FIN;IND;SG;1;FUT
ponda	waliponda	V;FIN;IND;PL;3;PST
pambua	niapambua	V;INDF;FIN;IND;SG;1;PRS
fagia	aafagia	V;INDF;FIN;IND;SG;3;PRS
saidia	tungesaidia	V;FIN;COND;PL;1;PRS
andika	ungeandika	V;FIN;COND;SG;2;PRS
fuata	angefuata	V;FIN;COND;SG;3;PRS
oga	wanaoga	V;DEF;FIN;IND;PL;3;PRS
fika	utafika	V;FIN;IND;SG;2;FUT
fanya	nihufanya	V;HAB;FIN;IND;SG;1;PRS
tazama	tunatazama	V;DEF;FIN;IND;PL;1;PRS
vuta	ninavuta	V;DEF;FIN;IND;SG;1;PRS
kausha	wahukausha	V;HAB;FIN;IND;PL;3;PRS
andika	niliandika	V;FIN;IND;SG;1;PST
omba	wameomba	V;PRF;FIN;IND;PL;3;PST
sukuma	umesukuma	V;PRF;FIN;IND;SG;2;PST
uza	niauza	V;INDF;FIN;IND;SG;1;PRS
ogelea	uaogelea	V;INDF;FIN;IND;SG;2;PRS
kamilisha	ahukamilisha	V;HAB;FIN;IND;SG;3;PRS
lala	tuhulala	V;HAB;FIN;IND;PL;1;PRS
potea	mhupotea	V;HAB;FIN;IND;PL;2;PRS
chukia	wangalichukia	V;FIN;COND;PL;3;PST
tafuna	tunatafuna	V;DEF;FIN;IND;PL;1;PRS
kamilisha	angalikamilisha	V;FIN;COND;SG;3;PST
kumbuka	aakumbuka	V;INDF;FIN;IND;SG;3;PRS
chimba	wangechimba	V;FIN;COND;PL;3;PRS
pika	mnapika	V;DEF;FIN;IND;PL;2;PRS
tazama	tulitazama	V;FIN;IND;PL;1;PST
fungua	unafungua	V;DEF;FIN;IND;SG;2;PRS
ogelea	waaogelea	V;INDF;FIN;IND;PL;3;PRS
anza	tuhuanza	V;HAB;FIN;IND;PL;1;PRS
sukuma	ungesukuma	V;FIN;COND;SG;2;PRS
uwa	niauwa	V;INDF;FIN;IND;SG;1;PRS
ongea	aliongea	V;FIN;IND;SG;3;PST
omba	ungeomba	V;FIN;COND;SG;2;PRS
tafuta	mmetafuta	V;PRF;FIN;IND;PL;2;PST
taka	tuhutaka	V;HAB;FIN;IND;PL;1;PRS
tafuta	mngalitafuta	V;FIN;COND;PL;2;PST
pea	mapea	V;INDF;FIN;IND;PL;2;PRS
gonga	nitagonga	V;FIN;IND;SG;1;FUT
tengeneza	alitengeneza	V;FIN;IND;SG;3;PST
uza	umeuza	V;PRF;FIN;IND;SG;2;PST
punguza	angepunguza	V;FIN;COND;SG;3;PRS
pambua	anapambua	V;DEF;FIN;IND;SG;3;PRS
kusanya	mngekusanya	V;FIN;COND;PL;2;PRS
vuta	aavuta	V;INDF;FIN;IND;SG;3;PRS
inuka	mmeinuka	V;PRF;FIN;IND;PL;2;PST
bandika	alibandika	V;FIN;IND;SG;3;PST
vuta	unavuta	V;DEF;FIN;IND;SG;2;PRS
jifunza	kujifunza	V;FIN
ficha	ningalificha	V;FIN;COND;SG;1;PST
vuta	nihuvuta	V;HAB;FIN;IND;SG;1;PRS
chimba	atachimba	V;FIN;IND;SG;3;FUT
funga	ulifunga	V;FIN;IND;SG;2;PST
kausha	ninakausha	V;DEF;FIN;IND;SG;1;PRS
fagia	mhufagia	V;HAB;FIN;IND;PL;2;PRS
ngoja	tutangoja	V;FIN;IND;PL;1;FUT
tengeneza	uhutengeneza	V;HAB;FIN;IND;SG;2;PRS
bandika	mtabandika	V;FIN;IND;PL;2;FUT
ruka	umeruka	V;PRF;FIN;IND;SG;2;PST
cheka	mngalicheka	V;FIN;COND;PL;2;PST
safisha	ningalisafisha	V;FIN;COND;SG;1;PST
piga	angalipiga	V;FIN;COND;SG;3;PST
punguza	waapunguza	V;INDF;FIN;IND;PL;3;PRS
paa	ungepaa	V;FIN;COND;SG;2;PRS
funga	ningefunga	V;FIN;COND;SG;1;PRS
vuta	wanavuta	V;DEF;FIN;IND;PL;3;PRS
zaa	mngezaa	V;FIN;COND;PL;2;PRS
omba	mhuomba	V;HAB;FIN;IND;PL;2;PRS
sukuma	alisukuma	V;FIN;IND;SG;3;PST
kopa	ulikopa	V;FIN;IND;SG;2;PST
ona	tutaona	V;FIN;IND;PL;1;FUT
ota	mngaliota	V;FIN;COND;PL;2;PST
nunua	umenunua	V;PRF;FIN;IND;SG;2;PST
nunua	mhununua	V;HAB;FIN;IND;PL;2;PRS
shinda	nihushinda	V;HAB;FIN;IND;SG;1;PRS
tafuta	ninatafuta	V;DEF;FIN;IND;SG;1;PRS
bandika	mhubandika	V;HAB;FIN;IND;PL;2;PRS
ruka	wanaruka	V;DEF;FIN;IND;PL;3;PRS
tazama	ninatazama	V;DEF;FIN;IND;SG;1;PRS
endesha	mhuendesha	V;HAB;FIN;IND;PL;2;PRS
oga	ninaoga	V;DEF;FIN;IND;SG;1;PRS
zima	mhuzima	V;HAB;FIN;IND;PL;2;PRS
kunja	mmekunja	V;PRF;FIN;IND;PL;2;PST
sukuma	walisukuma	V;FIN;IND;PL;3;PST
anguka	walianguka	V;FIN;IND;PL;3;PST
potea	tunapotea	V;DEF;FIN;IND;PL;1;PRS
lala	tulilala	V;FIN;IND;PL;1;PST
uliza	mauliza	V;INDF;FIN;IND;PL;2;PRS
kausha	anakausha	V;DEF;FIN;IND;SG;3;PRS
lamba	unalamba	V;DEF;FIN;IND;SG;2;PRS
kwaruza	mnakwaruza	V;DEF;FIN;IND;PL;2;PRS
anguka	maanguka	V;INDF;FIN;IND;PL;2;PRS
chimba	wanachimba	V;DEF;FIN;IND;PL;3;PRS
sema	ningalisema	V;FIN;COND;SG;1;PST
sukuma	mngesukuma	V;FIN;COND;PL;2;PRS
safisha	atasafisha	V;FIN;IND;SG;3;FUT
zima	tuhuzima	V;HAB;FIN;IND;PL;1;PRS
potea	uapotea	V;INDF;FIN;IND;SG;2;PRS
jua	mmejua	V;PRF;FIN;IND;PL;2;PST
tikisa	alitikisa	V;FIN;IND;SG;3;PST
jisikia	uajisikia	V;INDF;FIN;IND;SG;2;PRS
ota	ningeota	V;FIN;COND;SG;1;PRS
pea	ningepea	V;FIN;COND;SG;1;PRS
kata	mtakata	V;FIN;IND;PL;2;FUT
ogelea	mmeogelea	V;PRF;FIN;IND;PL;2;PST
sema	wahusema	V;HAB;FIN;IND;PL;3;PRS
inuka	aainuka	V;INDF;FIN;IND;SG;3;PRS
anguka	wataanguka	V;FIN;IND;PL;3;FUT
kwaruza	mmekwaruza	V;PRF;FIN;IND;PL;2;PST
choma	wanachoma	V;DEF;FIN;IND;PL;3;PRS
kamilisha	makamilisha	V;INDF;FIN;IND;PL;2;PRS
chimba	tuhuchimba	V;HAB;FIN;IND;PL;1;PRS
saidia	ulisaidia	V;FIN;IND;SG;2;PST
jifunza	ningalijifunza	V;FIN;COND;SG;1;PST
kamilisha	angekamilisha	V;FIN;COND;SG;3;PRS
uliza	tumeuliza	V;PRF;FIN;IND;PL;1;PST
saga	utasaga	V;FIN;IND;SG;2;FUT
kaa	mmekaa	V;PRF;FIN;IND;PL;2;PST
jifunza	mngejifunza	V;FIN;COND;PL;2;PRS
fagia	wangalifagia	V;FIN;COND;PL;3;PST
omba	tuhuomba	V;HAB;FIN;IND;PL;1;PRS
tazama	unatazama	V;DEF;FIN;IND;SG;2;PRS
tengeneza	nimetengeneza	V;PRF;FIN;IND;SG;1;PST
sinzia	utasinzia	V;FIN;IND;SG;2;FUT
fanya	ahufanya	V;HAB;FIN;IND;SG;3;PRS
ona	wataona	V;FIN;IND;PL;3;FUT
potea	ungalipotea	V;FIN;COND;SG;2;PST
kimbia	wamekimbia	V;PRF;FIN;IND;PL;3;PST
anza	niaanza	V;INDF;FIN;IND;SG;1;PRS
fagia	tulifagia	V;FIN;IND;PL;1;PST
jisikia	watajisikia	V;FIN;IND;PL;3;FUT
kausha	amekausha	V;PRF;FIN;IND;SG;3;PST
ona	waaona	V;INDF;FIN;IND;PL;3;PRS
kamata	niakamata	V;INDF;FIN;IND;SG;1;PRS
kata	mnakata	V;DEF;FIN;IND;PL;2;PRS
ondoa	aliondoa	V;FIN;IND;SG;3;PST
changanya	niachanganya	V;INDF;FIN;IND;SG;1;PRS
sinzia	tungesinzia	V;FIN;COND;PL;1;PRS
shinda	nitashinda	V;FIN;IND;SG;1;FUT
kopa	mngalikopa	V;FIN;COND;PL;2;PST
imba	tuaimba	V;INDF;FIN;IND;PL;1;PRS
fagia	wanafagia	V;DEF;FIN;IND;PL;3;PRS
tafuta	uatafuta	V;INDF;FIN;IND;SG;2;PRS
kusanya	ningalikusanya	V;FIN;COND;SG;1;PST
piga	mhupiga	V;HAB;FIN;IND;PL;2;PRS
soma	wanasoma	V;DEF;FIN;IND;PL;3;PRS
anza	anaanza	V;DEF;FIN;IND;SG;3;PRS
kamilisha	uakamilisha	V;INDF;FIN;IND;SG;2;PRS
kumbuka	ungalikumbuka	V;FIN;COND;SG;2;PST
fika	watafika	V;FIN;IND;PL;3;FUT
tazama	mngalitazama	V;FIN;COND;PL;2;PST
uwa	watauwa	V;FIN;IND;PL;3;FUT
fanya	mlifanya	V;FIN;IND;PL;2;PST
osha	tuaosha	V;INDF;FIN;IND;PL;1;PRS
ogelea	mnaogelea	V;DEF;FIN;IND;PL;2;PRS
tafuta	tungalitafuta	V;FIN;COND;PL;1;PST
vuta	angevuta	V;FIN;COND;SG;3;PRS
fika	uhufika	V;HAB;FIN;IND;SG;2;PRS
pea	tulipea	V;FIN;IND;PL;1;PST
fika	aafika	V;INDF;FIN;IND;SG;3;PRS
ogelea	wangeogelea	V;FIN;COND;PL;3;PRS
tengeneza	ahutengeneza	V;HAB;FIN;IND;SG;3;PRS
kamilisha	wahukamilisha	V;HAB;FIN;IND;PL;3;PRS
ambia	angeambia	V;FIN;COND;SG;3;PRS
kopa	ahukopa	V;HAB;FIN;IND;SG;3;PRS
leta	utaleta	V;FIN;IND;SG;2;FUT
kimbia	unakimbia	V;DEF;FIN;IND;SG;2;PRS
ponda	tunaponda	V;DEF;FIN;IND;PL;1;PRS
fagia	mnafagia	V;DEF;FIN;IND;PL;2;PRS
taka	aataka	V;INDF;FIN;IND;SG;3;PRS
kopa	ungalikopa	V;FIN;COND;SG;2;PST
shikilia	walishikilia	V;FIN;IND;PL;3;PST
anza	tutaanza	V;FIN;IND;PL;1;FUT
tazama	wangalitazama	V;FIN;COND;PL;3;PST
imba	wangaliimba	V;FIN;COND;PL;3;PST
shikilia	mngeshikilia	V;FIN;COND;PL;2;PRS
kamata	ungekamata	V;FIN;COND;SG;2;PRS
potea	angalipotea	V;FIN;COND;SG;3;PST
chapisha	tuhuchapisha	V;HAB;FIN;IND;PL;1;PRS
kumbuka	ulikumbuka	V;FIN;IND;SG;2;PST
kausha	nihukausha	V;HAB;FIN;IND;SG;1;PRS
fagia	mtafagia	V;FIN;IND;PL;2;FUT
lamba	walilamba	V;FIN;IND;PL;3;PST
saidia	angalisaidia	V;FIN;COND;SG;3;PST
ngoja	angengoja	V;FIN;COND;SG;3;PRS
chafya	watachafya	V;FIN;IND;PL;3;FUT
fuata	mhufuata	V;HAB;FIN;IND;PL;2;PRS
jisikia	mngalijisikia	V;FIN;COND;PL;2;PST
gonga	tumegonga	V;PRF;FIN;IND;PL;1;PST
ngoja	angalingoja	V;FIN;COND;SG;3;PST
saga	mlisaga	V;FIN;IND;PL;2;PST
kamata	ninakamata	V;DEF;FIN;IND;SG;1;PRS
changanya	nilichanganya	V;FIN;IND;SG;1;PST
tafuna	mmetafuna	V;PRF;FIN;IND;PL;2;PST
ponda	tuaponda	V;INDF;FIN;IND;PL;1;PRS
saga	tunasaga	V;DEF;FIN;IND;PL;1;PRS
soma	nilisoma	V;FIN;IND;SG;1;PST
shikilia	mlishikilia	V;FIN;IND;PL;2;PST
changanya	ungalichanganya	V;FIN;COND;SG;2;PST
andika	tuliandika	V;FIN;IND;PL;1;PST
pea	uhupea	V;HAB;FIN;IND;SG;2;PRS
punguza	tuapunguza	V;INDF;FIN;IND;PL;1;PRS
leta	ningeleta	V;FIN;COND;SG;1;PRS
kimbia	alikimbia	V;FIN;IND;SG;3;PST
soma	mngesoma	V;FIN;COND;PL;2;PRS
andika	utaandika	V;FIN;IND;SG;2;FUT
funza	aafunza	V;INDF;FIN;IND;SG;3;PRS
chukia	amechukia	V;PRF;FIN;IND;SG;3;PST
shinda	tulishinda	V;FIN;IND;PL;1;PST
chapisha	niachapisha	V;INDF;FIN;IND;SG;1;PRS
panguza	wangalipanguza	V;FIN;COND;PL;3;PST
nusa	atanusa	V;FIN;IND;SG;3;FUT
andika	uhuandika	V;HAB;FIN;IND;SG;2;PRS
fika	waafika	V;INDF;FIN;IND;PL;3;PRS
lamba	mhulamba	V;HAB;FIN;IND;PL;2;PRS
gusa	nimegusa	V;PRF;FIN;IND;SG;1;PST
kimbia	ningekimbia	V;FIN;COND;SG;1;PRS
jua	nitajua	V;FIN;IND;SG;1;FUT
paa	tunapaa	V;DEF;FIN;IND;PL;1;PRS
piga	uapiga	V;INDF;FIN;IND;SG;2;PRS
uwa	wahuuwa	V;HAB;FIN;IND;PL;3;PRS
saidia	mngesaidia	V;FIN;COND;PL;2;PRS
oga	ameoga	V;PRF;FIN;IND;SG;3;PST
enda	niaenda	V;INDF;FIN;IND;SG;1;PRS
cheka	nitacheka	V;FIN;IND;SG;1;FUT
jisikia	waajisikia	V;INDF;FIN;IND;PL;3;PRS
ona	mtaona	V;FIN;IND;PL;2;FUT
sema	tuasema	V;INDF;FIN;IND;PL;1;PRS
tafuna	tungalitafuna	V;FIN;COND;PL;1;PST
jifunza	nitajifunza	V;FIN;IND;SG;1;FUT
ngoja	tuangoja	V;INDF;FIN;IND;PL;1;PRS
kwaruza	nihukwaruza	V;HAB;FIN;IND;SG;1;PRS
pea	watapea	V;FIN;IND;PL;3;FUT
kopa	tunakopa	V;DEF;FIN;IND;PL;1;PRS
shikilia	ningalishikilia	V;FIN;COND;SG;1;PST
ogelea	wataogelea	V;FIN;IND;PL;3;FUT
funga	atafunga	V;FIN;IND;SG;3;FUT
bofya	mlibofya	V;FIN;IND;PL;2;PST
uwa	tuhuuwa	V;HAB;FIN;IND;PL;1;PRS
kimbia	uhukimbia	V;HAB;FIN;IND;SG;2;PRS
kamata	tunakamata	V;DEF;FIN;IND;PL;1;PRS
kausha	wangekausha	V;FIN;COND;PL;3;PRS
fika	tuafika	V;INDF;FIN;IND;PL;1;PRS
sukuma	nilisukuma	V;FIN;IND;SG;1;PST
tafuna	ungalitafuna	V;FIN;COND;SG;2;PST
ambia	waaambia	V;INDF;FIN;IND;PL;3;PRS
chukua	mlichukua	V;FIN;IND;PL;2;PST
vuta	kuvuta	V;FIN
fuata	ninafuata	V;DEF;FIN;IND;SG;1;PRS
paa	ninapaa	V;DEF;FIN;IND;SG;1;PRS
saga	mhusaga	V;HAB;FIN;IND;PL;2;PRS
funza	wangefunza	V;FIN;COND;PL;3;PRS
zima	mtazima	V;FIN;IND;PL;2;FUT
kunja	tutakunja	V;FIN;IND;PL;1;FUT
tembea	tutatembea	V;FIN;IND;PL;1;FUT
zaa	atazaa	V;FIN;IND;SG;3;FUT
pambua	nilipambua	V;FIN;IND;SG;1;PST
bandika	amebandika	V;PRF;FIN;IND;SG;3;PST
ota	mngeota	V;FIN;COND;PL;2;PRS
jua	mngejua	V;FIN;COND;PL;2;PRS
kohoa	walikohoa	V;FIN;IND;PL;3;PST
nunua	aanunua	V;INDF;FIN;IND;SG;3;PRS
inuka	umeinuka	V;PRF;FIN;IND;SG;2;PST
oga	wangalioga	V;FIN;COND;PL;3;PST
zaa	wamezaa	V;PRF;FIN;IND;PL;3;PST
vuta	wangalivuta	V;FIN;COND;PL;3;PST
elewa	mnaelewa	V;DEF;FIN;IND;PL;2;PRS
piga	utapiga	V;FIN;IND;SG;2;FUT
punguza	uapunguza	V;INDF;FIN;IND;SG;2;PRS
