ܓܪܒܝܐ	ܓܪܒܝ	N;SG;PSSD
ܡܪܝܬܐ	ܡܪܝܬܗ	N;SG;PSS3SM
ܥܠܘܠܐ	ܥܠܘܠܐ	ADJ;ABS;MASC;SG
ܥܠܘܠܐ	ܥܠܘܠܝܢ	N;ABS;PL
ܟܒܪܝܬܐ	ܟܒܪܝܬܐ	N;DEF;SG
ܦܛܝܪܐ	ܦܛܝܪܗ	N;SG;PSS3SF
ܟܗܢܘܬܐ	ܟܗܢܘܬܗܘܢ	N;SG;PSS3PM
ܪܚܡܢܘܬܐ	ܪܚܡܢܘܬܗܝܢ	N;SG;PSS3PF
ܟܒܝܪܐ	ܟܒܝܪܐ	ADJ;DEF;MASC;SG
ܝܘܪܩܐ	ܝܘܪܩܟ	N;SG;PSS2SM
ܙܕܝܩܘܬܐ	ܙܕܝܩܘܬܐ	N;DEF;SG
ܝܩܝܪܘܬܐ	ܝܩܝܪܘܬ	N;SG;PSSD
ܒܘܪܐ	ܒܘܪܝܟ	N;PL;PSS2SM
ܫܬܩܐ	ܫܬܩܟ	N;SG;PSS2SM
ܓܠܘܬܐ	ܓܠܘܬܟ	N;SG;PSS2SM
ܥܬܝܩܘܬܐ	ܥܬܝܩܘܬܢ	N;SG;PSS1P
ܡܡܘܢܐ	ܡܡܘܢܟܘܢ	N;SG;PSS2PM
ܐܪܝܟܘܬܐ	ܐܪܝܟܘܬ	N;SG;PSSD
ܓܫܘܫܘܬܐ	ܓܫܘܫܘܬ	N;SG;PSSD
ܥܠܝܡܐ	ܥܠܝܡܐ	ADJ;DEF;FEM;PL
ܫܒܒܐ	ܫܒܒܢ	N;SG;PSS1P
ܬܐܡܐ	ܬܐܡܬܐ	ADJ;DEF;MASC;SG
ܝܘܪܬܘܬܐ	ܝܘܪܬܘܬܝ	N;SG;PSS1S
ܐܣܩܐ	ܐܣܩ	N;SG;PSSD
ܩܛܝܪܐ	ܩܛܝܪܘܗܝ	N;PL;PSS3SM
ܩܛܝܪܐ	ܩܛܝܪܬܐ	ADJ;DEF;FEM;PL
ܛܢܢܐ	ܛܢܢܟܘܢ	N;SG;PSS2PM
ܛܝܝܐ	ܛܝܝܟܝܢ	N;SG;PSS2PF
ܥܠܘܠܐ	ܥܠܘܠܘܗܝ	N;PL;PSS3SM
ܝܒܝܫܬܐ	ܝܒܝܫܬܗ	N;PL;PSS3SM
ܬܐܡܐ	ܬܐܡܝ	ADJ;FEM;PL;PSSD
ܩܛܝܪܐ	ܩܛܝܪܟܝ	N;SG;PSS2SF
ܚܝܛܘܬܐ	ܚܝܛܘܬܗ	N;SG;PSS3SF
ܝܘܪܩܐ	ܝܘܪܩ	N;SG;PSSD
ܝܪܩܢܐ	ܝܪܩܢܘܗܝ	N;PL;PSS3SM
ܦܛܝܪܐ	ܦܛܝܪܝܟܝܢ	N;PL;PSS2PF
ܦܪܝܣܬܐ	ܦܪܝܣܬ	N;PL;PSSD
ܫܒܒܐ	ܫܒܒ	N;SG;PSSD
ܒܘܨܐ	ܒܘܨܗ	N;SG;PSS3SF
ܡܠܘܫܘܬܐ	ܡܠܘܫܘܬܗ	N;SG;PSS3SF
ܢܓܪܘܬܐ	ܢܓܪܘ	N;ABS;SG
ܥܒܕܘܬܐ	ܥܒܕܘܬܐ	N;DEF;SG
ܕܝܘܩܐ	ܕܝܘܩܗܝܢ	N;SG;PSS3PF
ܝܫܦܐ	ܝܫܦܗܘܢ	N;SG;PSS3PM
ܢܓܪܘܬܐ	ܢܓܪܘܬܐ	N;DEF;SG
ܝܘܪܩܐ	ܝܘܪܩܬ	ADJ;MASC;SG;PSSD
ܚܝܛܘܬܐ	ܚܝܛܘܬܟܘܢ	N;SG;PSS2PM
ܥܡܝܪܬܐ	ܥܡܝܪܬܟ	N;SG;PSS2SM
ܡܠܠܐ	ܡܠܠܗܝܢ	N;SG;PSS3PF
ܕܒܝܩܐ	ܕܒܝܩܗ	N;SG;PSS3SF
ܢܓܪܘܬܐ	ܢܓܪܘܬ	N;SG;PSSD
ܚܢܢܐ	ܚܢܢܢ	N;SG;PSS1P
ܝܪܘܩܐ	ܝܪܘܩܬ	ADJ;FEM;PL;PSSD
ܬܐܡܬܐ	ܬܐܡܬܟܝܢ	N;SG;PSS2PF
ܥܡܛܢܐ	ܥܡܛܢ	N;SG;PSSD
ܝܬܐ	ܝܬܗ	N;SG;PSS3SF
ܝܬܐ	ܝܬܢ	N;SG;PSS1P
ܚܠܕܝܬܐ	ܚܠܕܝܬܗ	N;SG;PSS3SF
ܫܬܩܐ	ܫܬܩܗ	N;SG;PSS3SM
ܬܠܡܝܕܘܬܐ	ܬܠܡܝܕܘܬܐ	N;DEF;SG
ܦܪܝܣܬܐ	ܦܪܝܣܬܐ	N;DEF;PL
ܣܢܝܘܬܐ	ܣܢܝܘܬܗܘܢ	N;SG;PSS3PM
ܝܫܦܐ	ܝܫܦ	N;ABS;SG
ܚܐܪܘܬܐ	ܚܐܪܘܬܟܝܢ	N;SG;PSS2PF
ܡܪܝܬܐ	ܡܪܝܬ	N;SG;PSSD
ܠܗܓܐ	ܠܗܓ	N;SG;PSSD
ܦܛܝܪܐ	ܦܛܝܪܟܘܢ	N;SG;PSS2PM
ܩܕܝܫܘܬܐ	ܩܕܝܫܘܬܢ	N;SG;PSS1P
ܝܬܡܐ	ܝܬܡܝܢ	ADJ;ABS;FEM;PL
ܩܛܘܠܐ	ܩܛܘܠܝܟܝܢ	N;PL;PSS2PF
ܣܘܡܩܐ	ܣܘܡܩܝ	N;PL;PSSD
ܫܪܪܐ	ܫܪܪܟܝܢ	N;SG;PSS2PF
ܡܢܢܐ	ܡܢܢܗ	N;SG;PSS3SF
ܒܘܪܐ	ܒܘܪܐ	N;DEF;PL
ܝܒܝܫܘܬܐ	ܝܒܝܫܘܬܗܘܢ	N;SG;PSS3PM
ܡܠܠܐ	ܡܠܠܝܗܘܢ	N;PL;PSS3PM
ܒܬܘܠܘܬܐ	ܒܬܘܠܘܬܟܘܢ	N;SG;PSS2PM
ܡܠܘܫܘܬܐ	ܡܠܘܫܘܬܝ	N;SG;PSS1S
ܣܦܢܘܬܐ	ܣܦܢܘܬܗ	N;SG;PSS3SM
ܟܒܪܝܬܐ	ܟܒܪܝܬܟ	N;SG;PSS2SM
ܬܦܫܘܪܬܐ	ܬܦܫܘܪܬܟܝܢ	N;SG;PSS2PF
ܡܠܠܐ	ܡܠܠ	N;ABS;SG
ܕܓܠܐ	ܕܓܠ	ADJ;ABS;MASC;SG
ܝܪܘܩܐ	ܝܪܘܩܬܐ	ADJ;DEF;FEM;SG
ܩܛܘܠܐ	ܩܛܘܠܗ	N;SG;PSS3SF
ܥܠܘܠܐ	ܥܠܘܠܟܝ	N;SG;PSS2SF
ܝܬܡܐ	ܝܬܡܝܢ	N;PL;PSS1P
ܐܒܩܐ	ܐܒܩ	N;SG;PSSD
ܣܘܡܩܐ	ܣܘܡܩܬ	ADJ;MASC;SG;PSSD
ܥܬܝܪܘܬܐ	ܥܬܝܪܘܬ	N;SG;PSSD
ܒܪܟܐ	ܒܪܟ	N;SG;PSSD
ܐܕܡܬܐ	ܐܕܡܬܗ	N;SG;PSS3SM
ܓܠܘܬܐ	ܓܠܘܬܗ	N;SG;PSS3SF
ܝܒܝܫܬܐ	ܝܒܝܫܐ	N;ABS;SG
ܒܛܢܘܬܐ	ܒܛܢܘܬ	N;SG;PSSD
ܫܩܝܦܐ	ܫܩܝܦܬ	ADJ;FEM;PL;PSSD
ܚܡܘܨܘܬܐ	ܚܡܘܨܘܬܢ	N;SG;PSS1P
ܦܪܘܫܐ	ܦܪܘܫ	N;SG;PSSD
ܡܣܟܐܢܘܬܐ	ܡܣܟܐܢܘܬܗܘܢ	N;SG;PSS3PM
ܕܓܠܐ	ܕܓܠܐ	N;DEF;SG
ܟܕܒܐ	ܟܕܒܝܟܘܢ	N;PL;PSS2PM
ܥܡܝܪܐ	ܥܡܝܪܗܘܢ	N;SG;PSS3PM
ܚܨܝܦܘܬܐ	ܚܨܝܦܘ	N;ABS;SG
ܡܐܪܝܬܐ	ܡܐܪܝܬܐ	N;DEF;SG
ܬܐܡܐ	ܬܐܡܝܟܝܢ	N;PL;PSS2PF
ܩܛܝܪܐ	ܩܛܝܪܬ	ADJ;FEM;PL;PSSD
ܬܝܢܬܐ	ܬܝܢܬܗܘܢ	N;SG;PSS3PM
ܪܟܟܐ	ܪܟܟܟܘܢ	N;SG;PSS2PM
ܫܪܝܪܘܬܐ	ܫܪܝܪܘܬܢ	N;SG;PSS1P
ܟܕܒܐ	ܟܕܒ	ADJ;ABS;MASC;SG
ܚܝܪܘܬܐ	ܚܝܪܘܬܟ	N;SG;PSS2SM
ܕܒܝܩܐ	ܕܒܝܩܝܢ	N;PL;PSS1P
ܡܡܘܢܐ	ܡܡܘܢܟܝ	N;SG;PSS2SF
ܕܝܘܩܐ	ܕܝܘܩܘܗܝ	N;PL;PSS3SM
ܒܪܒܪܝܐ	ܒܪܒܪܝܗ	N;SG;PSS3SM
ܟܐܢܘܬܐ	ܟܐܢܘܬܗܘܢ	N;SG;PSS3PM
ܝܬܡܐ	ܝܬܡܘܗܝ	N;PL;PSS3SM
ܝܩܕܬܐ	ܝܩܕܬܗ	N;SG;PSS3SF
ܡܠܠܐ	ܡܠܠܝ	N;PL;PSS1S
ܕܘܚܢܐ	ܕܘܚܢܗܘܢ	N;SG;PSS3PM
ܐܢܟܐ	ܐܢܟܟܝ	N;SG;PSS2SF
ܓܡܪܐ	ܓܡܪܢ	N;SG;PSS1P
ܩܕܡܝܘܬܐ	ܩܕܡܝܘܬܟܝܢ	N;SG;PSS2PF
ܫܘܩܠܐ	ܫܘܩܠܟ	N;SG;PSS2SM
ܕܢܚܐ	ܕܢܚܗܝܢ	N;SG;PSS3PF
ܩܛܝܪܐ	ܩܛܝܪܝܟܝ	N;PL;PSS2SF
ܝܒܝܫܬܐ	ܝܒܝܫܢ	N;ABS;PL
ܢܘܓܗܐ	ܢܘܓܗ	N;SG;PSSD
ܨܚܘܐ	ܨܚܘܗܝܢ	N;SG;PSS3PF
ܛܝܢܐ	ܛܝܢܗܝܢ	N;SG;PSS3PF
ܒܛܢܘܬܐ	ܒܛܢܘܬܗܘܢ	N;SG;PSS3PM
ܓܪܒܝܐ	ܓܪܒܝܗܝܢ	N;SG;PSS3PF
ܫܒܒܬܐ	ܫܒܒܢ	N;ABS;PL
ܝܬܡܐ	ܝܬܡܝ	N;PL;PSSD
ܫܒܒܐ	ܫܒܒܗܘܢ	N;SG;PSS3PM
ܢܓܪܘܬܐ	ܢܓܪܘܬܗܝܢ	N;SG;PSS3PF
ܥܠܝܡܐ	ܥܠܝܡܝܟܝ	N;PL;PSS2SF
ܚܐܘܬܐ	ܚܐܘܐ	N;ABS;SG
ܥܬܝܕܘܬܐ	ܥܬܝܕܘܬܟܘܢ	N;SG;PSS2PM
ܕܘܡܪܐ	ܕܘܡܪܟܝܢ	N;SG;PSS2PF
ܥܛܫܐ	ܥܛܫ	N;SG;PSSD
ܚܡܝܥܐ	ܚܡܝܥܟ	N;SG;PSS2SM
ܩܝܢܝܘܬܐ	ܩܝܢܝܘ	N;ABS;SG
ܐܟܘܠܐ	ܐܟܘܠܐ	ADJ;DEF;FEM;PL
ܢܘܨܦܐ	ܢܘܨܦ	N;ABS;SG
ܓܘܚܟܐ	ܓܘܚܟܝ	N;SG;PSS1S
ܐܘܪܟܐ	ܐܘܪܟܟܘܢ	N;SG;PSS2PM
ܝܨܝܦܘܬܐ	ܝܨܝܦܘܬܟܘܢ	N;SG;PSS2PM
ܕܒܝܩܐ	ܕܒܝܩ	ADJ;ABS;MASC;SG
ܥܠܝܡܐ	ܥܠܝܡܝ	ADJ;FEM;PL;PSSD
ܕܝܘܬܐ	ܕܝܘܬܗ	N;SG;PSS3SF
ܒܬܘܠܘܬܐ	ܒܬܘܠܘܬܝ	N;SG;PSS1S
ܣܢܝܐܘܬܐ	ܣܢܝܐܘܬܐ	N;DEF;SG
ܬܐܡܐ	ܬܐܡܬ	ADJ;FEM;PL;PSSD
ܫܩܝܦܐ	ܫܩܝܦܝܟ	N;PL;PSS2SM
ܚܐܘܬܐ	ܚܐܘܬܗܝܢ	N;SG;PSS3PF
ܚܐܪܘܬܐ	ܚܐܪܘܬܐ	N;DEF;SG
ܙܡܪܘܬܐ	ܙܡܪܘܬܟܝܢ	N;SG;PSS2PF
ܡܣܟܢܘܬܐ	ܡܣܟܢܘܬܗ	N;SG;PSS3SM
ܫܒܒܐ	ܫܒܒܗܝܢ	N;SG;PSS3PF
ܕܓܠܐ	ܕܓܠܢ	N;SG;PSS1P
ܫܩܝܦܐ	ܫܩܝܦܟ	N;SG;PSS2SM
ܝܘܪܩܐ	ܝܘܪܩܝ	N;PL;PSS1S
ܥܡܛܢܐ	ܥܡܛܢܢ	N;SG;PSS1P
ܟܬܟܘܬܐ	ܟܬܟܘܬܝ	N;SG;PSS1S
ܥܠܘܠܐ	ܥܠܘܠܝܟ	N;PL;PSS2SM
ܨܚܘܐ	ܨܚܘܐ	N;DEF;SG
ܚܨܝܦܘܬܐ	ܚܨܝܦܘܬܢ	N;SG;PSS1P
ܩܛܝܪܐ	ܩܛܝܪܗ	N;SG;PSS3SM
ܫܒܒܬܐ	ܫܒܒܬܗ	N;PL;PSS3SF
ܐܘܟܡܐ	ܐܘܟܡܝܟܝ	N;PL;PSS2SF
ܒܘܪܐ	ܒܘܪܬܐ	ADJ;DEF;FEM;PL
ܝܩܝܪܘܬܐ	ܝܩܝܪܘܬܗ	N;SG;PSS3SM
ܐܘܟܡܐ	ܐܘܟܡ	N;SG;PSSD
ܫܘܩܠܐ	ܫܘܩܠ	N;ABS;SG
ܦܝܓܢܐ	ܦܓܢܝ	N;SG;PSS1S
ܐܘܫܢܐ	ܐܘܫܢܝܗ	N;PL;PSS3SF
ܝܘܪܩܐ	ܝܘܪܩܬܐ	ADJ;DEF;MASC;SG
ܬܐܡܬܐ	ܬܐܡܬܟ	N;SG;PSS2SM
ܢܘܓܗܐ	ܢܘܓܗܟܘܢ	N;SG;PSS2PM
ܫܘܩܠܐ	ܫܘܩܠܢ	N;SG;PSS1P
ܫܬܩܐ	ܫܬܩܐ	N;DEF;SG
ܟܒܝܪܐ	ܟܒܝܪܢ	ADJ;ABS;FEM;PL
ܩܕܝܫܘܬܐ	ܩܕܝܫܘܬܝ	N;SG;PSS1S
ܫܒܒܐ	ܫܒܒ	ADJ;ABS;MASC;SG
ܡܫܚܠܦܐ	ܡܫܚܠܦܐ	ADJ;DEF;MASC;SG
ܛܒܚܘܬܐ	ܛܒܚܘܬܗ	N;SG;PSS3SM
ܒܘܪܐ	ܒܘܪܐ	N;DEF;SG
ܦܛܝܪܐ	ܦܛܝܪܟܝܢ	N;SG;PSS2PF
ܬܐܡܐ	ܬܐܡܘܗܝ	N;PL;PSS3SM
ܪܫܥܐ	ܪܫܥܗܝܢ	N;SG;PSS3PF
ܙܡܪܘܬܐ	ܙܡܪܘܬܝ	N;SG;PSS1S
ܡܡܘܢܐ	ܡܡܘܢܗܘܢ	N;SG;PSS3PM
ܓܫܘܫܘܬܐ	ܓܫܘܫܘܬܗ	N;SG;PSS3SF
ܬܐܡܐ	ܬܐܡܝܟܝ	N;PL;PSS2SF
ܐܘܟܡܐ	ܐܘܟܡܐ	N;DEF;SG
ܫܩܝܦܐ	ܫܩܝܦ	ADJ;ABS;MASC;SG
ܝܬܡܐ	ܝܬܡܗ	N;SG;PSS3SM
ܥܠܘܠܐ	ܥܠܘܠܐ	N;DEF;PL
ܕܘܚܢܐ	ܕܘܚܢܝ	N;SG;PSS1S
ܬܐܡܐ	ܬܐܡܢ	ADJ;ABS;FEM;PL
ܨܦܘܢܐ	ܨܦܘܢܟܝܢ	N;SG;PSS2PF
ܡܣܟܐܢܘܬܐ	ܡܣܟܐܢܘܬܗܝܢ	N;SG;PSS3PF
ܚܐܘܬܐ	ܚܐܘܬ	N;SG;PSSD
ܙܪܢܝܟܐ	ܙܪܢܝܟܗ	N;SG;PSS3SM
ܬܪܝܨܘܬܐ	ܬܪܝܨܘܬܟ	N;SG;PSS2SM
ܐܙܒܐ	ܐܙܒܟ	N;SG;PSS2SM
ܚܢܢܐ	ܚܢܢܟ	N;SG;PSS2SM
ܝܪܩܢܐ	ܝܪܩܢܐ	N;DEF;SG
ܐܘܟܡܐ	ܐܘܟܡܬ	ADJ;FEM;PL;PSSD
ܝܪܩܢܐ	ܝܪܩܢܬ	ADJ;FEM;PL;PSSD
ܡܠܠܐ	ܡܠܠܝ	ADJ;FEM;PL;PSSD
ܦܛܝܪܐ	ܦܛܝܪ	N;ABS;SG
ܪܚܡܢܘܬܐ	ܪܚܡܢܘܬܗܘܢ	N;SG;PSS3PM
ܕܝܘܩܐ	ܕܝܘܩܟ	N;SG;PSS2SM
ܓܘܚܟܐ	ܓܘܚܟܢ	N;SG;PSS1P
ܛܝܝܐ	ܛܝܝܝܟܘܢ	N;PL;PSS2PM
ܐܘܪܟܐ	ܐܘܪܟܟܝ	N;SG;PSS2SF
ܥܠܘܠܐ	ܥܠܘܠܟܘܢ	N;SG;PSS2PM
ܟܒܝܪܐ	ܟܒܝܪ	ADJ;MASC;SG;PSSD
ܚܐܫܐ	ܚܐܫܗܝܢ	N;SG;PSS3PF
ܦܛܝܪܐ	ܦܛܝܪܐ	ADJ;DEF;MASC;SG
ܐܘܡܢܐ	ܐܘܡܢܬ	ADJ;FEM;PL;PSSD
ܢܓܪܘܬܐ	ܢܓܪܘܬܝ	N;SG;PSS1S
ܬܝܡܢܐ	ܬܝܡܢܐ	N;DEF;SG
ܩܛܘܠܐ	ܩܛܘܠ	N;ABS;SG
ܢܓܪܘܬܐ	ܢܓܪܘܬܟܘܢ	N;SG;PSS2PM
ܢܓܪܘܬܐ	ܢܓܪܘܬܟܝ	N;SG;PSS2SF
ܐܪܝܟܘܬܐ	ܐܪܝܟܘܬܐ	N;DEF;SG
ܫܝܢܐ	ܫܝܢܢ	N;SG;PSS1P
ܪܚܡܘܬܐ	ܪܚܡܘܬܢ	N;SG;PSS1P
ܦܛܝܪܐ	ܦܛܝܪܝܢ	N;PL;PSS1P
ܕܓܠܐ	ܕܓܠܐ	ADJ;DEF;MASC;SG
ܚܝܛܘܬܐ	ܚܝܛܘܬܝ	N;SG;PSS1S
ܣܢܝܐܘܬܐ	ܣܢܝܐܘܬܟܝ	N;SG;PSS2SF
ܥܠܘܠܐ	ܥܠܘܠܬܐ	ADJ;DEF;MASC;SG
ܩܛܝܪܐ	ܩܛܝܪܝܗܝܢ	N;PL;PSS3PF
ܝܒܫܢܐ	ܝܒܫܢܐ	N;DEF;SG
ܐܘܫܢܐ	ܐܘܫܢܝܟܝ	N;PL;PSS2SF
ܡܠܘܫܘܬܐ	ܡܠܘܫܘܬܟܘܢ	N;SG;PSS2PM
ܣܐܡܐ	ܣܐܡܝ	N;SG;PSS1S
ܕܝܘܩܐ	ܕܝܘܩܝ	N;SG;PSS1S
ܐܘܫܢܐ	ܐܘܫܢܝ	N;PL;PSS1S
ܐܣܩܐ	ܐܣܩܟܝܢ	N;SG;PSS2PF
ܒܛܢܘܬܐ	ܒܛܢܘܬܢ	N;SG;PSS1P
ܝܬܐ	ܝܬܟ	N;SG;PSS2SM
ܐܕܡܬܐ	ܐܕܡܬܟ	N;SG;PSS2SM
ܩܛܘܠܐ	ܩܛܘܠܝܟ	N;PL;PSS2SM
ܟܐܢܘܬܐ	ܟܐܢܘܬܗ	N;SG;PSS3SF
ܛܝܝܐ	ܛܝܝ	N;SG;PSSD
ܚܡܘܨܘܬܐ	ܚܡܘܨܘܬܗܝܢ	N;SG;PSS3PF
ܥܡܛܢܐ	ܥܡܛܢܝ	N;SG;PSS1S
ܝܒܝܫܘܬܐ	ܝܒܝܫܘܬܗ	N;SG;PSS3SF
ܝܬܡܐ	ܝܬܡܟ	N;SG;PSS2SM
ܦܫܪܬܐ	ܦܫܪܬܗܝܢ	N;SG;PSS3PF
ܡܠܠܐ	ܡܠܠܝܟܘܢ	N;PL;PSS2PM
ܢܘܨܦܐ	ܢܘܨܦܗ	N;SG;PSS3SF
ܥܠܝܡܐ	ܥܠܝܡܝܢ	N;ABS;PL
ܦܬܠܐ	ܦܬܠ	N;SG;PSSD
ܫܩܝܦܐ	ܫܩܝܦܗܘܢ	N;SG;PSS3PM
ܬܠܡܝܕܘܬܐ	ܬܠܡܝܕܘ	N;ABS;SG
ܕܝܘܩܐ	ܕܝܘܩܬܐ	ADJ;DEF;FEM;PL
ܓܫܘܫܘܬܐ	ܓܫܘܫܘܬܗܘܢ	N;SG;PSS3PM
ܥܠܘܠܐ	ܥܠܘܠܬ	ADJ;FEM;PL;PSSD
ܕܝܘܬܐ	ܕܝܘܬܟܝܢ	N;SG;PSS2PF
ܦܛܝܪܐ	ܦܛܝܪܬ	ADJ;FEM;PL;PSSD
ܡܡܘܢܐ	ܡܡܘܢܐ	N;DEF;SG
ܒܪܟܐ	ܒܪܟܟܘܢ	N;SG;PSS2PM
ܕܘܡܪܐ	ܕܘܡܪܟ	N;SG;PSS2SM
ܐܘܡܢܐ	ܐܘܡܢܝܟܘܢ	N;PL;PSS2PM
ܨܒܝܢܝܘܬܐ	ܨܒܝܢܝܘܬ	N;SG;PSSD
ܚܡܝܥܐ	ܚܡܝܥܗܘܢ	N;SG;PSS3PM
ܦܠܙܐ	ܦܠܙܗܝܢ	N;SG;PSS3PF
ܝܬܡܐ	ܝܬܡܝܟܘܢ	N;PL;PSS2PM
ܛܝܝܐ	ܛܝܝܝܟܝܢ	N;PL;PSS2PF
ܪܚܡܘܬܐ	ܪܚܡܘ	N;ABS;SG
ܐܘܡܢܐ	ܐܘܡܢܘܗܝ	N;PL;PSS3SM
ܩܡܚܐ	ܩܡܚܝ	N;SG;PSS1S
ܦܫܪܬܐ	ܦܫܪܬܟܝ	N;SG;PSS2SF
ܝܒܫܢܐ	ܝܒܫܢܟܝܢ	N;SG;PSS2PF
ܫܘܩܠܐ	ܫܘܩܠܐ	N;DEF;SG
ܦܛܝܪܐ	ܦܛܝܪܝܢ	N;ABS;PL
ܥܠܝܡܐ	ܥܠܝܡܝܗܘܢ	N;PL;PSS3PM
ܫܩܝܦܐ	ܫܩܝܦܗܝܢ	N;SG;PSS3PF
ܥܬܝܕܘܬܐ	ܥܬܝܕܘܬ	N;SG;PSSD
ܨܚܘܐ	ܨܚܘ	N;SG;PSSD
ܛܝܢܐ	ܛܝܢܟܝܢ	N;SG;PSS2PF
ܬܐܡܐ	ܬܐܡܐ	ADJ;ABS;MASC;SG
ܝܨܝܦܘܬܐ	ܝܨܝܦܘܬܗܝܢ	N;SG;PSS3PF
ܫܝܢܐ	ܫܝܢܟܝ	N;SG;PSS2SF
ܟܒܝܪܐ	ܟܒܝܪܬܐ	ADJ;DEF;FEM;SG
ܐܒܩܐ	ܐܒܩܟܝܢ	N;SG;PSS2PF
ܪܫܥܐ	ܪܫܥ	N;SG;PSSD
ܕܝܘܬܐ	ܕܝܘ	N;ABS;SG
ܐܘܡܢܐ	ܐܘܡܢܟܘܢ	N;SG;PSS2PM
ܚܐܘܬܐ	ܚܐܘܬܢ	N;SG;PSS1P
ܟܕܒܐ	ܟܕܒܝ	N;PL;PSSD
ܡܣܟܢܘܬܐ	ܡܣܟܢܘܬܟܝܢ	N;SG;PSS2PF
ܐܘܟܡܐ	ܐܘܟܡܗܝܢ	N;SG;PSS3PF
ܝܒܝܫܬܐ	ܝܒܝܫܬܗ	N;SG;PSS3SM
ܐܒܩܐ	ܐܒܩܗܝܢ	N;SG;PSS3PF
ܬܐܡܐ	ܬܐܡܬܐ	ADJ;DEF;FEM;PL
ܪܚܡܘܬܐ	ܪܚܡܘܬܐ	N;DEF;SG
ܦܪܘܫܐ	ܦܪܘܫ	ADJ;ABS;MASC;SG
ܥܘܙܐ	ܥܘܙܗ	N;SG;PSS3SF
ܡܩܕܡܘܬܐ	ܡܩܕܡܘܬܟܝ	N;SG;PSS2SF
ܕܓܠܐ	ܕܓܠܟܝܢ	N;SG;PSS2PF
ܪܛܒܐ	ܪܛܒܢ	N;SG;PSS1P
ܣܛܝܡܐ	ܣܛܝܡܟܝ	N;SG;PSS2SF
ܚܝܪܘܬܐ	ܚܝܪܘܬܟܘܢ	N;SG;PSS2PM
ܥܡܝܪܬܐ	ܥܡܝܪܬܗ	N;SG;PSS3SF
ܟܒܪܝܬܐ	ܟܒܪܝܬܟܝ	N;SG;PSS2SF
ܚܟܬܐ	ܚܟܬܟܝܢ	N;SG;PSS2PF
ܣܡܝܘܬܐ	ܣܡܝܘܬܗܘܢ	N;SG;PSS3PM
ܕܢܚܐ	ܕܢܚܟ	N;SG;PSS2SM
ܙܡܝܬܐ	ܙܡܝܬ	N;SG;PSSD
ܚܝܛܘܬܐ	ܚܝܛܘ	N;ABS;SG
ܦܫܪܬܐ	ܦܫܪܬܗܘܢ	N;SG;PSS3PM
ܒܛܝܠܘܬܐ	ܒܛܝܠܘܬܗ	N;SG;PSS3SF
ܓܡܪܐ	ܓܡܪܐ	N;DEF;SG
ܣܘܡܩܐ	ܣܘܡܩܝܟܝ	N;PL;PSS2SF
ܨܦܘܢܐ	ܨܦܘܢܝ	N;SG;PSS1S
ܐܟܘܠܐ	ܐܟܘܠܝܗܘܢ	N;PL;PSS3PM
ܩܕܡܝܘܬܐ	ܩܕܡܝܘܬܐ	N;DEF;SG
ܥܡܝܪܬܐ	ܥܡܝܪܬܐ	N;DEF;SG
ܐܘܫܢܐ	ܐܘܫܢܝܢ	N;PL;PSS1P
ܚܐܫܐ	ܚܐܫܗܘܢ	N;SG;PSS3PM
ܥܠܝܡܐ	ܥܠܝܡܐ	ADJ;DEF;MASC;SG
ܝܩܕܬܐ	ܝܩܕܬܝ	N;SG;PSS1S
ܣܘܡܩܐ	ܣܘܡܩܝܟܝܢ	N;PL;PSS2PF
ܡܐܪܝܬܐ	ܡܐܪܝܬܟ	N;SG;PSS2SM
ܫܩܝܦܐ	ܫܩܝܦܝܟܝܢ	N;PL;PSS2PF
ܙܕܝܩܘܬܐ	ܙܕܝܩܘܬܗܝܢ	N;SG;PSS3PF
ܐܘܟܡܐ	ܐܘܟܡܟܝ	N;SG;PSS2SF
ܟܐܢܘܬܐ	ܟܐܢܘܬܐ	N;DEF;SG
ܬܝܡܢܐ	ܬܝܡܢܗܝܢ	N;SG;PSS3PF
ܪܛܒܐ	ܪܛܒܗܘܢ	N;SG;PSS3PM
ܫܝܢܐ	ܫܝܢܗܘܢ	N;SG;PSS3PM
ܡܡܠܠܘܬܐ	ܡܡܠܠܘܬܗܘܢ	N;SG;PSS3PM
ܥܠܝܡܐ	ܥܠܝܡܝܢ	N;PL;PSS1P
ܦܠܙܐ	ܦܠܙ	N;SG;PSSD
ܪܝܪܐ	ܪܝܪ	N;SG;PSSD
ܫܒܒܐ	ܫܒܒܝܢ	N;ABS;PL
ܚܝܪܘܬܐ	ܚܝܪܘܬܐ	N;DEF;SG
ܨܗܘܐ	ܨܗܘܟܘܢ	N;SG;PSS2PM
ܣܦܢܘܬܐ	ܣܦܢܘܬܟܘܢ	N;SG;PSS2PM
ܠܗܓܐ	ܠܗܓܗܘܢ	N;SG;PSS3PM
ܫܒܒܐ	ܫܒܒܝܟܝ	N;PL;PSS2SF
ܫܒܒܬܐ	ܫܒܒܬܗܝܢ	N;SG;PSS3PF
ܙܕܝܩܘܬܐ	ܙܕܝܩܘ	N;ABS;SG
ܥܛܫܐ	ܥܛܫܟ	N;SG;PSS2SM
ܫܘܩܠܐ	ܫܘܩܠܟܘܢ	N;SG;PSS2PM
ܬܝܡܢܐ	ܬܝܡܢܟ	N;SG;PSS2SM
ܒܛܢܘܬܐ	ܒܛܢܘܬܗܝܢ	N;SG;PSS3PF
ܣܡܝܘܬܐ	ܣܡܝܘܬܗ	N;SG;PSS3SM
ܛܝܝܐ	ܛܝܝܢ	ADJ;ABS;FEM;PL
ܡܠܠܐ	ܡܠܠܬܐ	ADJ;DEF;MASC;SG
ܝܫܦܐ	ܝܫܦܟܝܢ	N;SG;PSS2PF
ܥܠܘܠܐ	ܥܠܘܠܝܟܝ	N;PL;PSS2SF
ܪܚܡܢܘܬܐ	ܪܚܡܢܘ	N;ABS;SG
ܝܩܕܬܐ	ܝܩܕܬܗ	N;SG;PSS3SM
ܥܠܘܠܐ	ܥܠܘܠܝ	N;PL;PSSD
ܡܡܘܢܐ	ܡܡܘܢܟܝܢ	N;SG;PSS2PF
ܐܟܘܠܐ	ܐܟܘܠܐ	ADJ;DEF;MASC;SG
ܡܠܘܫܘܬܐ	ܡܠܘܫܘܬܟ	N;SG;PSS2SM
ܕܓܠܐ	ܕܓܠܬ	ADJ;FEM;PL;PSSD
ܒܛܝܠܘܬܐ	ܒܛܝܠܘܬܟܘܢ	N;SG;PSS2PM
ܝܬܡܐ	ܝܬܡܢ	N;SG;PSS1P
ܪܝܪܐ	ܪܝܪܗ	N;SG;PSS3SF
ܚܡܝܥܘܬܐ	ܚܡܝܥܘܬܗܝܢ	N;SG;PSS3PF
ܣܢܝܘܬܐ	ܣܢܝܘܬܝ	N;SG;PSS1S
ܚܐܫܐ	ܚܐܫ	N;SG;PSSD
ܛܝܝܐ	ܛܝܝܟܝ	N;SG;PSS2SF
ܛܝܢܐ	ܛܝܢܗܘܢ	N;SG;PSS3PM
ܙܡܪܘܬܐ	ܙܡܪܘܬܗ	N;SG;PSS3SF
ܡܣܟܝܢܘܬܐ	ܡܣܟܝܢܘܬܟܝܢ	N;SG;PSS2PF
ܫܪܝܪܘܬܐ	ܫܪܝܪܘܬܗ	N;SG;PSS3SF
ܝܪܘܩܐ	ܝܪܘܩܢ	ADJ;ABS;FEM;PL
ܚܐܪܘܬܐ	ܚܐܪܘ	N;ABS;SG
ܥܡܝܪܬܐ	ܥܡܝܪܬܗ	N;SG;PSS3SM
ܕܝܘܩܐ	ܕܝܘܩܬ	ADJ;FEM;PL;PSSD
ܩܛܝܪܐ	ܩܛܝܪܗܘܢ	N;SG;PSS3PM
ܝܨܝܦܘܬܐ	ܝܨܝܦܘܬ	N;SG;PSSD
ܒܬܘܠܘܬܐ	ܒܬܘܠܘܬܗܘܢ	N;SG;PSS3PM
ܟܗܢܘܬܐ	ܟܗܢܘܬܗ	N;SG;PSS3SF
ܕܘܡܪܐ	ܕܘܡܪܢ	N;SG;PSS1P
ܬܝܢܬܐ	ܬܝܢܬܟܝܢ	N;SG;PSS2PF
ܕܓܠܐ	ܕܓܠܝܢ	ADJ;ABS;FEM;PL
ܐܟܘܠܐ	ܐܟܘܠܝܢ	ADJ;ABS;FEM;PL
ܡܩܕܡܘܬܐ	ܡܩܕܡܘܬܗܝܢ	N;SG;PSS3PF
ܡܡܠܠܘܬܐ	ܡܡܠܠܘܬܟ	N;SG;PSS2SM
ܦܪܘܫܐ	ܦܪܘܫܟ	N;SG;PSS2SM
ܣܢܝܘܬܐ	ܣܢܝܘܬܢ	N;SG;PSS1P
ܣܡܝܘܬܐ	ܣܡܝܘܬܐ	N;DEF;SG
ܕܓܠܐ	ܕܓܠܝܗܘܢ	N;PL;PSS3PM
ܕܒܝܩܐ	ܕܒܝܩܝܗܝܢ	N;PL;PSS3PF
ܩܕܡܝܘܬܐ	ܩܕܡܝܘܬܗ	N;SG;PSS3SF
ܩܛܝܪܐ	ܩܛܝܪܝܗܘܢ	N;PL;PSS3PM
ܓܠܘܬܐ	ܓܠܘܬ	N;SG;PSSD
ܒܪܒܪܝܐ	ܒܪܒܪܝ	N;SG;PSSD
ܛܒܚܘܬܐ	ܛܒܚܘܬܐ	N;DEF;SG
ܬܦܫܘܪܬܐ	ܬܦܫܘܪܬܟܝ	N;SG;PSS2SF
ܦܪܝܣܬܐ	ܦܪܝܣܬܟ	N;PL;PSS2SM
ܥܬܝܕܘܬܐ	ܥܬܝܕܘܬܗ	N;SG;PSS3SM
ܬܠܡܝܕܘܬܐ	ܬܠܡܝܕܘܬܗ	N;SG;PSS3SF
ܥܠܘܠܐ	ܥܠܘܠܐ	N;DEF;SG
ܟܦܣܐ	ܟܦܣ	N;SG;PSSD
ܓܫܘܫܘܬܐ	ܓܫܘܫܘܬܟ	N;SG;PSS2SM
ܬܠܡܝܕܘܬܐ	ܬܠܡܝܕܘܬܟܘܢ	N;SG;PSS2PM
ܪܚܡܘܬܐ	ܪܚܡܘܬܟ	N;SG;PSS2SM
ܛܒܚܘܬܐ	ܛܒܚܘܬܢ	N;SG;PSS1P
ܒܬܘܠܘܬܐ	ܒܬܘܠܘܬܐ	N;DEF;SG
ܦܪܘܫܐ	ܦܪܘܫ	N;ABS;SG
ܦܪܝܣܬܐ	ܦܪܝܣܬܗܘܢ	N;SG;PSS3PM
ܙܓܘܐ	ܙܓܘܐ	N;DEF;SG
ܥܛܫܐ	ܥܛܫܗܝܢ	N;SG;PSS3PF
ܦܬܠܐ	ܦܬܠ	N;ABS;SG
ܣܛܝܡܐ	ܣܛܝܡܝ	N;SG;PSS1S
ܛܝܝܐ	ܛܝܝܐ	N;DEF;PL
ܐܘܪܟܐ	ܐܘܪܟܗ	N;SG;PSS3SM
ܩܛܘܠܐ	ܩܛܘܠܝܢ	N;PL;PSS1P
ܩܛܝܪܐ	ܩܛܝܪܝ	N;PL;PSS1S
ܩܛܘܠܐ	ܩܛܘܠ	N;SG;PSSD
ܒܪܒܪܝܐ	ܒܪܒܪܝܝ	ADJ;FEM;PL;PSSD
ܝܒܫܢܐ	ܝܒܫܢܢ	N;SG;PSS1P
ܪܝܪܐ	ܪܝܪܢ	N;SG;PSS1P
ܒܘܪܐ	ܒܘܪܝܟܝ	N;PL;PSS2SF
ܓܨܐ	ܓܨܟܝ	N;SG;PSS2SF
ܒܬܘܠܘܬܐ	ܒܬܘܠܘܬܗܝܢ	N;SG;PSS3PF
ܕܝܘܩܐ	ܕܝܘܩܝܟܝܢ	N;PL;PSS2PF
ܡܠܠܐ	ܡܠܠܗ	N;SG;PSS3SF
ܡܠܘܫܘܬܐ	ܡܠܘܫܘ	N;ABS;SG
ܫܩܝܦܐ	ܫܩܝܦܬ	ADJ;MASC;SG;PSSD
ܥܬܝܕܘܬܐ	ܥܬܝܕܘܬܟܝܢ	N;SG;PSS2PF
ܓܫܘܫܘܬܐ	ܓܫܘܫܘܬܐ	N;DEF;SG
ܙܡܪܘܬܐ	ܙܡܪܘܬܟܘܢ	N;SG;PSS2PM
ܝܘܪܬܘܬܐ	ܝܘܪܬܘܬܟܘܢ	N;SG;PSS2PM
ܣܢܝܐܘܬܐ	ܣܢܝܐܘܬܟܘܢ	N;SG;PSS2PM
ܐܟܘܠܐ	ܐܟܘܠܗܝܢ	N;SG;PSS3PF
ܟܦܣܐ	ܟܦܣ	N;ABS;SG
ܙܪܢܝܟܐ	ܙܪܢܝܟܗܘܢ	N;SG;PSS3PM
ܫܘܒܩܢܐ	ܫܘܒܩܢܗ	N;SG;PSS3SF
ܙܕܝܩܘܬܐ	ܙܕܝܩܘܬܗ	N;SG;PSS3SF
ܒܪܒܪܝܐ	ܒܪܒܪܝܟ	N;SG;PSS2SM
ܨܚܘܐ	ܨܚܘܟ	N;SG;PSS2SM
ܬܠܡܝܕܘܬܐ	ܬܠܡܝܕܘܬ	N;SG;PSSD
ܨܦܘܢܐ	ܨܦܘܢܗ	N;SG;PSS3SF
ܚܡܘܨܘܬܐ	ܚܡܘܨܘܬܝ	N;SG;PSS1S
ܝܘܪܩܐ	ܝܘܪܩܐ	N;DEF;PL
ܚܟܬܐ	ܚܟܬܗ	N;SG;PSS3SM
ܓܪܒܝܐ	ܓܪܒܝܗ	N;SG;PSS3SM
ܫܪܝܪܘܬܐ	ܫܪܝܪܘܬܟܝ	N;SG;PSS2SF
ܢܓܪܘܬܐ	ܢܓܪܘܬܟܝܢ	N;SG;PSS2PF
ܣܐܡܐ	ܣܐܡ	N;SG;PSSD
ܣܦܢܘܬܐ	ܣܦܢܘܬܢ	N;SG;PSS1P
ܩܕܡܝܘܬܐ	ܩܕܡܝܘܬ	N;SG;PSSD
ܩܕܡܝܘܬܐ	ܩܕܡܝܘܬܗܝܢ	N;SG;PSS3PF
ܝܬܡܐ	ܝܬܡܝܢ	N;ABS;PL
ܕܘܚܢܐ	ܕܘܚܢܗܝܢ	N;SG;PSS3PF
ܙܡܪܘܬܐ	ܙܡܪܘܬܟܝ	N;SG;PSS2SF
ܬܐܡܐ	ܬܐܡܟܝܢ	N;SG;PSS2PF
ܦܝܓܢܐ	ܦܓܢܗ	N;SG;PSS3SF
ܐܒܕܢܐ	ܐܒܕܢܟܝ	N;SG;PSS2SF
ܐܣܩܐ	ܐܣܩܝ	N;SG;PSS1S
ܣܛܝܡܐ	ܣܛܝܡ	N;ABS;SG
ܣܘܡܩܐ	ܣܘܡܩܝܢ	ADJ;ABS;FEM;PL
ܕܒܝܩܐ	ܕܒܝܩܟܝܢ	N;SG;PSS2PF
ܦܪܝܣܬܐ	ܦܪܝܣܬܢ	N;SG;PSS1P
ܚܘܡܐ	ܚܘܡ	N;ABS;SG
ܠܗܓܐ	ܠܗܓ	N;ABS;SG
ܫܝܢܐ	ܫܝܢܟܝܢ	N;SG;PSS2PF
ܨܒܥܘܬܐ	ܨܒܥܘܬܗܘܢ	N;SG;PSS3PM
ܓܪܒܝܐ	ܓܪܒܝܗܘܢ	N;SG;PSS3PM
ܬܦܫܘܪܬܐ	ܬܦܫܘܪܬ	N;SG;PSSD
ܐܘܡܢܐ	ܐܘܡܢܝ	N;PL;PSSD
ܬܝܡܢܐ	ܬܝܡܢܟܘܢ	N;SG;PSS2PM
ܕܝܘܬܐ	ܕܝܘܬܝ	N;SG;PSS1S
ܟܢܘܬܐ	ܟܢܘܬܝ	N;SG;PSS1S
ܒܘܪܐ	ܒܘܪܢ	ADJ;ABS;FEM;PL
ܐܟܘܠܐ	ܐܟܘܠܝܟܝ	N;PL;PSS2SF
ܫܒܒܐ	ܫܒܒܗ	N;SG;PSS3SF
ܓܪܒܝܐ	ܓܪܒܝܗ	N;SG;PSS3SF
ܫܒܒܬܐ	ܫܒܒܬܗܝܢ	N;PL;PSS3PF
ܛܝܝܐ	ܛܝܝܐ	N;DEF;SG
ܥܛܫܐ	ܥܛܫܝ	N;SG;PSS1S
ܪܟܟܐ	ܪܟܟܗ	N;SG;PSS3SF
ܕܓܠܐ	ܕܓܠ	ADJ;MASC;SG;PSSD
ܣܢܝܘܬܐ	ܣܢܝܘܬܟܝܢ	N;SG;PSS2PF
ܒܘܨܐ	ܒܘܨ	N;ABS;SG
ܛܝܢܐ	ܛܝܢܢ	N;SG;PSS1P
ܝܩܝܪܘܬܐ	ܝܩܝܪܘܬܟܘܢ	N;SG;PSS2PM
ܐܒܝܕܘܬܐ	ܐܒܝܕܘܬܟ	N;SG;PSS2SM
ܦܪܝܣܬܐ	ܦܪܝܣܬܗܝܢ	N;SG;PSS3PF
ܟܡܘܢܐ	ܟܡܘܢܗܝܢ	N;SG;PSS3PF
ܐܒܝܕܘܬܐ	ܐܒܝܕܘܬܝ	N;SG;PSS1S
ܫܪܪܐ	ܫܪܪ	N;SG;PSSD
ܚܐܫܐ	ܚܐܫܝ	N;SG;PSS1S
ܦܫܪܬܐ	ܦܫܪܬܟܘܢ	N;SG;PSS2PM
ܫܬܩܐ	ܫܬܩܗ	N;SG;PSS3SF
ܚܠܕܝܬܐ	ܚܠܕܝܬܗܝܢ	N;SG;PSS3PF
ܟܕܒܐ	ܟܕܒܗܘܢ	N;SG;PSS3PM
ܚܡܘܨܘܬܐ	ܚܡܘܨܘܬܗ	N;SG;PSS3SF
ܓܨܐ	ܓܨܗ	N;SG;PSS3SM
ܫܒܒܐ	ܫܒܒܝܟ	N;PL;PSS2SM
ܢܘܓܗܐ	ܢܘܓܗܗܝܢ	N;SG;PSS3PF
ܦܝܓܢܐ	ܦܓܢܢ	N;SG;PSS1P
ܚܐܘܬܐ	ܚܐܘܬܟܘܢ	N;SG;PSS2PM
ܬܐܡܐ	ܬܐܡܐ	ADJ;DEF;FEM;PL
ܒܛܝܠܘܬܐ	ܒܛܝܠܘܬܝ	N;SG;PSS1S
ܫܩܝܦܐ	ܫܩܝܦܐ	N;DEF;SG
ܦܪܘܫܐ	ܦܪܘܫܐ	ADJ;DEF;MASC;SG
ܚܢܢܐ	ܚܢܢܗܘܢ	N;SG;PSS3PM
ܦܪܘܫܐ	ܦܪܘܫܬܐ	ADJ;DEF;FEM;PL
ܛܝܢܐ	ܛܝܢܗ	N;SG;PSS3SM
ܟܕܒܐ	ܟܕܒܝ	ADJ;FEM;PL;PSSD
ܡܣܟܝܢܘܬܐ	ܡܣܟܝܢܘܬܢ	N;SG;PSS1P
ܥܡܛܢܐ	ܥܡܛܢܗ	N;SG;PSS3SF
ܐܘܡܢܐ	ܐܘܡܢܗ	N;SG;PSS3SM
ܥܬܝܪܘܬܐ	ܥܬܝܪܘܬܗܝܢ	N;SG;PSS3PF
ܢܘܓܗܐ	ܢܘܓܗܟܝ	N;SG;PSS2SF
ܩܝܢܝܘܬܐ	ܩܝܢܝܘܬܢ	N;SG;PSS1P
ܪܘܟܟܐ	ܪܘܟܟܝ	N;SG;PSS1S
ܛܝܝܐ	ܛܝܝܘܗܝ	N;PL;PSS3SM
ܚܒܪܘܬܐ	ܚܒܪܘܬܟܝ	N;SG;PSS2SF
ܒܘܪܐ	ܒܘܪܢ	N;SG;PSS1P
ܡܡܠܠܘܬܐ	ܡܡܠܠܘܬܟܝ	N;SG;PSS2SF
ܐܟܘܠܐ	ܐܟܘܠܬ	ADJ;MASC;SG;PSSD
ܦܪܝܣܬܐ	ܦܪܝܣܬܟܝܢ	N;PL;PSS2PF
ܫܒܒܬܐ	ܫܒܒܬܝ	N;PL;PSS1S
ܕܒܝܩܐ	ܕܒܝܩܝ	N;PL;PSSD
ܬܝܢܬܐ	ܬܝܢܬܟܘܢ	N;SG;PSS2PM
ܪܝܪܐ	ܪܝܪܟܝ	N;SG;PSS2SF
ܨܒܝܢܝܘܬܐ	ܨܒܝܢܝܘ	N;ABS;SG
ܦܪܘܫܐ	ܦܪܘܫܝܢ	N;PL;PSS1P
ܚܢܢܐ	ܚܢܢ	N;SG;PSSD
ܬܠܡܝܕܘܬܐ	ܬܠܡܝܕܘܬܟܝ	N;SG;PSS2SF
ܟܒܝܪܐ	ܟܒܝܪܬ	ADJ;FEM;PL;PSSD
ܡܠܠܐ	ܡܠܠܝܗ	N;PL;PSS3SF
ܢܘܓܗܐ	ܢܘܓܗܗ	N;SG;PSS3SF
ܨܒܥܘܬܐ	ܨܒܥܘܬܗ	N;SG;PSS3SF
ܕܝܘܩܐ	ܕܝܘܩܬܐ	ADJ;DEF;MASC;SG
ܡܣܟܝܢܘܬܐ	ܡܣܟܝܢܘܬ	N;SG;PSSD
ܟܕܒܐ	ܟܕܒܝܢ	N;ABS;PL
ܟܒܪܝܬܐ	ܟܒܪܝܬܗ	N;SG;PSS3SM
ܦܫܪܬܐ	ܦܫܪܐ	N;ABS;SG
ܕܝܘܬܐ	ܕܝܘܬܟ	N;SG;PSS2SM
ܟܬܟܘܬܐ	ܟܬܟܘܬܗܘܢ	N;SG;PSS3PM
ܣܪܡܛܐ	ܣܪܡܛܬ	ADJ;FEM;SG;PSSD
