liban	lilibanan	V;PFOC;LGSPEC1
isip	inisip	V;PFV;PFOC
bagsak	bagsak	V;NFIN
alaga'	alaga'	V;NFIN
nakaw	ninanakaw	V;IPFV;PFOC
maneho	minamaneho	V;IPFV;PFOC
másid	minamásdan	V;IPFV;PFOC
taguyod	itataguyod	V;PFOC;LGSPEC1
kuha'	kukuhanin	V;PFOC;LGSPEC1
basag	nagbasag	V;PFV;AGFOC
hirap	hirap	V;NFIN
babá'	babá'	V;NFIN
panalo	nananalo	V;IPFV;AGFOC
hagod	hahagurin	V;PFOC;LGSPEC1
sundó'	sinundó'	V;PFV;PFOC
kusot	kukusutin	V;PFOC;LGSPEC1
gayat	ginagayat	V;IPFV;PFOC
bagsak	binabagsak	V;IPFV;PFOC
suway	sumuway	V;PFV;AGFOC
ulit	umuulit	V;IPFV;AGFOC
sauli'	nagsasauli'	V;IPFV;AGFOC
tabí	nagtatabi	V;IPFV;AGFOC
liban	nilibanan	V;PFV;PFOC
babala'	nagbababala'	V;IPFV;AGFOC
senyas	sumenyas	V;PFV;AGFOC
punó'	pinunó'	V;PFV;PFOC
kuha'	mangunguuha'	V;AGFOC;LGSPEC1
bili	bumili	V;PFV;AGFOC
maneho	mamanehuin	V;PFOC;LGSPEC1
ingat	nag-iingat	V;IPFV;AGFOC
lungkot	lungkot	V;NFIN
arúga'	arúga'	V;NFIN
regalo	regalo	V;NFIN
táas	nagtáas	V;PFV;AGFOC
sákit	sinasáktan	V;IPFV;PFOC
kailangan	nanga-ilangan	V;PFV;AGFOC
gáwa'	ginagawa'	V;IPFV;PFOC
uwí'	inuwí'	V;PFV;PFOC
ibig	iibigin	V;PFOC;LGSPEC1
kain	nagpapakain	V;IPFV;AGFOC
lakbay	nilakbay	V;PFV;PFOC
tapos	tinatapos	V;IPFV;PFOC
sará	sinará	V;PFV;PFOC
layó'	lalayuan	V;PFOC;LGSPEC1
bigay	binigay	V;PFV;PFOC
tugtog	tinutugtog	V;IPFV;PFOC
másid	mamásdan	V;PFOC;LGSPEC1
hatid	hatid	V;NFIN
akusa	mang-aakusa	V;AGFOC;LGSPEC1
walá'	iwawalá'	V;PFOC;LGSPEC1
bilis	bilisan	V;PFV;PFOC
tanan	nagtanan	V;PFV;AGFOC
panalo	napapanalunan	V;IPFV;PFOC
tayó'	itatayó'	V;PFOC;LGSPEC1
taguyod	nagtataguyod	V;IPFV;AGFOC
tira	tumitira	V;IPFV;AGFOC
usap	pinapag-usapan	V;IPFV;PFOC
sunog	sunog	V;NFIN
útot	uútutin	V;PFOC;LGSPEC1
abot	nag-abot	V;PFV;AGFOC
salita'	salita'	V;NFIN
subo'	subo'	V;NFIN
surí'	magsusurí'	V;AGFOC;LGSPEC1
líto	nalilíto	V;IPFV;AGFOC
dali'	magmamadali'	V;AGFOC;LGSPEC1
dagdag	dadagdagan	V;PFOC;LGSPEC1
balí'	binalí' nabalí'	V;PFV;PFOC
muhí'	namumuhí'	V;IPFV;AGFOC
hila	naghila	V;PFV;AGFOC
dínig	dininig dinirig	V;PFV;PFOC
hikab	hinikaban	V;PFV;PFOC
akala	mag-aakala	V;AGFOC;LGSPEC1
tanong	tanong	V;NFIN
kailangan	nanganga-ilangan	V;IPFV;AGFOC
dama	dumama	V;PFV;AGFOC
takot	takot	V;NFIN
gusto	magugustuhan	V;PFOC;LGSPEC1
sigaw	sinigawan	V;PFV;PFOC
imbento	nag-iimbento	V;IPFV;AGFOC
dasal	dinadasal	V;IPFV;PFOC
akit	naakit	V;PFV;AGFOC
regalo	nagreregalo	V;IPFV;AGFOC
hila	maghihila	V;AGFOC;LGSPEC1
sulat	susulat	V;AGFOC;LGSPEC1
hingí'	humihingí	V;IPFV;AGFOC
upa	uupa	V;AGFOC;LGSPEC1
katay	katay	V;NFIN
kusot	kinusot	V;PFV;PFOC
akit	naaakit	V;IPFV;AGFOC
simangot	simangot	V;NFIN
pasan	pinasan	V;PFV;PFOC
hirap	naghihirap	V;IPFV;AGFOC
balita	balita	V;NFIN
pansin	pinansin	V;PFV;PFOC
arúga'	nag-aarúga'	V;IPFV;AGFOC
arte	aarte	V;AGFOC;LGSPEC1
ngiti	ngumingiti	V;IPFV;AGFOC
lutó'	lutó'	V;NFIN
sundó'	nagsundó'	V;PFV;AGFOC
suway	sinusuway	V;IPFV;PFOC
táyo'	tinayuan	V;PFV;PFOC
tulak	nagtutulak	V;IPFV;AGFOC
sundó'	sundó'	V;NFIN
lakbay	nilalakbay	V;IPFV;PFOC
sukat	nagsukat	V;PFV;AGFOC
bisita	bibisitahin	V;PFOC;LGSPEC1
tingín	tiníngnan	V;PFV;PFOC
lubog	nilulubog	V;IPFV;PFOC
iyak	iniiyakan	V;IPFV;PFOC
biro'	bibiruin	V;PFOC;LGSPEC1
sigaw	magsisigawan	V;AGFOC;LGSPEC1
útot	útot	V;NFIN
makinilya	minakinilya	V;PFV;PFOC
kinig	pinapakinggan	V;IPFV;PFOC
ábot	mag-aábot	V;AGFOC;LGSPEC1
akusa	nang-aakusa	V;IPFV;AGFOC
dasal	nagdasal	V;PFV;AGFOC
táas	tináas	V;PFV;PFOC
burá	burá	V;NFIN
saká	sinasaká	V;IPFV;PFOC
punit	punit	V;NFIN
bigay	ibinibigay	V;IPFV;PFOC
handá'	humandá'	V;PFV;AGFOC
bigay	binibigyan	V;IPFV;PFOC
pigil	nagpipigil	V;IPFV;AGFOC
sigaw	sinigaw	V;PFV;PFOC
loko	loko	V;NFIN
alís	alís	V;NFIN
kilala	magpapakilala	V;AGFOC;LGSPEC1
gulong	igugulong	V;PFOC;LGSPEC1
tinda	itinitinda	V;IPFV;PFOC
usap	nag-uusap	V;IPFV;AGFOC
sulong	sulong	V;NFIN
lakbay	lakbay	V;NFIN
hatid	ihahatid	V;PFOC;LGSPEC1
buti	buti	V;NFIN
tugtog	tutugtugin	V;PFOC;LGSPEC1
lungkot	nalulungkot	V;IPFV;AGFOC
sagot	sumagot	V;PFV;AGFOC
akala	nag-aakala	V;IPFV;AGFOC
isdá'	nangisdá'	V;PFV;AGFOC
gawá'	gawá'	V;NFIN
tinda	itininda	V;PFV;PFOC
imbita	iimbitahin	V;PFOC;LGSPEC1
nakaw	ninakaw	V;PFV;PFOC
gupit	ginupit	V;PFV;PFOC
hanap	humanap	V;PFV;AGFOC
gamit	ginamit	V;PFV;PFOC
huni	hinunihan	V;PFV;PFOC
gamit	gamit	V;NFIN
suót	susuót	V;AGFOC;LGSPEC1
abot	aabot	V;AGFOC;LGSPEC1
timbang	magtitimbang	V;AGFOC;LGSPEC1
tawa	tawa	V;NFIN
burá	binuburá	V;IPFV;PFOC
dampot	dinampot	V;PFV;PFOC
lutó'	maglulutó'	V;AGFOC;LGSPEC1
ibig	inibig	V;PFV;PFOC
balí'	balí'	V;NFIN
anak	manganganak	V;AGFOC;LGSPEC1
alís	umalís	V;PFV;AGFOC
lipat	lilipat	V;AGFOC;LGSPEC1
tapos	tapos	V;NFIN
sará	nagsasará	V;IPFV;AGFOC
higa'	hinihigaan	V;IPFV;PFOC
gulong	gulong	V;NFIN
hatid	hinahatid	V;IPFV;PFOC
mangha'	mangha'	V;NFIN
layó'	lalayó'	V;AGFOC;LGSPEC1
kailangan	kinakailangan	V;IPFV;PFOC
dating	dumating	V;PFV;AGFOC
buhos	binuhos	V;PFV;PFOC
hawak	hahakawan	V;PFOC;LGSPEC1
awit	awit	V;NFIN
damdám	daramdámin	V;PFOC;LGSPEC1
bakasyon	babakasyunan	V;PFOC;LGSPEC1
gusto	ginugusto	V;IPFV;PFOC
kuhá'	kukuhá'	V;AGFOC;LGSPEC1
lubog	lubog	V;NFIN
kabit	magkakabit	V;AGFOC;LGSPEC1
higa'	higa'	V;NFIN
daan	dinaanan	V;PFV;PFOC
gupit	ginugupit	V;IPFV;PFOC
okupá	inokupá	V;PFV;PFOC
basa	binabasahan	V;IPFV;PFOC
ngiti	nginingitian	V;IPFV;PFOC
taas	nagtataas	V;IPFV;AGFOC
ulat	nag-uulat	V;IPFV;AGFOC
búkas	nagbubúkas	V;IPFV;AGFOC
wagi'	ipinapagwagi'	V;IPFV;PFOC
lípad	lumilípad	V;IPFV;AGFOC
pirma	pirma	V;NFIN
lapit	nilalapitan	V;IPFV;PFOC
tapon	magtatapon	V;AGFOC;LGSPEC1
bulong	ibinubulong	V;IPFV;PFOC
sáma	isináma	V;PFV;PFOC
tuloy	tumuloy	V;PFV;AGFOC
pugot	magpupugot	V;AGFOC;LGSPEC1
sipol	sisipol	V;AGFOC;LGSPEC1
tángo'	tinatangú'an	V;IPFV;PFOC
balí'	babalí'in mababalí'	V;PFOC;LGSPEC1
yari'	nangyari'	V;PFV;AGFOC
bigay	magbibigay	V;AGFOC;LGSPEC1
dating	daratnan	V;PFOC;LGSPEC1
lusob	lulusubin	V;PFOC;LGSPEC1
galit	papagalitan	V;PFOC;LGSPEC1
laga	nilaga	V;PFV;PFOC
dínig	nadinig narinig	V;PFV;AGFOC
benta	nagbenta	V;PFV;AGFOC
hatí'	hahatí'in	V;PFOC;LGSPEC1
tángo'	tatángo'	V;AGFOC;LGSPEC1
sama	sasamahan	V;PFOC;LGSPEC1
gáwa'	ginagáwa'	V;IPFV;PFOC
dínig	didinggin diringinggin	V;PFOC;LGSPEC1
ipon	iniipon	V;IPFV;PFOC
tapon	tinatapon	V;IPFV;PFOC
parada	paparada	V;AGFOC;LGSPEC1
sayá	pinagsasayá	V;IPFV;PFOC
babá'	bababá'	V;AGFOC;LGSPEC1
bitbit	nagbibitbit	V;IPFV;AGFOC
pátay	nagpátay	V;PFV;AGFOC
hálik	hahálik	V;AGFOC;LGSPEC1
bakasyon	bakasyon	V;NFIN
másid	nagmásid	V;PFV;AGFOC
imbento	nag-imbento	V;PFV;AGFOC
garahe	iginagarahe	V;IPFV;PFOC
ása	inaásahan	V;IPFV;PFOC
sampay	sampay	V;NFIN
sibak	magsisibak	V;AGFOC;LGSPEC1
pirma	pinipirmahan	V;IPFV;PFOC
kita	nakita	V;PFV;PFOC
sulit	nagsusulit	V;IPFV;AGFOC
intindi	iintindi	V;AGFOC;LGSPEC1
hatid	hinatid	V;PFV;PFOC
labá	naglabá	V;PFV;AGFOC
labas	naglabas	V;PFV;AGFOC
tulong	tinulungan	V;PFV;PFOC
tanggap	tatanggap	V;AGFOC;LGSPEC1
tanggi	tanggi	V;NFIN
pangako'	mangangako'	V;AGFOC;LGSPEC1
palit	pinapalitan	V;IPFV;PFOC
balik	binalikan	V;PFV;PFOC
sáma	isinasáma	V;IPFV;PFOC
lapit	lalapitan	V;PFOC;LGSPEC1
hanap	hinanap	V;PFV;PFOC
babala'	magbababala'	V;AGFOC;LGSPEC1
isip	nag-iisip	V;IPFV;AGFOC
bisita	bumisita	V;PFV;AGFOC
sulit	nagsulit	V;PFV;AGFOC
ulit	uulit	V;AGFOC;LGSPEC1
subo'	nagsusubo'	V;IPFV;AGFOC
kusot	nagkukusot	V;IPFV;AGFOC
sukó'	isusukó'	V;PFOC;LGSPEC1
kipkip	nagkipkip	V;PFV;AGFOC
alala	mag-aalala	V;AGFOC;LGSPEC1
layas	lalayas	V;AGFOC;LGSPEC1
niwala	naniniwala	V;IPFV;AGFOC
biro'	magbibiro'	V;AGFOC;LGSPEC1
laga	nilalaga	V;IPFV;PFOC
sulat	nagsulat	V;PFV;AGFOC
gamit	gagamit	V;AGFOC;LGSPEC1
galing	galing	V;NFIN
huli	humuli	V;PFV;AGFOC
limot	nakakalimot	V;IPFV;AGFOC
gibá'	gigibá'in	V;PFOC;LGSPEC1
balot	nagbabalot	V;IPFV;AGFOC
dampot	dampot	V;NFIN
utang	inutang	V;PFV;PFOC
upa	uupahan	V;PFOC;LGSPEC1
sagot	sumasagot	V;IPFV;AGFOC
ipon	nag-ipon	V;PFV;AGFOC
dampot	dadamputin	V;PFOC;LGSPEC1
pugot	pugot	V;NFIN
alam	inaalam	V;IPFV;PFOC
tahi'	nagtahi'	V;PFV;AGFOC
puntá	puntá	V;NFIN
tingín	nagpatingín	V;PFV;AGFOC
bangon	binangon	V;PFV;PFOC
lipad	lilipad	V;AGFOC;LGSPEC1
liban	liban	V;NFIN
gamit	gumamit	V;PFV;AGFOC
tayó'	nagtatayó'	V;IPFV;AGFOC
útot	inútot	V;PFV;PFOC
kabit	kabit	V;NFIN
punta	pumupunta	V;IPFV;AGFOC
panalo	mananalo	V;AGFOC;LGSPEC1
kabit	nagkabit	V;PFV;AGFOC
sampay	nagsasampay	V;IPFV;AGFOC
uwí'	uwí'	V;NFIN
akit	aakitin	V;PFOC;LGSPEC1
kain	kinain	V;PFV;PFOC
kasal	kinasal	V;PFV;PFOC
alam	inalam	V;PFV;PFOC
hintay	naghihintay	V;IPFV;AGFOC
dusa	nagdudusa	V;IPFV;AGFOC
utos	mag-uutos	V;AGFOC;LGSPEC1
bakasyon	binabakasyunan	V;IPFV;PFOC
galit	ginalit	V;PFV;PFOC
púnit	pupúnitin	V;PFOC;LGSPEC1
sayaw	sinasayaw	V;IPFV;PFOC
hulog	nahulog	V;PFV;AGFOC
higa'	humiga'	V;PFV;AGFOC
lipad	nilipad	V;PFV;PFOC
liban	liliban	V;AGFOC;LGSPEC1
ábot	inábot	V;PFV;PFOC
púno'	napúno'	V;PFV;AGFOC
arte	inaartehan	V;IPFV;PFOC
takot	tatakutin	V;PFOC;LGSPEC1
mangha'	mamamangha'	V;AGFOC;LGSPEC1
sauli'	isasauli'	V;PFOC;LGSPEC1
buhos	ibubuhos	V;PFOC;LGSPEC1
hindí'	hinindí'an	V;PFV;PFOC
babala'	nagbabala'	V;PFV;AGFOC
dalá	dalá	V;NFIN
oo	umooo	V;IPFV;AGFOC
wasak	mawawasak wawasakin	V;PFOC;LGSPEC1
hálik	hahálikan	V;PFOC;LGSPEC1
sumbong	sumbong	V;NFIN
dínig	dinidinig dinirinig	V;IPFV;PFOC
arkila	arkila	V;NFIN
taka	ipinagtataka	V;IPFV;PFOC
dampot	dinadampot	V;IPFV;PFOC
tawag	tinatawagan	V;IPFV;PFOC
ingay	nag-iingay	V;IPFV;AGFOC
punit	nagpunit pumunit	V;PFV;AGFOC
pasyal	pinasyalan	V;PFV;PFOC
bantay	binantayan	V;PFV;PFOC
samá'	sumamá'	V;PFV;AGFOC
laga	naglaga	V;PFV;AGFOC
linis	maglilinis	V;AGFOC;LGSPEC1
kain	kumain	V;PFV;AGFOC
gamot	maggagamot	V;AGFOC;LGSPEC1
biro'	nagbiro'	V;PFV;AGFOC
kagat	kumagat	V;PFV;AGFOC
lípad	lilípad	V;AGFOC;LGSPEC1
taguyod	nagtaguyod	V;PFV;AGFOC
lagnat	lalagnatin	V;PFOC;LGSPEC1
unlad	inunlad	V;PFV;PFOC
lungkot	malulungkot	V;AGFOC;LGSPEC1
balot	binalot	V;PFV;PFOC
tahol	tumahol	V;PFV;AGFOC
sumbong	isusumbong	V;PFOC;LGSPEC1
sibak	sinisibak	V;IPFV;PFOC
kuhá'	kuhá'	V;NFIN
upa	upa	V;NFIN
talon	tatalunin	V;PFOC;LGSPEC1
tanggi	tinanggihan	V;PFV;PFOC
suót	suót	V;NFIN
hulog	nahuhulog	V;IPFV;AGFOC
tahol	tatahulan	V;PFOC;LGSPEC1
líto	nililíto	V;IPFV;PFOC
tapon	itatapon	V;PFOC;LGSPEC1
subok	sumusubok	V;IPFV;AGFOC
kita	nakakita	V;PFV;AGFOC
lipad	nililipad	V;IPFV;PFOC
renta	nirenta	V;PFV;PFOC
kuhá'	kumuhá'	V;PFV;AGFOC
inom	iniinom	V;IPFV;PFOC
táas	tinatáas	V;IPFV;PFOC
laban	laban	V;NFIN
anak	pinapanganak	V;IPFV;PFOC
tahi'	tatahiin	V;PFOC;LGSPEC1
layó'	nilayuan	V;PFV;PFOC
gáwa'	gagáwain gagáwin	V;PFOC;LGSPEC1
samba	nagsasamba	V;IPFV;AGFOC
tayó'	itinatayó'	V;IPFV;PFOC
gibá'	ginigibá'	V;IPFV;PFOC
awit	umaawit	V;IPFV;AGFOC
buhay	bumubuhay	V;IPFV;AGFOC
kain	papakainin	V;PFOC;LGSPEC1
pútol	pumútol	V;PFV;AGFOC
taka	magtataka	V;AGFOC;LGSPEC1
patay	mamamatay	V;AGFOC;LGSPEC1
mangha'	mamamanghaan	V;PFOC;LGSPEC1
dasal	dasal	V;NFIN
hirap	hinihirap	V;IPFV;PFOC
ilaw	iilawan	V;PFOC;LGSPEC1
sirá'	sinisirá'an	V;IPFV;PFOC
bulong	ibinulong	V;PFV;PFOC
abot	aabutan	V;PFOC;LGSPEC1
tawag	tinawag	V;PFV;PFOC
kopya	kokopya	V;AGFOC;LGSPEC1
sinungaling	nag- sinungaling	V;PFV;AGFOC
hikab	hihikaban	V;PFOC;LGSPEC1
init	nag-iinit	V;IPFV;AGFOC
lunok	lulunok	V;AGFOC;LGSPEC1
punó'	púpunuin	V;PFOC;LGSPEC1
layó'	layó'	V;NFIN
subok	susubukin	V;PFOC;LGSPEC1
hintay	maghihintay	V;AGFOC;LGSPEC1
kain	nagpakain	V;PFV;AGFOC
sama	sinasamahan	V;IPFV;PFOC
tawa	tatawanan	V;PFOC;LGSPEC1
kagat	kinakagat	V;IPFV;PFOC
plantsa	magplaplantsa	V;AGFOC;LGSPEC1
ngiti	nginitian	V;PFV;PFOC
ayos	inaayos	V;IPFV;PFOC
usog	nag-uusog	V;IPFV;AGFOC
alaga'	mag-aalaga'	V;AGFOC;LGSPEC1
plantsa	pinaplantsa	V;IPFV;PFOC
dama	dumarama	V;IPFV;AGFOC
plantsa	pinaltsa	V;PFV;PFOC
hárap	hahárap	V;AGFOC;LGSPEC1
buhos	buhos	V;NFIN
lípad	lilíparin	V;PFOC;LGSPEC1
suri'	nagsuri'	V;PFV;AGFOC
lípad	nilípad	V;PFV;PFOC
bába'	magbabába'	V;AGFOC;LGSPEC1
kamit	nakamit	V;PFV;AGFOC
sunog	nagsunog	V;PFV;AGFOC
ganda	magpapaganda	V;AGFOC;LGSPEC1
kuhá'	kinuhá'	V;PFV;PFOC
trabaho	tatrabahuin	V;PFOC;LGSPEC1
tanan	nagtatanan	V;IPFV;AGFOC
pasok	pinasok	V;PFV;PFOC
takbo	tumatakbo	V;IPFV;AGFOC
pinta	pinipintahan	V;IPFV;PFOC
pirma	pumirma	V;PFV;AGFOC
kusot	kusot	V;NFIN
biro'	biniro'	V;PFV;PFOC
ayos	inayos	V;PFV;PFOC
sanlá'	nagsanlá'	V;PFV;AGFOC
kuha	kukuhain	V;PFOC;LGSPEC1
balita	magbabalita	V;AGFOC;LGSPEC1
sumbong	nagsumbong	V;PFV;AGFOC
utos	inutusan	V;PFV;PFOC
garahe	iginarahe	V;PFV;PFOC
balot	nagbalot	V;PFV;AGFOC
wasak	nagwasak	V;PFV;AGFOC
pinta	pipintahin	V;PFOC;LGSPEC1
mahal	magmamahal	V;AGFOC;LGSPEC1
order	inoorder	V;IPFV;PFOC
tahol	tatahol	V;AGFOC;LGSPEC1
limot	lilimutin	V;PFOC;LGSPEC1
bilis	bibilisan	V;PFOC;LGSPEC1
okupá	mag-ookupá	V;AGFOC;LGSPEC1
pigil	pipigilan	V;PFOC;LGSPEC1
higpit	naghigpit	V;PFV;AGFOC
tawid	tinatawid	V;IPFV;PFOC
parada	pumarada	V;PFV;AGFOC
hatíd	maghahatíd	V;AGFOC;LGSPEC1
sunog	sinunog	V;PFV;PFOC
gibá'	ginibá'	V;PFV;PFOC
damdám	dinaramdám	V;IPFV;PFOC
renta	nagrerenta	V;IPFV;AGFOC
labá	nilalabhan	V;IPFV;PFOC
lipat	nilipat	V;PFV;PFOC
sipilyo 	sipilyo 	V;NFIN
kátok	kátok	V;NFIN
bangon	ibabangon	V;PFOC;LGSPEC1
gibá'	naggigibá'	V;IPFV;AGFOC
imbita	nag-imbita	V;PFV;AGFOC
palakpak	papalakpak	V;AGFOC;LGSPEC1
pahinga	nagpapahinga	V;IPFV;AGFOC
tanim	itatanim	V;PFOC;LGSPEC1
galing	nanggaling	V;PFV;AGFOC
lábas	lalábas	V;AGFOC;LGSPEC1
tángo'	tatangú'an	V;PFOC;LGSPEC1
hugas	hinuhugasan	V;IPFV;PFOC
laró'	nilaró'	V;PFV;PFOC
laki	inilalaki	V;IPFV;PFOC
kamay	nagkakamayan	V;IPFV;AGFOC
sugal	sugal	V;NFIN
sinungaling	sisinu- ngalingan	V;PFOC;LGSPEC1
alaga'	aalagaan	V;PFOC;LGSPEC1
kasal	pinakasalan	V;PFV;PFOC
masahe	nagmasahe	V;PFV;AGFOC
sama	sama	V;NFIN
patay	papatayin	V;PFOC;LGSPEC1
oo	ooo	V;AGFOC;LGSPEC1
balita	nagbabalita	V;IPFV;AGFOC
linis	nililinis	V;IPFV;PFOC
sayaw	sumayaw	V;PFV;AGFOC
okupá	nag-ookupá	V;IPFV;AGFOC
sipol	sinipulan	V;PFV;PFOC
hingí'	hingí'	V;NFIN
kíta	makikipagkíta	V;PFOC;LGSPEC1
pútol	pinupútol	V;IPFV;PFOC
