buyrumaq	buyruding	V;SG;2;INFM;PST
yapmaq	yépiwatattuq	V;PROG;PL;1;PST
mu'amile qilmaq	mu'amile qildim	V;SG;1;PST
heydimek	heydigenidingiz	V;PRF;FRML;SG;2;PST
öltürmek	öltürmigenidi	V;PRF;SG;3;NEG;PST
ögenmek	ögenmekchisiz	V;FRML;INTEN;SG;2;PRS
oylimaq	oylidim	V;SG;1;PST
untumaq	untattinglar	V;IPFV;PL;2;PST
oynimaq	oynighansen	V;PRF;SG;2;INFM;PRS
barmaq	bériwatimen	V;PROG;SG;1;PRS
naxsha éytmaq	naxsha éytmighan	V;PRF;PL;3;NEG;PRS
olturmaq	olturattinglar	V;IPFV;PL;2;PST
oxshatmaq	oxshitiwatattinglar	V;PROG;PL;2;PST
qoymaq	qoymaqchiduq	V;INTEN;PL;1;PST
mu'amile qilmaq	mu'amile qiliwatimen	V;PROG;SG;1;PRS
untumaq	untughaniding	V;PRF;SG;2;INFM;PST
ögenmek	ögen'migeniduq	V;PRF;PL;1;NEG;PST
yetküzmek	yetküzmekchidinglar	V;INTEN;PL;2;PST
heydimek	heydigenmiz	V;PRF;PL;1;PRS
jawab bermek	jawab bermigen	V;PRF;PL;3;NEG;PRS
qorqmaq	qorqiwatimiz	V;PROG;PL;1;PRS
heydimek	heydigensen	V;PRF;SG;2;INFM;PRS
yetküzmek	yetküzdingiz	V;FRML;SG;2;PST
tingshimaq	tingshimaqchimiz	V;INTEN;PL;1;PRS
untumaq	untumaqchiduq	V;INTEN;PL;1;PST
anglimaq	anglawatatting	V;PROG;SG;2;INFM;PST
tölimek	tölimigensiz	V;PRF;FRML;SG;2;NEG;PRS
sorimaq	sorimaqchi	V;INTEN;PL;3;PRS
achmaq	achtim	V;SG;1;PST
qalmaq	qéliwatattuq	V;PROG;PL;1;PST
buyrumaq	buyruwatatti	V;PROG;PL;3;PST
nepeslenmek	nepeslenmekchisiz	V;FRML;INTEN;SG;2;PRS
bayqimaq	bayqimighansiler	V;PRF;PL;2;NEG;PRS
achmaq	achmaqchiduq	V;INTEN;PL;1;PST
heydimek	heydewatisiler	V;PROG;PL;2;PRS
aghrinmaq	aghrinattingiz	V;IPFV;FRML;SG;2;PST
tölimek	tölimekchiduq	V;INTEN;PL;1;PST
ewetmek	ewetkenidi	V;PRF;SG;3;PST
yaqturmaq	yaqturisiler	V;IPFV;PL;2;PRS
bayqimaq	bayqighanidi	V;PRF;SG;3;PST
epsuslanmaq	epsuslanmaqchi	V;INTEN;SG;3;PRS
buyrumaq	buyrudingiz	V;FRML;SG;2;PST
bashlimaq	bashlawatatti	V;PROG;SG;3;PST
aghrinmaq	aghriniwatatti	V;PROG;PL;3;PST
mu'amile qilmaq	mu'amile qilimen	V;IPFV;SG;1;PRS
tashlimaq	tashlaymiz	V;IPFV;PL;1;PRS
tapshuruwalmaq	tapshuruwalmaqchiduq	V;INTEN;PL;1;PST
urushmaq	urushqanidim	V;PRF;SG;1;PST
sorimaq	sorimighanidi	V;PRF;PL;3;NEG;PST
yapmaq	yapmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
barmaq	bériwatisiz	V;PROG;FRML;SG;2;PRS
oxshatmaq	oxshatqan	V;PRF;PL;3;PRS
démek	démigensen	V;PRF;SG;2;NEG;INFM;PRS
kirmek	kiriwatimen	V;PROG;SG;1;PRS
körsetmek	körsettim	V;SG;1;PST
oxshatmaq	oxshitattinglar	V;IPFV;PL;2;PST
ögenmek	öginiwatimiz	V;PROG;PL;1;PRS
mangmaq	méngiwatisiz	V;PROG;FRML;SG;2;PRS
tashlimaq	tashliding	V;SG;2;INFM;PST
tashlimaq	tashlimighaniduq	V;PRF;PL;1;NEG;PST
körünmek	körünüwatattuq	V;PROG;PL;1;PST
ichmek	ichmigeniding	V;PRF;SG;2;NEG;INFM;PST
ichmek	ichtingiz	V;FRML;SG;2;PST
urushmaq	urushuwatisiz	V;PROG;FRML;SG;2;PRS
untumaq	untumighanidinglar	V;PRF;PL;2;NEG;PST
chaqirmaq	chaqirmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
étirap qilmaq	étirap qilding	V;SG;2;INFM;PST
kechürmek	kechüriwatimiz	V;PROG;PL;1;PRS
dawamlashturmaq	dawamlashturdingiz	V;FRML;SG;2;PST
kirmek	kirgenidingiz	V;PRF;FRML;SG;2;PST
sezmek	séziwatisiler	V;PROG;PL;2;PRS
tingshimaq	tingshaymiz	V;IPFV;PL;1;PRS
qilmaq	qilmaqchiduq	V;INTEN;PL;1;PST
ishenmek	ishen'migeniding	V;PRF;SG;2;NEG;INFM;PST
ewetmek	ewetmekchidim	V;INTEN;SG;1;PST
tutmaq	tumighansiler	V;PRF;PL;2;NEG;PRS
sözlimek	sözlimigenmiz	V;PRF;PL;1;NEG;PRS
heydimek	heydigeniding	V;PRF;SG;2;INFM;PST
oqumaq	oquwatattuq	V;PROG;PL;1;PST
keymek	keygen	V;PRF;SG;3;PRS
körsetmek	körsettinglar	V;PL;2;PST
ishenmek	ishinimiz	V;IPFV;PL;1;PRS
yapmaq	yapmaqchiding	V;INTEN;SG;2;INFM;PST
belgilimek	belgilimigensen	V;PRF;SG;2;NEG;INFM;PRS
ichmek	ichetti	V;IPFV;PL;3;PST
ewetmek	ewetmekchidi	V;INTEN;PL;3;PST
urushmaq	urushuwatatti	V;PROG;SG;3;PST
kirmek	kirmekchisen	V;INTEN;SG;2;INFM;PRS
yetküzmek	yetküzmekchidi	V;INTEN;PL;3;PST
yighlamaq	yighlighaniduq	V;PRF;PL;1;PST
ichmek	ichtim	V;SG;1;PST
urushmaq	urushmighanidinglar	V;PRF;PL;2;NEG;PST
mu'amile qilmaq	mu'amile qilghansen	V;PRF;SG;2;INFM;PRS
anglimaq	anglawatimiz	V;PROG;PL;1;PRS
étirap qilmaq	étirap qiliwatattingiz	V;PROG;FRML;SG;2;PST
yatmaq	yatmiding	V;SG;2;NEG;INFM;PST
tapmaq	tapmaqchidi	V;INTEN;PL;3;PST
körmek	körgen	V;PRF;SG;3;PRS
démek	dégensen	V;PRF;SG;2;INFM;PRS
sétiwalmaq	sétiwalmidinglar	V;PL;2;NEG;PST
achmaq	achmaqchidi	V;INTEN;PL;3;PST
bashlimaq	bashlighanidinglar	V;PRF;PL;2;PST
étirap qilmaq	étirap qilattuq	V;IPFV;PL;1;PST
soqmaq	soquwatisiz	V;PROG;FRML;SG;2;PRS
yémek	yémidinglar	V;PL;2;NEG;PST
tallimaq	tallaydu	V;IPFV;SG;3;PRS
oylimaq	oylimighan	V;PRF;PL;3;NEG;PRS
yetküzmek	yetküzgenidi	V;PRF;SG;3;PST
qaytmaq	qayturqan	V;PRF;PL;3;PRS
mangmaq	mangghanmen	V;PRF;SG;1;PRS
yardemleshmek	yardemleshmigen	V;PRF;SG;3;NEG;PRS
achmaq	achqanidi	V;PRF;PL;3;PST
mangmaq	mangghansiz	V;PRF;FRML;SG;2;PRS
yardemleshmek	yardemleshmigensiz	V;PRF;FRML;SG;2;NEG;PRS
soqmaq	soqattinglar	V;IPFV;PL;2;PST
bermek	birisiz	V;IPFV;FRML;SG;2;PRS
xalimaq	xalimaqchidim	V;INTEN;SG;1;PST
yatmaq	yamighan	V;PRF;SG;3;NEG;PRS
bayqimaq	bayqighanidingiz	V;PRF;FRML;SG;2;PST
chüshenmek	chüshenmekchidingiz	V;FRML;INTEN;SG;2;PST
mangmaq	mangmaqchisen	V;INTEN;SG;2;INFM;PRS
tapshuruwalmaq	tapshuruwalmiding	V;SG;2;NEG;INFM;PST
yaqturmaq	yaqturghanidi	V;PRF;SG;3;PST
anglimaq	anglayttuq	V;IPFV;PL;1;PST
anglimaq	anglaytting	V;IPFV;SG;2;INFM;PST
bildürmek	bildürüwatatting	V;PROG;SG;2;INFM;PST
yardemleshmek	yardemleshmidim	V;SG;1;NEG;PST
yardemleshmek	yardemleshmekchi	V;INTEN;PL;3;PRS
bilmek	bilettim	V;IPFV;SG;1;PST
külümsirimek	külümsireymen	V;IPFV;SG;1;PRS
untumaq	untuwatidu	V;PROG;PL;3;PRS
kirmek	kirmekchidim	V;INTEN;SG;1;PST
öltürmek	öltürisiler	V;IPFV;PL;2;PRS
körmek	körmekchisiz	V;FRML;INTEN;SG;2;PRS
yötkimek	yötkimekchisiz	V;FRML;INTEN;SG;2;PRS
bashlimaq	bashlighansiz	V;PRF;FRML;SG;2;PRS
kirmek	kiriwatisiler	V;PROG;PL;2;PRS
keymek	kéyiwatatti	V;PROG;PL;3;PST
eslimek	eslimigenmiz	V;PRF;PL;1;NEG;PRS
nepeslenmek	nepeslenettingiz	V;IPFV;FRML;SG;2;PST
barmaq	barmaqchimen	V;INTEN;SG;1;PRS
yighlamaq	yighlawatatti	V;PROG;PL;3;PST
söymek	söydi	V;SG;3;PST
ichmek	ichiwatimen	V;PROG;SG;1;PRS
bermek	bermekchidim	V;INTEN;SG;1;PST
agahlandurmaq	agahlandurisiz	V;IPFV;FRML;SG;2;PRS
ishlimek	ishlimidi	V;SG;3;NEG;PST
peseymek	pesiyisen	V;IPFV;SG;2;INFM;PRS
ögenmek	öginiwatimen	V;PROG;SG;1;PRS
körünmek	körün'migen	V;PRF;SG;3;NEG;PRS
sorimaq	sorighansen	V;PRF;SG;2;INFM;PRS
yimek	yewatidu	V;PROG;SG;3;PRS
yetküzmek	yetküzgen	V;PRF;SG;3;PRS
bilmek	biliwatisiz	V;PROG;FRML;SG;2;PRS
soqmaq	soqmidinglar	V;PL;2;NEG;PST
barmaq	bériwatattim	V;PROG;SG;1;PST
urushmaq	urushmaqchisiler	V;INTEN;PL;2;PRS
mu'amile qilmaq	mu'amile qilmaqchidi	V;INTEN;SG;3;PST
tallimaq	tallaydu	V;IPFV;SG;3;PRS
yardemleshmek	yardemlishetti	V;IPFV;PL;3;PST
körmek	körisen	V;IPFV;SG;2;INFM;PRS
yémek	yémigenmiz	V;PRF;PL;1;NEG;PRS
yémek	yémigenidim	V;PRF;SG;1;NEG;PST
keymek	kéyiwatattim	V;PROG;SG;1;PST
yapmaq	yapmighanidi	V;PRF;PL;3;NEG;PST
yémek	yewatattuq	V;PROG;PL;1;PST
saqlimaq	saqlayttuq	V;IPFV;PL;1;PST
sözlimek	sözlewatatti	V;PROG;SG;3;PST
achmaq	acmighansiler	V;PRF;PL;2;NEG;PRS
qoshulmaq	qoshulghaniduq	V;PRF;PL;1;PST
urushmaq	urushmaqchidim	V;INTEN;SG;1;PST
ölmek	ölmigenidi	V;PRF;SG;3;NEG;PST
bayqimaq	bayqaysiler	V;IPFV;PL;2;PRS
tölimek	tölewatatti	V;PROG;SG;3;PST
urushmaq	urushuwatisiler	V;PROG;PL;2;PRS
buyrumaq	buyrumighan	V;PRF;PL;3;NEG;PRS
oqumaq	oqumidingiz	V;FRML;SG;2;NEG;PST
peseymek	pesiyiwatattinglar	V;PROG;PL;2;PST
köydürmek	köydürmiduq	V;PL;1;NEG;PST
yapmaq	yapmighanidim	V;PRF;SG;1;NEG;PST
peseymek	pesiyidu	V;IPFV;PL;3;PRS
ögenmek	ögenmiding	V;SG;2;NEG;INFM;PST
achmaq	achmaqchidingiz	V;FRML;INTEN;SG;2;PST
bildürmek	bildürüwatisen	V;PROG;SG;2;INFM;PRS
oynimaq	oynawatattingiz	V;PROG;FRML;SG;2;PST
saqlimaq	saqlidim	V;SG;1;PST
tashlimaq	tashlimighan	V;PRF;SG;3;NEG;PRS
körünmek	körünmekchi	V;INTEN;PL;3;PRS
tapshuruwalmaq	tapshuruwalmaqchisiler	V;INTEN;PL;2;PRS
étirap qilmaq	étirap qiliwatimiz	V;PROG;PL;1;PRS
turmaq	turuwatatti	V;PROG;PL;3;PST
yötkimek	yötkimekchi	V;INTEN;SG;3;PRS
démek	démekchisiz	V;FRML;INTEN;SG;2;PRS
qaytmaq	qayturmighansiler	V;PRF;PL;2;NEG;PRS
tölimek	tölimigenidi	V;PRF;PL;3;NEG;PST
yötkimek	yötkigensiz	V;PRF;FRML;SG;2;PRS
peseymek	pesiyiwatatti	V;PROG;PL;3;PST
eslimek	esligensiler	V;PRF;PL;2;PRS
körünmek	körünüwatattim	V;PROG;SG;1;PST
étirap qilmaq	étirap qilidu	V;IPFV;PL;3;PRS
sözlimek	sözlewatidu	V;PROG;PL;3;PRS
sorimaq	sorimidingiz	V;FRML;SG;2;NEG;PST
ishlimek	ishligensen	V;PRF;SG;2;INFM;PRS
soqmaq	soqqanidi	V;PRF;PL;3;PST
tashlimaq	tashlawatisiz	V;PROG;FRML;SG;2;PRS
belgilimek	belgilidi	V;SG;3;PST
étirap qilmaq	étirap qildim	V;SG;1;PST
qachilimaq	qachilimighansiler	V;PRF;PL;2;NEG;PRS
qaytmaq	qayturmaqchiduq	V;INTEN;PL;1;PST
söymek	söymekchisiz	V;FRML;INTEN;SG;2;PRS
ewetmek	ewetkensen	V;PRF;SG;2;INFM;PRS
saqlimaq	saqlighansiz	V;PRF;FRML;SG;2;PRS
köydürmek	köydüriwatisen	V;PROG;SG;2;INFM;PRS
mu'amile qilmaq	mu'amile qildi	V;PL;3;PST
mangmaq	mangmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
qorqmaq	qorqimaqchisiler	V;INTEN;PL;2;PRS
oynimaq	oynidinglar	V;PL;2;PST
untumaq	untumighanidi	V;PRF;PL;3;NEG;PST
yémek	yeysiler	V;IPFV;PL;2;PRS
ishlimek	ishlidim	V;SG;1;PST
kechürmek	kechürisen	V;IPFV;SG;2;INFM;PRS
bilmek	biliwatisiler	V;PROG;PL;2;PRS
ölmek	ölgen	V;PRF;SG;3;PRS
bermek	biretti	V;IPFV;SG;3;PST
ewetmek	ewetmiduq	V;PL;1;NEG;PST
yimek	yigensen	V;PRF;SG;2;INFM;PRS
yapmaq	yapmighaniding	V;PRF;SG;2;NEG;INFM;PST
yetküzmek	yetküzgensiz	V;PRF;FRML;SG;2;PRS
kechürmek	kechürmekchisiz	V;FRML;INTEN;SG;2;PRS
dawamlashturmaq	dawamlashturmighanmiz	V;PRF;PL;1;NEG;PRS
urushmaq	urushuwatidu	V;PROG;SG;3;PRS
démek	déding	V;SG;2;INFM;PST
nepeslenmek	nepeslenidu	V;IPFV;SG;3;PRS
bolmaq	bolghantuq	V;PRF;PL;1;PST
tashlimaq	tashlawatimiz	V;PROG;PL;1;PRS
buyrumaq	buyruytti	V;IPFV;PL;3;PST
qilmaq	qiliwatidu	V;PROG;PL;3;PRS
öltürmek	öltürmekchidim	V;INTEN;SG;1;PST
qobul qilmaq	qobul qiliwatidu	V;PROG;SG;3;PRS
öltürmek	öltürdi	V;SG;3;PST
yötkimek	yötkidingiz	V;FRML;SG;2;PST
tapshuruwalmaq	tapshuruwaldinglar	V;PL;2;PST
körünmek	körün'migenidim	V;PRF;SG;1;NEG;PST
uchmaq	uchqansen	V;PRF;SG;2;INFM;PRS
ögenmek	öginettim	V;IPFV;SG;1;PST
jawab bermek	jawab berdi	V;SG;3;PST
étirap qilmaq	étirap qilmaqchisiler	V;INTEN;PL;2;PRS
bilmek	bilidu	V;IPFV;SG;3;PRS
ölmek	ölmekchidingiz	V;FRML;INTEN;SG;2;PST
qachilimaq	qachilawatisiler	V;PROG;PL;2;PRS
tapmaq	tapqanidi	V;PRF;PL;3;PST
ishenmek	ishen'migensiz	V;PRF;FRML;SG;2;NEG;PRS
söymek	söyettingiz	V;IPFV;FRML;SG;2;PST
kechürmek	kechüriwatattingiz	V;PROG;FRML;SG;2;PST
yimek	yigentuq	V;PRF;PL;1;PST
qalmaq	qéliwatattinglar	V;PROG;PL;2;PST
aghrinmaq	aghrin'ghansen	V;PRF;SG;2;INFM;PRS
söymek	söyüwatimen	V;PROG;SG;1;PRS
bayqimaq	bayqimaqchiding	V;INTEN;SG;2;INFM;PST
tingshimaq	tingshighanmiz	V;PRF;PL;1;PRS
qoymaq	qoymaqchisiz	V;FRML;INTEN;SG;2;PRS
eslimek	esleyttinglar	V;IPFV;PL;2;PST
aghrinmaq	aghrindingiz	V;FRML;SG;2;PST
untumaq	untuymen	V;IPFV;SG;1;PRS
yötkimek	yötkimigenidi	V;PRF;PL;3;NEG;PST
olturmaq	olturmiduq	V;PL;1;NEG;PST
urushmaq	urushimen	V;IPFV;SG;1;PRS
ichmek	ichmidi	V;SG;3;NEG;PST
sözlimek	sözleysiz	V;IPFV;FRML;SG;2;PRS
sezmek	sezmigenmiz	V;PRF;PL;1;NEG;PRS
nepeslenmek	nepeslen'migenmiz	V;PRF;PL;1;NEG;PRS
ishlimek	ishleyttuq	V;IPFV;PL;1;PST
tutmaq	tutmaqchidim	V;INTEN;SG;1;PST
ishlimek	ishliduq	V;PL;1;PST
buzmaq	buzmighansen	V;PRF;SG;2;NEG;INFM;PRS
körmek	kördim	V;SG;1;PST
kelmek	kelmekchidim	V;INTEN;SG;1;PST
kelmek	kéliwatattuq	V;PROG;PL;1;PST
tölimek	tölidinglar	V;PL;2;PST
oxshatmaq	oxshitiwatimiz	V;PROG;PL;1;PRS
yardemleshmek	yardemleshmigenidim	V;PRF;SG;1;NEG;PST
uchmaq	uchmaqchidinglar	V;INTEN;PL;2;PST
mangmaq	méngiwatattingiz	V;PROG;FRML;SG;2;PST
köydürmek	köydürmidi	V;SG;3;NEG;PST
bermek	bergen	V;PRF;PL;3;PRS
yaqturmaq	yaqturatti	V;IPFV;SG;3;PST
yetküzmek	yetküzmekchisen	V;INTEN;SG;2;INFM;PRS
tapmaq	tapmiduq	V;PL;1;NEG;PST
kelmek	kelmigeniduq	V;PRF;PL;1;NEG;PST
aghrimaq	aghriduq	V;PL;1;PST
ichmek	ichiwatidu	V;PROG;SG;3;PRS
oynimaq	oynimidingiz	V;FRML;SG;2;NEG;PST
qoshulmaq	qoshulghanidinglar	V;PRF;PL;2;PST
olturmaq	olturattingiz	V;IPFV;FRML;SG;2;PST
bayqimaq	bayqighansiz	V;PRF;FRML;SG;2;PRS
qoshulmaq	qoshulmaqchidi	V;INTEN;PL;3;PST
aghrinmaq	aghriniwatattim	V;PROG;SG;1;PST
köydürmek	köydüretti	V;IPFV;PL;3;PST
sezmek	sezdinglar	V;PL;2;PST
uchmaq	uchiwatattingiz	V;PROG;FRML;SG;2;PST
tutmaq	tutuwatatti	V;PROG;PL;3;PST
saqlimaq	saqlimaqchidingiz	V;FRML;INTEN;SG;2;PST
yimek	yimekchisiz	V;FRML;INTEN;SG;2;PRS
achmaq	achqanidim	V;PRF;SG;1;PST
tapshuruwalmaq	tapshuruwalimen	V;IPFV;SG;1;PRS
xalimaq	xalimighan	V;PRF;SG;3;NEG;PRS
naxsha éytmaq	naxsha éytmaqchisen	V;INTEN;SG;2;INFM;PRS
bermek	biriwatimiz	V;PROG;PL;1;PRS
yatmaq	yatti	V;PL;3;PST
kirmek	kiridu	V;IPFV;PL;3;PRS
yazmaq	yazghanidi	V;PRF;PL;3;PST
buzmaq	buziwatisiler	V;PROG;PL;2;PRS
chaqirmaq	chaqirmighansen	V;PRF;SG;2;NEG;INFM;PRS
yazmaq	yéziwatisiler	V;PROG;PL;2;PRS
dawamlashturmaq	dawamlashturatti	V;IPFV;PL;3;PST
chiqmaq	chiqiwatatting	V;PROG;SG;2;INFM;PST
yémek	yémekchi	V;INTEN;PL;3;PRS
oynimaq	oynighanmen	V;PRF;SG;1;PRS
körsetmek	körsitetting	V;IPFV;SG;2;INFM;PST
tashlimaq	tashlawatidu	V;PROG;SG;3;PRS
öltürmek	öltürmigenidi	V;PRF;PL;3;NEG;PST
sözlimek	sözlimekchisiz	V;FRML;INTEN;SG;2;PRS
chiqmaq	chiqmidi	V;SG;3;NEG;PST
oqumaq	oqughansiler	V;PRF;PL;2;PRS
tapshuruwalmaq	tapshuruwalduq	V;PL;1;PST
bildürmek	bildüridu	V;IPFV;SG;3;PRS
mu'amile qilmaq	mu'amile qilghanidi	V;PRF;PL;3;PST
bilmek	bilmigenidim	V;PRF;SG;1;NEG;PST
ichmek	ichiwatimiz	V;PROG;PL;1;PRS
aghrimaq	aghriwatimiz	V;PROG;PL;1;PRS
yötkimek	yötkimigenidinglar	V;PRF;PL;2;NEG;PST
öltürmek	öltürmekchisen	V;INTEN;SG;2;INFM;PRS
tapmaq	tapmidi	V;SG;3;NEG;PST
aghrimaq	aghriysen	V;IPFV;SG;2;INFM;PRS
körmek	körgenidinglar	V;PRF;PL;2;PST
tingshimaq	tingshawatisiler	V;PROG;PL;2;PRS
étirap qilmaq	étirap qilmighaniding	V;PRF;SG;2;NEG;INFM;PST
sezmek	sezmekchi	V;INTEN;SG;3;PRS
bashlimaq	bashlaysiler	V;IPFV;PL;2;PRS
oxshatmaq	oxhatmighanidi	V;PRF;PL;3;NEG;PST
chüshenmek	chüshen'migensen	V;PRF;SG;2;NEG;INFM;PRS
söymek	söyetti	V;IPFV;PL;3;PST
urushmaq	urushmidingiz	V;FRML;SG;2;NEG;PST
söymek	söyisen	V;IPFV;SG;2;INFM;PRS
almaq	aldim	V;SG;1;PST
uchmaq	uchmiding	V;SG;2;NEG;INFM;PST
körünmek	körün'genidingiz	V;PRF;FRML;SG;2;PST
sözlimek	sözlimigeniduq	V;PRF;PL;1;NEG;PST
naxsha éytmaq	naxsha éyttinglar	V;PL;2;PST
kirmek	kirmekchiding	V;INTEN;SG;2;INFM;PST
agahlandurmaq	agahlandurduq	V;PL;1;PST
oylimaq	oylawatatti	V;PROG;SG;3;PST
öltürmek	öltürmiduq	V;PL;1;NEG;PST
ewetmek	ewetiwatisiz	V;PROG;FRML;SG;2;PRS
belgilimek	belgiligensiz	V;PRF;FRML;SG;2;PRS
heydimek	heydimigenidingiz	V;PRF;FRML;SG;2;NEG;PST
ishenmek	ishiniwatimiz	V;PROG;PL;1;PRS
buyrumaq	buyrumiding	V;SG;2;NEG;INFM;PST
yapmaq	yamighansiler	V;PRF;PL;2;NEG;PRS
untumaq	untumidi	V;PL;3;NEG;PST
jawab bermek	jawab bergen	V;PRF;SG;3;PRS
sétiwalmaq	sétiwaldingiz	V;FRML;SG;2;PST
yémek	yémigeniduq	V;PRF;PL;1;NEG;PST
oynimaq	oynimaqchimen	V;INTEN;SG;1;PRS
qorqmaq	qorqighanduq	V;PRF;PL;1;PST
tapmaq	tépiwatatting	V;PROG;SG;2;INFM;PST
heydimek	heydimekchidinglar	V;INTEN;PL;2;PST
almaq	alatti	V;IPFV;PL;3;PST
barmaq	barmidingiz	V;FRML;SG;2;NEG;PST
yémek	yémekchidinglar	V;INTEN;PL;2;PST
heydimek	heydeysiler	V;IPFV;PL;2;PRS
yimek	yeysiz	V;IPFV;FRML;SG;2;PRS
qoshulmaq	qoshulmaqchiding	V;INTEN;SG;2;INFM;PST
almaq	aldingiz	V;FRML;SG;2;PST
ishlimek	ishliding	V;SG;2;INFM;PST
epsuslanmaq	epsuslan'ghan	V;PRF;SG;3;PRS
xalimaq	xalimaqchi	V;INTEN;PL;3;PRS
kechürmek	kechürdim	V;SG;1;PST
buyrumaq	buyrughanidinglar	V;PRF;PL;2;PST
agahlandurmaq	agahlandurghanidi	V;PRF;PL;3;PST
untumaq	untughansiz	V;PRF;FRML;SG;2;PRS
agahlandurmaq	agahlandurmighansiler	V;PRF;PL;2;NEG;PRS
eslimek	eslimekchidingiz	V;FRML;INTEN;SG;2;PST
belgilimek	belgilimigenidingiz	V;PRF;FRML;SG;2;NEG;PST
sözlimek	sözlewatattim	V;PROG;SG;1;PST
tutmaq	tuttim	V;SG;1;PST
külümsirimek	külümsirewatatti	V;PROG;PL;3;PST
soqmaq	soqmighansiler	V;PRF;PL;2;NEG;PRS
kirmek	kirmiding	V;SG;2;NEG;INFM;PST
heydimek	heydimidi	V;SG;3;NEG;PST
kelmek	kélettingiz	V;IPFV;FRML;SG;2;PST
yatmaq	yatqaniding	V;PRF;SG;2;INFM;PST
sezmek	sezdi	V;PL;3;PST
ewetmek	ewetmigenidi	V;PRF;PL;3;NEG;PST
sezmek	sezgensiz	V;PRF;FRML;SG;2;PRS
mu'amile qilmaq	mu'amile qilisiler	V;IPFV;PL;2;PRS
yighlamaq	yighlighanidi	V;PRF;SG;3;PST
xalimaq	xalawatimiz	V;PROG;PL;1;PRS
oylimaq	oylaymen	V;IPFV;SG;1;PRS
étirap qilmaq	étirap qilmighanmen	V;PRF;SG;1;NEG;PRS
bilmek	bilgensiler	V;PRF;PL;2;PRS
yapmaq	yapmaqchisen	V;INTEN;SG;2;INFM;PRS
chiqmaq	chiqtingiz	V;FRML;SG;2;PST
kirmek	kirmekchimen	V;INTEN;SG;1;PRS
yighlamaq	yighlimaqchisiler	V;INTEN;PL;2;PRS
yetküzmek	yetküzdinglar	V;PL;2;PST
yapmaq	yaptim	V;SG;1;PST
urushmaq	urushqansiler	V;PRF;PL;2;PRS
aghrimaq	aghrimaqchisiz	V;FRML;INTEN;SG;2;PRS
oxshatmaq	oxshitimiz	V;IPFV;PL;1;PRS
ölmek	ölduq	V;PL;1;PST
aghrinmaq	aghrinmiduq	V;PL;1;NEG;PST
naxsha éytmaq	naxsha éytqanidinglar	V;PRF;PL;2;PST
tapmaq	tapmighaniduq	V;PRF;PL;1;NEG;PST
urushmaq	urushqansiz	V;PRF;FRML;SG;2;PRS
uchmaq	uchmaqchiding	V;INTEN;SG;2;INFM;PST
tingshimaq	tingshayttingiz	V;IPFV;FRML;SG;2;PST
chüshenmek	chüshen'gen	V;PRF;PL;3;PRS
yimek	yimekchi	V;INTEN;SG;3;PRS
qalmaq	qalmaqchidi	V;INTEN;SG;3;PST
chüshmek	chüshüwatattim	V;PROG;SG;1;PST
sezmek	sezmigeniding	V;PRF;SG;2;NEG;INFM;PST
nepeslenmek	nepeslendim	V;SG;1;PST
barmaq	barmaqchimiz	V;INTEN;PL;1;PRS
ölmek	öldi	V;SG;3;PST
ewetmek	ewetmigenmen	V;PRF;SG;1;NEG;PRS
tölimek	tölimigenidi	V;PRF;SG;3;NEG;PST
oqumaq	oqughan	V;PRF;SG;3;PRS
qorqmaq	qorqiwatattim	V;PROG;SG;1;PST
naxsha éytmaq	naxsha éytmighanmiz	V;PRF;PL;1;NEG;PRS
aghrinmaq	aghrin'ghanidingiz	V;PRF;FRML;SG;2;PST
soqmaq	soqqanidinglar	V;PRF;PL;2;PST
aghrinmaq	aghrin'mighanmiz	V;PRF;PL;1;NEG;PRS
qoshulmaq	qoshulmaqchimiz	V;INTEN;PL;1;PRS
oxshatmaq	oxshatmighansiler	V;PRF;PL;2;NEG;PRS
körsetmek	körsetkensen	V;PRF;SG;2;INFM;PRS
bermek	bermigensiler	V;PRF;PL;2;NEG;PRS
bermek	bermidim	V;SG;1;NEG;PST
almaq	alghansiz	V;PRF;FRML;SG;2;PRS
epsuslanmaq	epsuslanmaqchi	V;INTEN;PL;3;PRS
jawab bermek	jawab béridu	V;IPFV;SG;3;PRS
olturmaq	olturdinglar	V;PL;2;PST
peseymek	peseymidi	V;PL;3;NEG;PST
dawamlashturmaq	dawamlashturdi	V;SG;3;PST
qoshulmaq	qoshulghansen	V;PRF;SG;2;INFM;PRS
tutmaq	tutimiz	V;IPFV;PL;1;PRS
tapshuruwalmaq	tapshuruwaldi	V;PL;3;PST
eslimek	eslimigenidim	V;PRF;SG;1;NEG;PST
tölimek	töligenidinglar	V;PRF;PL;2;PST
söymek	söymekchiding	V;INTEN;SG;2;INFM;PST
yaqturmaq	yaqturmighanidi	V;PRF;SG;3;NEG;PST
xalimaq	xalayttuq	V;IPFV;PL;1;PST
mu'amile qilmaq	mu'amile qilghanmiz	V;PRF;PL;1;PRS
bayqimaq	bayqawatisiz	V;PROG;FRML;SG;2;PRS
buyrumaq	buyrughanidim	V;PRF;SG;1;PST
achmaq	achmaqchidinglar	V;INTEN;PL;2;PST
heydimek	heydidinglar	V;PL;2;PST
nepeslenmek	nepeslen'gensiz	V;PRF;FRML;SG;2;PRS
yimek	yimigenidingiz	V;PRF;FRML;SG;2;NEG;PST
mangmaq	mangattim	V;IPFV;SG;1;PST
körsetmek	körsetmekchidingiz	V;FRML;INTEN;SG;2;PST
agahlandurmaq	agahlanruwatisiz	V;PROG;FRML;SG;2;PRS
yetküzmek	yetküzmekchimiz	V;INTEN;PL;1;PRS
qaytmaq	qayturimen	V;IPFV;SG;1;PRS
bermek	birettinglar	V;IPFV;PL;2;PST
sorimaq	soraytting	V;IPFV;SG;2;INFM;PST
yimek	yewatatti	V;PROG;SG;3;PST
aghrinmaq	aghrindim	V;SG;1;PST
ishlimek	ishleymiz	V;IPFV;PL;1;PRS
oqumaq	oqughanmen	V;PRF;SG;1;PRS
qoymaq	qoyuwatimen	V;PROG;SG;1;PRS
ishlimek	ishlimekchidingiz	V;FRML;INTEN;SG;2;PST
qoshulmaq	qoshulghan	V;PRF;SG;3;PRS
chüshenmek	chüshenmekchidim	V;INTEN;SG;1;PST
achmaq	acmighan	V;PRF;PL;3;NEG;PRS
aghrimaq	aghrighanidim	V;PRF;SG;1;PST
bashlimaq	bashlimaqchidinglar	V;INTEN;PL;2;PST
öltürmek	öltürgenidi	V;PRF;PL;3;PST
qoymaq	qoymighansiz	V;PRF;FRML;SG;2;NEG;PRS
chüshenmek	chüshen'genidi	V;PRF;PL;3;PST
tölimek	töligenidim	V;PRF;SG;1;PST
oxshatmaq	oxshitisiler	V;IPFV;PL;2;PRS
untumaq	untughanidim	V;PRF;SG;1;PST
tingshimaq	tingshidim	V;SG;1;PST
qaytmaq	qayturmaqchidinglar	V;INTEN;PL;2;PST
sezmek	sézidu	V;IPFV;SG;3;PRS
külümsirimek	külümsirigeniduq	V;PRF;PL;1;PST
kirmek	kirimen	V;IPFV;SG;1;PRS
qorqmaq	qorqmighanidi	V;PRF;SG;3;NEG;PST
yémek	yégen	V;PRF;SG;3;PRS
barmaq	barmaqchidim	V;INTEN;SG;1;PST
untumaq	untumaqchisiler	V;INTEN;PL;2;PRS
tölimek	tölewatidu	V;PROG;PL;3;PRS
dawamlashturmaq	dawamlashturmaqchidinglar	V;INTEN;PL;2;PST
tapmaq	tapmaqchimiz	V;INTEN;PL;1;PRS
chüshenmek	chüshinettingiz	V;IPFV;FRML;SG;2;PST
qobul qilmaq	qobul qilmighanidi	V;PRF;SG;3;NEG;PST
köydürmek	köydürmigenidingiz	V;PRF;FRML;SG;2;NEG;PST
oxshatmaq	oxshatmidingiz	V;FRML;SG;2;NEG;PST
yötkimek	yötkeytti	V;IPFV;PL;3;PST
qachilimaq	qachilimighanidinglar	V;PRF;PL;2;NEG;PST
tölimek	tölimigenmen	V;PRF;SG;1;NEG;PRS
mu'amile qilmaq	mu'amile qilding	V;SG;2;INFM;PST
agahlandurmaq	agahlandurattinglar	V;IPFV;PL;2;PST
chaqirmaq	chaqirisiz	V;IPFV;FRML;SG;2;PRS
sezmek	sézisiz	V;IPFV;FRML;SG;2;PRS
oqumaq	oqudinglar	V;PL;2;PST
kechürmek	kechürisiler	V;IPFV;PL;2;PRS
nepeslenmek	nepeslen'migensen	V;PRF;SG;2;NEG;INFM;PRS
ichmek	ichmigenidinglar	V;PRF;PL;2;NEG;PST
ögenmek	öginiwatattim	V;PROG;SG;1;PST
tingshimaq	tingshighanidinglar	V;PRF;PL;2;PST
peseymek	pesiyiwatattim	V;PROG;SG;1;PST
bilmek	bilmekchisiler	V;INTEN;PL;2;PRS
yetküzmek	yetküzdi	V;SG;3;PST
sözlimek	sözlewatattingiz	V;PROG;FRML;SG;2;PST
sétiwalmaq	sétiwalmaqchisiz	V;FRML;INTEN;SG;2;PRS
saqlimaq	saqlawatidu	V;PROG;SG;3;PRS
buyrumaq	buyrughanidi	V;PRF;PL;3;PST
uchmaq	uchiwatidu	V;PROG;PL;3;PRS
nepeslenmek	nepeslenmekchidinglar	V;INTEN;PL;2;PST
naxsha éytmaq	naxsha éytiwatattuq	V;PROG;PL;1;PST
qilmaq	qilghanmiz	V;PRF;PL;1;PRS
untumaq	untudim	V;SG;1;PST
keymek	keymiduq	V;PL;1;NEG;PST
démek	deytti	V;IPFV;SG;3;PST
chüshmek	chüshmigenmiz	V;PRF;PL;1;NEG;PRS
qoshulmaq	qoshulmighansiler	V;PRF;PL;2;NEG;PRS
öltürmek	öltürgenidi	V;PRF;SG;3;PST
sezmek	sézettim	V;IPFV;SG;1;PST
yighlamaq	yighlimidinglar	V;PL;2;NEG;PST
belgilimek	belgilewatattim	V;PROG;SG;1;PST
bilmek	bilgen	V;PRF;SG;3;PRS
peseymek	pesiyiwatattuq	V;PROG;PL;1;PST
bolmaq	bolmighanidim	V;PRF;SG;1;NEG;PST
urushmaq	urushtim	V;SG;1;PST
yatmaq	yatmidingiz	V;FRML;SG;2;NEG;PST
nepeslenmek	nepesleniwatattinglar	V;PROG;PL;2;PST
buyrumaq	buyrumaqchidi	V;INTEN;PL;3;PST
yimek	yimigen	V;PRF;PL;3;NEG;PRS
saqlimaq	saqlighan	V;PRF;SG;3;PRS
yetküzmek	yetküzgenidi	V;PRF;PL;3;PST
körünmek	körün'genidim	V;PRF;SG;1;PST
turmaq	turghanidim	V;PRF;SG;1;PST
tölimek	töleytti	V;IPFV;SG;3;PST
bermek	bermekchiduq	V;INTEN;PL;1;PST
aghrinmaq	aghrin'mighanidi	V;PRF;SG;3;NEG;PST
bildürmek	bildürgenidi	V;PRF;SG;3;PST
achmaq	échiwatatti	V;PROG;SG;3;PST
untumaq	untuding	V;SG;2;INFM;PST
öltürmek	öltürmekchiding	V;INTEN;SG;2;INFM;PST
sétiwalmaq	sétiwalmaqchidim	V;INTEN;SG;1;PST
étirap qilmaq	étirap qilmighanidi	V;PRF;PL;3;NEG;PST
oxshatmaq	oxhatmighanidim	V;PRF;SG;1;NEG;PST
ichmek	ichken	V;PRF;PL;3;PRS
ögenmek	ögen'genidinglar	V;PRF;PL;2;PST
sorimaq	soridingiz	V;FRML;SG;2;PST
achmaq	achmaqchi	V;INTEN;SG;3;PRS
qoshulmaq	qoshulmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
ewetmek	ewetmidi	V;PL;3;NEG;PST
tashlimaq	tashlawatattingiz	V;PROG;FRML;SG;2;PST
yimek	yewatisiz	V;PROG;FRML;SG;2;PRS
ichmek	ichmiduq	V;PL;1;NEG;PST
qalmaq	qalmidim	V;SG;1;NEG;PST
qobul qilmaq	qobul qilatti	V;IPFV;PL;3;PST
olturmaq	olturatting	V;IPFV;SG;2;INFM;PST
tölimek	tölimidingiz	V;FRML;SG;2;NEG;PST
tutmaq	tutqansen	V;PRF;SG;2;INFM;PRS
ewetmek	ewetting	V;SG;2;INFM;PST
ögenmek	öginidu	V;IPFV;SG;3;PRS
uchmaq	uchmidinglar	V;PL;2;NEG;PST
uchmaq	uchmaqchisiler	V;INTEN;PL;2;PRS
heydimek	heydewatatti	V;PROG;PL;3;PST
mu'amile qilmaq	mu'amile qilidu	V;IPFV;SG;3;PRS
qalmaq	qalisen	V;IPFV;SG;2;INFM;PRS
démek	dewatimiz	V;PROG;PL;1;PRS
sétiwalmaq	sétiwéliwatattingiz	V;PROG;FRML;SG;2;PST
olturmaq	olturuwatattingiz	V;PROG;FRML;SG;2;PST
qalmaq	qaldi	V;PL;3;PST
aghrimaq	aghrighansen	V;PRF;SG;2;INFM;PRS
qoshulmaq	qoshuldim	V;SG;1;PST
agahlandurmaq	agahlandurmaqchisen	V;INTEN;SG;2;INFM;PRS
yardemleshmek	yardemlishiwatimen	V;PROG;SG;1;PRS
kechürmek	kechürmekchidinglar	V;INTEN;PL;2;PST
qobul qilmaq	qobul qilisiler	V;IPFV;PL;2;PRS
körmek	körmekchimen	V;INTEN;SG;1;PRS
xalimaq	xalawatatting	V;PROG;SG;2;INFM;PST
chüshmek	chüshmekchisiler	V;INTEN;PL;2;PRS
ölmek	öldingiz	V;FRML;SG;2;PST
saqlimaq	saqlawatimiz	V;PROG;PL;1;PRS
uchmaq	uchqansiz	V;PRF;FRML;SG;2;PRS
nepeslenmek	nepeslen'genidi	V;PRF;PL;3;PST
tashlimaq	tashlighantingiz	V;PRF;FRML;SG;2;PST
eslimek	eslimekchisiz	V;FRML;INTEN;SG;2;PRS
jawab bermek	jawab bergeniding	V;PRF;SG;2;INFM;PST
köydürmek	köydürgenmiz	V;PRF;PL;1;PRS
dawamlashturmaq	dawamlashturmaqchiduq	V;INTEN;PL;1;PST
kechürmek	kechürgenidingiz	V;PRF;FRML;SG;2;PST
yapmaq	yépiwatisiler	V;PROG;PL;2;PRS
ichmek	ichkenidinglar	V;PRF;PL;2;PST
chiqmaq	chiqqanidi	V;PRF;SG;3;PST
bilmek	bilgeniding	V;PRF;SG;2;INFM;PST
epsuslanmaq	epsuslinattuq	V;IPFV;PL;1;PST
yighlamaq	yighlidingiz	V;FRML;SG;2;PST
aghrinmaq	aghriniwatattuq	V;PROG;PL;1;PST
turmaq	turmidinglar	V;PL;2;NEG;PST
aghrimaq	aghriyttuq	V;IPFV;PL;1;PST
qorqmaq	qorqighanmiz	V;PRF;PL;1;PRS
soqmaq	soqqansen	V;PRF;SG;2;INFM;PRS
chüshenmek	chüshiniwatimen	V;PROG;SG;1;PRS
öltürmek	öltüriwatimen	V;PROG;SG;1;PRS
yatmaq	yatqanidim	V;PRF;SG;1;PST
körmek	körüwatisen	V;PROG;SG;2;INFM;PRS
oxshatmaq	oxshatqaniding	V;PRF;SG;2;INFM;PST
öltürmek	öltürisen	V;IPFV;SG;2;INFM;PRS
turmaq	turiwatattuq	V;PROG;PL;1;PST
barmaq	barmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
qalmaq	qalghanmen	V;PRF;SG;1;PRS
sezmek	sezgeniduq	V;PRF;PL;1;PST
sorimaq	sorawatattuq	V;PROG;PL;1;PST
agahlandurmaq	agahlandurghansen	V;PRF;SG;2;INFM;PRS
chüshenmek	chüshen'genidingiz	V;PRF;FRML;SG;2;PST
yighlamaq	yighlawatisiz	V;PROG;FRML;SG;2;PRS
sözlimek	sözligensiz	V;PRF;FRML;SG;2;PRS
ewetmek	ewetkenidim	V;PRF;SG;1;PST
bilmek	biletti	V;IPFV;PL;3;PST
qorqmaq	qorqimighan	V;PRF;SG;3;NEG;PRS
mangmaq	mangmaqchi	V;INTEN;SG;3;PRS
tapmaq	tapattinglar	V;IPFV;PL;2;PST
bildürmek	bildürgenidingiz	V;PRF;FRML;SG;2;PST
achmaq	achattuq	V;IPFV;PL;1;PST
jawab bermek	jawab bermigenidinglar	V;PRF;PL;2;NEG;PST
yazmaq	yazghanmen	V;PRF;SG;1;PRS
tölimek	tölimekchisiz	V;FRML;INTEN;SG;2;PRS
aghrinmaq	aghrin'ghaniding	V;PRF;SG;2;INFM;PST
körsetmek	körsetmigeniding	V;PRF;SG;2;NEG;INFM;PST
qaytmaq	qayturmidingiz	V;FRML;SG;2;NEG;PST
qoshulmaq	qoshulattinglar	V;IPFV;PL;2;PST
naxsha éytmaq	naxsha éytattim	V;IPFV;SG;1;PST
yighlamaq	yighlimaqchi	V;INTEN;SG;3;PRS
kelmek	kelmiduq	V;PL;1;NEG;PST
ishlimek	ishligen	V;PRF;SG;3;PRS
qoymaq	qoyatting	V;IPFV;SG;2;INFM;PST
urushmaq	urushattim	V;IPFV;SG;1;PST
ewetmek	ewetkeniduq	V;PRF;PL;1;PST
ichmek	ichmigensen	V;PRF;SG;2;NEG;INFM;PRS
kirmek	kirettingiz	V;IPFV;FRML;SG;2;PST
chaqirmaq	chaqiriwatatti	V;PROG;PL;3;PST
tashlimaq	tashlighantinglar	V;PRF;PL;2;PST
keymek	kéyettim	V;IPFV;SG;1;PST
untumaq	untudinglar	V;PL;2;PST
anglimaq	anglidi	V;PL;3;PST
anglimaq	anglimighanidi	V;PRF;PL;3;NEG;PST
peseymek	pesiyimen	V;IPFV;SG;1;PRS
chaqirmaq	chaqirmighansiz	V;PRF;FRML;SG;2;NEG;PRS
aghrinmaq	aghrin'ghanmiz	V;PRF;PL;1;PRS
aghrimaq	aghriwatattingiz	V;PROG;FRML;SG;2;PST
oylimaq	oylimighanidim	V;PRF;SG;1;NEG;PST
agahlandurmaq	agahlandurghansiz	V;PRF;FRML;SG;2;PRS
bilmek	bilisiz	V;IPFV;FRML;SG;2;PRS
qoshulmaq	qoshuldi	V;PL;3;PST
nepeslenmek	nepeslenmiduq	V;PL;1;NEG;PST
ichmek	ichmigenmen	V;PRF;SG;1;NEG;PRS
yatmaq	yatqanidi	V;PRF;SG;3;PST
qalmaq	qalding	V;SG;2;INFM;PST
chüshmek	chüshgenmiz	V;PRF;PL;1;PRS
qachilimaq	qachilawatattinglar	V;PROG;PL;2;PST
qorqmaq	qorqimaqchisiz	V;FRML;INTEN;SG;2;PRS
kirmek	kiriwatimiz	V;PROG;PL;1;PRS
heydimek	heydimekchisiz	V;FRML;INTEN;SG;2;PRS
uchmaq	uchqaniding	V;PRF;SG;2;INFM;PST
qorqmaq	qorqimighansiler	V;PRF;PL;2;NEG;PRS
aghrinmaq	aghrindi	V;PL;3;PST
almaq	éliwatisen	V;PROG;SG;2;INFM;PRS
jawab bermek	jawab berdingiz	V;FRML;SG;2;PST
sezmek	sezgenmen	V;PRF;SG;1;PRS
yazmaq	yazatti	V;IPFV;PL;3;PST
qilmaq	qiliwatimen	V;PROG;SG;1;PRS
oqumaq	oquysiz	V;IPFV;FRML;SG;2;PRS
chüshmek	chüshmekchisiz	V;FRML;INTEN;SG;2;PRS
étirap qilmaq	étirap qilatti	V;IPFV;PL;3;PST
köydürmek	köydüretti	V;IPFV;SG;3;PST
tutmaq	tutuwatisiler	V;PROG;PL;2;PRS
külümsirimek	külümsirigeniding	V;PRF;SG;2;INFM;PST
qachilimaq	qachilimighaniduq	V;PRF;PL;1;NEG;PST
peseymek	peseymigenmiz	V;PRF;PL;1;NEG;PRS
chaqirmaq	chaqirghanidinglar	V;PRF;PL;2;PST
agahlandurmaq	agahlanduruwatatti	V;PROG;PL;3;PST
körsetmek	körsetmidi	V;SG;3;NEG;PST
ishenmek	ishenmiduq	V;PL;1;NEG;PST
naxsha éytmaq	naxsha éytmiding	V;SG;2;NEG;INFM;PST
yaqturmaq	yaqturuwatidu	V;PROG;PL;3;PRS
tingshimaq	tingshaydu	V;IPFV;SG;3;PRS
oylimaq	oylighansiz	V;PRF;FRML;SG;2;PRS
öltürmek	öltüridu	V;IPFV;PL;3;PRS
ichmek	ichmekchisiler	V;INTEN;PL;2;PRS
saqlimaq	saqlimighansen	V;PRF;SG;2;NEG;INFM;PRS
söymek	söyimen	V;IPFV;SG;1;PRS
yapmaq	yépiwatidu	V;PROG;PL;3;PRS
buzmaq	buzuwatisiz	V;PROG;FRML;SG;2;PRS
qilmaq	qilghaniding	V;PRF;SG;2;INFM;PST
ölmek	ölmigen	V;PRF;PL;3;NEG;PRS
sezmek	sezding	V;SG;2;INFM;PST
sezmek	sezmekchi	V;INTEN;PL;3;PRS
sétiwalmaq	sétiwalmaqchidinglar	V;INTEN;PL;2;PST
barmaq	barmighaniduq	V;PRF;PL;1;NEG;PST
mangmaq	méngiwatisen	V;PROG;SG;2;INFM;PRS
urushmaq	urushmidim	V;SG;1;NEG;PST
kechürmek	kechürettingiz	V;IPFV;FRML;SG;2;PST
bermek	biriwatimen	V;PROG;SG;1;PRS
aghrimaq	aghrimidim	V;SG;1;NEG;PST
öltürmek	öltürettingiz	V;IPFV;FRML;SG;2;PST
ewetmek	ewetisiler	V;IPFV;PL;2;PRS
ögenmek	öginimiz	V;IPFV;PL;1;PRS
söymek	söymidi	V;PL;3;NEG;PST
yighlamaq	yighlaymiz	V;IPFV;PL;1;PRS
epsuslanmaq	epsuslandingiz	V;FRML;SG;2;PST
oylimaq	oylawatisiz	V;PROG;FRML;SG;2;PRS
chiqmaq	chiqmaqchisiler	V;INTEN;PL;2;PRS
qalmaq	qalghan	V;PRF;PL;3;PRS
mu'amile qilmaq	mu'amile qilmaqchisiler	V;INTEN;PL;2;PRS
chüshenmek	chüshinettuq	V;IPFV;PL;1;PST
chaqirmaq	chaqirmaqchimen	V;INTEN;SG;1;PRS
yapmaq	yapqaniding	V;PRF;SG;2;INFM;PST
qobul qilmaq	qobul qilmaqchidinglar	V;INTEN;PL;2;PST
qalmaq	qéliwatisen	V;PROG;SG;2;INFM;PRS
ishenmek	ishinetting	V;IPFV;SG;2;INFM;PST
qoymaq	qoymidi	V;SG;3;NEG;PST
belgilimek	belgilewatidu	V;PROG;PL;3;PRS
peseymek	peseymigenidinglar	V;PRF;PL;2;NEG;PST
bermek	biretting	V;IPFV;SG;2;INFM;PST
tapmaq	tapqanidi	V;PRF;SG;3;PST
mu'amile qilmaq	mu'amile qilmighaniding	V;PRF;SG;2;NEG;INFM;PST
qoymaq	qoymaqchimen	V;INTEN;SG;1;PRS
qachilimaq	qachilimaqchi	V;INTEN;PL;3;PRS
qoymaq	qoydi	V;PL;3;PST
epsuslanmaq	epsusliniwatattingiz	V;PROG;FRML;SG;2;PST
chüshmek	chüshüwatattinglar	V;PROG;PL;2;PST
qoshulmaq	qoshuliwatisen	V;PROG;SG;2;INFM;PRS
yötkimek	yötkimiduq	V;PL;1;NEG;PST
soqmaq	soqattuq	V;IPFV;PL;1;PST
bermek	biriwatatting	V;PROG;SG;2;INFM;PST
chiqmaq	chiqisiler	V;IPFV;PL;2;PRS
yighlamaq	yighlawatimiz	V;PROG;PL;1;PRS
nepeslenmek	nepeslenmekchiding	V;INTEN;SG;2;INFM;PST
oxshatmaq	oxshattingiz	V;FRML;SG;2;PST
yaqturmaq	yaqturmighan	V;PRF;SG;3;NEG;PRS
eslimek	eslidim	V;SG;1;PST
nepeslenmek	nepeslen'migensiler	V;PRF;PL;2;NEG;PRS
epsuslanmaq	epsuslanmidingiz	V;FRML;SG;2;NEG;PST
ölmek	ölmidingiz	V;FRML;SG;2;NEG;PST
kirmek	kirgensiz	V;PRF;FRML;SG;2;PRS
ewetmek	ewetiwatatti	V;PROG;SG;3;PST
tutmaq	tutmidingiz	V;FRML;SG;2;NEG;PST
tapshuruwalmaq	tapshuruwalghansen	V;PRF;SG;2;INFM;PRS
yighlamaq	yighlayttim	V;IPFV;SG;1;PST
yazmaq	yéziwatimen	V;PROG;SG;1;PRS
buyrumaq	buyruytting	V;IPFV;SG;2;INFM;PST
aghrinmaq	aghrinmaqchiduq	V;INTEN;PL;1;PST
sétiwalmaq	sétiwéliwatattinglar	V;PROG;PL;2;PST
kirmek	kirmidi	V;PL;3;NEG;PST
barmaq	barghanidi	V;PRF;PL;3;PST
körmek	körmekchidingiz	V;FRML;INTEN;SG;2;PST
keymek	keydinglar	V;PL;2;PST
sétiwalmaq	sétiwéliwatidu	V;PROG;PL;3;PRS
bayqimaq	bayqimaqchidingiz	V;FRML;INTEN;SG;2;PST
yetküzmek	yetküzmekchiding	V;INTEN;SG;2;INFM;PST
bermek	biriwatattinglar	V;PROG;PL;2;PST
körünmek	köründim	V;SG;1;PST
yetküzmek	yetküzmekchidi	V;INTEN;SG;3;PST
söymek	söymekchi	V;INTEN;PL;3;PRS
almaq	éliwatattinglar	V;PROG;PL;2;PST
qoshulmaq	qoshulmighanidi	V;PRF;SG;3;NEG;PST
körünmek	körünmidingiz	V;FRML;SG;2;NEG;PST
barmaq	barmidinglar	V;PL;2;NEG;PST
tutmaq	tutqaniduq	V;PRF;PL;1;PST
yaqturmaq	yaqturmidingiz	V;FRML;SG;2;NEG;PST
qorqmaq	qorqaymiz	V;IPFV;PL;1;PRS
ichmek	ichettuq	V;IPFV;PL;1;PST
chüshmek	chüshidu	V;IPFV;SG;3;PRS
tapshuruwalmaq	tapshuruwaldingiz	V;FRML;SG;2;PST
étirap qilmaq	étirap qilghanidi	V;PRF;SG;3;PST
qoymaq	qoyimen	V;IPFV;SG;1;PRS
qaytmaq	qayturattuq	V;IPFV;PL;1;PST
buyrumaq	buyruwatidu	V;PROG;SG;3;PRS
naxsha éytmaq	naxsha éytidu	V;IPFV;SG;3;PRS
yötkimek	yötkigenidim	V;PRF;SG;1;PST
ishlimek	ishlimekchidi	V;INTEN;SG;3;PST
aghrinmaq	aghrin'ghanmen	V;PRF;SG;1;PRS
aghrimaq	aghrimighanidim	V;PRF;SG;1;NEG;PST
ewetmek	ewetmekchisen	V;INTEN;SG;2;INFM;PRS
körsetmek	körsetkensiz	V;PRF;FRML;SG;2;PRS
ewetmek	ewetmigeniding	V;PRF;SG;2;NEG;INFM;PST
yaqturmaq	yaqturghansen	V;PRF;SG;2;INFM;PRS
tingshimaq	tingshayttim	V;IPFV;SG;1;PST
bayqimaq	bayqimaqchi	V;INTEN;PL;3;PRS
heydimek	heydewatisen	V;PROG;SG;2;INFM;PRS
körsetmek	körsetmekchisiler	V;INTEN;PL;2;PRS
yatmaq	yétiwatisiz	V;PROG;FRML;SG;2;PRS
kechürmek	kechürgensen	V;PRF;SG;2;INFM;PRS
urushmaq	urushqansen	V;PRF;SG;2;INFM;PRS
qilmaq	qiliwatatti	V;PROG;SG;3;PST
sorimaq	sorimidinglar	V;PL;2;NEG;PST
bildürmek	bildürüwatidu	V;PROG;PL;3;PRS
qachilimaq	qachilimighan	V;PRF;PL;3;NEG;PRS
achmaq	achatti	V;IPFV;SG;3;PST
bolmaq	bolmighanidim	V;PRF;SG;1;NEG;PST
yetküzmek	yetküzmekchi	V;INTEN;SG;3;PRS
dawamlashturmaq	dawamlashturmaqchisen	V;INTEN;SG;2;INFM;PRS
yémek	yémekchiduq	V;INTEN;PL;1;PST
yémek	yégensiler	V;PRF;PL;2;PRS
külümsirimek	külümsirigen	V;PRF;SG;3;PRS
öltürmek	öltüridu	V;IPFV;SG;3;PRS
tutmaq	tumighansiz	V;PRF;FRML;SG;2;NEG;PRS
tutmaq	tutqaniding	V;PRF;SG;2;INFM;PST
untumaq	untuysiz	V;IPFV;FRML;SG;2;PRS
untumaq	untughansiler	V;PRF;PL;2;PRS
naxsha éytmaq	naxsha éytmidinglar	V;PL;2;NEG;PST
peseymek	pesiyiwatattingiz	V;PROG;FRML;SG;2;PST
körünmek	köründi	V;PL;3;PST
ishenmek	ishendi	V;PL;3;PST
tingshimaq	tingshimiduq	V;PL;1;NEG;PST
epsuslanmaq	epsuslanmaqchidim	V;INTEN;SG;1;PST
mu'amile qilmaq	mu'amile qilghansiz	V;PRF;FRML;SG;2;PRS
qorqmaq	qorqimaqchidim	V;INTEN;SG;1;PST
oylimaq	oylighanidim	V;PRF;SG;1;PST
oylimaq	oylayttingiz	V;IPFV;FRML;SG;2;PST
peseymek	pesiyidu	V;IPFV;SG;3;PRS
almaq	almighan	V;PRF;PL;3;NEG;PRS
bashlimaq	bashlayttuq	V;IPFV;PL;1;PST
chüshenmek	chüshiniwatatti	V;PROG;PL;3;PST
kechürmek	kechüretting	V;IPFV;SG;2;INFM;PST
almaq	alattim	V;IPFV;SG;1;PST
yötkimek	yötkewatattim	V;PROG;SG;1;PST
uchmaq	uchisen	V;IPFV;SG;2;INFM;PRS
yetküzmek	yetküzmigensiz	V;PRF;FRML;SG;2;NEG;PRS
kechürmek	kechürgeniduq	V;PRF;PL;1;PST
yazmaq	yazmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
kechürmek	kechürmekchiding	V;INTEN;SG;2;INFM;PST
sorimaq	sorighanmiz	V;PRF;PL;1;PRS
körsetmek	körsetmidim	V;SG;1;NEG;PST
bildürmek	bildürmiduq	V;PL;1;NEG;PST
nepeslenmek	nepesleniwatattim	V;PROG;SG;1;PST
qorqmaq	qorqimighan	V;PRF;PL;3;NEG;PRS
körsetmek	körsetkeniduq	V;PRF;PL;1;PST
körmek	körmekchidi	V;INTEN;PL;3;PST
yimek	yewatattim	V;PROG;SG;1;PST
kirmek	kirmidi	V;SG;3;NEG;PST
heydimek	heydimekchidingiz	V;FRML;INTEN;SG;2;PST
körünmek	körünisen	V;IPFV;SG;2;INFM;PRS
belgilimek	belgilewatatti	V;PROG;PL;3;PST
epsuslanmaq	epsuslan'ghanmiz	V;PRF;PL;1;PRS
sétiwalmaq	sétiwalidu	V;IPFV;PL;3;PRS
yighlamaq	yighlimaqchiduq	V;INTEN;PL;1;PST
qoymaq	qoymighanidi	V;PRF;PL;3;NEG;PST
qorqmaq	qorqidi	V;PL;3;PST
tingshimaq	tingshidinglar	V;PL;2;PST
yardemleshmek	yardemlishiwatatting	V;PROG;SG;2;INFM;PST
oynimaq	oynighanidim	V;PRF;SG;1;PST
aghrinmaq	aghrin'ghanidi	V;PRF;PL;3;PST
achmaq	achmighanidi	V;PRF;PL;3;NEG;PST
qaytmaq	qayturisiler	V;IPFV;PL;2;PRS
saqlimaq	saqlimighan	V;PRF;SG;3;NEG;PRS
qobul qilmaq	qobul qilmidim	V;SG;1;NEG;PST
tashlimaq	tashlimaqchisen	V;INTEN;SG;2;INFM;PRS
anglimaq	anglimaqchi	V;INTEN;PL;3;PRS
nepeslenmek	nepeslenmekchidi	V;INTEN;PL;3;PST
yazmaq	yéziwatattim	V;PROG;SG;1;PST
tölimek	töleymiz	V;IPFV;PL;1;PRS
köydürmek	köydüridu	V;IPFV;PL;3;PRS
aghrimaq	aghridi	V;PL;3;PST
oynimaq	oynighanidi	V;PRF;SG;3;PST
almaq	almighanidingiz	V;PRF;FRML;SG;2;NEG;PST
sétiwalmaq	sétiwalattinglar	V;IPFV;PL;2;PST
eslimek	esligen	V;PRF;SG;3;PRS
anglimaq	anglimiding	V;SG;2;NEG;INFM;PST
qalmaq	qalattim	V;IPFV;SG;1;PST
ewetmek	ewetkenidinglar	V;PRF;PL;2;PST
qobul qilmaq	qobul qiliwatisiz	V;PROG;FRML;SG;2;PRS
külümsirimek	külümsiriding	V;SG;2;INFM;PST
yetküzmek	yetküzüwatattingiz	V;PROG;FRML;SG;2;PST
köydürmek	köydürmigensiler	V;PRF;PL;2;NEG;PRS
ishenmek	ishen'migenidi	V;PRF;SG;3;NEG;PST
qaytmaq	qayturmaqchisiz	V;FRML;INTEN;SG;2;PRS
bilmek	biliwatattingiz	V;PROG;FRML;SG;2;PST
oxshatmaq	oxshitiwatatti	V;PROG;PL;3;PST
jawab bermek	jawab bériwatisen	V;PROG;SG;2;INFM;PRS
qorqmaq	qorqimidi	V;SG;3;NEG;PST
bolmaq	bolatting	V;IPFV;SG;2;INFM;PST
peseymek	peseymekchidinglar	V;INTEN;PL;2;PST
jawab bermek	jawab bermidinglar	V;PL;2;NEG;PST
eslimek	esleyttim	V;IPFV;SG;1;PST
söymek	söydingiz	V;FRML;SG;2;PST
yötkimek	yötkigenidi	V;PRF;SG;3;PST
kelmek	kelgen	V;PRF;SG;3;PRS
peseymek	peseymigen	V;PRF;SG;3;NEG;PRS
keymek	keymigenidi	V;PRF;PL;3;NEG;PST
nepeslenmek	nepesleniwatidu	V;PROG;SG;3;PRS
peseymek	pesiyettinglar	V;IPFV;PL;2;PST
öltürmek	öltürmekchimen	V;INTEN;SG;1;PRS
nepeslenmek	nepesleniwatattuq	V;PROG;PL;1;PST
eslimek	esliduq	V;PL;1;PST
keymek	kéyiwatimiz	V;PROG;PL;1;PRS
tutmaq	tutmaqchisiler	V;INTEN;PL;2;PRS
chüshmek	chüshmigenidi	V;PRF;SG;3;NEG;PST
nepeslenmek	nepesleniwatisiler	V;PROG;PL;2;PRS
ichmek	ichmigenidim	V;PRF;SG;1;NEG;PST
étirap qilmaq	étirap qilghaniding	V;PRF;SG;2;INFM;PST
söymek	söymekchimen	V;INTEN;SG;1;PRS
aghrinmaq	aghriniwatatti	V;PROG;SG;3;PST
oxshatmaq	oxshitisen	V;IPFV;SG;2;INFM;PRS
sezmek	sezgenidingiz	V;PRF;FRML;SG;2;PST
epsuslanmaq	epsuslinimiz	V;IPFV;PL;1;PRS
chüshmek	chüshüwatimiz	V;PROG;PL;1;PRS
bayqimaq	bayqimighansiz	V;PRF;FRML;SG;2;NEG;PRS
kelmek	kelmekchidingiz	V;FRML;INTEN;SG;2;PST
oqumaq	oqumighanidinglar	V;PRF;PL;2;NEG;PST
nepeslenmek	nepeslenmekchimiz	V;INTEN;PL;1;PRS
dawamlashturmaq	dawamlashturattinglar	V;IPFV;PL;2;PST
aghrinmaq	aghrin'mighanidingiz	V;PRF;FRML;SG;2;NEG;PST
tölimek	tölimekchi	V;INTEN;SG;3;PRS
bermek	bergeniding	V;PRF;SG;2;INFM;PST
yaqturmaq	yaqturmighanidinglar	V;PRF;PL;2;NEG;PST
epsuslanmaq	epsuslanmaqchiduq	V;INTEN;PL;1;PST
soqmaq	soqti	V;PL;3;PST
chüshenmek	chüshenmiding	V;SG;2;NEG;INFM;PST
soqmaq	soquwatatti	V;PROG;PL;3;PST
qilmaq	qiliwatisen	V;PROG;SG;2;INFM;PRS
köydürmek	köydüriwatidu	V;PROG;PL;3;PRS
qoshulmaq	qoshulmaqchidi	V;INTEN;SG;3;PST
bolmaq	bolatting	V;IPFV;SG;2;INFM;PST
yötkimek	yötkimekchidim	V;INTEN;SG;1;PST
peseymek	peseymekchisen	V;INTEN;SG;2;INFM;PRS
soqmaq	soqqan	V;PRF;PL;3;PRS
eslimek	eslewatidu	V;PROG;PL;3;PRS
achmaq	achmaqchimiz	V;INTEN;PL;1;PRS
oynimaq	oynimighansiz	V;PRF;FRML;SG;2;NEG;PRS
qorqmaq	qorqimighansiz	V;PRF;FRML;SG;2;NEG;PRS
achmaq	achting	V;SG;2;INFM;PST
buzmaq	buzmighansen	V;PRF;SG;2;NEG;INFM;PRS
mangmaq	mangduq	V;PL;1;PST
qachilimaq	qachilighanidingiz	V;PRF;FRML;SG;2;PST
köydürmek	köydürettinglar	V;IPFV;PL;2;PST
bilmek	bilgeniduq	V;PRF;PL;1;PST
untumaq	untuydu	V;IPFV;PL;3;PRS
yötkimek	yötkewatisiz	V;PROG;FRML;SG;2;PRS
chüshmek	chüshisiler	V;IPFV;PL;2;PRS
körmek	körisiz	V;IPFV;FRML;SG;2;PRS
soqmaq	soquwatimiz	V;PROG;PL;1;PRS
kelmek	kelmigenmiz	V;PRF;PL;1;NEG;PRS
körsetmek	körsetmigen	V;PRF;SG;3;NEG;PRS
sözlimek	sözlimekchidingiz	V;FRML;INTEN;SG;2;PST
qorqmaq	qorqiwatattinglar	V;PROG;PL;2;PST
olturmaq	olturmaqchisiler	V;INTEN;PL;2;PRS
epsuslanmaq	epsuslanding	V;SG;2;INFM;PST
sözlimek	sözligenidingiz	V;PRF;FRML;SG;2;PST
urushmaq	urushuwatimen	V;PROG;SG;1;PRS
külümsirimek	külümsirimiduq	V;PL;1;NEG;PST
eslimek	esleymen	V;IPFV;SG;1;PRS
yémek	yewatidu	V;PROG;PL;3;PRS
heydimek	heydewatattuq	V;PROG;PL;1;PST
saqlimaq	saqlaymiz	V;IPFV;PL;1;PRS
kirmek	kirgenidim	V;PRF;SG;1;PST
keymek	keymekchisiler	V;INTEN;PL;2;PRS
anglimaq	anglawatattingiz	V;PROG;FRML;SG;2;PST
urushmaq	urushuwatimiz	V;PROG;PL;1;PRS
jawab bermek	jawab bérettim	V;IPFV;SG;1;PST
körsetmek	körsetken	V;PRF;PL;3;PRS
bashlimaq	bashlimaqchidingiz	V;FRML;INTEN;SG;2;PST
qachilimaq	qachilimaqchimen	V;INTEN;SG;1;PRS
kirmek	kirmigen	V;PRF;SG;3;NEG;PRS
bilmek	bilgenidim	V;PRF;SG;1;PST
sétiwalmaq	sétiwalghansiler	V;PRF;PL;2;PRS
olturmaq	olturmidingiz	V;FRML;SG;2;NEG;PST
kirmek	kirmigenmiz	V;PRF;PL;1;NEG;PRS
barmaq	barmaqchidi	V;INTEN;SG;3;PST
barmaq	barmighansiler	V;PRF;PL;2;NEG;PRS
agahlandurmaq	agahlandurghansiler	V;PRF;PL;2;PRS
bildürmek	bildürmigenidi	V;PRF;SG;3;NEG;PST
almaq	éliwatattingiz	V;PROG;FRML;SG;2;PST
kirmek	kirgenmiz	V;PRF;PL;1;PRS
eslimek	esligeniding	V;PRF;SG;2;INFM;PST
soqmaq	soqtim	V;SG;1;PST
chüshmek	chüshettim	V;IPFV;SG;1;PST
ewetmek	ewetmekchimiz	V;INTEN;PL;1;PRS
urushmaq	urushqan	V;PRF;PL;3;PRS
oqumaq	oquwatimiz	V;PROG;PL;1;PRS
bayqimaq	bayqawatidu	V;PROG;SG;3;PRS
yötkimek	yötkimekchiduq	V;INTEN;PL;1;PST
qachilimaq	qachilighanmen	V;PRF;SG;1;PRS
yémek	yédinglar	V;PL;2;PST
urushmaq	urushmidi	V;PL;3;NEG;PST
eslimek	eslimekchimiz	V;INTEN;PL;1;PRS
külümsirimek	külümsirigenidi	V;PRF;PL;3;PST
ishlimek	ishlimigenmen	V;PRF;SG;1;NEG;PRS
yapmaq	yamighansiz	V;PRF;FRML;SG;2;NEG;PRS
bildürmek	bildürgeniduq	V;PRF;PL;1;PST
yapmaq	yapmidi	V;PL;3;NEG;PST
ishenmek	ishinettuq	V;IPFV;PL;1;PST
belgilimek	belgiligen	V;PRF;PL;3;PRS
tingshimaq	tingshimighanidinglar	V;PRF;PL;2;NEG;PST
oynimaq	oynimidinglar	V;PL;2;NEG;PST
aghrimaq	aghriding	V;SG;2;INFM;PST
jawab bermek	jawab bergenidim	V;PRF;SG;1;PST
achmaq	achisiz	V;IPFV;FRML;SG;2;PRS
bermek	bergensen	V;PRF;SG;2;INFM;PRS
urushmaq	urushqanidingiz	V;PRF;FRML;SG;2;PST
yighlamaq	yighlayttuq	V;IPFV;PL;1;PST
chaqirmaq	chaqiriwatattuq	V;PROG;PL;1;PST
chaqirmaq	chaqiratting	V;IPFV;SG;2;INFM;PST
barmaq	bardi	V;PL;3;PST
tapmaq	tépiwatatti	V;PROG;SG;3;PST
yaqturmaq	yaqturghanmiz	V;PRF;PL;1;PRS
achmaq	achqan	V;PRF;PL;3;PRS
ishenmek	ishinisen	V;IPFV;SG;2;INFM;PRS
aghrimaq	aghriymiz	V;IPFV;PL;1;PRS
ishlimek	ishleysiz	V;IPFV;FRML;SG;2;PRS
barmaq	barmiding	V;SG;2;NEG;INFM;PST
barmaq	bériwatimiz	V;PROG;PL;1;PRS
saqlimaq	saqlaydu	V;IPFV;PL;3;PRS
yapmaq	yapqanmen	V;PRF;SG;1;PRS
untumaq	untuwatattuq	V;PROG;PL;1;PST
aghrimaq	aghriydu	V;IPFV;SG;3;PRS
qorqmaq	qorqighandingiz	V;PRF;FRML;SG;2;PST
körünmek	körünmekchiding	V;INTEN;SG;2;INFM;PST
aghrimaq	aghrimaqchisen	V;INTEN;SG;2;INFM;PRS
sétiwalmaq	sétiwalmaqchi	V;INTEN;SG;3;PRS
söymek	söymidi	V;SG;3;NEG;PST
bayqimaq	bayqighanmiz	V;PRF;PL;1;PRS
kirmek	kiridu	V;IPFV;SG;3;PRS
urushmaq	urushmighanidi	V;PRF;PL;3;NEG;PST
untumaq	untumighaniduq	V;PRF;PL;1;NEG;PST
öltürmek	öltüriwatisiler	V;PROG;PL;2;PRS
körmek	körimen	V;IPFV;SG;1;PRS
bermek	biriwatattim	V;PROG;SG;1;PST
étirap qilmaq	étirap qiliwatisen	V;PROG;SG;2;INFM;PRS
körmek	körduq	V;PL;1;PST
qoshulmaq	qoshulmaqchimen	V;INTEN;SG;1;PRS
söymek	söygensiz	V;PRF;FRML;SG;2;PRS
tapmaq	tapmaqchidingiz	V;FRML;INTEN;SG;2;PST
bayqimaq	bayqayttuq	V;IPFV;PL;1;PST
chiqmaq	chiqtuq	V;PL;1;PST
oqumaq	oqughanidi	V;PRF;PL;3;PST
qilmaq	qilmighan	V;PRF;SG;3;NEG;PRS
xalimaq	xalimighanidingiz	V;PRF;FRML;SG;2;NEG;PST
tutmaq	tutmaqchimiz	V;INTEN;PL;1;PRS
mangmaq	méngiwatidu	V;PROG;SG;3;PRS
urushmaq	urushisen	V;IPFV;SG;2;INFM;PRS
aghrinmaq	aghriniwatisiler	V;PROG;PL;2;PRS
barmaq	baridu	V;IPFV;SG;3;PRS
sözlimek	sözlimigensen	V;PRF;SG;2;NEG;INFM;PRS
köydürmek	köydürettingiz	V;IPFV;FRML;SG;2;PST
soqmaq	soquwatisen	V;PROG;SG;2;INFM;PRS
körünmek	körünmekchidim	V;INTEN;SG;1;PST
sözlimek	sözlidi	V;SG;3;PST
sözlimek	sözlimigenidi	V;PRF;PL;3;NEG;PST
nepeslenmek	nepesleniwatisen	V;PROG;SG;2;INFM;PRS
qorqmaq	qorqatti	V;IPFV;SG;3;PST
turmaq	turmidinglar	V;PL;2;NEG;PST
untumaq	untumidi	V;SG;3;NEG;PST
uchmaq	ucmighansiler	V;PRF;PL;2;NEG;PRS
bildürmek	bildürettim	V;IPFV;SG;1;PST
sözlimek	sözlimigen	V;PRF;SG;3;NEG;PRS
qachilimaq	qachilimidinglar	V;PL;2;NEG;PST
qorqmaq	qorqmighaniding	V;PRF;SG;2;NEG;INFM;PST
bildürmek	bildürüwatattinglar	V;PROG;PL;2;PST
ichmek	ichiwatisiz	V;PROG;FRML;SG;2;PRS
qalmaq	qalduq	V;PL;1;PST
külümsirimek	külümsirigenidim	V;PRF;SG;1;PST
peseymek	peseydinglar	V;PL;2;PST
mu'amile qilmaq	mu'amile qilmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
söymek	söyüwatimiz	V;PROG;PL;1;PRS
kelmek	kéliwatatting	V;PROG;SG;2;INFM;PST
ishenmek	ishen'genmen	V;PRF;SG;1;PRS
olturmaq	olturmighanmiz	V;PRF;PL;1;NEG;PRS
belgilimek	belgilimekchidim	V;INTEN;SG;1;PST
qachilimaq	qachilawatisen	V;PROG;SG;2;INFM;PRS
peseymek	peseymigensiz	V;PRF;FRML;SG;2;NEG;PRS
aghrimaq	aghrimighan	V;PRF;PL;3;NEG;PRS
külümsirimek	külümsirimigensiz	V;PRF;FRML;SG;2;NEG;PRS
almaq	almidingiz	V;FRML;SG;2;NEG;PST
kelmek	kelmekchiding	V;INTEN;SG;2;INFM;PST
peseymek	peseymekchidi	V;INTEN;PL;3;PST
kirmek	kirgenidi	V;PRF;SG;3;PST
yatmaq	yatqanmiz	V;PRF;PL;1;PRS
qobul qilmaq	qobul qiliwatimiz	V;PROG;PL;1;PRS
saqlimaq	saqlimighansiler	V;PRF;PL;2;NEG;PRS
tölimek	töligensen	V;PRF;SG;2;INFM;PRS
mu'amile qilmaq	mu'amile qilmighanmiz	V;PRF;PL;1;NEG;PRS
körmek	körmiding	V;SG;2;NEG;INFM;PST
aghrinmaq	aghrinmiding	V;SG;2;NEG;INFM;PST
almaq	éliwatisiler	V;PROG;PL;2;PRS
tapshuruwalmaq	tapshuruwalghan	V;PRF;SG;3;PRS
eslimek	esligenidi	V;PRF;SG;3;PST
bildürmek	bildürmekchiduq	V;INTEN;PL;1;PST
qaytmaq	qayturmiduq	V;PL;1;NEG;PST
anglimaq	anglighanidi	V;PRF;PL;3;PST
tapmaq	tapmidingiz	V;FRML;SG;2;NEG;PST
kirmek	kirmekchidinglar	V;INTEN;PL;2;PST
étirap qilmaq	étirap qiliwatidu	V;PROG;SG;3;PRS
yapmaq	yépiwatattingiz	V;PROG;FRML;SG;2;PST
tölimek	töleydu	V;IPFV;SG;3;PRS
anglimaq	anglimighansiz	V;PRF;FRML;SG;2;NEG;PRS
dawamlashturmaq	dawamlashturmaqchisiler	V;INTEN;PL;2;PRS
nepeslenmek	nepeslendi	V;PL;3;PST
achmaq	échiwatattim	V;PROG;SG;1;PST
qilmaq	qilisen	V;IPFV;SG;2;INFM;PRS
yötkimek	yötkeyttinglar	V;IPFV;PL;2;PST
oylimaq	oylimaqchiduq	V;INTEN;PL;1;PST
kelmek	kelmekchimen	V;INTEN;SG;1;PRS
mu'amile qilmaq	mu'amile qiliwatatti	V;PROG;PL;3;PST
tapshuruwalmaq	tapshuruwalmaqchi	V;INTEN;SG;3;PRS
oynimaq	oynighanidinglar	V;PRF;PL;2;PST
ölmek	ölgensen	V;PRF;SG;2;INFM;PRS
chaqirmaq	chaqirmaqchidi	V;INTEN;SG;3;PST
uchmaq	uchiwatimen	V;PROG;SG;1;PRS
soqmaq	soqqanmiz	V;PRF;PL;1;PRS
yazmaq	yazmighaniding	V;PRF;SG;2;NEG;INFM;PST
yetküzmek	yetküzetti	V;IPFV;SG;3;PST
qorqmaq	qorqimaqchimiz	V;INTEN;PL;1;PRS
oxshatmaq	oxshitatti	V;IPFV;PL;3;PST
naxsha éytmaq	naxsha éytiwatimen	V;PROG;SG;1;PRS
uchmaq	uchimen	V;IPFV;SG;1;PRS
nepeslenmek	nepeslenmidingiz	V;FRML;SG;2;NEG;PST
yardemleshmek	yardemlishidu	V;IPFV;SG;3;PRS
qilmaq	qilmaqchisen	V;INTEN;SG;2;INFM;PRS
ichmek	ichimen	V;IPFV;SG;1;PRS
tingshimaq	tingshighanidi	V;PRF;SG;3;PST
agahlandurmaq	agahlandurmaqchidinglar	V;INTEN;PL;2;PST
yimek	yeytti	V;IPFV;PL;3;PST
chüshenmek	chüshending	V;SG;2;INFM;PST
aghrinmaq	aghrin'mighaniding	V;PRF;SG;2;NEG;INFM;PST
turmaq	turghaniduq	V;PRF;PL;1;PST
bashlimaq	bashlaymiz	V;IPFV;PL;1;PRS
yetküzmek	yetküzmekchidim	V;INTEN;SG;1;PST
tapmaq	tapmaqchiduq	V;INTEN;PL;1;PST
sétiwalmaq	sétiwalmaqchiding	V;INTEN;SG;2;INFM;PST
oylimaq	oylayttim	V;IPFV;SG;1;PST
tingshimaq	tingshimighaniding	V;PRF;SG;2;NEG;INFM;PST
démek	dewatatting	V;PROG;SG;2;INFM;PST
aghrinmaq	aghrinmidingiz	V;FRML;SG;2;NEG;PST
tapshuruwalmaq	tapshuruwalmaqchidi	V;INTEN;SG;3;PST
uchmaq	uchmaqchimiz	V;INTEN;PL;1;PRS
yardemleshmek	yardemleshmekchidingiz	V;FRML;INTEN;SG;2;PST
ishenmek	ishen'genidi	V;PRF;PL;3;PST
chiqmaq	chiqisiz	V;IPFV;FRML;SG;2;PRS
peseymek	peseymekchi	V;INTEN;SG;3;PRS
chaqirmaq	chaqirdinglar	V;PL;2;PST
qorqmaq	qorqidingiz	V;FRML;SG;2;PST
naxsha éytmaq	naxsha éytmighanmen	V;PRF;SG;1;NEG;PRS
naxsha éytmaq	naxsha éytqanmen	V;PRF;SG;1;PRS
heydimek	heydewatisiz	V;PROG;FRML;SG;2;PRS
urushmaq	urushmaqchidi	V;INTEN;PL;3;PST
naxsha éytmaq	naxsha éytmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
turmaq	turiwatisiler	V;PROG;PL;2;PRS
qoshulmaq	qoshulmidim	V;SG;1;NEG;PST
kirmek	kirgeniding	V;PRF;SG;2;INFM;PST
yazmaq	yazmaqchidi	V;INTEN;PL;3;PST
yazmaq	yéziwatimiz	V;PROG;PL;1;PRS
öltürmek	öltürding	V;SG;2;INFM;PST
kelmek	kéliwatattim	V;PROG;SG;1;PST
chiqmaq	chiqmighaniduq	V;PRF;PL;1;NEG;PST
yötkimek	yötkigensiler	V;PRF;PL;2;PRS
aghrinmaq	aghrin'mighanmen	V;PRF;SG;1;NEG;PRS
chaqirmaq	chaqiridu	V;IPFV;SG;3;PRS
keymek	keygensiz	V;PRF;FRML;SG;2;PRS
bermek	bermekchisen	V;INTEN;SG;2;INFM;PRS
qorqmaq	qorqiwatidu	V;PROG;PL;3;PRS
köydürmek	köydürmekchimen	V;INTEN;SG;1;PRS
yötkimek	yötkimigenidim	V;PRF;SG;1;NEG;PST
saqlimaq	saqlayttim	V;IPFV;SG;1;PST
turmaq	turghaniduq	V;PRF;PL;1;PST
anglimaq	anglighanmiz	V;PRF;PL;1;PRS
jawab bermek	jawab béretti	V;IPFV;SG;3;PST
körsetmek	körsetmigen	V;PRF;PL;3;NEG;PRS
démek	démigeniding	V;PRF;SG;2;NEG;INFM;PST
yémek	yéding	V;SG;2;INFM;PST
kechürmek	kechürdi	V;SG;3;PST
körsetmek	körsettingiz	V;FRML;SG;2;PST
qoshulmaq	qoshulattingiz	V;IPFV;FRML;SG;2;PST
oylimaq	oylimighanmen	V;PRF;SG;1;NEG;PRS
naxsha éytmaq	naxsha éytmiduq	V;PL;1;NEG;PST
köydürmek	köydürgending	V;PRF;SG;2;INFM;PST
ögenmek	ögen'migensen	V;PRF;SG;2;NEG;INFM;PRS
keymek	keygenidi	V;PRF;SG;3;PST
achmaq	achmaqchisen	V;INTEN;SG;2;INFM;PRS
anglimaq	anglimighanidingiz	V;PRF;FRML;SG;2;NEG;PST
sorimaq	sorimaqchi	V;INTEN;SG;3;PRS
yimek	yigensiz	V;PRF;FRML;SG;2;PRS
anglimaq	anglawatisiler	V;PROG;PL;2;PRS
qaytmaq	qayturmaqchi	V;INTEN;PL;3;PRS
yazmaq	yéziwatatti	V;PROG;SG;3;PST
kechürmek	kechüriwatisiler	V;PROG;PL;2;PRS
qalmaq	qalidu	V;IPFV;SG;3;PRS
xalimaq	xaliding	V;SG;2;INFM;PST
uchmaq	uchqan	V;PRF;PL;3;PRS
soqmaq	soqqanidim	V;PRF;SG;1;PST
ewetmek	ewetettingiz	V;IPFV;FRML;SG;2;PST
körsetmek	körsitimiz	V;IPFV;PL;1;PRS
saqlimaq	saqlaytting	V;IPFV;SG;2;INFM;PST
mu'amile qilmaq	mu'amile qilmaqchidim	V;INTEN;SG;1;PST
ishlimek	ishlimiduq	V;PL;1;NEG;PST
yazmaq	yazmaqchidinglar	V;INTEN;PL;2;PST
tölimek	tölidim	V;SG;1;PST
mangmaq	mangmighan	V;PRF;SG;3;NEG;PRS
urushmaq	urushattinglar	V;IPFV;PL;2;PST
belgilimek	belgilewatattuq	V;PROG;PL;1;PST
körmek	körgenidi	V;PRF;SG;3;PST
ichmek	ichkenmiz	V;PRF;PL;1;PRS
kirmek	kirmigeniding	V;PRF;SG;2;NEG;INFM;PST
barmaq	barghaniduq	V;PRF;PL;1;PST
ölmek	ölmekchidi	V;INTEN;PL;3;PST
almaq	almaqchiding	V;INTEN;SG;2;INFM;PST
chüshmek	chüshmekchi	V;INTEN;PL;3;PRS
mu'amile qilmaq	mu'amile qilmaqchiduq	V;INTEN;PL;1;PST
étirap qilmaq	étirap qilimen	V;IPFV;SG;1;PRS
öltürmek	öltürmekchi	V;INTEN;SG;3;PRS
keymek	keygensiler	V;PRF;PL;2;PRS
étirap qilmaq	étirap qilattim	V;IPFV;SG;1;PST
yémek	yéduq	V;PL;1;PST
aghrinmaq	aghrinmaqchi	V;INTEN;SG;3;PRS
qalmaq	qalatti	V;IPFV;PL;3;PST
ishenmek	ishenmekchisen	V;INTEN;SG;2;INFM;PRS
sezmek	sezdi	V;SG;3;PST
ishenmek	ishinettinglar	V;IPFV;PL;2;PST
achmaq	achqansiler	V;PRF;PL;2;PRS
oynimaq	oynimaqchiduq	V;INTEN;PL;1;PST
chaqirmaq	chaqirmighan	V;PRF;PL;3;NEG;PRS
olturmaq	olturmighan	V;PRF;PL;3;NEG;PRS
kechürmek	kechürmigensiz	V;PRF;FRML;SG;2;NEG;PRS
qilmaq	qilmidingiz	V;FRML;SG;2;NEG;PST
urushmaq	urushuwatatti	V;PROG;PL;3;PST
sétiwalmaq	sétiwalmighanmiz	V;PRF;PL;1;NEG;PRS
qobul qilmaq	qobul qilimiz	V;IPFV;PL;1;PRS
saqlimaq	saqlighanmen	V;PRF;SG;1;PRS
söymek	söydinglar	V;PL;2;PST
aghrinmaq	aghrin'mighansiler	V;PRF;PL;2;NEG;PRS
urushmaq	urushqanmen	V;PRF;SG;1;PRS
yaqturmaq	yaqturmaqchidingiz	V;FRML;INTEN;SG;2;PST
yardemleshmek	yardemleshtinglar	V;PL;2;PST
oqumaq	oqumighansiler	V;PRF;PL;2;NEG;PRS
qoshulmaq	qoshuliwatidu	V;PROG;PL;3;PRS
aghrinmaq	aghrinmaqchisiler	V;INTEN;PL;2;PRS
agahlandurmaq	agahlandurmaqchisiler	V;INTEN;PL;2;PRS
eslimek	eslimekchidim	V;INTEN;SG;1;PST
tutmaq	tutmaqchidi	V;INTEN;PL;3;PST
ishlimek	ishleysiler	V;IPFV;PL;2;PRS
qobul qilmaq	qobul qilattinglar	V;IPFV;PL;2;PST
ölmek	ölmigenidim	V;PRF;SG;1;NEG;PST
bilmek	bilding	V;SG;2;INFM;PST
tapmaq	tapmidi	V;PL;3;NEG;PST
külümsirimek	külümsireytting	V;IPFV;SG;2;INFM;PST
eslimek	eslewatatting	V;PROG;SG;2;INFM;PST
bashlimaq	bashlighaniduq	V;PRF;PL;1;PST
kirmek	kirdingiz	V;FRML;SG;2;PST
turmaq	turghanidim	V;PRF;SG;1;PST
belgilimek	belgilidinglar	V;PL;2;PST
yémek	yeyttim	V;IPFV;SG;1;PST
eslimek	esligenidi	V;PRF;PL;3;PST
tutmaq	tutmaqchisiz	V;FRML;INTEN;SG;2;PRS
qobul qilmaq	qobul qilattuq	V;IPFV;PL;1;PST
bermek	bermigensiz	V;PRF;FRML;SG;2;NEG;PRS
bayqimaq	bayqawatimiz	V;PROG;PL;1;PRS
olturmaq	olturdi	V;SG;3;PST
tingshimaq	tingshimidim	V;SG;1;NEG;PST
achmaq	achmidi	V;PL;3;NEG;PST
sezmek	sezmigenidingiz	V;PRF;FRML;SG;2;NEG;PST
chiqmaq	chiqqanidingiz	V;PRF;FRML;SG;2;PST
heydimek	heydimigen	V;PRF;PL;3;NEG;PRS
qoshulmaq	qoshuliwatidu	V;PROG;SG;3;PRS
kirmek	kirmekchisiz	V;FRML;INTEN;SG;2;PRS
yetküzmek	yetküzmidingiz	V;FRML;SG;2;NEG;PST
soqmaq	soqatti	V;IPFV;PL;3;PST
bashlimaq	bashlaysen	V;IPFV;SG;2;INFM;PRS
qaytmaq	qayturmighan	V;PRF;PL;3;NEG;PRS
yighlamaq	yighlimaqchidingiz	V;FRML;INTEN;SG;2;PST
tashlimaq	tashlayttingiz	V;IPFV;FRML;SG;2;PST
uchmaq	uchiwatatting	V;PROG;SG;2;INFM;PST
tashlimaq	tashlawatattim	V;PROG;SG;1;PST
mangmaq	mangmaqchisiz	V;FRML;INTEN;SG;2;PRS
heydimek	heydimigenidi	V;PRF;PL;3;NEG;PST
nepeslenmek	nepeslenettim	V;IPFV;SG;1;PST
uchmaq	ucmighan	V;PRF;SG;3;NEG;PRS
sözlimek	sözliding	V;SG;2;INFM;PST
oxshatmaq	oxshatmaqchidi	V;INTEN;PL;3;PST
naxsha éytmaq	naxsha éytisen	V;IPFV;SG;2;INFM;PRS
olturmaq	olturatti	V;IPFV;PL;3;PST
démek	démekchi	V;INTEN;SG;3;PRS
köydürmek	köydürgensiler	V;PRF;PL;2;PRS
almaq	alatting	V;IPFV;SG;2;INFM;PST
qorqmaq	qorqimaqchimen	V;INTEN;SG;1;PRS
körsetmek	körsitetti	V;IPFV;SG;3;PST
sétiwalmaq	sétiwalmaqchiduq	V;INTEN;PL;1;PST
kirmek	kirgen	V;PRF;PL;3;PRS
körmek	körüwatidu	V;PROG;SG;3;PRS
oylimaq	oylimiduq	V;PL;1;NEG;PST
uchmaq	uchatting	V;IPFV;SG;2;INFM;PST
kelmek	kelmekchi	V;INTEN;PL;3;PRS
qilmaq	qilghanidinglar	V;PRF;PL;2;PST
chüshmek	chüshüwatisiz	V;PROG;FRML;SG;2;PRS
ishenmek	ishenmekchimen	V;INTEN;SG;1;PRS
yötkimek	yötkiding	V;SG;2;INFM;PST
achmaq	achtinglar	V;PL;2;PST
qobul qilmaq	qobul qilmaqchi	V;INTEN;SG;3;PRS
yötkimek	yötkewatimen	V;PROG;SG;1;PRS
keymek	kéyisen	V;IPFV;SG;2;INFM;PRS
sezmek	sezmekchisiz	V;FRML;INTEN;SG;2;PRS
qaytmaq	qaytiwatatting	V;PROG;SG;2;INFM;PST
qilmaq	qildi	V;PL;3;PST
yardemleshmek	yardemlishiwatidu	V;PROG;SG;3;PRS
kechürmek	kechüriwatattuq	V;PROG;PL;1;PST
yötkimek	yötkimigensiz	V;PRF;FRML;SG;2;NEG;PRS
jawab bermek	jawab bermekchiding	V;INTEN;SG;2;INFM;PST
yatmaq	yatisiler	V;IPFV;PL;2;PRS
dawamlashturmaq	dawamlashturuwatatti	V;PROG;SG;3;PST
eslimek	esligensen	V;PRF;SG;2;INFM;PRS
yimek	yeydu	V;IPFV;SG;3;PRS
ishenmek	ishen'migen	V;PRF;PL;3;NEG;PRS
söymek	söydi	V;PL;3;PST
agahlandurmaq	agahlandurmidinglar	V;PL;2;NEG;PST
oxshatmaq	oxhatmighanidi	V;PRF;SG;3;NEG;PST
démek	déduq	V;PL;1;PST
turmaq	turuwatatting	V;PROG;SG;2;INFM;PST
jawab bermek	jawab bergen	V;PRF;PL;3;PRS
heydimek	heydimekchimiz	V;INTEN;PL;1;PRS
ögenmek	ögen'gensen	V;PRF;SG;2;INFM;PRS
oylimaq	oylimaqchidi	V;INTEN;PL;3;PST
körmek	körmekchi	V;INTEN;SG;3;PRS
mu'amile qilmaq	mu'amile qilmighaniduq	V;PRF;PL;1;NEG;PST
köydürmek	köydürmekchi	V;INTEN;SG;3;PRS
peseymek	pesiyiwatidu	V;PROG;PL;3;PRS
démek	démiduq	V;PL;1;NEG;PST
ishlimek	ishligenidi	V;PRF;PL;3;PST
qoymaq	qoyatti	V;IPFV;SG;3;PST
anglimaq	anglimaqchidim	V;INTEN;SG;1;PST
yémek	yédim	V;SG;1;PST
qoymaq	qoyuwatattinglar	V;PROG;PL;2;PST
buyrumaq	buyruysen	V;IPFV;SG;2;INFM;PRS
yapmaq	yapmaqchisiz	V;FRML;INTEN;SG;2;PRS
sorimaq	sorighaniding	V;PRF;SG;2;INFM;PST
kechürmek	kechürduq	V;PL;1;PST
chaqirmaq	chaqirmaqchidi	V;INTEN;PL;3;PST
yighlamaq	yighlidi	V;PL;3;PST
belgilimek	belgileytti	V;IPFV;PL;3;PST
aghrinmaq	aghrinisiz	V;IPFV;FRML;SG;2;PRS
ögenmek	ögen'genidingiz	V;PRF;FRML;SG;2;PST
jawab bermek	jawab bermekchidim	V;INTEN;SG;1;PST
qobul qilmaq	qobul qilghanmiz	V;PRF;PL;1;PRS
chüshenmek	chüshenmekchidi	V;INTEN;PL;3;PST
epsuslanmaq	epsusliniwatattim	V;PROG;SG;1;PST
belgilimek	belgilimekchiding	V;INTEN;SG;2;INFM;PST
körünmek	körünmekchiduq	V;INTEN;PL;1;PST
aghrimaq	aghrimiduq	V;PL;1;NEG;PST
yardemleshmek	yardemlishisiler	V;IPFV;PL;2;PRS
tashlimaq	tashlawatattinglar	V;PROG;PL;2;PST
chiqmaq	chiqqanidinglar	V;PRF;PL;2;PST
bildürmek	bildürmigenidim	V;PRF;SG;1;NEG;PST
yazmaq	yazghan	V;PRF;SG;3;PRS
aghrimaq	aghriwatattuq	V;PROG;PL;1;PST
aghrinmaq	aghrinmaqchidinglar	V;INTEN;PL;2;PST
yetküzmek	yetküzmekchi	V;INTEN;PL;3;PRS
kelmek	kélettuq	V;IPFV;PL;1;PST
kirmek	kirdi	V;PL;3;PST
oynimaq	oynaytti	V;IPFV;PL;3;PST
qalmaq	qaldinglar	V;PL;2;PST
qilmaq	qilghansiler	V;PRF;PL;2;PRS
aghrimaq	aghrighanidinglar	V;PRF;PL;2;PST
saqlimaq	saqlawatattinglar	V;PROG;PL;2;PST
öltürmek	öltürmigenidinglar	V;PRF;PL;2;NEG;PST
yapmaq	yapattingiz	V;IPFV;FRML;SG;2;PST
oynimaq	oynidingiz	V;FRML;SG;2;PST
almaq	almiding	V;SG;2;NEG;INFM;PST
sétiwalmaq	sétiwalidu	V;IPFV;SG;3;PRS
belgilimek	belgileytti	V;IPFV;SG;3;PST
tingshimaq	tingshaydu	V;IPFV;PL;3;PRS
ishenmek	ishen'gensiz	V;PRF;FRML;SG;2;PRS
tapshuruwalmaq	tapshuruwalmaqchimen	V;INTEN;SG;1;PRS
chüshenmek	chüshen'genidim	V;PRF;SG;1;PST
bermek	bermigensen	V;PRF;SG;2;NEG;INFM;PRS
sorimaq	sorimighansen	V;PRF;SG;2;NEG;INFM;PRS
dawamlashturmaq	dawamlashturmighanidi	V;PRF;PL;3;NEG;PST
qilmaq	qilmighanidinglar	V;PRF;PL;2;NEG;PST
nepeslenmek	nepeslenmidinglar	V;PL;2;NEG;PST
qalmaq	qalmighan	V;PRF;PL;3;NEG;PRS
bashlimaq	bashlaydu	V;IPFV;PL;3;PRS
tapshuruwalmaq	tapshuruwalidu	V;IPFV;SG;3;PRS
yaqturmaq	yaqturding	V;SG;2;INFM;PST
yimek	yimigeniding	V;PRF;SG;2;NEG;INFM;PST
qoshulmaq	qoshulatti	V;IPFV;SG;3;PST
külümsirimek	külümsirimigensen	V;PRF;SG;2;NEG;INFM;PRS
oynimaq	oynimighansen	V;PRF;SG;2;NEG;INFM;PRS
yazmaq	yazattuq	V;IPFV;PL;1;PST
peseymek	peseymigensiler	V;PRF;PL;2;NEG;PRS
xalimaq	xalimiding	V;SG;2;NEG;INFM;PST
turmaq	turuwatidu	V;PROG;PL;3;PRS
tingshimaq	tingshimighanidim	V;PRF;SG;1;NEG;PST
eslimek	esleysen	V;IPFV;SG;2;INFM;PRS
sezmek	sézimiz	V;IPFV;PL;1;PRS
kirmek	kirmekchidi	V;INTEN;PL;3;PST
oqumaq	oquytting	V;IPFV;SG;2;INFM;PST
yaqturmaq	yaqturghan	V;PRF;PL;3;PRS
xalimaq	xalimighanidi	V;PRF;SG;3;NEG;PST
yaqturmaq	yaqturuwatimen	V;PROG;SG;1;PRS
untumaq	untuysiler	V;IPFV;PL;2;PRS
bayqimaq	bayqimaqchidinglar	V;INTEN;PL;2;PST
naxsha éytmaq	naxsha éytmaqchiding	V;INTEN;SG;2;INFM;PST
qoshulmaq	qoshulding	V;SG;2;INFM;PST
qaytmaq	qaytiwatatti	V;PROG;SG;3;PST
ewetmek	ewetiwatattingiz	V;PROG;FRML;SG;2;PST
oynimaq	oynaydu	V;IPFV;PL;3;PRS
keymek	keygen	V;PRF;PL;3;PRS
qachilimaq	qachilimighanidi	V;PRF;SG;3;NEG;PST
külümsirimek	külümsirimigenidinglar	V;PRF;PL;2;NEG;PST
peseymek	peseymigenmen	V;PRF;SG;1;NEG;PRS
qalmaq	qalmidi	V;SG;3;NEG;PST
yémek	yémigen	V;PRF;PL;3;NEG;PRS
oqumaq	oqumaqchidi	V;INTEN;PL;3;PST
yötkimek	yötkigenmen	V;PRF;SG;1;PRS
oxshatmaq	oxshitiwatatti	V;PROG;SG;3;PST
sezmek	séziwatimen	V;PROG;SG;1;PRS
oxshatmaq	oxshatqanidim	V;PRF;SG;1;PST
bermek	bermidingiz	V;FRML;SG;2;NEG;PST
yatmaq	yétiwatatti	V;PROG;SG;3;PST
ölmek	ölgeniduq	V;PRF;PL;1;PST
ichmek	ichmigen	V;PRF;PL;3;NEG;PRS
bashlimaq	bashlimighanidingiz	V;PRF;FRML;SG;2;NEG;PST
külümsirimek	külümsirigensiz	V;PRF;FRML;SG;2;PRS
tingshimaq	tingshawatattim	V;PROG;SG;1;PST
yetküzmek	yetküzmekchidingiz	V;FRML;INTEN;SG;2;PST
dawamlashturmaq	dawamlashturatting	V;IPFV;SG;2;INFM;PST
oynimaq	oynawatattinglar	V;PROG;PL;2;PST
buzmaq	buzuwatimiz	V;PROG;PL;1;PRS
untumaq	untumaqchidinglar	V;INTEN;PL;2;PST
ishenmek	ishenmekchidi	V;INTEN;PL;3;PST
dawamlashturmaq	dawamlashturghansiler	V;PRF;PL;2;PRS
untumaq	untumidim	V;SG;1;NEG;PST
ögenmek	ögending	V;SG;2;INFM;PST
achmaq	achmiduq	V;PL;1;NEG;PST
qoymaq	qoyghaniding	V;PRF;SG;2;INFM;PST
turmaq	turuwatatti	V;PROG;SG;3;PST
körmek	köretti	V;IPFV;PL;3;PST
sorimaq	sorimaqchiduq	V;INTEN;PL;1;PST
agahlandurmaq	agahlanduratti	V;IPFV;PL;3;PST
oxshatmaq	oxshatmaqchidim	V;INTEN;SG;1;PST
tingshimaq	tingshimaqchidim	V;INTEN;SG;1;PST
epsuslanmaq	epsuslanmaqchidingiz	V;FRML;INTEN;SG;2;PST
untumaq	untuwatattim	V;PROG;SG;1;PST
naxsha éytmaq	naxsha éytmaqchimiz	V;INTEN;PL;1;PRS
yetküzmek	yetküzmigeniding	V;PRF;SG;2;NEG;INFM;PST
yaqturmaq	yaqturmighanidingiz	V;PRF;FRML;SG;2;NEG;PST
qaytmaq	qayturti	V;SG;3;PST
köydürmek	köydürmekchimiz	V;INTEN;PL;1;PRS
belgilimek	belgilimigeniduq	V;PRF;PL;1;NEG;PST
naxsha éytmaq	naxsha éytmidi	V;SG;3;NEG;PST
sétiwalmaq	sétiwaldim	V;SG;1;PST
yapmaq	yapattuq	V;IPFV;PL;1;PST
söymek	söygeniduq	V;PRF;PL;1;PST
ichmek	ichiwatatti	V;PROG;SG;3;PST
yapmaq	yapimen	V;IPFV;SG;1;PRS
tingshimaq	tingshawatidu	V;PROG;PL;3;PRS
yimek	yimidingiz	V;FRML;SG;2;NEG;PST
yaqturmaq	yaqturmaqchiduq	V;INTEN;PL;1;PST
démek	dégenidingiz	V;PRF;FRML;SG;2;PST
qilmaq	qiliwatattim	V;PROG;SG;1;PST
étirap qilmaq	étirap qilmighanidim	V;PRF;SG;1;NEG;PST
ölmek	ölmekchiding	V;INTEN;SG;2;INFM;PST
yaqturmaq	yaqturattuq	V;IPFV;PL;1;PST
peseymek	peseygenmen	V;PRF;SG;1;PRS
naxsha éytmaq	naxsha éytqanmiz	V;PRF;PL;1;PRS
heydimek	heydimigenidinglar	V;PRF;PL;2;NEG;PST
tapshuruwalmaq	tapshuruwalisen	V;IPFV;SG;2;INFM;PRS
körsetmek	körsitiwatatting	V;PROG;SG;2;INFM;PST
olturmaq	olturuwatattinglar	V;PROG;PL;2;PST
epsuslanmaq	epsuslinatti	V;IPFV;SG;3;PST
körünmek	körün'migenidingiz	V;PRF;FRML;SG;2;NEG;PST
tutmaq	tutmaqchiding	V;INTEN;SG;2;INFM;PST
