entši	enďissi	N;TRANS;PL
nain	naizõssi	N;TRANS;SG
tševäd	tševäinä	N;ESS;PL
tšäsi	tšäsi	N;NOM;SG
lumi	lunta	N;PRT;SG
üü	üit	N;PRT;PL
lintu	linnuu	N;GEN;SG
akkuna	akkunoil	N;AT+ESS;PL
mätši	mätšiika	N;COM;PL
seppä	sepält	N;AT+ABL;SG
varõz	varõhsõsõ	N;IN+ALL;SG
pää	päiz	N;IN+ESS;PL
ammaz	ampaasõssa	N;TERM;SG
entši	enďilt	N;AT+ABL;PL
susi	suõss	N;IN+ABL;SG
ammaz	ammassa	N;PRT;SG
kõrva	kõrvasõ	N;IN+ALL;SG
ilozuz	ilozuult	N;AT+ABL;SG
päivä	päiviina	N;ESS;PL
õźźa	õźźaa	N;PRT;SG
sipuli	sipulije	N;GEN;PL
võtii	võttimõd	N;NOM;PL
lintu	linnuz	N;IN+ESS;SG
pää	päďďe	N;GEN;PL
üü	üü	N;GEN;SG
tševäd	tševäďďeka	N;COM;PL
jalka	jalgaa	N;GEN;SG
opõnõ	opõzõllõssa	N;TERM;SG
lahsi	lahsijeka	N;COM;PL
staruha	staruhillõ	N;AT+ALL;PL
seppä	sepäll	N;AT+ESS;SG
akkuna	akkonoilõssa	N;TERM;PL
aika	aikoje	N;GEN;PL
mätši	mätšiit	N;PRT;PL
nain	naisiina	N;ESS;PL
itšä	itšiika	N;COM;PL
pää	päile	N;AT+ALL;PL
pää	päisessa	N;TERM;PL
vesi	vezissi	N;TRANS;PL
uhsi	uhsõlõ	N;AT+ALL;SG
tšäsi	tšäessi	N;TRANS;SG
jõtši	jõgõss	N;IN+ABL;SG
võtii	võttimõssi	N;TRANS;SG
aika	aigalõ	N;AT+ALL;SG
isä	isiit	N;PRT;PL
lammaz	lampaalt	N;AT+ABL;SG
lammaz	lammaz	N;NOM;SG
akkuna	akkunassi	N;TRANS;SG
leipä	leiväd	N;NOM;PL
aika	aigass	N;IN+ABL;SG
uhsi	uhsiit	N;PRT;PL
juusso	juussoilõ	N;AT+ALL;PL
kõrva	kõrviisõssa	N;TERM;PL
pää	päinä	N;ESS;PL
nain	naiziss	N;IN+ABL;PL
susi	suzill	N;AT+ESS;PL
tähti	tähtee	N;IN+ALL;SG
opõnõ	opõzillõssa	N;TERM;PL
kurtši	kurkõa	N;PRT;SG
lupa	lupaa	N;PRT;SG
tševäd	tševääss	N;IN+ABL;SG
kuu	kuult	N;AT+ABL;SG
jalka	jalgad	N;NOM;PL
leipä	leipoilõ	N;AT+ALL;PL
tütär	tütärtä	N;PRT;SG
varõz	varõhsõõ	N;GEN;SG
vesi	vezile	N;AT+ALL;PL
meez	meheďďeka	N;COM;PL
õźźa	õźďissi	N;TRANS;PL
ilozuz	ilozuiss	N;IN+ABL;PL
luu	luhõõ	N;IN+ALL;SG
kuu	kuiz	N;IN+ESS;PL
tševäd	tševää	N;GEN;SG
koira	koirõina	N;ESS;PL
koira	koiraa	N;GEN;SG
luu	luissa	N;TERM;PL
õlud	õluiz	N;IN+ESS;PL
kõrsi	kõrrõz	N;IN+ESS;SG
meez	meheise	N;IN+ALL;PL
õlud	õluulõ	N;AT+ALL;SG
susi	susije	N;GEN;PL
võtii	võttimill	N;AT+ESS;PL
meez	meheit	N;PRT;PL
ilozuz	ilozuina	N;ESS;PL
jalka	jalka	N;NOM;SG
jää	jääkä	N;COM;SG
meez	meheilt	N;AT+ABL;PL
sõzar	sõsarõõ	N;IN+ALL;SG
õźźa	õźall	N;AT+ESS;SG
velli	velliss	N;IN+ABL;PL
kõrva	kõrviisõ	N;IN+ALL;PL
kurtši	kurďiss	N;IN+ABL;PL
maa	maat	N;PRT;SG
õźźa	õźďiina	N;ESS;PL
akkuna	akkunalt	N;AT+ABL;SG
luu	luuss	N;IN+ABL;SG
opõnõ	opõzissi	N;TRANS;PL
üü	üüka	N;COM;SG
silmä	silmässi	N;TRANS;SG
kõrsi	kõrziss	N;IN+ABL;PL
tšivi	tšivell	N;AT+ESS;SG
töö	töiz	N;IN+ESS;PL
varõz	varõhsije	N;GEN;PL
silmä	silmä	N;NOM;PL
lintu	lintuilõ	N;AT+ALL;PL
itšä	itšää	N;PRT;SG
staruha	staruhaz	N;IN+ESS;SG
vesi	veziss	N;IN+ABL;PL
töö	töösessa	N;TERM;SG
ilozuz	ilozuilõ	N;AT+ALL;PL
lumi	lumissi	N;TRANS;PL
tähti	tähdill	N;AT+ESS;PL
luu	luise	N;IN+ALL;PL
võtii	võttimiisõ	N;IN+ALL;PL
tšivi	tšivessi	N;TRANS;SG
vesi	veelt	N;AT+ABL;SG
silmä	silmält	N;AT+ABL;SG
lahsi	lahsije	N;GEN;PL
lammaz	lampaaka	N;COM;SG
juusso	juusoka	N;COM;SG
juusso	juusona	N;ESS;SG
leipä	leipoiz	N;IN+ESS;PL
meez	meheissi	N;TRANS;PL
nain	naizõlõssa	N;TERM;SG
opõnõ	opõzõlt	N;AT+ABL;SG
seppä	sepäss	N;IN+ABL;SG
sipuli	sipulilõssa	N;TERM;SG
akkuna	akkunoilt	N;AT+ABL;PL
tševäd	tševäässi	N;TRANS;SG
üü	üült	N;AT+ABL;SG
aika	aigalt	N;AT+ABL;SG
seppä	seppiit	N;PRT;PL
kurtši	kurgõssi	N;TRANS;SG
üü	üiz	N;IN+ESS;PL
karu	karussi	N;TRANS;SG
staruha	staruhalt	N;AT+ABL;SG
lumi	lumõss	N;IN+ABL;SG
lupa	lupõil	N;AT+ESS;PL
seppä	seppiz	N;IN+ESS;PL
aika	aigoika	N;COM;PL
üü	üďďe	N;GEN;PL
süä	süämmez	N;IN+ESS;SG
pää	pähää	N;IN+ALL;SG
sipuli	sipulii	N;IN+ALL;SG
ilozuz	ilozuulõ	N;AT+ALL;SG
juusso	juussoit	N;PRT;PL
tütär	tüttäriz	N;IN+ESS;PL
sõzar	sõsarille	N;AT+ALL;PL
tšivi	tšiveka	N;COM;SG
staruha	staruhaasõ	N;IN+ALL;SG
tširjai	tširjait	N;PRT;SG
kuu	kuilõssa	N;TERM;PL
päivä	päivää	N;PRT;SG
juusso	juussoika	N;COM;PL
varõz	varõhsiiz	N;IN+ESS;PL
jõtši	jõtšije	N;GEN;PL
kõrva	kõrvaa	N;PRT;SG
seppä	sepile	N;AT+ALL;PL
emä	emää	N;PRT;SG
meez	meheisessa	N;TERM;PL
varõz	varõz	N;NOM;SG
leipä	leivält	N;AT+ABL;SG
susi	suõll	N;AT+ESS;SG
lintu	linnulõssa	N;TERM;SG
akkuna	akkunana	N;ESS;SG
kõrva	kõrvasõssa	N;TERM;SG
jalka	jalgoilt	N;AT+ABL;PL
kõrsi	kõrrõõ	N;GEN;SG
vesi	veenä	N;ESS;SG
tšivi	tšiveä	N;PRT;SG
tševäd	tševääz	N;IN+ESS;SG
silmä	silmissi	N;TRANS;PL
itšä	iäll	N;AT+ESS;SG
sõbra	sõbraka	N;COM;SG
võtii	võttimillõ	N;AT+ALL;PL
nain	naisõõ	N;IN+ALL;SG
jää	jäikä	N;COM;PL
seppä	seppänä	N;ESS;SG
entši	enďelessa	N;TERM;SG
karu	karuiss	N;IN+ABL;PL
isä	izäd	N;NOM;PL
tšivi	tšivess	N;IN+ABL;SG
üü	üil	N;AT+ESS;PL
jõtši	jõďilt	N;AT+ABL;PL
sõbra	sõbrõissi	N;TRANS;PL
kuu	kuissi	N;TRANS;PL
lupa	lupõit	N;PRT;PL
emä	emäd	N;NOM;PL
akkuna	akkunoilõ	N;AT+ALL;PL
mätši	mätšeä	N;PRT;SG
opõnõ	opõzõka	N;COM;SG
staruha	staruhallõ	N;AT+ALL;SG
päivä	päiväse	N;IN+ALL;SG
võtii	võtiit	N;PRT;SG
staruha	staruhaka	N;COM;SG
uhsi	uhsiz	N;IN+ESS;PL
aika	aikaa	N;PRT;SG
tähti	tähdile	N;AT+ALL;PL
jalka	jalgalõssa	N;TERM;SG
süä	süämmeessa	N;TERM;SG
jää	jääss	N;IN+ABL;SG
opõnõ	opõziz	N;IN+ESS;PL
tšivi	tšiviiz	N;IN+ESS;PL
isä	izälessa	N;TERM;SG
õlud	õluina	N;ESS;PL
meez	mehese	N;IN+ALL;SG
süä	süämmije	N;GEN;PL
koira	koirõlt	N;AT+ABL;PL
jalka	jalgoina	N;ESS;PL
ilozuz	ilozuilta	N;AT+ABL;PL
vesi	vezill	N;AT+ESS;PL
sõzar	sõsarõllõ	N;AT+ALL;SG
võtii	võttimiisõssa	N;TERM;PL
leipä	leipoilt	N;AT+ABL;PL
tširjai	tširjaimijeka	N;COM;PL
kõrva	kõrvassi	N;TRANS;SG
töö	töössi	N;TRANS;SG
leipä	leiväle	N;AT+ALL;SG
kõrsi	kõrzilõssa	N;TERM;PL
maa	maass	N;IN+ABL;SG
kurtši	kurgõlt	N;AT+ABL;SG
silmä	silmiit	N;PRT;PL
tševäd	tševäält	N;AT+ABL;SG
lammaz	lampaina	N;ESS;PL
õźźa	õźďiz	N;IN+ESS;PL
tševäd	tševättä	N;PRT;SG
ammaz	ampaa	N;GEN;SG
emä	emälessa	N;TERM;SG
lintu	linnuss	N;IN+ABL;SG
seppä	sepää	N;GEN;SG
lupa	luvalõ	N;AT+ALL;SG
lahsi	lahsiisõssa	N;TERM;PL
leipä	leivää	N;GEN;SG
tähti	tähdilt	N;AT+ABL;PL
õźźa	õźźasõ	N;IN+ALL;SG
isä	izissi	N;TRANS;PL
lintu	lintuit	N;PRT;PL
kõrsi	kõrzill	N;AT+ESS;PL
tšäsi	tšäsiit	N;PRT;PL
tütär	tüttärissi	N;TRANS;PL
ammaz	ampaiz	N;IN+ESS;PL
varõz	varõhsõnna	N;ESS;SG
lahsi	lahsiss	N;IN+ABL;PL
luu	luiss	N;IN+ABL;PL
luu	luilt	N;AT+ABL;PL
võtii	võttimõka	N;COM;SG
uhsi	uhsi	N;NOM;SG
varõz	varõhsõz	N;IN+ESS;SG
sõzar	sõsarõka	N;COM;SG
sipuli	sipuliiss	N;IN+ABL;PL
pää	päässi	N;TRANS;SG
karu	karuissi	N;TRANS;PL
velli	velliise	N;IN+ALL;PL
ammaz	ampailt	N;AT+ABL;PL
võtii	võttimõll	N;AT+ESS;SG
varõz	varõhsõllõ	N;AT+ALL;SG
mätši	mäďill	N;AT+ESS;PL
üü	üile	N;AT+ALL;PL
lammaz	lampaass	N;IN+ABL;SG
lammaz	lampaďďe	N;GEN;PL
tütär	tüttäriit	N;PRT;PL
velli	vellessi	N;TRANS;SG
võtii	võttimilt	N;AT+ABL;PL
tširjai	tširjai	N;NOM;SG
sõbra	sõbra	N;NOM;SG
karu	karuina	N;ESS;PL
päivä	päivää	N;GEN;SG
velli	vellenä	N;ESS;SG
uhsi	uhsõna	N;ESS;SG
lahsi	lahsõõ	N;IN+ALL;SG
süä	süämmee	N;GEN;SG
õlud	õluisõssa	N;TERM;PL
emä	emije	N;GEN;PL
emä	emiit	N;PRT;PL
entši	enďell	N;AT+ESS;SG
pää	päilt	N;AT+ABL;PL
entši	enďile	N;AT+ALL;PL
silmä	silmiisässa	N;TERM;PL
juusso	juusolõ	N;AT+ALL;SG
kuu	kuulõssa	N;TERM;SG
tütär	tüttärelle	N;AT+ALL;SG
