alonõ	alotsõhe	N;IN+ALL;SG
silm	.silmä	N;IN+ALL;SG
täi	.täihe	N;IN+ALL;SG
herneh	herneh	N;NOM;SG
tarõ	tarri	N;PRT;PL
kerge	kerget	N;PRT;SG
vari	.varjo	N;IN+ALL;SG
tükk	tükke	N;IN+ALL;PL
kuu	kuu	N;NOM;SG
talo	tallõ	N;GEN;PL
täüs'	täüt	N;PRT;SG
kannõl'	kandlidõ	N;GEN;PL
kogõr	kogrõ	N;GEN;SG
tarõ	tarõ	N;GEN;SG
tükk	tükkü	N;IN+ALL;SG
aig	ao	N;GEN;SG
silm	silmä	N;GEN;SG
ehitüs	ehitüisi	N;PRT;PL
sõda	sõto	N;PRT;PL
rits'kas	rits'kilõ	N;ALL;PL
kubõl	kubla	N;GEN;SG
väits	.väitsi	N;PRT;PL
kanarik	kanarikkõ	N;GEN;PL
aig	.aigõ	N;GEN;PL
üü:	öid	N;PRT;PL
tükk	tükke	N;PRT;PL
jalg	.jalga	N;PRT;SG
kerge	kergile	N;ALL;PL
laiõh	laiõh	N;NOM;SG
kana	kana	N;NOM;SG
pini	pinne	N;PRT;PL
alomanõ	alomast	N;PRT;SG
alomanõ	alomastõ	N;IN+ALL;SG
kotus	kotus	N;NOM;SG
tarõ	tarilõ	N;ALL;PL
asõq	asõmõhe	N;IN+ALL;SG
pini	pini	N;GEN;SG
kommõq	kombihe	N;IN+ALL;PL
kask	kask	N;NOM;SG
pini	pinne	N;IN+ALL;PL
vari	var'o	N;GEN;SG
kannõl'	kandlõhe	N;IN+ALL;SG
kuu:l'	kuu:l'	N;NOM;SG
kannõl'	kandlilõ	N;ALL;PL
kuld	kuld	N;NOM;SG
tarõ	tarrõ	N;PRT;SG
üü:	.öihe	N;IN+ALL;PL
asi	.asja	N;PRT;SG
kask	.kaskihe	N;IN+ALL;PL
hõrak	hõrakat	N;PRT;SG
kerge	kergit	N;PRT;PL
herneh	hernihe	N;IN+ALL;PL
kuu:l'	kuu:li	N;IN+ALL;SG
nagõl	naglolõ	N;ALL;PL
võrokõnõ	võrokõisihe	N;IN+ALL;PL
igä	ikile	N;ALL;PL
kuldnõ	kuldsõ	N;GEN;SG
kii:l'	kii:li	N;IN+ALL;PL
üü:	üü:he	N;IN+ALL;SG
ehitüs	ehitüst	N;PRT;SG
kii:l'	keelile	N;ALL;PL
hammas	hammas	N;NOM;SG
.suhvli	.suhvli	N;NOM;SG
puhm	puhmõ	N;GEN;PL
kanarik	kanarikkõ	N;IN+ALL;PL
läteq	lättit	N;PRT;PL
särg'	.särgi	N;IN+ALL;PL
.suhvli	.suhvlihe	N;IN+ALL;PL
igä	ikki	N;IN+ALL;PL
kanarik	kanarigu	N;GEN;SG
tervüs	tervüid	N;PRT;PL
käsi	käsi	N;NOM;SG
tütär'	tütrit	N;PRT;PL
kask	.kaskat	N;PRT;SG
nagõl	nagla	N;GEN;SG
sõda	sõda	N;NOM;SG
laiõh	laidõhe	N;IN+ALL;SG
elläi	eläjä	N;GEN;SG
tütär'	tütrihe	N;IN+ALL;PL
jalg	.jalgo	N;IN+ALL;PL
nagõl	nagõl	N;NOM;SG
kand	.kandõ	N;IN+ALL;PL
makõ	makõ	N;NOM;SG
nagõl	.naklo	N;GEN;PL
kii:l'	kii:l'	N;NOM;SG
kuu	.kuihõ	N;IN+ALL;PL
kogõr	.kokrõ	N;IN+ALL;SG
tervüs	tervüide	N;GEN;PL
hain	haina	N;IN+ALL;SG
tükk	tükü	N;GEN;SG
repän'	rebäside	N;GEN;PL
tarõ	tarri	N;GEN;PL
kogõr	kogrilõ	N;ALL;PL
kana	kanno	N;PRT;PL
kannõl'	kannõl'	N;NOM;SG
makõ	makõ	N;GEN;SG
väits	.väitsi	N;GEN;PL
herneh	hernit	N;PRT;PL
igä	ikkä	N;IN+ALL;SG
kotus	kotussõhe	N;IN+ALL;SG
laiõh	laidihe	N;IN+ALL;PL
kanarik	kanarikku	N;IN+ALL;SG
vari	vari	N;NOM;SG
