gaˀabi	bigaˀabi	V;PFV
u+siŏba	gúsiŏba	V;POT
u+kîʔ	bakîʔ	V;PFV
a+zhuuˀn	razhuuˀn	V;HAB
iuˀuyi	riuˀuyi	V;HAB
iun=buaˀa	riun=buaˀa	V;HAB
gaaˀ	gígaaˀ	V;POT
shăla	gíshăla	V;POT
bwi	rbwi	V;HAB
iaaˀbi	riaaˀbi	V;HAB
zaka	guzaka	V;PFV
asi	gâsi	V;POT
ieˀetu	dxîeˀetu	V;POT
uˀuda	gûˀuda	V;POT
ñiiˀdzhu	guñiiˀdzhu	V;PFV
iuuˀ=stoˀo	biuuˀ=stoˀo	V;PFV
utshi	bitshi	V;PFV
u+g+uuˀyi	gúuuˀyi	V;POT
bishi	gubishi	V;PFV
u+txîʔtsi	rutxîʔtsi	V;HAB
biˀibí	bibiˀibí	V;PFV
uʔla	ruʔla	V;HAB
txeza	rtxeza	V;HAB
u+sa+gaˀald=yu	gúsagaˀald=yu	V;POT
u+txuʔă	gútxuʔă	V;POT
u+s+iăba	rusiăba	V;HAB
dxiˀizi	gudxiˀizi	V;PFV
u+z+aˀa	ruzaˀa	V;HAB
reˀen=dxesa	rreˀen=dxesa	V;HAB
u+sa+ntxĕ	gúsantxĕ	V;POT
giˀishú	gígiˀishú	V;POT
zaˀabi	saˀabi	V;POT
u+la	bala	V;PFV
a+dzhĕla	gádzhĕla	V;POT
u+taʔ	bataʔ	V;PFV
bwidzhi	kwĭdzhi	V;POT
fiitxi	gufiitxi	V;PFV
u+sa+zhidzí	rusazhidzí	V;HAB
baaˀba	gíbaaˀba	V;POT
sheʔla	gísheʔla	V;POT
u+zoˀoba	ruzoˀoba	V;HAB
u+sa+ñiiˀdzhu	gúsañiiˀdzhu	V;POT
u+txooˀ	gútxooˀ	V;POT
u+s+eˀewu	baseˀewu	V;PFV
gaˀatsi	bigaˀatsi	V;PFV
a+rooˀ	gárooˀ	V;POT
aaˀyi	raaˀyi	V;HAB
bwĕʔe	gulĕʔe	V;PFV
yasa	ryasa	V;HAB
zhaˀata	bizhaˀata	V;PFV
u+tyăaˀa	gútyăaˀa	V;POT
gaˀazhu	bigaˀazhu	V;PFV
rooˀ	gurooˀ	V;PFV
u+tubí	rutubí	V;HAB
eeˀ	guaaˀ	V;PFV
u+sa+zhunga	basazhunga	V;PFV
daˀawu	bidaˀawu	V;PFV
guuˀ	rguuˀ	V;HAB
uˀuyi=dzhiˀidzhi	ruˀuyi=dzhiˀidzhi	V;HAB
u+shi=rin	rushi=rin	V;HAB
abí	gudabí	V;PFV
gaˀatsi	gígaˀatsi	V;POT
ieˀew	dxîeˀew	V;POT
u+g+aza	baaza	V;PFV
dzhiˀitshĭ	gudzhiˀitshĭ	V;PFV
gaaˀ	bigaaˀ	V;PFV
a+tasa	gátasa	V;POT
a+dziiˀn	badziiˀn	V;PFV
reˀen=dxesa	bireˀen=dxesa	V;PFV
sheʔla	rsheʔla	V;HAB
u+sa+dzhaga	basadzhaga	V;PFV
îˀi	rîˀi	V;HAB
zhupi	shŭpi	V;POT
dzhishi=zhgasi	gudzhishi=zhgasi	V;PFV
asa	gâsa	V;POT
u+sa+gĭʔi	rusagĭʔi	V;HAB
u+sa+ra	gúsara	V;POT
laʔ	rlaʔ	V;HAB
u+sa+g+uaˀa	basaguaˀa	V;PFV
eeˀ	reeˀ	V;HAB
zhoˀoba	gízhoˀoba	V;POT
tăaˀa	gutăaˀa	V;PFV
dxiˀibi	bidxiˀibi	V;PFV
dzhuuˀyi	rdzhuuˀyi	V;HAB
ioʔ	bioʔ	V;PFV
u+ga	baga	V;PFV
naˀ aza	gínaˀaza	V;POT
ñiiˀdzhu	nñĭdzhu	V;POT
u+kăʔa	bakăʔa	V;PFV
txaˀa	rtxaˀa	V;HAB
u+g+aku	gúaku	V;POT
ziˀi	guziˀi	V;PFV
a	gâ	V;POT
dzhishi=zhgasi	rdzhishi=zhgasi	V;HAB
u+su	gúsu	V;POT
reʔ/riaʔ	bireʔ/riaʔ	V;PFV
dusha	rdusha	V;HAB
gaˀabi	gudaˀabi	V;PFV
a+bĭiˀ	rabĭiˀ	V;HAB
ieˀedu	bieˀedu	V;PFV
a+dzhaga	gádzhaga	V;POT
dxiˀizhu	rdxiˀizhu	V;HAB
u+tyăaˀa	batyăaˀa	V;PFV
ropá	biropá	V;PFV
abi	gâbi	V;POT
diăaˀa	rdiăaˀa	V;HAB
uˀun	biˀin	V;PFV
baaˀn	kwăn	V;POT
gĭʔi	bigĭʔi	V;PFV
ruuˀga	guruuˀga	V;PFV
u+tshăʔa	batshăʔa	V;PFV
u+zeʔ	ruzeʔ	V;HAB
ban	gíban	V;POT
u+txuʔă	batxuʔă	V;PFV
a	guya	V;PFV
zĭĭn	rzĭĭn	V;HAB
dxizhi	rdxizhi	V;HAB
ri=gunâʔla	rri=gunâʔla	V;HAB
u+saˀabí	basaˀabí	V;PFV
u+tsiyi	rutsiyi	V;HAB
u+ñiˀibi	ruñiˀibi	V;HAB
a+bwĕʔe	rabwĕʔe	V;HAB
u+răʔa	gúrăʔa	V;POT
iăla	dxîăla	V;POT
u+zhidzí	ruzhidzí	V;HAB
u+g+aza	gúaza	V;POT
u+lăba	balăba	V;PFV
u+yaˀan	gúyaˀan	V;POT
kayí	bikayí	V;PFV
u+txeldá	gútxeldá	V;POT
iaka	biaka	V;PFV
batxi	kwătxi	V;POT
uta	bweˀetu	V;PFV
shiˀidxi	rshiˀidxi	V;HAB
baˀagú	rbaˀagú	V;HAB
u+shoˀoba	gúshoˀoba	V;POT
a+yidzhi	gáyidzhi	V;POT
bwĕza	rbwĕza	V;HAB
a+tădzhu	ratădzhu	V;HAB
ga	rga	V;HAB
zhiˀin	rzhiˀin	V;HAB
guˀudzí	biguˀudzí	V;PFV
tuyí	rtuyí	V;HAB
u+sa+ra	rusara	V;HAB
u+tusha	gútusha	V;POT
gŭʔun	kŭʔun	V;POT
u+sa+g+uˀula	basaguˀula	V;PFV
dxipa	rdxipa	V;HAB
năba	rnăba	V;HAB
u+tshaʔ	gútshaʔ	V;POT
dxiˀida	rdxiˀida	V;HAB
tann	gítann	V;POT
iuyi	biuyi	V;PFV
zĭĭn	guzĭĭn	V;PFV
dxishi	txĭshi	V;POT
a+zhuˀuyi	gázhuˀuyi	V;POT
u+kaˀabi	gúkaˀabi	V;POT
dxaʔ	bidxaʔ	V;PFV
bwîˀi	rbwîˀi	V;HAB
txâˀan	gítxâˀan	V;POT
a+byetxi=garĭ	gubyetxi=garĭ	V;PFV
a+doˀoba	radoˀoba	V;HAB
u+g+aku	rugaku	V;HAB
dxîʔyí	gudxîʔyí	V;PFV
u+zhuʔn	gúzhuʔn	V;POT
ieˀew	bieˀew	V;PFV
u+s+iaʔn	basiaʔn	V;PFV
txaˀa	gítxaˀa	V;POT
u+dziˀiyi	gúdziˀiyi	V;POT
a+tădzhu	batădzhu	V;PFV
iaˀatshu	riaˀatshu	V;HAB
zhuˀubí=dxa	bizhuˀubí=dxa	V;PFV
dusha	tŭsha	V;POT
ĭnn	rĭnn	V;HAB
u+zaʔ	gúzaʔ	V;POT
u+kwiˀidzi	rukwiˀidzi	V;HAB
u+sházhí	basházhí	V;PFV
u+s+iaˀatshu	gúsiaˀatshu	V;POT
zhiˀi=duʔ	gízhiˀi=duʔ	V;POT
u+s+iaˀatshu	rusiaˀatshu	V;HAB
iulda	riulda	V;HAB
dxa	rdxa	V;HAB
yaˀa	ryaˀa	V;HAB
u+kâʔ	r/ukâʔ	V;HAB
a+zaaˀ	gázaaˀ	V;POT
dalá	gudalá	V;PFV
a+zaaˀ	bazaaˀ	V;PFV
u+kidzí	bakidzí	V;PFV
u+sa+gaˀald=yu	rusagaˀald=yu	V;HAB
yubí	biyubí	V;PFV
u+tusha	batusha	V;PFV
zhiʔ	bizhiʔ	V;PFV
gaˀabi	kâˀabi	V;POT
iăla	riăla	V;HAB
yiˀibí	ryiˀibí	V;HAB
a+guʔla	gáguʔla	V;POT
tann	gutann	V;PFV
u+s+iăba	gúsiăba	V;POT
shiʔ	rshiʔ	V;HAB
uta	ruta	V;HAB
dzhagá	bidzhagá	V;PFV
shiˀidxi	gíshiˀidxi	V;POT
nisa	gunisa	V;PFV
u+z+uʔyí	gúzuʔyí	V;POT
u+saka=zĭ	gúsaka=zĭ	V;POT
dxiʔtsi	bidxiʔtsi	V;PFV
yaˀa	tshâˀa	V;POT
a+dziiˀn	radziiˀn	V;HAB
u+ga	gúga	V;POT
dxishi	rdxishi	V;HAB
zaka=zĭ	guzaka=zĭ	V;PFV
zhubí=dxa	shŭbí=dxa	V;POT
u+ldâʔ	baldâʔ	V;PFV
zaka	săka	V;POT
a+byetxi=garĭ	gâbyetxi=garĭ	V;POT
u+shoˀoba	bashoˀoba	V;PFV
iuʔn	biuʔn	V;PFV
u+tshibi	rutshibi	V;HAB
yaˀa=lo	ryaˀa=lo	V;HAB
u+txîʔtsi	batxîʔtsi	V;PFV
yădzhu	biyădzhu	V;PFV
u+sa	gúsa	V;POT
unn	runn	V;HAB
gooˀba	gudooˀba	V;PFV
u+sa+ldaʔ	basaldaʔ	V;PFV
a+zu	razu	V;HAB
u+kîʔ	rukîʔ	V;HAB
taˀa=nĭku	gítaˀa=nĭku	V;POT
