khombisa	ngikhombise	V;SG;1;PST+RCT
nzeka	ngenzeke	V;SG;1;PST+RCT
sala	ngisala	V;SG;1;PRS
thanda	ngizothanda	V;SG;1;FUT+IMMED
cula	ngicula	V;SG;1;PRS
dlala	ngidlala	V;SG;1;PRS
bona	ngibone	V;SG;1;PST+RCT
chasisa	ngizochasisa	V;SG;1;FUT+IMMED
funa	ngiyofuna	V;SG;1;FUT
fundisa	ngizofundisa	V;SG;1;FUT+IMMED
ngena	ngingena	V;SG;1;PRS
mamatheka	ngiyomamatheka	V;SG;1;FUT
qonda	ngizoqonda	V;SG;1;FUT+IMMED
bhala	ngiyobhala	V;SG;1;FUT
cula	ngiyocula	V;SG;1;FUT
qabula	ngiyoqabula	V;SG;1;FUT
hleka	ngizohleka	V;SG;1;FUT+IMMED
khohlwa	ngizokhohlwa	V;SG;1;FUT+IMMED
thuma	ngathuma	V;SG;1;PST+RMT
phuka	ngizokwephuka	V;SG;1;FUT+IMMED
fundisa	ngifundise	V;SG;1;PST+RCT
pheka	ngipheke	V;SG;1;PST+RCT
nzeka	ngizokwenzeka	V;SG;1;FUT+IMMED
phinda	ngiphinde	V;SG;1;PST+RCT
qabula	ngiqabula	V;SG;1;PRS
sala	ngisale	V;SG;1;PST+RCT
nda	ngiyokwanda	V;SG;1;FUT
lala	ngiyalala	V;SG;1;PRS
khumbula	ngizokhumbula	V;SG;1;FUT+IMMED
lala	ngilale	V;SG;1;PST+RCT
fa	ngife	V;SG;1;PST+RCT
shayela	ngashayela	V;SG;1;PST+RMT
vuma	ngivume	V;SG;1;PST+RCT
nqoba	nginqobe	V;SG;1;PST+RCT
sho	ngiyosho	V;SG;1;FUT
thengisa	ngithengise	V;SG;1;PST+RCT
cula	ngicule	V;SG;1;PST+RCT
thatha	ngiyothatha	V;SG;1;FUT
lala phansi	ngizolala phansi	V;SG;1;FUT+IMMED
mema	ngiyomema	V;SG;1;FUT
vula	ngizovula	V;SG;1;FUT+IMMED
za	ngeza	V;SG;1;PST+RMT
fa	ngiyokufa	V;SG;1;FUT
hlisa	ngehlisa	V;SG;1;PRS
qabula	ngiqabule	V;SG;1;PST+RCT
phuza	ngiphuze	V;SG;1;PST+RCT
bheka	ngiyobheka	V;SG;1;FUT
qonda	ngaqonda	V;SG;1;PST+RMT
bulala	ngibulala	V;SG;1;PRS
thola	ngithole	V;SG;1;PST+RCT
nika	ngizonika	V;SG;1;FUT+IMMED
phuma	ngizophuma	V;SG;1;FUT+IMMED
za	ngizile	V;SG;1;PST+RCT
hlala phansi	ngahlala phansi	V;SG;1;PST+RMT
gijima	ngiyogijima	V;SG;1;FUT
khohlwa	ngiyokhohlwa	V;SG;1;FUT
nqoba	ngizonqoba	V;SG;1;FUT+IMMED
nzeka	nganzeka	V;SG;1;PST+RMT
cabanga	ngacabanga	V;SG;1;PST+RMT
funda	ngifunde	V;SG;1;PST+RCT
zisa	ngazisa	V;SG;1;PST+RMT
hlangana	ngizohlangana	V;SG;1;FUT+IMMED
funda	ngafunda	V;SG;1;PST+RMT
lwa	ngizokulwa	V;SG;1;FUT+IMMED
shayela	ngizoshayela	V;SG;1;FUT+IMMED
thengisa	ngathengisa	V;SG;1;PST+RMT
funa	ngafuna	V;SG;1;PST+RMT
thuma	ngithuma	V;SG;1;PRS
cabanga	ngiyocabanga	V;SG;1;FUT
chasisa	ngiyochasisa	V;SG;1;FUT
lala phansi	ngilala phansi	V;SG;1;PRS
khuluma	ngakhuluma	V;SG;1;PST+RMT
sho	ngasho	V;SG;1;PST+RMT
zisa	ngiyazise	V;SG;1;PST+RCT
thuma	ngizothuma	V;SG;1;FUT+IMMED
naka	nganaka	V;SG;1;PST+RMT
phuka	ngiyephuka	V;SG;1;PRS
lahlekelwa	ngalahlekelwa	V;SG;1;PST+RMT
